- templates/master/00-master/openstack/files/openstack-haproxy.yaml
- templates/master/00-master/ovirt/files/ovirt-haproxy.yaml
This PR updates OpenStack and Ovirt HAProxy static pod manifest to enable reading API LB backend details from Kubernetes instead of _etcd-server-ssl._tcp SRV.
Original baremetal PR: https://github.com/openshift/machine-config-operator/pull/1574
> Bug 1825823: Add support for reading API LB backends from KUBE-API for OpenStack and Ovirt

- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/helpers.go
Fixes #1822750 (https://bugzilla.redhat.com/show_bug.cgi?id=1822750)
cherry-pick of https://github.com/openshift/machine-config-operator/pull/1637
A map doesn't guarantee order when we are creating new ignitions.
When we update the image CR with blocked registries, the ctrcfg
controller needs to update two files registries.conf and policy.json.
Since we get an update from the image CR about every 20 mins, we compare
the semantics to see if anything has changed. But since the order is not
guaranteed, the controller might think that the semantics is not equal
even if nothing in the data changed. Hence another MC is created, and
everytime we get an update the MC applied to the nodes keeps flipping
back and forth for the 2 …
> [release-4.3] Bug 1822750: [ctrcfg controller] Use a struct array instead of map when creating new ignitions

- pkg/server/api.go
Coming from an user request but it makes sense as we (OpenShift) use and control
that port.
It's not fully clear to me if we _can_ drop tls < 1.2 but I'm leaning toward so for security reasons
@cgwalters also ptal
> Bug 1823852: pkg/server: disable weak TLS versions

- pkg/controller/template/render.go
- pkg/controller/template/render_test.go
- pkg/operator/sync.go
cloudConfig is now generated by kube_cloud_config controller for all supported
platforms. Controller generates kube-cloud-config ConfigMap in openshift-config-managed
namespace where cloud.conf key is stored.
Links:
- https://github.com/openshift/enhancements/blob/master/enhancements/installer/aws-custom-region-and-endpoints.md
- https://github.com/openshift/api/pull/599
- https://github.com/openshift/api/pull/621
> Bug 1825948: cloudConfig: read cloud Config from openshift-config-managed/kube-cloud-config ConfigMap

- Makefile
When an MCO e2e test fails, we keep running all the others till the end.
That has the shortcoming of not providing the journal for any test that
failed. This has been found in https://bugzilla.redhat.com/show_bug.cgi?id=1827712
The bug itself needs journal to debug.
Adding -failfast will halt test execution at the first failure which I think it's
generally better for e2e-op as we get a fast feedback from tests.
To further debug that BZ tho we'd need to capture the last boot as well which I'll
fix in a follow up PR to openshift/release (https://github.com/openshift/release/pull/8558)
> Makefile: add -failfast to e2e-op

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
with a new version of cri-o, we are going to cleanup containers when a node reboots (which we detect when a tmpfs file is removed), and cleanup images when a node upgraded (which we detect how we used to: persistent version file out of date)
This PR changes where cri-o looks for those files. These match the upstream defaults, so when we move to drop in files, we won't need to specify these
containers are cleared on node reboot, images are cleared when we bump a cri-o minor version (1.17->1.18)
> Bug 1826896: [release-4.4] crio: set version-file{,-persist} correctly

- pkg/controller/template/render.go
- pkg/operator/sync.go
Baremetal IPI doesn't use a cloud config, and [this change](https://github.com/openshift/machine-config-operator/pull/1658) is now
breaking CI:
```
level=error msg="Cluster operator machine-config Degraded is True with
RenderConfigFailed: Unable to apply 0.0.1-2020-04-26-200215:
openshift-config-managed/kube-cloud-config configmap is required on
platform BareMetal but not found: configmap \"kube-cloud-config\" not
found"
```
> Bug 1828106: cloudConfig: remove bare metal from platforms that require a cloud conifg

- templates/master/01-master-kubelet/_base/units/kubelet.yaml
- templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Bumping the kubelet log level to 4 to aid in debugging an issue.
> Bug 1828622: bumps kubelet log level to 4

- pkg/daemon/update.go
Install additional RT kernel package if any shipped
as part of update in machine-os-content
Also some code cleanup to simplify RT kernel update logic
> Bug 1827143: daemon: consider addition of an RT kernel package as update

- templates/master/00-master/baremetal/files/NetworkManager-resolv-prepender.yaml
- templates/worker/00-worker/baremetal/files/NetworkManager-resolv-prepender.yaml
This PR prevents the pods from complaining about the nameserver limits
exceeded:
Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.0.128.6 10.0.128.12 10.0.128.11 (207 times)
Original openstack PR: #1573 
> Bug 1825909: baremetal - Limit the number of nameservers to 3

- manifests/machineconfig.crd.yaml
- pkg/operator/assets/bindata.go
TL;DR; if somebody provides fields like disks and other we don't specify in the crd
those get dropped and can cause whatever issue you can think of.
I think adding that will preserve the unknown field.
holding pending tests
> [release-4.4] Bug 1829651: MC CRD: preserve unknown fields

- pkg/daemon/update.go
Fixes bz#1785219 with the simplest approach.
Since this is a corner case [1] which probably few people will hit, this is the simplest approach to fix the issue.
[1] RHEL7.6 + audit enabled + logger not supporting --journald flag
> Bug 1785219: [release-4.2] Discard audit messages from journald

- templates/common/_base/units/machine-config-daemon-firstboot-v42.service
This is aiming to fix:
https://bugzilla.redhat.com/show_bug.cgi?id=1829642
AKA
https://github.com/openshift/machine-config-operator/pull/1215#issuecomment-622081019
Basically we have our systemd units dynamically differentiate between
"4.2" and "4.3 or above" by looking at the aleph version.
---
In the beginning, we had this concept of `pivot.service` whose whole job was to pull a new `machine-os-content` and reboot, running `Before=kubelet.service`.
More: [OSUpgrades](https://github.com/openshift/machine-config-operator/blob/master/docs/OSUpgrades.md).
That was simple, and worked well!  Life was good.  Everyone was relaxing on the beach.
Then, we needed to [handle kernel arguments](https://github.com/openshift/installer/pull/1392) (specifically adding `nosmt`).
But a core problem here is …
> Bug 1829642: templates: Add a special machine-config-daemon-firstboot-v42.service

- templates/common/_base/units/machine-config-daemon-firstboot-v42.service
Backport of #1706
```
This is aiming to fix:
https://bugzilla.redhat.com/show_bug.cgi?id=1829642
AKA
#1215 (comment)
Basically we have our systemd units dynamically differentiate between
"4.2" and "4.3 or above" by looking at the aleph version.
```
> [release-4.4] Bug 1830102: templates: Add a special machine-config-daemon-firstboot-v42.service

- templates/master/01-master-kubelet/_base/files/kubelet.yaml
- templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Cherry pick of: https://github.com/openshift/machine-config-operator/pull/1450
Kubelet and Crio are running at around 250-500 MB each (on default installs). This PR bumps the limit to 1 GB to allow for a bit of headroom to preserve some of the Kernel cache as well. If we don't bump the limit then memory pressure on the node could flush some of the kernel cache resulting in the kernel trying to re-read the cache. This flood of IOPS can be throttled  by the cloud providers which results in a kernel pause.
> [release-4.3] Bug 1801824: kubelet: add more system reservation to protect node

- pkg/daemon/update.go
Backport of https://github.com/openshift/machine-config-operator/pull/1593
> Bug 1817458: [release-4.3] fix wrongful backup of files not originally on the system

- templates/common/_base/files/etc-networkmanager-dispatcher.d-90-long-hostname.yaml
On GCP it is not uncommon to have DNS names that are too long.
Linux restricts the kernel hostname to being less than 63 characters.
The new template simply ensures that a hostname is set in the event that
NetworkManager is unable to do so.
Bug: 1809345
> Bug 1809345: templates: add etc-networkmanager-dispatcher.d-90-long-hostname.yaml

- lib/resourcemerge/machineconfig.go
Proxy day2 wasn't working because the MCO wasn't rolling the additionalTrustBundle to nodes. Now it does and day2 proxy is deployed.
> Bug 1784201: lib/resourcemerge: set AdditionalTrustBundle

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
This is a back-port PR for https://github.com/openshift/machine-config-operator/pull/1630, goes hand-in-hand with https://github.com/openshift/cluster-network-operator/pull/602
Let me know in case someone requires more information.
/cc @danwinship
> Bug 1811140: Add containernetworking-plugin RPM's bin location to CRI-O config

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
change the entry in crio.conf template to manage ns lifecycle
As it is more secure and gives cri-o more control of namespace lifecycle
This is attempting to do what https://github.com/openshift/machine-config-operator/pull/1568 did, but now we've hopefully ironed out the issues that caused the need for https://github.com/openshift/machine-config-operator/pull/1600
CRI-O now manages namespace lifecycle
> Bug 1831866: cri-o: manage ns lifecycle, again!

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
This is the release-4.3 back-port of https://github.com/openshift/machine-config-operator/pull/1669
/cc @danwinship 
Since you approved the release-4.4 PR:
/assign @umohnani8 @sinnykumari
> Bug 1834247: Add containernetworking-plugin RPM's bin location to CRI-O config

- pkg/daemon/daemon.go
`AddFunc` docs [here][1] and [here][2].  We've been setting an `UpdateFunc` on this informer since we pivoted to node informers in d67e633b7c (#130).  But we need to listen for add events to catch situations where the node's `desiredConfig` is altered before the informer's initial `List` call.  This avoids [situtations][3] [like][4]:
```
I0514 03:27:54.773485    4242 update.go:1346] Starting to manage node: ci-op-9gpgc-w-d-hdjg2.c.openshift-gce-devel-ci.internal
...
I0514 03:42:37.392240    4242 request.go:1068] Response Body: {"kind":"Node","apiVersion":"v1","metadata":{"name":"ci-op-9gpgc-w-d-hdjg2.c.openshift-gce-devel-ci.internal"..."machineconfiguration.openshift.io/desiredConfig":"rendered-node-log-level-14137156-e501-4d3b-9a93-7fff577b45e5-a048da8ad1c08dce6dc6aa3c1101fb44"...
... …
```
> Bug 1834895: pkg/daemon: Set AddFunc on the nodeInformer as well

- templates/common/vsphere/files/NetworkManager-mdns-hostname.yaml
- templates/common/vsphere/files/etc-systemd-system-crio-stream-address.conf.yaml
- templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
- templates/common/vsphere/files/vsphere-coredns-corefile.yaml
- templates/common/vsphere/files/vsphere-coredns.yaml
- templates/common/vsphere/files/vsphere-hostname.yaml
- templates/common/vsphere/files/vsphere-keepalived.yaml
- templates/common/vsphere/files/vsphere-mdns-publisher.yaml
- templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
- templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
- templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
- templates/master/01-master-kubelet/vsphere/units/kubelet.yaml
- templates/worker/00-worker/vsphere/files/NetworkManager-resolv-prepender.yaml
- templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
- templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
- templates/worker/00-worker/vsphere/files/vsphere-mdns-config.yaml
- templates/worker/01-worker-kubelet/vsphere/units/kubelet.yaml
Update the vsphere templates to check if `.Infra.Status` and `.Infra.Status.PlatformStatus` is nil.
> bug 1834925: vsphere: check if .Infra.Status and .Infra.Status.PlatformStatus is nil

- templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
- templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
- templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
- templates/master/00-master/openstack/files/openstack-haproxy.yaml
- templates/master/00-master/ovirt/files/ovirt-haproxy-haproxy.yaml
- templates/master/00-master/ovirt/files/ovirt-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
Per [0], the /readyz endpoint is how the api communicates that it
is gracefully shutting down. Once /readyz starts to report failure,
we want to stop sending traffic to that backend. If we wait for
/healthz, it may be too late because once /healthz starts failing
the api is already not accepting connections.
I also moved the liveness probe for haproxy itself to use a /readyz
endpoint for consistency. This isn't strictly necessary, but I think
it will be less confusing if there aren't multiple health check
endpoints in the config.
0: https://github.com/openshift/installer/pull/3537
Use correct health check endpoint in haproxy configuration to avoid intermittent outages of the api on graceful shutdown.
> Bug 1823950: [baremetal] Switch to /readyz for haproxy healthchecking

- pkg/controller/kubelet-config/helpers.go
Fixes #1817430 (https://bugzilla.redhat.com/show_bug.cgi?id=1817430)
After a kubeletconfig CR rolls out updates to the
kubelet.conf, we want to parse the contents so that
it is printed out in a pretty format.
Create a kubeletconfig CR and check the nodes to ensure that /etc/kubernetes/kubelet.conf is formatted correctly with the tabs and all
Parse the contents of the kubelet.conf after a CR update to ensure it is pretty printed
> Bug 1817430: Parse the kubelet.conf data after an update

- templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Added the environment variables needed for straightforward execution of etcdctl into /root/.profile, so that oc rsh has the ready-made environment.
Install cluster
1. oc rsh -n openshift-etcd etcd-member-pod
2. Run etcdctl commands such as etcdctl member list
Should work right off the bat.
Provide environment variables for straightforward execution of etcdctl commands on pods.
> [release-4.3] Bug 1801430: Write environment variables needed for etcdctl execution into ~/.profile

- install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
After a conversation with @eparis about the fact that this change adds a dependency on SDN to quorum-guard health checks for etcd I feel this should be reverted. The fear would be false negatives on health. Although the cluster would have other problems if SDN were down we don't want to triage that layer if we don't have to.
cc @vrutkovs @sdodson 
This PR reverts
- https://github.com/openshift/machine-config-operator/pull/1552
- https://github.com/openshift/machine-config-operator/pull/1648
> Bug 1825967: revert: etcd quorum guard: don't set hostNetwork

- templates/master/01-master-kubelet/baremetal/units/kubelet.yaml
- templates/master/01-master-kubelet/openstack/units/kubelet.yaml
- templates/master/01-master-kubelet/vsphere/units/kubelet.yaml
- templates/worker/01-worker-kubelet/baremetal/units/kubelet.yaml
- templates/worker/01-worker-kubelet/openstack/units/kubelet.yaml
- templates/worker/01-worker-kubelet/vsphere/units/kubelet.yaml
Using approach from https://github.com/openshift/machine-config-operator/pull/1439 by removing quotes around kubelet_node_ip for rhel7.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1828112
> Bug 1828112: remove quotes around kubelet_node_ip to account for rhel7

- templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
- templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
- templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
This PR updates Keepalived API check script to monitor both kube-api-server health and HAProxy LB health.
With this change, the API VIP should failover to another master if local LB isn't healthy.
> Bug 1835974: Update keepalived API script to monitor also LB health

- cmd/gcp-routes-controller/README.md
- cmd/gcp-routes-controller/run.go
- pkg/controller/template/test_data/controller_config_aws.yaml
- pkg/controller/template/test_data/controller_config_baremetal.yaml
- pkg/controller/template/test_data/controller_config_gcp.yaml
- pkg/controller/template/test_data/controller_config_libvirt.yaml
- pkg/controller/template/test_data/controller_config_none.yaml
- pkg/controller/template/test_data/controller_config_openstack.yaml
- pkg/controller/template/test_data/controller_config_ovirt.yaml
- pkg/controller/template/test_data/controller_config_vsphere.yaml
- templates/master/00-master/gcp/files/etc-kubernetes-manifests-gcp-routes-controller.yaml
- templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
- templates/master/00-master/gcp/units/gcp-routes.service
- templates/master/00-master/gcp/units/openshift-gcp-routes.service
Move gcp-routes to the MCO, call it openshift-gcp-routes. Also, improve the behavior significantly:
1. always accept connections from external sources
2. use downfiles instead of stopping the service
3. implement the equivalent in gcp-routes-controller.
> Bug 1802534: gcp-routes: move to MCO, implement downfile, tweak timing

- templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
In the case that a master node is new it is possible that the etcd container has not yet been downloaded. In this case, DR script will fail because we need auth to create the container by first pulling the image.
> Bug 1825221: templates/master:openshift-recovery-tools pass --authfile to podman create

- templates/master/00-master/_base/files/usr-local-bin-etcd-member-add-sh.yaml
Closes: #1804067
Added an extra check to make sure etcd-member container is not already running on the master.
Try to run etcd-member-add.sh script on an active etcd-member. It should print an error and exit.
Prevent users from running the etcd-member-add.sh script on a wrong master.
> Bug 1804067: Prevent etcd-member-add.sh from running on an active master

- templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
Added the environment variables needed for straightforward execution of etcdctl into /root/.profile, so that oc rsh has the ready-made environment.
Install cluster
oc rsh -n openshift-etcd etcd-member-pod
Run etcdctl commands such as etcdctl member list
Should work right off the bat.
Provide environment variables for straightforward execution of etcdctl commands on pods.
> Bug 1834823: Write environment variables needed for etcdctl execution into ~/.profile

- pkg/daemon/daemon.go
Time of 20s was added when we switched to kubectl drain lib.  This results in consistent error-retries for router pod, which takes ~ 90s each time. Upped timeout to 90s to avoid these preventable and predictable errors.
> Bug 1834948: increase eviction time to avoid preventable timeouts

- templates/common/_base/units/machine-config-daemon-firstboot.service
See https://bugzilla.redhat.com/show_bug.cgi?id=1840222
Something in the baremetal IPI stack is forcibly powering off nodes
during the firstboot.  This causes all sorts of problems, but
we should be more robust to handling this.
The problem with `BindsTo=ignition-firstboot-complete.service`
is twofold:
First, if the service fails, we don't run, and will silently
continue on to e.g. `kubelet.service`.  That's bad - we should
not land user workloads until a node is up to date and secure.
Second, the binding is wrong because at some point we may
move that service into the initramfs in CoreOS, and that would
cause this to break.
The "stamp file" approach is a generally good method of achieving
idempotence, and we already have one, so let's use it.
We also add a …
> Bug 1841255:  machine-config-daemon-firstboot.service: Make idempotent and block kubelet

- templates/common/_base/units/machine-config-daemon-firstboot-v42.service
- templates/common/_base/units/machine-config-daemon-host.service
Also, add machine-config-daemon-firstboot-v42.service so that new
nodes through machine-api comes up as expected on a 4.2 to 4.3
upgraded cluster
Backport of PRs:
- https://github.com/openshift/machine-config-operator/pull/1366
- https://github.com/openshift/machine-config-operator/pull/1706
> Bug 1838984: [release-4.3] templates: Don't enable machine-config-daemon-host.service by default

- docs/Update-SSHKeys.md
Came to my attention these examples were missing ignition version..
> docs: fix ssh machineconfigs to include ignition version

- templates/common/_base/files/etc-systemd-system-machine-config-daemon-firstboot.service.d-10-default-env.conf.yaml
This PR fixes https://github.com/openshift/okd/issues/19. On fcos the machine-config-daemon-firstboot cannot pull images when behind a proxy.
This PR configures the proxy settings for the machine-config-daemon-firstboot service.
Start an OKD installation using proxy settings in the install-config.yaml. The master would fail with
```
Error: unable to pull quay.io/openshift/okd-content@sha256:6625bb97a35604080af348340f0788df36455352b1a039f073cb6894c548fb78: unable to pull image: Error initializing source docker://quay.io/openshift/okd-content@sha256:6625bb97a35604080af348340f0788df36455352b1a039f073cb6894c548fb78: pinging docker registry returned: Get https://quay.io/v2/: dial tcp 3.230.48.144:443: i/o timeout
```
After the PR the image should be pulled using the …
> [OKD] Proxy for machine config daemon firstboot

- manifests/openstack/coredns.yaml
- manifests/openstack/keepalived.conf.tmpl
- manifests/openstack/keepalived.yaml
- pkg/operator/assets/bindata.go
- templates/common/openstack/files/openstack-coredns.yaml
- templates/common/openstack/files/openstack-keepalived.yaml
- templates/common/openstack/files/openstack-mdns-publisher.yaml
- templates/master/00-master/openstack/files/NetworkManager-resolv-prepender.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
- templates/worker/00-worker/openstack/files/NetworkManager-resolv-prepender.yaml
Now that etcd does not need DNS for clustering, we no longer need to
have a VIP to allow the masters to use the bootstrap coredns until
their own coredns instances start. Instead, we can just point them
at the local coredns directly and skip the extra complexity. We
already do this on the workers because they never had a dependency
on the bootstrap coredns so the same method is now used for masters.
This brings the BM change #1569 to OpenStack platform.
> Bug 1841066: OpenStack: Remove DNS VIP

- pkg/daemon/daemon.go
Populate with output of `ignition --version` command
from locally installed binary.
This might be useful.
> pkg/daemon: Add IgnitionVersion to Daemon

- cmd/common/helpers.go
When upgrading 4.2.16 to 4.2.18 I noticed that the `machine-config`
cluster operator remained at 4.2.16. Looking at the logs of the
`machine-config-operator` I noticed the following:
```
I0227 20:34:38.428822       1 start.go:42] Version: v4.2.15-202001171551-dirty (31fed93186c9f84708f5cdfd0227ffe4f79b31cd)
E0227 20:34:38.458532       1 event.go:247] Could not construct reference to: '&v1.ConfigMap{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"machine-config", GenerateName:"", Namespace:"openshift-machine-config-operator", SelfLink:"/api/v1/namespaces/openshift-machine-config-operator/configmaps/machine-config", UID:"9305be83-59a0-11ea-a084-064dd2f0c578", ResourceVersion:"42279333", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, …
```
> Make sure corev1 schema is registered

- templates/master/01-master-kubelet/_base/units/kubelet.yaml
- templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
Cherry pick https://github.com/openshift/machine-config-operator/pull/1390 with two patches to backport the kubelet log level setting to 4.3
> [release-4.3] Bug 1840300: kubelet: add log level environment variable

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Update the crio.conf template to add log_dir and its
value. This ensures that we don't break on an empty value
when a ctrcfg is created and the cluster is upgraded to 4.3.
Create a ctrcfg CR and then upgrade to 4.3.x
Update the crio.conf template to include log_dir
> [release-4.2] Bug 1840461: Update the crio.conf template to have log_dir

- pkg/server/api.go
It's super useful to see the bootimage version for debugging
things like https://bugzilla.redhat.com/show_bug.cgi?id=1829642
AKA
https://github.com/openshift/machine-config-operator/pull/1215#issuecomment-621950182
> mcs: Log User-Agent

- manifests/machineconfigdaemon/daemonset.yaml
- pkg/operator/assets/bindata.go
This is supposed to fix the BZ in $subject and it's the same as BZs like https://bugzilla.redhat.com/show_bug.cgi?id=1813479. The impact of a change like this isn't fully clear as mentioned in the DNS PR as well https://github.com/openshift/cluster-dns-operator/pull/171#issuecomment-622110777
I'm opening this PR to get some more eyes and testing on this - @derekwaynecarr @smarterclayton ptal
The BZ has been pushed to 4.6 following what the DNS team did as well.
> Bug 1780318: MCD: tolerate all taints

- templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
- templates/common/vsphere/files/vsphere-coredns-corefile.yaml
- templates/common/vsphere/files/vsphere-coredns-db.yaml
- templates/common/vsphere/files/vsphere-coredns.yaml
- templates/common/vsphere/files/vsphere-keepalived.yaml
- templates/common/vsphere/files/vsphere-mdns-publisher.yaml
- templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
- templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
- templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
- templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
- templates/worker/00-worker/vsphere/files/vsphere-mdns-config.yaml
- templates/worker/00-worker/vsphere/files/vsphere-non-virtual-ip.yaml
v4.1 did not include the `.Infra` see: https://github.com/openshift/machine-config-operator/blob/master-4.1/pkg/apis/machineconfiguration.openshift.io/v1/types.go#L111-L136
Add a check to make sure that it is not nil.
> Bug 1834194: vsphere: 4.1 to 4.4 upgrade bug

- templates/common/vsphere/files/NetworkManager-mdns-hostname.yaml
- templates/common/vsphere/files/etc-systemd-system-crio-stream-address.conf.yaml
- templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
- templates/common/vsphere/files/vsphere-coredns-corefile.yaml
- templates/common/vsphere/files/vsphere-coredns.yaml
- templates/common/vsphere/files/vsphere-hostname.yaml
- templates/common/vsphere/files/vsphere-keepalived.yaml
- templates/common/vsphere/files/vsphere-mdns-publisher.yaml
- templates/common/vsphere/units/nodeip-configuration.service.yaml
- templates/common/vsphere/units/vsphere-hostname.service.yaml
- templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
- templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
- templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
- templates/master/01-master-kubelet/vsphere/units/kubelet.service.yaml
- templates/worker/00-worker/vsphere/files/NetworkManager-resolv-prepender.yaml
- templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
- templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
- templates/worker/00-worker/vsphere/files/vsphere-mdns-config.yaml
- templates/worker/01-worker-kubelet/vsphere/units/kubelet.service.yaml
In an upgrade from 4.1 to 4.4 the .Infra can be nil
This causes templating to fail and the MCO rollout in an
upgrade to fail.
> Bug 1842952: vsphere templates check if Infra is nil

- templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
Fixes #1823967 (https://bugzilla.redhat.com/show_bug.cgi?id=1823967)
By default, kubelet sets the pod-infra-container-image flag to k8s.gcr.io/pause:3.1.
The kubelet does an image status call for this image every few minutes and that is
why we were seeing the warning logs in cri-o saying this pause image is not found.
Overriding the pod-infra-container-image flag here to ensure the image status calls
we get from the kubelet is for the ocp pause image.
Start a cluster and check the crio logs for any warnings about the k8s.gcr.io/pause:3.1 image not being found.
Set the pod-infra-container-image flag in kubelet to the correct ocp pause image
> Bug 1823967: Set the pod-infra-container-image flag in kubelet to ocp pause image

- templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
- templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
- templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
- templates/worker/00-worker/baremetal/files/baremetal-keepalived-keepalived.yaml
- templates/worker/00-worker/openstack/files/openstack-keepalived-keepalived.yaml
- templates/worker/00-worker/ovirt/files/ovirt-keepalived-keepalived.yaml
- templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
Before this `curl -s´ only failed when the tcp connection failed, not on http non-200 errors.
> Bug 1844387: Fail healthz/readyz curls on non-200 http errors

- install/0000_80_machine-config-operator_06_clusteroperator.yaml
- pkg/operator/status.go
collect everything needed, should be better than https://github.com/openshift/must-gather/pull/157
> pkg/operator: collect all needed resources

- pkg/daemon/daemon.go
We really want dynamic visibility and cluster events/alerts on
this of course but let's start with this.
> daemon: Also dump systemd failed units on start

- pkg/daemon/update.go
This fixes restoring original file content into /etc/
when file is available in /usr/etc/ and not owned by any rpm.
> Bug 1843974: daemon: fix restoring file logic to avoid unnecessary deletion

- install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Before this change, the quorum-guard `timeoutSeconds` and `failureThreshold` values were
left unspecified in the manifest, and were defaulted.
The default value for `timeoutSeconds` is 1, while the probe itself enforces a 2
second timeout. This means that in cases where the probe itself should succeed,
Kube will consider the probe failed because of the stricter timeout on the probe
specification.
The effect is the probe sporadically reports false negative outcomes.
This change increases the `timeoutSeconds` value to exceed the probe logic's
internal timeout so that the probe command is the source of truth with regards
to timeouts.
This change also makes the `failureThreshold` value explicit, but the default value
is preserved because I don't have a clear reason yet to change it.
**- What …
> Bug 1829923: Fix quorum-guard timeouts

- templates/master/00-master/baremetal/files/baremetal-mdns-config.yaml
- templates/master/00-master/openstack/files/openstack-mdns-config.yaml
- templates/master/00-master/ovirt/files/ovirt-mdns-config.yaml
- templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
Similar to https://github.com/openshift/installer/pull/3265, this
removes the etcd entries from mdns config because etcd no longer uses
DNS.
> etcd: remove etcd entries from mdns

- pkg/controller/common/helpers.go
- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/container-runtime-config/helpers.go
- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
- pkg/controller/kubelet-config/kubelet_config_features.go
- pkg/controller/kubelet-config/kubelet_config_features_test.go
- pkg/controller/render/render_controller.go
- pkg/controller/template/render.go
This is a funny bug...and it's tricky to explain as well but I'll try.
Scenario: installation with custom chrony conf user provided with name (remember it):
99-master-etc-chrony-conf
Install the cluster with the above and 1/(probably an high number) fails with the usual:
Node master-0-0.ocp-edge08-0.qe.lab.redhat.com is reporti
ng: \"machineconfig.machineconfiguration.openshift.io \\\"rendered-master-a2dacf21a0e43d86e8495317ad36ae98\\\" not found\"
So master and workers go up, but masters somehow have a diff between what the bootstrap generated
for rendered-master and what the MCO did once it was up and running in the cluster.
Now, taking a look at the diff between what's on bootstrap and what the MCO generated yields
nothing in file contents diff, everything is same EXCEPT a file name …
> Bug 1826150: Bootstrap Machine Config ordering issue

- pkg/server/api.go
Reverts openshift/machine-config-operator#1793
```
[core@ci-op-1155yj38-94601-74fmj-bootstrap ~]$ sudo crictl logs 1c601dc2cab8e
I0610 18:43:07.189725       1 bootstrap.go:37] Version: machine-config-daemon-4.6.0-202006101417-2-g65817154-dirty (65817154799c286cacc45bd2724f560784c7748b)
I0610 18:43:07.189866       1 api.go:56] Launching server on :22624
I0610 18:43:07.189872       1 api.go:56] Launching server on :22623
2020/06/10 18:43:07 http: TLS handshake error from 168.63.129.16:53505: tls: client offered only unsupported versions: [303 302 301 300]
2020/06/10 18:43:07 http: TLS handshake error from 168.63.129.16:53506: tls: client offered only unsupported versions: [302 301 300]
2020/06/10 18:43:07 http: TLS handshake error from 168.63.129.16:53507: tls: client offered only …
```
> Revert "Bug 1844990: pkg/server: default to TLS 1.3"

- templates/common/_base/units/crio.service.yaml
- templates/common/_base/units/kubelet.service.yaml
- templates/common/_base/units/machine-config-daemon-host.service.yaml
- templates/common/_base/units/pivot.service.yaml
Commit 9b2e4248f5ffeb38710720070018bec1949f88ca made things *really*
confusing to debug looking at the journal because the `Description=`
field doesn't just apply to the drop-in - it overrides the base description.
I only discovered this when I was manually doing `systemctl start machine-config-daemon-host`
to test something and was really confused why I was seeing
`Jun 09 03:49:02 compute-0 machine-config-daemon[1342]: Starting MCO environment configuration...`
in the logs.
Previously when trying to determine timelines I'd been searching
for `Starting Machine` but this override breaks that!
See also https://github.com/systemd/systemd/pull/15957
> templates: Stop renaming description of crio/kubelet and other units

- pkg/daemon/daemon.go
https://bugzilla.redhat.com/show_bug.cgi?id=1842906
The removal of `BindsTo=` in https://github.com/openshift/machine-config-operator/pull/1762/commits/75dbab9c54c6cb3470075af1da1b139ecea02d38
I think was completely correct for *new* installs, but creates
an upgrade hazard if we happened to be interrupted when
the cluster was originally installed as 4.4 or below.
Basically the scenario is:
- 1st boot: 4.4 install, machine boots the first time
- restart.service kills machine-config-daemon-firstboot before it upgrades, or before it unlinks the file
- 2nd boot: We stumble on without having pivoted, node joins cluster
MCD starts a reboot into 44.81.202006062030-0 which we *should* have updated to before joining the cluster
- Cluster upgrade to 4.5 starts, new MCO starts an updated OS rollout …
> Bug 1842906: daemon: Remove encapsulated config when joining the cluster

- install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Made the following changes as settings were not getting
picked up:
- move failure threshold/timeout to nest under readinessProbe
- move and correct initialDelaySeconds and periodSeconds
- reorder container sub-elements to nest image under name
> Bug 1829923: etcd-quorum-guard: update containers section in deployment.yaml

- templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
When the local kube-apiserver becomes ready, the GCP LBs pick up the endpoint and route traffic to the IP. In parallel the gcp-routes service notices the local, green readyz and stops sending traffic to that LB.
The second step must happen *BEFORE* the first. Otherwise, local requests still go to the GCP LB that already picked up the endpoint. We risk to blackhole 1/3 of the requests (because GCP has no hairpinning support).
The reason is that the gcp-routes script polls every 5s (without inotify which isn't installed in the image as we know) such that we end up with 1*2s + 1.9999s + 5s until the gcp-routes script updates iptables (1.9999s because the readyz polling happens at an unfortunate time, and the 5s for the poll script to notice). Hence, 9s >> 6s of the LB. Hence, for 3s we might …
> Bug 1845903: gcp-routes: decrease downfile poll to be faster than LB on recovery

- pkg/controller/kubelet-config/kubelet_config_controller.go
We ignored retrying KubeletConfigs if the MCP pool was not available. This fix will retry applying the KubeletConfig if the MCP pool is not present.
We did not retry by returning a ForgettableError. This change removes the forgettableerror and returns the standard Error object.
```
Retry applying KubeletConfigs if the MachineConfigPool is not present.
```
> Bug 1841358: kubelet: retry kubeletconfigs if the MCP pool is not found

- manifests/baremetal/coredns-corefile.tmpl
- pkg/operator/assets/bindata.go
- templates/common/baremetal/files/baremetal-coredns-corefile.yaml
Previously the ingress record was hard-coded to be an A record, which
does not work when deploying with an ipv6 ingress VIP. While fixing
that, an issue with the api and api-int records was also exposed.
According to RFC 4074, when a query for a record comes in that asks
for the wrong type of record (i.e. asking for an A record when only
a AAAA record exists), the server should return NOERROR with an
empty list of records. This indicates to the client resolver that
a record of that name exists, but not with that type.
For our purposes, it was necessary to convert all of the records to
use the template plugin in order to get this behavior. The hosts
plugin previously used for the api records does not correctly handle
requests for the wrong record type, at least with the fallthrough
option …
> Bug 1820785: [baremetal] Correctly handle requests for ipv4/ipv6 records

- templates/master/01-master-kubelet/baremetal/units/kubelet.service.yaml
- templates/master/01-master-kubelet/openstack/units/kubelet.service.yaml
- templates/master/01-master-kubelet/vsphere/units/kubelet.service.yaml
This came up because of a bug report showing that workloads were
scheduled on masters for the baremetal platform regardless of the
schedulableMasters scheduler configuration.  This is due to the
NoSchedule taint not being applied by default on this platform.  The
baremetal platform specific kubelet caused this behavior.  We were
going to remove the custom kubelet config once this behavior was
configurable (see PR #993), but it was never removed because we ended
up needing to make some IPv6 related customizations in this file.  We
also forgot to re-add the default taint.
Meanwhile, some other changes to the kubelet unit were not applied to
the baremetal version.  I also checked the openstack and vsphere files
and found discrepencies there, as well.
This is the simplest fix, which is to get …
> Bug 1828250: Sync kublelet config across platforms

- pkg/controller/node/node_controller.go
- pkg/controller/node/node_controller_test.go
- pkg/controller/node/status.go
As of now, MCC is watching for all the nodes in the cluster. While this is not
a problem, with the introduction of worker Windows Nodes in the cluster, MCC
will react to changes happening to the Windows Node objects. This commit ensures
that MCC ignores the changes for the Windows node objects by not assigning them
to the worker pool
Make MCC ignore Windows worker node events.
Updated the unit tests to exercise those scenarios.
MCO should watch only for Linux node events
I couldn't write a e2e to validate the changes as it requires bringing a Windows Worker node. Here is the ref for the [label](https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#kubernetes-io-os)
xref: …
> [MCO] Ignore Windows Nodes

- docs/custom-pools.md
Update the docs for custom pools showing that you can drop the worker role label to have "infra-only" nodes (which is valid for any custom pool also).
> docs: custom-pools work w/o the worker role label

- templates/common/_base/units/node-valid-hostname.service
This seeks to address the problem with "localhost" nodes attempting to
join a cluster by holding up network-online.target until the node gets a
valid hostname (not localhost).
Closes 1845885: race condition during installation between nodes getting their
hostnames and crio+kubelet starting
> Bug 1845885: templates: add node-valid-hostname.service for hostname check

- install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
Made the following changes as settings were not getting
picked up:
- move and correct initialDelaySeconds and periodSeconds
- reorder container sub-elements to nest image under name
- add failureThreshold and timeoutSeconds
Closes: BZ 1845636
> [release-4.5] Bug 1845636: etcd-quorum-guard: update containers section in deployment.yaml

- templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
- templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
- templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
Based on [1] and [2] we should check for the router's readiness rather than for its liveliness.
This updates the keepalived ingress check query accordingly.
[1] https://github.com/openshift/installer/blob/master/docs/dev/kube-apiserver-health-check.md#load-balancer-health-check-probe
[2] https://github.com/openshift/router/blob/df645b1bb2c4085468845a526ac21cadb54b375d/deploy/router.yaml#L47-L48
> Update keepalived ingress check's endpoint

- pkg/daemon/daemon.go
We seem to be missing some spaces:
```
I0617 21:04:50.776559    6609 daemon.go:307] Evicted pod from Nodepodrevision-pruner-2-ip-10-0-194-55.us-east-2.compute.internal/openshift-kube-scheduler
```
Ahh I see the order is also off... will fix
> Bug 1848195: daemon: fix formating in eviction message

- go.mod
- pkg/daemon/daemon.go
This is most straightforward fix as users are super confused by A/B instead of Actual/Expected - This can be better and imo isn't worth wrapping. 
Am considering using `go-cmp`(https://pkg.go.dev/github.com/google/go-cmp/cmp?tab=doc#Diff) which diffs line by line (like a traditional diff) instead of just huge blocks as it's hard for users to see the differences between the files.
> Bug 1810680: make file diffs more user friendly

- test/e2e/old-bootimages.sh
Let's validate that old bootimages can join the cluster.
I started this in shell because it seemed simpler, then it got
messy...sorry.
I plan to add this as an optional
`/test old-bootimages`
Prow job.
> test/old-bootimages: New test

- pkg/daemon/daemon.go
It seems `upgradeHackFor44AndBelow` was running inside an if statement
that only runs on cluster installation. The bug we got happens on
upgrade so what we really want is to run the hack once the MCD is
running from within the cluster (e.g. during an upgrade).
This PR still targets the now-verified 4.6 BZ - if we confirm this fix (and the verification was then flacky) we'll have to move 1842906 back to POST
@cgwalters @sinnykumari ptal
> Bug 1842906: pkg/daemon: run 4.4 upgrade hack on MCD cluster boot

- templates/common/baremetal/files/baremetal-NetworkManager-kni-conf.yaml
The full fix for all platforms is #1840, but as this is completely
blocking baremetal ci and dev right now and we're having ci issues
with the other platforms on the full fix, this is just the bit that
is needed to get baremetal working again. We'll still want to get
1840 in eventually, but that will be less critical if we merge this
in the meantime.
> Minimal DHCP fix to unblock baremetal ci

- pkg/operator/status.go
- pkg/operator/status_test.go
- test/e2e/mco_test.go
This func is called only from within `setOperatorStatusExtension` which
in turns is called in some other operator routines. The thing is, this
doesn't work, the `Status.Extension` field of the CO is never set and
I'm looking at why as we speak. Besides that, this function should
report pools statuses regardless of the correctness of the pool
(controller version mismatch anyone? :troll:).
This will ensure, once we fix the CO issue, that we'll always have
something to immediately look at when looking at the MCO cluster
operator object.
This is meant to be the "improve controller version mismatch errors" as
from now on, we'll have users differentiate on the exact error by
looking at the CO.Status.Extension field (which, as you can see from the
code, reports the pools statuses, including any …
> pkg/operator: report pools statuses

- pkg/controller/kubelet-config/kubelet_config_controller.go
If the MachineConfigPool is not present, then the kubelet config controller immediately requeues the key. It is highly unlikely a Pool will be created immediately after this error, so we should requeue the key after a minute.
> Bug 1849538: kubelet: wait to requeue after mcp error

- pkg/daemon/daemon.go
When the force file is present, we didn't actually validate.
Obviously, this just changes logging; I was just reading the code
as part of looking at
https://bugzilla.redhat.com/show_bug.cgi?id=1766515
> daemon: Move "Validated on-disk state" log to only when we have

- cmd/machine-config-daemon/pivot.go
- pkg/daemon/rpm-ostree.go
While chasing https://bugzilla.redhat.com/show_bug.cgi?id=1842906
I thought at one point this code might be invoked and was causing
a reboot that shouldn't be happening.
That turned out not to be the case.  But since nothing uses
the `--reboot` or stamp file anymore (we use the `-firstboot`)
code, the MCD code is always controlling reboots, delete this code.
Code that doesn't exist can't have (potential) bugs.
> Remove pivot invocations of systemctl reboot

- pkg/daemon/daemon.go
- pkg/daemon/daemon_test.go
One of the fundamental flaw of the MCO is its inability to properly
bubble up errors to the node object and pools (and later, cluster
operator).
One of the code flaw that we have is around Go idioms. The functions
I've modified here were just logging the error and returning a boolean.
That makes thing very tricky when debugging as there's no other way to
read those errors other than asking for a full must-gather...
This patch converts that code to properly return errors and bubble up
any. The only thing we don't report is the diff when file content
mismatch which is ok for debugging purposes at least we can immediately
check "which" file is diffing (and later check what's diffing with
must-gather if needed, at least this helps us debug and triage duplicate
bugs if possible). …
> pkg/daemon: use Golang idioms and bubble up errors

- examples/cluster.controllerconfig.yaml
- lib/resourcemerge/machineconfig.go
- manifests/controllerconfig.crd.yaml
- pkg/apis/machineconfiguration.openshift.io/v1/types.go
- pkg/controller/bootstrap/testdata/bootstrap/machineconfigcontroller-controllerconfig.yaml
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
- pkg/controller/kubelet-config/kubelet_config_features_test.go
- pkg/controller/template/render.go
- pkg/controller/template/render_test.go
- pkg/controller/template/template_controller_test.go
- pkg/controller/template/test_data/controller_config_aws.yaml
- pkg/controller/template/test_data/controller_config_baremetal.yaml
- pkg/controller/template/test_data/controller_config_gcp.yaml
- pkg/controller/template/test_data/controller_config_libvirt.yaml
- pkg/controller/template/test_data/controller_config_none.yaml
- pkg/controller/template/test_data/controller_config_openstack.yaml
- pkg/controller/template/test_data/controller_config_ovirt.yaml
- pkg/controller/template/test_data/controller_config_vsphere.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/render.go
- pkg/operator/render_test.go
Currently ControllerConfig.Platform and
ControllerConfig.Infra.Status.PlatformStatus.Type contain redundant
information. However, the former is encoded as untyped string and the
latter as configv1.PlatformType.
This deprecates the ControllerConfig.Platform field and leaves
ControllerConfig.Infra.Status.PlatformStatus.Type as the
canonical platform identifier, making all internals consume that field
instead.
> Deprecate Platform field on ControllerConfig CRD

- templates/common/openstack/files/openstack-NetworkManager-conf.yaml
The full fix for all platforms is #1840, but as this is completely
blocking openstack ci and dev right now and we're having ci issues with
the other platforms on the full fix, this is just the bit that is
needed to get openstack working again. We'll still want to get
1840 in eventually, but that will be less critical if we merge this in
the meantime.
Similar to what Baremetal did in https://github.com/openshift/machine-config-operator/pull/1851
> OpenStack: Minimal DHCP fix to unblock CI

- templates/common/ovirt/files/NetworkManager-resolv-prepender.yaml
- templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
The EtcdDiscoveryDomain field on ControllerConfig CRD was deprecated in
[1] in favor of `ControllerConfig.Infra.Status.EtcdDiscoveryDomain`.
However the originial PR missed two matches.
This fixes it so that there is no surprise in case
`ControllerConfig.EtcdDiscoveryDomain` is effectively removed.
[1] https://github.com/openshift/machine-config-operator/pull/1675
> [ovirt/vsphere] Favor EtcdDiscoveryDomain in ControllerConfig.Infra.Status

- manifests/baremetal/coredns-corefile.tmpl
- pkg/operator/assets/bindata.go
- templates/common/baremetal/files/baremetal-coredns-corefile.yaml
In order to avoid sending multicast traffic on all configured
interfaces on a system, we need to specify the address of the
interface we want to send the traffic on.
Because this is a high priority problem on baremetal and (at least
to my knowledge) not on other platforms, I'm doing it for baremetal
only for now. We can do the other platforms as a followup, but I
don't want to hold it up waiting for everyone to sign off.
Configure coredns-mdns to only send multicast traffic on one interface
to avoid sending it to interfaces where it is undesirable.
> [baremetal] Set NonVirtualIP in mdns plugin config

- templates/common/_base/files/iptables-modules.yaml
Added a template file to create `/etc/modules-load.d/iptables.conf` to force the legacy iptables module to be loaded; this guarantees that pods that try to create iptables rules in their own network namespace will be able to, regardless of whether they use iptables-legacy or iptables-nft.
(Specifically, this is about making legacy and third-party pods work. We can't just say "change the pod to do X instead" because this is about fixing the behavior of pods that we don't control.)
Create a privileged, non-hostNetwork pod, verify that "iptables-legacy -L" (or just "iptables -L" with older iptables) works rather than giving an error
The legacy iptables kernel module is now loaded by default on OCP nodes, to allow …
> Bug 1822945: templates: add a file to load legacy iptables kernel modules

- pkg/controller/node/status.go
- pkg/controller/render/render_controller.go
- pkg/controller/render/render_controller_test.go
TL;DR; of the Tl;DR; 
> This isn't changing something big, just have the Source field always in sync which if it isn't it can cause problems
This bug is easily reproducible by creating two machine configs which
won't change anything in the Ignition config, thus causing no new hashed
rendered machine config name and finally leaving the pool Source field outdated.
This isn't a real issue for the worker pool, but it becomes an upgrade blocker
when the master pool suffers from this - see https://bugzilla.redhat.com/show_bug.cgi?id=1851965
TL;DR; to reproduce this and verify:
metadata:
labels:
name: 50-examplecorp-chrony
spec:
config:
ignition:
version: 2.2.0
As you may notice, …
> pkg/controller: sync pools configuration source

- manifests/baremetal/coredns-corefile.tmpl
- pkg/operator/assets/bindata.go
- templates/common/baremetal/files/baremetal-coredns-corefile.yaml
Previously the ingress record was hard-coded to be an A record, which
does not work when deploying with an ipv6 ingress VIP. While fixing
that, an issue with the api and api-int records was also exposed.
According to RFC 4074, when a query for a record comes in that asks
for the wrong type of record (i.e. asking for an A record when only
a AAAA record exists), the server should return NOERROR with an
empty list of records. This indicates to the client resolver that
a record of that name exists, but not with that type.
For our purposes, it was necessary to convert all of the records to
use the template plugin in order to get this behavior. The hosts
plugin previously used for the api records does not correctly handle
requests for the wrong record type, at least with the fallthrough
option …
> Bug 1851541: Correctly handle requests for ipv4/ipv6 records

- manifests/baremetal/coredns-corefile.tmpl
- pkg/operator/assets/bindata.go
- templates/common/baremetal/files/baremetal-coredns-corefile.yaml
In order to avoid sending multicast traffic on all configured
interfaces on a system, we need to specify the address of the
interface we want to send the traffic on.
Because this is a high priority problem on baremetal and (at least
to my knowledge) not on other platforms, I'm doing it for baremetal
only for now. We can do the other platforms as a followup, but I
don't want to hold it up waiting for everyone to sign off.
> Bug 1848094: [baremetal] Set NonVirtualIP in mdns plugin config

- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1745919
Use the same utility that `kubelet` uses to parse the relevant values during validation.
Try to create a `KubeletConfig` with invalid or negative values for `kubeReserved` or `systemReserved`. 
```yaml
custom-kubelet-reserved.yaml:
metadata:
name: set-reserved
spec:
matchLabels:
custom-kubelet: set-reserved
kubeletConfig:
kubeReserved:
cpu: -200m
memory: -200G
systemReserved:
cpu: -200m
memory: -200G
```
You should be able to see following error in `KubeletConfig` CR,
```sh
Status:
Conditions:
Last Transition Time:  2020-07-01T03:12:50Z
Message:               Error: KubeletConfiguration: cpu …
```
> Bug 1745919: KubeletConfig: Validate kubeReserved and systemReserved for KubeletConfig

- templates/common/_base/files/etc-zincati-configd-90-disable-feature.yaml
- templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
- templates/common/_base/units/machine-config-daemon-host.service.yaml
- templates/common/_base/units/machine-config-daemon-pull.service.yaml
This ensures Zincati is disabled early on master pivot.
Fixes https://github.com/openshift/okd/issues/215
> [fcos] disable zincati on masters/workers

- pkg/daemon/update.go
- pkg/daemon/update_test.go
- test/e2e/mcd_test.go
Split multiple kernel parameters in a single string, best matching what the kernel does. This
allows users to provide kernelArguments space delineated as a single string. For
instance, the following will be treated the same:
```yaml
kernelArguments:
- a=1 b=2
```
and
```yaml
kernelArguments:
- a=1
- b=2
```
1.
```shell
oc create -f - <<EOF
metadata:
labels:
name: 50-worker-custom
spec:
kernelArguments:
- a=1 b=2
EOF
```
2. Watch the node <node> reboot and become Ready.
3. Delete the custom MC
```shell
oc delete mc/50-worker-custom
```
4. Watch the node <node> reboot and become Ready
Split multiple …
> Bug 1812649: split kernel arguments

- cmd/machine-config-daemon/pivot.go
- pkg/controller/node/node_controller.go
- pkg/daemon/daemon.go
- pkg/daemon/pivot/types/imageinspection.go
- pkg/daemon/pivot/utils/run.go
- pkg/daemon/pivot/utils/run_test.go
- pkg/daemon/rpm-ostree.go
- pkg/daemon/update.go
taking a look at BZ 1840385 we can see that we had tons of useful logs in the MCD:
```
2020-05-19T13:06:46.445346629Z I0519 13:06:46.085072 2996778 run.go:16] Running: podman pull -q --authfile /var/lib/kubelet/config.json quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b920c6ed07fa42565949ce61f14b3b9dd7bea64d2cfb13539fcea7068ea799f2
2020-05-19T13:06:46.445346629Z Error: error pulling image "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b920c6ed07fa42565949ce61f14b3b9dd7bea64d2cfb13539fcea7068ea799f2": unable to pull quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b920c6ed07fa42565949ce61f14b3b9dd7bea64d2cfb13539fcea7068ea799f2: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:b920c6ed07fa42565949ce61f14b3b9d …
```
> Bug 1840385: pkg/daemon: bubble up pivot errors

- templates/common/vsphere/files/vsphere-hostname.yaml
- templates/common/vsphere/units/vsphere-hostname.service.yaml
This PR enables UPI to support MachineSets.
The hostname of the VMware Guest must be set for
CSR approval to work correctly and the node to join the cluster.
> Bug 1843384: Remove IPI checks for vsphere hostname script and systemd unit

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
closes https://bugzilla.redhat.com/show_bug.cgi?id=1853735
`crio config` on a MCO managed node will return /etc/containers/oci/hooks.d for hooks_dir
> Bug 1853735: crio: correct hooks directory

- templates/common/_base/units/docker.socket.yml
`docker` service is not used and takes ~150MB of RAM on all nodes
Fixes https://github.com/openshift/okd/issues/243
> [fcos] templates/common/_base/units: disable docker

- templates/common/_base/files/etc-networkmanager-dispatcher.d-90-long-hostname.yaml
Use `printf` instead of `echo` when truncating the hostname. `echo` adds
line termination that gets counted as a character. Example:
$ echo test | wc -c
5
$ printf test | wc -c
4
Signed-off-by: Ben Howard <ben.howard@redhat.com
> templates: Fix for NM dispatcher script miscounting length

- pkg/server/api.go
To not break existing behaviour, if no user-agent is defined in
the request, just serve spec v2 as we used to.
> Bug 1854160: server: serve v2 if no user-agent is defined

- pkg/daemon/update.go
- pkg/daemon/update_test.go
- test/e2e/mcd_test.go
Basically what the title says, ~~allow args with same key value and~~ preserve the order we get the args from the MC. Not fully sure if rpm-ostree does some magic there but this should avoid random ranging over a map.
Note: we lost the beauty of checking in O(1) using a map but this isn't gonna be a big deal as the kargs array shouldn't be thousands of elements afaict.
On a second thought, I think we were allowing duplicates already, I'm gonna triple check that.
> Bug 1853890: pkg/daemon: preserve kargs order

- pkg/daemon/daemon.go
force does 2 things mainly: skip validation and "force" update to the desiredConfig. That doesn't mean the MCD can't fail anymore, we're just forcing a rollout that wouldn't have normally happened. The usual cases are: pivot not booting into the right ostree, someone writes the force file and the update is retryed (but still can fail!) or somebody touches files on disk, use the force file to bring the system back to desiredConfig w/o validating (and degrading)
cc @cgwalters related to https://github.com/openshift/machine-config-operator/pull/1086#issuecomment-652592586
Testing with:
- `oc debug node/<worker>`
- edit `/etc/crio/crio.conf.d/00-default` and add a dummy comment
- check MCD degraded because of the above
- touch the file, reboot the MCD
- watch it recover to the correct file …
> pkg/daemon: make force use the force

- templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
- templates/master/00-master/baremetal/files/baremetal-keepalived-script.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-script.yaml
- templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
- templates/master/00-master/ovirt/files/ovirt-keepalived-script.yaml
- templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
- templates/master/00-master/vsphere/files/vsphere-keepalived-script.yaml
This commit extracts the chk_ocp script into a separate file and wraps
the check scripts with the timeout command to workaround
acassen/keepalived#1364.
This PR supersedes #1908.
Co-Authored-By: Yossi Boaron <yboaron@redhat.com>
Co-Authored-By: Ben Nemec <bnemec@redhat.com>
Installer can deploy OCP on on-prem platform again.
Wrap keepalived checks with timeout to workaround known issue with keepalived v2.0.10.
> Bug 1854249: [On-Prem] Workaround issues with keepalived v2.0.10

- templates/master/01-master-kubelet/baremetal/units/kubelet.yaml
This came up because of a bug report showing that workloads were
scheduled on masters for the baremetal platform regardless of the
schedulableMasters scheduler configuration. This is due to the
NoSchedule taint not being applied by default on this platform. The
baremetal platform specific kubelet caused this behavior. We were
going to remove the custom kubelet config once this behavior was
configurable (see PR #993), but it was never removed because we ended
up needing to make some IPv6 related customizations in this file. We
also forgot to re-add the default taint.
Meanwhile, some other changes to the kubelet unit were not applied to
the baremetal version.
This is the simplest fix, which is to get these files in sync again.
The differences are very minor, so a better follow-up would be …
> Bug 1849217: Sync kublelet config across platforms

- pkg/controller/node/node_controller.go
- test/e2e/mco_test.go
Fixes https://github.com/openshift/machine-config-operator/issues/1875
The `CheckMasterIsAlreadySchedulable` check is redundant in these cases, because both `makeMasterNode(Un)Schedulable` functions already check if the worker label exists before adding/removing it, and `make..Schedulable` checks for the taint, so we just need to add the taint check to `make...UnSchedulable`.
This also cleans up the logic where if a master taint was removed (effectively making the master nodes schedulable), it could conflict with a `mastersSchedulable: false` setting in the schedule, and would never be reconciled (because `CheckMasterIsAlreadySchedulable` always returned `false` without the master taint.
This makes the `mastersSchedulable: false` setting the ultimate source-of-truth for …
> Bug 1851226: Refactor mastersSchedulable reconciliation checks

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
change the entry in crio.conf template to manage ns lifecycle
As it is more secure and gives cri-o more control of namespace lifecycle. Also change the outdated config name value
backport of https://github.com/openshift/machine-config-operator/pull/1689
CRI-O now manages namespace lifecycle
> Bug 1825339: [4.4] crio: manage ns lifecycle

- cmd/machine-config-operator/bootstrap.go
Partially fixes https://bugzilla.redhat.com/show_bug.cgi?id=1835233
We want to be able to access the release-image used for
cluster installation so we can avoid setting that registry
as blocked when there is an Image CR at installation. For
this, we need to pass down the release-image info from the
installer to the controller at bootstrap.
This is step 1. After this is merged, will update bootkube.sh
to set the --release-image flag with the information needed.
Same way as mentioned in https://github.com/openshift/machine-config-operator/pull/1866 once that is merged in.
Add --release-image as a bootstrap option flag.
> Add --release-image flag to bootstrap options

- templates/worker/00-worker/openstack/files/openstack-disable-tx-checksum-offload.yaml
RHCOS image now contains the fix for nodeport service running on
different hosts, allowing us to remove the partial workaround.
The fix landed in kernel-4.18.0-202.el8 [1],
kernel-4.18.0-193.10.1.el8_2 [2], and kernel-4.18.0-147.21.1.el8_1 [3].
This reverts commit 270bb6748152824754d34b9f83bed1f4fbf98a8c.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1794714
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1847128
[3] https://bugzilla.redhat.com/show_bug.cgi?id=1847127
> Bug 1821800: Revert "OpenStack: disable tx checksum offload for workers"

- templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Closes: 1826021
Fixed a problem with a greedy regular expression.
Run restore on a master which is not the first one in the ETCD_INITIAL_CLUSTER. It should finish successfully.
Current restore shell script results in an error "Error: snapshot restore requires exactly one argument" if the attempted master in not the first member listed in the ETCD_INITIAL_CLUSTER. This is due to a bug in the regular expression.
> Bug 1826021: Fix a problem with a greedy regular expression matching more than needed

- templates/common/baremetal/units/nodeip-configuration.service.yaml
- templates/common/openstack/units/nodeip-configuration.service.yaml
- templates/common/vsphere/units/nodeip-configuration.service.yaml
We had a report that podman failed to pull the image, possibly because
the service came up before the interface that had access to the
registry, and as a result the service failed. This results in crio
and kubelet starting without an explicit IP set, which may cause
problems in some environments.
Ideally we would set Restart=on-failure in the unit file, but it looks
like the version of systemd we have right now is too old to support
that. Instead, add an infinite loop around the podman command so it
will retry indefinitely and prevent the deployment from continuing
without proper configuration. Once podman completes successfully it
will break the loop and end the oneshot.
> Add retry loop to nodeip-configuration service

- templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
- templates/common/baremetal/files/NetworkManager-resolv-prepender.yaml
- templates/common/baremetal/units/nodeip-configuration.service.yaml
- templates/common/openstack/files/NetworkManager-resolv-prepender.yaml
- templates/common/openstack/units/nodeip-configuration.service.yaml
- templates/common/ovirt/files/NetworkManager-resolv-prepender.yaml
- templates/common/vsphere/files/NetworkManager-resolv-prepender.yaml
- templates/common/vsphere/units/nodeip-configuration.service.yaml
The nodeip-configuration service used in on-premise platforms needs to
follow proxy settings otherwise it may not be able to download
container image.
> Bug 1851344: Pass proxy settings nodeip-configuration service for baremetal, vsphere, openstack

- pkg/daemon/update.go
- pkg/daemon/update_test.go
No need for these to be exported out of the package since the package
itself is the only user.
> pkg/daemon: unexport pkg functions/structs

- templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
- templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
- templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
Currently we see two ugly messages in the keepalived logs when
starting the service:
WARNING - default user 'keepalived_script' for script execution does
not exist - please create.
and
SECURITY VIOLATION - scripts are being executed but script_security
not enabled.
This patch adds the enable_script_security and script_user options to
our keepalived.conf to suppress those messages.
Add configuration options to clean up keepalived warnings.
> [baremetal & friends] Clean up keepalived script warnings

- go.sum
- lib/resourceapply/machineconfig_test.go
- pkg/controller/bootstrap/bootstrap_test.go
- pkg/controller/bootstrap/testdata/bootstrap/99_openshift-machineconfig_master.yaml
- pkg/controller/bootstrap/testdata/bootstrap/99_openshift-machineconfig_worker.yaml
- pkg/controller/common/helpers.go
- pkg/controller/common/helpers_test.go
- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/container-runtime-config/helpers.go
- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
- pkg/controller/kubelet-config/kubelet_config_features.go
- pkg/controller/kubelet-config/kubelet_config_features_test.go
- pkg/controller/render/render_controller.go
- pkg/controller/render/render_controller_test.go
- pkg/controller/template/render_test.go
- pkg/daemon/daemon.go
- pkg/daemon/daemon_test.go
- pkg/daemon/update.go
- pkg/daemon/update_test.go
- pkg/server/api.go
- pkg/server/server.go
- pkg/server/server_test.go
- test/e2e/mcd_test.go
- test/helpers/helpers.go
Based on https://github.com/openshift/machine-config-operator/pull/1703, this is a (messy and hacky) MCO that renders all existing configs to spec 3. Currently tested to work with a default install upgrading to this.
Unit and e2e tests not included
> *: Ign spec 3 upgrade

- templates/common/_base/files/etc-networkmanager-dispatcher.d-90-long-hostname.yaml
- templates/common/_base/files/usr-local-sbin-set-valid-hostname.yaml
- templates/common/_base/units/node-valid-hostname.service
This aims to fix all the edge-cases around invalid hostnames. This can
include:
- localhost as the hostname
- a static hostname larger than 63 characters
- slow reverse DNS hostname discovery
Previously, there was a node-valid-hostname.service, but it only ensured
that the hostname was not localhost. When running in the initramfs,
NetworkManager will truncate the hostname at 64 characters resulting in
the `node-valid-hostname.service` checks succeeding (!localhost) but
still invalid for the cluster. This change consolidates the logic used by
the dispatcher script _and_ the systemd unit into a library script that
is used by both.
This fix is not ideal, but it seems like the best path that be
backported to 4.3 and 4.5.
Fixes BZs 1844613, 1845885, 1853400, 1853584 (and probably more)
> Bug 1853584: templates: node hostnames: ensure RHCOS hostnames are mostly valid

- cmd/machine-config-daemon/pivot.go
- pkg/daemon/daemon.go
- pkg/daemon/osrelease.go
- pkg/daemon/update.go
- pkg/daemon/update_test.go
This is required for Fedora CoreOS installs, which set
`mitigations=auto,nosmt` and may enable cgroups v2
in the future so it has to be allowed to disable it explicitly.
/cc @runcom @vrutkovs
> Add kernel arg tuneable allowlist for FCOS

- templates/common/_base/units/zincati.service.yaml
This disables Zincati updates on FCOS nodes - no-op on RHCOS.
> templates/common/_base/units: disable Zincati service

- lib/resourcemerge/machineconfig.go
- pkg/controller/template/render.go
- pkg/operator/sync.go
- pkg/operator/sync_test.go
infra.Status.PlatformStatus is *PlatformStatus and in some <4.5.x setups this entire thing is empty and only platform is set to none. So when we hit the switch statement in the MCO we panic bc pointers, so check that it's really there before you do the switch stmt case comparisions.  Before my fix, the unit test I added failed with same panic, now it passes and func returns false.  This behavior was seen in bm clusters updating from 4.4.12->4.5.2, which is also when Platform was deprecated in favor of PlatformStatus and the MCO was missing the check. The checks do exist in the MCC transitioning them to the new type.
As for why we saw this with users but not in CI, AFAIK there isn't an e2e metal upgrade job accounting for this anywhere and I believe the existing metal job would just …
> Bug 1858026: add nil check for infra.Status.PlatformStatus in isCloudConfigReqd

- pkg/operator/bootstrap.go
It doesn't make much sense to set the executable bit only for group
and other, and this causes problems for services like keepalived
that won't start if the executable bit is set on their config file.
> Change manifest file mode to 0644

- templates/common/_base/units/ovs-vswitchd.service.yaml
- templates/common/_base/units/ovsdb-server.service
Set Restart=always in service files
By manually killing the ovs-vswitchd process on rhcos and verifying
it gets started automatically by systemd.
OVS services (openvswitch and ovsd-bserver) are run without the
--monitor option. As a result, when the underlying daemon gets
killed by SIGTERM, the process is not automatically restarted
unless the Restart tag is set to always. This is critical for
system services such as OVS which need to be always up for traffic
forwarding. This fixes BZ: 1854801
> Bug 1854801: Make sure openvswitch related services are always restarted

- templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
- templates/master/00-master/openstack/files/openstack-haproxy.yaml
- templates/master/00-master/ovirt/files/ovirt-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
In some cases, we noticed that HAProxy static pod starts running before NM resolv prepend script[1] was applied,
as a result of that the pod's resolv.conf file doesn't point to the local Coredns instance.
In this case, HAProxy pod (actually it's haproxy-monitor container) will fail to retrieve information
from api-int:kube-apiserver (because local Coredns instance his the one that resolves api-int).
With this PR the resolv.conf used by haproxy-monitor should be always synced with node's resolv.conf
[1] https://github.com/openshift/machine-config-operator/blob/master/templates/common/baremetal/files/NetworkManager-resolv-prepender.yaml
> Bug 1849432: [baremetal] verify resolv.conf in HAProxy static pod synced with host resolv.conf

- templates/common/_base/files/etc-networkmanager-dispatcher.d-90-long-hostname.yaml
- templates/common/_base/files/usr-local-sbin-set-valid-hostname.yaml
- templates/common/_base/units/node-valid-hostname.service
templates: ensure RHCOS node hostnames are mostly valid
This aims to fix all the edge-cases around invalid hostnames. This can include:
- localhost as the hostname
- a static hostname larger than 63 characters
- slow reverse DNS hostname discovery
- truncated hostname in initramfs discovery that is 64 characters long
Fixes BZ 1855878
Includes commits:
- cb12bb855b7493f9b1a23dbe9ed13d5dbaa70d51
- cf2db93410f23d3a5099ed6e619cb286affff538
- 9ddd20dcbe04e90df97b6abcdf511ceef3ec1170
> [release 4.5] Bug 1855877: cherry-pick hostname fixes

- pkg/operator/sync.go
- pkg/operator/sync_test.go
backport of https://github.com/openshift/machine-config-operator/pull/1935
infra.Status.PlatformStatus is *PlatformStatus and in some <4.5.x setups this entire thing is empty and only platform is set to none. So when we hit the switch statement in the MCO we panic bc pointers, so check that it's really there before you do the switch stmt case comparisions. Before my fix, the unit test I added failed with same panic, now it passes and func returns false. This behavior was seen in bm clusters updating from 4.4.12->4.5.2, which is also when Platform was deprecated in favor of PlatformStatus and the MCO was missing the check. The checks do exist in the MCC transitioning them to the new type.
As for why we saw this with users but not in CI, AFAIK there isn't an e2e metal upgrade job accounting …
> Bug 1858907: add nil check for infra.Status.PlatformStatus in isCloudConfigReqd

- manifests/baremetal/keepalived.conf.tmpl
- manifests/baremetal/keepalived.yaml
- pkg/operator/assets/bindata.go
- templates/common/baremetal/files/baremetal-keepalived.yaml
- templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
- templates/worker/00-worker/baremetal/files/baremetal-keepalived-keepalived.yaml
The current deployment workflow relies on the network allowing multicast traffic for VRRP management of the VIP addresses, with this PR keepalived supports both unicast and multicast modes.
To enable unicast keepalived, keepalived.conf in each node should include all the relevant nodes
(including the bootstrap node ) IP addresses, to support this requirement the bootstrap node will run
a simple server that will return its IP address, rest of nodes details will be retrieved from kube-apiserver.
The keepalived mode (unicast or multicast) controlled by 'ENABLE_UNICAST' environment variable, it's set by default to multicast.
> [baremetal] Update keepalived to support both multicast and unicast modes (default=multicast)

- pkg/daemon/update.go
Manual backport of https://github.com/openshift/machine-config-operator/pull/1781 to fix conflict
> Bug 1845494: daemon: fix restoring file logic to avoid unnecessary deletion

- pkg/operator/sync.go
We will be updating this with a more robust nil check later tp avoid these piecemeal checks in the next Sprint I believe, but this fixes the last outstanding platformStatus nil check.
No backport this func is new in 4.6.
> Bug 1859230: operator/sync: update getIgnitionHost to account for nil PlatformStatus

- cmd/machine-config-daemon/pivot.go
- go.sum
- pkg/daemon/daemon.go
- pkg/daemon/kernelargs.go
This commits ensures kernel args modifications from /etc/pivot/kernel-args
are being applied on both pivot and firstboot_complete_machineconfig. Currently its only applied on bootstrap (which uses `pivot`), but not on masters/workers. In order to archieve that kargs tuning logic is moved from `cmd/` package to `pkg/daemon`.
OKD requires this so that "mitigations" karg could be removed from cmdline,
as MachineConfig's `kernelArguments` doesn't support removing existing arguments. This should also affect OCP with HyperThreading off, as machineconfigs for that still use `/etc/pivot/kernel-args`
> Update kernel args on firstboot-complete

- templates/common/baremetal/files/baremetal-coredns.yaml
- templates/common/baremetal/files/baremetal-mdns-publisher.yaml
- templates/common/openstack/files/openstack-coredns.yaml
- templates/common/openstack/files/openstack-mdns-publisher.yaml
- templates/common/ovirt/files/ovirt-coredns.yaml
- templates/common/ovirt/files/ovirt-mdns-publisher.yaml
- templates/common/vsphere/files/vsphere-coredns.yaml
- templates/common/vsphere/files/vsphere-mdns-publisher.yaml
Currently both the coredns and mdns-publisher init containers are
named "render-config". This makes it impossible to tell at a glance
which belongs to which service. This change appends the name of the
service to the init container name so it is clear which service the
container is configuring.
Give coredns and mdns-publisher init containers unique names so it
is clear which service they belong to.
> [baremetal & friends] Give coredns and mdns-publisher init containers unique names

- Makefile
- test/e2e/mcd_test.go
- test/e2e/utils_test.go
Refactor mco e2e tests and reduce time of the e2e tests by ~50% by removing duplicative tests & using custom pools. Current runtime based on this PR is ~55m for the mco e2e tests to run down from ~100min.
> tests/e2e: Refactor and reduce test run time 

- pkg/operator/sync.go
For UPI workflow installer not set the vSphere platform [1] when no API / Ingress VIP are provided
by the user as they intend to setup their own load balancing etc.
Therefore we should make sure we check for nil vSphere platform.
[1]: https://github.com/openshift/installer/blob/c72e5026b06e8d810fb8f911c6ece8ada7d4c957/pkg/asset/manifests/infrastructure.go#L150-L157
> vsphere: check for nil platform in getIgnitionHost

- manifests/openstack/coredns-corefile.tmpl
- manifests/ovirt/coredns-corefile.tmpl
- manifests/vsphere/coredns-corefile.tmpl
- pkg/operator/assets/bindata.go
- templates/common/openstack/files/openstack-coredns-corefile.yaml
- templates/common/ovirt/files/ovirt-coredns-corefile.yaml
- templates/common/vsphere/files/vsphere-coredns-corefile.yaml
This is applying the change from #1767 to the other platforms that
use mdns. To my knowledge it hasn't been reported as a problem on
any of them, but it's still good to do for consistency and to avoid
sending multicast traffic to interfaces that don't need it.
> Set NonVirtualIP in non-baremetal mdns platforms

- templates/common/_base/files/configure-ovs-network.yaml
- templates/common/_base/units/ovs-configuration.service.yaml
- templates/master/00-master/gcp/units/openshift-gcp-routes.service.yaml
OVN-k8s needs to be able to move the primary NIC of the host into the
OVS bridge, making the physical NIC essentially a Layer 2 port. This
patch uses nmcli to configure OVS with the NIC on it, as well as bring
up the Layer 3 OVS interface. The configuration can be auto-detected
based on the existing default gateway interface or NM configuration key
files may be provided during ignition and placed on the host.
> Configure OVS NIC for OVN

- pkg/controller/common/constants.go
- pkg/controller/node/node_controller.go
- pkg/controller/node/node_controller_test.go
- pkg/daemon/daemon.go
- test/e2e/mco_test.go
Prep work for  https://github.com/openshift/machine-config-operator/pull/1946 - basically stubbing out infrastructure.  See patches for details.
> Controlplane upgrades prep

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
This was initially made critical, but that seems to be overkill so move to warning (probably should have been from the start). Prom rules are going to be refactored, so will bake in more nuance at that time.
> Bug 1861876: telemetry: change MCDDrainErr from critical to warning

- test/e2e/mcd_test.go
It seems the kernel-rt-core package may change uname -a
content. In older package it included substring PREEMPT RT
which we were using to determine that current booted kernel
in rt kernel.
This changed recently to PREEMPT_RT, due to which tests started
failing. Hopefully just checking for PREEMPT is sufficient.
> test/e2e: check that kernel-rt-core pacakge is installed

- templates/common/_base/files/configure-ovs-network.yaml
Previously we were only looking at IPv4 for default routes. This also
looks for IPv6 if IPv4 is not found. This patch also includes a fix for
jq returning null when it fails to read, which we were not previously
checking for.
> Add missing IPv6 support for OVN/OVS config

- docs/ContainerRuntimeConfigDesign.md
- docs/KubeletConfigDesign.md
- manifests/master.machineconfigpool.yaml
- manifests/worker.machineconfigpool.yaml
- pkg/controller/bootstrap/testdata/bootstrap/master.machineconfigpool.yaml
- pkg/controller/bootstrap/testdata/bootstrap/worker.machineconfigpool.yaml
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
- pkg/operator/assets/bindata.go
- test/helpers/helpers.go
Today the master/worker MCP does not have any different labels.
This means that if e.g. a user wants to add a kubeletconfig, they
must first create a label for the pool and target the kubeletconfig
against the label. This PR creates a default label for master/worker
pools to skip that step.
> pools: add default label for master/worker pool

- cmd/machine-config-daemon/pivot.go
- pkg/daemon/daemon.go
- pkg/daemon/pivot/types/imageinspection.go
- pkg/daemon/rpm-ostree.go
- pkg/daemon/rpm-ostree_test.go
- pkg/daemon/update.go
- pkg/daemon/update_test.go
As we are waiting on e2e-gcp-upgrade test go green, this PR is built on top of https://github.com/openshift/machine-config-operator/pull/1941 and hence includes commits from PR#1941 too.
Don't know how merge works, perhaps PR#1941 goes in first and then rebase this PR again or github does all the magic.
> cleanup unused code as a result of extensions and OS update rework

- pkg/operator/bootstrap.go
Previously the cloud provider config map was sourced from the `.spec.cloudConf` of the infrastructure object.
but to enable user input and stitching explained in [1] and [2], we added a controller to generate a cloud configuraration using the spec
for use by kubelet and kube cloud controller manager. The new API defined in [3] creates a config map `openshift-config-managed/kube-cloud-config` with
the configuration in `cloud.conf` key. We updated the in-cluster MCO to use the new API [4] but the MCO on bootstrap host was left untouched because the controller
could not generated on the bootstrap host yet.
But [5] and [6] intend to provide the same generated config map on the bootstrap host for MCO, and therefore we need the bootstrap MCO to read the key defined by
the generated API but …
> Bug 1864677: operator/bootstrap: use correct key for generated cloud conf

- manifests/baremetal/keepalived.yaml
- pkg/operator/assets/bindata.go
- templates/common/baremetal/files/baremetal-keepalived-flip-mode.yaml
- templates/common/baremetal/files/baremetal-keepalived.yaml
Starting from 4.6 Keepalived will run in unicast mode by default, in case of upgrade to 4.6 the Keepalived configuration
should be updated to run in unicast mode.
But since multicast and unicast are considered as separate Keepalived domains and will
not interoperate, the updated configuration should be simultaneously reloaded in all the relevant
Keepalived instances. This option is feasible since the nodes run NTP.
In upgrade process, the Keepalived config already generated by the previous SW version, so Keepalived will
continue first to run in a mode determined in accordance with the existing config file.
The MCO should render a new file (/etc/keepalived/monitor.conf) in all nodes, this file will trigger a synchronized
configuration update, the content of the file will determine the …
> bug 1865308 : [baremetal] Create conf file to flip Keepalived mode to unicast post-upgrade

- pkg/daemon/daemon.go
- pkg/daemon/daemon_test.go
- pkg/daemon/update.go
We don't need to do this special casing anymore.  This
corner case only arises for the synthetic `e2e-gcp-upgrade`
test, and we actually want to test the OS update path there.
Closes: https://github.com/openshift/machine-config-operator/issues/1964
> Bug 1852047: daemon: Remove "compare digest" code for OS updates

- pkg/daemon/update_test.go
My IDE warns about this - it's the only warning.
> tests: Fix capitalization

- templates/common/vsphere/files/vsphere-hostname.yaml
- templates/common/vsphere/units/vsphere-hostname.yaml
This PR enables UPI to support MachineSets.
The hostname of the VMware Guest must be set for
CSR approval to work correctly and the node to join the cluster.
Cherry-pick https://github.com/openshift/machine-config-operator/pull/1894
> bug 1861773: Remove IPI checks for vsphere hostname script and systemd unit

- templates/common/_base/files/iptables-modules.yaml
We need to load the iptables modules so that containers can use the legacy iptables interface.  Since 4.4 uses v2 Ignition, I needed to add fields to conform to the older format when I did the backport.
Backport of a change to make RHCOS load the iptables compatibility modules.
With this, the egress router pods should work.
We need to load the iptables modules so that containers can use the legacy iptables interface.
> [release-4.4] Bug 1855895: templates: add a file to load legacy iptables

- go.mod
- pkg/daemon/image-inspect.go
- pkg/daemon/rpm-ostree.go
- pkg/daemon/update.go
This PR fixes:
1. Fallback to podman copy when oc fails to extract image
2. Fallback to podman inspect if imageInspect doesn't work
2. Reduce oc and imageInspect retry to 2. Time to retry grows exponentially, so let's keep a balance.
> Bug 1862979: daemon: fallback to podman copy when oc fails to extract image

- pkg/server/api.go
- pkg/server/api_test.go
Makes the API inspect the Accept header instead of the User-Agent to
derive the Ignition config spec version it has to serve.
e2e CI
api: Derive spec version to serve from Accept header instead of User-Agent
> Bug 1866743: api: Detect spec version to serve from Accept header

- templates/common/_base/files/etc-networkmanager-dispatcher.d-90-long-hostname.yaml
- templates/common/_base/files/usr-local-sbin-set-valid-hostname.yaml
- templates/common/_base/units/node-valid-hostname.service
templates: ensure RHCOS node hostnames are mostly valid
This aims to fix all the edge-cases around invalid hostnames. This can include:
- localhost as the hostname
- a static hostname larger than 63 characters
- slow reverse DNS hostname discovery
- truncated hostname in initramfs discovery that is 64 characters long
Fixes BZs 1844613, 1845885, 1853400, 1853584 (and probably more)
Includes commits:
- cb12bb855b7493f9b1a23dbe9ed13d5dbaa70d51
- cf2db93410f23d3a5099ed6e619cb286affff538
- 9ddd20dcbe04e90df97b6abcdf511ceef3ec1170
> [release 4.4] Bug 1855878:  cherry-pick hostname fixes

- docs/MachineConfiguration.md
We don't want to encourage users to install kernel-devel
as an extension in BaseOS. Preferred way is to install
it in a development build container.
> Bug 1866693: docs: drop kernel-devel from supported extensions

- pkg/daemon/update.go
I was surprised we weren't logging anything related to this when
I went to double-check the node state while working on
https://github.com/openshift/origin/pull/25362
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1861095
> Bug 1861095: daemon: Log when we validate that FIPS is on

- templates/common/_base/files/etc-zincati-configd-90-disable-feature.yaml
- templates/common/_base/units/zincati.service.yaml
Disabling zincati update feature still requires ostree labels. OKD is using ostree dev overlay to create a new commit, so it not yet possible to add basearch label required by Zincati
Fixes https://github.com/openshift/okd/issues/219
> [fcos] templates/common/_base: disable Zincati service via dropin

- templates/common/_base/files/configure-ovs-network.yaml
- templates/common/_base/units/ovs-configuration.service.yaml
Deploying with multiple NICs will end up placing all NICs on the same
default NM connection. If one of these interfaces fails to DHCP or does
not DHCP in time during boot, NM-wait-online will fail (even though 1
NIC may have DHCP'ed correctly). Therefore the ovs-configuration service
should not require NM-wait-online, but we should wait until it is
completed and we do want it. However, if it fails we still try to to
check the system if a default gateway is present.
Additionally, since multiple NICs may share the same NM connection, we
cannot always just bring it down. Instead, change the behavior to just
disconnect the NIC and then bring up the higher priority connection
later to preserve the default NM connection.
> Bug 1867392: Fixes multiple NICs OVN/OVS config

- docs/OSUpgrades.md
Various updates/clarifications here.  (If anyone wants to
do nontrivial edits, feel free to toss this into a hackmd.io
doc and we can collaborate!)
> docs/OSUpgrades.md: Update/reword

- templates/common/_base/units/ovs-configuration.service.yaml
Run OVS configuration only after the machine has pivoted. This is crucial for OKD installs which uses standard FCOS image with no OVS pre-installed.
> Configure OVS after firstboot is done

- pkg/daemon/update.go
We had an event when we were starting an OS update, but nothing
when it was completed - one could implicitly get that by looking
at the next event, but that's a bit fragile.
And since then we started doing a lot more stuff with the OS,
so let's add an event emitted before and after all OS changes
so we can consistently get e.g. timing information about it.
Relates to https://github.com/openshift/machine-config-operator/pull/1962
around getting better data about timing during upgrades.
> Bug 1852047: daemon: Add events before/after all OS changes

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Added a temporary directory for cri-o to read hooks dir, so a node powercycle would allow hooks to be recreated rather than use old state
Note: this needs https://github.com/cri-o/cri-o/pull/4052 which should be in nightlies soon. It will probably fail before that
> Bug 1835145: crio: add temporary hooks directory

- templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
- templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
- templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
- templates/master/00-master/openstack/files/openstack-haproxy.yaml
- templates/master/00-master/ovirt/files/ovirt-haproxy-haproxy.yaml
- templates/master/00-master/ovirt/files/ovirt-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
This is a backport of the 4.5 fix #1724 by @cybertron 
(cherry picked from commit 022933c07a4e37bed097f1cd1fa4cd2d637decc0)
Per [0], the /readyz endpoint is how the api communicates that it
is gracefully shutting down. Once /readyz starts to report failure,
we want to stop sending traffic to that backend. If we wait for
/healthz, it may be too late because once /healthz starts failing
the api is already not accepting connections.
I also moved the liveness probe for haproxy itself to use a /readyz
endpoint for consistency. This isn't strictly necessary, but I think
it will be less confusing if there aren't multiple health check
endpoints in the config.
0: https://github.com/openshift/installer/pull/3537
> Bug 1840366: [baremetal] Switch to /readyz for haproxy healthchecking

- pkg/daemon/update.go
- pkg/daemon/update_test.go
To keep kernel argument processing simpler and bug free,
let's first delete all kernel arguments which has been
applied by MCO previously and append all of the kernel
arguments present in new rendered MachineConfig.
This prevents bugs like https://bugzilla.redhat.com/show_bug.cgi?id=1866546
Also, adjust unit test for kernel arguments
> Bug 1866546: daemon: simplify kernel arguments processing

- pkg/daemon/daemon.go
- pkg/daemon/metrics.go
xref https://bugzilla.redhat.com/show_bug.cgi?id=1854009
Using the err message as a label introduces a bug in resetting the metrics to 0 when the kubelet health returns to normal.
Test by ssh'nig into node, stopping kubelet, waiting for alert to fire, restart kubelet, ensure the alert goes away and the `mcd_kubelet_state` metric returns to 0.
@runcom
> Bug 1854009: remove err cardinality from mcd_kubelet_state metrics

- templates/common/baremetal/files/baremetal-keepalived.yaml
- templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
- templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
- templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
- templates/master/00-master/baremetal/files/baremetal-keepalived-script-both.yaml
- templates/master/00-master/baremetal/files/baremetal-keepalived-script.yaml
We're having some issues in ci with api flakiness that appear to be
related to VIP failover. In order to reduce the need to do failovers
during normal circumstances, we want to leave the VIP alone as long
as the loadbalanced api endpoint on the node is responding. Currently
if the local api service on a node stops responding it will trigger
a failover. This is unnecessary since in most cases haproxy will
continue to distribute the traffic while the local api restarts.
In order to get this behavior, the chk_ocp vrrp_script is split in
two. The reason for this is that we still want to handle the case
where all haproxy instances in the cluster go down, but at least
one api service is still functional. One check looks at the haproxy
endpoint only. This one has a higher weight since it's the …
> "Bug 1823950: [baremetal] Don't failover api vip if loadbalanced endpoint is responding"

- cmd/machine-config-operator/bootstrap.go
- cmd/machine-config-operator/start.go
- install/0000_80_machine-config-operator_04_deployment.yaml
- install/image-references
- lib/resourcemerge/machineconfig.go
- manifests/controllerconfig.crd.yaml
- pkg/apis/machineconfiguration.openshift.io/v1/types.go
- pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
- pkg/controller/bootstrap/testdata/bootstrap/machineconfigcontroller-controllerconfig.yaml
- pkg/controller/template/constants.go
- pkg/controller/template/render.go
- pkg/controller/template/render_test.go
- pkg/operator/assets/bindata.go
- pkg/operator/bootstrap.go
- pkg/operator/operator.go
- pkg/operator/sync.go
- templates/common/_base/units/machine-config-daemon-pull.service.yaml
- templates/master/00-master/_base/files/etcd-ca.yaml
- templates/master/00-master/_base/files/etcd-metric-ca.yaml
This PR removes various etcd related assets and functions that are no longer used. Once these changes merge we will followup with the installer removing the related etcd flags against MCO render command.
Then to close this effort out one for PR will be needed to remove kube-client-agent from manifests. The reason for this is we need to remove the references to kube-client-agent before we remove reference to the image or installer will fail.
>  Bug 1868117: cleanup: remove legacy etcd bits

- templates/common/_base/files/configure-ovs-network.yaml
When the vmxnet3 driver gets added to ovs, it does not
honor the promiscuous mode setting for multicast traffic.
This PR adds support to temporarily fix that by configuring
the allmulti flag on the interface when it's moved to ovs.
> Bug 1869886: Fix to configure vmxnet3 driver in multicast mode

- templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
The high value for `timeout http-keep-alive` was probably messing with
the `[sig-api-machinery] API data in etcd should be stored at the
correct location and version for all resources [Serial]` test causing
it to fail frequently on OpenStack platform.
It's also better to have consistency between platforms.
This reverts commit d34b2750341f90163bf92be7bfe017f28811be7b.
> Bug 1871970: OpenStack: Align haproxy config with other on-prem platforms

- pkg/daemon/controlplane.go
- pkg/daemon/coreos.go
- pkg/daemon/daemon.go
- pkg/daemon/pivot/utils/run.go
- pkg/daemon/pivot/utils/run_test.go
- pkg/daemon/update.go
- templates/master/00-master/_base/units/rpm-ostreed.service.yaml
Part of solving #1897
A lot more details in https://hackmd.io/WeqiDWMAQP2sNtuPRul9QA
The TL;DR is that the `bfq` I/O scheduler better respects IO priorities,
and also does a better job of handling latency sensitive processes
like `etcd` versus bulk/background I/O .
> Bug 1850057: Use bfq scheduler on control plane, idle I/O for rpm-ostreed

- pkg/controller/common/helpers.go
- pkg/controller/common/helpers_test.go
During rendering of rendered-configs for the pools, specify spec
version if the first merged machineconfig does not contain an ignition
snippet, and ignore other machineconfigs without an ignition snippet.
Fixes an issue where if the last alphanumerical machineconfig doesn't
contain an explicit ignition spec version, the ignition Merge() function
merges the final config to have no spec version, degrading the MCO.
> Bug 1872313: controller: improve merging of MCs during rendering

- pkg/operator/render.go
It prevents the user from breaking the cluster network when configuring an invalid value.
1. oc patch networks.config.openshift.io cluster -p \{\"spec\":\{\"networkType\":\"bad\"\}\} --type=merge
Expect no reboot triggered by MCO
Watching the `networkType` in the status of  Network.config.openshift.io if it
is not empty, otherwise use the value in spec.
> Bug 1868536: Watching the networkType in the status of  Network.config.openshift.io

- manifests/machineconfigcontroller/events-clusterrole.yaml
- manifests/machineconfigcontroller/events-rolebinding-default.yaml
- manifests/machineconfigcontroller/events-rolebinding-target.yaml
- pkg/controller/node/node_controller.go
- pkg/controller/node/status.go
- pkg/operator/assets/bindata.go
- pkg/operator/sync.go
A while ago I'd invested some time in tweaking the
node controller to have useful logs around what it's
doing; my first "point of contact" when looking at
upgrades was its pod logs. But...we lose most
those on upgrade since the pod gets killed.
Add events to the node controller too.
Currently the MCD emits useful events which
can be queried afterwards (in our CI runs we
dump `events.json`).
With this we can create a "journal/history"
for upgrade/update events just by querying the
event stream.
> Bug 1852047: controller: Emit events

- templates/common/_base/files/configure-ovs-network.yaml
RHEL7 does not have 'jq' by default or a version of the ip command that supports the
"-j" option. To support RHEL7 worker nodes it is required to remove the unsupported actions
from the setup scripts
Signed-off-by: Jacob Tanenbaum <jtanenba@redhat.com>
Fixes: 1867992
Run the script in the yaml on a RHEL7 system with ovs installed and an updated network manager (so far not in an official release https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=30784728#)
> Bug 1867992: Support RHEL7 workers by removing 'jq' commands from ovs setup

- pkg/controller/node/node_controller.go
Added a log message that is written when the machine config pool is Paused, but is also updating. This message is written when the machine config pool status is being calculated .
1. Configure worker machine config to be 'Paused'
2. Update the 99-worker-ssh machine config with a new SSH key
3. Wait for worker pool to progress to Updating
4. Check machine-config-controller logs for an entry like: W0818 19:49:38.503997 10 status.go:94] Pool worker is Paused, but is 'Updating'. Pool will not progress
Logs a warning when a machine config pool is Paused, but also updating
> Bug 1869876: Cluster upgrades silently stall when machine config pools are paused

- pkg/controller/container-runtime-config/container_runtime_config_controller.go
Fixes #1858277 (https://bugzilla.redhat.com/show_bug.cgi?id=1858277)
Add a check for the version hash to ensure that we resync
and generate a new controller version during an upgrade.
Update the way we append the status for a ctrcfg as well -
ensure that we don't have mutliple of the same status recorded.
Add a check to avoid adding the same mc name more than once in
the list of finalizers. When we update an existing ctrcfg, the
generation number changes causing a resync and we don't need to add
the same name to the list of finalizers every time this happens.
And remove the check for cri-o drop-in files.
1. Create a 4.5 cluster
2. Create a ctrcfg CR on it and apply it to both master and worker …
> Bug 1858277: Check the version hash so we resync on an upgrade

- cmd/machine-config-daemon/pivot.go
- pkg/daemon/daemon.go
- pkg/daemon/rpm-ostree.go
- pkg/daemon/update.go
We perform operations like rt-kernel switch from packages
available in the latest machine-os-content to which we are going
to rebase OS. It makes sense to overlay additional
packages after performing OS rebase. This also prevents issues
like missing dependencies which may be now already part of BaseOS.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1861026
> Bug 1861026: daemon: perform other rpm-ostree operations after OS rebase

- templates/common/_base/files/configure-ovs-network.yaml
Some users may have manually configured ipv4/v6 addresses on their
interfaces. This patch adds support for handling that case when moving
the interface into OVS. Support for more advanced network configuration,
including VLANs or bonds will not be handled by this script and will
require ignition NM key files.
> Bug 1866602: OVS Configuration: handle static IP ifaces

- templates/common/openstack/units/afterburn-hostname.service.yaml
To prevent possible race conditions with ovn-kubernetes we need to set hostnames before network-online.target and node-valid-hostname.service
> Bug 1851540: OpenStack: set hostnames on early stages of machine provisioning

- cmd/machine-config-operator/bootstrap.go
- install/image-references
Removed unused flags and images for etcd, cluster-etcd-operator and kube-client-agent.
Install or upgrade a cluster. MCO should come up fine without the removed flags.
Remove unused flags and images needed in the past for etcd.
> Bug 1813012: Remove the unused flags and images used in the previous releases for etcd

- pkg/controller/common/helpers.go
- pkg/server/api.go
- pkg/server/bootstrap_server.go
- pkg/server/cluster_server.go
- pkg/server/server.go
- pkg/server/server_test.go
There's no need to parse the whole ignition section from the MC every
time we're about to append a file in the MCS. This leads to a performance
regression when the ignition section contains a lot of files as
discovered in https://bugzilla.redhat.com/show_bug.cgi?id=1866117
compared to pre 4.5.
Also removed some parse call where it's obvious that in code we're
dealing with a particular version and there's no need to test against
something we know it can't be.
> Bug 1866117: pkg/server: reduce calls to ignition parse

- templates/common/_base/units/machine-config-daemon-pull.service.yaml
See https://bugzilla.redhat.com/show_bug.cgi?id=1870343
Pulling the image can flake, we need to retry.  Today the
bootstrap node will retry indefinitely, see
https://github.com/openshift/installer/blob/18e286bfc0120142a480f6239191e90c6bf69d4f/data/data/bootstrap/files/usr/local/bin/release-image-download.sh.template
Let's do the same.  It's not elegant but eh.
> Bug 1870343: machine-config-daemon-pull: Retry pulling image

- lib/resourcemerge/core.go
- manifests/machineconfigdaemon/daemonset.yaml
- pkg/daemon/update.go
- pkg/operator/assets/bindata.go
With the introduction of extensions and reworking of OS updates in
https://github.com/openshift/machine-config-operator/pull/1941,
we now run `oc/podman` directly in the MCD to fetch the OS image.
Thus we need to inject the proxy env vars into the container via the
daemonset definition, otherwise image pulls will fail.
> Bug 1857162: daemon: inject proxy vars into MCD container

- lib/resourcemerge/machineconfig.go
Born in 4.1 clusters have Platform and EtcdDiscoveryDomain in their ControllerConfigSpec both deprecated: Platform(Infra.Status.PlatformStatus.Type) and EtcdDiscovery(Infra.Status.EtcdDiscoveryDomain)
As such on upgrade to 4.6 the upgrade was failing as Infra was empty.
This PR syncs Infra in the ControllerConfigSpec to allow the 4.1 clusters to update and upgrade successfully.
> Bug 1861404: sync Infra in ControllerConfigSpec

- pkg/controller/common/helpers.go
- pkg/controller/container-runtime-config/container_runtime_config_controller.go
Backport of https://github.com/openshift/machine-config-operator/pull/1984
Fixes #1873321 (https://bugzilla.redhat.com/show_bug.cgi?id=1873321)
Add a check for the version hash to ensure that we resync
and generate a new controller version during an upgrade.
Update the way we append the status for a ctrcfg as well -
ensure that we don't have mutliple of the same status recorded.
Add a check to avoid adding the same mc name more than once in
the list of finalizers. When we update an existing ctrcfg, the
generation number changes causing a resync and we don't need to add
the same name to the list of finalizers every time this happens.
And remove the check for cri-o drop-in files.
1. Create a 4.5 …
>  Bug 1873321: Check the version hash so we resync on an upgrade

- templates/worker/01-worker-kubelet/baremetal/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/openstack/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/vsphere/units/kubelet.service.yaml
Patch at https://github.com/openshift/machine-config-operator/pull/1817
addressed the drift of kubelet configuration for control plane nodes but
didn't update compute nodes' kubelet to catch up changes made to the
main kubelet unit.
We're currently missing a number of fixes for the worker nodes on
Baremetal, OpenStack and vSphere platforms:
- https://bugzilla.redhat.com/show_bug.cgi?id=1823967
- https://bugzilla.redhat.com/show_bug.cgi?id=1806027
- https://bugzilla.redhat.com/show_bug.cgi?id=1828622
This change sync the custom kubelet unit files accross platforms.
> Bug 1874448: [BM, OpenStack, vSphere]: Sync compute kubelet

- templates/worker/00-worker/ovirt/files/ovirt-disable-tx-checksum-offload.yaml
This PR removes the disable checksum workaround that was created due to https://bugzilla.redhat.com/show_bug.cgi?id=1794714
Signed-off-by: Gal-Zaidman <gzaidman@redhat.com>
> Bug 1820305: remove disable checksum workaround for workers

- templates/common/_base/units/ovs-configuration.service.yaml
In ipv6 deployments on baremetal we're seeing the following sequence
when deploying nodes:
* node-valid-hostname runs
* node gets a hostname, so node-valid-hostname succeeds
* ovs-configuration runs
* it unconfigures the physical interface so it can be added to the
bridge. When this happens, NetworkManager removes the hostname that
was set using the DHCP address on that interface, which puts us
back at localhost.localdomain
* kubelet starts, sees localhost.localdomain and madness ensues
* the node gets its hostname back using the address now on br-ex
This means all nodes try to register as localhost.localdomain, which
obviously does not work. This change switches the ordering of
ovs-configuration and node-valid-hostname so that ovs-configuration
has to run before node-valid-hostname …
> Bug 1875388: Have ovs-configuration.service run before node-valid-hostname

- pkg/controller/template/constants.go
- pkg/operator/bootstrap.go
- pkg/operator/sync.go
- templates/common/_base/units/machine-config-daemon-pull.service.yaml
Splitting this out from https://github.com/openshift/machine-config-operator/pull/2011 so we can test/review it independently.
I *think* this will work although I find the split between `RenderConfigImages` and `ControllerConfigImages` confusing because it certainly looks like we will use both of them when rendering both `manifests/` and `templates/`.
> Bug 1868158: machine-config-daemon-pull: Use the MCO image

- templates/common/baremetal/files/NetworkManager-resolv-prepender.yaml
- templates/common/openstack/files/NetworkManager-resolv-prepender.yaml
- templates/common/ovirt/files/NetworkManager-resolv-prepender.yaml
- templates/common/vsphere/files/NetworkManager-resolv-prepender.yaml
We copy /var/run/NetworkManager/resolv.conf to /etc/resolv.conf for the case that /etc/resolv.conf is not present, but if it is present we override it.
On oVirt this causes the api-int to not be resolvable for a short period of time, causing failures and events.
This PR adds a check to override cp only if it is not present.
Notice that at the end of this script we replace it with a new file anyway but that is ok.
** Sent this fix to all the platforms that have similar logic to be consistent
Signed-off-by: Gal-Zaidman <gzaidman@redhat.com>
Added a check to see if /etc/resolv.conf exist before overriding it
Check if /etc/resolv.conf is present before overriding at the beginning of NetworkManager-resolv-prepender
> Bug 1876216: Check if /etc/resolv.conf is present before overriding

- pkg/controller/common/helpers.go
- pkg/daemon/update.go
Support installing OS Extensions on FCOS nodes too.
TODO:
/cc @LorbusChris @sinnykumari
> Bug 1877448: pkg/daemon/update: allow installing os-extensions on FCOS

- cmd/machine-config-daemon/start.go
This way we know in the systemd journal that it's the MCO making
changes, as distinct from any other process running `rpm-ostree`
as a binary.
I added this in 1e08e0c02a692d7749651636e23d6f56c0191be9
but then it was removed in a99a12315e422bc46cf95d3b9dcceeb87bd1f69e
Came up as part of https://bugzilla.redhat.com/show_bug.cgi?id=1865839
so we can more easily identify which other project is calling rpm-ostree.
> Bug 1865839: daemon: Set RPMOSTREE_CLIENT_ID again

- pkg/daemon/update.go
Right now, we `cleanup -p` if we hit an error. But if we hit another
error during the cleanup, we lose what the original error was. Let's log
it to help debugging.
Related: rhbz#1865839
> Bug 1865839: daemon/update: print error causing rollback

- templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
Fixes: #1874399 
Added `podman image pull` prior to `podman create` command.
Install a new machine and try to add it to the etcd cluster using etcd-recover.sh shell script.
For a new machine, the images are not already pulled, and therefore need an explicit `image pull` command before attempting to create a container using that image.
> Bug 1874399: Pull the image using authfile before creating the container layer

- templates/common/openstack/files/openstack-keepalived.yaml
- templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
- templates/master/00-master/openstack/files/openstack-haproxy.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-script-both.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-script.yaml
This ports #1893 to OpenStack platform, together with the dependent #1124 PR, and fixes from #1508 and #1604, and a sprinkle of #1768 on top.
> Bug 1875005: OpenStack: Don't failover api vip if loadbalanced endpoint is responding

- templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
This is not a complete fix for bug 1872632. However, regardless of the approach taken there, it seems like there needs to be some way for platform-none UPI users to override an incorrect guess by kubelet regarding the node IP. Currently we allowing overriding it (based on `nodeip-configuration.service`) in bare metal IPI, openstack, and vsphere, but not anywhere else.
This just patches the _base kubelet service files so that if `KUBELET_NODE_IP` has been set, somewhere, we pass it to kubelet. It does not actually provide any simple way to set it yet. (`nodeip-configuration.service` won't work on UPI because it requires there to be an apiserver VIP.)
The idea of making `--node-ip` configurable was somewhat rejected in #944 although in that case it was clear that the user only needed it to …
> Bug 1872632: allow overriding kubelet --node-ip in the _base templates

- templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
- templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
Since we moved to keepalived healthchecking against haproxy, we want
haproxy to handle most failures so the VIP doesn't have to move.
However, previously the time it took for haproxy to recognize an
outage on a node was longer than it was for keepalived, which resulted
in the VIP moving before haproxy removed the failing backend.
This change makes the haproxy interval 1 second, so it should notice
outages in 2 seconds or less (because it has a fall value of 2).
The keepalived interval is changed to 2, which means it will detect
failures in 2 to 4 seconds (also a fall value of 2). This means
haproxy should deal with api outages before keepalived does and
allow the VIP to stay on the same node.
> Bug 1823950: Reverse haproxy and keepalived check timings

- templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml
Azure hosts cannot hairpin back to themselves over a load
balancer. Thus, we need to redirect traffic to the apiserver vip to
ourselves via iptables. However, we should only do this when our local
apiserver is running.
Previously it was added support for host network only, adding the
same iptables rules in PREROUTING we apply the same rules for pods.
Signed-off-by: Antonio Ojea <aojea@redhat.com>
> Bug 1878794: handle azure vips for pods

- templates/common/baremetal/files/NetworkManager-resolv-prepender.yaml
- templates/common/openstack/files/NetworkManager-resolv-prepender.yaml
- templates/common/ovirt/files/NetworkManager-resolv-prepender.yaml
- templates/common/vsphere/files/NetworkManager-resolv-prepender.yaml
If /etc/resolv.conf existed but didn't have nameservers, the prepender
wouldn't copy the resolv.conf.
Check that either resolv.conf does not exist OR does not contain nameservers
> Bug 1879156: Check that resolv.conf actually has nameservers

- install/0000_80_machine-config-operator_06_clusteroperator.yaml
- pkg/operator/status.go
MCO holds kubelet config, which leads to node creation.  This adds node collection for related resources because the MCO configuration has a direct impact on the node resources.
> bug 1878129: add node collection for oc adm inspect

- templates/common/_base/files/etc-networkmanager-dispatcher.d-90-long-hostname.yaml
hostnamectl previously refused to assign a long hostname. Since
hostnamectl now allows for longer hostnames, we need to alway check if
the hostname is too long.
Fixes BZ #1872885
> Bug 1872885: always check hostname char count

- templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
Since we moved to keepalived healthchecking against haproxy, we want
haproxy to handle most failures so the VIP doesn't have to move.
However, previously the time it took for haproxy to recognize an
outage on a node was longer than it was for keepalived, which resulted
in the VIP moving before haproxy removed the failing backend.
This change makes the haproxy interval 1 second, so it should notice
outages in 2 seconds or less (because it has a fall value of 2).
The keepalived interval is changed to 2, which means it will detect
failures in 2 to 4 seconds (also a fall value of 2). This means
haproxy should deal with api outages before keepalived does and
allow the VIP to stay on the same node.
This ports
https://github.com/openshift/machine-config-operator/pull/2075/ to
OpenStack platform.
> Bug 1875005: OpenStack: Reverse haproxy and keepalived check timings

- pkg/controller/kubelet-config/kubelet_config_features.go
- pkg/controller/kubelet-config/kubelet_config_features_test.go
To install a dual-stack cluster you must set the IPv6DualStack feature gate at install time. MCO currently does not process feature gates provided as install-time manifests and so the bootstrap configs will not match the post-install configs and the operator will become Degraded because the masters are stuck unable to move to the expected config.
As it happens, kubelet does not use the IPv6DualStack feature gate unless you are using dockershim, so to work around this problem for now, just ignore that feature gate when generating the kubelet config, so that the "real" generated config will match the config expected by the bootstrap code.
(Not yet tested, but I think this will fix things in 4.6, and then it can be reverted and fixed correctly in 4.7, since kubelet will need the feature gate …
> Bug 1881057: ignore the IPv6DualStack feature gate for the kubelet config

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
@smarterclayton @mrunalp @nee1esh @derekwaynecarr 
xref https://issues.redhat.com/browse/OCPNODE-402
> Bug 1881208: add alert for system.slice rss going over system-reserved

- pkg/controller/common/helpers.go
- pkg/controller/common/helpers_test.go
In spec 2 MC merging, the passwd user sections are merged into each
other. This means in practice that there will be multiple entries
for a "core" user if you define multiple ssh keys via multiple MCs.
This will fail the translation to spec 3 upon upgrading, so we need
to also de-duplicate this section by merging sshkeys into one "core"
user. Also add explicit check for other users here (since we don't
support them).
> Bug 1880603: controller/helpers.go: de-duplicate ign spec 2 passwdUsers

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Fixes #1874671 (https://bugzilla.redhat.com/show_bug.cgi?id=1874671)
Dropping this list will also drop the NET_RAW and SYS_CHROOT
capabilities from the default list.
Log onto a node and run `crio config`, the list of default_capabilities returned should not have NET_RAW and SYS_CHROOT in it.
Drop default_capabilities list from the crio template
> Bug 1874671:  Drop the default_capabilities list from the crio template

- templates/common/vsphere/files/vsphere-keepalived.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
- templates/master/00-master/vsphere/files/vsphere-keepalived-script-both.yaml
- templates/master/00-master/vsphere/files/vsphere-keepalived-script.yaml
Ports #1893 to the vSphere platform.
vSphere CI is experiencing the issues described in the above
PR.
> Bug 1881137: vSphere: don't failover api vip if lb is responding

- templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
#2088 was broken because I tried to use shell syntax in a systemd unit file where shell syntax isn't parsed _and_ I forgot that kubelet will just treat a bogus `--node-ip` value (eg, passing literally `--node-ip='${KUBELET_NODE_IP:-}'`) the same as not passing any value so my assumption that it would break CI if it was wrong failed.
> Bug 1872632: templates: fix --node-ip override

- manifests/controllerconfig.crd.yaml
- pkg/operator/assets/bindata.go
This was only deprecated in 4.6, and removing it completely in the
same release breaks upgrades of platforms that use the value in
their 4.5 templates. It appears that the controllerconfig is getting
upgraded before the templates, so when MCO goes to re-render the
old templates with the new controllerconfig we end up with a blank
value for EtcdDiscoveryDomain references. This value should stay in
the crd until 4.7 when it can be safely removed because the 4.6
templates no longer have any references to it.
> Bug 1875237: Add etcdDiscoveryDomain back to controllerconfig crd

- templates/common/_base/files/configure-ovs-network.yaml
- templates/common/_base/units/ovs-configuration.service.yaml
Fixes: BZ 1854306
1. Clean NM objects created for ovn-kube shared gateway mode by configure-ovs.sh, when cluster network is openshift-sdn.
2. Render ovs-configuration.service differently for openshift-sdn and ovn-kube.
3. Remove unneeded ovs bridges.
Executing the SDN migration process
Initialize host ovs differently for Openshift-SDN and Ovn-kubernetes
> Bug 1854306: Initialize host ovs differently for Openshift-SDN and Ovn-kubernetes by ovs-configuration.service

- manifests/baremetal/keepalived.conf.tmpl
- manifests/baremetal/keepalived.yaml
- pkg/operator/assets/bindata.go
Keeping the API VIP in the bootstrap node until the bootstrap’s node API goes away eliminates
the need for master nodes to specify the bootstrap as one of their peers in the unicast
Keepalived case, see [1].
Additionally, it makes the deployment flow more deterministic so other components
(e.g: remove the requirement for provisioning static IP, see [2] ) can benefit from it.
[1] https://docs.google.com/document/d/1jPIOYuK1J3PKYS8ff8waHWeHqzgl5OZeOkWngUxHtR8/edit?usp=sharing
[2] https://docs.google.com/document/d/18DVr7Ikw_gSJsiQvG8zV2oBEqlG070MzyIElcK94LJI/edit#
> Bug 1871769: [baremetal] keep API VIP in the bootstrap node until the bootstrap’s node API goes away

- templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
- templates/master/00-master/openstack/files/openstack-haproxy.yaml
- templates/master/00-master/ovirt/files/ovirt-haproxy.yaml
- templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
The Liveness probe of haproxy container monitors the health of the HAProxy LoadBalancer.
Since HAProxy LoadBalancer starts running only after haproxy-monitor container rendered
the config file (which might take 30-40 seconds) the liveness probe of haproxy container
initial timing should be adjusted.
> Bug 1849583: [openstack,bm,ovirt,vsphere] Adjust HAProxy liveness probe to initial timing 

- pkg/daemon/daemon.go
Unconditionally remove this file in the once-from (classic RHEL)
case.  We use this file to suppress things like kubelet and SDN
starting on CoreOS during the firstboot/pivot boot, but there's
no such thing on classic RHEL.
> Bug 1882667: daemon: Unlink encapsulated config in once-from mode

- templates/common/openstack/files/openstack-keepalived.yaml
- templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
- templates/master/00-master/openstack/files/openstack-haproxy.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-script-both.yaml
- templates/master/00-master/openstack/files/openstack-keepalived-script.yaml
Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/2077 to release-4.5.
> Bug 1881147: OpenStack: Don't failover api vip if loadbalanced endpoint is responding

- templates/common/_base/units/nodeip-configuration.service.yaml
#2088 / #2100 updated kubelet.service to allow manually overriding the node IP on bare metal UPI (to deal with the fact that kubelet's node IP autodetection does the wrong thing in the presence of ovn-kubernetes now). This finishes this fix by running an updated version of the nodeip-configuration service to _automatically_ override the IP.
Two open questions:
1. What should trigger this? Currently the patch says `{{ if eq .Infra.Status.PlatformStatus.Type "None" }}`, which covers the reporter's use case, but if we wanted to just _always_ bypass kubelet's not-very-good node-IP-detection code, we should check `{{ if eq cloudProvider "" }}`. (ie, in that case we would always pass _either_ a non-empty `--cloud-provider`, causing kubelet to get the IP from the CloudProvider; _or_ a non-empty …
> Bug 1872632: templates: add nodeip-configuration.service for bare metal UPI

- templates/common/_base/units/ovs-configuration.service.yaml
With RHEL 7 worker nodes, network service and NetworkManager will both
exist. network service runs after NetworkManager and may interfere with
ovs-configuration service. Therefore ensure we run ovs-configuration
after network.service is done.
> Bug 1882667: Make ovs-configuration wait for network.service

- templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
When updating vSphere for baremetal changes
of keepalived and haproxy I missed the interval change
for haproxy backend masters.
> Bug 1881137: vsphere - update haproxy interval

- templates/worker/00-worker/baremetal/files/baremetal-keepalived-keepalived.yaml
- templates/worker/00-worker/openstack/files/openstack-keepalived-keepalived.yaml
- templates/worker/00-worker/ovirt/files/ovirt-keepalived-keepalived.yaml
- templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
This commit wraps chk_ingress script with timeout to workaround [1]
[1] https://github.com/acassen/keepalived/issues/1364
> Bug 1883508: [ Baremetal and friends] wrap Keepalived chk_ingress script with timeout

- templates/common/gcp/files/etc-networkmanager-conf.d-hostname.yaml
In cases where NetworkManager can set an otherwise invalid cluster
hostname, but valid for NM (between 63 and 65 characters),
NetworkManager will bypass the dispatcher hook.
This config tells NetworkManager to not set the transient hostname.
Instead, the dispatcher.d hook script will set the hostname.
Signed-off-by: Ben Howard <ben.howard@redhat.com>
> Bug 1872885: add template for NM to not manage hostname on GCP

- manifests/baremetal/keepalived.conf.tmpl
- manifests/baremetal/keepalived.yaml
- pkg/operator/assets/bindata.go
- templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
Now that the cluster is grown from boostrap to the master nodes, it
should make the clustering easier if we just keep the API vip in the
bootstrap until we're done bootstrapping.
We used to transition the API VIP to the master nodes as soon as
we could. This was necessary with the way Etcd used to cluster. Now
that the clustering starts with the bootstrap node and grows to the
master nodes, it should be possible to reduce deployment instability
by keeping the VIP in the bootstrap until the bootstrap is taken down.
Make a deployment and see that the clustering succeeds.
Keep API VIP in the bootstrap while it exists.
> baremetal: bootstrap api vip until down

- templates/common/_base/files/configure-ovs-network.yaml
In CNO, we have no reliable way to detect if OVS should be running in
systemd or not. Using systemd or dbus is unreliable from the containers.
Checking for file existence is not foolproof because MCO lays the files
down before it reboots into 4.6. This patch makes ovs-configuration
write a file when it executes. We can use this to detect if we should
expect OVS to be running in systemd.
> Bug 1880591: Make ovs-configuration write a file

- templates/common/_base/files/etc-systemd-system.conf.d-10-default-env-godebug.conf.yaml
This sets GODEBUG=x509ignoreCN=0 system wide.
To verify install a cluster with this patch, confirm that your environment variables contain the expected value. Something like this.
```
$ oc debug node/ip-10-0-141-152.us-west-2.compute.internal
Starting pod/ip-10-0-141-152us-west-2computeinternal-debug ...
To use host binaries, run `chroot /host`
Pod IP: 10.0.141.152
If you don't see a command prompt, try pressing enter.
sh-4.4# chroot /
sh-4.4# systemctl show-environment
GODEBUG=x509ignoreCN=0
sh-4.4# cat /etc/systemd/system/test.service
[Service]
ExecStart=echo $GODEBUG
sh-4.4# systemctl start test.service
sh-4.4# journalctl -lu test.service
-- Logs begin at Tue 2020-10-06 20:58:26 UTC, end at Tue 2020-10-06 23:47:25 UTC. --
Oct 06 23:47:23 ip-10-0-141-152 systemd[1]: Started …
```
> Bug 1882191: Add GODEBUG=x509ignoreCN=0 to systemd DefaultEnvironment

- pkg/daemon/rpm-ostree.go
- pkg/daemon/update.go
When an error occurs during rpm-ostree operation, we get
returned error as exit status 1 which is not much useful.
Actual failure gets printed on the stdout which we capture
in runGetOut() function.
> Bug 1865839: daemon: better error reporting for rpm-ostree operations

- pkg/controller/kubelet-config/kubelet_config_controller.go
Fixes #1849543 (https://bugzilla.redhat.com/show_bug.cgi?id=1849543) 
The uid was being used as the entry for the finalizer list
but everytime an update happens it generates a new uid, which
is why we were ending up with multiple uids in the finalizers
list. So use the mc name for the list of finalizer instead as
the mc name stays the same for each kubelet config.
1) Start a cluster with this patch and create a kubeletconfig CR. The description of the CR should not have duplicate entries in the list of finalizers.
2) Start a cluster without this patch and create a kubeletconfig CR - there will be multiple entries in the list of finalizers. Upgrade the cluster to a version with this patch, the list …
> Bug 1849543: Use mc name as finalizer for kubelet config

- docs/README.md
Updated the example to include the directives documented here: https://docs.openshift.com/container-platform/4.5/installing/install_config/installing-customizing.html#installation-special-config-crony_installing-customizing
Without rtcsync in particular an alert called NodeClockNotSynchronising will trigger in Openshift, as discussed in Case 02763639 
Apply the example as is (with a valid NTP server) and the alert will fire.
Fix example to include directives required for alerting
> Fix example to include directives required for alerting

- pkg/controller/common/helpers.go
- pkg/controller/container-runtime-config/container_runtime_config_controller.go
Backport of https://github.com/openshift/machine-config-operator/pull/2034
Fixes #1875821 (https://bugzilla.redhat.com/show_bug.cgi?id=1875821)
Add a check for the version hash to ensure that we resync
and generate a new controller version during an upgrade.
Update the way we append the status for a ctrcfg as well -
ensure that we don't have mutliple of the same status recorded.
Add a check to avoid adding the same mc name more than once in
the list of finalizers. When we update an existing ctrcfg, the
generation number changes causing a resync and we don't need to add
the same name to the list of finalizers every time this happens.
1. Create a 4.3 cluster
2. Create a ctrcfg CR on it and apply it …
> [release-4.4] Bug 1875821: Check the version hash so we resync on an upgrade

- templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
On FCOS boot OS extensions are being installed, so in order to use
only shipped RPMs and avoid pulling in updates from public repos existing
repos need to be removed.
TODO:
Keeping this on hold until updated OKD machine-os-content is promoted
> Bug 1884165: firstboot.service: disable existing repos before pivot

- cmd/machine-config-controller/main.go
- cmd/machine-config-controller/start.go
- pkg/controller/bootstrap/bootstrap.go
- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/container-runtime-config/helpers.go
- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Fixes #1856529 (https://bugzilla.redhat.com/show_bug.cgi?id=1856529)
Split out the default_capabilities list from the default.conf
file to a spearate drop-in file under /etc/crio/crio.conf.d.
cri-o enables the NET_RAW and SYS_CHROOT capabilities by default
in the config the MCO lays down. We want to drop these capabilities,
but need to make sure that we don't break existing clusters by doing so.
Thus, split out the default capabilities list to its own drop-in file and
create an MC for it. This way, the user has the ability to delete this MC
once they believe that removing these capabilities will not affect their
cluster.
We will drop this logic in the following version as the capabilities
MC would have already been created. It will then be up to the user on
when they want …
> [release-4.5] Bug 1856529: Create a drop-in file for cri-o's default_capabilities

- templates/common/_base/files/configure-ovs-network.yaml
With UPI installs, openvswitch package is not installed until after
upgrade. In the ovs-configuration.service there is a Requires
declaration on openvswitch.service. However due to a bug in systemd,
ovs-configuration is started even when openvswitch.service is not
present:
https://bugzilla.redhat.com/show_bug.cgi?id=1888017
As a workaround, this patch checks to ensure OVS is installed in
configure-ovs.sh.
> Bug 1887040: OVS config: check if OVS is installed

- manifests/machineconfigdaemon/daemonset.yaml
- pkg/operator/assets/bindata.go
This daemonset is not critical to availability like SDN or DNS pods therefore
allow maxUnavailable to scale with cluster size. This roughly increases rollout
speed by 10x on a 250 node cluster.
How to verify this, provision a cluster with 20 or more hosts. Confirm that updates
to the machine-config-daemonset allows for up to 10% to update at once but otherwise
operates normally.
> Bug 1867608: ds/machine-config-daemon: Set maxUnavailable 10%

- pkg/server/api.go
- pkg/server/bootstrap_server.go
- pkg/server/cluster_server.go
- pkg/server/server.go
- pkg/server/server_test.go
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1890250
Basically adding new workers during the window when:
- control plane has upgraded to 4.6 (actually more precisely, the machine-config-server)
- worker pool is still rolling out
Will fail for clusters whose bootimage is older than 4.6 because
the MCD-on-host will find the `3.1.0` version in
`/etc/ignition-machine-config-encapsulated.json`
and barf.
> Bug 1890250: mcs: Ensure that the encapsulated config is spec 2 if requested

- go.sum
- pkg/server/api.go
- pkg/server/bootstrap_server.go
- pkg/server/cluster_server.go
- pkg/server/server.go
- pkg/server/server_test.go
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1890250
Basically adding new workers during the window when:
- control plane has upgraded to 4.6
- worker pool is still rolling out
Will fail for clusters whose bootimage is older than 4.6 because
the MCD-on-host will find the `3.1.0` version in
`/etc/ignition-machine-config-encapsulated.json`
and barf.
> Bug 1890362: mcs: Ensure that the encapsulated config is spec 2 if requested

- install/0000_80_machine-config-operator_01_machineconfig.crd.yaml
- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_features.go
- pkg/daemon/daemon.go
- pkg/daemon/update.go
In ignition spec 3, the File.Contents.Source was changed to a pointer,
thus causing a panic when it is nil when we dereference during decodes.
Also explicitly reject Append sections of Ignition File sections, since
they are not supported anyways and should fail eventually.
> Bug 1879283: *: add nil check when decoding File.Contents.Source

- go.sum
- pkg/server/server_test.go
In between the master and 4.6 PRs I added more unit testing;
this "forward ports" the additional unit testing to master.
At the time I didn't re-push to the master PR because I didn't want to
re-trigger CI, but now we can.
> server: More unit testing for MCS Ignition version

- pkg/server/bootstrap_server.go
- pkg/server/cluster_server.go
- pkg/server/server.go
- pkg/server/server_test.go
There's no need to parse the whole ignition section from the MC every
time we're about to append a file in the MCS. This leads to a performance
regression when the ignition section contains a lot of files as
discovered in https://bugzilla.redhat.com/show_bug.cgi?id=1866117
compared to pre 4.5.
> Bug 1874815: pkg/server: reduce calls to ignition parse

- templates/common/_base/files/configure-ovs-network.yaml
When we add the bond port OVS connection it needs to use type bond
instead of ethernet. Similarly VLAN needs type vlan as well as some
extra arguments.
> Bug 1887545: Fix ovs-configuration detecting bond and vlan interfaces

- pkg/daemon/update.go
- test/e2e/mcd_test.go
In the previous implementation, an extension was one to one
mapping with the package it would install on the host. This can
become confusing if enabling an extension would require
installing multiple sets of packages which are not install
time dependency.
Also added e2e test for kernel-devel extensions
> Bug 1890074: daemon: allow an extension to install group of packages

- Dockerfile.rhel7
Updating ose-machine-config-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-machine-config-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating ose-machine-config-operator builder & base images to be consistent with ART

- templates/common/_base/files/configure-ovs-network.yaml
Cherry-pick of https://github.com/openshift/machine-config-operator/pull/2154 on 4.6
With UPI installs, openvswitch package is not installed until after
upgrade. In the ovs-configuration.service there is a Requires
declaration on openvswitch.service. However due to a bug in systemd,
ovs-configuration is started even when openvswitch.service is not
present:
https://bugzilla.redhat.com/show_bug.cgi?id=1888017
As a workaround, this patch checks to ensure OVS is installed in
configure-ovs.sh.
> Bug 1887607: OVS config: check if OVS is installed

- pkg/daemon/update.go
FCOS does one to one mapping of extension to package
to be installed on FCOS node. This is needed as OKD
layers additional packages on top of official FCOS shipped,
See https://github.com/openshift/release/blob/959c2954344438c4eed3ec7f52a5e099e8335516/ci-operator/jobs/openshift/release/openshift-release-release-4.7-periodics.yaml#L586
In future, once the package list has been stabilized,
we can make use of the group and add all the packages required
to enable OKD as a single extension.
> Bug 1890074: daemon: allow one to one mapping of extension on OKD

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
- pkg/daemon/metrics.go
- pkg/daemon/update.go
This fix does the following:
- fixes bug where node name was missing for MCDDrainErr
- reduces cardinality of MCDDrainErr via set err messages & value
- adds a duration to the metric (15m) to give time for the failed drain to resolve
- fixes labels on other metrics (minor)
This fixes some Drain metric pain points have have been going on forever..
see: https://bugzilla.redhat.com/show_bug.cgi?id=1866873#c3 for screenshot
> Bug 1866873: update MCDDrainErr to reduce cardinality & fix nodename

- templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
Since we eliminate the need for the master nodes to know the bootstrap IP address
for unicast Keepalived, we can delete BootstrapIP from Keepalived template.
> [Baremetal] Remove BootstrapIP from Keepalived template

- go.sum
- pkg/controller/node/status.go
- pkg/controller/node/status_test.go
If a pool is paused, we can't be `Updating=True`.  Fixes a UX
issue as administrators want to use pool pausing to more
finely control updates.
> controller: Reflect pool paused status in Updating

- pkg/daemon/update.go
It accidentally got removed in https://github.com/openshift/machine-config-operator/commit/6757381f09358f05fe5eefedfa85480ce09b3720#diff-349c0748c3f52201852d3027c29daf618b45300b949482728df6666a3f9ba245L1325 . Thanks to @kikisdeliveryservice for noticing this.
> Bug 1892448: daemon: add back metrics for pivot error

- templates/common/baremetal/files/baremetal-NetworkManager-kni-conf.yaml
- templates/common/baremetal/files/baremetal-kni-tmpfiles.yaml
- templates/common/baremetal/units/baremetal-system-connections-mount.yaml
This does 4 things for the baremetal platform:
1. Configures NetworkManager to look for it's keyfiles in /etc/NetworkManager/system-connections-merged
2. Creates that directory
3. Adds two temporary directories for systemd-tmpfiles to process. These are the storage and work locations for the overlay.
4. Mount an overlay filesystem at /etc/NetworkManager/system-connections-merged that uses /etc/NetworkManager/system-connections as the lower filesystem, and the temporary directory as the upper.
Any changes made outside of a MachineConfig will result in it being ephemeral. This maintains the idea that MCO will own the configuration of a machine before kubelet runs. MCO changes would go into /etc/NetworkManager/system-connections.
**- Description for …
> [baremetal] Create and enable overlay mount point for NetworkManager

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
in cri-o 1.19 we introduced a feature to drop the infra container when a pod doesn't have a pod level PID namespace
We have been running with this option in cri-o internal tests and have seen no issues.
Let's enable it by default in 4.7. In addition to being more performant, it also should aid in a race with the kubelet
win-win!
Have CRI-O drop the infra container in some cases, which performs better
> crio: drop infra container when possible

- templates/master/00-master/_base/files/etcd-root-ca.yaml
This CA is not used by the product and causes confusion.
> templates/master/00-master/_base/files: remove etcd-root-ca

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
This reverts commit 6eb37894974b71080648a92bbb71fd201c5a84f4.
reverts https://github.com/openshift/machine-config-operator/pull/2177, one of two commits that merged before the permafail of e2e-serial on OOMs
> Revert "crio: drop infra container when possible"

- pkg/server/cluster_server.go
The CI cluster hit an issue where a pull secret was broken, and
then we hit a deadlock because the MCO failed to drain nodes on
the old config, because other nodes on the old config couldn't
schedule the pod.
It just generally makes sense for new nodes to use the new config;
do so as long as at least one node has successfully joined the
cluster at that config.  This way we still avoid breaking
the cluster (and scaleup) with a bad config.
xref: https://bugzilla.redhat.com/show_bug.cgi?id=1873288
> Bug 1873288: server: Target the spec configuration if we have at least one node

- manifests/openstack/coredns-corefile.tmpl
- manifests/ovirt/coredns-corefile.tmpl
- manifests/vsphere/coredns-corefile.tmpl
- pkg/operator/assets/bindata.go
- templates/common/openstack/files/openstack-coredns-corefile.yaml
- templates/common/ovirt/files/ovirt-coredns-corefile.yaml
- templates/common/vsphere/files/vsphere-coredns-corefile.yaml
This is the same change as #1879, but applied to the non-baremetal platforms that use coredns-mdns.
> Bug 1890797: Set NonVirtualIP in mdns plugin config

- templates/common/_base/files/configure-ovs-network.yaml
When we add the bond port OVS connection it needs to use type bond
instead of ethernet. Similarly VLAN needs type vlan as well as some
extra arguments.
(cherry picked from commit 64b79dfb1247e480478633f3f383653a6f787d3b)
> Bug 1887596: Fix ovs-configuration detecting bond and vlan interfaces

- templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
KUBELET_LOG_LEVEL was bumped to level 4 to aid in
debugging some issue by node team (see https://github.com/openshift/machine-config-operator/pull/1672).
However customers upgrading to 4.5 in prod, are seeing this bump
causing extra GBs of data to be saved.
Closes: BZ 1895385
> Bug 1895385: Drop kubelet logging back down to level 3

- templates/common/_base/units/nodeip-configuration.service.yaml
The current bash code in the service looks invalid.
```
[root@master-0 ~]# systemctl status nodeip-configuration
● nodeip-configuration.service - Writes IP address configuration so that kubelet and crio services select a valid node IP
Loaded: loaded (/etc/systemd/system/nodeip-configuration.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Wed 2020-11-04 08:22:50 UTC; 22min ago
Process: 980 ExecStart=/bin/bash -c     until    /usr/bin/podman run --rm    --authfile /var/lib/kubelet/config.json    --net=host    --volume /etc/systemd/system:/etc/systemd/system:z    registry.svc.ci.openshift.org/origin/4.6-2020>
Main PID: 980 (code=exited, status=1/FAILURE)
CPU: 4ms
lis 04 08:22:50 master-0 systemd[1]: Starting Writes IP address configuration so that kubelet …
```
> Bug 1894477: Fix bash in nodeip-configuration.service

- pkg/daemon/update.go
- test/e2e/mcd_test.go
- Manually backported PR https://github.com/openshift/machine-config-operator/pull/2170 and https://github.com/openshift/machine-config-operator/pull/2181.
- Both commits (c30db97742a3921e4e3bd2e4ed0a1b6feb0ee7ff and c78925da6d50ad82b485dd28d2df1c3a369051de) has been cleanly cherry-picked.
> Bug 1888853: daemon: allow an extension to install group of packages

- templates/common/_base/files/configure-ovs-network.yaml
The script did
iface=$(ip route show default | awk '{if ($4 == "dev") print $5; exit}')
which is to say:
iface=$(ip route show default | awk '{
if ($4 == "dev")
print $5;
exit
}')
ie, it was unconditionally exiting after the first line (which actually worked most of the time...)
> Bug 1896898: Fix awk syntax in configure-ovs.sh

- pkg/controller/template/render.go
- templates/common/on-prem/files/NetworkManager-mdns-hostname.yaml
- templates/common/on-prem/files/NetworkManager-onprem.conf.yaml
- templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
- templates/common/on-prem/files/coredns.yaml
- templates/common/on-prem/files/keepalived.yaml
- templates/common/on-prem/files/mdns-publisher.yaml
- templates/common/on-prem/units/nodeip-configuration.service.yaml
- templates/common/vsphere/files/etc-systemd-system-crio-stream-address.conf.yaml
- templates/master/00-master/on-prem/files/haproxy.yaml
The VSphere UPI install does not fully populate PlatformStatus. When we deduped
the templates, we didn't account for this being nil. This should render these
templates empty when that PlatformStatus is nil.
> Bug 1895099: Fix VSphere UPI not populating PlatformStatus

- test/e2e/ctrcfg_test.go
- test/e2e/utils_test.go
Waiting for the previous MC isn't right here; we're deleting
a config and so what we want to wait for is the previous pool
target.
Drop the racy `sleep()`.
> Bug 1897361: ctrcfg_test: Wait for our prior target config

- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
controller: cleanup: Remove unnecessary patch methods
CI
controller: cleanup: Remove unnecessary patch methods
/hold
> controller: cleanup: Remove unnecessary patch methods

- pkg/daemon/daemon.go
- pkg/daemon/update.go
Came out of concerns from compliance about having bootloader
entries that may not have expected parameters.
> daemon: Remove rollback deployment

- pkg/controller/container-runtime-config/helpers.go
> Fix CRIO PidsLimit json tag

- templates/common/_base/files/sshd-disable-ssh-key-dir.yaml
On FCOS, this sshd config dropin ensures that only SSH keys from the
`/home/core/.ssh/authorized_keys` file are picked up, and not ones
present in the `/home/core/.ssh/authorized_keys.d/` directory,
which might be written by Ignition and/or Afterburn.
On RHCOS this is a no-op, as it already looks up SSH keys from the
authorized_keys file only.
CI e2e testing
templates: Disable SSH keys lookup from authorized_keys.d on FCOS
/hold
for testing
> templates: Disable SSH keys lookup from authorized_keys.d on FCOS

- pkg/daemon/update.go
- pkg/daemon/update_test.go
Some systemd service settings may be defined in .Storage.Files and in .Systemd.Units.Dropins. Dropins is preferable, so users may want to migrate to the way.
However if a file representing a dropin was defined in .Storage.Files and converted into .Systemd.Units.Dropin in new version of MC, it would be placed by Ignition's dropin implementation and then garbage-collected by MCD's deleteStaleData.
This change ensures we're checking Systemd.Units.Dropins before attempting to remove this file. This is crucial for OKD 4.5 -> 4.6 upgrades - kubelet MCO config was defined as a file in 4.5 and converted into a dropin in 4.6
> Bug 1895360: pkg/daemon: don't delete a file if its replaced with a dropin

- templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
Rebased with the e2e fix https://github.com/openshift/machine-config-operator/pull/2239
Cherry pick of https://github.com/openshift/machine-config-operator/pull/2211
> [release-4.6] Bug 1896329: Drop kubelet logging back down to level 3

- templates/common/_base/files/configure-ovs-network.yaml
Instead of the default OVS interface route metric, which is much lower,
and causes problems when secondary interfaces are added to the machine.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1880259
@trozet @knobunc
> Bug 1880259: ovs-configuration: use NM default ethernet route metric

- templates/master/00-master/_base/files/recycler_pod_bad.yaml
xref https://bugzilla.redhat.com/show_bug.cgi?id=1896226
This is the first step in resolving a bug introduced by https://github.com/openshift/machine-config-operator/pull/1687 and https://github.com/openshift/cluster-kube-controller-manager-operator/pull/405
`/etc/kubernetes/manifests` is the kubelet's static pod manifests directory.  The kubelet will try to start pods defined in this location as static pods.  The recycler pod is not a static pod and the kubelet continuously fails to start it.
The solution is to move the recycler pod manifests to a different directory.
The fix is a 3-step process (as I see it):
- Change location of the recycler pod in the MCO template (this PR)
- Change KCM to use the new location
- Delete (or empty out) the file in the old location
@runcom @sttts …
> templates: move recycler pod out of kubelet manifests directory

- pkg/daemon/update.go
This breaks RHEL7 jobs as they do not have rpm-ostree.
> Bug 1899603: daemon: do not roll back on non-*COS machines

- pkg/daemon/controlplane.go
- pkg/daemon/update.go
Using bfq by default reportedly causes etcd latency regressions
when we're not doing an OS update.  Change the logic so we
only do the switch when we want to balance update speed while running
etcd.
(I still think schedulable masters may want this but they can
configure it manually with a systemd unit)
> Bug 1899600: daemon: Only switch to bfq scheduler when we have an OS update

- manifests/machineconfigcontroller/controllerconfig.yaml
- pkg/controller/bootstrap/testdata/bootstrap/machineconfigcontroller-controllerconfig.yaml
- pkg/controller/render/render_controller.go
- pkg/controller/render/render_controller_test.go
- pkg/daemon/constants/constants.go
- pkg/operator/assets/bindata.go
- pkg/operator/sync.go
Should fix: https://bugzilla.redhat.com/show_bug.cgi?id=1879099
Basically we only want to roll out new machineconfigs if
the controllerconfig (generated by the operator) and the
controller are at matching versions.
Per Jerry's comment in Bugzilla:
> 1. The new MCO rolls out. It first syncs the controllerconfig to the new one as part of the RenderConfig step above.
> 2. The running (old) MCC's template controller has an informer on the controllerconfig, which since the previous step updated the config, calls a syncControllerConfig. This re-generates the base master config (00-master MC)
> 3. The running (old) MCC now sees a MC change which calls another sync call to generate a new rendered config, and instructs the master pool to start an update
> 4. The new MCC rolls out, and does the …
> Bug 1879099: Inject version into controllerconfig, refuse mismatches

- pkg/operator/status.go
- pkg/operator/sync.go
Finally using our Upgradeable operator status which is currently always at true..
One of the biggest problems and compounding issues we see are upgrades rolled out by users when there are already degraded pools. This makes troubleshooting more difficult, makes users think that a previous upgrade is finished an successful and compounds any existings bugs/problems.
This pr finally leverages the upgradeable status so that users can fix their degraded pools before upgrading (which is the easier time) and have the MCO's status be a better reflection of the pools that it manages.
So we end up with Upgradeable = False when pools are degraded and toggle back to Upgradeable = True when no pools are degraded.
> operator: prevent upgrades on degraded pools

- manifests/on-prem/keepalived.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/render.go
The bootstrap node was unconditionally setting the ENABLE_UNICAST
environment variable to yes on all on-prem platforms, causing it to use
unicast_src_ip and unicast_peer settings in keeepalived.conf, while it
should have used the output of the
`onPremPlatformKeepalivedEnableUnicast` function as done on the control
plane nodes.
> Bug 1901472: Only enable unicast mode on platform that asked for it

- docs/FAQ.md
- docs/MachineConfigController.md
- docs/MachineConfigDaemon.md
- docs/PullSecret.md
The ostree link is now broken as the site moved
https://ostree.readthedocs.io now redirects to https://ostreedev.github.io/ and the rest of the path changed, so we end up with a 404.
> docs: Fix broken ostree url

- templates/common/_base/files/configure-ovs-network.yaml
> Bug 1898036: Copy files from NM overlay onto /etc/NetworkManager/system-connections

- templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
In order to have the proxy variables (HTTP_PROXY, HTTPS_PROXY and
NO_PROXY), we need to `export` them otherwise then don't end up being
loaded in the environment and it causes issues if a proxy is used,
when pulling an image from a registry for example.
> Bug 1873556: [on-prem] inject the proxy into the env for NetworkManager.service

- pkg/daemon/daemon.go
- pkg/daemon/update.go
- pkg/daemon/update_test.go
- test/e2e/mcd_test.go
- test/e2e/utils_test.go
- test/helpers/helpers.go
Adds to/supercedes https://github.com/openshift/machine-config-operator/pull/2254
This is the overall PR for the reboot epic work, which aims to allow "rebootless updates" when certain changes happen.
Currently supported:
No action (drain, update files, uncordon)
- ssh keys
- pull secret
Reload crio
- registries.conf changes
Reboot
- all other scenarios
Also add corresponding unit and e2e tests
> daemon: selectively reboot based on diffs of applied MCs

- templates/common/baremetal/files/NetworkManager-static-dhcp.yaml
We have a feature request for nodes to be able to initially get
assigned their IP addresses via infinite DHCP leases, but then to
have those addresses statically configured on the node so that if
the DHCP server is unavailable for any reason they don't lose their
network configuration.
This adds a dispatcher script for NetworkManager that does so. It
looks at the DHCP assigned network settings and adds static
configuration with the same values.
> [baremetal] Add dispatcher script to statically configure DHCP address

- install/0000_80_machine-config-operator_00_clusterreader_clusterrole.yaml
- install/0000_80_machine-config-operator_00_namespace.yaml
- install/0000_80_machine-config-operator_00_service.yaml
- install/0000_80_machine-config-operator_01_containerruntimeconfig.crd.yaml
- install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
- install/0000_80_machine-config-operator_01_machineconfig.crd.yaml
- install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml
- install/0000_80_machine-config-operator_02_images.configmap.yaml
- install/0000_80_machine-config-operator_03_rbac.yaml
- install/0000_80_machine-config-operator_04_deployment.yaml
- install/0000_80_machine-config-operator_05_osimageurl.yaml
- install/0000_80_machine-config-operator_06_clusteroperator.yaml
- install/0000_90_machine-config-operator_00_servicemonitor.yaml
- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
This implements phase 1 of openshift/enhancements#482
> Annotate manifests for single-node-developer cluster profile

- pkg/constants/constants.go
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
- pkg/controller/template/render.go
- pkg/controller/template/render_test.go
- pkg/controller/template/template_controller_test.go
- pkg/operator/render.go
- templates/master/00-master/_base/files/apiserver-url-env.yaml
A few components need to know the URL of the internal apiserver load balancer. Most notably, the network operator does.
Right now, the only way to get this is to parse the kubelet's kubeconfig, but this is fragile. So, write down an environment file that just sets the "usual" service environment variables. Then we can just seamlessly source the environment file.
Ref: [SDN-1347](https://issues.redhat.com/browse/SDN-1347)
> templates: add apiserver-url.env file

- manifests/on-prem/coredns.yaml
- manifests/on-prem/keepalived.yaml
- pkg/operator/assets/bindata.go
- templates/common/on-prem/files/coredns.yaml
- templates/common/on-prem/files/keepalived.yaml
Now that we are using the loadbalanced endpoint for keepalived
healthchecks, it is not correct to be using the local apiserver for
readiness checks. Also, I don't think there's any need for readiness
checks on the monitor. Kubernetes isn't routing any traffic to this
pod, so its ready status is meaningless.
> [baremetal and friends] Drop unnecessary readiness probes

- pkg/daemon/daemon.go
- pkg/daemon/kernelargs.go
- pkg/daemon/osrelease.go
- pkg/daemon/update.go
- pkg/daemon/update_test.go
A whole lot of our conditionals were "is coreos or not".  Let's rework
things so that we explicitly use that.
Detecting based on the operating system ID is also generally wrong;
e.g. we had an "is this traditional rhel or centos" check that really wanted to be
"is this a rhel7-like system" because both "traditional" RHEL8 and CentOS8 exist.
>  daemon: Rework operating system conditionals

- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/container-runtime-config/helpers.go
A new option, containerRuntimeSearchRegistries, has been added
to the images.config.openshift.io CRD. Implement this new option
in the ctrcfg controller so that when users set this in the cluster
wide Image CR, we create a drop-in file at /etc/containers/registries.conf.d
that sets unqualified-search-registries to the given list. This overwrites
the unqualified-search-registries list in registries.conf and lets the user
decide specify which registries to check when using short names for an image.
This PR is for the UnqualifiedSearchRegistries support epic.
Start a 4.7 cluster and add the `containerRuntimeSearchRegistries` field to the cluster wide Image CR. Once that deploys, you should see a …
> Create drop in file for ContainerRuntimeSearchRegistries

- templates/common/vsphere/files/vsphere-hostname.yaml
- templates/common/vsphere/units/vsphere-hostname.service.yaml
In Fedora 33, a change was introduced to set the hostname to "fedora" as a fallback instead of the default "localhost", so the current script does not work in OKD as NM will assign the fallback hostname.
This change makes it so the hostname is set to vSphere's
guestinfo.hostname if that's defined, before NetworkManager is started.
> templates: Set vSphere hostname from guestinfo before NM starts

- templates/common/_base/files/configure-ovs-network.yaml
Adds copying over the dhcp client-id as well as bond options from the interface being migrated over to OVS.
> Bug 1899350: Include dhcp client-id and bond options during ovs-configuration

- pkg/operator/sync.go
When installed on C2S regions on AWS, a CA bundle is needed for communication with the AWS API. This CA bundle will be placed in the kube-cloud-config ConfigMap in the openshift-config-managed namespace. When that ConfigMap is present, the machine-config-operator assumes that it will contain a cloud provider config in the "cloud.conf" key. However, for AWS, the cloud provider config is not required.
With these changes, the machine-config-operator will accept a ConfigMap that does not have the "cloud.conf" key. The MCO will still error when the "cloud.conf" key is absent for a platform where the cloud provider config is required.
https://issues.redhat.com/browse/CORS-1584
Add a cloud-provider-config ConfigMap in the openshift-config namespace. Verify …
> operator: allow kube-cloud-config cm with CA data but no cloud config

- templates/common/baremetal/files/NetworkManager-static-dhcpv6.yaml
If infinite leases are used on initial boot, we will attempt to
modify the default connection because OVNKubernetes hasn't created
the br-ex bridge yet. We want to wait for that to happen, so if
we see that we're operating on the default "Wired Connection" id
then we want to exit the script.
> Bug 1904124: [baremetal] Add check for default connection id to static DHCPv6 script

- templates/common/baremetal/files/NetworkManager-resolv-prepender.yaml
- templates/common/openstack/files/NetworkManager-resolv-prepender.yaml
- templates/common/ovirt/files/NetworkManager-resolv-prepender.yaml
- templates/common/vsphere/files/NetworkManager-resolv-prepender.yaml
Note: manual cherry-pick of #2266 (bot can't handle git conflicts)
In order to have the proxy variables (HTTP_PROXY, HTTPS_PROXY and
NO_PROXY), we need to `export` them otherwise then don't end up being
loaded in the environment and it causes issues if a proxy is used,
when pulling an image from a registry for example.
Signed-off-by: Emilien Macchi <emilien@redhat.com>
(cherry picked from commit f41b1d2ae7feea9aedfbd62143baefdf950c8569)
> Bug 1904065: [on-prem] export proxy variables to be taken in account

- install/0000_80_machine-config-operator_01_containerruntimeconfig.crd.yaml
- install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
All ctrcfgs must have a spec and containerruntimeconfig all kubelet configs and all kubeletconfigs should have a spec (but as the new loglevel  was added as same level, kubeletruntimeconfig not required)
> Bug 1886636: update ctrcfg crd to make spec & containerruntimeconfig required

- pkg/daemon/daemon.go
- pkg/daemon/rpm-ostree.go
- pkg/daemon/rpm-ostree_test.go
- templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
See https://bugzilla.redhat.com/show_bug.cgi?id=1888565
for one instance of this.  Since the DBus activation timeout is 25s
but the systemd timeout is 90s, let's defer to the latter by explicitly
starting the service.  (This is slightly racy because rpm-ostreed
auto-exits on idle, but when we go to send the DBus message we'll
auto-activate again if really necessary).
Also tell systemd we're going to need the service via the
firstboot unit file.
> Bug 1888565: daemon: Explicitly start rpm-ostreed

- pkg/daemon/daemon.go
- pkg/daemon/rpm-ostree.go
- pkg/daemon/rpm-ostree_test.go
- templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
Reverts openshift/machine-config-operator#2291
assisted-installer is running MCD inside custom podman container as once from[1].
Reverting this PR until better consider once from usage.
/cc @cgwalters 
[1] https://github.com/openshift/assisted-installer/blob/e3c999d9f16f8c8e9fa6d4105591da33ad84fc62/src/installer/installer.go#L218-L224
> Revert "Bug 1888565: daemon: Explicitly start rpm-ostreed"

- pkg/daemon/constants/constants.go
- pkg/daemon/daemon.go
- pkg/daemon/update.go
Remove the hardlink to multi-user.target and instead invoke systemctl
to directly enable/disable units as needed, so [Install] - wantedby
sections are properly parsed.
Also call systemctl preset on units that are deleted/changed, to
ensure "rollback" of unit enablement to system defaults. Remove
the Ignition-written preset file to account for this.
> Bug 1885365: daemon: properly handle unit enable/disables

- pkg/daemon/daemon.go
- pkg/daemon/update.go
See https://bugzilla.redhat.com/1907333
Doing this when the MCD lands on a node the first time means
we compete for I/O with lots of other containers, and on
slow systems that can cause a timeout.  Then a further
problem is that we were fatally erroring out in the MCD
rather than retrying.
But we don't have control loop in the MCD today outside of
trying to apply an update; let's defer this until we add one.
> Bug 1907333: daemon: Revert code to remove rollback

- templates/common/on-prem/files/keepalived.yaml
Currently, if keepalived stops responding for any reason but the
process is still there, we will never notice because the previous
version of /tmp/keepalived.data will still be present in /tmp.
This change writes the fault string to keepalived.data before doing
the kill -s SIGUSR1 so that we assume failure unless keepalived
overwrites the file as expected. A sleep is added as well to give
it time to do so. This way if keepalived stops responding to the
kill command we will see the default failure and restart keepalived.
> Bug 1907671: Handle keepalived hangs in liveness probe

- templates/common/_base/files/configure-ovs-network.yaml
The network manager config was only being applied to the bridge instead
of the interface. It is required to set on the interface.
> Bug 1880259: Fixes setting route metric for ovs-config

- lib/resourcemerge/machineconfig.go
The initial implementation of this had incorrect logic for handling
merges of configs. Because DNS is a new field, the existing one will
always be nil on upgrade. We need to remove the nil check for the
existing object so that it can be populated with the new object.
> Bug 1901376: Fix upgrade issue with DNS controllerconfig field

- pkg/operator/sync.go
- pkg/operator/sync_test.go
The machine-config-operator should accept a kube-cloud-config ConfigMap on platforms that do not require a cloud.conf when the ConfigMap has no cloud.conf data but does have ca-bundle.pem data. This was the intent of https://github.com/openshift/machine-config-operator/pull/2208, but there was a bug in that code.
> Bug 1908159: operator: fix error syncing cloud config with CA data but no cloud config

- test/e2e/mcd_test.go
- test/e2e/utils_test.go
Adds an isOKDCluster function to determine whether the current cluster
is an OKD cluster.
Skips TestKernelType on OKD because the realtime kernel is not available
on OKD clusters.
> Bug 1908648: [test] Skip TestKernelType on OKD

- templates/common/_base/files/configure-ovs-network.yaml
Includes fixes for bond options, dhcp client id, and iface parsing.
> [release-4.6] Bug 1899622: backport bond options fixes

- pkg/daemon/controlplane.go
RHEL7 worker nodes do not support bfq. Rather than assuming the block
device supports bfq, this checks before applying the setting.
Signed-off-by: Ben Howard <ben.howard@redhat.com>
> Bug 1909943: check for scheduler support before setting

- install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
Added a description to the kubelet configuration CRD
`oc explain KubeletConfig.spec.kubeletConfig --recursive=true` should show following `DESCRIPTION` field instead of an empty entry.
```
DESCRIPTION:
The fields of the kubelet configuration are defined in kubernetes upstream.
Please refer to the types defined in the version/commit used by OpenShift
of the upstream kubernetes.
```
Added the description to kubelet config CRD
> Bug 1882140: KubeletConfig: Add the description to kubelet config CRD

- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
Allow only positive values for KubeReserved, SystemReserved and EvictionHard
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1891460
Validate if KubeReserved, SystemReserved and EvictionHard in KubeletConfig are positive or not. 
https://bugzilla.redhat.com/show_bug.cgi?id=1891460#c0
Allow only positive values for KubeReserved, SystemReserved, EvictionHard and EvictionSoft
> Bug 1891460: KubeletConfig: Allow only positive values for KubeReserved, SystemReserved, EvictionHard and EvictionSoft

- templates/common/baremetal/files/NetworkManager-static-dhcp.yaml
It turns out that creating a new connection for the static configuration
doesn't work right with OVNKubernetes. This is because the type of
the interface we get in that case is OVS, not a physical connection.
However, in the OVNKubernetes case we don't need to create a new
connection because we can apply the configuration directly on the
OVS bridge. This change modifies the script so it will only create
a new connection when it sees the default connection id.
> Bug 1911468: [baremetal] Handle OVNKubernetes on ipv4 correctly in static-dhcp

- pkg/daemon/update.go
In https://github.com/openshift/machine-config-operator/pull/2243
we made it so that we switch to BFQ during updates, but unintentially
made it also apply to workers. This does not work on RHEL7 since it
breaks on both trying to set the scheduler as well as finding the root
device.
Change the behaviour back to master only, which also implies that only
CoreOS variants will do this.
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>
> Bug 1913154: update.go: only set BFQ scheduler for masters

- templates/common/baremetal/files/NetworkManager-static-dhcpv6.yaml
Generally speaking there should only be one address configured per
interface. However, in some ipv6 environments a node may get an
address from both DHCP and SLAAC. In this case, we need to make sure
that the ipv6 DHCP to static dispatcher script can handle the inputs
it gets.
Previously, the lease time check would get back a single string
with multiple values. This caused the if to always fail, which
meant we would do static configuration even if the DHCP lease was
not infinite.
This change further filters the lease time query to ensure it only
returns the value for the specific DHCP address in question. It also
improves the address assignment logic to ensure that we get the
correct address no matter how many are present on the interface.
**- …
> Bug 1910165: [baremetal] Correctly handle multiple ipv6 addresses on interface

- templates/common/_base/units/ovs-vswitchd.service.yaml
Temporary fix for making sure the ownership of openvswitch directory is set to `openvswitch` user till we fix https://github.com/coreos/rpm-ostree/issues/49.
Signed-off-by: Aniket Bhat <anbhat@redhat.com>
> Bug 1865743: Add a prestart line to change ownership of openvswitch dir

- pkg/daemon/update.go
During the extension refactor [1], the upgrade logic that installed the
realtime kernel RPM's was lost. 'rpm-ostree' does not have the ability
to do non-local replacements of installed overrides (the packages are
shipped as a bona-fida repo). The cleanest method for handling the
upgrade is to remove the override and the install the new ones; this
avoids having to calculate the rpm dependencies.
> Bug 1911632: daemon/update: fix regression in realtime upgrades

- go.mod
- manifests/controllerconfig.crd.yaml
- pkg/apis/machineconfiguration.openshift.io/v1/types.go
- pkg/controller/kubelet-config/kubelet_config_features.go
- pkg/controller/kubelet-config/kubelet_config_features_test.go
- pkg/operator/assets/bindata.go
- pkg/operator/render.go
- pkg/operator/render_test.go
- templates/master/01-master-kubelet/_base/files/kubelet.yaml
- templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
- templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
- templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
- vendor/k8s.io/utils/net/ipnet.go
- vendor/k8s.io/utils/net/net.go
- vendor/k8s.io/utils/net/port.go
- vendor/modules.txt
kubelet 1.20 supports, eg,  `--node-ip 10.0.0.5,fd01::5` for bare-metal dual-stack, so pass that when available.
https://github.com/openshift/baremetal-runtimecfg/pull/110 changes runtimecfg to set both `KUBELET_NODE_IP` and `KUBELET_NODE_IPS`, where the latter contains either a single IP (if the node only has one) or dual-stack IPs (if available). Note that we don't tell runtimecfg whether we actually want dual-stack IPs or not, so we have to be careful to only use `KUBELET_NODE_IPS` in the case where we actually expect dual-stack IPs (because kubelet will complain if you pass dual `--node-ip`s on a cloud platform). (Also, restricting the use of `KUBELET_NODE_IPS` to the dual-stack case means we don't have to worry about MCO/runtimecfg version skew during 4.6->4.7 upgrades, because we …
> Bug 1907639: Pass dual-stack node IPs to kubelet in dual-stack clusters

- templates/common/on-prem/units/nodeip-configuration.service.yaml
Updates the on-prem nodeip-configuration.service template so content is always written but enabled is toggled based on onPremPlatformAPIServerInternalIP. Prior to this change, if onPremPlatformAPIServerInternalIP is nil the enabled is true but content is empty. This change puts the template to be consistent with /pkg/templates/common/_base/units/nodeip-configuration.service.yaml.
The product of the template can be verified in vSphere UPI CI (and another platform to check the opposite case).
Updates the on-prem nodeip-configuration.service template so content is always written but enabled is toggled based on onPremPlatformAPIServerInternalIP.
Discussion:
I believe this change will mitigate the issues in bz-1917038 …
> Bug 1910738: [on-prem] fix nodeip-configuration.service template

- pkg/daemon/osrelease.go
- pkg/daemon/osrelease_test.go
Bug Summary: 
The VERSION_ID was 7.5 but our check IsLikeTraditionalRhel7() did not account for minor versions (only for "7" not for 7.x) and so returned false. This resulted in dn.loggerSupportsJournal being set to true which is the relevant value when selecting which logger to use. So instead of using storePendingStateLegacyLogger() (for cases where journald isn't avail) we used normal logger resulting in the --journald flag erroneously being used for a rhel7 node.
Also added a unit test for this func to keep it working going forward.  Pre-fix unit new test failed and returned false for 7.5, now it correctly returns true.
> Bug 1913582: fix IsLikeTraditionalRhel7() to account for minor versions

- pkg/daemon/daemon.go
Closes: BZ #1891825
**Reproducer:**
```
package main
import (
"log"
"os"
)
func main() {
file, e := os.Create("a.out")
if e != nil {
log.Fatal(e)
}
log.Println(file)
os.Chmod(file.Name(), 0204)
fi, _ := os.Lstat(file.Name())
mode := os.FileMode(644)
if fi.Mode() != mode {
log.Printf("mode: %v fi.Mode: %v", mode, fi.Mode())
}
log.Printf("%v", fi.Mode())
log.Printf("%v", mode)
file.Close()
}
```
The reason is that:
chmod 204 on your file represents 0204 
```
chmod 204 test.md
ls -la test.md
--w----r--  1 rrobin  staff  35 14 Jan 08:05 test.md
```
and 644 is 01204
```
chmod 01204 test.md
ls -la test.md
--w----r-T  1 rrobin  staff  35 14 Jan 08:05 test.md
```
That extra 1(T) is not printed, since 01000 is nothing.
If we want to check if this is the …
> Bug 1891825: Mode mismatch fix for confusing strings

- pkg/operator/sync.go
- pkg/operator/sync_test.go
Since 4.4 etcd no longer has a DNS dependency. Currently, we are still passing etcd records to the proxy config which should be removed.
In order to remove the deprecated etcd records from the proxy config, we must tolerate the old etcd records.
This PR allows the toleration of this divergence providing the user a chance to update the NoProxy config and in the meantime allow CI to pass for the below PRs.
blocks:
- https://github.com/openshift/installer/pull/4518
- https://github.com/openshift/cluster-network-operator/pull/930
> Bug 1909502: pkg/operator: tolerate removal of etcd records from proxy config

- pkg/controller/container-runtime-config/helpers.go
- pkg/controller/kubelet-config/helpers.go
Fixed: 1873593 (https://bugzilla.redhat.com/show_bug.cgi?id=1873593)
Fix wrapErrorWithCondition seleting the args when format the error message.
It should selsect the rest elements except the format string.
> Bug 1873593: fix error args paring causing unresolved string

- pkg/operator/sync.go
- pkg/operator/sync_test.go
Reverts openshift/machine-config-operator#2315
This reverts the temporary PR #2315 
depends on
- https://github.com/openshift/installer/pull/4518
- https://github.com/openshift/cluster-network-operator/pull/930
/hold
> Revert "Bug 1909502: pkg/operator: tolerate removal of etcd records from proxy config"

- pkg/daemon/update.go
- pkg/daemon/update_test.go
Today we are unnecessarily calling updateKernelArguments() even when there is no kargs to apply. This doesn't fixes bug 1916169 but discovered in https://bugzilla.redhat.com/show_bug.cgi?id=1916169#c8.
If needed, can file a new bug but for now getting it in as part of BZ#1916169
Update: Created a new bug to track it separately.
> Bug 1918440: daemon: add check before updating kernelArgs

- templates/master/00-master/openstack/files/NetworkManager-resolv-prepender.yaml
- templates/worker/00-worker/vsphere/files/NetworkManager-resolv-prepender.yaml
Apparently in 4.5 the vsphere and openstack platforms had separate
templates for the resolv-prepender. This caused the backports for
the proxy settings to only apply to either the master or the worker
instead of both. We should have those settings everywhere, so this
change adds the appropriate env vars.
> Bug 1907636: [vsphere, openstack] Add missing proxy settings to resolv-prepender

- manifests/on-prem/coredns-corefile.tmpl
- pkg/operator/assets/bindata.go
- templates/common/on-prem/files/coredns-corefile.yaml
- templates/common/ovirt/files/coredns-corefile.yaml
- templates/common/vsphere/files/coredns-corefile.yaml
This was already done for openstack in #1527, but not for baremetal
because we don't have any separation between external and internal
hostnames. However, in environments where the DNS servers are
misconfigured such that the second one listed in resolv.conf does
not properly resolve external names, this can cause intermittent
resolution failures from our coredns because it randomly chooses to
use the broken server.
Switching the forward policy to sequential will avoid potentially
confusing issues where a set of DNS servers works fine standalone
but breaks when configured as the forwarding upstreams in coredns.
> Bug 1882209: baremetal & friends: Set coredns forward policy to sequential

- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_features.go
- pkg/controller/kubelet-config/kubelet_config_features_test.go
Fixed applying Custom FeatureGate to the MCO. Prior to this fix 'CustomNoUpgrade' featuregates would not be injected into ignition correctly. This fix adds a unit test as well.
```
apiVersion: config.openshift.io/v1
kind: FeatureGate
metadata:
name: cluster
spec:
featureSet: "CustomNoUpgrade"
customNoUpgrade:
enabled:
- GracefulNodeShutdown
- APIPriorityAndFairness
- RotateKubeletServerCertificate
- SupportPodPidsLimit
- NodeDisruptionExclusion
- ServiceNodeExclusion
- SCTPSupport
disabled:
- LegacyNodeRoleBehavior
- RemoveSelfLink
```
Edit the cluster featuregate and paste in this spec. Also rely on the added unit test.
> Bug 1918471: fix custom featuregates and add a unit test

- templates/common/_base/files/etc-mco-proxy.yaml
- templates/common/_base/units/crio.service.yaml
- templates/common/_base/units/kubelet.service.yaml
- templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
- templates/common/_base/units/machine-config-daemon-pull.service.yaml
- templates/common/_base/units/nodeip-configuration.service.yaml
- templates/common/_base/units/pivot.service.yaml
- templates/common/on-prem/units/nodeip-configuration.service.yaml
Proxies that are url encoded represent sepcial characters with a '%'.
However, systemd uses '%' as control character in unit files and
dropins [1]. This moves the environment varialbes into a file and uses a
EnviromentFile stanza in the units which cannot safely contain '%' and
avoids adding complicated logic to the MCO for mangling the proxy
passwords (detecting if its URL encoded and special character handling).
Closes: 1882674
> Bug 1882674: use environment file for proxy settings

- templates/common/_base/units/crio.service.yaml
- templates/common/_base/units/kubelet.service.yaml
Golang 1.12 changed to use MADV_FREE. MADV_FREE is somewhat faster than 
MADV_DONTNEED; however, the kernel will not try and reclaim memory in golang processes until the system is memory constrained. Cloud servers can potentially page out executable caches, which can cause IOPS throttles. Since golang 1.16  will be changing the default to MADV_DONTNEED, we are going to enable the flag by default.
https://github.com/golang/go/issues/42330
> Bug 1907929: enable madvdontneed in system components

- pkg/controller/common/constants.go
- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/container-runtime-config/helpers.go
- test/e2e/ctrcfg_test.go
Fixes #1825417 (https://bugzilla.redhat.com/show_bug.cgi?id=1825417)
Create a new MC object for each ctrcfg object created.
Before we were only creating 1 MC object for every ctrcfg
created, this would override the previouse ctrcfg CR options
causing a rollback to go all the way back to the default values
when the latest ctrcfg CR was deleted.
So if there was ctrcfg-1, ctrcfg-2 and we deleted ctrcfg-2, it would
skip over ctrcfg-1 and go back to the defaults.
Having a 1:1 mapping of ctrcfg to MC prevents this from happening.
So ctrcfg-1 will have mc-1 and ctrcfg-2 will have [mc-2](https://issues.redhat.com/browse/mc-2) - if ctrcfg-2
is deleted, the changes will roll back to mc-1, which is from ctrcfg-1
and not the …
> Bug 1825417: Make the ctrcfg CR to MC mapping 1:1

- pkg/controller/kubelet-config/helpers.go
This is preventing upgrades in certain cases where the imagefs.inodesFree resource field is used.
Upgrade from 4.6.12 to 4.7.nightly with the following custom resource:
```
spec:
kubeletConfig:
evictionHard:
imagefs.available: 10%
imagefs.inodesFree: 5%
memory.available: 200Mi
nodefs.available: 5%
nodefs.inodesFree: 4%
evictionPressureTransitionPeriod: 0s
evictionSoft:
imagefs.available: 15%
imagefs.inodesFree: 10%
memory.available: 500Mi
nodefs.available: 10%
nodefs.inodesFree: 5%
evictionSoftGracePeriod:
imagefs.available: 1m30s
imagefs.inodesFree: 1m30s
memory.available: 1m30s
nodefs.available: 1m30s
nodefs.inodesFree: 1m30s
imageGCHighThresholdPercent: 80
imageGCLowThresholdPercent: 75
imageMinimumGCAge: 5m
maxPods: 240
podsPerCore: 80 …
```
> Bug 1915235: add imagefs.inodesFree to resourceFields

- pkg/daemon/update.go
If unit enable fails, remove broken symlinks in multi-user.target.wants
and try again. This fixes a bug where enables would fail on cluster upgrades
with RHEL 7 nodes between 4.6 -> 4.7.
Context: before https://github.com/openshift/machine-config-operator/pull/2145,
the MCO hard coded a symlink from /etc/system/systemd/$UNIT to
/etc/systemd/system/multi-user.target.wants/$UNIT, which is not the case
for every unit and thus caused broken symlinks. On RHCOS/FCOS, the systemd
version is newer and is able to remove broken symlinks, but on RHEL 7 nodes,
it will not first attempt to remove broken symlinks and thus fails the
enable. As a workaround, this PR thus attempts to remove broken symlinks
when the first enable fails, and then try again. Successful FCOS/RHCOS upgrades
should not hit this, …
> Bug 1913536: update.go: add broken symlink check + removal during unit enable

- docs/KubeletConfigDesign.md
- install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
Fixes: #2357 
Add message about `KubeletConfig` validation in the CRD as well as in docs
`oc explain kubeletconfig.spec.kubeletConfig --recursive=true` should show following message,
```
description: The fields of the kubelet configuration are defined in 
kubernetes upstream. Please refer to the types defined in the 
version/commit used by OpenShift of the upstream kubernetes.
It's importent to note that, since the fields of the kubelet
configuration are directly fetched from upstream the validation 
of those values is handled directly by the kubelet. Please refer 
to the upstream version of the relavent kubernetes for the 
valid values of these fields. Invalid values of the kubelet
configuration …
```
> Bug 1921248: KubeletConfig validation warning in CRD and Docs

- pkg/daemon/daemon.go
- pkg/daemon/update.go
This fixes a problem were a previous dropin/unit is replaced with zero
length file by ensuring that drops/units have actual content.
> Bug 1920027: daemon: handle zero-length dropins/units

- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/helpers.go
- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
- pkg/controller/kubelet-config/kubelet_config_features.go
- pkg/controller/kubelet-config/kubelet_config_features_test.go
- test/e2e/kubeletcfg_test.go
Fixes #1840881 (https://bugzilla.redhat.com/show_bug.cgi?id=1840881)
Create a new MC object for each kubelet config object created.
Before we were only creating 1 MC object for every kubelet config
created, this would override the previouse kubelet config CR options
causing a rollback to go all the way back to the default values
when the latest ctrcfg CR was deleted.
So if there was kc-1, kc-2 and we deleted kc-2, it would
skip over kc-1 and go back to the defaults.
Having a 1:1 mapping of kubelet config to MC prevents this from happening.
So kc-1 will have mc-1 and kc-2 will have [mc-2](https://issues.redhat.com/browse/mc-2) - if kc-2
is deleted, the changes will roll back to mc-1, which is from kc-1
and not the …
> Bug 1840881: Make the kubelet config CR to MC mapping 1:1

- templates/common/_base/units/kubelet.service-proxy.yaml
- templates/common/_base/units/kubelet.service.yaml
Test commit to see if rendering/merging dropins may be broken.
> Bug 1920027: use separate dropin files for kubelet

- templates/common/_base/units/crio.service.yaml
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>
Added a drop-in for crio service to enable pprof profile by default.
```
curl --unix-socket /var/run/crio/crio.sock http://localhost/debug/pprof/goroutine?debug=1
```
Enable crio pprof profile over unix socket
cc: @rphillips
> Bug 1922454: Enable crio pprof profile over unix socket

- pkg/controller/kubelet-config/kubelet_config_controller.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1904133
For kubeletconfig, do not append new status conditions if the error message stays the same
to avoid the repeated same conditions
This patch mirrors the handlerErr of the container runtime config controller.
Verify this by applying the problematic YAML and waiting for several minutes to check the status
```
Status:
Conditions:
Last Transition Time:  2021-01-27T21:19:29Z
Message:               Error: could not find any MachineConfigPool set for KubeletConfig
Status:                False
Type:                  Failure
Events:                    <none>
// wait several minutes
Status:
Conditions:
Last Transition Time:  2021-01-27T21:26:16Z
Message: …
```
> Bug 1904133: kubeletcfg: fix repeated status error msg

- templates/common/_base/files/configure-ovs-network.yaml
In baremetal and vsphere platforms the merged directory serves as
overlayFS for supporting k8s nmstate. But because of the way it
gets mounted, if the corresponding files in that directory exist in
the lower directory, the files get their contents zeroed out.
This commit fixes the issue with zeroing out of nmconnection files.
Also, on other cloud platforms the merged directory doesn't exist.
The ovs-configuration script previously would try to copy files
from a non-existent path and fail. This commit also fixes that issue
by first checking if the merged directory exists before trying to
copy the nmconnection files.
Signed-off-by: Aniket Bhat <anbhat@redhat.com>
This is a follow-up fix for #2263
> Bug 1916363: Fix how files from system-connections-merged get copied into system-connections

- OWNERS_ALIASES
- templates/common/baremetal/OWNERS
- templates/common/on-prem/OWNERS
- templates/common/ovirt/OWNERS
- templates/common/vsphere/OWNERS
- templates/master/00-master/on-prem/OWNERS
- templates/worker/00-worker/on-prem/OWNERS
This already exists for openstack, so adding vsphere, baremetal & ovirt.
Did this last night by memory on who does what, lmk if you want any changes...
Also assigned all the aliases as on-prem reviewers (to assist in getting the right eyes on this) but not authors as those prs need signoff from multiple teams.
LMK whatever changes you want, I'll leave this open for a while.
> Add platform aliases

- templates/common/_base/units/crio.service-proxy.yaml
- templates/common/_base/units/crio.service-socket.yaml
- templates/common/_base/units/crio.service.yaml
Somewhere in the template rendering stack the dropin merge logic
is broken, causing only the last dropin defined in a file to get
rendered. Split the dropin templates into separate files for now
to fix CI failures, and revisit later the template rendering logic
to see where this breaks.
Fixes https://github.com/openshift/machine-config-operator/commit/0c7541ec30748c774d1c9e0f27afde2ae6c1e0fb#diff-934bed5b78da27a91177feabe213288a794cc4d1851be77d92c3ff5426f1d88c and https://github.com/openshift/machine-config-operator/commit/fe7fea755afa7f6f1f4706cb4b924a68a0a6a59d#diff-934bed5b78da27a91177feabe213288a794cc4d1851be77d92c3ff5426f1d88c
> Bug 1920027: templates: split crio dropins into separate files

- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
This reverts commit 1eb4bd3fca7ad32bf74f436f494c431000e13716.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1923874
Reverting https://github.com/openshift/machine-config-operator/pull/2314
Percentage values should be allowed in kubeletconfig
None
> Bug 1923874: KubeletConfig: Revert "Fix KubeletConfig validation for invalid values"

- templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
- remove OS check.  If node has systemd-resolved enabled this will work
- Check to see if systemd-resolved is enabled.  Otherwise skip
- Check if /etc/systemd/resolved.conf.d/60-kni.conf exists.  If it doesn't create it and restart systemd-resolved if active
- Add logging
NM resolve prepender:  Update for systemd-resolved logic
> Bug 1919271: NM resolve prepender: Update for systemd-resolved logic. systemd-resolved requires restart after dropin created

- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
Fixes: https://github.com/openshift/machine-config-operator/issues/2357
Drop all the validation for `KubeletConfig`
```yaml
metadata:
name: set-max-pods
spec:
logLevel: 5
matchLabels:
kubeletConfig:
evictionHard:
imagefs.available: 10%
imagefs.inodesFree: 5%
memory.available: 200Mi
nodefs.available: 5%
nodefs.inodesFree: 4%
evictionPressureTransitionPeriod: 0s
evictionSoft:
imagefs.available: 15%
imagefs.inodesFree: 10%
memory.available: 500Mi
nodefs.available: 10%
nodefs.inodesFree: 5%
evictionSoftGracePeriod:
imagefs.available: 1m30s …
```
> Bug 1923874: KubeletConfig: Drop validation for kubeletconfig

- docs/KubeletConfigDesign.md
- install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
Fixed a typo in Kubeletconfig CRD
`oc explain kubeletconfig.spec.kubeletConfig --recursive=true` 
Fix the typo in KubeletConfig validation warning in CRD and Docs
> Bug 1921248: KubeletConfig: validation warning in CRD and Docs

- install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
This is a cherry-pick of https://github.com/openshift/cluster-etcd-operator/pull/426 in OCP 4.5. Because we moved quorum-guard to cluster-etcd-operator in 4.6 the backport needs to traverse repos.
More details on the original bug and conversations. I really think this warrants backport given the possible failure case.
- https://bugzilla.redhat.com/show_bug.cgi?id=1840358
- https://github.com/openshift/cluster-etcd-operator/pull/426 
depends on openshift/origin#25700
> Bug 1884195: etcd-quorum-guard remove toleration timeouts

- templates/common/_base/files/configure-ovs-network.yaml
Fixes: 1925319
```shell
if [ -z "$vlan_id"]; then
```
```
configure-ovs-network.sh:140:5: note: The mentioned syntax error was in this if expression. [SC1009]
configure-ovs-network.sh:140:8: error: Couldn't parse this test expression. Fix to allow more checks. [SC1073]
configure-ovs-network.sh:140:13: error: Expected this to be an argument to the unary condition. [SC1019]
configure-ovs-network.sh:140:24: error: You need a space before the ]. [SC1020]
configure-ovs-network.sh:140:24: error: Missing space before ]. Fix any mentioned problems and try again. [SC1072]
```
Extract inline bash configure-ovs.sh to file, run `shellcheck` on it.
Fixed bash syntax error in configure-ovs.sh
> Bug 1925319: configure-ovs: fix bash syntax error

- templates/common/vsphere/files/vsphere-hostname.yaml
- templates/common/vsphere/units/vsphere-hostname.service.yaml
Fixes: BZ1920807 - when creating a new machine, the node will get an unexpected hostname
Added the --static flag to `hostnamectl` to prevent DHCP from overriding the hostname sourced from guestinfo.  This is only done once on vsphere nodes on the first boot.
- Configure DHCP to assign a hostname as part of the lease
- Scale a new node
- The node should automatically join the cluster with a node name like ` <cluster>-<clusterid>-worker-<name>`
Resolves issue where the hostname provided by the DHCP overrides the guestinfo hostname thus preventing the machine-api-controller from reconciling new nodes which receive a hostname from DHCP.
> Bug 1920807: [vsphere] set hostname with --static to provide consistent node name for CSR approval

- Dockerfile
Update reference, so that doing a `make image` pulls from the updated location to match CI.
Interestingly `registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.8` (the one referenced in Dockerfile.rhel7) doesn't seem to work, so using 4.7 one for now.
> Dockerfile: update reference to builder to new CI location

- pkg/controller/kubelet-config/helpers.go
- test/e2e/kubeletcfg_test.go
Fixes #1840881 (https://bugzilla.redhat.com/show_bug.cgi?id=1840881)
Minor fix in the logic for getting the suffix of the MC for a kubelet
config. Remove some extra debugs from the e2e tests.
Create multiple kubeelet configs and confirm a new MC is created for each one.
> Bug 1840881: Fix 1:1 mapping for kubeletconfig:MC and some e2e test fixes

- templates/common/_base/files/configure-ovs-network.yaml
When using nm clone for a connection where we cannot find the current
keyfile, the file is assumed to be in the regular NM keyfile path.
However on platforms using the "merged" keyfile path, this fails,
because the file only exists in the merged directory.
Additionally, after we copy the cloned file to edit for static IP
addressing, NM will fail to load it because of selinux. Therefore we
need to restorecon after we copy it.
> Bug 1927366: Fixes ovs-configuration with cloned connections

- pkg/daemon/daemon.go
Code is from ec135eee0c (#545), and while it was not wrong, the wrapping `select` isn't necessary for blocking on a single channel read.  I only noticed because I'm working through a SIGQUIT stack trace which included:
```
goroutine 53 [select (no cases), 814 minutes]:
github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).runLoginMonitor(0xc000582a80, 0x0, 0xc000538480)
/go/src/github.com/openshift/machine-config-operator/pkg/daemon/daemon.go:689 +0x30f
created by github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).ClusterConnect
/go/src/github.com/openshift/machine-config-operator/pkg/daemon/daemon.go:299 +0x578
```
So with this commit, we drop the `select` and get straight into the blocking channel read.
> pkg/daemon: Drop unnecessary select from runLoginMonitor

- manifests/machineconfigdaemon/daemonset.yaml
- pkg/daemon/daemon.go
- pkg/daemon/update.go
- pkg/operator/assets/bindata.go
This armors the signal handling for the daemon blocking any shutdown until _after_ an update is complete.
The old functions `catchIgnoreSIGTERM` and `cancelSIGTERM` really didn't do much (they used the mutex and then set a bool) but there were no checks in the signal handling.
This also increases the time for the MCD to shutdown from 5min to a 1hr. Since the MCD will shut down immediately when safe to do so this shouldn't have negative effects except in the case of an already unhappy node.
> daemon: safer signal handling for shutdown

- pkg/controller/node/node_controller.go
- pkg/controller/node/node_controller_test.go
etcd-quorum-guard has been part of cluster-etcd-operator
for a while and it already guards against node drain to
prevent from quorum loss.
With having support for different types of cluster like
SingleReplica and HighlyAvailable, it allows MCO to not
think about what quorum guard behaviour should be
depending upon cluster type.
Also use GetScaledValueFromIntOrPercent() instead of
deprecated function GetValueFromIntOrPercent() and
update unit tests accordingly.
> controller: remove etcd quorum-guard check on master pool

- docs/MachineConfigDaemon.md
- pkg/daemon/update.go
- pkg/daemon/update_test.go
- pkg/operator/bootstrap.go
- pkg/operator/sync.go
Incorporates https://github.com/openshift/machine-config-operator/pull/2294 and https://github.com/openshift/machine-config-operator/pull/2290, such that a kubelet cert signer rotation causes a "none" action.
In 4.7 we introduced non-reboot updates for select cases, but still drained nodes for safety. This is still a major workload disruption, and non-reboot updates do not require draining for correctness. This PR will also introduce the ability to not drain at all for non-reboot updates, and in case of error, return the error directly instead of rebooting in an attempt to fix it.
This will cause updates to effectively to not cordon nodes at all, and on AWS a change to e.g. kubelet ca would talk ~20 seconds to apply to a 3-node pool.
One last thing to consider is what behaviour we want …
> Add kubelet CA to no-reboot action list/Do not drain for non-reboot actions

- templates/common/_base/files/NetworkManager-keyfiles.yaml
- templates/common/_base/files/nm-tmpfiles.yaml
- templates/common/_base/units/nm-system-connections-mount.yaml
- templates/common/on-prem/files/NetworkManager-onprem.conf.yaml
In order to reduce complexity, and to promote consistency between platforms,
and thereby reducing an opportunity for future issues, this patch introduces
the OverlayFS mounted /etc/NetworkManger/system-connections-merged to all
platforms. It is meant to be a transparent change, and should not change the
functionality of NetworkManager on any platform. The purpose is to make any
NetworkManager configuration that is not performed by Machine Config Operator
be ephemeral.
> Bug 1928473: Apply system-connections-merged to all platforms

- templates/common/_base/files/configure-ovs-network.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1922997
Conduct SDN migration, then rollback
Connect default NIC to cluster network if it is not triggered automatically, after rolling back to ovn-kubernetes.
> Bug 1922997: Connect default NIC to cluster network

- OWNERS
I'm heading to the CoreOS team on March 1. Thank you @kikisdeliveryservice @yuqi-zhang @sinnykumari for the wild ride. 
I won't be far, and I'm happy to help.
> OWNERS: Surrendering membership

- pkg/controller/container-runtime-config/helpers.go
Fix Bug 1930620 https://bugzilla.redhat.com/show_bug.cgi?id=1930620
Add trace loglevel as valid level for ContainerRuntimeConfig as documented and current crio can support this level.
Apply the containerRuntiemConfig with `logLevel: trace`.
Add trace loglevel as valid level for ContainerRuntimeConfig.
> Bug 1930620: support trace loglevel

- pkg/server/api.go
- pkg/server/api_test.go
With [1], SHA and 3DES Ciphers are considered unsafe. 
http/2 requires these inseucre Ciphers which means that fixing the CVE requires disableing http/2
[1] https://access.redhat.com/security/cve/cve-2016-2183
This change will not conflict with the TLS profile work coming later.
> Bug 1844990: server/api: Disable unsafe ciphers for CVE-2016-2183

- pkg/daemon/daemon.go
https://github.com/openshift/machine-config-operator/pull/1729 introduced code to obtain the version of the Ignition binary shipped in the OS root filesystem.  That PR contemplated that the version would be used more widely in the MCD, but that hasn't occurred, so its only current use is to log the Ignition version at MCD startup.  On balance, I think that code path introduces more risk than value, so this PR backs it out.  My reasoning is:
1. By the time this code is invoked, Ignition will never run again, so its version is useful for forensics and not much else.  In particular, the version of the Ignition binary in machine-os-content probably doesn't match the one in the bootimage.
2. MCD is invoking the Ignition binary via a private (non-contractual) path in the root filesystem, but …
> Bug 1927731: Revert "pkg/daemon: Add IgnitionVersion to Daemon"

- templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
- templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
This makes it a little prettier and easier for automation to parse.
> Bug 1871770: Remove extraneous whitespace from keepalived peer list

- pkg/operator/sync.go
In the course of working on wait for all pools (#2231) an error when a required pool isn't yet finished updating was inadvertently removed. Restoring it here.
Replaces  #2433
> Bug 1932105: operator/sync.go restore err when required pools not leveled

- templates/common/_base/files/configure-ovs-network.yaml
With static IP addressing we try to copy the original NM keyfile so that
we can modify it and retain the original IP settings. In the case where
a bond was configured with a static IP address we grep for the UUID in
the keyfiles to determine which keyfile belongs to the original
connection. However, bond slaves will also contain the UUID in their
keyfile, and the grep was accidentally returning multiple files which
causes the script to fail.
> Bug 1931522: OVS Config: fixes detecting bond NM files with static IP

- install/0000_90_machine-config-operator_00_servicemonitor.yaml
In order to associate the metrics of each target, we want to clearly
identify which node the MCD is scheduled on to. This will allow us
to more accurately track target health as it relates to nodes in
order to improve the TargetDown alert during upgrades. In the future,
other alerts should be based on node name, not instance name, which
should simplify behavior.
If the node label is already set, do nothing.
The linked bug reports TargetDown firing for MCD because at least one
instance is down the entire time of the upgrade due to overlapping
control plane / worker updates. We are changing the alert to exclude
instances that are deliberately being upgraded (today by using the
unschedulable flag, in the future potentially by a more targeted MCO
driven metric indicating the phase of node …
> Bug 1933805: Add node label to service monitor

- pkg/daemon/daemon.go
- pkg/daemon/update.go
Dependency backports for Bug 1933077.
This fixes a problem were a previous dropin/unit is replaced with zero
length file by ensuring that drops/units have actual content.
Signed-off-by: Ben Howard <ben.howard@redhat.com>
(cherry picked from commit c6df6d8)
The previous commit checks for IsNotExist as a return of
checkFileContentsAndMode, which since we wrap the error, will
never be the case, thus always erroring there. Instead check
for the error in a separate case.
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.
> [release-4.6] Bug 1933075: backport systemd dropin/units zero-length handling

- templates/common/_base/files/configure-ovs-network.yaml
When using nm clone for a connection where we cannot find the current
keyfile, the file is assumed to be in the regular NM keyfile path.
However on platforms using the "merged" keyfile path, this fails,
because the file only exists in the merged directory.
Additionally, after we copy the cloned file to edit for static IP
addressing, NM will fail to load it because of selinux. Therefore we
need to restorecon after we copy it.
(cherry picked from commit f99c1bb3d626370a660d96f0c47221ea899fa060)
> [release-4.7] Bug 1927405: Fixes ovs-configuration with cloned connections

- pkg/daemon/rpm-ostree.go
- pkg/daemon/update.go
Add a nil check, so that if a firstboot osupdate fails, the error
is properly captured instead of panicking, since the node object
is nil.
Also just report the error directly if the command fails, since
runGetOut doesn't return stdout when it errors.
> Bug 1934113: Improve error handling for os updates

- templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
- templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
We've seen occasional issues during upgrades caused by what seems to be
the kubelet still being active during OSTree finalization. If the
kubelet changes things in `/etc`, it'll confuse OSTree which is trying
to do the `/etc` merge.
We want to be sure that the kubelet is done modifying everything it
needs to in `/etc` and that it exited before we finalize the deployment.
Add a `After=ostree-finalize-staged.service` for this. The way this
works is that that service runs in its `ExecStop`, and shutdown ordering
is the reverse of startup. So this will cause the kubelet to exit before
`ostree-finalize-staged.service` is stopped.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1902963
It's tricky to verify because it's a flake. So verification …
> Bug 1902963: templates: add After=ostree-finalize-staged.service to kubelet.service

- templates/common/_base/files/configure-ovs-network.yaml
With static IP addressing we try to copy the original NM keyfile so that
we can modify it and retain the original IP settings. In the case where
a bond was configured with a static IP address we grep for the UUID in
the keyfiles to determine which keyfile belongs to the original
connection. However, bond slaves will also contain the UUID in their
keyfile, and the grep was accidentally returning multiple files which
causes the script to fail.
(cherry picked from commit e73bd012f14fe5025ccae35059c02d4835ecf4e8)
> Bug 1931615: OVS Config: fixes detecting bond NM files with static IP

- pkg/controller/kubelet-config/helpers.go
Fixes #1840881 (https://bugzilla.redhat.com/show_bug.cgi?id=1840881)
Instead of relying on the order in which the kubeletconfig
objects are added to the list, let's go through the
list and find the maximum suffix value used. We can
then add 1 to the max suffix value to be used for the
MC when creating the new kubeletconfig object.
Create multiple kubelet config CRs and each one will have a different MC for it.
> Bug 1840881: Make getting the suffix of a kubeletconfig MC more robust

- pkg/controller/kubelet-config/helpers.go
- test/e2e/kubeletcfg_test.go
Fixes #1929257
Fix 1:1 mapping for kubeletconfig:MC and make getting the suffix of a kubeletconfig MC more robust.
Cherry-pick of https://github.com/openshift/machine-config-operator/pull/2408 and https://github.com/openshift/machine-config-operator/pull/2459.
> [release-4.7] Bug 1929257: Fix 1:1 mapping for kubeletconfig:MC and some e2e test fixes

- cmd/machine-config-controller/start.go
- manifests/controllerconfig.crd.yaml
- pkg/controller/node/node_controller.go
- pkg/controller/node/node_controller_test.go
- pkg/daemon/constants/constants.go
- pkg/daemon/daemon.go
- pkg/daemon/drain.go
- pkg/daemon/update.go
- pkg/operator/assets/bindata.go
With the introduction of different ControlPlaneTopology types
in the OpenShift cluster, the behaviour of the cluster may differ
based on cluster type. For example: cluster with Single
controlPlane node, it doesn't make sense to perform workload drain.
ControllerConfig now understands ControlPlaneTopology:TopologyMode
set in the cluster. Node controller later on reads the value from
controllerConfig and sets value into node annotation
`machineconfiguration.openshift.io/controlPlaneTopology`.
While performing a configuration update, machine-config-daemon
will read the annotation and based on controlPlaneTopology
type, it will decide drain action.
MCD skips drain if controlPlaneTopology is SingleReplica.
Part of - https://github.com/openshift/enhancements/pull/560/
This PR also:
- refactors …
> Skip drain on Single Node deployment

- templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
Per the request in our discussion with the api team, we want to try
increasing this timeout to see if it helps with our api flakiness.
Note that I did not change the openstack platform's timeout because
they were already using 1 minute.
Increase the http-request timeout in haproxy on platforms that use that to loadbalance the api.
> Bump haproxy http-request timeout to 30 seconds

- pkg/operator/status.go
c6e2fa8674 (#2231) added this check, but [`Reason` is supposed to be a machine-readable slug, while the human-oriented string goes in `Message`][1].  Possibly worth a backport to 4.7?
[1]: https://github.com/openshift/api/blob/4b79815405ec40f1d72c3a74bae0ae7da543e435/config/v1/types_cluster_operator.go#L128-L136
> Bug 1939270: pkg/operator/status: Use 'DegradedPool' reason for Upgradeable=False

- templates/common/vsphere/files/vsphere-disable-vmxnet3v4-features.yaml
Based on one of VMware's recommendations disable
both:
tx-udp_tnl-segmentation
tx-udp_tnl-csum-segmentation
This could potentially replace the more generic offload disable.
> Bug 1935539: vSphere: Disable tx udp_csum segmentation

- Makefile
Recent jobs have seen a lot [of][1]:
panic: test timed out after 1h15m0s
Nothing looks wrong with the test-case that was running at panic time,
there are just a bunch of slow cases, and we've already consumed most
of the 1.25 hours before we start in on the panicking case:
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2472/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op/1373072029300822016/build-log.txt | sed -n 's/.*PASS.*[(]\([0-9]*\.[0-9]*\)s)$/\1/p' | awk 'BEGIN{s = 0}{s += $1}END{print s / 3600}'
1.17946
```
Breaking it down by test:
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2472/pull-ci-openshift-machine-config-operator-master-e2e-gcp …
```
> Makefile: Bump test-e2e timeout to 90 minutes

- templates/common/_base/files/configure-ovs-network.yaml
With static IP addressing we try to copy the original NM keyfile so that
we can modify it and retain the original IP settings. In the case where
a bond was configured with a static IP address we grep for the UUID in
the keyfiles to determine which keyfile belongs to the original
connection. However, bond slaves will also contain the UUID in their
keyfile, and the grep was accidentally returning multiple files which
causes the script to fail.
(cherry picked from commit e73bd012f14fe5025ccae35059c02d4835ecf4e8)
> Bug 1931617: OVS Config: fixes detecting bond NM files with static IP

- pkg/controller/container-runtime-config/helpers.go
Follow up of #2448. Bug 1930636: fix error print verb.
Error: invalid PidsLimit '\n' should be Error: invalid PidsLimit -10.
> Bug 1930636: fix error print verb

- templates/common/_base/files/configure-ovs-network.yaml
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
This issue seen with UPI deployment on vsphere where mac address field was never been populated
this PR Fixes: 1938084
fix logical issue in the script such that if cloned-mac-address field doesn't exits it will create it and assign ovs port
the same mac as ethernet device
- UPI vsphere deployment
- manually by running the right command and saw filed get populate
- original file
[ethernet]
mtu=1500
mtu=
mac-address-blacklist=
- run fix manually
sed -i '/^\[ethernet\]$/,/^\[/ s/^cloned-mac-address=.*$/cloned-mac-address=00:50:56:ac:55:06/' /etc/NetworkManager/system-connections-merged/ovs-if-br-ex.nmconnection
- check results
[ethernet]
cloned-mac-address=00:50:56:ac:55:06
mtu=1500
mtu= …
> Bug 1938084: configure-ovs.sh:incorrect setting of cloned-mac-address field

- templates/common/vsphere/units/vsphere-hostname.service.yaml
Removed condition which ensures vsphere-hostname.service only runs on the first boot.
- Install latest version of 4.6.22
- Configure DHCP to assign a hostname to nodes in the cluster
- Upgrade with the fix included
Addresses issue which causes hostnames to be lost when upgrading from 4.6 to 4.7 on vSphere IPI clusters.
> Fixes: Bug 1942207: [vsphere] hostnames are changed when upgrading from 4.6 to 4.7.x causing upgrades to fail

- templates/common/_base/files/configure-ovs-network.yaml
ovs-configuration: use NM default ethernet route metric
Instead of the default OVS interface route metric, which is much lower,
and causes problems when secondary interfaces are added to the machine.
> Bug 1883916: [4.6z backport] Fixes setting route metric for ovs-config

- templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
Sometimes, the host can have stale conntrack entries towards the
apiserver, that cause random network interruptions.
This is caused by the GCP healtchecker traffic, that only must be valid when is 
directed to the node and it can never loop through it.
Signed-off-by: Antonio Ojea <aojea@redhat.com>
> Bug 1925698: not allow healthcheck traffic to loop through the node

- templates/common/vsphere/files/vsphere-disable-vmxnet3v4-features.yaml
In testing this evening with openshift-sdn based install
nmcli does not change the ethtool features until the
interface has been restarted.
Switching to using ethtool directly.
> Bug 1935539: vSphere: udp tnl workaround cannot use nmcli

- pkg/apis/machineconfiguration.openshift.io/v1/types.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1941936
Made `LogSizeMax` and `OverlaySize` in `ContainerRuntimeConfiguration` omit when not used. 
https://bugzilla.redhat.com/show_bug.cgi?id=1941936#c0
Drop LogSizeMax and OverlaySize in ContainerRuntimeConfiguration when not used
> Bug 1941936: drop LogSizeMax and OverlaySize in ContainerRuntimeConfiguration when not used

- templates/common/_base/units/nodeip-configuration.service.yaml
- templates/common/on-prem/units/nodeip-configuration.service.yaml
I have not managed to reproduce this bug, but the circumstantial evidence is strong.
we write out 20-nodenet.conf at 11:08:14:
```
Mar 17 11:08:14 ...-infra-0-qx58v bash[1716]: time="2021-03-17T11:08:14Z" level=info msg="Writing Kubelet service override with content [Service]\nEnvironment=\"KUBELET_NODE_IP=192.168.48.21\" \"KUBELET_NODE_IPS=192.168.48.21\"\n"
```
then start kubelet 2 seconds later:
```
Mar 17 11:08:16 ...-infra-0-qx58v systemd[1]: Starting Kubernetes Kubelet...
```
but kubelet doesn't see `${KUBELET_NODE_IP}`:
```
root        2113 11.7  1.0 3212924 168416 ?      Ssl  Mar17 184:29 kubelet --config=/etc/kubernetes/kubelet.conf --bootstrap-kubeconfig=/etc/kubernetes/kubeconfig --kubeconfig=/var/lib/kubelet/kubeconfig --container-runtime=remote …
```
> Bug 1940939: Do "systemctl daemon-reload" after running "runtimecfg node-ip"

- templates/common/vsphere/files/vsphere-disable-vmxnet3v4-features.yaml
backport PR: #2482
There is an issue (tbd) with the VMXNET3 v4 driver causing
network traffic between various openshift services to be dropped.
With the addition of VMXNET3 v4 in RHCOS 4.7 (RHEL 8.3 kernel)
this workaround needs to be in place for customers running on
vSphere 6.7, OpenShift 4.7 and virtual hardware version 14 or higher.
> Bug 1941246: vSphere: Disable tx-udp-tnl offload

- templates/common/on-prem/files/keepalived.yaml
When Keepalived container that holds VIP being SIGTERMed that should trigger a priority 0 advertisement
message to allow faster VIP migration.
This PR forwards the SIGTERM to child processes (the Keepalived processes) in Keepalived container
in order for SIGTERM to cause a VRRP priority 0 message to be sent.
> Bug 1920670: [Baremetal and friends] Properly handle SIGTERM - Keepalived container

- install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
Added the TLSSecurityProfile description to the KubeletConfig manifest. Not sure how I missed this.
```
metadata:
name: set-kubelet-tls-security-profile
spec:
tlsSecurityProfile:
type: Old
matchLabels:
```
> Bug 1943329: add tlsSecurityProfile to KubeletConfig manifest

- templates/common/vsphere/units/nodeip-configuration.service.yaml
The nodeip service should not be enabled for vSphere UPI. Prior to this change, enabled was always true but the content was empty for vSphere UPI. In 4.7, this has already been remedied and the service is correctly set to enabled: false. The discrepency between 4.6 and 4.7 breaks upgrades, so this commit fixes the issue in 4.6.
@yuqi-zhang @jcpowermac @rvanderp3
> Bug 1940585: conditionally set nodeip-service enabled for vSphere

- templates/common/_base/units/nodeip-configuration.service.yaml
Make MCO templates use new `runtimecfg node-ip --prefer-ipv6` flag when on single-stack IPv6, so that we pick the correct node IP when bringing up a single-stack IPv6 cluster on a node that happens to also have IPv4 IPs.
Our infra doesn't currently create any such clusters anywhere but we can confirm that the option gets passed (and accepted) in single-stack IPv6 clusters, and not elsewhere. (Of course, I don't think MCO has a single-stack IPv6 presubmit job, so...)
(Why does the template ask for this? What changelog?)
/hold
for testing
> Bug 1939740: Use new --prefer-ipv6 flag to "runtimecfg node-ip" as appropriate

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
As a warning, the alert should only fire over sustained usage
because this is a symptom and may peak briefly during startup.
Set the timeout to 15m and slightly improve the alert message.
The `SystemMemoryExceedsReservation` alert requires a longer period of extended usage before firing, and the description is slightly clarified.
> Bug 1945431: alerts: SystemMemoryExceedsReservation triggers too quickly

- templates/common/_base/files/configure-ovs-network.yaml
Fixes the following error:
ERR|interface br-ex: ignoring mac in Interface record
While benign, this error would fill up the OVS logs. Old versions of
Network Manager required the cloned-mac to be set on both the bridge and
the bridge interface. However, in newer versions of NM this has been
fixed and it only needs to be set on the interface. See:
https://bugzilla.redhat.com/show_bug.cgi?id=1899745#c8
> Bug 1899057: configure-ovs-network: fix spurious OVS warnings

- docs/MachineConfiguration.md
- pkg/daemon/update.go
- test/e2e/mcd_test.go
This adds support for a new RHCOS extension called
"sandboxed-containres". It will install kata-containers  and its
dependencies, 9 RPMs with a total size of ~55MB when downloaded, ~150MB
when installed.
It will allow users to run kernel isolated containers via the Sandboxed
Containers operator.
TBD
Added support for a new RHCOS extension to install `sandboxed-containers`.
**IMPORTANT:**
Let me add a big note here that I'm experimenting with the fact of having a kata-containers extension, superseding https://github.com/openshift/machine-config-operator/pull/2376, and it comes from a suggestion made by @cgwalters while reviewing https://github.com/openshift/enhancements/pull/677#discussion_r588732079 (also, refer …
> Add new extension for sandboxed-containers

- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
- templates/common/_base/files/kubelet-auto-node-sizing-enabled.yaml
- templates/common/_base/files/kubelet-auto-sizing.yaml
- templates/common/_base/units/kubelet-auto-node-size.service.yaml
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1946513
Fix auto node sizing to honor user specified system reserved. 
```
metadata:
name: single-node-reserve-sys-mem
spec:
matchLabels:
pools.operator.machineconfiguration.openshift.io/master: ""
kubeletConfig: 
systemReserved:
memory: 3Gi
```
When the MCO has done rolling out that kubeletconfig, the node should come up with 3Gi systemd reserved. 
Fix Auto node sizing to honor user input
> Bug 1946513: Fix Auto node sizing to honor user input

- pkg/operator/status.go
- pkg/operator/sync.go
Sets machine-config clusteroperator Upgradeable: False when pools are updating (covering future upgrades), does not block current upgrade from reporting finished on all completing.
To verify roll out a mcp then once pool is updating, verify Upgradeable: False:
```oc get co/machine-config -oyaml```
when pool finished, should toggle back to Upgradeable: True
> operator: upgradeable false when pools are still updating

- manifests/machineconfigdaemon/daemonset.yaml
- pkg/daemon/daemon.go
- pkg/daemon/update.go
- pkg/operator/assets/bindata.go
We need to revert the following commits due to Bugzilla 1933772
https://github.com/openshift/machine-config-operator/commit/dd7154131a868ec950e87cdfc74d1b89b3919792
https://github.com/openshift/machine-config-operator/commit/6d92a7bb54f5264f2863fdb6859ea1d4d1bfa9c6
> Bug 1933772: Revert rework of signal handling

- templates/common/_base/files/configure-ovs-network.yaml
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
update all existing connection with master set to use the new devices name.
Walk through all existing connection and modify any connection with master to use the new connection device's name.
follow repro steps doc in 1943320
update connection UUID for bond interfaces for OVNKubernetes
> Bug 1943320: configure-ovs doesn't handle bond interfaces correctly for OVNKubernetes

- templates/common/_base/files/configure-ovs-network.yaml
The file is not needed by 4.7+ ovs pods, but when rolling back from 4.7
to 4.6 CNO is updated before MCO. The 4.6 version of the pod does not
find the file, executes ovs in a pod with the result that two ovs
instances are running at the same time.
Need to test the downgrade with this PR in
> Bug 1940207: create the ovs-config-executed file to signal ovs is running on the host

- templates/common/openstack/units/afterburn-hostname.service.yaml
To correct setting of hostname, afterburn requires Network Manager to be up. To prevent potential race conditions this commit ensures that we start afterburn only when Network Manager is online and blocks services relying on Networking being up.
> Bug 1899187: run afterburn-hostname only when Network Manager is up

- pkg/controller/kubelet-config/kubelet_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
> Bug 1947684: delay kubelet config readiness until after pools and controller config are ready

- templates/common/_base/files/configure-ovs-network.yaml
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
configure-ovs script doesn't detect team interface and incorrectly mark it as 802-3-type, this leads to failure
when try to install OCP with ovnkubernetes.
Added team interface and its options detection
install OCP with OVNKubernetes with team interface.
Modify the script to check for team interface type and its options
**- Unit Testing**
manually created team interface and set team config options
``` 
nmcli connection add type team autoconnect no con-name my-team
nmcli connection modify my-team team.runner activebackup team.link-watchers "name=ethtool delay-up=5, name=nsna_ping target-host=target.host"
```
wrote a script the minmic the changes in the PR and …
> Bug 1934443: Fix ovs-configure script to detect team interface

- templates/common/_base/files/kubelet-auto-sizing.yaml
Fixes : https://bugzilla.redhat.com/show_bug.cgi?id=1949387
Fixed the typo in auto node sizing script
Enable auto node sizing where `getconf _NPROCESSORS_ONLN` is 2, and the auto node sizing should not fail. 
Fix the typo reserved cpu calculation in auto sizing script
> Bug 1949387: Fix the typo in reserved calculation in auto sizing script

- templates/common/on-prem/files/keepalived.yaml
Due to a bug in keepalived 2.0.10, if the liveness probe kills
keepalived, any vips that were assigned to the system remain and
are not cleaned up when keepalived restarts. Until we get a fixed
version of keepalived, let's clean up the VIPs ourselves before
starting keepalived. If the node is supposed to have the VIP it will
configure it again when keepalived starts.
This is a workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1931505
Under some circumstances, a VIP may be configured on a node it shouldn't be due to keepalived exiting uncleanly. To avoid this, remove any existing VIPs before starting keepalived.
> Bug 1931505: [on-prem] Cleanup keepalived vips before starting service

- pkg/operator/render.go
When status.Migration is set in network.config. MCO shall render
the node according to the target networkType.
> Bug 1937594: Respect status.Migration in network.config when exsits

- pkg/operator/status.go
Previously the kni namespace was explicitly listed in must-gather,
but when I went to add the other on-prem ones it was pointed out
that this should probably be done with relatedObjects. This adds
the namespaces here so we don't need anything in must-gather itself.
Added on-prem service namespaces to relatedObjects so they will be included in must-gather.
> Bug 1948022: Add on-prem namespaces to relatedObjects

- install/0000_80_machine-config-operator_00_namespace.yaml
- install/0000_80_machine-config-operator_04_deployment.yaml
- manifests/bootstrap-pod-v2.yaml
- manifests/machineconfigcontroller/deployment.yaml
- manifests/machineconfigdaemon/daemonset.yaml
- manifests/machineconfigserver/daemonset.yaml
- manifests/on-prem/coredns.yaml
- manifests/on-prem/keepalived.yaml
- pkg/operator/assets/bindata.go
In support of the workload partitioning feature (https://github.com/openshift/enhancements/pull/703), we need to add annotations to all management pods and namespaces so they can be properly identified and assigned to segregated management cores on clusters configured to do so.
Added the new workload identification annotations to all namespaces, pods, and pod templates to support the workload partitioning feature (https://github.com/openshift/enhancements/pull/703)
This will be verified by the team performing the work for the workload partitioning feature; but it should be as simple as verifying that all machine-config-operator namespaces have the `workload.openshift.io/allowed: "management"` annotation, and all machine-config-operator pods running …
> Add management workload annotations

- pkg/daemon/update.go
Return the error if the podman cp fails during a failed OS update,
instead of continuing on and having the next chcon command error
being reported to the operator status.
For the linked bug, it is a bit odd because I think if the command did
fail, the MCD should have logged warnings. Regardless, we should
try to return the error if it occurs.
> Bug 1950112: properly return error in failed podman cp

- templates/common/_base/files/NetworkManager-keyfiles.yaml
- templates/common/_base/files/configure-ovs-network.yaml
- templates/common/_base/files/nm-tmpfiles.yaml
- templates/common/_base/units/nm-system-connections-mount.yaml
- templates/common/baremetal/files/NetworkManager-static-dhcp.yaml
Looks like there is a bug in 8.4 systemd which causes the system-connections-merged mount unit to not be enabled. On further investigation looks like systemd does not like the `\x2d` character when enabling presets. While this issue needs to be investigated by the systemd folks, changing the name here so that UPI baremetal deploys can succeed.
> Bug 1950974: change system-connections-merged directory to systemConnectionsMerged

- templates/common/on-prem/files/keepalived.yaml
Keepalived doesn't necessarily start immediately when its container
is created. It waits until keepalived.conf exists. In some case,
it takes longer for the config file to be created than for the
liveness probe to time out, which triggers unnecessary restarts of
the container. Once the monitor populates keepalived.conf it will
send the reload command, which starts keepalived.
This change just adds a check for the keepalived.conf file to the
liveness probe. This way, the liveness probe will always succeed
until keepalived.conf is created.
> Bug 1949664: [on-prem] Disable liveness probe until keepalived.conf exists

- install/0000_80_machine-config-operator_04_deployment.yaml
- manifests/bootstrap-pod-v2.yaml
- manifests/machineconfigcontroller/deployment.yaml
- manifests/machineconfigdaemon/daemonset.yaml
- manifests/machineconfigserver/daemonset.yaml
- manifests/on-prem/coredns.yaml
- manifests/on-prem/keepalived.yaml
- pkg/operator/assets/bindata.go
As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
As before, this will be verified via a an e2e test in CI still under development.
None (fix to previous change)
/hold
Hold until after openshift/kubernetes#632 is merged please
> Rename workload annotations

- pkg/controller/common/helpers.go
- pkg/controller/common/helpers_test.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1934176
I added some code to `pkg/controller/common/helpers.go` to ensure that when Ignition 2 configs are converted to Ignition 3, all `PasswdUser` objects contain per-user-unique `AuthorizedSSHKey`. Not ensuring the SSH keys are unique results in a degraded state for the MCO.
Ensures SSH keys are unique for translation from Ignition 2 to Ignition 3.
> Bug 1934176: ensure SSH key uniqueness

- templates/common/_base/units/nodeip-configuration.service.yaml
> Bug 1942488: Use new --prefer-ipv6 flag to "runtimecfg node-ip" as appropriate

- templates/common/on-prem/files/keepalived.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1931505  reproduced in QE folks environments even with the latest version,
seems that changing vip filtering syntax solved the problem locally.
> Bug 1931505: [On-prem] - fix vip filtering syntax for Keepalived remove-vips

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1953846
Subtract hugepages while calculating the metrics for the alert `SystemMemoryExceedsReservation`
If the hugepages are disabled on your cluster then the old query,
```
sum by (node) (container_memory_rss{id="/system.slice"}) > ((sum by (node) (kube_node_status_capacity{resource="memory"} - kube_node_status_allocatable{resource="memory"})) * 0.9)
```
and the new query
```
((sum by (node) (kube_node_status_capacity{resource="memory"}) - sum by (node) (kube_node_status_capacity{resource="hugepages_1Gi"}) - sum by (node) (kube_node_status_capacity{resource="hugepages_2Mi"}) - sum by (node) (kube_node_status_allocatable{resource="memory"}) - sum by (node) …
```
> Bug 1953846: Subtract hugepages from memory capacity and allocatables

- templates/master/00-master/gcp/units/openshift-gcp-routes.service.yaml
The gcp-routes script handles the traffic from external LB
directed to the node, hence, it should start before the network
is up, and it should exit after the network goes down.
> Bug 1956372: gcp-routes should wait until network is stopped

- templates/common/on-prem/files/keepalived.yaml
This is a combined backport of the fixes in #2511 and #2548 . It works around a bug in keepalived that could cause duplicate VIPs to be assigned to nodes.
Deploy a cluster. When this bug occurs, operators like console and authentication fail to deploy because they can't talk to the ingress VIP correctly.
Fix an intermittent issue with VIPs being duplicated across multiple nodes.
> Bug 1957015: [on-prem] Backport duplicate VIP fixes

- pkg/daemon/daemon.go
This is a non-automated cherry-pick of #2431.
> [release-4.6] Bug 1933206: Revert "pkg/daemon: Add IgnitionVersion to Daemon"

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Instead of asking folks to look up the pod using the node name, use the pod label that the Prometheus scraper adds automatically when scraping metrics off the daemon pod.  While I'm touching this, I'm pivoting to the automatic label for the namespace as well, even though that is very unlikely to change.  The container being scraped is `oauth-proxy`, so I'm leaving the target container hard-coded to `machine-config-daemon`, since that's where the interesting logs are.
> Bug 1957374: install: Automatically fill in the pod for MCDDrainError

- manifests/machineconfigdaemon/daemonset.yaml
- pkg/operator/assets/bindata.go
- pkg/operator/render_test.go
If a wildcard (*) is used in the `noProxy` field, it is not properly quoted before being rendered into YAML, causing `resourceread.ReadDaemonSetV1OrDie()` to fail because the rendered YAML was `noProxy: *` instead of `noProxy: "*"`.
The reason for the read failure is because an unquoted asterisk has special meaning in YAML, typically used to repeat other sections (which we're not doing here).
Fixes: #1947066
I added quotes to the `manifests/machineconfigdaemon/daemonset.yaml` file around the optional `noProxy` field.
I've updated the unit test suite `pkg/operator/render_test.go` to read the rendered templates using the appropriate `resourceread` function.
Allow wildcard (*) in noProxy field
> Bug 1947066: Allow wildcard in noProxy field

- templates/common/ovirt/units/nodeip-configuration.service.yaml
This change adds the nodeip-configuration.service to the oVirt platform.
On 4.7 due to the unification of the unit files of each on prem platform to the "on-prem" directory oVirt got the "nodeip-configuration.service" file but on 4.6 release we are missing it which can cause hard to debug problems to customers.
This change also adds fixes for BZ#1940939 https://github.com/openshift/machine-config-operator/pull/2470
** I was not able to reproduce the issue on BZ#1948533 but this change seems relevant and according to the comments on BZ#1948533 will fix the issues
Install a 4.6 ovirt cluster
> Bug 1948533: Add nodeip-configuration.service for oVirt

- templates/common/_base/files/NetworkManager-keyfiles.yaml
- templates/common/_base/files/configure-ovs-network.yaml
1. Configure keyfile as the default plugin of NetworkManager explicitly for all nodes. It is the default setting in RHCOS.
2. Fix configure-ovs.sh script for RHEL7 workers with old version NetworkManager.
> Bug 1917282: Explicitly set keyfile as the default plugin of NetworkManager for RHEL7

- templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
- templates/common/_base/units/machine-config-daemon-pull.service.yaml
- templates/common/_base/units/nodeip-configuration.service.yaml
- templates/common/on-prem/units/nodeip-configuration.service.yaml
or else they may race against each other, causing issues with crio-wipe running on a forced shutdown
both machine-config-daemon-pull.service and nodeip-configuration.service must run after crio wipe runs, to protect against a corrupted image storage from a forced reboot
> Bug 1943539: templates: order service files that use podman around crio-wipe

- docs/README.md
The MCO [has a bug][1] where it relies on its commit hash to mark the target version of rendered MachineConfigs.  We didn't get a bump, or even a rebuild between 4.7.11 and 4.7.12:
```console
$ oc adm release info --commits quay.io/openshift-release-dev/ocp-release:4.7.11-x86_64 | grep machine-config-operator
machine-config-operator                        https://github.com/openshift/machine-config-operator                        e3863b02b7403342cdf0f981889e8c3cfc2d86bb
$ oc adm release info --commits quay.io/openshift-release-dev/ocp-release:4.7.12-x86_64 | grep machine-config-operator
machine-config-operator                        https://github.com/openshift/machine-config-operator                        e3863b02b7403342cdf0f981889e8c3cfc2d86bb
```
So the MCO starts updating the pools …
> docs/README: Useless bump to get a new commit hash

- pkg/daemon/rpm-ostree.go
- pkg/daemon/update_test.go
Using `CombinedOutput()` here is wrong since e.g. for invoking
things like `rpm-ostree status --json` we don't want to try to
ever parse stderr text.
Instead, propagate the stderr text into the error, so it
will be reported up into the daemon logs where we can see the
actual error text.
> Bug 1958812: daemon: Change runGetOut to not intermix stdout/stderr

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
to make sure we're calling CNI del on a node reboot
> Bug 1948137: crio: enable internal_wipe option

- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
Fix BZ 1955517: upgrade when there are more than one configs,
these generated MC will be duplicated by upgraded MC with
number suffixed name (func getManagedKubeletConfigKey()) and fails the upgrade.
Remove the mc if its generated and degraded.
> Bug 1955517: Add cleanUpDuplicatedMC

- cmd/machine-config-controller/start.go
- manifests/machineconfigcontroller/clusterrole.yaml
- pkg/apis/machineconfiguration.openshift.io/v1/types.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
- pkg/operator/assets/bindata.go
Mixin the default `apiserver.v1.config.openshift.io` config singleton to configure the KubeletConfig's TLSSecurityProfile. The KubeletConfig can override the global setting, but the global setting takes precedence. 
Unit+Integration Tests
> Bug 1958391: configure kubelet with apiserver TLSSecurityProfile

- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
Open this PR to chery-pick #2570, since the /cherry-pick command failed https://github.com/openshift/machine-config-operator/pull/2570#issuecomment-847286280
Fix Bug 1964568: upgrade when there are more than one configs,
these generated MC will be duplicated by upgraded MC with
number suffixed name (func getManagedKubeletConfigKey()) and fails the upgrade.
Remove the mc if its generated and degraded.
> [release-4.7] Bug 1964568: Delete duplicated generated mc 

- pkg/daemon/rpm-ostree.go
- pkg/daemon/update_test.go
If we get an error deserializing, let's log a bit of the actual output
so we can better figure out what's going on there.
xref https://bugzilla.redhat.com/show_bug.cgi?id=1958812
> Bug 1958812: daemon: Display more non-JSON text from rpm-ostree status --json

- templates/common/on-prem/files/keepalived.yaml
Mount the host filesystem as /host in the keepalived container so that
the host's iptables binary can be called in the keepalived setup script
This PR works in combination with openshift/images#89
> Bug 1960035: Use host's iptables binary in keepalived container

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
otherwise, we create /etc/hostname as a directory, which causes issues on reboot
> Bug 1921937: crio: reject /etc/hostname mount if absent

- templates/common/on-prem/files/coredns.yaml
- templates/common/on-prem/files/keepalived.yaml
- templates/master/00-master/on-prem/files/haproxy.yaml
Kubelet complains about empty files in the manifests directory because
it can't parse them. While this doesn't cause any harm, it has caused
bugs to be mis-routed because people see the error messages while
debugging and think something is wrong.
Instead of conditionalizing the content of the files, we can
conditionalize the path and just write them to a disabled location
so they won't be deployed and they also won't be processed by kubelet.
Note that I tried just using /dev/null to avoid writing the files
entirely, but I was not able to get that to work.
> Bug 1927042: [baremetal & friends] Don't write empty static pod manifests

- templates/master/01-master-kubelet/_base/files/kubelet.yaml
- templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
It's on by default now, and setting it explicitly may result in an initial kubelet config that doesn't match the post-bootstrap one.
I think we're not hitting this in CI because we're still explicitly setting the feature gate there...
> Bug 1966602: Don't explicitly set the IPv6DualStack feature gate

- manifests/on-prem/keepalived.conf.tmpl
- pkg/operator/assets/bindata.go
The nopreempt option has the opposite effect to what we want on the
bootstrap. In our current LB architecture, we want the VIP to be on
the bootstrap any time the bootstrap api is running. nopreempt
breaks this by not allowing the VIP to move back to the bootstrap
if there happens to be a blip in the bootstrap apiserver that causes
keepalived to stop temporarily while one of the masters is running.
The following sequence of events is the problematic one:
1) A master keepalived instance comes up
2) There is a temporary outage of the bootstrap apiserver.
3) Bootstrap keepalived-monitor notices the outage and stops the
bootstrap keepalived.
4) The master keepalived takes the VIP
5) The bootstrap apiserver comes back up.
6) Bootstrap keepalived-monitor notices that the api is back and …
> Bug 1916890: Stop setting nopreempt on bootstrap keepalived.conf

- templates/common/_base/units/nodeip-configuration.service.yaml
Backport of #2478 / #2525 to 4.6, to make nodeip-configuration work for single-stack IPv6 on nodes with stray IPv4 addresses.
(baremetal-runtimecfg PR has already merged)
> Bug 1942506: [4.6] Use new --prefer-ipv6 flag to "runtimecfg node-ip" as appropriate

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
- pkg/daemon/drain.go
- pkg/daemon/metrics.go
As per retro and subsequent follow-up conversation, make a short term bump to the pool drain degradation to 1hour since the existing times are too short for many users and cause premature erroring/degrading.
In addition:
Refactor drain() since exponential backoff is not suitable for these longer durations. 
Refactor the metric and reduce cardinality, and remove 15min delay on alert.
> Bug 1968019: Bump drain timeout to 1h

- cmd/common/helpers.go
As a temporary solution in lieu of graceful shutdowns, have the
operator and controller pods use faster defaults for lease/renew/
retry, which shouldn't otherwise notably affect operation other
than the new pod acquiring a new lease faster during upgrades,
saving some waiting time.
Example in CVO: https://github.com/openshift/cluster-version-operator/blob/706a0062cade643767e95da2e6142823e8399986/pkg/start/start.go#L51
> Bug 1817075: operator/controller pods: faster leader elections

- lib/resourcemerge/apps.go
- lib/resourcemerge/apps_test.go
The configuration change fix from Bug #1899535 ( set maxUnavaiable to "10%" instead of "1") worked only against newly installed clusters because the EnsureDaemonSet function in resourcemerge doesn't merge the UpdateStrategy part of the DaemonSet structure. 
This PR makes EnsureDaemonSet additionally merge the UpdateStrategy part of the structure so it also works for cluster upgrades. 
- Fixes #1959258
- Added code to merge the UpdateStrategy portion of the DaemonSet as part of a resource merge if it has been updated
- Added unit test just to make sure the UpdateStrategy structure gets merged as part of EnsureDaemonSet (if UpdateStrategy has been updated)
- Verified that this works by upgrading 4.5 -> 4.6 -> 4.7 -> this commit (4.8) and verifying …
> Bug 1969681: maxUnavailable of ds/machine-config-daemon isn't changed even after Bug 1899535 was fixed 

- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
Fix: Bug 1946584 https://bugzilla.redhat.com/show_bug.cgi?id=1946584
When checking whether managedKey has MC name suffix annotation, add validation to confirm it is a number type as we added.
> Bug 1946584: Check suffix annotation is a number

- pkg/daemon/drain.go
- pkg/daemon/drain_test.go
- pkg/daemon/update.go
Today, we perform drain for any changes made into container registry config file /etc/containers/registries.conf.
- To avoid users workload disruption, we can safely skip drain for some of the changes made into the config file. Such as:
1. A new mirror is added to an existing registry that has `mirror-by-digest-only=true`
2. A new registry has been added that has `mirror-by-digest-only=true`
- If any other unsafe changes are detected in registry conf, MCD will default to perform node drain.
- Also added unit tests.
> Bug 1943315: daemon: make node drain logic smarter for ICSP changes

- pkg/daemon/rpm-ostree.go
- pkg/daemon/update.go
- pkg/daemon/update_test.go
This is the dual/inverse of https://github.com/openshift/machine-config-operator/pull/2583
Replace all the parts where we were using `runGetOut` but not actually processing
the output with a function that:
- Writes rpm-ostree stdout to our stdout
- Captures stderr for propagation into the error we return
Instead of gathering the data from both streams into a pipe but then
discarding it.
(Now the daemon also logs into the journal, but there's not much
harm from capturing both client and daemon output)
> Bug 1958812: daemon: Rework rpm-ostree synchronous invocation logging

- templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
- templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Ingress VIP should be set only on a node that runs an instance of
the default ingress controller pod.
In current code, in case extra ingress-controllers are created the
ingress VIP might be wrongly set on a node that doesn't run an instance of
the default ingress controller.
This PR sets keepalived ingress priority to a variable, the variable should be calculated and set by 
baremetal-runtimecfg based on the presence of the router pod in the node.
This PR should be merged after  - https://github.com/openshift/baremetal-runtimecfg/pull/141
> Bug 1886572: [on-prem] set keepalived ingress priority to variable

- templates/common/vsphere/files/vsphere-hostname.yaml
- templates/common/vsphere/units/vsphere-hostname.service.yaml
Fixes: BZ1927555 - when creating a new machine, the node will get an unexpected hostname
Note: This pull-request is a replacement for PR 2404.  A problem was found in release-4.7 which required a change to PR 2404.
- What I did
Added the --static flag to hostnamectl to prevent DHCP from overriding the hostname sourced from guestinfo. 
Configure DHCP to assign a hostname as part of the lease
Scale a new node
The node should automatically join the cluster with a node name like <cluster>-<clusterid>-worker-<name>
Resolves issue where the hostname provided by the DHCP overrides the guestinfo hostname thus preventing the machine-api-controller from reconciling new nodes which receive a hostname from DHCP.
> [release-4.6] Bug 1927555: [vsphere] set hostname with --static to provide consistent node name for CSR approval

- install/0000_80_machine-config-operator_03_rbac.yaml
Partial cherry-pick of #2572 to update CRB to v1, as we'd like to drop RBAC v1beta1 support in 4.7 CVO
> [release-4.7] Bug 1961341: rbac: update remaining apis to v1

- templates/common/baremetal/files/baremetal-coredns.yaml
- templates/common/baremetal/files/baremetal-keepalived.yaml
- templates/common/openstack/files/openstack-coredns.yaml
- templates/common/ovirt/files/ovirt-coredns.yaml
- templates/common/vsphere/files/vsphere-coredns.yaml
Now that we are using the loadbalanced endpoint for keepalived
healthchecks, it is not correct to be using the local apiserver for
readiness checks. Also, I don't think there's any need for readiness
checks on the monitor. Kubernetes isn't routing any traffic to this
pod, so its ready status is meaningless.
Removed unnecessary readiness probes for on-prem services. This should clear up warnings about unready containers.
> Bug 1940594: [baremetal and friends] Drop unnecessary readiness probes

- pkg/daemon/daemon.go
- pkg/daemon/update.go
Also, add log and event for successful node cordon.    
cordoning the node accidentally got removed in https://github.com/openshift/machine-config-operator/pull/2605.
> Bug 1973006: daemon: cordon the node before performing drain

- install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
Bug 1971899: match tlsSecurityProfile oc explain doc with the output of kubelet.conf file.
> Bug 1971899: match tlsSecurityProfile  doc with kubelet.conf file

- templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
- templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
The new version of keepalived recommends setting a config value of
max_auto_priority. Since we are not having performance issues with
keepalived to my knowledge, I'm just setting it to -1 to suppress
the message.
In addition, the worker config was missing a couple of settings
related to running check scripts. Those were already present in the
master config so I've added them for workers too.
> Clean up keepalived log messages

- Dockerfile.proxy
- docs/openshift-proxy-pull-test.md
This image will be added into the ocp-build-data(https://github.com/openshift/ocp-build-data)
repository. So product MCO(https://github.com/openshift/machine-config-operator) can
pull the image through a proxy that the customer configured to validate the proxy.
Ticket for the image build request: https://issues.redhat.com/browse/ART-2961
> Add Dockerfile for proxy test image

- templates/common/_base/files/audit-quiet-containers.yaml
I was going to go add a check for "system has an AVC denial"
but the problem today is that every time a container starts or
stops *and* most notably liveness probes end up generating
audit events.
This very quickly rotates out audit events that we *do* care
about.
Outside of Kubernetes, workloads can be much more "static"
and it makes sense for "iptables rules changed" to cause an
audit event.  For OpenShift, it doesn't make sense.
Silence that and the promiscuous device one so that we can
more easily read the audit logs captured from a CI run to
verify there were no AVC denials.
This will also be useful preparation for e.g. teaching
the MCO do watch for some types of audit event (such as
AVC) and bridge them to Prometheus metrics or so.
> templates: Silence audit events from container infra by default

- pkg/daemon/update.go
The machine config daemon's SIGTERM protection was not being removed on 
rebootless updates.The existing logic made sense before rebootless updates
were a thing, but now if an update happens and we don't reboot, the MCD 
protects itself from SIGTERM forever.
Also, the sequence of functions triggerUpdateWithmachineConfig->
update->performPostConfigChangeAction is recursive, so if we put the
work from https://github.com/openshift/machine-config-operator/pull/2395 back in to solve this, or try to use the mutex "properly" we'll
potentially deadlock on ourselves under the right conditions. 
- This PR removes an if condition so the SIGTERM protection is removed
on a successful rebootless update and also adds some logging messages to make 
it more apparent when the protection is being …
> Bug 1965992: Gracefully shutdown taking around 6-7 mins (libvirt provider) 

- cmd/machine-config-controller/start.go
- go.mod
- go.sum
- pkg/controller/common/constants.go
- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_features.go
- pkg/controller/kubelet-config/kubelet_config_features_test.go
- pkg/controller/template/render.go
- pkg/controller/template/render_test.go
- pkg/controller/template/template_controller.go
- pkg/controller/template/template_controller_test.go
- vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go
- vendor/modules.txt
Implementing external cloud provider selection forced by feature gate. Described in the proposal: https://github.com/openshift/enhancements/pull/463/files#diff-3e0e2c48e70215076dfe36c13768a823ab7080d929d80292f37db2ef5a2121e8R201
This PR is main blocker on other work with integrating CCM in Openshift: https://issues.redhat.com/browse/OCPCLOUD-1107
> [OCPCLOUD-1107] External cloud-provider support via FeatureGate in post-install

- templates/common/_base/files/configure-ovs-network.yaml
configure-ovs sets the master device name as connection.master on slave
connection profiles when the default gateway being replaced is a master
device.
Those slave profiles may activate before the master profile and if so,
NM may chose non-deterministically any master profile that might provide
a connection for the master device name, which may be the old master
connection profile instead of the replacement connection profile. The
auto-connect priority does not seem to be considered as this might not
be regarded by NM as an auto-connect of the master profile in strict
sense.
Setting the master connection profile uuid as connection.master on slave
connection profiles ensures that the correct master profile is activated
when the slave auto-connects. This does require a bit …
> Bug 1971715: configure-ovs: fix nondeterministic master in slave profiles

- templates/common/_base/files/usr-local-bin-mco-hostname.yaml
- templates/common/aws/files/etc-networkmanager-conf.d-hostname.yaml
- templates/common/aws/units/aws-hostname.service.yaml
During kubelet migration from `--cloud-provider=aws` to `--cloud-provider=external` kubelet determines `Node` name by the hostname of the machine where it is running. AWS hostname is mismatched, usually it is a reversed DNS mapping of machine ip, like  `ip-10-0-195-176`. This results in node name mismatch in kubelet, and API server admission plugin rejects changes for the object.
This fixes the issue.
- Ensure that new nodes provisioned by kubelet will report hostname with aws prefix, typically reversed IP mapping + `<region>.compute.internal` even when the cloud-provider is set to `external`.
> [OCPCLOUD-1106] Add afterburn task to update AWS hostname to match instance metadata

- pkg/daemon/daemon.go
daemon: Rename `os` variable to `hostos`
Prep for a future patch; `os` conflicts with the standard Go package.
---
daemon: Dump systemctl status rpm-ostreed on load failure
This is yet another patch which should help debugging
https://bugzilla.redhat.com/show_bug.cgi?id=1958812
like situations in the future.
I also have https://github.com/coreos/rpm-ostree/pull/2932
cooking but it's going to take a while to cycle down.
---
>  daemon: Dump systemctl status rpm-ostreed on load failure

- templates/common/_base/files/configure-ovs-network.yaml
The configure-ovs.sh script does not provide the correct team interface configuration format in nmcli command. It fails with:
```
Error: failed to modify team.config: team configuration must be a JSON object.
```
Corrected team interface configuration format.
Install OpenShift with OVNKubernetes using team interface.
Modify the script to correct the team interface configuration format.
> Bug 1934443: Fix team config JSON format for nmcli command

- templates/common/_base/units/crio.service-proxy.yaml
- templates/common/_base/units/crio.service.yaml
- templates/common/_base/units/kubelet.service-proxy.yaml
- templates/common/_base/units/kubelet.service.yaml
The template rendering has broken merge logic, which causes us
to lose some templates. This was originally fixed for 4.7
(see https://github.com/openshift/machine-config-operator/pull/2378/)
but previous cherry-pick failures + a recent backport of another
bug broke this for 4.6.
Split the crio/kubelet dropins such that we don't break the proxy.
> Bug 1978041: templates: split unit dropins into separate files

- templates/common/_base/files/NetworkManager-keyfiles.yaml
- templates/common/_base/files/configure-ovs-network.yaml
1. Configure keyfile as the default plugin of NetworkManager explicitly
for all node. It is the default setting in RHCOS.
2. Fix configure-ovs.sh script for RHEL7 workers with old version
NetworkManager
(cherry picked from commit 5af273d4c986bc7018882afdfeab6d3479469bb6)
> Bug 1976232: Explicitly set keyfile as the default plugin of NetworkManager for RHEL7

- pkg/daemon/daemon.go
For better debugging in future for bugs like
https://bugzilla.redhat.com/show_bug.cgi?id=1975907,
let's explicitly log and add event when a node has
been successfully uncordoned by MCO.
> daemon: add log and event for uncordoning node

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
This reverts commit faa05e7e87bd03cfd9d05fca3576f1dcf14130dc.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1979297
It seems like we incorrectly modified a prometheus alert `SystemMemoryExceedsReservation`
On a system with hugepages configured the alert should not fire without memory stress. 
> Bug 1979297: Revert "Subtract hugepages from memory capacity and allocatables"

- templates/master/00-master/on-prem/files/haproxy.yaml
The HAProxy-monitor container should start running only after applying the NM prepender script
(to be able to communicate with api-int: kube-api).
We noticed that in the current implementation (Liveness probe) we may break the API traffic for a
few seconds even because of changes in host's resolv.conf that aren't relevant to the HAProxy monitor.
This PR replaces the Liveness probe that compares resolv.conf and host's resolv.conf
with an init container.
> Bug 1980658: ON-PREM] HAProxy - Verify that NM prepender script was applied using initcontainer

- docs/KubeletConfigDesign.md
- install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
Close https://bugzilla.redhat.com/show_bug.cgi?id=1975626
Backport of https://github.com/openshift/machine-config-operator/pull/2358 since the cherrypick robot failed. https://github.com/openshift/machine-config-operator/pull/2358#issuecomment-768780813
> [release-4.6] Bug 1975626: KubeletConfig validation warning in CRD and Docs

- pkg/daemon/daemon.go
- pkg/daemon/rpm-ostree.go
- pkg/daemon/rpm-ostree_test.go
This is a workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1982389
which is already fixed in rpm-ostree in
https://github.com/coreos/rpm-ostree/pull/2995
because it will take a fair while until we can ship the fixed
rpm-ostreed in RHEL and then OpenShift stable versions.
(Yes, this is a sad recurring pattern)
The updater client gains an explicit `Initialize` method, where
we also explicitly `systemctl start rpm-ostreed` which
then effectively rolls in the change from
https://github.com/coreos/rpm-ostree/pull/2945
too.
> daemon: Explicitly start rpm-ostreed, restart if we detect active txn

- templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
To use the -x option [1] in HAProxy the socket must be enabled using "expose-fd listeners" in haproxy configuration.
[1] https://github.com/haproxy/haproxy/blob/c3fe968f221e2f7c63b7eb24f557223c4bbbe75f/doc/management.txt#L325
> Bug 1981090: [ON-PREM] HAProxy - enable listening sockets retrieval from old processes

- templates/common/_base/files/configure-ovs-network.yaml
When teamed/bonded interfaces are presented to the ovs-configure
script, the uevent file doesn't exist under the device dir because
there is no actual net-device corresponding to the bond. This
commit adds a more clear error message for handling team/bonded
interfaces.
Signed-off-by: Aniket Bhat <anbhat@redhat.com>
> Bug 1982052: Handle team/bond interfaces with a more clear message

- templates/common/_base/files/configure-ovs-network.yaml
Pull request #2626 did not account for a possible scenario where
networking configuration would be backed with ifcfg files instead of
nmconnection files. Attempting to persist slave nmconnection changes in
case of an overlay setup of NM configuration directory would fail.
Additionally opted for a strategy of cloning slave connection profiles
instead of modifying them directly to avoid any interference with MCO
existing configuration.
Also fixed shellcheck reported issues in 4.8 backport pull request #2639.
fixes: #2626
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1971715
> Bug 1971715: configure-ovs: fix bond ifcfg backed configuration

- templates/common/on-prem/files/keepalived.yaml
- templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
- templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Ingress VIP should be set only on a node that runs an instance of the default
ingress controller pod.
In the current code, the keepalived-monitor container calculates the priority for keepalived ingress
VIP depending on the presence of the router pod in the node by monitoring the content of
router-internal-default endpoints resource.
This PR moves the ingress dynamic priority setting to Keepalived track_script which makes it easier
to debug and eliminates the need for keepalived container reload in case of priority change.
> On-prem: add default ingress track script to Keepalived

- pkg/daemon/drain.go
So we're symmetric for both cordoning and uncording.
Including the node name in the message is not strictly necessary, because it is already in the event's referenced object.  But the message is pretty short otherwise, so repeating the node name inline seemed like it might be a good use of space.
> pkg/daemon/drain: Clarify "cordon/uncordon" messages

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
This reverts commit 4554713bef99dcfc80ef9fc48788f4042881083e.
Attempt to drop infra container again, now with a test that verifies we don't regress in the same way that
caused us to revert before
> Revert "Revert "crio: drop infra container when possible""

- templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
Log curl errors, ~with `--fail-with-body`~ (edit: [no longer using `--fail-with-body` due to RHCOS's old `curl`](https://github.com/openshift/machine-config-operator/pull/2617#issuecomment-881700256)):
```console
$ man curl | grep -A6 '^ *--fail-with-body'
--fail-with-body
(HTTP)  Return an error on server errors where the HTTP response code is 400 or greater). In normal cases when an HTTP server fails to deliver a document, it returns an HTML document stating so (which often also describes why and more). This
flag will still allow curl to outputting and save that content but also to return error 22.
This is an alternative option to -f, --fail which makes curl fail for the same circumstances but without saving the content.
See also -f, --fail. Added in 7.76.0.
```
This should avoid …
> Bug 1971046: templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes: Stderr for curl errors

- templates/common/_base/files/configure-ovs-network.yaml
A recent feature in OVNK requires the presence of a second optional ovs
bridge configured at host level.
Here we change the script so that if a file is available under
/etc/ovnk/extra_bridge, it's content is used to choose the interface to
back up the second bridge and to apply the configuration.
> Ovs bridge setup: Create an optional second bridge

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
We now can configure metrics by referencing the collector since
https://github.com/cri-o/cri-o/pull/5061 has been merged.
This patch adds the default CRI-O metrics collectors and reflects the
previously overwritten state from the Cluster Monitoring Operator (CMO).
Verify that the configured metrics are being served.
Added CRI-O `metrics_collectors` configuration.
> Add CRI-O metrics collectors configuration

- pkg/controller/bootstrap/bootstrap.go
- pkg/controller/bootstrap/bootstrap_test.go
- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_features.go
- pkg/controller/kubelet-config/kubelet_config_features_test.go
- pkg/controller/template/template_controller.go
Note, the first two commits of this PR are currently the content of #2647, there would be conflicts if I tried to implement it individually so thought it was quicker to leave this based on that.
I've extracted some of the logic in the kubeletconfig package to standalone functions rather than being part of the `Controller.` This is the first commit "Extract KubeConfig FeatureGate ignition to a standalone function"
Then I've copied the logic from the feature gate sync into a bootstrap ready `RunFeatureGateBootstrap` function, and then we run this if a `FeatureGate` is detected in the manifests directory.
* `openshift-install create install-config`
* `openshift-install create manifests`
* Add a FeatureGate yaml resource to the manifests directory
``` …
```
> [OCPCLOUD-1209] Run KubeletConfig FeatureGate sync during bootstrap

- cmd/machine-config-operator/start.go
- pkg/operator/operator.go
- pkg/operator/status.go
- pkg/operator/status_test.go
ref: https://issues.redhat.com/browse/OCPNODE-595
replace https://github.com/openshift/machine-config-operator/pull/2552
Check for API server and node versions skew.
Update with the message the Kube API version is skew too far, but do not force
`Upgradeable=False` according to enhancement https://github.com/openshift/enhancements/pull/762/files
> Bug 1986453: Check for API server and node versions skew

- templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
- templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
We've noticed that the ingress VIP could be flapping in some
environments where the keepalived check fails due to timeout. We should
make the ingress check more resilient to errors and start using `fall`
and `raise` to mitigate flapping as we did for the API checks.
> Bug 1982766: [on-prem] Make ingress VIP more tolerant to failures

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Originally from: https://github.com/openshift/machine-config-operator/pull/2629
- What I did
Add the CPU and Memory alerts for the master nodes - https://issues.redhat.com/browse/OCPNODE-542
If the CPU or the Memory consumption goes beyond the specified limit in the alert then it should fire.
Add CPU and memory alerts for the master nodes
> Bug 1987948: OCPNODE-542: Add CPU and memory alerts for the master nodes

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
to make sure we're calling CNI del on a node reboot
> [release-4.7] Bug 1977432: crio: enable internal_wipe option

- lib/resourcemerge/apps.go
- lib/resourcemerge/apps_test.go
Manual backport of #2601
Also, remove MaxSurge field from 4.8 unit test because that field didn't 
exist in the RollingUpdateDaemonSet structure back in in 4.7.
( Was originally #2608 but the unit test failed )
> [release-4.7] Bug 1970166: MCO: maxUnavailable of ds/machine-config-daemon does not get updated due to missing resourcemerge check

- pkg/controller/kubelet-config/helpers.go
Add nil check for KubeletConfig to fix the nil pointer panic.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1975626
> Bug 1975626: Fix KubeletConfig nil error

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
> Bug 1992557: crio: use conmon from path

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1980844
SystemMemoryExceedsReserved alert should fire at 95% utilization instead of existing 90%.
> Bug 1980844: bump SystemMemoryExceedsReservation alert threshold to 95%

- Makefile
- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
- pkg/daemon/daemon.go
- pkg/daemon/metrics.go
- pkg/daemon/update.go
> [release-4.6] Bug 1987221: Backport drain timeout optimizations

- pkg/daemon/update.go
- pkg/daemon/update_test.go
Also, make kargs variable and function name logical to
avoid confusion.
Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/2349
> [release-4.6] Bug 1989403: daemon: add check before updating kernelArgs

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Instead of relying on /etc/crio/crio.conf (shipped in the cri-o rpm) for fields, we should import all relevant fields into MCO.
This will allow us to eventaully use MCO to remove /etc/crio/crio.conf (and have the rpm stop shipping it).
We do this because there exists a feature where rpm-ostree pins a file if it was ever managed by an RPM, and doesn't update it.
however, we want to be able to change crio configuration post-installation, and having a pinned crio config could interfere with that.
Finally, even though conmon path ("conmon" option) is set to the default, we include it here, to work around the aforementioned bug manifesting
in CRI-O failing to come up.
> Bug 1995785: crio: complete crio default config

- templates/common/_base/units/ovs-vswitchd.service.yaml
This bug was previously fixed in a different way: https://github.com/openshift/cluster-network-operator/pull/1142
And then reverted: https://github.com/openshift/cluster-network-operator/pull/1163
Set ovs syslog level to info (default is err), to collect info level logs with must-gather since it uses systemd journal.
ovs-vswitchd service runs `ovs-ctl` to start and reload service (https://github.com/openvswitch/ovs/blob/master/rhel/usr_lib_systemd_system_ovs-vswitchd.service.in#L23).
`ovs-ctl` doesn't let you set log level on start (https://github.com/openvswitch/ovs/blob/master/utilities/ovs-ctl.in#L214)
So, I added `ExecStartPost` to the service which sets right log level on start and restart.
There is also `reload` operation defined for the service …
> Bug 1970129: Set ovs syslog level to info

- pkg/operator/status.go
To further debug, add event when MCO reports unavailable or degraded to CVO
> Bug 1955300: operator: add event on degraded and unavailable status

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
> [release-4.7] Bug 1995810: crio: complete crio default config

- templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
- templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Once you change the memory manager policy it requires removing the memory manager state file, otherwise, the kubelet will fail to restart. To avoid kubelet start failures during the change of the memory manager policy we can remove the state as `PreStart` condition under the systemd unit file.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
Delete the memory manager state file before the kubelet start
> Bug 1994277: delete the memory manager state file before the kubelet start

- install/0000_80_machine-config-operator_00_namespace.yaml
This appears to have been copy-pasta from the MCO namespace, but we
don't need it for the on-prem services.
Dropped the runlevel specifier for the on-prem namespaces. It was not necessary and may have caused confusion about the services running in the namespace.
> Bug 1973525: [on-prem] Drop runlevel from infra namespaces

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Catching the message up with the logic change from 5148f16bd6 (#2716).
> Bug 1980844: install/0000_90_machine-config-operator_01_prometheus-rules: Doc 95% for SystemMemoryExceedsReserved

- templates/common/on-prem/files/keepalived.yaml
- templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
- templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Ingress VIP should be set only on a node that runs an instance of
the default ingress controller pod.
In current code, in case extra ingress-controllers are created the
ingress VIP might be wrongly set on a node that doesn't run an instance of
the default ingress controller.
This PR adds a Keepalived track_script that should update the priority based on the 
existence of a default ingress pod on the node.
> Bug 1988102: [release-4.7] On-prem: add default ingress track script to Keepalived

- templates/common/on-prem/files/keepalived.yaml
timeoutSeconds defaults to 1 second, but our liveness probe attempts
to wait for 5 seconds. This seems to be causing frequent liveness
probe timeouts in some environments which triggers unnecessary
restarts.
This patch sets timeoutSeconds to 5 to match the expectations of
the probe.
Fixed an issue with the keepalived liveness probe that could cause spurious timeouts.
> Bug 1986757: Set timeoutSeconds for keepalived liveness probe

- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
The bug reported a problem with the 1-to-1 mapping to MCPs and Kubelet Configs. I figured out the `getManageKubeletConfigKey` function did not include a LabelSelector to filter out the KubeletConfig for the Pool, thus including all the KubeletConfigs in the system for the limit validation.
The patch adds a test to validate multiple pools and their 1:1 relationship with KubeletConfigs.
```
Fix KubeletConfig 1-to-1 relationship to Pools.
```
> Bug 1993922: fixes 1 to 1 kubelet config mapping

- pkg/operator/status.go
- pkg/operator/sync.go
The MCO available status should only be set to False when we believe that the operator/operands have problems/aren't working correctly.  An Operator can be degraded (such as in the case of a degraded master pool) but that does not mean that the operator itself is Unavailable and not functioning properly.
We are setting Available = False when we have Degraded = True across the board and by far this is being set when we have a problem with syncRequiredPools. Pool issues do not mean that the operator itself has a problem (if it did it wouldve failed the other syncs first). Instead, let syncAvailable() look at the results of the syncs itself and only set Available = False when the syncing of operands, etc.. fails (which occurs much less often). When those other syncs fail, we have good reason …
> Bug 1955300: tighten operator availability conditions

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
This is a backport of https://github.com/openshift/machine-config-operator/pull/2716
> [release-4.7] Bug 2000501: bump SystemMemoryExceedsReservation alert threshold to 95%

- templates/common/_base/files/configure-ovs-network.yaml
Currently br-ex defaults to the mode stable-privacy because that's
the default for new nmcli connections. However, the host interface
is actually configured for eui64, which causes inconsistency from
initial boot to bridge configuration.
To fix this we can just persist the addr-gen-mode like we do with
the DHCP parameters.
Persist addr-gen-mode for ipv6 connection when creating br-ex.
> Bug 1990625: configure-ovs: Persist addr-gen-mode for ipv6 connections

- templates/common/_base/files/configure-ovs-network.yaml
Warning message sent by `clone_slave_connection` function ends up in a `new_uuid` variable breaking following command:
```bash
Sep 23 20:26:06 master-0-0 configure-ovs.sh[147099]: ++ clone_slave_connection 87546f2c-6f14-37d9-902b-75b2d99f9606
Sep 23 20:26:06 master-0-0 configure-ovs.sh[147099]: ++ local uuid=87546f2c-6f14-37d9-902b-75b2d99f9606
Sep 23 20:26:06 master-0-0 configure-ovs.sh[147099]: ++ local old_name
Sep 23 20:26:06 master-0-0 configure-ovs.sh[147099]: +++ nmcli -g connection.id connection show uuid 87546f2c-6f14-37d9-902b-75b2d99f9606
Sep 23 20:26:06 master-0-0 configure-ovs.sh[147099]: ++ old_name=enp0s4
Sep 23 20:26:06 master-0-0 configure-ovs.sh[147099]: ++ local new_name=enp0s4-slave-ovs-clone
Sep 23 20:26:06 master-0-0 configure-ovs.sh[147099]: ++ nmcli connection show …
```
> Send WARN message to stderr

- templates/common/on-prem/files/coredns-corefile.yaml
KNI CoreDNS does not resolve hostnames if the nameservers in the forwarders provide a DNS reponse > 512 bytes
So name resolution to github.com from application pod fails if the forward section of Corefile had an upstream DNS which provides a DNS response > 512
The response size you get while dig to github.com using upstream namserver 10.11.142.1  is 602 whereas using namserver 10.11.5.19 it is 55
The limit for UDP DNS messages is 512 bytes long. Well behaved DNS servers are supposed to truncate the message and set the truncated bit. See RFC 1035 section 4.2.1.
https://datatracker.ietf.org/doc/html/rfc1035#section-4.2.1
https://datatracker.ietf.org/doc/html/rfc1035#section-2.3.4
The difference in the dig to github.com is the response size. For  10.11.142.1 it is 602 > 512 and for …
> Bug 1991067: [on-prem] Set coredns bufsize to 512

- cmd/machine-config-operator/bootstrap.go
- install/0000_80_machine-config-operator_02_images.configmap.yaml
- install/image-references
- manifests/on-prem/coredns.yaml
- pkg/controller/bootstrap/testdata/bootstrap/machineconfigcontroller-controllerconfig.yaml
- pkg/controller/template/constants.go
- pkg/operator/assets/bindata.go
- pkg/operator/bootstrap.go
- pkg/operator/images.go
- pkg/operator/sync.go
- templates/common/on-prem/files/coredns.yaml
mDNS functionality was removed in 4.8, but we left some of the code
in the interest of not risking issues on upgrade. Now that we're
multiple releases past the initial removal we should be able to get
rid of the last vestiges.
> Remove all references to mdns

- install/0000_80_machine-config-operator_00_namespace.yaml
Starting with OpenShift 4.10 we are introducing PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement).
Currently, all pods are marked as privileged, however, over time we want to enforce at least baseline, admirably restricted as default. In order not to break control plane workloads this allows workloads in `openshift-machine-config-operator` namespace to run privileged pods.
See https://github.com/openshift/enhancements/pull/899 for more details (and excuse the eventual consistency of updates).
/cc @stlaz
> podsecurity: enforce privileged for openshift-machine-config-operator namespace

- templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Fixes: https://github.com/openshift/okd/issues/690
See also: #2778 
OKD e2e
templates: NM prepender: ensure /etc/systemd/resolved.conf.d dir exists
> templates: [on-prem] NM prepender: ensure /etc/systemd/resolved.conf.d dir exists

- templates/common/on-prem/files/keepalived-script-default-ingress.yaml
- templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
- templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
The Keepalived default ingress track script checks if a node running an instance of a default router pod.
We noticed that Keepalived failed to run this script as a command, this PR moves default ingress track script
to a separate file (like chk_ocp_lb and chk_ocp_both).
> Bug 2003655: [IPI ON-PREM] move Keepalived default ingress script to separate file

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Having this directory by default enables the use of the
oci-seccomp-bpf-hook which in turn enables recording of syscalls either
manually or via e.g. the Security Profiles Operator.
oci-seccomp-bpf-hook is being requested as an extension of RHCOS at the
moment:
https://github.com/openshift/os/pull/596
The easy way is to verify that the file contents contain /usr/share/containers/oci/hooks.d
A more involved way includes actually installing the oci-seccomp-bpf-hook
which is not trivial on RHCOS, but see e.g. https://issues.redhat.com/browse/CMP-927
or ping me for instructions.
(Not sure if this change warrants a changelog entry?)
The CRI-O configuration files enables the use of OCI plugins whose
JSON manifests are …
> templates: Add /usr/share/containers/oci/hooks.d to the "hooks_dir" array of crio.conf

- templates/common/_base/files/configure-ovs-network.yaml
Every now and again NM fails to bring up the phys0 connection.
Try a couple times.
```
configure-ovs.sh[1280]: ++ nmcli -g connection.master connection show uuid 3739be42-f3bc-4ac0-8c69-7a4de7d9e464
configure-ovs.sh[1280]: + '[' c5abc0d7-e93c-4a2d-ac6b-71cb1ead98bf '!=' ens5 ']'
configure-ovs.sh[1280]: + continue
configure-ovs.sh[1280]: + nmcli conn up br-ex
configure-ovs.sh[1280]: Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/5)
configure-ovs.sh[1280]: + nmcli conn up ovs-if-phys0
configure-ovs.sh[1280]: Error: Connection activation failed: A dependency of the connection failed
configure-ovs.sh[1280]: Hint: use 'journalctl -xe NM_CONNECTION=3739be42-f3bc-4ac0-8c69-7a4de7d9e464 + NM_DEVICE=ens5' to get more details. …
```
> Bug 2009404: ovs-configuration: work around NM connection dependency issue

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
instead of relying on the default config.
(a step in fixing https://github.com/cri-o/cri-o/issues/5352)
> Bug 2009785: crio: specifically enable version_file_persist

- templates/common/on-prem/files/coredns.yaml
- templates/common/on-prem/files/keepalived.yaml
- templates/master/00-master/on-prem/files/haproxy.yaml
Kubelet complains about empty files in the manifests directory because
it can't parse them. While this doesn't cause any harm, it has caused
bugs to be mis-routed because people see the error messages while
debugging and think something is wrong.
Instead of conditionalizing the content of the files, we can
conditionalize the path and just write them to a disabled location
so they won't be deployed and they also won't be processed by kubelet.
Note that I tried just using /dev/null to avoid writing the files
entirely, but I was not able to get that to work.
> [release-4.7] Bug 2008692: Don't write empty static pod manifests

- Dockerfile
- OWNERS_ALIASES
- manifests/controllerconfig.crd.yaml
- pkg/controller/template/render.go
- pkg/controller/template/render_test.go
- pkg/controller/template/test_data/controller_config_alibaba.yaml
- pkg/operator/assets/bindata.go
- templates/common/alibabacloud/OWNERS
- templates/common/alibabacloud/files/usr-local-bin-alibaba-kubelet-nodename.yaml
- templates/common/alibabacloud/units/alibaba-kubelet-nodename.service.yaml
This code enables the Alibaba Cloud provider platform on OpenShift.  The Alibaba provider requires that the instances have a specific format in which the [documentation](https://github.com/kubernetes/cloud-provider-alibaba-cloud/blob/master/docs/getting-started.md) states should be in `"${REGION}.${INSTANCE_ID}"`.
This patch follows the pattern for other providers which sets an environment variable named `KUBELET_NODE_NAME` in `/etc/systemd/system/kubelet.service.d/`. The environment variable is set through creating a service that upon start will query the metadata service for the region and the instanceid.
This pull request requires #2772.
I was able to verify that this code works by deploying the following work:
- …
> Enable Alibaba Cloud provider instances with expected ProviderID

- pkg/daemon/constants/constants.go
- pkg/daemon/update.go
- test/e2e/mcd_test.go
Previously updating ssh keys would change their owner and group to root
Closes https://bugzilla.redhat.com/show_bug.cgi?id=1956739
> Bug 1956739: Change owner and group of authorized_keys to core

- templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml
Alibaba Cloud provider requires the `--provider-id` kubelet parameter instead of `--hostname-override`. 
I added custom kubelet.service files for `alibabacloud`.
Install a cluster on Alibaba and verify that the control plane nodes have the proper settings in `/cat /etc/systemd/system/kubelet.service`.
AlibabaCloud provider-id kubelet flag
> Alibaba Cloud Provider: use --provider-id kubelet parameter

- templates/common/_base/files/configure-ovs-network.yaml
Cherry-pick of #2626 & #2643 & #2706 & #2704 & #2512 & #2645 & #2468
> [release-4.7] Bug 1975174: configure-ovs: fix nondeterministic master in slave profiles

- pkg/daemon/update.go
- pkg/daemon/update_test.go
This PR fixes a condition where: 
1.  The mcd backs up a relative/dangling symlink while backing up original files during a configuration rollout 
2.  The next time configuration gets rolled out, the mcd checks to see if it has already backed up the original files 
3.  os.Stat returns an error against the previously backed-up symlink because the symlink's target does not exist
4.  The mcd interprets that error as the file not existing and tries to copy over it, resulting in  "cp: not writing through dangling symlink"
This PR adds a symlink check before the file existence check, to make sure we don't try to back up over the dangling symlink. 
This also adds a unit test for original file backups that tests the symlink case as well as the "normal" case. I broke the backup file paths out into …
> Bug 2020003: Node upgrade stuck due to not writing through dangling symlink '/etc/machine-config-daemon/orig/etc/issue.mcdorig'

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
this workload will be allowed to mount devices (like /dev/fuse) and configure user namespaces
to allow for unprivileged builds
completes https://issues.redhat.com/browse/OCPNODE-683
> crio: add openshift builder workload

- pkg/daemon/update.go
A drain no longer occurs, and another case, kubelet-ca.crt, has been
added
> Update postConfigChangeActionNone comment

- pkg/daemon/update.go
- templates/common/_base/files/sshd-disable-ssh-key-dir.yaml
In older versions of OKD, the SSH keys were written to
`/home/core/.ssh/authorized_keys`. Newer versions of OKD will
expect the keys at `/home/core/.ssh/authorized_keys.d/ignition`.
In the case of a newer version of OKD, the keys file is removed
from the legacy path in the updateSSHKeys function.
It will then be recreated at the new fragment path by the
atomicallyWriteSSHKey function that is called right after.
CI
Support ssh-key-dir on OKD/FCOS
> Support `ssh-key-dir` on OKD/FCOS

- pkg/daemon/drain.go
Before marking cordon/uncordon successful,
also check the node.Spec.Unschedulable has been set
correctly.
Also added additional log while performing cordon/uncordon
This is to help debug bugs such as
https://bugzilla.redhat.com/show_bug.cgi?id=2022387
> Bug 2024108: daemon: make cordon/uncordon more robust

- install/0000_80_machine-config-operator_00_namespace.yaml
- manifests/machineconfigdaemon/clusterrole.yaml
- manifests/machineconfigserver/clusterrole.yaml
- pkg/operator/assets/bindata.go
> Bug 1978581: remove run-level info from operators namespaces

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
This intends to fix https://bugzilla.redhat.com/show_bug.cgi?id=2017756
The way it does is:
- Removing crio options from `/etc/crio/crio.conf.d/00-default` that may overwrite changes in `/etc/containers/storage.conf` introduced by `ContainerRuntimeConfig` custom resources.
- Wiping default `/etc/crio/crio.conf`, as it also includes the offending settings and any other interesting default has already been moved to MCO-managed configuration `/etc/crio/crio.conf.d/00-default`.
> Bug 2017756: Remove crio settings that overwrite /etc/containers/storage.conf

- templates/common/on-prem/files/keepalived-script-default-ingress.yaml
- templates/common/on-prem/files/keepalived.yaml
- templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
- templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Manual cherry-pick:
- https://github.com/openshift/machine-config-operator/pull/2637
- https://github.com/openshift/machine-config-operator/pull/2798
> [release-4.8] Bug 2021073: [ipi onprem] cherry pick Keepalived default ingress scripts fixes

- pkg/daemon/update.go
Ignore ssh keys if core user does not exist, rather than failing and
degrading the node. Degrading is undesirable because ssh keys were
previously written as root, so machine configs with ssh keys could be
applied even if the core user did not exist
> Bug 2023657: Only write ssh keys if core user exists

- templates/common/_base/files/container-storage.yaml
The `storage.conf(5)` `override_kernel_check` option was removed from the
containers/storage library in early 2019:
https://github.com/containers/storage/commit/bd6cac944a0f808561eb3ab41ff0db73fc2596cb
With recent version of CRI-O present in OCP >= 4.9, the presence of
this field causes sandbox creation failure when using user namespaces:
Warning  FailedCreatePodSandBox  SSs (xN over MMm)  kubelet
(combined from similar events): Failed to create pod sandbox: rpc
error: code = Unknown desc = error creating pod sandbox with name
"{NAME}": error creating an ID-mapped copy of layer "{HASH}":
time="{TIMESTAMP}" level=warning msg="Failed to decode the keys
[\"storage.options.override_kernel_check\"] from
\"/etc/containers/storage.conf\"."
Remove the `override_kernel_check` option.
> storage.conf: remove obsolete option override_kernel_check

- pkg/daemon/daemon.go
- pkg/daemon/drain.go
Manual backport of https://github.com/openshift/machine-config-operator/pull/2829
Also, requires https://github.com/openshift/machine-config-operator/pull/2659 to get #2829 work properly
Back-porting https://github.com/openshift/machine-config-operator/pull/2657 as well for completeness in event and logging that we have for node cordon/uncordon
> Bug 2028025: [Release 4.8] daemon: make cordon/uncordon more robust and better logging

- pkg/operator/sync.go
Besides eliminating code duplication, this will allow more easily unit
testing functions that call resourceapply.* functions, which will help
in migrating from using ./lib to library-go
Created a new type manifestPaths to wrap all the arguments needed for
applyManifests
> Consolidate duplicated code into applyManifests

- pkg/daemon/daemon.go
- pkg/daemon/update.go
Before marking cordon/uncordon successful,
also check the node.Spec.Unschedulable has been set
correctly.
Also added additional log while performing cordon/uncordon
This is to help debug bugs such as
https://bugzilla.redhat.com/show_bug.cgi?id=2022387
Manual backport of PRs:
- https://github.com/openshift/machine-config-operator/pull/2829
- https://github.com/openshift/machine-config-operator/pull/2659
- https://github.com/openshift/machine-config-operator/pull/2657
> Bug 2028525: [Release 4.7] daemon: make cordon/uncordon more robust and better logging

- cmd/machine-config-operator/start.go
- manifests/userdata_secret.yaml
- pkg/controller/common/controller_context.go
- pkg/controller/common/helpers.go
- pkg/operator/assets/bindata.go
- pkg/operator/bootstrap.go
- pkg/operator/operator.go
- pkg/operator/render.go
- pkg/operator/sync.go
https://issues.redhat.com/browse/METAL-74
Related issue: #683
Enhancement: https://github.com/openshift/enhancements/blob/master/enhancements/machine-config/user-data-secret-managed.md#machines-user-data-managed-by-the-mco
This change was previously committed in #1792, but reverted again in #2126. With the installer change openshift/installer#4413 in place, [Bug 1881703](https://bugzilla.redhat.com/show_bug.cgi?id=1881703) is now resolved and it is safe to re-add this code.
This is now required for the enhancement https://github.com/openshift/enhancements/blob/master/enhancements/baremetal/coreos-image-in-release.md#implementation-detailsnotesconstraints
> Manage user data

- pkg/daemon/daemon.go
- pkg/daemon/rpm-ostree.go
- pkg/daemon/rpm-ostree_test.go
This is *mainly* to validate that
https://github.com/openshift/release/pull/24225
worked.
But, this code may be useful as a sanity check going forward.
See also https://github.com/coreos/rpm-ostree/pull/3251
(I also may try to expose e.g. `ex-container` as a feature flag
that we can query instead of version-parsing)
> [mcbs] Validate rpm-ostree version is new enough

- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/container-runtime-config/helpers.go
https://github.com/openshift/machine-config-operator/pull/2752 fixed the 1-1 mapping for kubeletconfig,
this PR fix the machineconfig name and pool name 1-1 mapping for containerruntime config.
> Bug 2028731: fixes 1 to 1 containerruntime config mapping

- pkg/constants/constants.go
- pkg/controller/node/node_controller.go
- pkg/controller/node/node_controller_test.go
- pkg/daemon/daemon.go
All the upgrade candidate nodes in a mcp would be applied
`UpdateInProgress: PreferNoSchedule` taint.
The taint will be removed MCD once the upgrade is complete.
Since kubernetes/kubernetes#104251 landed,
the nodes not having PreferNoSchedule taint will have higher score.
Before the upgrade starts, MCC will taint all the nodes in the
cluster that are supposed to be upgraded. Once the upgrade is
complete since MCD will remove the taint, none of the nodes will
have `UpdateInProgress: PreferNoSchedule` taint. This ensures
the score of the nodes will be equal again.
Why is this needed?
This reduces the pod churn when the cluster upgrade is in progress.
When the non-upgraded nodes in the cluster have `UpdateInProgress:
PreferNoSchedule` taint, they would get lesser score and …
> [MCC][MCD]: Introduce in progress taint

- go.mod
- hack/build-go.sh
- pkg/daemon/config_drift_monitor.go
- pkg/daemon/config_drift_monitor_test.go
- pkg/daemon/daemon.go
- pkg/daemon/on_disk_validation.go
- pkg/daemon/update.go
- test/e2e-shared-tests/README.md
- test/e2e-shared-tests/helpers.go
- test/e2e-shared-tests/mcd_config_drift.go
- test/e2e-shared-tests/shared.go
- test/e2e-single-node/sno_mcd_test.go
- test/e2e/mcd_test.go
- test/framework/clientset.go
- test/helpers/utils.go
- vendor/modules.txt
This enables the MCD to check if on-disk configuration has drifted from the currently applied MachineConfig. This work is being tracked in https://issues.redhat.com/browse/MCO-69
I added a goroutine to the MCD to run a Config Drift Monitor. Under the hood, the Config Drift Monitor uses fsnotify to wire up handlers for all of the directories referenced in a given MachineConfig. If a write event is detected for any file (or files relating to a Systemd unit) defined in a MachineConfig, the Config Drift Monitor will run the `validateOnDiskState` function. If the on-disk configuration has drifted from what is specified in the MachineConfig, the node will be marked Degraded. Additionally, I added a `validateOnDiskState` check to the `syncNode` routine so that if the config has …
> Proactively detect config drift

- pkg/controller/node/node_controller_test.go
The event ordering in the controller is not
guaranteed if there are same operations on the
object, sometimes they can be combined, sometimes
they can be ignored. This commit makes the
TestMakeProgress test more robust by using subtest.
Test output:
```go
go test ./pkg/controller/node  -race -run ^\TestShouldMakeProgress\$ -count 100
ok  	github.com/openshift/machine-config-operator/pkg/controller/node	84.172s
```
cc @sinnykumari  @jcaamano
> fix races while syncing node events

- pkg/controller/common/helpers.go
- pkg/controller/common/helpers_test.go
- pkg/daemon/update_test.go
- test/helpers/helpers.go
These functions will be needed by both
https://github.com/openshift/machine-config-operator/pull/2802
and
https://github.com/openshift/machine-config-operator/pull/2851
so adding them here to avoid merge conflicts later
Moved/renamed newFile -> NewIgnFile
> Add helper functions to work with Ignition Configs

- templates/common/_base/files/configure-ovs-network.yaml
Improvements for configure-ovs script
* On error, clean up any configuration to avoid interference. This
configuration will be saved on a temporary directory for
troubleshooting.
* Consolidated logic to rollback any applied configuration, to activate
a connection profile, reload NM, print network state information and
exit handling.
* Avoid using `nmcli device connect` as it will generate a persistent
connection profile if there wasn't any, ipossibly changing the state
the node was initially deployed with.
* Change `configure-ovs` to rebuild the ovs configuration on every boot.
This allows to take in new network configuration that administrator
intends to apply to the cluster on day-2.
> configure-ovs: improvements & reset openvswitch configuration on every boot

- pkg/controller/template/render_test.go
- templates/common/_base/files/configure-ovs-network.yaml
- templates/common/_base/files/mtu-migration-dispatcher.yaml
A new Network Manager dispatcher script, placed in mtu-migration-dispatcher.yaml, responds to UP events on selected host interfaces when an MTU migration is ongoing. It sets appropriate (transient) MTU values for host interfaces and their routes in the first phase of the MTU migration in order to avoid disruption while the cluster MTU is also being modified.
Permanently applying an MTU value to host interfaces is instead under the cluster administrators's responsibility; an option for the cluster admin, for instance, would be to apply a MachineConfig object that adds a custom Network Manager profile to the host.
> mtu-migration-dispatcher script

- pkg/daemon/constants/constants.go
- pkg/daemon/drain.go
- pkg/daemon/drain_test.go
- pkg/daemon/update.go
- pkg/daemon/update_test.go
If a config change does not contain changes to registries.conf, don't
apply checks specific to registries.conf
Also start using helper functions added in
https://github.com/openshift/machine-config-operator/pull/2870
> Don't perform registries.conf checks on GPG change

- pkg/daemon/config_drift_monitor_test.go
- pkg/daemon/on_disk_validation.go
- test/e2e-shared-tests/mcd_config_drift.go
- test/helpers/utils.go
The Config Drift Monitor (https://github.com/openshift/machine-config-operator/pull/2795) was previously unaware of compressed files. What would happen is the MCD would unzip a compressed file payload and write that to disk. However, the Config Drift Monitor was unaware that the file was compressed, so it was comparing the compressed contents of the MachineConfig against the uncompressed contents that were written to disk. Because of that, the Config Drift Monitor would erroneously degrade the node / MCP.
Fixes: #2032565
I made the Config Drift Monitor aware of compressed files by replacing the calls to `dataurl.DecodeBytes` with a call to `decodeContents` which is aware of compressed files.
1. On a freshly provisioned test cluster, create a …
> Bug 2032565: makes config drift monitor aware of compressed files

- pkg/operator/sync.go
This PR is to resolve a panic when
`PlatformStatus.VSphere` is nil.
> Bug 2031049: Fix panic when PlatformStatus VSphere is nil

- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
- templates/master/01-master-kubelet/azure/files/kubelet.yaml
- templates/worker/01-worker-kubelet/azure/files/kubelet.yaml
* Removes the restriction of setting the runtimeRequestTimeout within the kubelet config.
* Adds an azure specific config to bump the runtimeRequestTimeout to 4m
> Bug 2033729: Remove runtime request timeout restriction and add azure config

- pkg/controller/bootstrap/bootstrap.go
- pkg/controller/bootstrap/bootstrap_test.go
- pkg/controller/container-runtime-config/container_runtime_config_bootstrap.go
- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- test/e2e-bootstrap/bootstrap_test.go
This PR adds container runtime support at bootstrap.
```yaml
kind: ContainerRuntimeConfig
metadata:
name: cr-pid-limit
spec:
matchLabels:
pools.operator.machineconfiguration.openshift.io/master: ''
containerRuntimeConfig:
pidsLimit: 100000
```
Create the manifest at bootstrap time (0000-openshift-container-runtime.yaml). 
``` Adds Container Runtime support at bootstrap```
> [OCPNODE-674] Add container runtime at bootstrap

- docs/MachineConfigDaemon.md
GPG keys were added to the list of reboot exceptions, and inaccurate
documentation was updated. Selected registries.conf changes were
previously listed under the "None" action, but registries.conf changes
always trigger the "Reload Crio" action. Some organizational and wording
changes were made to make this more clear
Depends https://github.com/openshift/machine-config-operator/pull/2851
> Update reboot exception documentation and add GPG

- templates/common/_base/files/configure-ovs-network.yaml
The /etc/NetworkManager/systemConnectionsMerged directory has been removed, but this script still references the directory which is problematic in case of an OCP upgrade from 4.9 -> 4.10 as the directory exists with no contents and the script fails to execute on an upgrade.
> Bug 2036577: configure-ovs: do not use overlay directory when checking and copying connections

- templates/common/openstack/units/afterburn-hostname.service.yaml
With this change, the afterburn-hostname service uses the 'openstack'
provider, which fetches userdata from the config drive, and only uses
the Nova metadata service as a fallback. This is especially useful in
network topologies where Nova-metadata is not guaranteed to be reachable
(e.g. when using baremetal (Ironic) instances).
> Bug 2033953: Afterburn to try config-drive before Nova metadata

- pkg/daemon/daemon.go
- pkg/daemon/daemon_test.go
- pkg/daemon/update.go
- pkg/daemon/update_test.go
I'm going to have to do some refactoring of OS update code for https://issues.redhat.com/browse/MCO-126, which is to use the new format for OS images. Currently there are 3 separate code paths that perform OS updates (`applyOSChanges()`, `checkStateOnFirstRun()`, and pivot.go), and it will likely make sense to refactor those code paths so that I don't have to make additions for the new format in all three places. While reading over what we have currently, I ran into a few things that make it hard to understand the differences between what's going on in `applyOSChanges()` and `checkStateOnFirstRun()`, so I cleaned those up anticipating that it will make later refactoring easier.
I kept things separate into 4 commits (and I'm not completely sure the last one is good style), so if any of it …
> daemon.go/update.go: various cleanup surrounding OS updates

- templates/common/_base/files/configure-ovs-network.yaml
Setting the default NM route metric for ovs-if-br-ex is problematic
in the presence of other Ethernet ports. In that case, ovs-if-br-ex
as well as the Ethernet ports will have the same route metric, and
the winner is undefined. Lower ovs-if-br-ex route metric to 49 to
avoid ambiguous situations.
Cause: 
When more than one ethernet interface has the default route on startup, then NMs default behavior will assign metrics 100, 101, 102.. 
and so forth to the Ethernet interfaces to avoid ambiguity. NM will make sure that interfaces of the same type will not
have the same metric: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/managing-the-default-gateway-setting_ …
> Bug 2035326: ovs-configuration - use lower than NM default ethernet route metric

- templates/common/_base/files/configure-ovs-network.yaml
Take additional precautionary measures to clean up possible leftovers
from previous runs.
Fixes: #2036113
> Bug 2036113: configure-ovs: cleanup leftovers from previous run

- cmd/apiserver-watcher/README.md
- templates/master/00-master/alibabacloud/files/etc-kubernetes-manifests-apiserver-watcher.yaml
- templates/master/00-master/alibabacloud/files/opt-libexec-openshift-alibabacloud-routes-sh.yaml
- templates/master/00-master/alibabacloud/units/openshift-alibabacloud-routes.path.yaml
- templates/master/00-master/alibabacloud/units/openshift-alibabacloud-routes.service.yaml
In the vein of https://github.com/openshift/machine-config-operator/pull/2011, this PR add an alibabacloud routes script that fixes hairpin.
Background: Alibaba cloud hosts cannot hairpin back to themselves over a load balancer. Thus, we need to redirect traffic to the apiserver vip to ourselves via iptables. However, we should only do this when our local apiserver is running.
The apiserver-watcher drops a $VIP.up and $VIP.down file, accordingly, depending on the state of the apiserver. Then, we add or remove iptables rules that short-circuit the load balancer.
Like Azure, we don't need to do this for external traffic, only local clients.
Install on alibabacloud, ensure connections to the internal API load balancer are reliable - both when the local apiserver process is …
> Bug 2042655: Alibaba hairpin

- pkg/daemon/update.go
Currently the MachineConfig being applied is saved to disk before OS
changes are applied. If the node loses power while OS changes are being
applied, the MCO incorrectly concludes from the config stored on disk
that the update has been applied. Instead, wait until the OS changes
have been made to write the config to disk.
I manually verified that this shouldn't break anything:
getCurrentConfigOnDisk is the only function that accesses the config on
disk, and it is only called in the following code paths:
syncNode->runPreflightConfigDriftCheck
syncNode->startConfigDriftMonitor
performPostConfigChangeAction->startConfigDriftMonitor
checkStateOnFirstRun
syncNode->prepUpdateFromCluster
runOnceFromMachineConfig->prepUpdateFromCluster
None of those functions are called between where the config …
> Bug 1916169: storeCurrentConfigOnDisk after os changes

- templates/common/_base/files/NetworkManager-keyfiles.yaml
This commit explicitly sets NetworkManager to look for its keyfiles in
the default directory (`/etc/NetworkManager/system-connections`) instead
of relying on the defaults.
This change is driven by the bug introduced by the Assisted Installer in
pre-4.10 installations using IPv6 where the NM configuration has been
changed to use `/etc/NetworkManager/system-connections-merged` without
ensuring that the directory exists and contains a correct configuration.
The issue has been exposed by openshift#2742 when removal of the
`99-keyfiles.conf` made the file created by the AI the one taking
precedence. Back then the solution implemented in the AI was a
workaround for another issue which since 4.7+ is no longer present.
As a consequence, any OCP cluster installed initially by the Assisted …
> Bug 2041889: Explicitly configure NetworkManager keyfile

- templates/common/_base/files/configure-ovs-network.yaml
Setting the default NM route metric for ovs-if-br-ex is problematic
in the presence of other Ethernet ports. In that case, ovs-if-br-ex
as well as the Ethernet ports will have the same route metric, and
the winner is undefined. Lower ovs-if-br-ex route metric to 49 to
avoid ambiguous situations.
Conflicts:
templates/common/_base/files/configure-ovs-network.yaml
(cherry picked from commit e6a673db9a2931906cf00832684f5d132ca333ee)
- What I did
Cause:
When more than one ethernet interface has the default route on startup, then NMs default behavior will assign metrics 100, 101, 102..
and so forth to the Ethernet interfaces to avoid ambiguity. NM will make sure that interfaces of the same type will not
have the same metric: …
> [release-4.9] Bug 2044503: ovs-configuration: use lower than NM default ethernet route metric

- templates/common/_base/files/configure-ovs-network.yaml
When activating the br-ex connection, NM would return success if only
one of the address families got an IP. We should wait for both families
in the case of dualstack.
> Bug 2040671: Configure-ovs: Ensure DHCP finishes for both address families

- pkg/operator/operator.go
Currently we're getting the error:
Error creating event &Event...
Event ".16c2ed25cd8773b4" is invalid: involvedObject.namespace: Invalid value: "": does not match event.namespace
Related to Bug 2034364, overlooked in
https://github.com/openshift/machine-config-operator/pull/2833
Replaces https://github.com/openshift/machine-config-operator/pull/2891
> Bug 2045866: Set proper InvolvedObject when using library-go EventRecorder

- templates/common/_base/units/machine-config-daemon-pull.service.yaml
Recent podman in F35 is hanging during `cat`. Not sure why, but since its not being regularly tested, we should fall back to `cp` and `chcon` instead.
This doesn't affect OCP (at least yet), but critical for OKD, see https://github.com/openshift/installer/pull/5567
> Bug 2044808: mcd pull service: use `cp` instead of `cat` to copy MCD on host

- templates/common/_base/units/machine-config-daemon-pull.service.yaml
I'm opening this draft PR to open a forum for MCO and OKD maintainers to discuss how the OKD-specific changes to the MCO code base can be merged back into master. This would allow for dropping the fork and lighten the OKD maintenance burden.
I'd like to ask @fortinj66 and @vrutkovs to expand on the reasoning behind those individual changes, and provide links to associated issue/bug reports (if any). I am open to opening more fine-grained PRs against master for each issue addressed with these changes.
My hopes are this will make it easier for @openshift/openshift-team-mco to review the changes.
> Merge OKD-specific changes into master

- docs/MachineConfigDaemon.md
- docs/SingleNodeOpenShift.md
Catching up with the header change from 86aadca173 (#2855).
> docs: Update links from "Optimized Updates" to "Rebootless Updates"

- OWNERS_ALIASES
He's been working on metal IPI for a while now so he should be in the
list. I also removed Yossi from the reviewer list since he recently
moved to a different team. I'm leaving him as an approver for now
since we might still want to pull him in on patches. We just don't
want to pester him with automatic review requests.
> Add Christoph as a baremetal owner

- templates/common/_base/files/configure-ovs-network.yaml
For some reason the nmcli call to determine the number of ipv6
addresses on an interface is sometimes returning a blank line as
part of the output. This causes a single address to look like 2
because we're just checking the line count and makes us incorrectly
set "ipv6.may-fail no" on the interface. This causes the connection
to fail and prevents ovs-configuration from completing.
Here's some example output from an affected system:
[root@master-0-0 core]# nmcli -m multiline --get-values ip6.address conn show 84a523ff-ee8a-4a29-94ca-47590eb0cb76
IP6.ADDRESS[1]:fe80::5054:ff:fe6e:6923/64
[root@master-0-0 core]#
Additionally, we have seen another case where the link-local address
from both the baremetal and provisioning networks shows up in the
output of this command. That will also fail …
> Bug 2047445: Use ip command to check for ipv6 addresses

- templates/common/_base/files/sysctl-inotify.conf.yaml
Removed `sysctl-inotify.conf.yaml`
Install a functional OCP cluster.
Sysctls (and other node-level tuning) on OpenShift clusters is handled
by the Node Tuning Operator (NTO).  Changing sysctls via NTO has the
added benefit of not needing to reboot the node and settings rollback.
Both the OS-level (e.g. RHEL) and containerized TuneD shipped by NTO
does not override sysctls set via /etc/sysctl{.conf,.d}.  Cluster
administrators trying to change sysctls already set in
/etc/sysctl{.conf,.d} are easily confused why are their settings not
applied by NTO.
I believe only system-critical sysctls for enabling OpenShift
functionality should be managed by MCO.  NTO delivers both
fs.inotify.max_user_watches = 65536 …
> Remove sysctl-inotify.conf.yaml

- templates/common/_base/files/sysctl-inotify.conf.yaml
Reverts openshift/machine-config-operator#2909
This is leading to open file exhaustion, with messages like `too many open files` sinking [dev-branch update CI][1]:
I'm not entirely clear why update jobs appear particularly vulnerable.  Hunting for a bracket, I focused just on [`master` origin update presubmits][2], to exclude confounders like differences in job definition between different repositories:
The success on the extreme left is [this run][3].  The first failure with this mode is [this run][4].  Diffing the two payloads to find suspects:
```console
$ REF_A=https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/26806/pull-ci-openshift-origin-master-e2e-gcp-upgrade/1489144429657722880/artifacts/release/artifacts/release-payload-latest/image-references
$ …
```
> Revert "Remove sysctl-inotify.conf.yaml"

- templates/master/01-master-container-runtime/_base/files/crio.yaml
- templates/worker/01-worker-container-runtime/_base/files/crio.yaml
**- What I did** Changed metrics that are enabled by default for CRI-O set by default worker and master machine config templates
* metrics that have high cardinality labels are disabled as previous
* metrics that do not follow prometheus naming best practices are enabled for now but in deprecated stage and will be removed in a future release
* enabled metrics that CRI-O provide and which are not marked as deprecated
* `"operations_total", "operations_latency_seconds_total", "operations_latency_seconds", "operations_errors_total", "image_pulls_layer_size", "image_pulls_bytes_total", "image_pulls_skipped_bytes_total", "image_pulls_success_total", "image_pulls_failure_total", "image_layer_reuse_total", "containers_oom_total", "containers_oom_count_total", "processes_defunct"`
**- How to …
> templates: Change default container-runtime config to enable all CRI-O metrics

- docs/MachineConfigDaemon.md
Adds docs for the config drift detection mechanism introduced by https://github.com/openshift/machine-config-operator/pull/2795
Adds docs for config drift detection
> updates docs for config drift detection

- templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
If resolv.conf gets populated after NetworkManager has attempted to
do a reverse lookup on the node IP to get the hostname, we can end
up with a hostname of localhost because the lookup has no DNS servers
to use. To avoid this possibility, reload NetworkManager after we
populate resolv.conf, which should force it to redo the lookup.
Reload NetworkManager after populating resolv.conf to ensure we correctly populate the node hostname.
> Bug 1929160: Add NetworkManager reload to resolv-prepender

- templates/common/openstack/files/usr-local-bin-openstack-afterburn-hostname.yaml
- templates/common/openstack/units/afterburn-hostname.service.yaml
afterburn-hostname was setting the static hostname but not the transient
hostname. This was causing a 5 minute timeout on first boot while
node-valid-hostname waited for hostname to be changed to something other
than localhost.
> OpenStack: set transient hostname in afterburn-hostname

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2028854
**- What I did** Backport the updated prometheus rule for SystemMemoryExceedsReservation alert. The updated rule does not take hugepages into account. More context at https://bugzilla.redhat.com/show_bug.cgi?id=1979297 or openshift/machine-config-operator#2661
> [release-4.8] Bug 2028854: Backport of SystemMemoryExceedsReservation alert rule

- go.mod
- go.sum
- pkg/controller/container-runtime-config/helpers.go
- pkg/controller/container-runtime-config/helpers_test.go
- vendor/github.com/openshift/runtime-utils/pkg/registries/registries.go
- vendor/modules.txt
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=2050466
- vendor in https://github.com/openshift/runtime-utils/pull/14
- Add validation for image and icsp CR to not allow the empty string ("") in the CRD.
Empty string regsitries configurations will fail the machine config daemon operations
of pulling images and the nodes will stopped in NotReady state when node rebooting after node drain.
```
2022-02-03T23:16:02.952318066Z I0203 23:16:02.952259    2590 run.go:18] Running: podman pull -q --authfile /var/lib/kubelet/config.json quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6d4ff6bb5494c55c24f9a322b1a5faffb8a92ea0f572f1078db55f3f1abaa588
2022-02-03T23:16:03.033231339Z Error: error loading registries configuration "/etc/containers/registries.conf": invalid condition: mirror location …
```
> Bug 2050466: Not allow empty string in icsp&image CR

- templates/common/_base/files/ofport-request.yaml
When NetworkManager is restarted, all interfaces are removed from the
external bridge (br-ex / breth0). By default, ports' OVS IDs
change and the existing flows point to wrong 'output:' port numbers
leading to packet drops of all traffic that originates at
LOCAL and the node will not be able to request an IP address via DHCP.
Request fixed ofport numbers via the ofport_request field.
> Bug 2048352: ovn-kubernetes: Fixed ofport_request for physical ports

- templates/common/_base/files/configure-ovs-network.yaml
Setting the default NM route metric for ovs-if-br-ex is problematic
in the presence of other Ethernet ports. In that case, ovs-if-br-ex
as well as the Ethernet ports will have the same route metric, and
the winner is undefined. Lower ovs-if-br-ex route metric to 49 to
avoid ambiguous situations.
Conflicts:
templates/common/_base/files/configure-ovs-network.yaml
(cherry picked from commit e6a673db9a2931906cf00832684f5d132ca333ee)
(cherry picked from commit 3711b7ceac0d1e92f0496ea78bd9305d499fe35b)
> [release-4.8] Bug 2059330: ovs-configuration: use lower than NM default ethernet route metric

- docs/MachineConfiguration.md
- pkg/daemon/update.go
- test/e2e-single-node/sno_mcd_test.go
- test/e2e/mcd_test.go
Added support for new RHCOS extension called `kerberos`. See https://github.com/openshift/os/pull/731.  It will allow users to kerberize their NFS mounts.
Create a MachineConfig with `kerberos` extension as described in https://github.com/openshift/machine-config-operator/blob/master/docs/MachineConfiguration.md#rhcos-extensions and apply it to a cluster either day 0 or day 1.
Add support for a new RHCOS extension called "kerberos".
> Add new extension for kerberos

- templates/common/aws/files/usr-local-bin-aws-kubelet-nodename.yaml
- templates/common/aws/units/aws-kubelet-nodename.service.yaml
In order to support IMDSv2 on AWS platform curling metadata server is not enough.
Here is an attempt to use afterburn for obtaining information from IMDS
Tested manually with custom built release - works well, migration to techpreview also works
IMDSv2 doc: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
> [OCPCLOUD-1436] Use afterburn to collect instance metadata in order to populate nodename

- Makefile
- test/e2e-layering/README.md
- test/e2e-layering/layering_test.go
I've added an empty e2e-layering test package which is intended to house future tests related to the OpenShift CoreOS Layering effort as well as an additional Makefile target.
1. Clone this PR.
2. `$ make test-e2e-layering`
Enables e2e layering tests
> adds e2e-layering test package

- templates/common/_base/files/NetworkManager-keyfiles.yaml
This was originally set as such in 4.9. But it was removed what it seems inadvertently in 4.10 at the same time systemConnectionsMerged overlay was removed. We still want keyfile to be the default plugin, which it already is for RHCOS but not for RHEL. Set it back.
> Bug 2060133: Explicitly set keyfile as the default plugin

- cmd/machine-config-controller/main.go
Before this commit, the `--templates` flag to `machine-config-controller` was
associated only with the `start` subcommand even though the `bootstrap`
subcommand also uses the value. As a result, users could not override the
default `--templates` value when using the `bootstrap` command.
This commit associates the persistent flag with the root command so that both
the `start` and `bootstrap` subcommands expose the `--templates` flag to users.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2062007
Add `--templates` flag to the `machine-config-controller bootstrap` command
> Add `--templates` flag to MCC `bootstrap` command

- templates/common/_base/files/configure-ovs-network.yaml
Makes configure-ovs reload NM only when it has actually made any
configuration change.
> configure-ovs: reload NM only when necessary

- install/0000_80_machine-config-operator_05_osimageurl.yaml
- install/image-references
- manifests/controllerconfig.crd.yaml
- pkg/apis/machineconfiguration.openshift.io/v1/types.go
- pkg/controller/render/render_controller.go
- pkg/operator/bootstrap.go
- pkg/operator/images.go
- pkg/operator/sync.go
Part of https://github.com/openshift/enhancements/pull/1032
We'll add the new-format image into the payload alongside the old
one until we can complete the transition.
(There may actually be a separate `rhel-coreos-extensions` image
e.g. too, so this is just the start)
> Add `rhel-coreos` image in configmap and `oscontainer` in controllerconfig

- pkg/daemon/coreos.go
- pkg/daemon/daemon.go
daemon: Log data from `/sysroot/.coreos-aleph-version.json`
My immediate motivation is to gather more information in the MCD
logs; same reason we log the boots.  For coreos layering work,
we will be sensitive to the initial bootimage more and may need
to update it.
Another angle for this is that we could actually plumb this information
up into the node object, and from there into the operator/controller
and feed it into prometheus and into telemetry, so we start
to gather information on e.g. how many clusters have old bootimages.
---
daemon: Also log Ignition provisioning information
More data is good here; this builds on the previous information
for the bootimage generation time.
---
> daemon: bootimage and ignition logging

- cmd/machine-config-daemon/start.go
In ovnkube based cluster, the connectivity between MCD pods and
kube-api-server relies on the openflow rules injected by ovnkube.
If due to some reason, the ovnkube-node pod cannot start after
the reboot of applying new MC. The MCD will not be able to reach
the api-server.
This PR lets the kubeclient in MCD use the kube-api-server url of
the node kubeconfig file instead. It eliminates the dependency
on ovnkube-node pod from MCD.
> daemon: get the apiserver url from the kubelet's kubeconfig

- pkg/operator/bootstrap.go
Before this commit, the MCO template rendering code created a template output
parent directory with mode `0655`, which caused subsequent subdirectory creation
and file writes to fail when running MCO in some unprivileged contexts that rely
on linux file permissions (as both `wx` are required for owner writes).
This commit adjusts the directory mode to `0755` on creation to ensure
compatibility in those unprivileged contexts.
While integrating with HyperShift which executes MCO binaries in unprivileged containers, I discovered the MCO template execution is creating a parent output directory with mode 0655, which causes rendering to fail because subdirectories and files can't be created within that parent due to the missing executable bit for the owner.
Run `machine-config-operator …
> Bug 2063324: Ensure directories are created with usable permission bits

- templates/common/_base/files/etc-mco-proxy.yaml
- templates/common/_base/files/etc-systemd-system.conf.d-10-default-env-godebug.conf.yaml
- templates/common/_base/files/vsphere-disable-vmxnet3v4-features.yaml
The `filesystem: "root"` kv pair is a remnant of the past from when
the template format was based on the Container Linux Config spec.
Nowadays, it's based on the Butane config spec (formerly known as
Fedora CoreOS Config) where this property node does not exist, and is
thus ignored when transpiling templates to Ignition config.
> templates: Clean out filesystem properties

- pkg/server/api_test.go
Right now Fedora doesn't ship Go 1.17, only Go 1.18beta.  That
version emits a different error message for incompatible TLS
versions.  Adjust our unit test to handle both.
(Also, a motivation for me is to cross-check the new CI configuration
after https://github.com/openshift/release/pull/27015 )
> server/api_test: Adjust expected error message for Go 1.18

- cmd/machine-config-controller/start.go
- install/0000_80_machine-config-operator_00_service.yaml
- install/0000_90_machine-config-operator_00_servicemonitor.yaml
- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
- manifests/machineconfigcontroller/clusterrole.yaml
- manifests/machineconfigcontroller/clusterrolebinding.yaml
- manifests/machineconfigcontroller/deployment.yaml
- pkg/controller/common/helpers.go
- pkg/controller/common/metrics.go
- pkg/controller/node/node_controller.go
- pkg/controller/node/node_controller_test.go
- test/e2e-bootstrap/bootstrap_test.go
- test/e2e/mcc_test.go
- test/helpers/utils.go
- vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go
- vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
- vendor/modules.txt
1. Added metrics reporting to machine-config-controller because it did not previously have that capability by adding:  
- In manifests:
- Cluster Roles
- Cluster Role Bindings
- ServiceMonitor for metrics
- Service for metrics
- oauth-proxy container for machine-config-controller deployment
- mcc-proxy-tls secret for machine-config-controller
- In controller:
- metrics handler function in machine-config-controller common
- machine config lister in node_controller and node_controller_test
- References:
- For the handler I cribbed off of: 557303ffd70ba6ccfa834f86ff7d4acd1f97dd17
- And then to add oauth: 3ab692f423cb34d70d7cb4dc808206849362ba05	
2. Added an alert that fires when the kubelect-ca certificate is pending in a paused pool: 
- added a GaugeVec …
> Send alert when MCO can't safely apply updated Kubelet CA on nodes in paused pool

- templates/common/_base/files/NetworkManager-keyfiles.yaml
(cherry picked from commit 342f20bf2e6efe43e2735d426aae2d49674df3fb)
> [release-4.10] Bug 2060954: Explicitly set keyfile as the default plugin

- pkg/daemon/update.go
I originally has this as part of https://github.com/openshift/machine-config-operator/pull/3020 but it got lost since my PR merged before @jkyros's
> Use MCONamespace constant in getPullSecret()

- pkg/daemon/kernelargs.go
- pkg/daemon/update.go
This will keep layered and non-layered update logging consistent
> Move log statement to UpdateTuningArgs

- test/e2e-bootstrap/bootstrap_test.go
I came across these when working on https://github.com/openshift/machine-config-operator/pull/3020, and rather than replacing componentNamespace with the new constant, it looks like it's unused and should just be dropped. Couldn't find references to some of the other constants either
> bootstrap_test.go: remove unused constants

- OWNERS_ALIASES
- install/0000_80_machine-config-operator_00_namespace.yaml
- manifests/controllerconfig.crd.yaml
- pkg/controller/template/render.go
- pkg/controller/template/render_test.go
- pkg/controller/template/test_data/controller_config_nutanix.yaml
- pkg/operator/bootstrap.go
- pkg/operator/render.go
- pkg/operator/status.go
Update controllerconfig CRD and relevant switch statements
in pkg to handle Nutanix platform.
> Add Nutanix Platform to Machine Config Operator

- install/0000_80_machine-config-operator_01_machineconfig.crd.yaml
Fix a typo in the description of osImageURL field of CRD
> Fix description typo in osImageURL CRD parameter

- Makefile
Today, typing `make` does nothing, which is not very useful.  By listing this rule first,
`make` will default to `make binaries`.
> build-sys: Default to `make binaries`

- templates/common/_base/files/configure-ovs-network.yaml
As we now tear down and reconfigure br-ex on every reboot, we must
provide a means to stabilize interface selection in scenarios with
multiple default route interfaces.
> Bug 2057160: configure-ovs.sh: Provide store hint for default route interface

- manifests/machineconfigcontroller/clusterrole.yaml
- manifests/machineconfigcontroller/clusterrolebinding.yaml
- manifests/machineconfigcontroller/events-clusterrole.yaml
- manifests/machineconfigdaemon/clusterrole.yaml
- manifests/machineconfigdaemon/clusterrolebinding.yaml
- manifests/machineconfigdaemon/events-clusterrole.yaml
- manifests/machineconfigserver/clusterrole.yaml
- manifests/machineconfigserver/clusterrolebinding.yaml
We recently switched some of our calls to use library-go, and around the same time we started filling up events and logs with update notifications for ClusterRoles and ClusterRoleBindings: 
```
42s         42s          1         machine-config-operator.16e0bbc5b7e9ffbb                      Deployment                                                Normal    ClusterRoleUpdated                machine-config-operator                             Updated ClusterRole.rbac.authorization.k8s.io/machine-config-daemon -n openshift-machine-config-operator because it changed
42s         42s          1         machine-config-operator.16e0bbc5baa68337                      Deployment                                                Normal    ClusterRoleBindingUpdated         machine-config-operator …
```
> Bug 2068613: ClusterRoleUpdated/ClusterRoleBindingUpdated Spamming Event Logs

- pkg/daemon/osrelease.go
- pkg/daemon/update.go
- pkg/daemon/update_test.go
Currently, post config change actions are calculated as follows:
1) Reboot if there's a force file
2) Reboot if any MachineConfig fields change except for passwd
3) Calculate an action based on file changes
Layered updates will need to calculate post config change actions solely
based on files, as they will be diffing two images. 1) and 3) can be
consolidated into a single function that is shared between layered and
legacy updates. All MachineConfig changes (2) will result in file
changes on disk, which will cause a reboot if actions are calculated as
normal. This is correct for any change except for changes to passwd,
which currently do not require any post config change action. In order
to preserve this behavior, add a reboot file exception for ssh keys,
which is the only field the MCO …
> update.go: refactor calculatePostConfigChangeAction() 

- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
Remove the restriction on the runtime-request-timeout
option in the kubeletconfig.
Epic for this https://issues.redhat.com/browse/OCPNODE-896
Remove the restriction on the runtime-request-timeout option.
Create a kubletconfig CR and modify the runtime-request-timeout option. Apply the kubeletconfig to the cluster and check the kubeletconfig file on the node to verify that the runtime-request-timeout was set to the value from the CR.
> Remove runtime request timeout restriction

- pkg/daemon/update.go
The call to TempDir a few lines above already created this directory, so
this call to MkdirAll is completely unecessary
> mcd: Remove redundant MkdirAll call in update.go

- templates/common/_base/files/configure-ovs-network.yaml
DHCP and other addressing and routing configuration should be set on ovs-if-br-ex and not in br-ex connection profile.
> Bug 2058030: configure-ovs: move dhcp config from br-ex to ovs-if-br-ex

- templates/common/_base/units/nodeip-configuration.service.yaml
When we added the nodeip-configuration service for None platform
deployments, we broke some existing users who were relying on the
(largely undefined) previous behavior Kubelet used to select its
node ip. While it is possible to work around this by overriding the
node ip selection logic, that's very cumbersome and not an acceptable
user experience.
This change adds a KUBELET_NODEIP_HINT env variable that can be used
to override the default behavior of runtimecfg when selecting a node
ip. When the variable is unset, the old behavior of selecting an
address on the interface of the default route will take effect. When
the variable is set, its value will be passed to runtimecfg like a
VIP for the IPI platforms. This will cause runtimecfg to prefer an
address in the same subnet as the one …
> Bug 1949827: Add KUBELET_NODEIP_HINT to nodeip-configuration

- pkg/daemon/drain.go
- pkg/daemon/drain_test.go
- pkg/daemon/update.go
Various refactors that will be helpful for sharing functionality between a legacy and layering update flow. Opening this against `master` per discussion in https://github.com/openshift/machine-config-operator/pull/2982#issuecomment-1059193703. I would like to get a CI run because I'm having trouble launching a cluster with code we're trying to get into `layering`
> Factor out functionality from update() that will be needed for layering

- pkg/daemon/update.go
- pkg/daemon/update_test.go
This is a refactor to allow reusing updateKernelArgs() for layering. It
is a minor improvement for master since it better protects
MachineConfigs from unintended modification by updateKernelArgs(), and
it simplifies test code which doesn't have to create dummy
MachineConfigs
> updateKernelArgs: pass kargs instead of MCs

- templates/common/_base/files/configure-ovs-network.yaml
`nm-online -s` does not wait for autoconnect profiles to be active if
NM is restarted with networking off. The fact that it does most of the
time is just a race condition.
Set networking on before restarting NetworkManager.
Additionally, try not to re-activate connections more than necessary.
> Bug 2055433: configure-ovs: set networking on before restarting NetworkManager

- pkg/controller/template/render.go
- pkg/controller/template/render_test.go
Nutanix `cloudProvider` field needs to be rendered as blank.
> Render Nutanix cloud provider as blank.

- templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
- templates/master/00-master/on-prem/files/haproxy.yaml
Per [0], the range 30000-32767 is used for kubernetes node ports.
We should not have haproxy listening in that range to avoid possible
conflicts.
0: https://github.com/openshift/openshift-docs/blob/main/modules/installation-network-user-infra.adoc
Move the haproxy listening port out of the kubernetes node port range to avoid conflicts.
> Bug 2069740: Avoid kubernetes node port range

- docs/DemoLayering.md
- hack/layering/file.yaml
- hack/layering/layered-pool.yaml
- hack/layering/live-apply.yaml
- pkg/controller/render/render_controller.go
- pkg/daemon/daemon.go
- pkg/daemon/rpm-ostree.go
- pkg/daemon/rpm-ostree_test.go
- pkg/daemon/update.go
- pkg/daemon/writer.go
Still rebasing changes to `experimentalUpdateLayeredConfig` that will use these changes. Should I lump it all into one PR or keep this as a separate prep PR?
> Integrate functionality from update into layered update

- pkg/controller/render/render_controller.go
Something changed in openshift last week to where after about 20 minutes or so of the cluster being up, requests to/for images start getting forwarded directly to the cloud storage endpoint (signed by aws/google/whoever) intead of being proxied by the cluster (endpoint signed by our cluster signer). 
This should have been fine, and probably was fine everywhere else, except for our hacky scratch image push, where we weren't loading the `SystemCertPool`, which meant  we couldn't verify those cloud provider certificates. 
We only loaded one of our cluster signer certificates because we didn't know we would ever be talking to the clouds directly (and, well, we weren't until other non-MCO changes last week). 
This loads the `SystemCertPool` so we can verify those cloud certificates instead of …
> Load system cert pool for image push to accommodate direct cloud storage access

- docs/HACKING.md
- hack/get-mcd-nodes.py
- hack/lib
- hack/prep-cluster-for-mcd-push.sh
- hack/push-to-mcd-pods.sh
These are some small hack scripts I wrote to make it quicker to work on the MCD between build / run / test cycles.
1. Provision an OpenShift cluster.
2. Store your kubeconfig in a file.
3. `export KUBECONFIG=/path/to/kubeconfig`.
4. Run `$ ./hack/prep-cluster-for-mcd-push.sh`.
5. Make a change to the MCD.
6. Run `$ ./hack/push-to-mcd-pods.sh`.
MCO developer tool enhancements
> adds zacks hack scripts

- cmd/machine-config-controller/main.go
- cmd/machine-config-controller/start.go
- pkg/controller/bootstrap/bootstrap.go
- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/container-runtime-config/helpers.go
Epic: https://issues.redhat.com/browse/OCPNODE-887
issue: https://issues.redhat.com/browse/OCPNODE-869
Create a MCO drop-in to explicitly set `seccomp_use_default_when_empty = false` in 4.10.z
crio will change the default value of `seccomp_use_default_when_empty` from false to true in 4.11(crio1.24) and later versions.  In order to not break current clusters, in 4.10.z we create a machine-config to have drop-in crio.conf file with `seccomp_use_default_when_empty = false` and make it a mandatory upgrade edge(OTA team). So `seccomp_use_default_when_empty = true` change be an opt-in for upgraded users, users will have the option to delete the MC associated with this file when they are ready to
consume this change for their workload
1. Fresh cluster …
> Bug 2072621: [OCPNODE-869] Create a drop-in file for cri-o's seccomp use default config

- pkg/daemon/daemon.go
I've spent some time thinking about how to refactor CoreOSDaemon and
want to leave some explanation for why it's been left the way it is
Maybe there's actually a good solution that I'm missing though - any ideas?
> daemon: add a comment explaining CoreOSDaemon

- cmd/machine-config-daemon/start.go
- pkg/daemon/constants/constants.go
- pkg/daemon/daemon.go
- pkg/daemon/update.go
Add new flag to indicate an update that looks for a desired config
in a ConfigMap, which will be used exclusively for Hypershift
hosted cluster nodes that do not have MachineConfig API.
This mode initializes a simplified daemon that watches for various
state changes, including requests to drain which the Hypershift
nodepool controller will perform instead. This pod should be
ephemeral and only created when an update is required.
There are some duplicated code, which was done to ensure the regular
in-cluster daemonset variant is not affected.
TODOs:
1. switch to using kubelet kubeconfig (can be done on the controller
side by setting startOpts.kubeconfig + adding the necessary
ConfigMap to the pod volumes)
2. add disruptionless update logic
3. move to using the same current/desiredconfig …
> daemon: add desiredConfigMap mode for Hypershift

- pkg/controller/render/render_controller.go
xref https://github.com/coreos/coreos-layering-examples/pull/10/files#diff-cd7826bbd09913ac02ac88625deb775fa25e3feeee90522f12601665e2a59031R9
Basically we're not certain on the CoreOS side where/how to ship
this actually, so just hack it in here for now.
> render: Hack in symlink for `ignition-apply`

- pkg/daemon/update_test.go
This has been creating yellow warning dots in my editor but until now I've been too lazy to fix it. Wonder why this isn't caught by verify :thinking: 
These types are already declared by the containing arrays
> [low priority] update_test: remove redundant types

- pkg/controller/node/node_controller.go
- pkg/controller/node/node_controller_test.go
Users with HA clusters tend to schedule pods across multiple zones
to minimize chances of disruption. To avoid picking all nodes (across multiple zones)
running the same types of pods resulting in an outage, upgrade nodes in
topology.kubernetes.io/zone order and then by node age (oldest first).
If zones are not present (for ex: baremetal deployments) upgrade nodes by age oldest first.
> mcc/node controller: order node updates by zone

- pkg/controller/kubelet-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_bootstrap.go
- pkg/controller/kubelet-config/kubelet_config_controller.go
I was debugging https://bugzilla.redhat.com/show_bug.cgi?id=2070285 and reading through some kubelet controller code, and I figured I'd use the compiler to check my understanding of what's going on and make this change
Looks like a282006d2d3b245c2f5cdf444a4dea45d1b27585 factored out code
into generateKubeletIgnFiles and should have moved
userDefinedSystemReserved as well, but it got missed.
No caller of generateKubeletIgnFiles puts anything in
userDefinedSystemReserved, so it can be dropped as a parameter. Although
the capacity of the map is set by callers, only the length of the map is
checked in generateKubeletIgnFiles
@QiWang19 is there any reason you didn't move it?
> [low priority] kubelet controller: rm unused userDefinedSystemReserved

- pkg/controller/node/node_controller.go
- pkg/controller/node/node_controller_test.go
- pkg/daemon/daemon.go
Move removeUpdateInProgressTaint functionality to mcc so that MCD is relieved of this job. The unit tests are updated as well. This was introduced in https://github.com/openshift/machine-config-operator/pull/2686
> Bug 2035005: Move removeUpdateInProgressTaint functionality to mcc

- pkg/controller/render/render_controller.go
Right now all the image builds fail because of ignition-apply errors during the docker build. 
https://github.com/openshift/machine-config-operator/pull/3087 would have worked, but the ignition binary I packed in my hacky image was older and seemed to care less. The newest ignition-apply is picky about passwd sections (I noticed this for the buildcontroller code and then promptly forgot to mention it). 
```
[2/2] STEP 5/13: RUN exec -a ignition-apply /usr/lib/dracut/modules.d/30ignition/ignition /etc/machine-config-ignition.json
INFO     : Ignition 2.13.0
CRITICAL : failed to apply: running stage 'files': cannot apply passwd live
```
This just makes it skip past the parts it can't implement and continue so builds will work again, and we can talk about the ramifications (if any) later.
> [ layering ] Fix ignition-apply args in dockerfile

- cmd/machine-config-daemon/firstboot_complete_machineconfig.go
Kubernetes is all about eventual consistency, control loops.  On the
daemonset side, we will keep retrying, but not on firstboot.
This exposes us to flakes where e.g. a hypervisor is heavily loaded
on firstboot, or network issues etc.
Let's just retry forever.
> Bug 2073021: firstboot: Retry on failure

- templates/master/01-master-kubelet/_base/files/kubelet.yaml
- templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
there is an effort in CRI-O to deprecate config values that are duplicated with ones in the kubelet (see https://issues.redhat.com/browse/OCPNODE-878)
To begin this process, we intend on setting the default in cri-o to unlimited. Before doing so, there should be a kubelet config in place to replace it.
Set kubelet's config field `podPidsLimit` by default so the CRI-O version of the field can be deprecated.
> Kubelet: apply default podPidsLimit

- manifests/on-prem/coredns-corefile.tmpl
- templates/common/on-prem/files/coredns-corefile.yaml
Closes: #2066605
Make coredns template block more strict to match only exact "api.\<basedomain\>" and resolve the API address.
Resolve a host matching ".*api.\<basedomain\>" from inside a pod. Only an exact match should resolve the API address.
e.g.:
`nslookup api.mycluster.tld` should resolve the API address
`nslookup myapi.mycluster.tld` should be resolved upstream
make Corefile api matching stricter
> Bug 2066605: [on-prem] make Corefile api matching stricter

- templates/common/_base/files/configure-ovs-network.yaml
When converting a static interface to br-ex, we must set the correct
metric as well.
> Bug 2076975: OVN Kubernetes configure-ovs-network set static if conversion metric 

- pkg/controller/kubelet-config/kubelet_config_controller.go
- pkg/controller/kubelet-config/kubelet_config_controller_test.go
Remove `cleanUpDuplicatedMC()` from pkg/controller/kubelet-config/kubelet_config_controller_test.go
`cleanUpDuplicatedMC()` was a symptomatic fix for https://bugzilla.redhat.com/show_bug.cgi?id=1955517.
The root cause is getManagedKubeletConfigKey(). After https://github.com/openshift/machine-config-operator/commit/b0139eaf9c1f2c4c225e6019e0b14e70ea6f199f  and https://github.com/openshift/machine-config-operator/commit/6b5bdaf1f4fae0eee6630dbb6ca3b6c01f287c52
bz 1955517 should be fixed. `cleanUpDuplicatedMC()` is nolonger needed.
I confirmed bz 1955517 is not reproducible without cleanUpDuplicatedMC():
1.Launch a cluster
2.Apply 2 kubeletconfigs: one for master pool, one for worker pool.
3.Upgrade the cluster to a release-payload built from this patch
4.Should not see degraded …
> kcfg controller remove cleanupmc

- pkg/controller/node/node_controller.go
nodecontroller: Log when a node changes pool
A customer is implementing "control upgrade of group of nodes"
by changing pools.  I think zone ordering is the right fix to this,
but let's be verbose and explicit when a node changes pool so it's
easier to debug things.
---
nodecontroller: Add missing format argument
I saw this in logs from a customer:
```
2022-04-11T20:05:02.493178928Z I0411 20:05:02.493135       1 event.go:282] Event(v1.ObjectReference{Kind:"MachineConfigPool", Namespace:"", Name:"x", UID:"0c0508c0-c827-4d46-9b2c-2b7f8f0bcd9a", APIVersion:"machineconfiguration.o
penshift.io/v1", ResourceVersion:"378320503", FieldPath:""}): type: 'Normal' reason: 'SetDesiredConfig' Set target for %!d(string=rendered-x-d78cb2662dd777c789f033d3611e71e8) nodes to config %!s(MISSING)
```
--- …
> nodecontroller: 3 logging patches

- templates/common/_base/files/nm-ignore-sdn.yaml
Causes delays on boot waiting for the patch port to become unmanaged.
> Bug 2072040: Avoid NM managing patch port between br-int and br-ex

- templates/common/_base/files/configure-ovs-network.yaml
Fix a bad cherry-pick done on https://github.com/openshift/machine-config-operator/pull/3065 9f7a7eb96
It failed on RHEL on a manual verification:
```
Apr 06 01:43:55 ip-10-0-49-218.us-east-2.compute.internal configure-ovs.sh[1278]: + remove_all_ovn_bridges
Apr 06 01:43:55 ip-10-0-49-218.us-east-2.compute.internal configure-ovs.sh[1278]: + echo 'Reverting any previous OVS configuration'
Apr 06 01:43:55 ip-10-0-49-218.us-east-2.compute.internal configure-ovs.sh[1278]: Reverting any previous OVS configuration
Apr 06 01:43:55 ip-10-0-49-218.us-east-2.compute.internal configure-ovs.sh[1278]: + remove_ovn_bridges br-ex phys0
Apr 06 01:43:55 ip-10-0-49-218.us-east-2.compute.internal configure-ovs.sh[1278]: + bridge_name=br-ex
Apr 06 01:43:55 ip-10-0-49-218.us-east-2.compute.internal …
```
> [release-4.8] Bug 2062655: Fix bad cherry-pick at 9f7a7eb96

- templates/master/00-master/alibabacloud/files/etc-kubernetes-manifests-apiserver-watcher.yaml
- templates/master/00-master/azure/files/etc-kubernetes-manifests-apiserver-watcher.yaml
- templates/master/00-master/gcp/files/etc-kubernetes-manifests-apiserver-watcher.yaml
An alternative of https://github.com/openshift/machine-config-operator/pull/2674, using `flock`.
wrap `apiserver-watcher` call with `flock`.
> Bug 2078945: Ensure only one apiserver-watcher process is active on a node. 

- pkg/daemon/daemon.go
- pkg/daemon/rpm-ostree.go
- pkg/daemon/rpm-ostree_test.go
Cherry-picked from https://github.com/openshift/machine-config-operator/pull/2677
This is a workaround for https://bugzilla.redhat.com/show_bug.cgi?id=1982389
which is already fixed in rpm-ostree in
https://github.com/coreos/rpm-ostree/pull/2995
because it will take a fair while until we can ship the fixed
rpm-ostreed in RHEL and then OpenShift stable versions.
(Yes, this is a sad recurring pattern)
The updater client gains an explicit `Initialize` method, where
we also explicitly `systemctl start rpm-ostreed` which
then effectively rolls in the change from
https://github.com/coreos/rpm-ostree/pull/2945
too.
> Bug 2057544: daemon: Explicitly start rpm-ostreed, restart if we detect active txn

- pkg/controller/node/node_controller.go
- pkg/controller/node/node_controller_test.go
- pkg/daemon/daemon.go
Manually picking commits from #3064
> [release-4.10] Bug 2076308: Move removeUpdateInProgressTaint functionality to mcc

- pkg/daemon/daemon.go
I'm debugging https://bugzilla.redhat.com/show_bug.cgi?id=2075126
and while I haven't verified this is the case, as far as I can tell
from looking through the code and thinking about things, if we somehow
fail to apply the expected kernel arguments (which can occur if
`ostree-finalize-staged` fails) then we will (on the next boot)
drop in to `validateOnDiskState()` which has for a long time
checked that all the expected *files* exist and mark the update as
complete.  But we didn't check the kernel arguments.
That can then cause later problems because in trying to apply further
updates we'll ask rpm-ostree to try to remove kernel arguments that
aren't actually present.
Worse, often these kernel arguments are actually *quite important*
and may even have security relevant properties (e.g. …
> daemon: Validate kernel arguments

- pkg/controller/node/node_controller.go
- pkg/controller/node/node_controller_test.go
Add check for nodes with matching zones, in this case, sort by age oldest to newest.
Also added some test case coverage for this and refactor existing test cases to all have a standardized declaration.
Closes: BZ 2076521
> Bug 2076521: mcc: update node sort to account for matching zones

- install/0000_80_machine-config-operator_01_containerruntimeconfig.crd.yaml
- pkg/apis/machineconfiguration.openshift.io/v1/types.go
The outdated doc confused the customer with default overlaySize. The description should be updated since the default was removed.
> Bug 2081119: drop doc overlaysize default

- pkg/controller/common/helpers.go
- pkg/controller/common/helpers_test.go
- pkg/controller/container-runtime-config/helpers.go
- pkg/controller/kubelet-config/helpers.go
- pkg/controller/node/node_controller_test.go
- pkg/daemon/update_test.go
- test/helpers/helpers.go
See https://github.com/coreos/butane/issues/332#issuecomment-1113670664
Basically, everywhere we make a "raw" Ignition file type, we need
to be explicitly setting the compression field.  This is prep
for updating butane and using it for some of our templates, which
will start compressing files automatically.
The problem is Ignition config merging is a bit broken with respect
to an unset compression field.  We need to make it the explicit
empty string.
Now, when I was digging into this I noticed that we'd ended up with
our API to make Ignition files in the `test/helpers`.  We shouldn't
have *core* code importing APIs from `test/`.
This moves the APIs into `controller/common`.
Port the kubelet config and container runtime config bits to this -
notice how much the code shrinks!
> Move Ignition file generation to controller/common, fix Compression

- pkg/operator/sync.go
Removed logged warning when PlatformStatus.VSphere is nil.  
Check machine-config-operator logs for the presence of `Warning: PlatformStatus.VSphere should not be nil` on conclusion of e2e-vsphere-upi e2e test.  Log message should not be present.
remove `PlatformStatus.VSphere should not be nil` warning encountered on vSphere UPI clusters.
> Bug 2080267: [vsphere] remove warning encountered on vSphere UPI cluster without API VIP

- pkg/controller/container-runtime-config/container_runtime_config_bootstrap.go
- pkg/controller/container-runtime-config/container_runtime_config_bootstrap_test.go
- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
- pkg/controller/container-runtime-config/helpers.go
- pkg/controller/kubelet-config/kubelet_config_bootstrap.go
- pkg/controller/kubelet-config/kubelet_config_bootstrap_test.go
fix: https://bugzilla.redhat.com/show_bug.cgi?id=2076355 for kubeletconfig and containerruntimeconfig.
This PR applies the changes made in https://github.com/openshift/machine-config-operator/pull/2936 to kubeletoconfig and containerruntimeconfig bootstrap.
Set MCNameSuffixAnnotationKey for bootstrap kubeletconfig/containerruntimeconfig to avoid
regeneration of suffixed machineconfig names.
> Bug 2076355: fix MCNameSuffix when kcfg ctrrcfg after bootstrap config

- test/helpers/utils.go
We always call LabelRandomNodeFromPool with worker as the pool argument,
but it could be some other pool
> [low priority] test/helpers: fix typo hardcoded pool

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
This PR add two prometheus rules for master node memory usage.
The docs recommend limiting control plane memory consumption to <=60% [1].  
This commit adds `HighOverallControlPlaneMemory` to give warning-level alerting when the control plane as a whole passes that level.  Scaling the control plane instances currently requires draining and rebooting nodes, so we don't want to wait for higher resource consumption before scaling up.  `60m` is the default for warning alerts [2], and we have no reason to diverge from that default here.
Also replace the old, full-control-plane `MasterNodesHighMemoryUsage` with `ExtremelyHighIndividualControlPlaneMemory` at the >90% level, and raise severity to critical.  The new name aligns with the established CPU-alerting pattern.  The new severity is …
> RFE-2703: add prometheus rules for master memory usage

- manifests/machineconfigdaemon/clusterrole.yaml
There is no reason for the daemonset to mutate machineconfigs.
Part of https://github.com/openshift/machine-config-operator/pull/3135
> manifests: Lower daemon RBAC permissions on machineconfig objects

- templates/common/_base/files/configure-ovs-network.yaml
As we now tear down and reconfigure br-ex on every reboot, we must
provide a means to stabilize interface selection in scenarios with
multiple default route interfaces.
Clean backport for:
bc566e892e8931fe069fecda8d76801d3a5b134d
Conflict for:
e6ea64c82e88c1f7a2d7f99db935a09aaa4b3666
Due to the removal of the following lines in: 
https://github.com/openshift/machine-config-operator/commit/e43a9f216937df5b0fc9c744be78687ac38c21f2#diff-afb45a3711a77d94f26471d9d94a7f7a03d931d9e72bdf849f2e26e2711d6fd7L188
> [release-4.10] Bug 2081317: configure-ovs.sh: Provide store hint for default route interface

- pkg/controller/common/controller_context.go
- pkg/daemon/daemon.go
- pkg/daemon/update.go
- pkg/daemon/writer.go
This is just the first two commits from https://github.com/openshift/machine-config-operator/pull/3141
I think we can safely land this now.
--
daemon: Have nodeWriter maintain ref to lister and node name
The NodeWriter is an instance of the "actor" pattern effectively;
it processes messages to update its internal state.
However, it's a bit redundant to have every update take the node
lister and node name - we only use this on the daemon side,
where there is exactly one node we will be updating.
Have the clusterNodeWriter instance of this interface cache
references to that data and avoid passing it on every message.
Prep for reworking the NodeWriter to have its own clientset.
---
controller: Export default resync period function
So I can use this from the daemon code.
---
> daemon: Have nodeWriter maintain ref to lister and node name

- pkg/daemon/drain.go
- pkg/daemon/drain_test.go
Signed-off-by: Raisaat Rashid <rarashid@redhat.com>
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2056442
Changed the logic of how the MCD handles node drains in order to prevent node drains from happening when mirrors are only added to registries with `mirror-by-digest-only=true` and no changes are made to existing registries with `mirror-by-digest-only=false`. Added a unit test case for the change.
Change registry configurations according to the steps described [here](https://docs.openshift.com/container-platform/4.9/openshift_images/image-configuration.html#images-configuration-file_image-configuration). Make sure to have a blocked/insecure registry or a registry with the `mirror-by-digest-only` field unset. This change should cause node …
> Bug 2056442: Bug fix for node drain caused by ICSP objects

- templates/common/_base/files/configure-ovs-network.yaml
Setting the default NM route metric for ovs-if-br-ex is problematic
in the presence of other Ethernet ports. In that case, ovs-if-br-ex
as well as the Ethernet ports will have the same route metric, and
the winner is undefined. Lower ovs-if-br-ex route metric to 49 to
avoid ambiguous situations.
Conflicts:
templates/common/_base/files/configure-ovs-network.yaml
(cherry picked from commit e6a673db9a2931906cf00832684f5d132ca333ee)
(cherry picked from commit 3711b7ceac0d1e92f0496ea78bd9305d499fe35b)
(cherry picked from commit 0644dd31d7c2e84047bf4f50d6c4db6ef52721c2)
> [release-4.7] Bug 2057526: ovs-configuration: use lower than NM default ethernet route metric

- templates/common/_base/files/configure-ovs-network.yaml
Restarting NM has a bunch of race conditions to whatever NM might be doing in the background at that time. There are several bugs open for this but we just should avoid restarting NM or managing general networking. Instead:
* Make sure that connections profiles are initially added deactivated so we can make further modifications on them without requiring an extra activation or interfering with whatever might be happening in the background with NM while we do so.
* Rely on a single & final explicit activation within a retry loop.
* Make sure we activate slave clones of active connections
* As we activate the profiles, enable autoconnect to make sure they are activated in the future when needed.
* On rollback, just wait for the original devices to activate through any profile that NM …
> Bug 2078866: configure-ovs: avoid restarting NetworkManager

- pkg/daemon/update.go
To provide better information to what the MCD is doing, the MCD should emit an event whenever a MachineConfig specifies that a new OS will be installed as well as whenever it does not.
I added two events, `OSUpgradeApplied` and `OSUpgradeSkipped` which are emitted whenever the MCD determines an OS upgrade is required or not.
1. Spin up a test cluster.
2. Watch the logs for a given node, e.g.: `$ oc logs -n openshift-machine-config-operator -c machine-config-daemon -f pod/machine-config-daemon-8hqvd`.
3. Create and apply a new MachineConfig.
4. Watch for the following events in the log (may need to start the MCD with the `-v4`) flag:
```console
I0518 19:51:24.703522    2623 event.go:285] Event(v1.ObjectReference{Kind:"Node", Namespace:"", …
```
> Bug 2012969: emit kube events for skipped and upgraded OSes

- templates/master/00-master/alibabacloud/files/etc-kubernetes-manifests-apiserver-watcher.yaml
- templates/master/00-master/azure/files/etc-kubernetes-manifests-apiserver-watcher.yaml
- templates/master/00-master/gcp/files/etc-kubernetes-manifests-apiserver-watcher.yaml
Move the `apiserver-watcher` static pods from the `kube-system` namespace to the `openshift-kube-apiserver` namespace.
> Bug 1948551: apiserver-watcher should run in a privileged namespace 

- templates/common/aws/files/usr-local-bin-aws-kubelet-providerid.yaml
- templates/common/aws/units/aws-kubelet-providerid.service.yaml
- templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
- templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
I Added AWS specific systemd unit (`aws-kubelet-providerid.service`) and file (`/usr/local/bin/aws-kubelet-providerid`) for generating the AWS instance provider-id (then stored in the `KUBELET_PROVIDERID` env var), in order to pass it as the `--provider-id` argument to the kubelet service binary.
We needed to add such flag, and make it non-empty only on AWS, to make the node syncing (specifically backing instance detection) work via provider-id detection, to cover cases where the node hostname doesn't match the expected `private-dns-name` (e.g. when a custom DHCP Option Set with empty `domain-name` is used).
Should fix: https://bugzilla.redhat.com/show_bug.cgi?id=2084450
Reference to an upstream issue with context: …
> Bug 2084450: Add unit/file for AWS to compute instance provider-id and pass it to the kubelet

- pkg/controller/node/node_controller.go
This explicitly requeues the "old" pool when a node between pools so the "old" pool can update its counts immediately rather than having to wait until the pool gets re-queued by something else (which can take minutes). 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2090436
> Bug 2090436: It takes 30min-60min to update the machine count in custom MachineConfigPools (MCPs) when a node is removed from the pool

- templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
We have reports that on rare occasions when a control plane node is
taken offline it causes a keepalived failover on a different node.
This should not happen because haproxy should stop sending traffic
to the offline node before keepalived runs two health checks.
HAProxy is configured to check every second, while keepalived is
configured to check every 2 seconds, and it requires two failures
before considering the node failed.
What I think might be happening is that the keepalived and haproxy
health checks overlap exactly and the two keepalived health checks
happen exactly the same two seconds apart that it takes for haproxy
to notice the outage.
To ensure this cannot happen, I'm changing the fall value of the
keepalived checks to 3 so it will take 6 seconds to notice an outage.
While …
> [on-prem] Bug 2045559: Increase keepalived API check fall value to 3

- install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Update message to point to MCC and not MCD pod, since MCC now does
the actual draining.
For now we are doing this to preserve old alerts, but we should
potentially consider alerting via MCC and deprecating the old alert.
> Bug 2089687: Update alert message for drain failure

- pkg/controller/drain/drain_controller.go
So we know when the drain actually started. Cordon has a separate log already.
> Bug 2090358: Move drain log message to when drain starts

- templates/common/on-prem/files/keepalived-script-default-ingress.yaml
Fixes: #3155
Changed regexp in template. Really I didn't even try to build MCO, just created machineconfig override to test if it works :-)
Apply fix on cluster and see if destination file contains correct grep command, and keepalived keeps ingress VIP on same node that runs ingress pod.
Ideally one can check it on cluster that has nodes with IP as described in issue #3155.
Fixed keepalived check for ingress VIP
> [on-prem] Bug 2089775: Fix regexp in keepalived script chk_default_ingress.sh

- pkg/controller/drain/drain_controller.go
- pkg/daemon/daemon.go
- pkg/daemon/drain.go
Change drain controller to continue retrying after 1h timeout,
to match old daemon behaviour. If the drain is eventually successful
or if a user intervenes and deletes the problematic pod, the controller
will now continue instead of being stuck on the failure.
Also modify daemon logic to properly report degrade instead of
unnecessarily retrying.
Using the steps in the BZ https://bugzilla.redhat.com/show_bug.cgi?id=2090794, wait for timeout to ensure the pool is degraded with the corresponding message, then delete the pod. The MCC/MCD will continue and undegrade.
Manually tested with above (after dropping timeouts to 6 min)
> Bug 2090794: drain controller: continue retry after 1h timeout

- templates/common/_base/files/configure-ovs-network.yaml
After backporting 715393a in #3160, auto-connect was being set after keyfiles were persisted from the overlay `systemConnectionsMerged` to the underlay `system-connections` and thus the setting was lost after reboot. So persist profiles at the very end.
> [release-4.9] Bug 2089763: configure-ovs: persist profiles after auto-connect has been set

- pkg/operator/sync.go
This adjusts our behavior around how machine-config-operator reacts to config changes while the master pool has been paused. 
Old behavior on a config change with a paused master was: 
- `syncRequiredMachineConfigPools` spins for 10 minutes and times out with an error (which holds up other syncs such as RenderConfig) 
- Operator degrades after sync timeout error
New behavior is: 
- `syncRequiredMachineConfigPools` returns error immediately if pool is paused 
- Operator degrades after paused error
So we save the 10 minute timeout/wait that was useless anyway because we *knew* it would never succeed 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2005694
> Bug 2005694: Removing proxy object takes up to 10 minutes for the changes to propagate to the MCO 

- templates/common/_base/files/configure-ovs-network.yaml
* clone connection to avoid selinux problems
/etc/NetworkManager/systemConnectionsMerged is not correctly registered
in selinux as a location for NM to manage its connection profiles so
attempting to update a profile through NM after manually copying and
doing a restorecon from that location fails. So instead of copying files
there and restorecon manually, rely on `nmcli clone` to copy a connection
and let that handle selinux attributes.
While we don't use /etc/NetworkManager/systemConnectionsMerged since
4.9 and this only really applies to that and earlier releases, bring in
these changes anyway as it should still be ok and common code eases
backports.
* explicitly set ovs-if-phys mac
ovs-if-br-ex and ovs-if-phys need to be configured with the same mac
address. While ovs-if-br-ex mac …
> Bug 2096413: configure-ovs: improve handling of static ip and mac address configuration

- pkg/controller/common/helpers.go
- pkg/controller/common/helpers_test.go
Our current logic looks for FIPS and kerneltype in the same loop,
breaking if any of them sets type=realtime. This means that if both
are enabled, and the FIPS MachineConfig is higher alphanumerically
compared to kerneltype (which is generally the case: installer
generates FIPS as 99 and NTO generates realtime as 50), the FIPS gets
lost when merging, causing the cluster to break.
Modify the logic a bit so this can't happen. Also re-order the test
to ensure this case is fixed.
> Bug 2096496: controller: de-couple FIPS and realtime detection

- pkg/controller/drain/drain_controller.go
In our old daemon logic, we used to retry failing drains after 1
minute for the first 5 failures, then we would retry after 5 minutes
until the 1hr timeout is reached.
In practice, this means that the daemon retries after
5 * (retry sleep + drain timeout) = 12.5 minutes, which is a bit
more resource saving.
The controller has a bit more difficulty matching this, since the
retries can happen at odd intervals (faster if the node gets requeued
by something else, or slower if there are many nodes competing for
the limited queue parallelism). So there is less value of doing so.
This is an example implementation of time based slowdown in retries,
but the usefulness may not be worth it.
> Bug 2092442: drain_controller: slow down retries for failing nodes

- cmd/common/helpers.go
- cmd/machine-config-controller/start.go
- cmd/machine-config-operator/start.go
- pkg/controller/common/metrics.go
**TL;DR**: SIGTERM/SIGINT --> cancel `runContext` --> shutdown -->   cancel `leaderContext` --> release leader lease --> terminate 
- added two contexts:
- a `runContext` (for cencelling our running state)  and 
- a `leaderContext` (for cancelling our leader lease) 
to both the controller and the operator run functions
- added a signal handler that catches SIGINT/SIGTERM to controller and operator
- updated run functions such that: 
- signal handler cancels `runContext` when SIGTERM/SIGINT is received
- operator/controller shuts down when `runContext` is cancelled, and then sequentially cancels `leaderContext`
- updated leaderElection config in controller and operator to release leader lease when `leaderContext` is cancelled 
- shutdown metrics listener properly 
**- How …
> Bug 1817075: MCC & MCO don't free leader leases during shut down -> 10 minutes of leader election timeouts

- docs/README.md
I went to look at our README.md and was surprised it still talked
about Ignition spec 2.  Plus, there's now butane to generate
configs and not need to manually base64 encode things, etc.
Let's just link this section to the product documentation, which
will also help motivate us to improve that.
> README: Link to the product documentation for example MachineConfigs

- templates/common/_base/files/configure-ovs-network.yaml
Partially revert cloning the mac address for ovs-if-phys except for 
aggregated links:
* it's entirely possible that some devices won't support the operation.
* link aggregation active-backup mode with fail_over_mac doesn't
support it, bond driver ignores the request and NM fails.
* all other bond modes should support it and have been tested.
* assuming the same for teamd as it is functionally equivalent for the
most part, documentation states "A random hardware address is generated
for a newly created device unless the user explicitly specifies it."
Tested that this is the case for all modes.
While testing teamd aggregated links, activating a cloned slave would
fail. This happened because NM would try to re-connect the other slave,
and since the other slave cloned profile still had not …
> Bug 2096413: configure-ovs: set mac only for non fail_over_mac bonds

- pkg/daemon/daemon.go
As part of https://github.com/openshift/machine-config-operator/pull/3143
we re-ordered the clusterconnect operations. This meant that the login
monitor started before the nodewriter object was initialized, which
caused a race where the monitor could try to write the ssh accessed
annotation before the nodewriter was initialized, causing a panic.
This is good to get fixed, but also note that:
1. this is relatively rare since most users should not be ssh'ing
2. the general ssh accessed annotation is broken such that its not
always applied, but we definitely should not panic here.
> Bug 2099664: daemon: initialize nodewriter before login monitor

- install/0000_80_machine-config-operator_00_namespace.yaml
We dropped the run-level label from this namespace back in 4.5
but because of how the cluster-version operator reconciles manifest
labels, dropping a label from the manifest does not remove it from the
in-cluster resource when old clusters are updated into the new
manifest. This commit uses the approach the cluster-version
operator used to drop its run-level, by setting the value to an
empty string, which the run-level-consuming code treats identically to
an unset label.
This avoids errors about:
...container has runAsNonRoot and image will run as root...
when updating to 4.11 in case the operator deployment manifest
specifically requests `runAsNonRoot: true`.
> Bug 2101880: NS manifest: Set empty openshift.io/run-level

- templates/common/_base/files/configure-ovs-network.yaml
For OVN-K based clusters, each connection is activated if  it contains the suffix "-slave-ovs-clone". The iteration doesn't work if the connection name has spaces in it. It will also incorrectly activate a connection if the name contains the string "-slave-ovs-clone" but not as a suffix.
Added the correct handling of connection names with spaces. Also added the check to activate connections which has the string "-slave-ovs-clone" as suffix only.
Signed-off-by: Arkadeep Sen <arsen@redhat.com>
> Bug 2101157: configure-ovs: fix handling of connection names with spaces and checking the connection name suffix

- templates/common/_base/files/configure-ovs-network.yaml
We assumed that only active slave profiles were valid. But if a node
boots with one of the slave links down, and thus the corresponding
profile inactive, it would be ignored, and then if the link went up we
would have no cloned profile for it.
So not only clone active slave profiles, but those that have autoconnect
set as well.
We can't just clone all profiles because we don't know if there is a
profile sitting around not intended to be used.
> Bug 2099945: configure-ovs: clone inactive autoconnect slaves

- pkg/controller/common/helpers.go
When da5184f304 (#3128) created the `NewIgnFileBytes*` helpers, the call-sites which had previously explicitly set file modes
began leaving them unset.  Updating from 4.10 to 4.11 and picking up da5184f304, clusters which include ContainerRuntimeConfig (or possibly KubeletConfig) which flow through the NewIgnFileBytes* helpers would have rendered MachineConfig entries with null/unset mode values.
While this is not a problem for Ignition v3 clients, where there is an explicit 0644 default:
```console
$ git clone --depth 1 --branch main https://github.com/coreos/ignition.git
$ cd ignition
$ git --no-pager log --oneline -1
7652b83 (grafted, HEAD -> main, origin/main, origin/HEAD) Merge pull request #1409 from bgilbert/notes
$ git --no-pager grep '_mode_.*file' docs …
```
> Bug 2102004: pkg/controller/common/helpers: Explicitly set mode 0644

- manifests/machineconfigcontroller/deployment.yaml
- pkg/controller/drain/drain_controller.go
In 4.11 we moved the drain operation to a centralized controller.
This drain controller doesn't drain the MCC today.
In theory this means the pod can finish and then gracefully terminate.
In practice this is problematic since the pod never gets scheduled
off the node, meaning it thinks its still running (according to the API)
when the master node shuts down, and won't be reachable until the master
node reboots.
For some metal setups the reboot could take up to 30 minutes, this means
that we won't have a MCC for 30 minutes, which would be very problematic
as other pools waiting for drains/updates are stalled as well. We should
instead just drain the controller pod. The next one will immediately
pick up where this one left off, so there shouldn't be any conflicts.
The pod when drained will …
> Bug 2103786: drain controller: don't skip the MCC pod drain

- templates/common/on-prem/files/coredns.yaml
coredns sometimes gets stuck in a CrashLoopBackoff (and thus node stays
at NotReadfy) because render-config-coredns fails to render when there
are no nameservers in /etc/resolv.conf. Currently this happens because
kubelet might start before resolv-prepender has had a chance to write
/etc/resolv.conf and when it does render-config-coredns does not see the
update.
Make render-config-coredns use /var/run/NetworkManager/resolv.conf which
is actually what coredns-monitor is using as well.
> on-prem: render-config-coredns from /var/run/NetworkManager/resolv.conf

- templates/common/_base/files/configure-ovs-network.yaml
Clean cherry-picks of c4b7ad1a8 9655b6bca 8d65c53df from #3190, and a9e1a1d81d7c8a6543668850b793be093c1b0327 0750a4a8cce4f8d918caf8f3a4236f0ae2b6b2e4 from #3216
> [release-4.10] Bug 2098626: configure-ovs: improve handling of static ip and mac address configuration

- pkg/daemon/rpm-ostree.go
In 4.12 (master) we'll be shipping with at least RHEL8.6's
rpm-ostree 2022.2 which ships the fixes for the two bugs we were
hacking around here.
> daemon: Drop workarounds for rpm-ostree bugs

- pkg/daemon/kernelargs.go
daemon: Drop tuneableFCOSArgsAllowlist
In OKD/FCOS, there is no reason from a supportability standpoint to
enforce an allowlist for kernel arguments that the MCD can tune.
Currently, its existence is actually rather a hindrance, as in OKD this
API is used to set kargs during cluster bootstrapping via manifests,
the flexibility of which is therefore limited.
Verify this doesn't break CI
/cc @vrutkovs
> daemon: Drop tuneableFCOSArgsAllowlist

- pkg/controller/drain/drain_controller.go
Drain controller was still using the cached lookup for the "did the cordon work" safety check even though the logging message was using the live value. 
It seems that if the apiserver was under heavy load or in some unreliable state, the MCO would allow a cordoned node to sneak through, thinking it had uncordoned it.  
This PR makes the safety check also use the live/uncached value. 
@yuqi-zhang I thought I'd just fix this quick since I saw it and I was in here, but if you'd rather do something different, I'm 100% cool with it. 
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2109963
> Bug 2109963: Master node in SchedulingDisabled after upgrade from 4.10.24 -> 4.11.0-rc.4

- pkg/controller/container-runtime-config/container_runtime_config_controller.go
- pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
Apply code clean up in #3096 to ctrcfg controller. Remove cleanUpDuplicatedMC() from pkg/controller/container-runtime-config/container_runtime_config_controller.go.
This function is nolonger needed since the original issue was from getManagedKeyCtrCfg() and we have fixed it.
> ctrcfg controller remove cleanupmc()

- OWNERS
Updating OWNERS list with current active MCO members to make sure that PRs gets assigned for review/approval accordingly.
Thanks @kikisdeliveryservice  for all the MCO contribution! If you would like to continue being a reviewer, your input will be always welcome :heart:
> Update approvers and reviewers list with current active members

- templates/common/_base/files/configure-ovs-network.yaml
Cherry-pick of https://github.com/openshift/machine-config-operator/commit/e6ea64c82e88c1f7a2d7f99db935a09aaa4b3666 from #3131, and https://github.com/openshift/machine-config-operator/pull/3197/commits/147c84ac58c6b96a1de724aee910bb456744657f, https://github.com/openshift/machine-config-operator/pull/3197/commits/c3666affe233969155b5a803ef3499971e1e8911, https://github.com/openshift/machine-config-operator/pull/3197/commits/56b993fe29436ec9c0f8fc24d8c05eb098e0ebde and  https://github.com/openshift/machine-config-operator/pull/3197/commits/75ba2045e96230ce1abf7a1f5f6647ba468b3190 from #3197  
Note that https://github.com/openshift/machine-config-operator/pull/3197/commits/d469d406675b50184c0629460f16d1c65239c50b from #3197 was already included in this released
Minor conflicts resolution.
> [release-4.9] Bug 2108538: configure-ovs: improve handling of static ip and mac address configuration
