openshift/machine-config-operator

OWNERS
cmd/machine-config-daemon/OWNERS
pkg/daemon/OWNERS

Dropping `reviewers` sections as recommended by @stevekuznetsov

*: fix owners file

---

README.md

README.md: Add test instructions

---

pkg/daemon/daemon.go

Minor tweaks as I was reading the codebase. See individual commit messages.

Minor tweaks

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go
pkg/daemon/update.go

Prereq for https://github.com/openshift/machine-config-operator/pull/17

chroot to rootPrefix

---

pkg/daemon/daemon.go
pkg/daemon/update.go

pkg/daemon/: Fix gofmt issues

---

cmd/machine-config-daemon/start.go

During some testing by @jlebon it was noted that chrooting is
causing some files mounted into the container to be no longer
available while MCD is reading it's initial configuration.
This change pushes the chroot after the clients have been
created and the main daemon struct has been created.

mcd: chroot after clients load

---

pkg/daemon/update.go

We were previously dereferencing `f.User` without checking if it was
`nil` first. Just lift `ResolveNodeUidAndGid()` from Ignition (and make
a note that we should dedupe stuff down the line).

daemon: strengthen user/group handling

---

pkg/daemon/daemon.go

I may be mistaken, but it seems like what we want here is a main loop
that continuously watches for updates and re-applies config changes.
I.e., we don't want to reboot if a config change doesn't actually
requires it.
Of course, this is a moot point for now given that we always reboot for
any changes. Though figuring out the higher-level logic upfront is worth
it.

pkg/daemon: run main loop

---

pkg/controller/template/test_data/templates/aws/master/units/etcd-member-tls.service
pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member-tls.service
pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
templates/_base/master/units/etcd-member-tls.yaml
templates/_base/master/units/etcd-member.yaml

Use podman for etcd
/cc @crawford 
/hold
Need to test in installer before merging.

templates: update etcd to use podman

---

install/02_images.configmap.yaml
install/04_deployment.yaml

install: fix images

---

pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
templates/_base/master/units/etcd-member.yaml

:( missed some changes that hardcoded apiserver-url

templates: fix etcd_template

---

Gopkg.lock
pkg/operator/render_test.go
vendor/github.com/openshift/installer/pkg/types/machinepools.go

Bumping our vendored installer to pick up openshift/installer#237, and updating the test to match.
/assign @abhinavdahiya

pkg/operator/render_test: Catch up with platformConfig -> platform

---

pkg/daemon/node.go

See:
- https://github.com/openshift/machine-config-operator/issues/68
- https://github.com/openshift/machine-config-operator/pull/72

daemon: Restart watch on ErrWatchClosed

---

hack/push-image.sh

How to use:
[REPO=<personal repo>] WHAT=[all,machine-config-*] ./hack/push-image.sh
/cc @ashcrow @sdemos 
ref: https://github.com/openshift/machine-config-operator/pull/81#discussion_r218976034

hack: add push-image.sh

---

pkg/operator/sync.go

pkg/operator: remove etcd pool assets; doesn't exist

---

pkg/controller/template/test_data/templates/aws/master/units/kubelet.service
pkg/controller/template/test_data/templates/aws/worker/units/kubelet.service
pkg/controller/template/test_data/templates/libvirt/master/units/kubelet.service
pkg/controller/template/test_data/templates/libvirt/worker/units/kubelet.service
templates/_base/master/units/kubelet.yaml
templates/_base/worker/units/kubelet.yaml

@smarterclayton @eparis @rphillips 
xref https://github.com/openshift/installer/pull/266

enable parallel image pulls

---

pkg/daemon/update.go

Closes Issue #80
- Adds V(2) logging to /daemon/update.go

MCD: Log level clean up (daemon/update.go)

---

install/02_images.configmap.yaml

install: fix namespace for images.configmap

---

pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/template/render.go
pkg/controller/template/render_test.go
pkg/controller/template/test_data/controller_config_openstack.yaml
pkg/controller/template/test_data/templates/openstack/master/files/-etc-containers-registries.conf
pkg/controller/template/test_data/templates/openstack/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt
pkg/controller/template/test_data/templates/openstack/master/files/-etc-hosts
pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-ca.crt
pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/openstack/master/files/-etc-ssl-etcd-ca.crt
pkg/controller/template/test_data/templates/openstack/master/files/-etc-ssl-etcd-root-ca.crt
pkg/controller/template/test_data/templates/openstack/master/files/-etc-sysconfig-crio-network
pkg/controller/template/test_data/templates/openstack/master/units/etcd-member.service
pkg/controller/template/test_data/templates/openstack/master/units/kubelet.service
pkg/controller/template/test_data/templates/openstack/worker/files/-etc-containers-registries.conf
pkg/controller/template/test_data/templates/openstack/worker/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt
pkg/controller/template/test_data/templates/openstack/worker/files/-etc-hosts
pkg/controller/template/test_data/templates/openstack/worker/files/-etc-kubernetes-ca.crt
pkg/controller/template/test_data/templates/openstack/worker/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/openstack/worker/files/-etc-sysconfig-crio-network
pkg/controller/template/test_data/templates/openstack/worker/units/kubelet.service
pkg/operator/render.go
vendor/github.com/openshift/installer/pkg/ipnet/ipnet.go
vendor/github.com/openshift/installer/pkg/types/installconfig.go
vendor/github.com/openshift/installer/pkg/types/machinepools.go

I'm adding support for OpenStack to the various operators, controllers, and providers that manage an openshift cluster.
I've started by pushing this patch as it seems to be the first step in the flow. I'm not sure if this PR should depend on others so I'd really appreciate some guidance in the process. :smile:

Add OpenStack as a valid platform

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go
pkg/daemon/fsclient.go
pkg/daemon/fsclient_test.go
pkg/daemon/update.go

Part of #101 
/cc @jlebon @sdemos @kikisdeliveryservice

daemon/fsclient: Wraps file system operations

---

pkg/daemon/daemon.go
pkg/daemon/update.go

Otherwise we'll think we successfully reconciled even if the modes
differ.

daemon: also check file mode when comparing

---

pkg/daemon/fsclient.go
pkg/daemon/fsclient_test.go

daemon: Add WriteFiles to FsClient

---

HACKING.md

MCD: update hacking doc

---

HACKING.md

Adding some of my notes to the mcd documentation.

update hacking.md with oc commands and check for successful deployment.

---

HACKING.md

See https://github.com/openshift/machine-config-operator/pull/144#issuecomment-433172099

HACKING.md: Remove kube commands

---

pkg/daemon/constants.go
pkg/daemon/osrelease.go

Resolves #161
/cc @vrutkovs @kikisdeliveryservice

mcd: Add CentOS to OS whitelist

---

Dockerfile.machine-config-daemon
Dockerfile.machine-config-daemon.rhel7

*: fix mcd docker files

---

pkg/controller/template/test_data/templates/aws/master/files/-etc-modules-load.d-bridge.conf
pkg/controller/template/test_data/templates/aws/master/files/-etc-sysctl.d-bridge.conf
pkg/controller/template/test_data/templates/aws/master/files/-etc-sysctl.d-forward.conf
pkg/controller/template/test_data/templates/aws/worker/files/-etc-sysctl.d-forward.conf
pkg/controller/template/test_data/templates/libvirt/master/files/-etc-modules-load.d-bridge.conf
pkg/controller/template/test_data/templates/libvirt/master/files/-etc-sysctl.d-bridge.conf
pkg/controller/template/test_data/templates/libvirt/master/files/-etc-sysctl.d-forward.conf
pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-sysctl.d-forward.conf
pkg/controller/template/test_data/templates/openstack/master/files/-etc-modules-load.d-bridge.conf
pkg/controller/template/test_data/templates/openstack/master/files/-etc-sysctl.d-bridge.conf
pkg/controller/template/test_data/templates/openstack/master/files/-etc-sysctl.d-forward.conf
pkg/controller/template/test_data/templates/openstack/worker/files/-etc-sysctl.d-forward.conf
templates/_base/master/files/modules-load-bridge-conf.yaml
templates/_base/master/files/sysctl-bridge-conf.yaml
templates/_base/master/files/sysctl-forward-conf.yaml
templates/_base/worker/files/sysctl-forward-conf.yaml

* revert the flannel bridge changes
* Enable `ip_forward` by default.

Clean up some network sysctls

---

pkg/controller/template/template_controller.go
pkg/controller/template/template_controller_test.go

controller: pull secret should always be compacted

---

cmd/machine-config-server/bootstrap.go
cmd/machine-config-server/main.go
cmd/machine-config-server/start.go
pkg/controller/bootstrap/bootstrap.go
pkg/controller/render/render_controller.go
pkg/server/api.go

xref: https://jira.coreos.com/browse/CORS-904
/cc @crawford

server: serve on both insecure and secure ports 

---

hack/build-go.sh

Change $VERSION to $VERSION_OVERRIDE for the echo output as well,
as we did this elsewhere.

hack: fix version env

---

OWNERS
OWNERS_ALIASES

So that we don't have to bother other folks for e.g. small docs changes.

OWNERS: add more OS folks

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go
pkg/daemon/writer.go

See individual commit messages.

Various error-handling fixes

---

lib/resourceapply/rbac.go
lib/resourcemerge/rbac.go
lib/resourceread/rbac.go
manifests/machineconfigdaemon/events-clusterrole.yaml
manifests/machineconfigdaemon/events-rolebinding-default.yaml
manifests/machineconfigdaemon/events-rolebinding-target.yaml
pkg/daemon/daemon.go
pkg/daemon/update.go
pkg/operator/assets/bindata.go
pkg/operator/sync.go

These three events represent rough actions taken by the MCD that an
administrator should know about.

debug: Send significant events to the apiserver for a node

---

manifests/machineconfigcontroller/deployment.yaml
pkg/controller/node/node_controller.go
pkg/controller/render/render_controller.go
pkg/controller/template/template_controller.go
pkg/operator/assets/bindata.go

This should give us move visibility into root cause for #203

controller: requeue errors after timeout

---

Makefile
README.md
hack/build-go.sh

Minor enhancements to the building process to use a Makefile. Updated
the README.md to include Makefile instructions.

Build Enhancements: added Makefile and fixed unbound variable

---

README.md

/cc @kikisdeliveryservice @ashcrow

README.md: Add managing go dependencies section

---

pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/aws/worker/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/openstack/worker/files/-etc-kubernetes-kubelet.conf
templates/master/00-master/_base/files/kubelet.yaml
templates/worker/00-worker/_base/files/kubelet.yaml

parity with openshift 3.11
https://docs.openshift.com/container-platform/3.11/admin_guide/manage_nodes.html#configuring-node-resources
/cc @smarterclayton @sjenning

kubelet: bump max pods to 250

---

HACKING.md

Should help folks understand how to play around with the MCC and MCD and
how things are wired together at a practical level.

HACKING.md: add layered MachineConfig example

---

pkg/server/bootstrap_server.go
pkg/server/server.go

The last consumer was removed by 4cc79882 (#143).

pkg/server: Drop unused etcdTemplateParam

---

hack/cluster-push.sh

two small hack/cluster-push patches

---

pkg/server/server.go

Some MCD refactoring in: https://github.com/openshift/machine-config-operator/pull/245
will be nicer if these annotations all
exist and are in sync initially.

server: Also write state=Done annotation initially

---

OWNERS

I think I have graduated to at least a yellow belt in this codebase,
and would like the ability to approve other people's PRs.

OWNERS: Add myself

---

pkg/controller/render/render_controller.go

I'd like a bit more visibility into what the controller is doing.
While I could `oc watch machineconfigs` too, I think this one is
worth a log message.

controller: Log when we generate a MC

---

Makefile

Regression from https://github.com/openshift/machine-config-operator/pull/236
I think I'd fixed this when developing but forgot to commit or something?

Makefile: Fix `make deploy-daemon`

---

pkg/daemon/node.go

Just like we do with `getMachineConfig()`.
Closes: https://github.com/openshift/machine-config-operator/issues/252

daemon: Add retries around fetching annotations

---

docs/MachineConfigDaemon.md

Update for https://github.com/openshift/machine-config-operator/pull/245
And fill in with other details that were decided on a while ago (e.g.
oscontainer and not raw ostree fetches to in-cluster HTTP etc.)

docs/MCD: Update some for new model

---

pkg/daemon/update.go

The presence of an old config file can affect how the system runs.  So
we should treat the inability of deleting such files as an error.
Follow up to #272 (only the last commit is new). Will rebase once that's merged.

daemon: error out if failing to delete stale data

---

pkg/daemon/daemon.go

We can almost update but go degraded on boot because we had
incorrect variable scoping here :cry:

daemon: Fix load of booted OS

---

Makefile

This matches what cluster-image-registry-operator is doing.
Prep for #309

 Makefile: Add `test-unit`, only test pkg/ lib/ and cmd/

---

pkg/controller/template/render_test.go

controller/tests: Avoid hardcoding SSH MC offsets

---

HACKING.md
pkg/operator/assets/bindata.go

I missed asking for updating `bindata` for operator in #316 . :(
/cc @sjenning @cgwalters

Update bindata for operator

---

pkg/controller/render/render_controller.go

It doesn't work right now and fixing it would break other things
until we have time to define a sane GC model.  The current code
emits warning spam, so let's delete it, but leave an empty function
so we remember we do need to implement it.

controller: Move MC garbage collection to helper function, disable it

---

pkg/operator/bootstrap.go

We had this before, compare the endless string with numbers:
```
Jan 24 14:37:42 ip-10-0-14-29 bootkube.sh[4456]: I0124 14:37:42.492631       1 bootstrap.go:58] Version: 3.11.0-496-g182773bf-dirty
Jan 24 14:37:42 ip-10-0-14-29 bootkube.sh[4456]: I0124 14:37:42.497388       1 bootstrap.go:74] {manifests/machineconfigcontroller/controllerconfig.yaml [] bootstrap/manifests/machineconfigcontroller-controllerconfig.yaml}
Jan 24 14:37:42 ip-10-0-14-29 bootkube.sh[4456]: I0124 14:37:42.505191       1 bootstrap.go:74] {manifests/master.machineconfigpool.yaml [] bootstrap/manifests/master.machineconfigpool.yaml}
Jan 24 14:37:42 ip-10-0-14-29 bootkube.sh[4456]: I0124 14:37:42.506780       1 bootstrap.go:74] {manifests/worker.machineconfigpool.yaml [] …
```

Fix log output

---

pkg/daemon/update.go

pkg/daemon: add missing defer file.Close

---

pkg/controller/container-runtime-config/container_runtime_config_controller.go

pkg/controller: remove fmt.Println

---

pkg/controller/container-runtime-config/container_runtime_config_controller_test.go

Add unit tests for ctrcfg update, imgcfg create, and
imgcfg update.

Add unit tests for containerruntimeconfig controller

---

cmd/setup-etcd-environment/run.go

the InterfaceAddrs [1] returns list of all unicast addreses from the system
[ipaddrs.go]
```go
package main
import (
"fmt"
"net"
)
func main() {
addrs, err := ipAddrs()
fmt.Println(addrs, err)
}
func ipAddrs() ([]string, error) {
var ips []string
addrs, err := net.InterfaceAddrs()
if err != nil {
return ips, err
}
for _, addr := range addrs {
var ip net.IP
switch v := addr.(type) {
case *net.IPNet:
ip = v.IP
case *net.IPAddr:
ip = v.IP
}
if ip == nil {
continue
}
ip = ip.To4()
if ip == nil {
continue // not an ipv4 address
}
if !ip.IsGlobalUnicast() {
continue // we only want global unicast address
}
ips = append(ips, ip.String())
}
return ips, nil
}
```
The new `ipAddrs` function returns all the ipv4 addresses rather than return one ip address for a defined interface …

cmd/setup-etcd-environment: use all unicast address as candidate when discovering self

---

pkg/controller/container-runtime-config/container_runtime_config_controller.go

When a CR was being created and the label didn't exist in any of the pools
the controller would fail and exit it out. It should try resyncing so that
when the label is added later on, it can finally sync properly and make
the necessary changes to the config fies.
Also adds patch to only update when a real change in the containerruntimeconfig
is detected. It also fetches a fresh config so that we limit the number of "object
has been updated" messages.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1686282

ctrruntimeconfig: Resync on failure and accuratey detect object updates

---

manifests/machineconfigcontroller/clusterrole.yaml
pkg/operator/assets/bindata.go

FeatureGates need to be added to the clusterrole to allow for reading and listing.
`NONE`

clusterrole: add featuregates to allowed resources

---

pkg/operator/images.go

Fixed struct's doc to fix a vet warning

pkg/operator: fix struct doc

---

hack/verify-codegen.sh
hack/verify-generated-bindata.sh

We were showing what's missing w/o make update. Makes more sense to
report the lines that make update would add actually.

hack: switch diff to show positive diffing

---

pkg/controller/kubelet-config/kubelet_config_controller.go

Log a warning on failure of status update, and return the actual error
to the caller.
close #615
/cc @runcom

kubeletconfig: Fix error propogation of status message

---

pkg/controller/kubelet-config/kubelet_config_features.go

Defaults should be sane and missing feature gates isn't.

make featuregate missing consistent with default

---

.gitignore
docs/HACKING.md

See individual commit messages

Small fixes to docs and gitignore

---

cmd/machine-config-controller/start.go
cmd/machine-config-operator/start.go
pkg/controller/container-runtime-config/container_runtime_config_controller.go
pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/controller/node/node_controller.go
pkg/controller/render/render_controller.go
pkg/controller/template/template_controller.go
pkg/operator/operator.go

It's not really syncing otherwise nor reacting...def a bug since syncs aren't even firing at this point.
This PR basically does the following:
- start informer for secrets
- add some v4 debugging which I found useful
- wait for cache syncs

start informers and wait for cache sync on informers

---

Gopkg.lock
pkg/operator/status.go
pkg/operator/status_test.go
pkg/operator/sync.go
vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
vendor/github.com/openshift/api/config/v1/types_cluster_version.go
vendor/github.com/openshift/api/config/v1/types_feature.go
vendor/github.com/openshift/api/config/v1/types_scheduling.go
vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go

- Bump vendored openshift/api and openshift/client-go
- Rename ClusterStatusConditionType "Failing" to "Degraded" 
CI
Closes: #641

Change the ClusterStatusConditionType "Failing" to "Degraded" 

---

pkg/daemon/node.go

added a log message to help with https://bugzilla.redhat.com/show_bug.cgi?id=1702626

pkg/daemon: add log about initial node annotation

---

pkg/operator/status.go
pkg/operator/sync.go

The master MCP we sync in the operator can flip Degraded=True too early
if it's still rolling out. This patch introduces back a 10 minutes
polling to give it some time to correctly roll. We also now bubble up
any error to the CO's Extension field along with a full MCPs status. The
net result of this patch is that we only flip Degraded=True if: 1)
10m are up and we do have a real error preventing roll out 2) 10m are up
and we have transient errors slowing down the roll out. In both case we
report what's happening at every iteration of the sync during the 10
mins poll w/o flipping Degraded=True (as most errors are transient
anyway). If we get a permanent error during sync, we still wait 10 mins
before reporting Degraded but the error can be seen immediately in the
clusteroperator status …

Bug 1702832: pkg/operator: poll during master MCP sync

---

docs/etcd-quorum-guard.md
install/0000_30_machine-config-operator_07_etcdquorumguard_deployment.yaml
install/0000_30_machine-config-operator_08_etcdquorumguard_pdb.yaml
install/image-references

Add etcd-quorum-guard to the machine config operator
Until the e2e is added, look at the log files in the artifacts.
Add guard to prevent more than one etcd member from being taken down at any one time

Add etcd-quorum-guard to the machine config operator

---

cmd/setup-etcd-environment/OWNERS

So he can lgtm PRs related to etcd.
@hexfusion if there are any subdirs that I've forgot to add you please let me know

setup-etcd-environment: add hexfusion to reviewers

---

Makefile
install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
test/e2e/etcdquorumguard_test.go

Add e2e for etcd-quota-guard, and remove debugging startup code from the pod
Followon to #671.
Run e2e
Add e2e for etcd-quota-guard, and remove debugging startup code from the pod

Add etcd-quota-guard e2e and remove debugging code

---

docs/MachineConfiguration.md
docs/README.md

docs: Link to OSUpgrades.md more, other various tweaks

---

.gitattributes

This makes github PRs easier to read.

gitattrs: flag updated template testdata as generated files

---

pkg/controller/kubelet-config/kubelet_config_features.go
pkg/controller/kubelet-config/kubelet_config_features_test.go
pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/master/01-master-kubelet/none/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/master/01-master-kubelet/openstack/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/master/01-master-kubelet/vsphere/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/openstack/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vsphere/files/-etc-kubernetes-kubelet.conf
templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml

Add check to skip machineconfig changes if featuregates are the same
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1699353
Fixes: https://github.com/openshift/cluster-config-operator/pull/39
/cc @sjenning @deads2k

featuregates: Add default featuregates and comparison check

---

docs/OSUpgrades.md

I've been linking to this doc a lot lately and wanted to improve it.

docs/OSUpgrades.md: Various improvements

---

pkg/controller/node/node_controller.go
pkg/controller/render/render_controller.go

Just some logging I think would be useful.

Two more mcc logs

---

pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/none/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/vsphere/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vsphere/units/kubelet.service
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

templates: increase kubelet loglevel for better troubleshooting

---

manifests/machineconfigdaemon/daemonset.yaml
pkg/daemon/daemon.go
pkg/daemon/update.go
pkg/operator/assets/bindata.go

Couple of small fixes helping in debugging + removal of not needed mounts (and I suspect something is going on under `/etc` so just remove that as we chroot into rootfs anyway.

Small fixes + remove not needed mounts

---

docs/README.md

Responsibly disclose security issues.

README.md: add Security Response section

---

pkg/daemon/daemon.go
pkg/daemon/update.go

Added command output logging on error to help debug bugzilla#1708602

Bug 1708602: pkg/daemon: log cmd output on error

---

.github/ISSUE_TEMPLATE.md

update issue template to link to security response

---

pkg/daemon/update.go

we don't need a goroutine to write to a process' stdin, just attach a buffer to it

pkg/daemon: attach stdin directly

---

pkg/daemon/update.go
pkg/daemon/update_test.go

It's really useful to see in the logs explicitly when the osImageURL
changes and the files change (or didn't).
Eventually we should try to get a real diff and consider only
applying that.

daemon: Log high level diff between MCs

---

pkg/daemon/daemon.go

removed a really high spammy logSystem call
check daemon logs in jobs

Bug 1709907: pkg/daemon: drop spammy logSystem

---

pkg/daemon/daemon.go
pkg/daemon/update.go

Cherry-pick of commits from #734 - that PR has been missed from the branching somehow but we need that to verify the linked BZ.
@imcleod ptal

[release-4.1] Bug 1708602: pkg/daemon: workaround old util-linux logger in rhel7.6

---

pkg/daemon/update.go
pkg/daemon/update_test.go

It's basically doing a "diff of Ignition configs" and also filtering
by "changes the MCD supports".  There's nothing here that needs
anything in the daemon state.
Prep for use in the controller, so we can warn/error before
we even try to roll out changes to the nodes.

 daemon: Export Reconcilable as free function

---

hack/cluster-push-prep.sh
pkg/server/api.go

This is very useful for debugging, and is prep for adding
further auditing.

 server: Add a log message when a pool is requested

---

docs/OnceFrom.md

Added link to `hacking.md` file inside the `OnceFrom.md` file

docs: Add link in the OnceFrom md file to hacking.md

---

pkg/server/testdata/machine-configs/test-config.yaml
templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/master/01-master-kubelet/openstack/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/openstack/units/kubelet.yaml

Just a few things I saw while looking at kubelet logs.  Lightly tested by making interactive edits to a worker.

Kubelet config fixes

---

docs/HACKING.md
docs/README.md

Docs: Fix dead links in docs (and some typos)

---

docs/HACKING.md

Substituted usage of 4.1 in examples with a placeholder and a note.
Minor cleanup of language in doc to simplify.
as per our conversion yesterday, @runcom

docs: remove refs to 4.1 in examples & cleanup language

---

docs/README.md

Just did a quick pass through the doc again.

README.md: Small tweaks

---

docs/HACKING.md

Some quick additions/fixes to HACKING.md
Docs: Clean up hacking readme and add example podman commands

Docs: Clean up hacking readme and add example podman commands

---

install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
test/e2e/etcdquorumguard_test.go

Merged part of #764 and all of #789 
Run e2e test
etcd quorum guard test does not correctly make nodes unschedulable

Bug 1713039: etcd quorum guard test does not correctly make nodes unschedulable

---

OWNERS

OWNERS: add Erica

---

pkg/controller/template/render.go

Cleaned up some code and comment blocks.
Clean up code and comment blocks in pkg/controller.

pkg/controller: Clean up template rendering code

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go
pkg/daemon/daemon_test.go

Just some more cleanups in prep for having the MCD process machineconfig early at start in a "once from" like mode.

Daemon more cleanups

---

docs/HACKING.md

For cri-o developers at the moment but we also mention the kernel
here, etc.

HACKING.md: Doc `machine-os-content` development a bit more

---

pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
pkg/apis/machineconfiguration.openshift.io/v1/helpers_test.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/render/render_controller_test.go
pkg/controller/template/status.go
pkg/controller/template/template_controller_test.go

Fixed ControllerConfigStatusConditionType typos by adding the missing r in TemplateContoller status conditions
CI

Fix ControllerConfigStatusConditionType typos

---

.golangci.yml
pkg/operator/sync.go

golangci: Enable dupl check

---

test/e2e/mcd_test.go

I actually just discovered the `require` package is what I really
wanted, make use of it in more places so we consistently panic
rather than stumbling on in some cases, and we don't need to duplicate
`err`, it's 1 line instead of 3 etc.

test/e2e: More use of assert/require

---

OWNERS

Remove my name from `OWNERS` to reflect reality. The bot wants me to
provide reviews, but it's been a while now since I've really worked on
this codebase.

OWNERS: drop jlebon

---

pkg/operator/operator.go
pkg/operator/sync.go
test/e2e/mcd_test.go

Correctly look for the right MCP status conditions instead of the generic Degraded
First commit just cleanup some stuff, no biggie

test/e2e: correctly check MCP status condition

---

examples/controllerconfig.crd.yaml
examples/machineconfig.crd.yaml
examples/machineconfigpool.crd.yaml
install/0000_80_machine-config-operator_01_mcoconfig.crd.yaml
manifests/controllerconfig.crd.yaml
manifests/machineconfig.crd.yaml
manifests/machineconfigpool.crd.yaml
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/operator/assets/bindata.go

Fix a liar's paradox in our code. This is not a crusade, so I'm sparing vendored files.

CamelCase -> PascalCase

---

pkg/controller/node/status.go

Cleaned up some inaccurate / hard to follow function doc strings.
Fix doc strings in pkg/controller node status

pkg/controller: Fix up node status.go docs

---

pkg/operator/assets/bindata.go

Updated bin data

---

hack/cluster-push.sh

There are other things I want to do with this script, but at
least it works again.

hack/cluster-push: Fix for single image

---

pkg/operator/status.go

During `syncRequiredMachineConfigPools` we're not reporting node errors
and if something like pivot fails it's not immediately visible at
installation time for instance. Bubble up the pool status to make that
visible.

pkg/operator: bubble up errors from pools

---

docs/MachineConfiguration.md

The plus side is, on the Internet, no one can see you crying while writing a commit message.

docs: Note restrictions/bugs in kargs

---

test/e2e/mcd_test.go

There has been a lot of interest around custom pools lately and it does make sense to cover the flow with an e2e to avoid regressions.
CI

test/e2e: add custom pool test

---

OWNERS_ALIASES

OpenStack: update approvers

---

pkg/daemon/daemon.go

Quick comment typo fixes in `pkg/daemon/daemon.go`. 
pkg/daemon: daemon.go comment fixes

pkg/daemon: daemon.go comment fixes

---

templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
templates/master/00-master/_base/files/usr-local-share-openshift-recovery-template-etcd-generate-certs-yaml-template.yaml

This change improves DR by covering changes of image unification.
ref: https://github.com/openshift/machine-config-operator/pull/1028
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1742744

BUG 1742744: DR: set command for setup-etcd-environment

---

pkg/controller/container-runtime-config/helpers.go
pkg/controller/container-runtime-config/helpers_test.go

`RepositoryDigestMirrors` configuration with mirrors listing only the source (like in the added test case) was causing a panic; fix that.
The added unit test.
Fixed a panic in a corner case of ImageContentSourcePolicy mirror configuration.

Bug 1745767: Fix a corner case in mergedMirrorSets

---

cmd/setup-etcd-environment/run.go

etcd has no limitations to the architecture that the binary is compiled with (assuming it can compile). But it does require the environment variable `ETCD_UNSUPPORTED_ARCH` to be populated with the arch at runtime if that architecture is not supported upstream[1]. This PR adds support for OpenShift etcd to run s390 and s390x binaries required for IBM Z.
[1] https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/supported-platform.md
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1747124
Signed-off-by: Sam Batschelet <sbatsche@redhat.com>

BUG 1747124: cmd/setup-etcd-environment: add support for s390, s390x arch

---

pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-sysctl.d-inotify.conf
pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-sysctl.d-inotify.conf
pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-sysctl.d-inotify.conf
pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-sysctl.d-inotify.conf
pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-sysctl.d-inotify.conf
pkg/controller/template/test_data/templates/worker/00-worker/aws/files/-etc-sysctl.d-inotify.conf
pkg/controller/template/test_data/templates/worker/00-worker/libvirt/files/-etc-sysctl.d-inotify.conf
pkg/controller/template/test_data/templates/worker/00-worker/none/files/-etc-sysctl.d-inotify.conf
pkg/controller/template/test_data/templates/worker/00-worker/openstack/files/-etc-sysctl.d-inotify.conf
pkg/controller/template/test_data/templates/worker/00-worker/vsphere/files/-etc-sysctl.d-inotify.conf
templates/master/00-master/_base/files/sysctl-inotify.conf.yaml
templates/worker/00-worker/_base/files/sysctl-inotify.conf.yaml

Cherrypicks: #1063
Closes: BZ 1745016
cc: @runcom

Bug 1745016: [release-4.1] add base templates with default inotify.max_user settings

---

templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml

Update maximum number of concurrent connections and backend's health check
stabilization time.

Bug 1748807: tuning of API LB configuration parameters

---

docs/PullSecret.md

Add a note about nodes rebooting, including master nodes.

docs: fix up PullSecret text

---

docs/ContainerRuntimeConfigDesign.md
docs/HACKING.md
docs/KubeletConfigDesign.md
docs/MachineConfigController.md
docs/MachineConfiguration.md
docs/Update-SSHKeys.md
pkg/daemon/daemon.go

Note: this probably shouldn't be merged until master is branched for `4.3`
Fix various docs/comments and add snippet to test a release image.
Fix various formatting errors and typos in docs.

docs: fix up doc discrepancies

---

manifests/baremetal/coredns-corefile.tmpl
manifests/baremetal/coredns.yaml
pkg/operator/assets/bindata.go
templates/common/baremetal/files/baremetal-coredns-corefile.yaml
templates/common/baremetal/files/baremetal-coredns.yaml

Inherit changes from Openstack PR (#1164)

Baremetal - change coredns healthcheck port 8080->18080

---

docs/HACKING.md
docs/README.md

docs: add go version & FAQ link

---

docs/FAQ.md

docs/FAQ.md: Add one about workers

---

Dockerfile
Makefile

Smaller parts of https://github.com/openshift/machine-config-operator/pull/946

Build dockerfile cleanup

---

pkg/controller/kubelet-config/kubelet_config_controller.go

Backports #1069 to release-4.1 to not requeue the `errCouldNotFindMCPSet` error.

BUG 1762344: backport 1069: Do not requeue a failed kubeletconfig decode

---

pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/none/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/vsphere/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vsphere/units/kubelet.service
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

Fixes: 1741608
Cherrypick of #772

Bug 1741608: logs are flooded with "failed to get pod stats: failed to get imageFs info: non-existent label "crio-images"" messages

---

OWNERS

Adding myself to OWNERS list in `fcos` branch only to speed up development

[fcos] Add vrutkovs to OWNERS

---

templates/common/_base/units/machine-config-daemon-pull.service

* Use pull request to pull MCO image
* Fix path to restorecon

[fcos] Fix mcd pull service

---

manifests/machineconfig.crd.yaml
pkg/operator/assets/bindata.go

Better CRD validation via OpenAPIV3 schema. Taken from https://github.com/coreos/ignition/blob/spec2x/schema/ignition.json

machineconfig.crd.yaml: add passwd schema

---

docs/HACKING.md

Also other minor updates in HACKING doc

docs: Update make target to build individual binaries

---

pkg/daemon/update.go

Fix up the previous FIPS patch by moving the FIPS check for the
system to reconcilable. This way we can detect a change to the
FIPS flag much earlier and fail.
The check for FIPS is still comparing FIPS on the system to the
desiredConfig. In a perfect world currentConfig would be the
correct check, but currently this seems to be failing for
firstboot scenarios.
-->
Move the FIPS check to earlier in the update process
Run a normal (FIPS=false) cluster, apply a machineconfig to turn it on, watch it fail trying to reconcile

daemon/FIPS: move check to reconcilable

---

install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1772155
add proper terminationMessagePolicy for etcd quorum guard pods

Bug 1772155: install: add proper terminationMessagePolicy for etcd quorum guard pods

---

templates/common/_base/files/etc-zincati-config.d-90-disable-feature-toml.yaml

Zincati would hit FCOS servers and update machines.
/cc @LorbusChris @smarterclayton

Disable Zincati on masters/workers

---

OWNERS

Removed 'LorbusChris' from the OWNERSFILE
N/A
Remove old team member

OWNERSFILE: remove lorbuschris

---

docs/FAQ.md

Describe our relationship with machine API a bit.

FAQ: So many machine thingys

---

templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

Cleaned up and commented recent changes for readability and easier troubleshooting.
Backup etcd and restore it as described in the OCP documentation.
Clean up of backup and restore DR scripts.

DR: Cleanup and comment backup and restore scripts

---

Makefile
pkg/daemon/update.go

Make code able to run on osx especially for units

test: fix units to run on osx

---

test/e2e/mcd_test.go

Attempt to include e2e test for kernelType

test/e2e - Add e2e test for Realtime Kernel

---

test/e2e/mcd_test.go

Initially in e2e test for [kernelType](https://github.com/openshift/machine-config-operator/pull/1407),  we created a MachineConfig with `kerneltype:realtime`  to switch to Real Time kernel.
For better test coverage, we are now also making sure that switching back to `default` kernel also works fine. We are testing this by deleting the Real Time MachineConfig we applied earlier.

test/e2e: Add rollback test for kernelType

---

pkg/controller/kubelet-config/kubelet_config_controller.go

This PR changes the KubeletConfig finalizer name to be the Machine Config UID. Finalizer names are restricted to 63 characters, so machine names impact if the kubelet config finalizer will be set.
The change preserves backwards compatibility by attempting the deletion of the MachineConfig by name, then falling back to Listing the machineconfigs and finding the UID that matches.
```
KubeletConfig finalizers have changed to using the MachineConfig UID.
```

Bug 1787907: use the machine config uid for the kubeletconfig finalizer name

---

templates/master/00-master/baremetal/files/baremetal-haproxy.yaml

[IPI][BAREMETAL] Add CPU and memory resources for Haproxy pod
Fixes: 1777379

Bug 1777379: [Baremetal] add CPU and memory resources for Haproxy pod

---

cmd/machine-config-operator/bootstrap.go
lib/resourcemerge/machineconfig.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
pkg/operator/bootstrap.go
pkg/operator/sync.go
templates/common/_base/files/cloud-provider-ca.yaml

[release-4.3] Bug 1796822: Support deployment on OpenStack with self-signed certificate

---

cmd/setup-etcd-environment/run.go
templates/common/_base/files/sysctl-forward-conf.yaml
templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml

release-4.3 backport of PR #1211

Bug 1785718: [release-4.3] etcd: Add initial support for an IPv6 control plane

---

pkg/daemon/daemon.go
pkg/operator/sync.go

Closes #1480 
Enable CEO testing - return early when validating the file CEO cares about
@deads2k @kikisdeliveryservice

Bug 1803986:Revert 1473 and skip etcd-member.yaml validation

---

templates/common/baremetal/files/NetworkManager-mdns-hostname.yaml
templates/common/baremetal/files/baremetal-mdns-publisher.yaml

Cherry pick of :
3e39a8f8278e5bb7a8965173dd1f73474e8fdac8 
and 
5961218222f94d07a73586fdcb4b184183f4939f

Bug 1802675: [release-4.3] baremetal: Verify that mdns start only after hostname was set 

---

templates/master/00-master/_base/files/usr-local-bin-etcd-member-add-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-member-remove-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-tokenize-signer-sh.yaml

The changes needed to make DR scripts functional with the introduction of CEO.
Run DR scripts as documented in openshift-docs.
Fix DR scripts to make them work in conjunction with CEO.

Bug 1797989: Changes to fix DR scripts with new CEO environment and manifests

---

pkg/daemon/daemon.go
pkg/daemon/osrelease.go
pkg/daemon/update.go

Prep for supporting Fedora CoreOS as base OS.

Add machineConfigDaemonOSFCOS

---

docs/ContainerRuntimeConfigDesign.md
docs/KubeletConfigDesign.md

The ctrcfg and kubeletecfg instructions are missing several steps that makes it confusing for users to follow. This PR enumerates  all steps for both and hopefully clarifies the process for users.

docs: update ctrcfg &kubeletcfg instructions

---

templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

Fix runtimeCgroups/--runtime-cgroups Kubelet option

Bug 1817173: Move non-existant runtimeCgroups kubelet option to flag

---

pkg/controller/bootstrap/testdata/bootstrap/99_openshift-machineconfig_master.yaml
pkg/controller/bootstrap/testdata/bootstrap/99_openshift-machineconfig_worker.yaml
pkg/controller/template/render.go
pkg/daemon/update.go
pkg/server/testdata/machine-configs/test-config.yaml

Avoid soon-to-be invalid v3.1.0-experimental

[FCOS] Use v3.0.0 for Ignition templates

---

templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

This is a manual cherry-pick of #1540 and #1580

Bug 1811720: Specify cgroups in kubelet.conf so cAdvisor stats will be tracked

---

templates/master/00-master/_base/files/recycler_pod.yaml

Added template for recycler pod.
This should create a new file in `/etc/kubernetes/manifests/recycler-pod.yaml`.
CC @openshift/storage

Bug 1805908: Add template for recycler pod

---

install/0000_80_machine-config-operator_01_machineconfig.crd.yaml

Forward-port of https://github.com/openshift/machine-config-operator/pull/1698

Bug 1829138: MC CRD: preserve unknown fields

---

docs/MachineConfiguration.md

This is needed only on 4.2 based cluster

Bug 1766346: docs: Workaround to properly apply kargs on new nodes created by machine-api

---

templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
templates/common/vsphere/files/vsphere-coredns-corefile.yaml
templates/common/vsphere/files/vsphere-coredns-db.yaml
templates/common/vsphere/files/vsphere-coredns.yaml
templates/common/vsphere/files/vsphere-keepalived.yaml
templates/common/vsphere/files/vsphere-mdns-publisher.yaml
templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
templates/worker/00-worker/vsphere/files/vsphere-mdns-config.yaml
templates/worker/00-worker/vsphere/files/vsphere-non-virtual-ip.yaml

Bug 1834194: vsphere: check if .Infra.Status and .Infra.Status.PlatformStatus is nil

---

OWNERS_ALIASES
templates/common/openstack/OWNERS
templates/master/00-master/openstack/OWNERS
templates/master/01-master-container-runtime/openstack/OWNERS
templates/master/01-master-kubelet/openstack/OWNERS
templates/worker/00-worker/openstack/OWNERS
templates/worker/01-worker-container-runtime/openstack/OWNERS
templates/worker/01-worker-kubelet/openstack/OWNERS

Also remove former approvers.
/cc mandre iamemilio

Add OpenStack reviewers

---

docs/HACKING.md

HACKING.md: Note that the machine-os-content must be digested

---

OWNERS

Removed the rest of the team to avoid unnecessary review requests

[FCOS] add vrutkovs and LorbusChris to owners

---

cmd/machine-config-daemon/pivot.go
docs/ContainerRuntimeConfigDesign.md
docs/KubeletConfigDesign.md
pkg/controller/kubelet-config/kubelet_config_controller_test.go

*: Use {allow,deny}list vocabulary

---

test/e2e/old-bootimages.sh

I *think* the Prow job may have died on `oc debug node` wanting
to parse stdin or something.
But while trying to debug this I added a `sleep 4m` invocation
so we have less spam about waiting for the node objects; we
know provisioning is very unlikely to be faster than 4 minutes
today (unfortunately).

test/e2e/old-bootimages: Some tweaks to hopefully fix Prow

---

go.mod
manifests/etcdquorumguard_deployment.yaml
manifests/machineconfigdaemon/daemonset.yaml
pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/daemon/daemon.go
pkg/daemon/update.go
pkg/operator/assets/bindata.go
templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
templates/master/01-master-kubelet/baremetal/units/kubelet.service.yaml
templates/master/01-master-kubelet/openstack/units/kubelet.service.yaml
templates/master/01-master-kubelet/vsphere/units/kubelet.service.yaml
templates/worker/00-worker/baremetal/files/baremetal-keepalived-keepalived.yaml
templates/worker/00-worker/openstack/files/openstack-keepalived-keepalived.yaml
templates/worker/00-worker/ovirt/files/ovirt-keepalived-keepalived.yaml
templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml

/cc @LorbusChris 
Procedure:
```
$ TARGET_COMMIT=$(git describe --tags fcos | sed 's/.*-//')
$ git checkout -b fcos-rebase-jun23 origin/release-4.5
$ git rebase --onto fcos $TARGET_COMMIT
```

[FCOS] Periodic rebase on release-4.5 branch

---

pkg/controller/common/helpers.go

When Ignition2 files are converted to Ignition3 we have to ensure no files are duplicated. This commit would rewrite previous versions of the file with the latest content.
Fixes https://github.com/openshift/okd/issues/237

[fcos] pkg/controller/common/helpers: replace duplicate files in ConvertIgnition2to3

---

install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml

Made the following changes as settings were not getting
picked up:
- move and correct initialDelaySeconds and periodSeconds
- reorder container sub-elements to nest image under name
- add failureThreshold and timeoutSeconds
Closes: BZ 1845635

[release-4.4] Bug 1845635: etcd-quorum-guard: update containers section in deployment.yaml

---

pkg/daemon/update.go

Manual backport of https://github.com/openshift/machine-config-operator/pull/1781 to fix conflict

Bug 1845492: daemon: fix restoring file logic to avoid unnecessary deletion

---

Dockerfile
Dockerfile.rhel7
Makefile

[fcos] Update base image in Dockerfile

---

test/e2e/mcd_test.go

Delete unneeded commented out lines.

test/e2e: cleanup - remove commented out lines

---

pkg/controller/common/helpers.go

Default to spec 3 for the return type, and clarify error messages,
so the user has a better sense of what went wrong in MCC logs.
Mostly useful for MachineConfig manifests provided during install
that have errors in them.

IgnParseWrapper: return better errors

---

manifests/baremetal/keepalived.yaml
pkg/operator/assets/bindata.go
templates/common/baremetal/files/baremetal-keepalived.yaml

Set Keepalived default mode to unicast for Baremetal case

[Baremetal] Set Keepalived default mode to unicast

---

pkg/server/api.go

This is for people using e.g. curl to retrieve Ignition config from the MCS (a few people have had this issue, e.g. here: https://github.com/openshift/okd/issues/239#issuecomment-665737901)
/cc @vrutkovs

[OKD] api: Serve spec v3.1 by default for non-Ignition user agents

---

manifests/baremetal/coredns-corefile.tmpl
pkg/operator/assets/bindata.go
pkg/operator/sync.go
pkg/operator/sync_test.go
templates/common/_base/files/etc-networkmanager-dispatcher.d-90-long-hostname.yaml
templates/common/_base/files/usr-local-sbin-set-valid-hostname.yaml
templates/common/_base/units/node-valid-hostname.service
templates/common/baremetal/files/baremetal-coredns-corefile.yaml
templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

Rebase fcos on latest commits from release-4.5
TARGET_COMMIT=$(git describe --tags fcos | sed 's/.*-g//')
git checkout -b fcos-rebase-jul06 origin/release-4.5
git rebase --onto fcos $TARGET_COMMIT

[fcos] rebase jul06

---

docs/HACKING.md

This is to enable developers looking to test/run customized kubelet on an openshift cluster
Signed-off-by: Swati Sehgal <swsehgal@redhat.com>

Capturing steps to run customized kubelet on Openshift worker nodes

---

docs/HACKING.md

I ran into this question while verifying #1960, so let's document it

HACKING: add example for talking to MCS via curl

---

pkg/controller/kubelet-config/helpers.go
pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/controller/kubelet-config/kubelet_config_controller_test.go
templates/common/_base/files/iptables-modules.yaml
templates/common/vsphere/files/vsphere-hostname.yaml
templates/common/vsphere/units/vsphere-hostname.service.yaml

Rebase fcos on latest commits from release-4.5
TARGET_COMMIT=$(git describe --tags fcos | sed 's/.*-g//')
git checkout -b fcos-rebase-aug12 origin/release-4.5
git rebase --onto fcos $TARGET_COMMIT

[FCOS] Rebase Aug 12

---

pkg/daemon/update.go

We handle rpm-ostree operations such as OS update,
karg update, kernel switch and additional package
overlay in applyOSChanges(). When an error occurs
during any one of these operations, we would want
to rollback any changes we have performed on booted
OS so that we can cleanly retry again to apply
the changes. rpm-ostree provides us `cleanup -p`
options which removes pending deployment.

Bug 1865839: daemon: cleanup pending deployment on an error

---

cmd/machine-config-daemon/pivot.go
pkg/daemon/daemon.go
pkg/daemon/rpm-ostree.go
pkg/daemon/update.go

Manual backport of https://github.com/openshift/machine-config-operator/pull/2029

Bug 1873383: daemon: perform other rpm-ostree operations after OS rebase

---

docs/MachineConfigDaemon.md
docs/MachineConfiguration.md

Additional documentation updates for Ignition spec 2/3 dual support.

Bug 1879409: docs: Update for Ignition spec 2/3 dual support

---

pkg/daemon/daemon.go

Bringing up a RHEL7 node requires the ansible playbook to fetch the
ignition config from the MCS and the run the MCD in onceFrom mode.
We want the encapsulated MC file to be unconditionally removed on RHEL
nodes, thus in onceFrom we can just rm the file.
The problem is we were deleting the file before the onceFrom mode wrote
the file itself, resulting in the file always being there.
This patch moves the removal _after_ the onceFrom writes all files from
ignition, including the encapsulated path, that we'll later now remove.
Just a note that leveraging that file isn't something the MCO advertises or exposes as an API to derive any kind of logic like the OVN components imply. That's just wrong and from now on, unsupported. I'll work with them to find another way.
Signed-off-by: Antonio …

Bug 1882667: pkg/daemon: rm the encapsulated mc at the right time

---

docs/FAQ.md

Came up a few times, weave together some of the issue threads here.

FAQ: Discuss changing partitioning

---

docs/OSUpgrades.md

A few things that have come up.

OSUpgrades.md: Expand question/answer section

---

docs/custom-pools.md

This came up in chat, let's explain the "one pool per node" bit
as well as the concurrency.

docs/custom-pools: Describe a little about nodes and pools and updates

---

docs/OSUpgrades.md

In the spirit of writing down more of the internals.  Motivated
by the recent bug with spec3 transition.

docs/OSUpgrades: Doc /etc/ignition-machine-config-encapsulated.json

---

install/0000_80_machine-config-operator_00_clusterreader_clusterrole.yaml
install/0000_80_machine-config-operator_00_namespace.yaml
install/0000_80_machine-config-operator_00_service.yaml
install/0000_80_machine-config-operator_01_containerruntimeconfig.crd.yaml
install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
install/0000_80_machine-config-operator_01_machineconfig.crd.yaml
install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml
install/0000_80_machine-config-operator_02_images.configmap.yaml
install/0000_80_machine-config-operator_03_rbac.yaml
install/0000_80_machine-config-operator_04_deployment.yaml
install/0000_80_machine-config-operator_05_osimageurl.yaml
install/0000_80_machine-config-operator_06_clusteroperator.yaml
install/0000_90_machine-config-operator_00_servicemonitor.yaml
install/0000_90_machine-config-operator_01_prometheus-rules.yaml

This is matches openshift/enhancements#510 and doesn't change existing behavior

add current profile annotations to CVO manifests

---

pkg/controller/kubelet-config/helpers.go

This adds the same validation resource validation for EvictionHard limits within the KubeletConfiguration.

Bug 1891460: kubelet: add eviction hard validation

---

docs/FAQ.md

A question came up in Slack about using the MCO with RHEL worker
nodes, so this tries to answer the question.

FAQ: add entry about RHEL worker nodes

---

OWNERS_ALIASES

owners: Add mdbooth to approvers

---

docs/FAQ.md

Motivated by https://bugzilla.redhat.com/show_bug.cgi?id=1896751

FAQ: Add a "debugging node join" section

---

templates/common/_base/units/nodeip-configuration.service.yaml

backport of https://github.com/openshift/machine-config-operator/pull/2199
/cc @danwinship @knobunc @cgwalters @vrutkovs

[release-4.6] Bug 1894483: Fix bash in nodeip-configuration.service

---

templates/common/baremetal/files/NetworkManager-static-dhcpv6.yaml

This is essentially an ipv6 version of #2188.
Co-authored-by: Antoni Segura Puimedon <antoni@redhat.com>

[baremetal] Add ipv6 support to static DHCP configuration

---

templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

Cherry pick of https://github.com/openshift/machine-config-operator/pull/2211

[release-4.5] Bug 1900013: Drop kubelet logging back down to level 3

---

install/0000_80_machine-config-operator_00_clusterreader_clusterrole.yaml
install/0000_80_machine-config-operator_00_namespace.yaml
install/0000_80_machine-config-operator_00_service.yaml
install/0000_80_machine-config-operator_01_containerruntimeconfig.crd.yaml
install/0000_80_machine-config-operator_01_kubeletconfig.crd.yaml
install/0000_80_machine-config-operator_01_machineconfig.crd.yaml
install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml
install/0000_80_machine-config-operator_02_images.configmap.yaml
install/0000_80_machine-config-operator_03_rbac.yaml
install/0000_80_machine-config-operator_05_osimageurl.yaml
install/0000_90_machine-config-operator_01_prometheus-rules.yaml

This matches https://github.com/openshift/enhancements/pull/445 and does
not change behavior.

Add IBM Cloud managed annotations to CVO manifests

---

pkg/daemon/update.go

Check dropin content for nil pointer and content.

Bug 1918415: check dropins for nil-pointers

---

pkg/daemon/update.go

 [release-4.6] Bug 1893409: daemon: add back metrics for pivot error

---

pkg/daemon/update.go
pkg/daemon/update_test.go

Still WIP bc I'd like to do more testing but this seems like a better approach in line with MCO rules

Bug 1885186: handle Passwd.Users removal more gracefully

---

OWNERS

With gratitude and best wishes for @runcom's new grand adventure, this removes Antonio from the owner's file. 
(Per his request)

OWNERS: drop @runcom with gratitude

---

install/0000_90_machine-config-operator_01_prometheus-rules.yaml
pkg/daemon/metrics.go
pkg/daemon/update.go

Cherry-pick of #2044
Replaces #2292

[release-4.6] Bug 1906298: update MCDDrainErr to reduce cardinality & fix nodename

---

pkg/operator/status.go
pkg/operator/sync.go

To help with debugging [rhbz#1932105][1], which we're still seeing in CI.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1932105

Bug 1932105: pkg/operator/sync: More logging for syncRequiredMachineConfigPools

---

pkg/daemon/update.go
pkg/daemon/update_test.go
pkg/operator/bootstrap.go
pkg/operator/sync.go

Manual backport of https://github.com/openshift/machine-config-operator/pull/2398. See https://bugzilla.redhat.com/show_bug.cgi?id=1921894 for the main bug

Bug 1939278: Backport kubelet CA no-drain rotation

---

pkg/controller/container-runtime-config/helpers.go

Fixes #1825417 (https://bugzilla.redhat.com/show_bug.cgi?id=1825417)
Instead of relying on the order in which the ctrcfg
objects are added to the list, let's go through the
list and find the maximum suffix value used. We can
then add 1 to the max suffix value to be used for the
MC when creating the new ctrcfg object.
Create multiple ctrcfg CRs and a new MC with a different suffix will be created for each one.

Bug 1825417: Make getting the suffix of an MC more robust

---

templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml

Bug 1940950: Strengthen kubelet service dependency on crio service

---

templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml

Bug 1943145: Strengthen kubelet service dependency on crio service

---

OWNERS_ALIASES

Hopefully this will help get more eyes on vSphere-specific changes
and spread the load on reviews.

vSphere: Update reviewers and approvers

---

docs/ContainerRuntimeConfigDesign.md
install/0000_80_machine-config-operator_01_containerruntimeconfig.crd.yaml

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1944986
Update Docs for ContainerRuntimeConfig to warn the user about validation 
CRD for ContainerRuntimeConfig should reflect the updated validation related information. 
Update ContainerRuntimeConfig docs on validation

Bug 1944986: Doc fix for ContainerRuntimeConfig CR

---

cmd/apiserver-watcher/run.go

apiserver-watcher support for dual-stack
The apiserver-watcher monitors the local apiserver, and indicates
the gcp-routes.sh scripts the status of the apiserver VIP, so it
can install the corresponding iptables rules to REDIRECT the
traffic to the local apiserver instance.
On dual-stack environments, the apiserver url can resolve to multiple
IPs, one per IP family.
The apiserver-watcher must send to the gcp-route script each of the
resolved addresses, so those can be reachable in all the IP families.
Signed-off-by: Antonio Ojea <aojea@redhat.com>

Bug 1949347: apiserver-watcher support for dual-stack

---

docs/MachineConfigDaemon.md
docs/MachineConfiguration.md
docs/PullSecret.md
docs/SingleNodeOpenShift.md

Closes: https://issues.redhat.com/browse/GRPA-3225
Documents high availability (HA) behavior and what causes reboots and other disruptions
Documents high availability (HA) behavior and what causes reboots and other disruptions

Bug 1950543: document non-HA behaviors

---

pkg/daemon/update.go

MCO doesn't support rpm-ostree related operation on RHEL
nodes like KernelType change, extensions. Instead of returning
error, log message and return nil so that nodes don't go
degraded and block updates for the rest of the
nodes in the pool.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1952368

Bug 1952368: daemon: return nil for unsupported operation on an OS

---

pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/controller/kubelet-config/kubelet_config_controller_test.go

Close: Bug 1950133 https://bugzilla.redhat.com/show_bug.cgi?id=1950133
Add cleanUpStatus method to keep a limited number of conditions of different
timestamps. The list keeps the three latest conditions. Updates only the timestamp
if the new status condition stays the same as the last condition.
fix the bug MCO creates empty conditions on the kubeletconfig object

Bug 1950133: Add cleanupStatus to keep three kubelet config conditions

---

test/e2e/kubeletcfg_test.go

Closes: https://issues.redhat.com/browse/OCPNODE-547
Add e2e for auto node sizing

Bug 1954554: add e2e for auto node sizing

---

pkg/daemon/update.go

Due to conflict, this is a manual backport of PR https://github.com/openshift/machine-config-operator/pull/2542

Bug 1953493: daemon: return nil for unsupported operation on an OS

---

Makefile
install/0000_90_machine-config-operator_01_prometheus-rules.yaml
pkg/daemon/metrics.go
pkg/daemon/update.go

Manual backport of https://github.com/openshift/machine-config-operator/pull/2597

[release-4.7] Bug 1968759: Bump drain timeout to 1h 

---

pkg/daemon/drain.go

Made the first five tries 1min after that you have problems so need more time.

Bug 1971080: daemon/drain.go: bump initial drain sleeps down to 1min

---

pkg/daemon/update.go

Manual backport of https://github.com/openshift/machine-config-operator/pull/2611

[release-4.7] Bug 1971374: daemon/drain.go: bump initial drain sleeps down to 1min

---

Dockerfile
docs/HACKING.md
go.mod
go.sum
vendor/modules.txt

Also, 
keep Dockerfile in sync with ART Dockerfile, see https://github.com/openshift/machine-config-operator/pull/2621

 go.mod: switch to Go 1.16

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

[release-4.8] Bug 1995809: crio: complete crio default config

---

test/e2e-single-node/sno_mcd_test.go

Now that SNO performance issue with rt-kernel has been
resolved https://bugzilla.redhat.com/show_bug.cgi?id=1994879 ,
We should be able to test this in our ci for Single Node OpenShift.

Bug 1999593: e2e-single-node: add test for rt-kernel switch

---

templates/common/_base/files/configure-ovs-network.yaml

Cherry-pick of #2626 & #2643 & #2706 & #2704
/assign jcaamano

[release-4.8] Bug 1976110: configure-ovs: fix nondeterministic master in slave profiles

---

hack/build-image

I need this to run the script on NixOS

Use env instead /usr/bin/bash

---

pkg/daemon/drain.go
pkg/daemon/drain_test.go
pkg/daemon/update.go
pkg/daemon/update_test.go

Instead of passing machine configs that must be parsed, just pass the
already parsed Ignition configs

Pass parsed Ignition config to updateFiles

---

docs/MachineConfigController.md
install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml
pkg/apis/machineconfiguration.openshift.io/v1/types.go

Update the CRD description as well as inline comments/docs, so users
looking to use maxUnavailable can better understand some nuances.

Make maxUnavailable description more detailed

---

pkg/controller/common/helpers_test.go
pkg/daemon/daemon.go
pkg/daemon/update.go
pkg/daemon/update_test.go

Bug 1970218: Support compressed files for updates

---

templates/master/00-master/on-prem/files/keepalived-keepalived.yaml
templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml

Manual backporting of:
https://github.com/openshift/machine-config-operator/pull/2794
https://github.com/openshift/machine-config-operator/pull/2578

Bug 2024511: [release-4.8] [on-prem] Manual backporting of keepalived arp retries

---

pkg/daemon/update.go

Empty systemd units should ensure no files exist for that unit
This fixes edge cases such as when a previous symlink to /dev/null is
never removed, which inappropriately continues to mask the unit
Closes: #1966445

Bug 1966445: Cleanup systemd unit files for empty units

---

OWNERS

Includes existing approvers and new members in MCO team

owners: add reviewers for MCO repo

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

Bug 2028802: crio: fix a segfault on 4.9->4.10 upgrade

---

pkg/controller/common/helpers.go
pkg/controller/common/helpers_test.go

Fixes: #2038240
Added some additional validation logic to the Ignition 2 / 3 config validators to check that file mode values for any file do not exceed 0777. This is because setting special file mode bits (sticky, setuid, setgid) will not have the desired effect because `os.Chmod()` discards anything past the first 9 bits of a file mode.
For example, `01777` becomes `0777`. This breaks config drift detection because the MachineConfig specifies that the file should have mode `01777`, but the on-disk state is `0777` because of the aforementioned behavior.
1. On an OCP cluster, apply the following MachineConfig:
```yaml
metadata:
labels: …
```

Bug 2038240: Error if files have special bits set

---

templates/common/_base/files/configure-ovs-network.yaml

This is a cherry-pick of:
* 47957d7e: Improvements for configure-ovs script
* 7a5d2996: configure-ovs: cleanup leftovers from previous run
* 6528d2d: Configure-ovs: Ensure DHCP finishes for both address families
* af7b491: Use ip command to check for ipv4/v6 addresses

[release-4.8] Bug 2062655: Improvements for configure-ovs script

---

templates/common/_base/files/configure-ovs-network.yaml

Cherry-pick of #3024 [e43a9f2](https://github.com/openshift/machine-config-operator/pull/3024/commits/e43a9f216937df5b0fc9c744be78687ac38c21f2)

[release-4.10] Bug 2070492: configure-ovs: move dhcp config from br-ex to ovs-if-br-ex

---

pkg/controller/node/node_controller.go
pkg/daemon/daemon.go
pkg/daemon/osrelease.go
pkg/daemon/update.go

Layered updates are not possible on non-CoreOS nodes

check that layered nodes use CoreOS

---

docs/DemoLayering.md

We iterated on docs for the current state of things, update
this git repo with the current from hackmd.

docs/DemoLayering: Update with snapshot from hackmd

---

pkg/daemon/daemon.go

I'm debugging https://bugzilla.redhat.com/show_bug.cgi?id=2075126
and I find our handling of the `state` variable a bit suspicious.
Unfortunately...we don't log this in the default daemon logs
and it would have been *very* useful to have that because it is
input to a key bit of control flow today - if the state is not `done`
then we try to perform an update between config A and config A which
smells like a bug to me.

daemon: Add some logging for state

---

templates/common/_base/files/configure-ovs-network.yaml

Cherry pick of #3005 https://github.com/openshift/machine-config-operator/commit/dcb74d6cf7d13c7d4a4b2255b1ee1c70822c0734

[release-4.9] Bug 2070490: configure-ovs: reload NM only when necessary

---

pkg/controller/kubelet-config/kubelet_config_nodes.go

Do no check for statuses put by other operators in node.config object. This leads to a possible scenario where either `KCMO` or `KASO` updates the `progressing` state for their component and MCO ends up unnecessarily waiting. Each operator should only care about the status added by itself in node.config.  
Fix incorrect status handling for node.config 
edit node.config and observe that it's not blocked in case KCMO or KASO updates their respective statuses. 
None

Do not check for status of other operators for node config

---

test/e2e-bootstrap/bootstrap_test.go

https://coreos.slack.com/archives/C02CZNQHGN8/p1650653177443869 pointed out the ci failed
with wrong arguments of containerruntimeconfig.New.containerruntimeconfig.New was updated
with PR #3008, this is a follow up PR of it.

[release-4.10] Bug 2072621: Fix bootstrap-unit test failure caused by #3008

---

pkg/daemon/daemon.go
pkg/daemon/update.go
pkg/server/server.go
pkg/server/server_test.go

daemon: Add some more code comments
I think the role of "currentConfig" is really important and
deserves more comments.
---
server: Use common helper to decode ignition
To properly handle compression.  Prep for using butane.
---

colin's small patches rollup

---

test/helpers/utils.go

As part of 1.24 kube rebase, API access tokens are no longer created
for SAs. Instead of trying to use the default one, our e2e test
should be instead requesting one on the fly.
Fixes e2e-gcp-op failures.
Based on https://github.com/openshift/origin/blob/master/test/extended/router/metrics.go

Bug 2091730: create openshift-monitoring token in e2e

---

templates/common/aws/files/usr-local-bin-aws-kubelet-providerid.yaml
templates/common/aws/units/aws-kubelet-providerid.service.yaml
templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml

Bug 2092003: Fixup of URL for AWS unit/file to compute instance provider-id

---

go.mod
go.sum
pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
vendor/github.com/openshift/runtime-utils/pkg/registries/registries.go
vendor/modules.txt

Vendor in changes form runtime-utils and fix test test case that was failing initially.
Run the TestRegistriesValidation test

Update block payload test with vendored runtime-utils

---

pkg/daemon/update.go

Currently, the core events API does not allow us to flush
events that haven't been sent before exiting therefore,
I am adding a short sleep to allow events to be sent.
This issue can be seen when updating a node and MCO reboots
the node, a sig term is sent to MCO and MCO exits before all
events are sent.
This has been seen with OSUpdateStaged event missing for alert `Nodes should reach OSUpdateStaged in a timely fashion`.
Signed-off-by: Martin Kennelly <mkennell@redhat.com>

Bug 2097785: Send out OSUpdateStaged event directly

---

templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml

Add the control plan label to master nodes.
ref: https://issues.redhat.com/browse/OCPNODE-709

[OCPNODE-709] add control-plane label

---

OWNERS_ALIASES

Updated `ovirt-approvers` alias. 
added @engelmi, @eslutsky and @Darth-Mera to ovirt-approvers

added @engelmi, @eslutsky, @Darth-Mera to ovirt-approvers

---

OWNERS_ALIASES

* Removed @yboaron and myself (@creydr) from the bare metal approvers & reviewers list
* Added @dougsland as a bare metal reviewer & approver
Check OWNERS_ALIASES file
/hold
until I fully disengaged from the BM networking team

Cleanup BM owner aliases

---

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml

~~Enabling debug mode for testing. It will probably generate too much noise in production.~~

OCPBUGS-1577: On-prem: Ensure resolv-prepender respects NM dispatcher timeout

---

pkg/daemon/daemon.go

The "complete update" workflow in the daemon today is quite convoluted, which can cause the daemon to never uncordon the node, if the first attempt reaches the timeout.
This patch moves the storePendingState to the very end of update completion, such that if the drain fails, we just start from the beginning again.
I thought we had worked around this via the drain controller (the MCD isn't uncordoning directly anymore), but we can now just fail the request and then stick in a cordoned state forever.
To test, you can try to trigger an API failure of some sort during the upgrade. Alternatively, you can try deploying with 
https://github.com/yuqi-zhang/machine-config-operator/tree/fix-uncordon-retries-test-failing
and
https://github.com/yuqi-zhang/machine-config-operator/tree/fix-uncordon-retr …

OCPBUGS-1491: daemon: gate done state on uncordon completion

---

templates/common/_base/files/configure-ovs-network.yaml

OCPBUGS-2921: configure-ovs: copy IP method and warn about low MTU

---

pkg/daemon/controlplane.go
pkg/daemon/coreos.go
pkg/daemon/update.go

Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3415 as some conflict were showing up

OCPBUGS-3756: daemon: Stop setting I/O scheduler to bfq

---

templates/common/alibabacloud/files/usr-local-lib-systemd-system-generators-alibaba-kubelet-extra-env-generator.sh.yaml
templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml

starting a PR to reproduce and test changes related to https://issues.redhat.com/browse/OCPBUGS-3311

OCPBUGS-2248: [alicloud] provider ID not being set for kubelet

---

OWNERS_ALIASES

Adding myself as a new team member of the BM Networking Team.
/cc @cybertron

Add mkowalsk as a bare metal reviewer and approver

---

pkg/daemon/update.go

- We were inspecting the OS container image to figure out its type regardless of whether we were sure we had OS/Extensions/Kernel changes to make.
-  That broke cases where a customer would remove the pull secret to  "shrink-wrap" a cluster for distribution as an image,  as inspections would fail (and the mcd would degrade) once the secret was removed.  
For reference, in [4.11](https://github.com/openshift/machine-config-operator/blob/92012a837e2ed0ed3c9e61c715579ac82ad0a464/pkg/daemon/update.go#L332), before we had the native format image, we didn't inspect anything because there was no decision to make. 
- This PR adds an "is there actually work to do?" check so we can survive the pull secret removal as long as no changes are being made and we're not using extensions or a real-time …

OCPBUGS-4049: Only check image type if we are sure there is work that needs to be done 

---

pkg/daemon/daemon.go

daemon: Add some comments on the firstboot reboot sleep

---

pkg/operator/sync.go

In #3458 we switched to using the proper "live" certificate bundle, but it contains additional certificates, so the machineConfig generated from it is different than it used to be.
You can see that new clusters come up with two `rendered-config`s per pool instead of one: 
```
[jkyros@jkyros-t590 tmp]$ oc get mc
NAME                                               GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
00-master                                          60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
00-worker                                          60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
01-master-container-runtime                        60bb76579811a2487e67ba337a99e13282257b92   3.2.0             78m
01-master-kubelet …
```

OCPBUGS-5888: Don't switch to the "live" certificate bundle until after first ControllerConfig is generated

---

pkg/controller/common/helpers.go
pkg/controller/common/helpers_test.go

When rendering the final rendered-MC, add a default overwrite: true if
not provided by the user.
The MCO always overwrites files on disk, but Ignition does not. This can
cause a user-supplied MC with no default to fail spinning up new nodes,
since MCO would overwrite anything on the host for existing nodes, but
new nodes would not allow the overwrite if the file was already on the
base filesystem.
To verify this, you can provide any user-created MC with a files entry with no default ovewrite. With this change, it will render into a overwrite:true. Without this, we have no overwrite specified (which for ignition, defaults to false)

OCPBUGS-630: controller: default overwrite to true for files

---

OWNERS_ALIASES
pkg/controller/template/render.go
pkg/controller/template/render_test.go
templates/common/sno/OWNERS
templates/common/sno/files/sno-dnsmasq.conf.yaml

Added dnsmasq.conf file for sno deployments
Install sno and check /etc/dnsmasq.conf

OCPBUGS-7743: Adding dnsmasq config for sno

---

pkg/controller/template/render.go

Fixing platform path order as platform specific path should be the last

---

OWNERS_ALIASES

Removing jstuever from OWNERS_ALIASES

Removing jstuever from OWNERS_ALIASES

---

templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
templates/master/01-master-kubelet/vsphere/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/vsphere/units/kubelet.service.yaml

remove container runtime flag

---

cmd/machine-config-daemon/pivot.go

- Took out the meat in the pivot run() call
- Added depreciation text, with a blurb about the forcefile method and link to more instructions
Attempt to run pivot on any node, it should just bop you with a warning. 
```
sh-5.1# /run/bin/machine-config-daemon pivot test
ERROR: pivot no longer forces a system upgrade. It will be fully depreceated in a later y release. 
If you are attempting a manual OS upgrade, please try the following steps:
-delete the currentconfig(rm /etc/machine-config-daemon/currentconfig)
-create a forcefile(touch /run/machine-config-daemon-force) to retry the OS upgrade.
More instructions can be found here: https://access.redhat.com/solutions/5598401
sh-5.1# 
```
OCPBUGS-7836: Removed pivot …

OCPBUGS-7836: The MCD has a non-functional pivot command that should be removed

---

pkg/daemon/update.go

Our OSUpdateStarted/OSUpdateStaged were being thrown when we entered the function, which I think is a bit confusing if no OS updates actually were to happen.
This aims to fix the CI issue where the MCO events were being mis-interpreted as the update stage taking too long, although we do potentially open ourselves to the issue of a non-osupdate-upgrade (i.e. the payloads have the same OSImage), but that should be rare, and I am not sure if no events were emitted, if we'd fail or not. I guess we can find out if we ever hit it.

OCPBUGS-11304: daemon: event only on actual OS updates

---

hack/build-go.sh

We can discuss details in Slack.

Permit consistent go compilation

---

docs/MachineConfiguration.md
pkg/daemon/update.go
test/e2e-single-node/sno_mcd_test.go
test/e2e/mcd_test.go

add ipsec extension

---

OWNERS

Added @cdoern, @djoshy and @dkhater-redhat to reviewer and approver list

OWNERS: Update onwer list

---

Dockerfile
Dockerfile.rhel7

nmstate build was updated in https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=71688
further work in https://github.com/openshift/machine-config-operator/pull/3720
4.14 version of https://github.com/openshift/machine-config-operator/pull/3764

OCPBUGS-15575: Dockerfile: pin to nmstate-2.2.9

---

Dockerfile
Dockerfile.rhel7

Dockerfile: OKD: Reenable extensions image on SCOS
SCOS payload can be built with this change
/cc @sherine-k @travier

OKD-174: Dockerfile: OKD: Reenable extensions image on SCOS

---

docs/FAQ.md

faq: Talk about "no enabled repositories"

---

test/e2e-shared-tests/helpers.go
test/e2e/mco_test.go
test/helpers/utils.go

The TestMetrics e2e test is not correctly cleaning up the MachineConfigs and MachineConfigPools it creates. This means that other e2e tests which run after this e2e test can falsely fail or become flaky.
What's happening is this:
1. The target node is removed from the ephemeral MachineConfigPool by unlabeling it.
2. A race condition occurs when we call WaitForPoolComplete because technically, the pool is updated at this point since it has not yet picked up the unlabelling event from the target node.
3. We delete the ephemeral MachineConfigPool, which deletes the rendered MachineConfigs that belong to it.
4. The node starts the update process, but cannot find the rendered MachineConfigs for the ephemeral pool since they were deleted. The MCD degrades at this point and …

MCO-687: Fix metrics e2e test

---

Dockerfile
Dockerfile.rhel7
Makefile
cmd/machine-config-daemon/firstboot_complete_machineconfig.go
cmd/machine-config-daemon/pivot.sh
cmd/machine-config-daemon/start.go
hack/build-go.sh
pkg/daemon/constants/constants.go
pkg/daemon/daemon.go
pkg/daemon/osrelease/osrelease.go
templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
templates/common/_base/units/machine-config-daemon-pull.service.yaml

Manual backport of PR https://github.com/openshift/machine-config-operator/pull/3799
Also, fixed cosmetic issue noted in https://github.com/openshift/machine-config-operator/pull/3799#issuecomment-1642431904 about log formatting.
Due to various differences, it took me some time to carefully cherry-pick each commits from PR#3799. Hopefully, I didn't miss anything.

OCPBUGS-16622: daemon: Copy matching binary to host, re-exec with it

---

pkg/daemon/daemon.go

Also. revert of PR https://github.com/openshift/machine-config-operator/pull/3824

OCPBUGS-16888: daemon: Make binary writing idempotent

---

pkg/daemon/update.go

- implement func updateKubeConfigPermission to chmod the permission of /etc/kubernetes/kubeconfig to 0600
- func called in func update 
Running 
```
for i in $(oc get nodes  -o name)
do
oc debug $i --  <<EOF
chroot /host
stat -c%a /etc/kubernetes/kubeconfig
EOF
done
```
returns 600 for every node.

OCPBUGS-15367: The kubeconfig copied on to each node has 644 permissions

---

pkg/daemon/daemon.go

daemon: Create `/run/bin` always
Prep for more work
---
daemon: Always replace binary
To fix https://issues.redhat.com/browse/OCPBUGS-17156
---

OCPBUGS-17156: daemon: Always replace binary

---

pkg/daemon/daemon.go

4.13 backport of https://github.com/openshift/machine-config-operator/pull/3832
---
To fix https://issues.redhat.com/browse/OCPBUGS-17156
(cherry picked from commit 59a2a900fbe9bfeec6ebdec2a9252a8b50d24240)

OCPBUGS-17163: daemon: Always replace binary

---

manifests/bootstrap-pod-v2.yaml
pkg/controller/bootstrap/bootstrap.go

Adding some logs to investigate https://issues.redhat.com/browse/OCPBUGS-17568 + a memory bump

OCPBUGS-17568: Agent-based install process the container machine-config-controller will be oom

---

manifests/bootstrap-pod-v2.yaml
pkg/controller/bootstrap/bootstrap.go

Manual cherry pick of #3862 because klog is 4.14+

[release-4.13] OCPBUGS-17769: Agent-based install process the container machine-config-controller will be oom 

---

manifests/bootstrap-pod-v2.yaml
pkg/controller/bootstrap/bootstrap.go

Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3882 due to a conflict

[release-4.10] OCPBUGS-18176: Agent-based install process the container machine-config-controller will be oom

---

pkg/daemon/update.go

This is a manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3808

[release-4.12] OCPBUGS-19515: The kubeconfig copied on to each node has 644 permissions

---

templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml

Clean cherry-pick of https://github.com/openshift/machine-config-operator/pull/3926

[release-4.14] OCPBUGS-19344: Ignore invoking nbctl calls if its SDN

---

templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
test/e2e/kubeletcfg_test.go

OCPBUGS-15583: Revert "Revert "fix nodeStatusUpdateFrequency""

---

manifests/controllerconfig.crd.yaml
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/operator/sync.go

A combined backport of John's work in https://github.com/openshift/machine-config-operator/pull/3662, https://github.com/openshift/machine-config-operator/pull/3682, https://github.com/openshift/machine-config-operator/pull/3713

OCPBUGS-19958: [release-4.13] Backport logspam PRs

---

templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml

Same as https://github.com/openshift/machine-config-operator/pull/3904 but for GCP
this time @huiran0826 we should ensure we don't break SDN :D 
Also I don't plan to backport the GCP fix unless someone asks

OCPBUGS-17841: Ensure gcp-routes hack for internalLB hairpin traffic works for SGW

---

templates/common/on-prem/files/keepalived-script-default-ingress.yaml

This is a manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3687 and https://github.com/openshift/machine-config-operator/pull/3908.

[release-4.12] OCPBUGS-21723: keepalived/ingress: change healthcheck script 

---

docs/MachineOSBuilderDesign.md

Connecting the two Markdown files added in b72e62570a (#3885).

docs/MachineOSBuilderDesign: 'Known Limitations' links

---

pkg/controller/container-runtime-config/helpers.go
pkg/controller/container-runtime-config/helpers_test.go

Add source and mirror format regex validation
1. Apply an icsp CR with blacspaces in the source or mirror filed
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
name: repo-icsp
spec:
repositoryDigestMirrors:
- mirrors:
- "example.io/cp4d-dp-xyz  "
source: "  example.io/cp4d/dp/xyz"
```
2. MCO will not rollout this CR.
Add source and mirror format regex validation.

OCPBUGS-19427: Add source and mirror format regex validation

---

docs/ImageMirrorSetDesign.md
pkg/controller/container-runtime-config/helpers.go

NO-ISSUE: Update the design doc dual support icsp and idms

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

OCPNODE-2005: crio: add support for LinkLogs annotation by default

---

pkg/operator/bootstrap.go

Fixes OCPBUGS-28969 : When platform specific manifests are being generated make sure `cloud-platform-alt-dns` manifests are generated for platform GCP.

OCPBUGS-28969: On-prem coredns manifests should not be generated for GCP

---

docs/HACKING.md

The api.ci.openshift.org has been decommissioned, we should use
`quay.io/openshift-release-dev/ocp-release` instead.

docs/HACKING: Update command for building customize OCP release

---

OWNERS

I have changed roles and in the short term I can't be a default
assignee to review PRs on this repository.  But don't hesitate
to reach out where I'm needed!
---

NO-ISSUE: OWNERS: Remove myself from reviewers

---

templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
test/e2e/kubeletcfg_test.go

This is a manual backport of https://github.com/openshift/machine-config-operator/pull/4170

OCPBUGS-29366: release-4.12: fix nodeStatusUpdateFrequency

---

templates/common/_base/units/ovs-configuration.service.yaml
templates/common/azure/units/ovs-configuration.service.yaml

Run ovs-configuration after nmstate.service
Run ovs-configuration after nmstate.service

NO-JIRA: ovs-configfuration, run after nmstate.service

---

pkg/controller/template/constants.go
pkg/operator/bootstrap.go
pkg/operator/sync.go
templates/master/01-master-kubelet/_base/files/criometricsproxy-config.yaml
templates/master/01-master-kubelet/_base/files/criometricsproxy.yaml
templates/worker/01-worker-kubelet/_base/files/criometricsproxy-config.yaml
templates/worker/01-worker-kubelet/_base/files/criometricsproxy.yaml

Cherry pick of https://github.com/openshift/machine-config-operator/pull/4175

[release-4.15] OCPBUGS-30761: add static pods for rbacproxy

---

manifests/on-prem/coredns.yaml
templates/common/on-prem/files/coredns.yaml

Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/4058 because bot didn't pick it

[4.15] OCPBUGS-30093: Mount /run/nodeip-configuration into coredns containers

---

manifests/machineconfigdaemon/daemonset.yaml
templates/worker/01-worker-kubelet/_base/files/criometricsproxy.yaml

missed a couple the first time

OCPBUGS-28230: enforce termination message policy on all platform pods

---

templates/master/01-master-kubelet/_base/units/kubelet-cleanup.service.yaml
templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml
templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet-cleanup.service.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml

This is a semi-automated cherry-pick of https://github.com/openshift/machine-config-operator/pull/4124
This replaces https://github.com/openshift/machine-config-operator/pull/4151 that has a merge conflict.

OCPBUGS-28545: Delete state files on reboot only

---

manifests/cloud-platform-alt-dns/coredns.yaml

OCPBUGS-29067: Fix CoreDNS pod definition on bootstrap nodes on cloud platforms

---

OWNERS_ALIASES

Removing some folks who are no longer working on this so they don't get auto-assigned to PRs.

NO-ISSUE: Update baremetal owner aliases

---

pkg/controller/template/template_controller.go

added additional logging to log enough details to triage malformed cert issue

OCPBUGS-31312: machine-config-controller not logging enough details to triage the malformed certificate issue.

---

pkg/controller/container-runtime-config/helpers.go

```bash
apiVersion: config.openshift.io/v1alpha1
kind: ClusterImagePolicy 
metadata:
name: p1
spec:
scopes:
- localhost:5000/myns/sigstore-signed-with-full-references
- example.com/global
policy:
rootOfTrust:
policyType: PublicKey
publicKey:
keyData: Zm9vIGJhcg==
signedIdentity:
matchPolicy: MatchRepoDigestOrExact
```
policy.json:
```
sh-5.1# cat /etc/containers/policy.json 
{"default":[{"type":"insecureAcceptAnything"}],"transports":{"atomic":{"example.com/global":[{"type":"sigstoreSigned","keyData":"Zm9vIGJhcg==","signedIdentity":{"type":"matchRepoDigestOrExact"}}],"localhost:5000/myns/sigstore-signed-with-full-references":[{"type":"sigstoreSigned","keyData":"Zm9vIGJhcg==","signedIdentity":{"type":"matchRepoDigestOrExact"}}]},"docker":{"example.com …
```

NO-JIRA: format policy.json

---

templates/common/_base/units/kubelet-dependencies.target.yaml

This reverts commit 5236644ad2c4868a90deb47745d7bf7fe322c2d2.
/cc @rphillips @harche

NO-ISSUE: Revert "disable mglru service"

---

pkg/operator/bootstrap.go

This PR refactors the manifest generation for vSphere so that instead of
crafting the list of manifests inline, it leverages the existing
`getPlatformManifests` function.

OPNET-465: Refactor LB and DNS manifest list for vSphere

---

pkg/controller/drain/drain_controller.go

This PR ensures there is a diff in the `machineconfiguration.openshift.io/desiredDrain` annotation value before it runs through the drain callback function.
Follow the reproduction instructions [in the bug](https://issues.redhat.com/browse/OCPBUGS-33134), there should only be one drain log per node in the drain_controller logs.

OCPBUGS-33134: Nodes are drained twice when an OCB image is applied

---

test/e2e/mcd_test.go
test/helpers/utils.go

I rewrote the `TestFirstBootHasSSHKeys` e2e test in pure Go to ensure that it uses the official Machine Go client instead of shelling out to the `oc` command. In the process of doing so, I observed a couple of things:
- The original version of the `TestFirstBootHasSSHKeys` e2e test was running `$ oc scale --replicas=2` to start, and then running `$ oc scale --replicas=1` to scale back down again after cleanup. Doing this would leave the worker pool with a single node.
- Additionally, I observed a few issues which can best be described as weird shell-scripting gremlins caused by parsing the output of `oc` with typical shell commands such as `head` or `grep`. Writing shell scripts to parse output isn't a problem, but I suspect that output formatting for `oc` may have …

OCPBUGS-29444: Rewrote TestFirstBootHasSSHKeys e2e test in pure Go

---

templates/common/openstack/files/usr-local-bin-openstack-kubelet-nodename.yaml
templates/common/openstack/units/openstack-kubelet-nodename.service.yaml

OSASINFRA-3560: OpenStack: kubelet-nodename service for IPv6

---

pkg/controller/node/node_controller.go

Added syncs for all the old pools of a node when the primary pool of the node could not be resolved. We don't support a node belonging to multiple custom pools; however when a node is attempting to exit from this invalid state to a valid state, this helps in populating the status numbers for the old pools correctly.
Repeat the steps in the bug, the MCP numbers should now be reported correctly.

OCPBUGS-41920: MCPs report wrong number of nodes when we move nodes from one custom MCP to another custom MCP

---

pkg/controller/build/build_controller.go

Fixed an issue where deleting a MachineOSConfig during its building state did not properly clean up related ConfigMap resources. This resulted in conflicts when reapplying the same MachineOSConfig, as existing ConfigMap resources prevented new builds from progressing.
1. Apply a MachineOSConfig and verify that it starts building.
2. Delete the MachineOSConfig while it is still in the building state.
3. Reapply the same MachineOSConfig.
4. Verify that the build progresses successfully without conflicts, confirming that the previous ConfigMap resources were properly cleaned up.
Fixed an issue where deleting a `MachineOSConfig` in the building state did not properly clean up associated `ConfigMap` resources, …

OCPBUGS-36810: When MCOS is deleted in building state configmap resources related to MOSC are not deleted.

---

pkg/controller/build/build_controller.go

The `.status.ObservedGeneration` field on the MachineOSConfigs was not being properly incremented, so we should do that every time we update it, from now on. Additionally, the build was being prematurely marked as a failure due to a transient image pull error that was occurring when the pod is in the pending phase. To work around that, we ignore that error when the pod is in a pending phase.
The e2e-gcp-op-techpreview job should pass as-is
Fix observedgeneration on MachineOSConfigs and fix pending pod behavior for build pods

OCPBUGS-42742: set observed generation and fix pod error detection

---

OWNERS

NO-ISSUE: OWNERS: Add umohnani8

---

OWNERS

Add myself back into OWNERS file after rejoining the MCO team.
/assign @yuqi-zhang 

NO-ISSUE: Add LorbusChris to OWNERS

---

OWNERS

Add Rishabh Saini to approvers and reviewers
/assign @cheesesashimi 

NO-ISSUE: Add Rishabh Saini to approvers and reviewers

---

pkg/controller/node/node_controller.go

Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/4647

[release-4.14] OCPBUGS-43980: MCPs report wrong number of nodes when we move nodes from one custom MCP to another custom MCP

---

pkg/daemon/daemon.go
pkg/daemon/metrics.go

[release-4.17] MCO-1343: Backport Telemetry to 4.17

---

pkg/daemon/daemon.go
pkg/daemon/metrics.go

[release-4.16] MCO-1342: Backport Telemetry to 4.16

---

pkg/daemon/daemon.go
pkg/daemon/metrics.go

Backport Telemetry work to 4.14

[release-4.14] MCO-1278: Backport Telemetry to 4.14

---

pkg/controller/node/node_controller.go

Closes: OCPBUGS-43382
Added an delete event handle in Node Controlled when a MOSC resource is deleted
Create an MOSC, wait till it triggers an MOSB
Delete the MOSC
Added an delete event handle in Node Controlled when a MOSC resource is deleted

OCPBUGS-43382: Node takes too long to get updated config after MOSC deletion

---

lib/resourceapply/machineconfig.go
lib/resourcemerge/meta.go

backport of https://github.com/openshift/machine-config-operator/pull/4378

[release-4.15] OCPBUGS-42137: Removal of additionalTrustBundle CA  does not remove certificate from node backport

---

pkg/upgrademonitor/upgrade_monitor.go

Added a check so the MCO will always send in a non empty value for `newMCNode.Spec.ConfigVersion.Desired`. Also took this opportunity to update this file to use the daemon constants package.
This bug only affects TechPreview clusters as MCN is not in the default featureset. With this fix, we should no longer see any errors in the daemon log about invalid MCN apply requests like the following:
```
E1006 10:59:31.339379   13305 upgrade_monitor.go:319] Error making MCN spec for Update Compatible: MachineConfigNode.machineconfiguration.openshift.io "ip-10-0-113-112.us-east-2.compute.internal" is invalid: spec.configVersion.desired: Invalid value: "": spec.configVersion.desired in body should match …
```

OCPBUGS-42816: MachineConfigNode objects should not produce too many invalid apply requests

---

pkg/operator/sync.go

Add a short retry for the operator image version check before degrading.
This is hard to manually verify, but we should no longer see failures of the sort listed in the bug. Existing e2es should pass and this retry should not have a discernible performance impact.

OCPBUGS-39199: clusteroperator/machine-config blips Degraded=True during upgrade test

---

pkg/daemon/daemon.go

The daemon will begin to save its logs right before shutdown at `/etc/machine-config-daemon/previous-logs/`. I'm hoping that we can update the must gather tool so that it is able to scoop up this log file. I also wanted this to be a backportable solution so I tried to keep it out of the critical path, on encountering an error the daemon logs it, but it's not fatal.
- Roll out an MC change that causes a node reboot. A cluster upgrade should also trigger this. 
- On reboot, debug into the node, and you should see the previous daemon logs saved at `/etc/machine-config-daemon`:
```
sh-5.1# ls /etc/machine-config-daemon/previous-logs/openshift-machine-config-operator_machine-config-daemon-qmgx4_a2b53ce6-ac08-4211-b93f-c1286d4e0554/machine-config-daemon/ …
```

MCO-113: Preserve previous boot MCD log

---

cmd/machine-config-controller/start.go
pkg/apihelpers/apihelpers.go
pkg/controller/render/render_controller.go
pkg/controller/render/render_controller_test.go
test/e2e-bootstrap/bootstrap_test.go

This is an manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/4727

OCPBUGS-48583: trying to wait for sub-contorllers

---

cmd/machine-config-controller/start.go
pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
pkg/controller/render/render_controller.go
pkg/controller/render/render_controller_test.go
test/e2e-bootstrap/bootstrap_test.go

This is an manual cherry-pick of #4727 since #4803 failed to do it automatically despite having no conflicts 

OCPBUGS-48801: Wait for all subcontrollers

---

OWNERS

Added myself as an approver & reviewer to the code owners file.
N/A
OWNERS: Add isabella-janssen as approver & reviewer

NO-ISSUE: Add isabella-janssen to OWNERS as approver & reviewer

---

pkg/controller/node/status.go

added mcp reporting status to follow mosb's
1. Enable techpreview
2. Create a MOSC
3. watch mcp status change 
*NOTE* mcp will not degrade if a build fails. 

OCPBUGS-44618: In OCL, MCPs are reporting Updating=false while the image is being built

---

test/helpers/utils.go

NO-ISSUE: increase WaitForPoolComplete() timeout

---

pkg/apihelpers/apihelpers.go
pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/controller/render/render_controller.go

kubelet_config_controller: Update ObservedGeneration

OCPBUGS-52213: Update ObservedGeneration in KubeletConfig

---

templates/common/_base/files/wait-for-ipsec-connect.yaml
templates/common/_base/units/ipsec.service.yaml
templates/common/_base/units/wait-for-ipsec-connect.yaml

Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/4854. No conflicts.

[release-4.18] OCPBUGS-52949: Add ipsec connect wait service

---

templates/common/_base/files/wait-for-ipsec-connect.yaml
templates/common/_base/units/ipsec.service.yaml
templates/common/_base/units/wait-for-ipsec-connect.yaml

Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/4926, No conflicts.

[release-4.17] OCPBUGS-52951: Add ipsec connect wait service 

---

pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/controller/render/render_controller.go

This is an manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/4944
/assign RishabhSaini

[release-4.14] OCPBUGS-54228: Update ObservedGeneration in KubeletConfig

---

pkg/operator/status.go

Updated the message to reflect accurate way to update the cgroupMode.
Also included reference of the ocp doc to switch cgroupMode
/cc @wking @yuqi-zhang @haircommander

Update cluster operator's status condition message

---

pkg/controller/machine-set-boot-image/platform_helpers.go

Adds a default region fallback if the cluster's region specific AMI is not found during boot image update. This mirrors the [installer's behavior](https://github.com/openshift/installer/blob/08aa270e20db77b237306b3f3700d6b2ad654abc/pkg/asset/rhcos/image.go#L99-L103).
Existing e2es should pass and OKD installs should succeed.

OCPBUGS-55231: MCO should fall back to us-east-1 for AWS bootimages if no region specific-AMI exists

---

pkg/operator/sync.go

Ensured that the errors in the PollUntilContextTimeout aren't used for an immediate exit. 
Existing e2es/units should pass. I don't think this needs pre merge QE.

OCPBUGS-55043: Fix PollUntilContextTimeout in syncRenderConfig

---

pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go

We should skip windows machinesets for boot image updates.

OCPBUGS-55388: MSBIC should not update windows machinesets

---

pkg/daemon/pinned_image_set.go

NO-ISSUE: debug podman on PIS

---

pkg/daemon/pinned_image_set.go

Reverts openshift/machine-config-operator#5003

Revert "NO-ISSUE: debug podman on PIS"

---

templates/master/01-master-kubelet/_base/units/kubelet.service.yaml
templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml

manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/4857

OCPBUGS-54765: [release-4.18] kubelet-service: narrow down restorecon path

---

pkg/daemon/daemon.go

Update MCD Log Output to Clarify No Configuration Change
when rendered MC stays the same, observe the log

OCPBUGS-41485: Update MCD Log Output to Clarify No Configuration Change

---

cmd/machine-config-daemon/start.go
pkg/controller/common/controller_context.go
pkg/daemon/writer.go

This is a manual cherry-pick of #5015

[release-4.18] OCPBUGS-56585: scope MCD node listers to current node

---

templates/master/01-master-kubelet/_base/files/criometricsproxy.yaml
templates/worker/01-worker-kubelet/_base/files/criometricsproxy.yaml

Manual cherry pick of https://github.com/openshift/machine-config-operator/pull/4997 to 4.18.

OCPBUGS-55246: kubelet: readonly mounts for criometricsproxy

---

OWNERS_ALIASES

She is part of the baremetal networking team now and we should start including her on reviews.

NO-ISSUE: Add emy to baremetal-reviewers

---

pkg/controller/build/reconciler.go

1. Moved the “delete existing MOSB” call into createNewMachineOSBuildForRebuild, so that we only ever delete exactly the build we’re about to recreate.
2. Removed the pre-emptive Delete(existingMosb.Name) from the if isRebuild block in createNewMachineOSBuildOrReuseExisting, delegating all delete/wait/create logic to the helper.
1. e2e test
Run TestMissingImageIsRebuilt and confirm it passes cleanly.
2. Manual ocl scenario
Enable OCL on a cluster and wait for the initial MOSB to start (but not finish).
While that build is in-flight, apply an MC changing kargs or extensions. Verify no degradation and pre-emptive MOSB deletion.
Only delete old MOSB's inside the rebuild helper to avoid accidental image removal on …

OCPBUGS-58238: Image Mode creates new MOSBs when osbuilder is drained and it results in degraded MCPs

---

pkg/controller/machine-set-boot-image/vsphere_helpers.go

vsphere_helpers: Find existing VM Template in vsphere with a known name rather than using the value mentioned in providerSpec template. This prevents breaking reconciliation logic when the template in the providerSpec diverges from the name of the VM in vsphere. If the names have diverged, correct it
Changing the `machineSet.spec.template.spec.providerSpec.value.template` name from its real-value to a "fake-value", should be automatically fixed and brought back to its real-value.

MCO-1815: vSphere bootimage update reconciliation should handle bootimage name diverging

---

pkg/controller/build/reconciler.go

I updated the logic that handles image reuse for a MOSB. Previously, any failure during image inspection (including authentication errors) would cause the controller to incorrectly delete the MOSB and trigger a rebuild. I added an explicit check to catch IsUnauthorized errors from the image inspection. Now, if an authentication error occurs, the controller will return a specific error message and stop, preventing the incorrect deletion. This makes the error reporting more accurate and the controller's behavior more robust. I also updated the code comments to reflect this new logic.
1. Do not create a long lived token
2. Opt into OCL
3. Apply a MC with an ssh change (for example)
4. View logs

OCPBUGS-58443: In OCL for reboot, after applying ssh/file/password based MC the MCP is stuck in updating state

---

pkg/daemon/update.go

Manual cherry-pick of: https://github.com/openshift/machine-config-operator/pull/5333
Closes: #OCPBUGS-62788
This commit slightly changes the behaviour of OS updates if PIS is not configured.
Before this change, if PIS was enabled we checked if the new OS image was locally present and if so, the OS rebase was requested to be performed using the local stored copy, no matter if any PinnedImageSet was available for the node's pools.
With this change that local check is only performed if PIS is enabled and configured.
This minor behaviour change helps during upgrades from 4.19.10 to any version that has PIS enabled (from 4.19.12 it's enabled by default) as the machine-config-nodes-crd-cleanup job uses the target image to run before the update, catching the image locally and …

OCPBUGS-62788: Skip rpm-ostree local rebase if no PIS
