openshift/machine-config-operator

cmd/machine-config-controller/bootstrap.go
cmd/machine-config-operator/bootstrap.go
manifests/machineconfigcontroller/bootstrap-pod.yaml
manifests/machineconfigcontroller/deployment.yaml
manifests/machineconfigdaemon/daemonset.yaml
manifests/machineconfigserver/bootstrap-pod.yaml
pkg/controller/bootstrap/bootstrap.go
pkg/controller/render/render_controller.go
pkg/controller/template/template_controller.go
pkg/operator/bootstrap.go

1. Add bootstrap mode for MCC. MCC now reads ControllerConfig, Pools, user-defined Machineconfigs to seed the MCS with correct Pools and generated Machineconfigs
2. MCO renders pods for MCC and MCS, ControllerConfig and Pools to disk in bootstrap phse
/cc @yifan-gu 
/assign @yifan-gu

Bootstrap modes for MCO and MCC

---

README.md
hack/build-image.sh

hack script to build images quickly.
```
$ sudo  ./hack/build-image.sh 
WHAT must be set to one of the following:
- all
- machine-config-controller
- machine-config-daemon
- machine-config-operator
```
```
$ sudo WHAT=asd ./hack/build-image.sh 
asd is not a valid build target
$ sudo WHAT=machine-config-daemon ./hack/build-image.sh 
Using version from git...
---
Building machine-config-daemon
Executing: podman build -t machine-config-daemon:v0.0.0-68-g57ceadb3 -f Dockerfile.machine-config-daemon
---
STEP 1: FROM golang:1.10.3
STEP 2: COPY . /go/src/github.com/openshift/machine-config-operator
STEP 3: WORKDIR /go/src/github.com/openshift/machine-config-operator
STEP 4: RUN WHAT=machine-config-daemon ./hack/build-go.sh
Using version from git...
Building …
```

hack/build-image.sh: Add script to build images

---

pkg/daemon/daemon.go
pkg/daemon/update.go

This is pre-work for enabling/disabling units intelligently via incoming config.
- `enableUnit`:  Takes a `ignv2_2types.Unit` and attempts to link into the enabled path on the system. If it is already linked the function returns early.
- `disableUnit`: Takes a `ignv2_2types.Unit` and attempts to remove the link from the enabled path. If the link does not exist the function returns early.

systemd enable/disable

---

cmd/machine-config-operator/bootstrap.go
cmd/machine-config-operator/start.go
install/mco.images.yaml
manifests/machineconfigcontroller/bootstrap-pod.yaml
manifests/machineconfigcontroller/deployment.yaml
manifests/machineconfigdaemon/daemonset.yaml
manifests/machineconfigserver/bootstrap-pod.yaml
manifests/machineconfigserver/daemonset.yaml
pkg/apis/machineconfiguration.openshift.io/v1/register.go
pkg/operator/assets/bindata.go
pkg/operator/bootstrap.go
pkg/operator/images.go
pkg/operator/operator.go
pkg/operator/render.go

In preparation for https://docs.google.com/document/d/1CGZVEyuloZ9oD4NUArW6dnEpi0WFc6BP2tqPSwFZTCY/edit#heading=h.1qxlffn2dsyu
bootstrap mode mco reads a config map with images.json key
long running mode mco reads the images.json directly as the configmap
will be mounted as a volume
mco doesn't load images.json at startup rather continuously reads the file
so that it can reconcile state if the configmap changes at runtime.
/cc @yifan-gu 
/assign @yifan-gu

Update MCO to use images.json from ConfigMap for image resolution

---

OWNERS_ALIASES
cmd/machine-config-daemon/OWNERS
pkg/daemon/OWNERS

To DRY up our two sub-`OWNERS`.  The namespacing (vs. just `daemon-approvers`) is for when these are [slurped into openshift/release][1].  If we used `daemon-approvers` and another release upstream did as well, ours would be [namespaced to `openshift-machine-config-operator-daemon-approvers`][2].  That's not too bad, but I went with the middle-ground namespacing to keep things stable and relatively short ;).
[1]: https://github.com/openshift/release/blob/51ed98ca754e80618769eae5a3f8f602a30f8977/tools/populate-owners/README.md
[2]: https://github.com/openshift/release/blame/51ed98ca754e80618769eae5a3f8f602a30f8977/tools/populate-owners/README.md#L20

OWNERS_ALIASES: add machine-config-daemon-approvers

---

docs/MachineConfiguration.md

So that others don't also spend an inordinate amount of time trying to
get hand-crafted machineconfigs to work when hacking.

docs: document how a machineconfig manifest looks

---

HACKING.md

tree: add basic HACKING.md with section for MCD

---

docs/MachineConfiguration.md

We need the MachineConfiguration to be a full specification, which also
means the OS image URL must already be resolved to a specific image
digest to ensure consistency across the cluster.

docs: clarify osImageURL pull spec

---

pkg/controller/template/test_data/templates/aws/master/files/-etc-containers-registries.conf
pkg/controller/template/test_data/templates/aws/worker/files/-etc-containers-registries.conf
pkg/controller/template/test_data/templates/libvirt/master/files/-etc-containers-registries.conf
pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-containers-registries.conf
templates/_base/master/files/container-registries.yaml
templates/_base/worker/files/container-registry.yaml

add docker.io registry

---

pkg/daemon/update.go

If the file exists, then we *don't* expect an error from `os.Stat()`.
This is a quick fix, though these paths should be reworked to just do the operation and non-fatally handle `ENOENT`/`EEXIST`.

daemon: fix inverted logic

---

manifests/machineconfigdaemon/OWNERS
pkg/operator/assets/OWNERS

So that MCD approvers can also approve changes to MCD related manifests.
Closes: #73

manifests/mcd: add OWNERS file

---

pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
templates/_base/master/units/etcd-member.yaml

Avoid trying (and failing) to launch before all of our networks have IP addresses.  [One recent instance][1] of this looked like:
```
master0$ journalctl
...
Sep 18 05:59:12 localhost.localdomain sh[2911]: Trying to pull quay.io/coreos/kube-client-agent:678cc8e6841e2121ebfdb6e2db568fce290b67d6...Failed
Sep 18 05:59:12 localhost.localdomain sh[2911]: unable to find image: unable to pull quay.io/coreos/kube-client-agent:678cc8e6841e2121ebfdb6e2db568fce290b67d6: unable to pull image, or you do not have pull acces
Sep 18 05:59:12 localhost.localdomain systemd[1]: etcd-member.service: control process exited, code=exited status=125
Sep 18 05:59:12 localhost.localdomain systemd[1]: Failed to start etcd (System Application Container).
Sep 18 05:59:12 localhost.localdomain systemd[1]: Unit …
```

templates/_base/master/units/etcd-member: Block on network-online.target

---

manifests/machineconfigdaemon/daemonset.yaml
pkg/daemon/daemon.go
pkg/daemon/rpm-ostree.go
pkg/daemon/run.go
pkg/daemon/update.go
pkg/operator/assets/bindata.go

Teach the MCD to check the current OS version and upgrade the host. This
essentially implements the 'OSImageURL` part of the `MachineConfig`
spec.
Since we're in a chroot anyway, I just took the easy path of exec'ing
`rpm-ostree` and `pivot` directly. Which is good, because right now only
`pivot` knows how to upgrade RHCOS from an oscontainer image pull spec.

pkg/daemon: implement OS version validation

---

pkg/daemon/node.go

/cc @sjenning @sdemos 
Hopefully resolves #79 
**Notes**:
- Even if this does resolve #79 we likely still will want to record the updated `ResourceVersion` for the next watcher in a follow on.
- I was not able to test this patch properly to verify it fixed the issue

daemon: Create a new watcher on error

---

pkg/daemon/node.go

This reverts us back to the restarting of MCD when the watch fails. As found by @sdemos this was actually a feature rather than a bug in the original implementation. However, we should look at how to do this better in the near future. 
/cc @sjenning @rphillips @sdemos

Use cluo style restart again

---

pkg/controller/template/test_data/templates/aws/master/units/kubelet.service
pkg/controller/template/test_data/templates/aws/worker/units/kubelet.service
pkg/controller/template/test_data/templates/libvirt/master/units/kubelet.service
pkg/controller/template/test_data/templates/libvirt/worker/units/kubelet.service
templates/_base/master/units/kubelet.yaml
templates/_base/worker/units/kubelet.yaml

See https://github.com/openshift/installer/pull/303
See https://github.com/openshift/openshift-ansible/pull/10177
kubelet won't use cAdvisor with cri-o to return pod stats summary data if prefixed with unix:// for historical reasons.

Fix kubelet stats summary endpoint with cri-o

---

Gopkg.lock
Gopkg.toml
cmd/machine-config-daemon/start.go
pkg/daemon/constants.go
pkg/daemon/daemon.go
pkg/daemon/osrelease.go
vendor/github.com/ashcrow/osrelease/LICENSE
vendor/github.com/ashcrow/osrelease/osrelease.go

This set of work adds:
- a function to check what OS the MCD is running on
- usage of said function on start up and exit if the OS is not supported
- plumbs the `operatingSystem` found at start into `Daemon` for use later
/cc @derekwaynecarr @abhinavdahiya @sjenning @crawford @aaronlevy @rphillips

MCD: Check what OS MCD is running on

---

cmd/machine-config-daemon/start.go

This was the only message left that wasn't capitalize. Also bump the
`Moving to /` message to `V(2)`.

cmd/daemon: consistently capitalize log messages

---

pkg/daemon/daemon.go
pkg/daemon/rpm-ostree.go
pkg/daemon/update.go

The booted OSImageURL is clearly not going to change during the same run
of the daemon, so query it just once at the beginning instead. This
simplifies comparisons later on against new machine configs and avoids
running `rpm-ostree status --json` twice.

cmd/daemon: simplify OSImageURL querying

---

pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/aws/master/units/kubelet.service
pkg/controller/template/test_data/templates/aws/worker/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/aws/worker/units/kubelet.service
pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/libvirt/master/units/kubelet.service
pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/libvirt/worker/units/kubelet.service
templates/_base/master/files/kubelet.yaml
templates/_base/master/units/kubelet.yaml
templates/_base/worker/files/kubelet.yaml
templates/_base/worker/units/kubelet.yaml

Migrates the kubelet to a kubelet.conf file.
The customer typically had to set configuration settings within the kubelet unit file and pass command-line flags to reconfigure the Kubelet. With this patch, the configuration file will allow a subset of options to be set by the customer.

migrate to kubelet config file

---

pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
templates/_base/master/units/etcd-member.yaml

Reverts openshift/machine-config-operator#104

Revert "templates: change etcd-member to notify type"

---

pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/aws/worker/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-kubernetes-kubelet.conf
templates/_base/master/files/kubelet.yaml
templates/_base/worker/files/kubelet.yaml

case matters in yaml and kubelet configuration. clusterDNS was not being propagated into the config.
/cc @abhinavdahiya

kubelet: fix the clusterDNS property within the config

---

pkg/controller/template/render.go
pkg/controller/template/render_test.go
pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service

the clusternetwork apiservers like openshift-apiserver use the `etcd.kube-system.svc` to get at etcd.  The cert needs to be signed for that name
/assign @abhinavdahiya

sign for the local etcd service name that cluster-network apiservers use

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go
pkg/daemon/rpm-ostree.go
pkg/daemon/rpm-ostree_test.go
pkg/daemon/update.go
pkg/daemon/update_test.go

This change allows for modification of rpm-ostree related code so
unittesting can occur. Instead of the functionality being spread
through private functions within the daemon package, a structure
which implements DeploymentClient is used and is passed in to
the Daemon at creation.
Part of https://github.com/openshift/machine-config-operator/issues/101
/cc @jlebon @sdemos @kikisdeliveryservice

Turn rpm-ostree code into a client

---

pkg/daemon/daemon.go

there was a bug where config changes where the only difference was
unreconcilable the node wouldn't be marked as degraded. it happened
because the update would not be applied if the node verification was
successful, and the verification logic only checks things it
understands, and skips unreconcilable stuff.
this restructuring of the top level logic sets up the process function
to verify the machine every time the mcd starts, and after a successful
update that didn't require a reboot, but only then. essentially this
means verification happens after every update. however, unlike before,
the update is _always_ attempted regardless of whether or not the
machine seems like it is in the correct state. the update logic is
responsible for checking if a config is reconcilable, so that is still …

daemon: restructure the process function

---

pkg/controller/template/test_data/templates/aws/master/units/flannel-dns-hack.service
pkg/controller/template/test_data/templates/libvirt/master/units/flannel-dns-hack.service
pkg/controller/template/test_data/templates/openstack/master/units/flannel-dns-hack.service
templates/_base/master/units/flannel-dns-hack.yaml

when pod requesting dns resolution is located on the same node as the dns pod,
the dns query fails with error
```console
nslookup test1-etcd-0.tt.testing
;; reply from unexpected source: 10.2.0.6#53, expected 10.3.0.10#53
```
@rchopra found that the cause is flannel using the bridge to route pod traffic and
the bridge does not participate in iptables if routed locally. The fix is to force
the cni0 bridge to use iptables.
https://github.com/openshift/installer/issues/440
/cc @crawford

templates: add flannel-dns-hack.service for masters

---

cmd/machine-config-operator/bootstrap.go
pkg/operator/bootstrap.go
pkg/operator/images.go
pkg/operator/operator.go
pkg/operator/render.go

This will allow us remove the hardcoded config map in installer for bootstrap mco.
/cc @crawford

operator: add mco cli flags to mco bootstrap

---

pkg/controller/template/test_data/templates/aws/master/units/flannel-dns-hack.service
pkg/controller/template/test_data/templates/libvirt/master/units/flannel-dns-hack.service
pkg/controller/template/test_data/templates/openstack/master/units/flannel-dns-hack.service
templates/_base/master/units/flannel-dns-hack.yaml

https://github.com/openshift/machine-config-operator/pull/118 added this service
which is not started by systemd on boot because of the missing Install section

templates: fix missing Install section for flannel-dns-hac.service

---

pkg/daemon/update.go

It's inherently non-idempotent. See upstream Ignition issue on this:
https://github.com/coreos/ignition/issues/642

daemon: don't try to reconcile file appends

---

pkg/daemon/daemon.go

As discussed in #109, if the node is marked degraded, then we don't want
the MCD to do anything at all. As a first step, just check for this on
start and exit right away if that's the case. Down the line, we should
investigate tainting the node to make sure we don't get scheduled in the
first place as was discussed in #109.

daemon: exit early if node is degraded

---

pkg/daemon/update_test.go

```
Running tool: /usr/bin/go test -timeout 30s -run ^TestReconcilable$
PASS
ok  	github.com/openshift/machine-config-operator/pkg/daemon	0.008s
Success: Tests passed.
```
Kind of part of #101 
/cc @sdemos @kikisdeliveryservice @jlebon

daemon/update_test.go: Add TestReconcilable

---

pkg/daemon/daemon.go

An issue with immediately exiting if the node is degraded is that we
then clobber the logs of the previous MCD containers, which means that
the logs from the MCD instance that actually set the node to degraded is
lost in the ether.
Let's just block on `poll()` so we don't exit and don't waste any CPU
resources. The stop channel here isn't actually being written/closed by
any other goroutine so this just sits there.
See also #127.

daemon: just sit quietly if node is degraded

---

pkg/daemon/daemon.go
pkg/daemon/node.go

Regression from #121: we would fail at retrieving the annotation on the
first run since it wasn't set yet. Except... that annotation gets set by
us normally.
Tweak this by adding an `Ext` version of `getNodeAnnotation` which
doesn't error out if the annotation is not yet set. So now, we exit
early only if the label is set *and* its value is set to "Degraded".
Fixes: #127

daemon: allow no state label to be set on node

---

manifests/machineconfigserver/csr-approver-role-binding.yaml
manifests/machineconfigserver/csr-bootstrap-role-binding.yaml
manifests/machineconfigserver/csr-renewal-role-binding.yaml
pkg/operator/assets/bindata.go
pkg/operator/sync.go

/cc @mfojtik 
This fixes the error where workers could not join the cluster in absence of KCO in https://github.com/openshift/installer/pull/420
Error from one of the worker
```console
failed to run Kubelet: cannot create certificate signing request: certificatesigningrequests.certificates.k8s.io is forbidden: User "system:serviceaccount:openshift-machine-config-operator:node-bootstrapper" cannot create certificatesigningrequests.certificates.k8s.io at the cluster scope: no RBAC policy matched
```

Take ownership of the bootstrapping CSR cluster roles from KubeCoreOperator

---

pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/aws/worker/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/openstack/worker/files/-etc-kubernetes-kubelet.conf
templates/_base/master/files/kubelet.yaml
templates/_base/worker/files/kubelet.yaml

When we migrated to the kubelet configuration file, the config disabled
the readOnlyPort by default. The port is enabled for the checkpointer
and other components to read from the kubelet without credentials.

kubelet: enable readOnlyPort for 10255

---

pkg/daemon/daemon.go

Otherwise, there's no sane way to check the OS version.

daemon: error out early if we can't talk to rpm-ostree

---

pkg/controller/template/test_data/templates/aws/master/units/kubelet.service
pkg/controller/template/test_data/templates/aws/worker/units/kubelet.service
pkg/controller/template/test_data/templates/libvirt/master/units/kubelet.service
pkg/controller/template/test_data/templates/libvirt/worker/units/kubelet.service
pkg/controller/template/test_data/templates/openstack/master/units/kubelet.service
pkg/controller/template/test_data/templates/openstack/worker/units/kubelet.service
templates/_base/master/units/kubelet.yaml
templates/_base/worker/units/kubelet.yaml

kubelet supports running as systemd unit and sends READY=1 signal when running.
https://github.com/kubernetes/kubernetes/blob/12cf5451952c8425a47334465f3e03d7ca181956/cmd/kubelet/app/server.go#L761-L762
/cc @crawford @sjenning @rphillips

templates: switch kubelet systemd unit to type notify

---

pkg/daemon/daemon.go
pkg/daemon/node.go

Currently when we finish an update, we re-check the desired config
and indiscriminately set the current config to it. This can cause
an update to be lost since the desired config may have changed
inbetween the isDesired check and when the map is updated. Instead
we should be updating the config to the one we checked for in
isDesired.
Tested the update process, seems fine to work.

mcd: fix race condition for annotation updates

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go
pkg/daemon/node.go

Change existing watch workflow to an informer instead, as watches
are prone to breaking and restarting the MCD. The Run() function
within MCD is changed from an infinite loop to instead block,
and updates are handled by callbacks via the informer.

daemon: use informers to check for updates

---

pkg/daemon/daemon.go

the node state validation function had a test right at the beginning
that checked if the values of the current annotation and the desired
annotation were equal. if they were, it returned, under the assumption
that because the annotations were equal the node was in the state we
wanted it to be in.
with the way that we try to behave, in general that would be true.
however, we instead opt for more rigorous testing of the node - every
time the validation function is called, it does a full validation of the
node state. if something changed, we attempt to reconcile the state back
to the desired. this also reflects the fact that nobody should be
modifying the node outside of the daemon, and if they do they should
expect to get clobbered.
also, my editor ran gofmt on the file and fixed the import …

pkg/daemon: remove annotation equality test from validation

---

pkg/daemon/daemon.go
pkg/daemon/rpm-ostree.go
pkg/daemon/update.go

Now that RHCOS is pre-pivoted (see
https://github.com/openshift/os/issues/307), we need to tweak the logic
here on how we handle `osImageURL`. Notably, we allow `://dummy` from
the installer to always match the current image, regardless of whether
we're pivoted or not. In fact, that should've been the logic from the
start.
Closes: #150

daemon: Adapt to OS being pre-pivoted

---

pkg/controller/template/test_data/templates/aws/master/units/setup-etcd-environment.service
pkg/controller/template/test_data/templates/libvirt/master/units/setup-etcd-environment.service
pkg/controller/template/test_data/templates/openstack/master/units/setup-etcd-environment.service
templates/_base/master/units/setup-etcd-environment.yaml

Requires: https://github.com/openshift/installer/pull/596
/cc @crawford

templates: use cluster-name.base-domain for etcd srv search

---

pkg/controller/template/render.go
pkg/controller/template/render_test.go
pkg/controller/template/test_data/templates/aws/master/units/etcd-member.service
pkg/controller/template/test_data/templates/libvirt/master/units/etcd-member.service
pkg/controller/template/test_data/templates/openstack/master/units/etcd-member.service
templates/_base/master/units/etcd-member.yaml

https://github.com/openshift/machine-config-operator/pull/155 missed changing the
--discovery-srv flag on etcd to cluster-name.basedomain
/cc @crawford

templates: fix etcd discovery-srv endpoint

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go
pkg/daemon/fsclient.go
pkg/daemon/fsclient_test.go
pkg/daemon/update.go

Non RHCOS nodes will need to apply an MC once and exit.
Requires: https://github.com/openshift/machine-config-operator/pull/139
/cc @aaronlevy @dustymabe @sdodson 
Still todo:

daemon: Run once mode

---

cmd/machine-config-daemon/start.go

Currently, if an invalid path is provided to mcd with
once-from, mcd will attempt to start in normal mode.
We validate the path later in the process, this commit
ensures we don't start mcd in normal mode by mistake.

MCD: Fix once-from start

---

pkg/daemon/daemon.go
pkg/daemon/daemon_test.go

This commit corrects logic to ensure ValidPath works as intended.
ilepath.Clean strips leading '.' from path and should be removed.

MCD: Fix ValidPath function

---

pkg/daemon/daemon.go
pkg/daemon/update.go

This will get past the `ostree` hit that @michaelgugino found on RHEL. I'm looking to see if there are any other hits that may cause an error on non RHCOS nodes just incase.

daemon: Only check osImageURL on RHCOS

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go
pkg/daemon/update.go

WIP: Enable from-ignition option
This commit enables mcd run-once to parse ignition file
directly instead of needing a MachineConfig.
This is useful first-booted clusters in BYO-RHEL

Ignition parse

---

pkg/operator/operator.go

configmap values are raw strings, not base64 encoded.
This makes the MCO bilingual until the installer pull merges
/assign @abhinavdahiya

accept unencoded configmaps

---

cmd/machine-config-controller/bootstrap.go
cmd/machine-config-operator/bootstrap.go
lib/resourcemerge/machineconfig.go
lib/resourcemerge/meta.go
manifests/bootstrap-pod.yaml
manifests/machineconfigcontroller/clusterrole.yaml
manifests/machineconfigcontroller/controllerconfig.yaml
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
pkg/controller/bootstrap/bootstrap.go
pkg/controller/template/render.go
pkg/controller/template/render_test.go
pkg/controller/template/template_controller.go
pkg/controller/template/template_controller_test.go
pkg/controller/template/test_data/controller_config_aws.yaml
pkg/controller/template/test_data/controller_config_libvirt.yaml
pkg/controller/template/test_data/controller_config_openstack.yaml
pkg/controller/template/test_data/templates/aws/master/files/-var-lib-kubelet-config.json
pkg/controller/template/test_data/templates/aws/worker/files/-var-lib-kubelet-config.json
pkg/controller/template/test_data/templates/libvirt/master/files/-var-lib-kubelet-config.json
pkg/controller/template/test_data/templates/libvirt/worker/files/-var-lib-kubelet-config.json
pkg/controller/template/test_data/templates/openstack/master/files/-var-lib-kubelet-config.json
pkg/controller/template/test_data/templates/openstack/worker/files/-var-lib-kubelet-config.json
pkg/operator/assets/bindata.go
pkg/operator/bootstrap.go
pkg/operator/operator.go
pkg/operator/render.go
templates/_base/master/files/pull-secret.yaml
templates/_base/worker/files/pull-secret.yaml

Updates the MCC to read pull-secret from `Secret` (used in cluster) or `Inline data` (used during bootstrapping).
This reads the `kube-system/coreos-pull-secret` Secret from the api.

Sync pull secret from `kube-system/coreos-pull-secret` to disk

---

pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/aws/worker/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/openstack/worker/files/-etc-kubernetes-kubelet.conf
templates/_base/master/files/kubelet.yaml
templates/_base/worker/files/kubelet.yaml

The readonly port is no longer needed since we do not depend on the pod checkpointer.
/cc @sjenning @rphillips

pkg/controller: disable kubelet readonly port

---

hack/build-go.sh

One of the CI runs shows `1.10.3` as the version chosen for build of machine config operator
```console
Pulling image "docker-registry.default.svc:5000/ci-op-39bh1qy5/pipeline@sha256:daa33010e3225f7abefc2358aaff9891353e86b3d7dde7257982fb487a298e6b" ...
Replaced Dockerfile FROM image registry.svc.ci.openshift.org/openshift/origin-v4.0:base
Pulling image docker-registry.default.svc:5000/ci-op-39bh1qy5/pipeline@sha256:02b13d581ad7d92b43d0557a26e804c06f7f35261cbed17ac91b21a468483ff9 ...
Pulling image registry.svc.ci.openshift.org/openshift/release:golang-1.10 ...
--> FROM registry.svc.ci.openshift.org/openshift/release:golang-1.10 as builder
--> WORKDIR /go/src/github.com/openshift/machine-config-operator
--> COPY . .
--> RUN WHAT=machine-config-operator ./hack/build-go.sh
Building …
```

hack: change override env for version in build-go.sh

---

cmd/machine-config-daemon/start.go

We had two "failed to initialize daemon" log messages in the
`runStartCmd()` function. One can still distinguish which one was
emitted since glog does print the line number too, but really that first
one wasn't accurate, so tweak it.

daemon: tweak log message

---

pkg/controller/template/render.go
pkg/daemon/daemon.go
pkg/daemon/update.go

The fact that `://dummy` is not a valid URL syntax was bothering me,
let's support (and default to) the empty string to mean unset.
Use a common function for handling this, and also change the comments
to clarify that we're not today "working around" the installer, it's
simply not specified.

Use "" for "unspecified OS", tweak comments

---

HACKING.md

`oc delete daemonset...` returns an error, the correct instruction is now `oc delete deploy...`

Update instructions to disable CVO.

---

pkg/controller/template/test_data/templates/aws/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/aws/worker/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/libvirt/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/libvirt/worker/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/openstack/master/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/openstack/worker/files/-etc-kubernetes-kubelet.conf
templates/_base/master/files/kubelet.yaml
templates/_base/worker/files/kubelet.yaml

@smarterclayton @ericavonb @mrogers950 @rphillips 
wait for https://github.com/openshift/cluster-machine-approver/pull/3 to merge and ensure that machine-approver is running

enable kubelet server cert bootstrapping

---

pkg/daemon/writer.go

We were using `%v` so need `f` for format.

daemon: Fix format message for degraded message

---

pkg/daemon/update.go

I was looking at this code again and realized this is probably
an issue.

daemon: Only log to recorder in cluster driven model

---

lib/resourceread/machineconfig.go
lib/resourceread/machineconfig_test.go
pkg/daemon/daemon.go

Use lib/resourceread for loading machineconfigs for the daemon. Added
basic testing for load function.

resourceread: use lib function for loading machine configs

---

pkg/daemon/update.go

I saw my master reboot (pretty sure it was the MCD) after I killed
the MCD pod to test something.  There was no event (must not have
gotten flushed? - wonder if we should wait a little bit for the
event to propagate...or be more conservative about rebooting masters?)
Anyways let's log to the systemd journal too.  Yes, this implementation
is crude but it works.

daemon: Log reboot reason to systemd journal as well

---

pkg/daemon/daemon.go
pkg/daemon/update.go
pkg/daemon/update_test.go

We really want admins to know *why* a system is degraded, so let's
add the precise error to the event log, and also log it to the
systemd journal just like we do reboots.
This changes the internal core `reconcible()` method to
return its error message rather than logging it itself, so we can
append it when we e.g. send the event.

daemon: Log degredation reason to journal and event too

---

HACKING.md

- The exact versions we tested with were quite old, no reason
to have those now.
- Use `oc scale --replicas=0` for the CVO so it's easy to turn
back on
- Add note about `oc project` for shorthand
- Use `1.` to let the Markdown renderer take care of incrementing
integers for us

HACKING.md: Tweak development instructions

---

pkg/controller/render/hash.go
pkg/controller/render/render_controller.go

This way it's easy to see at a glance where a given
config came from.  Now looks like:
```
$ oc get machineconfig
NAME                                      AGE
00-master                                 6h
00-worker                                 6h
...
master-e92af7e0bdc0591dc11405aeabb57ccd   1m
worker-50748faa54f9cc70af13c8686c2c7a28   1m
```

controller: Prefix generated configs with pool type

---

HACKING.md
Makefile
hack/cluster-push-prep.sh
hack/cluster-push.sh

I *just* got this working but I am feeling it's going
to be a *dramatic* improvement in my development workflow.
To set up, run `hack/cluster-push-prep.sh` once after doing
an install.  Then run `hack/cluster-push.sh` to deploy a new
MCD.  Use `env WHAT=machine-config-controller hack/cluster-push.sh`
to update the controller.
(Yes, these don't integrate with the `Makefile` yet...)

hack: Add cluster-push-*.sh scripts

---

pkg/daemon/daemon.go
pkg/daemon/update.go
pkg/daemon/update_test.go

The err return value in dn.reconcilable is never used.  Given that this function just does comparisons of config values, removing it to clean up function.

MCD: Remove unused error return value from reconcilable()

---

pkg/server/server_test.go

Future-proofing for folks who want to run the unit tests on Windows ;).

pkg/server/server_test: Use filepath.Join for path creation

---

pkg/server/api.go
pkg/server/api_test.go

We don't want folks `POST`ing, etc. to this server.  With this pull-request, we'll return the appropriate response status code if they do.

pkg/server/api: Return 405s for non-GET requests

---

HACKING.md
Makefile

Since we're in the machine-config-operator repository, typing
`machine-config-` is redundant.  Now one can just type e.g.
`make daemon` or `make controller`.  But we still support
`make machine-config-daemon` for backwards compat.

Makefile: Also support specifying just e.g. `make controller`

---

lib/resourceapply/machineconfig.go
manifests/controllerconfig.crd.yaml
manifests/machineconfigcontroller/controllerconfig.yaml
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/node/node_controller.go
pkg/controller/render/render_controller.go
pkg/controller/template/template_controller.go
pkg/controller/template/template_controller_test.go
pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/controllerconfig.go
pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/fake/fake_controllerconfig.go
pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/fake/fake_machineconfiguration.openshift.io_client.go
pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/machineconfiguration.openshift.io_client.go
pkg/generated/informers/externalversions/machineconfiguration.openshift.io/v1/controllerconfig.go
pkg/generated/informers/externalversions/machineconfiguration.openshift.io/v1/interface.go
pkg/generated/listers/machineconfiguration.openshift.io/v1/controllerconfig.go
pkg/generated/listers/machineconfiguration.openshift.io/v1/expansion_generated.go
pkg/operator/assets/bindata.go

MachineConfig and MachineConfigPools were made cluster scoped in #25
But I missed that ControllerConfig used by the machineconfigcontroller to create the OpenShift mananged MachineConfigs have to be owned by the ControllerConfig.
And ControllerConfig being a namespaced resource owning a cluster scoped resource MachineConfig does not make sense.
Also since MachineConfigController controls resources at cluster scope (MachineConfigs, MachineConfigPools, NodeUpdates), it makes sense to make it cluster scoped too.

pkg/apis:  controllerconfig needs to be cluster-scoped 

---

lib/resourcemerge/machineconfig.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/template/render.go
pkg/controller/template/render_test.go
pkg/daemon/update.go
pkg/daemon/update_test.go
pkg/operator/operator.go
pkg/operator/render.go

Closes https://github.com/openshift/installer/issues/578
Summary of issue: the ClusterConfig has the SSH key and while that key is being passed into the MCO, the MCO isn't properly adding it to the MachineConfig. This prevents us from being able add functionality to MCD updating existing SSH keys in a MachineConfig's Spec.Config.Passwd.Users.
Comments & feedback welcome!
cc: @abhinavdahiya @wking

Pass ssh keys from clusterconfig to machineconfig

---

pkg/daemon/update.go

Minor regression from 1d14b2a. We weren't passing the right variable to
`RemoveAll()`.
Closes: #268

 daemon: fix deletion of stale config files 

---

manifests/machineconfigdaemon/daemonset.yaml

Ensure that machine config daemon only runs on linux nodes.
This enables third-parties to explore Windows nodes on OpenShift.

manifests: machine config daemon node selector for linux

---

hack/build-go.sh

Using `: "${GOARCH:=${GOHOSTARCH}}"` since:
- it is DRY 
- avoids subsequent typos.
- The : will only apply the value if GOARCH is unset.
Also it is fixing a typo.

typo fix and better bash variable handling

---

docs/MachineConfigController.md

Clarify a few things about how templates are rendered into the "base"
OpenShift-owned MCs.
Related: #255

docs: add more details about the template controller

---

HACKING.md
README.md

The `README.md` of a Github repository is rendered very prominently;
really every project should attempt to describe succinctly *what*
the project does and a bit of *why*.
Since we already have a `HACKING.md`, move all of our developer-related
stuff consistently there.

docs: Describe more of what/why in README.md, devel stuff in HACKING.md

---

pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
pkg/apis/machineconfiguration.openshift.io/v1/helpers_test.go

Today each MC will contain both an Ignition fragment and an
`osImageURL`.  Define "merging" as using the first
non-empty `osImageURL` so we don't have to be very picky about
ordering.
This is a smaller version of
https://github.com/openshift/machine-config-operator/pull/228
Prep for: https://github.com/openshift/machine-config-operator/pull/273

controller: Take first non-empty osImageURL

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go
pkg/daemon/node.go
pkg/daemon/update.go

In the spirit of retrying all the things that could fail transiently,
just wrap the `/bin/pivot` call in a retry loop.
Closes: #276

daemon/update: retry pivot 5 times on failed rc

---

pkg/operator/assets/bindata.go

37599e13 added node selector to run only on linux, but did not update the operator bindata using `./hack/update-generated-bindata.sh`.
/assign @cgwalters

operator: fix bindata

---

pkg/daemon/update.go
pkg/daemon/update_test.go

Allow MCD to update SSH Keys.  
We are only allowing one user named "core" and only updating the field SSHAuthorizedKeys for this user.

Update SSH keys via MCD

---

Gopkg.lock
Gopkg.toml
pkg/daemon/constants.go
pkg/daemon/daemon.go
pkg/daemon/writer.go
vendor/gopkg.in/fsnotify.v1/AUTHORS
vendor/gopkg.in/fsnotify.v1/LICENSE
vendor/gopkg.in/fsnotify.v1/fen.go
vendor/gopkg.in/fsnotify.v1/fsnotify.go
vendor/gopkg.in/fsnotify.v1/inotify.go
vendor/gopkg.in/fsnotify.v1/inotify_poller.go
vendor/gopkg.in/fsnotify.v1/kqueue.go
vendor/gopkg.in/fsnotify.v1/open_mode_bsd.go
vendor/gopkg.in/fsnotify.v1/open_mode_darwin.go
vendor/gopkg.in/fsnotify.v1/windows.go

Add functionality to taint nodes with `rhcosSsh=accessed:NoSchedule`
when a user SSH's into the machine. This is done via a file watcher
that detects a write to `/var/tmp/ssh-taint`. Also add fsnotify package
and modify nodewriter to facilitate this.
This by itself does not currently affect behaviour on RHCOS nodes,
and is coupled with RHCOS changes to sshd config to write to above
file.
Tested to work with ssh access before the MCD is up, when the MCD
is running, and after removing the taint and re-sshing. The taint only
applies once even if multiple SSH happens.
Note: if the file watcher fails, the behaviour in the goroutine is to log it and
not degrade the node/error out. Maybe that should be changed.
cc/ @ashcrow @cgwalters @jlebon

daemon: taint node when an ssh access is detected

---

manifests/machineconfig.crd.yaml
manifests/machineconfigpool.crd.yaml
pkg/operator/assets/bindata.go

This makes the lists more informative
```console
$ oc get machineconfigpools
NAME      CONFIG                                    UPDATED   UPDATING   DEGRADED
master    master-49e4fc3d90841496575db504d606eb3c   True      False      False
worker    worker-e397e9633d67ced5bcbe3f4067715bff   True      False      False
oc get machineconfigs
NAME                                      GENERATEDBY                  IGNITIONVERSION   OSIMAGEURL
00-master                                 3.11.0-429-g9f6d7d5f-dirty   2.2.0
00-master-ssh                             3.11.0-429-g9f6d7d5f-dirty
00-worker                                 3.11.0-429-g9f6d7d5f-dirty   2.2.0
00-worker-ssh                             3.11.0-429-g9f6d7d5f-dirty
01-master-kubelet                         3.11.0-429-g9f6d7d5f-dirty …
```

manifests: include pretty column prints for some CRDs

---

docs/MachineConfigDaemon.md
docs/Update-SSHKeys.md

Document the canonical way to update SSH Keys via MCD. 
Documentation for: #115 
Closes: COREOS-488

docs: how to update sshkeys for user "core" via mcd

---

pkg/daemon/update.go
pkg/daemon/update_test.go

Add logic to updateSSH/reconcilable to account for machineconfigs where Passwd:Users is completely empty/unset.
Closes Issue: #292

daemon: fix updateSSHKeys for MC with Users unset/empty

---

pkg/daemon/update.go
pkg/daemon/update_test.go

Since nothing used it.  Also add a local variable for the target
URL to reduce noise.

daemon: Drop unused `oldConfig` parameter to update function

---

pkg/daemon/daemon.go

This confused me while grepping through the codebase. We were naming a
variable the same as its type. Compiled fine but shadowing it might have
caused issues in the future.

daemon: don't use type name as variable name

---

pkg/controller/render/render_controller.go

To reduce churn if MCs are being created rapidly - both on general
principle, and also to reduce our exposure to the current bug
that a booting node may fail to find a GC'd MachineConfig:
https://github.com/openshift/machine-config-operator/issues/301

controller: Add a 5s delay before rendering MCs

---

pkg/controller/kubelet-config/kubelet_config_controller.go

Adds the generated by annotation and version to KubeletConfig CR configmaps managed by MCC.

kubeletconfig: add the generated-by annotation

---

Makefile
cmd/common/client_builder.go
test/e2e/main_test.go
test/e2e/sanity_test.go

Add a basic test suite, targeting a test case for
44d5c52
This is inspired by the cluster-image-registry-operator tests:
https://github.com/openshift/cluster-image-registry-operator/blob/e6c7544903d2826d171be45cdde5a83a58d97383/test/e2e/main_test.go
Next step is to try hooking this up to Prow.
Related: #257
Replaces: #298

 test/e2e: New test framework

---

pkg/controller/render/render_controller.go

We were immediately returning from the function when ignoring an error
instead of moving on to the next MachineConfig in the list. Also, we
were completely ignoring errors we *shouldn't* ignore. For now, I've
just made this a warning rather than a hard failure pending discussions
re. garbage collection.

controller/render: fix ownerRef deletion error-handling

---

pkg/daemon/daemon.go
pkg/daemon/update.go

The same way we pass the specific desiredConfig we "locked on" when
updating, also similarly pass the currentConfig. This is a minor
optimization so we avoid querying the cluster again for information we
already have, but it does also make the code more resilient to humans
meddling with node annotations.
Requires: #310

daemon: skip querying currentConfig if possible

---

pkg/controller/template/test_data/README.md
pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/none/units/kubelet.service
pkg/controller/template/test_data/templates/worker/00-worker/aws/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
pkg/controller/template/test_data/templates/worker/00-worker/libvirt/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
pkg/controller/template/test_data/templates/worker/00-worker/none/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
pkg/controller/template/test_data/templates/worker/00-worker/openstack/files/-etc-kubernetes-kubelet-plugins-volume-exec-.dummy
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/units/kubelet.service
templates/master/00-master/_base/files/volume-plugins.yaml
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/00-worker/_base/files/volume-plugins.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

Fixes https://jira.coreos.com/browse/STOR-157
This parameter can not be configured via `KubeletConfiguration` because of  https://github.com/kubernetes/kubernetes/pull/72937

Provide a writable location for flexvolume plugins

---

pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/none/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/units/kubelet.service
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

Talked to @sjenning about cpu_manager_state.
When a node is drained there is not any cpu state to preserve. Preserving
this file also causes the kubelet to fail to startup when the
cpu_manager_state has changed from none to static (or vice versa).
ref: https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy
/cc @jeremyeder 
related to: https://github.com/openshift/machine-config-operator/issues/332

kubelet: always delete cpu_manager_state

---

pkg/operator/operator.go

Summary: PR #305 added logging to operator.go func sync(), which fills the MCO logs (as seen in `oc logs -f ...` ) with line output similar to `I0125 23:24:27.865406       1 operator.go:273] using osimageurl: registry.svc.ci.openshift.org/openshift/origin-v4.0-2019-01-25-191847@sha256:61dc83d62cfb5054c4c5532bd2478742a0711075ef5151572e63f94babeacc1a` approx 4 times every minute. 
This makes it difficult to read/watch the logs for other alerts/messages from the MCO.
Closes: #345

mco: remove osimageurl logging from sync() to make mco logs readable

---

pkg/controller/kubelet-config/kubelet_config_controller_test.go
pkg/controller/template/render.go
pkg/controller/template/render_test.go
pkg/operator/render.go

In order to incrementally roll new platforms out across the project
we must be able to provision platforms before all support is added.
Components should treat an unrecognized platform as "None", performing
the same function as they would in that scenario, and print a warning
to the logs.
Formalizing this requirement as we assess how future providers will
be added in openshift/installer#1112 (found in openshift/installer#1109)

mco: If the platform is unrecognized, treat the platform as 'none'

---

pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/daemon/fixtures/test1.txt

Files within ignition can be overwritten by later entries. This fixes
the validation to check all ignition written files for validity instead
of checking only the first.
This fixes an issue where the MCD marks a node as degraded when a file within ignition has overwritten a default config (ie: KubeletConfig)
/cc @jeremyeder @sjenning

daemon: fix overwritten files

---

pkg/daemon/daemon.go
pkg/daemon/update.go

We need special handling for the *initial* case where we boot
into a target config, but we may be using an old OS image.  Currently
the MCD would treat this as "config drift" and go degraded.
Today we write the node annotations to a file in `/etc` as part of the
rendered Ignition.  Use that as a "bootstrap may be required" flag,
and handle it specially - if we need to pivot, do *just* that and
reboot.
We also clean things up by unlinking that node annotation file; after
that, if the `osImageURL` drifts from the expected config, we'll go
degraded, just like if someone modified a file.

daemon: Handle osImageURL bootstrap

---

HACKING.md

Add a paragraph about turning debugging on using `oc patch` for any
given component.

HACKING.md: add paragraph to turn verbose on

---

manifests/machineconfigdaemon/daemonset.yaml

Make it clear in the manifest file that we don't actually make use of
the other mount points right now since we chroot early on.

manifests/daemon: add note about other mountpoints

---

pkg/daemon/constants.go
pkg/daemon/daemon.go
pkg/daemon/osrelease.go
pkg/daemon/update.go
pkg/daemon/writer.go

Went through a bunch of cleanup to be more idiomatic when writing Go
code (no else if previous return, default values, return on err, bool comparison etc etc)
(mainly went to read and learn the code)
There should be no functional change at all.
(so sorry for this PR :angel: )

pkg/daemon: idiomatic Go cleanup

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go
test/e2e/mcd_test.go

Because we `chroot()` we need to ensure that we can still see
the service account tokens injected into our pod.
Closes: https://github.com/openshift/machine-config-operator/issues/358

daemon: Bind /run/secrets/ in so we can see SA tokens

---

pkg/daemon/daemon.go

Fix #372, after this patch, no ssh/accessed annotation is applied on a machine config addition.
On reboot, the SessionNew subscribed channel gets closed
causing the node ssh/accessed annotation to be added.
This patch fixes that by checking if the channel is indeed
closing before going ahead and add the annotation.
Haven't added an e2e cause watching for something _not to_ happen is gonna be the best flake ever, I'll defer to add proper testing around ssh/accessed being added on real login in a follow up.

pkg/daemon: check channel closing

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go

If there would ever be a way to reconcile a Degraded node, I believe it
would be worth to still learn if someone jumped on a node and messed up
with it so we can decide what to do.
Feel free to close this telling I'm dumb as well, I'm probably missing some context which led to this PR while playing around reading the code but it makes sense to me to still have something like this. This is also not fixing anything related to super early startup where someone can jump on a node _before_ the daemon is running and tracking accesses.
This PR builds on #373, I'll rebase it once that merges

 pkg/daemon: run login monitor for Degraded nodes

---

OWNERS
OWNERS_ALIASES
cmd/machine-config-daemon/OWNERS
manifests/machineconfigdaemon/OWNERS
pkg/daemon/OWNERS
pkg/operator/assets/OWNERS

We're reorganizing the teams to have part of the RHCOS team own
this operator too.

OWNERS: Rework to move everyone to toplevel, add runcom

---

cmd/machine-config-server/bootstrap.go
cmd/machine-config-server/main.go
cmd/machine-config-server/start.go

Change machine-config-server ports from 49500/49501 -> 22623/22624
to avoid conflict with local port and node port ranges.
Closes: #166
Related-to: https://github.com/openshift/installer/pull/1180

MCS: change machine-config-server ports

---

test/e2e/mcd_test.go

Far away from being the right tests we need to test this whole workload
but it's a start. Just making sure we can see the daemon (1) actually
converge to the new config. (Next step would be to deploy a pod with
an hostPath referencing an MC file, exec into this pod and verify
the file is rightly there)

test/e2e: add MC smoke test

---

pkg/daemon/update.go

Don't want to fail on transient errors.
Closes: #393

update: Retry Drain() multiple times

---

Makefile

Since Go 1.10, test results get cached. This leads to the tests not being run
sometimes because Go has cached the results and just assumes it will get the
same results because the Go code hasn't changed.
Set GOCACHE=off to get clean results everytime (this is especially good
for us since we can poke at the cluster and rerun the test w/o having to
change go code).

Makefile: set GOCACHE=off in tests

---

install/0000_30_machine-config-operator_06_clusteroperator.yaml
pkg/operator/sync.go

Closes https://github.com/openshift/machine-config-operator/issues/383

pkg/operator: lay down ClusterOperator for MCO

---

pkg/daemon/update.go

Saw
```
E0211 21:20:54.783163   68957 daemon.go:384] Fatal error checking initial state of node: Checking initial state: pending config master-e36ac826fbfdf3342e5579460c64658e bootID 4f94db9f-79a2-43be-8630-4fb276eb2e14 matches current! Failed to reboot?
E0211 21:20:54.783186   68957 writer.go:91] Marking degraded due to: Checking initial state: pending config master-e36ac826fbfdf3342e5579460c64658e bootID 4f94db9f-79a2-43be-8630-4fb276eb2e14 matches current! Failed to reboot?
```
on chat.  Thinking about this, we could hit this case if e.g.
the MCD was restarted during the drain (or more generally between
where we were writing the pending file and rebooting).
Let's write it just before reboot to reduce the chance of hitting
those cases.

daemon: Write out pending state file just before reboot

---

cmd/machine-config-operator/bootstrap.go
pkg/operator/images.go
pkg/operator/operator.go

Since having a mismatch here will result in a broken cluster,
change things so that the command line arguments are required
and drop the `docker.io` image references.  We never want
to pull those into a real cluster.
Ref: https://github.com/openshift/machine-config-operator/issues/367

bootstrap: Require images on command line

---

pkg/daemon/update.go

Saw this in a log:
```
I0211 21:20:46.924255   61902 daemon.go:660] Unable to apply update: rpc error: code = Unknown desc =
```
It must be from the drain; let's make that clear.

daemon: Clearly log if error is from draining

---

install/image-references

This isn't the long term path, but let's do this until
we have that implemented.

image-references: Update maipo oscontainer

---

pkg/daemon/update.go

That way, we get more feedback when retrying since it can take a while.
And we also catch the instance when e.g. different errors might have
happened each time.

daemon/update: Log each error before retrying

---

pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/daemon/update.go

`contents.Data` is a byte slice and can be anything (i.e. a binary after
deconding). Use a bytes writer to prevent misbehaves in such scenarios.
Along with that, use a buffered writer around the file in case we're
dealing with big files. Also, compare byte slices as well instead of
using strings.

pkg/daemon: write bytes, use buffered writer and compare bytes

---

Gopkg.lock
hack/build-go.sh
pkg/daemon/rpm-ostree.go
vendor/github.com/coreos/go-systemd/dbus/dbus.go
vendor/github.com/coreos/go-systemd/dbus/methods.go
vendor/github.com/coreos/go-systemd/dbus/properties.go
vendor/github.com/coreos/go-systemd/dbus/set.go
vendor/github.com/coreos/go-systemd/dbus/subscription.go
vendor/github.com/coreos/go-systemd/dbus/subscription_set.go
vendor/github.com/coreos/go-systemd/sdjournal/functions.go
vendor/github.com/coreos/go-systemd/sdjournal/journal.go
vendor/github.com/coreos/go-systemd/sdjournal/read.go
vendor/github.com/coreos/pkg/LICENSE
vendor/github.com/coreos/pkg/NOTICE
vendor/github.com/coreos/pkg/dlopen/dlopen.go
vendor/github.com/coreos/pkg/dlopen/dlopen_example.go

Rather than directly executing `pivot` from within the container, use
its new service unit to run it. The main advantage of this is that
`pivot` can correctly run `ostree` as `install_t` which is required for
writing new SELinux labels. More generally though, we should be running
such host tools within the host context rather than from the container.
This works nicely though the downside is that we lose progress output
from pivot. I'd like to add journal proxying to fix that.
Closes: #314 
Requires: https://github.com/openshift/pivot/pull/25

Use pivot.service to perform pivot

---

hack/build-go.sh

This saves about ~20MB for the resulting daemon image (we've been doing this in CRI-O and other Runtimes tools for a while now)

hack/build-go: strip debuginfo from binaries

---

pkg/daemon/daemon.go
pkg/daemon/update.go
pkg/daemon/update_test.go

Pointer to strings in Golang as used rarely and almost only for struct
properties when deserializing json or yaml (or anything) into a structure.
Else, the idiomatic way of informing something isn't right it's through
errors only. Errors in Go do also have an handy `.Error()` which represents
the error as a string for our use cases.
Second commit unexports consts not used outside the daemon package.

[cleanup] pkg/daemon: do not use pointers to strings for errors + unexport consts

---

pkg/daemon/daemon.go

Reads the journal checking for logind message ID and annotates the node
with the ssh accessed label if it finds out there were previous
accesses.
Close #379 

pkg/daemon: detect ssh accesses before daemon started

---

examples/kubeletconfig.crd.yaml
pkg/controller/kubelet-config/kubelet_config_controller.go

@umohnani8 found out that KubeletConfigs were hanging on deletes caused by the reference not getting updated. This PR expands the comparison for the update event to look at the entire object instead of just the spec.
Additionally, a second commit fixes the kubeletconfig example within the examples folder.

kubelet config deletions fix + example update

---

pkg/controller/node/node_controller.go
pkg/controller/node/node_controller_test.go

A few patches for the node controller to help me debug https://github.com/openshift/machine-config-operator/pull/385

Controller logging

---

docs/HACKING.md

The instructions didnt work for me and I hit errors.  `oc login` needed `--server=` 
Also added a `-f` in the watching logs command to stream the logs.

docs: update oc commands for watching a live ci cluster

---

docs/HACKING.md

Please go over it by testing the flow as well to make sure it's correct (I just did and it works for me (tm)).
Please also correct any of my mistakes in english lol

docs: HACKING.md: add custom payload build section

---

pkg/daemon/update.go

we missed checking it https://github.com/openshift/machine-config-operator/blob/master/pkg/daemon/update.go#L92
also, refactored the condition function a bit to be more future proof (i.e. someone comes and add a `return false, err`)

pkg/daemon/update.go: check wait err and wrap it

---

cmd/machine-config-server/bootstrap.go
cmd/machine-config-server/start.go

legacySecureServer and legacyInsecureServer were added to accommodate the
installer port references when we transitioned the MCS ports from 49500/49501
to 22623/22624. The installer was updated via PR #1180 to use 22623/22624, so
we can now remove the legacy server/port references.
Clean-up step for: #166 
Related to: #368 
Related-to: [openshift/installer#1180](https://github.com/openshift/installer/pull/1180)

MCS: remove legacy servers & ports

---

pkg/daemon/update.go
pkg/daemon/update_test.go

Minor updates that I wanted to fix/cleanup since my last ssh pr:
1. remove user.name check this is already done in reconcilable() and is unnecessary here
2. use consts for "core" and core's filepath "/home/core/ssh" to make it more consistent and maintainable.

mcd: remove unnecessary checks and simplify updateSSHKeys

---

pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/controller/kubelet-config/kubelet_config_controller_test.go

ObservedObservations and Generations were a new concept to me...
Adds support for KubeletConfig Status updates and generations comparisons. Fixes KubeletConfig Updates where the status will get updated causing the watch to trigger an unlimited amount of times.

kubeletconfig: add support for observedgeneration

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Bring github templates for issues and PRs so people actually document what they're doing in any issue or PR.

.github: add templates for issues and PRs

---

cmd/machine-config-operator/bootstrap.go
pkg/operator/bootstrap.go
pkg/operator/operator.go

For https://github.com/openshift/installer/pull/1179 it's necessary to include the now self-signed kube-ca in the /etc/kubernetes/ca.crt file for kubelets, since the PR makes root-ca no longer a valid trust anchor for the API server certs. I think this is the correct spot to modify to change /etc/kubernetes/ca.crt, and I'm opting to append it rather than replace the root CA for now to make sure nothing else breaks. (There might be a different configmap that it would be better to grab kube-ca from.)
/cc @abhinavdahiya @deads2k @openshift/sig-auth

append kube-ca to root-ca for mco config

---

pkg/daemon/daemon.go
pkg/daemon/node.go
pkg/daemon/update.go
pkg/daemon/writer.go

I think this is what's causing the issue in:
https://github.com/openshift/machine-config-operator/issues/395#issuecomment-462482242

daemon: Add GetNode() wrapper which retries on errors

---

pkg/operator/status.go
pkg/operator/sync.go

Based on:
- https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md#conditions
- Slack conversation with Clayton
We should correctly report Progressing only when really progressing towards something. Re-syncing, reconciling, drift detections verifying everything is still where you left it is not _changing_ something, thus is not progressing.
closes #346
/cc @smarterclayton @abhinavdahiya ptal

pkg/operator: correctly sync status for the CVO

---

cmd/machine-config-controller/bootstrap.go

Not immediately essential of course, but pretty harmless too.

cmd/controller: Fix minor typo in error message

---

pkg/controller/node/node_controller.go
pkg/controller/node/node_controller_test.go
pkg/controller/node/status.go
pkg/controller/render/render_controller.go
pkg/controller/template/render.go
pkg/controller/template/template_controller.go

- use the object given by range directly, no reason to access the array by index, slices in Golang are guaranteed to be ordered as well
- use int instead of int32 to remove unnecessary casts
**- How I did it**
vscode
CI I guess

[cleanup] pkg/controller: don't use index in ranges, use int instead of int32

---

.github/PULL_REQUEST_TEMPLATE.md

Discussed with @runcom and decided to remove the How I did it section to keep this template simple.
**- How I did it**
remove template section --> template section removed!
n/a

templates: remove How I did it section from PR template

---

pkg/operator/status.go
test/e2e/mco_test.go

This patch populates the RelatedObjects field of the MCO ClusterOperator
so openshift/must-gather can consume it. We're just exposing our own
namespace for the tool to scrape.
Build a custom payload from this PR, create a cluster with it, run `oc describe clusteroperator machine-config` and confirm the "Related Objects" section is populated with our namespace

pkg/operator: link related objects to clusteroperator

---

README.md

fixed broken link in README.md to HACKING.md now that it resides under docs/
check the README.md from this PR

README.md: fix link to HACKING.md

---

pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/controller/kubelet-config/kubelet_config_controller_test.go

@umohnani8 found a bug in kubeletconfig updates. This PR adds a unit test and fixes the underlying validation.
Unit test
Fix KubeletConfig updates not being applied correctly to the MachineConfig.
Also fixes race conditions found in:
Close #417

kubeletconfig: fix updates, add unit test, race condition fix

---

Dockerfile.machine-config-daemon
Dockerfile.machine-config-daemon.rhel7

As part of the general cleanup we are moving to UBI based Docker images
and util-linux is being removed from the base image. Add an explicit
dependency here.

image: MCD depends on util-linux (mount) which is being removed from base

---

test/e2e/mcd_test.go

TestMCDeployed wasn't checking that the MC was indeed deployed on every
node (worker). Fix that by checking every node. The test is going to
take a little longer but it's more robust as well.
run e2e

test/e2e: check MC deployed on every node

---

install/image-references
pkg/controller/template/render.go
pkg/daemon/constants/constants.go
pkg/daemon/rpm-ostree.go
pkg/server/bootstrap_server.go
pkg/server/cluster_server.go
pkg/server/server.go
test/e2e/osimageurl_test.go

We landed a lot of code to have the MCD call out to `pivot.service`;
this builds on that to implement an "early pivot" model where
we do the OS update before the node even joins the cluster.
This should result in less disruption, though debuggability is weaker.

server: Implement "early pivot" before the MCD comes up

---

pkg/daemon/update.go

The code was just checking `/home/core` but we later try to write to `/home/core/.ssh` (that folder is surely there but this needs to be fixed anyway).
I've centralized file writes in https://github.com/openshift/machine-config-operator/pull/401 as well to reduce the chances of doing this again.

pkg/daemon: ensure /home/core/.ssh is there, not just /home/core

---

pkg/daemon/daemon.go

Without this we end up in a reboot loop.  Happened
for the UPI scaleup tests on CentOS (classic).

daemon: Don't do OS updates/pivoting on !RHCOS

---

Dockerfile.machine-config-daemon.rhel7

RHEL builds broke because this dockerfile was not also updated.

Fix RHEL image typo

---

cmd/machine-config-operator/bootstrap.go

This PR is a follow-up regarding https://github.com/openshift/machine-config-operator/pull/420#issuecomment-463721284
The installer now uses the flag with https://github.com/openshift/installer/pull/1266.
/cc @cgwalters

bootstrap: set --kube-ca default to empty

---

cmd/common/client_builder.go
cmd/machine-config-operator/start.go
pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/status_test.go

I added a wrapper around the ClusterOperators client mainly for unit tests in #442  which turns out to be totally unnecessary since I've learned about fake clients in kube land. This PR removes that wrapper and turns the code back to its state and just use plain fake clients in unit tests which will reduce code and not needed abstractions.

pkg/operator: use fake clients in unit

---

pkg/controller/container-runtime-config/container_runtime_config_controller.go

A resync happens about every 20 minutes, which sends an updated
event to the image informer even if nothing in the image CR has
changed. Adding and extra filter that checks if there has been
any changes to the registries part of the image CR before syncing
the image handler again.
Helps fix https://github.com/openshift/machine-config-operator/issues/453 where changes to the image config will not be applied unless and actual change happened in the CR.

Add extra filter for checking if registries have changed

---

pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
pkg/controller/kubelet-config/kubelet_config_controller_test.go
pkg/controller/node/node_controller_test.go
pkg/controller/render/render_controller_test.go
pkg/controller/template/template_controller_test.go

The indexer in the informer uses a store which manages object using a read-write lock, the flakes come from the fact that if we don't sync up the store before adding objects, the listing of objects can race against an add (verified this by adding a bunch of debug logs during investigation and I could spot that `lister.List` can return empty even if we added objects to the indexer before starting the informers themselves).
Fixes #417 
Fixes #444 
Fixes #451 
Fixes #449 
Cannot reproduce anymore with this patch (running in a loop since 3 hours now), I'm able to consistently reproduce by running `go test -race` w/o this patch.
```
true && while [ $? -eq 0 ]; do GOCACHE=off go test -race -v ./cmd/... …
```

pkg/controller: start informers before populating store in tests

---

manifests/machineconfig.crd.yaml
pkg/operator/assets/bindata.go

We really want this driven by the CVO; people should look at
`oc get clusterversion`.
See also https://github.com/openshift/os/issues/377

machineconfig: Drop osimageurl from `oc get machineconfigs`

---

Dockerfile.machine-config-daemon.upstream
hack/build-image.sh
hack/cluster-push-prep.sh
hack/cluster-push.sh

Make `make deploy-daemon` work again.

Upstream mcd dockerfile

---

manifests/machineconfigdaemon/daemonset.yaml
pkg/daemon/daemon.go
pkg/daemon/update.go

Ref: https://github.com/openshift/machine-config-operator/issues/407
The MCD is not ready to be killed at any arbitrary point.  Bump
the termination timeout to 5 minutes, and ignore `SIGTERM` if we're
in the middle of performing an update.

daemon: Catch SIGTERM and ignore it if we're doing an update

---

pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/daemon/update.go

The way CI works, a release payload is generated in the CI namespace
but reusing the digested pull of existing components.  This means
the pull specs for *everything* change format - but the actual
content stays the same.
Let's handle this for the OS image at least.
In practice...I feel like we're going to want higher level special
handling for this - maybe the CVO does pull-through to the registry
and rewrites to an internal canonical form, but this should help
us for now.
Closes: https://github.com/openshift/machine-config-operator/issues/462

daemon: Accept osImageURL with matching digests

---

Makefile

`make images` and the other targets were just creating this file named `1` because the redirection is inverted
run `make images` and watch it not creating a file named `1`

Makefile: fix io redirection for image targets

---

pkg/controller/container-runtime-config/container_runtime_config_controller.go

The CRC (container runtime config) controller recently added a check to
avoid resyncing and recreating the very same registries config if
nothing has changed on the image crd side [1]. While that's correct,
during an upgrade, the controllers need to generate the MC fragments
using the controller version they're at. Since we weren't checking the
versions of the controller that generated the registries config, we
wrongly assumed the configurations were equal and never generated a new
one with the new controller.
This patch fixes that by adding a version check before skipping a
regeneration on equal content in the registries configs.
Fixes: https://github.com/openshift/machine-config-operator/issues/487
[1] https://github.com/openshift/machine-config-operator/pull/461
Signed-off-by: Antonio …

 pkg/controller: fix container runtime registries generation

---

pkg/daemon/update.go

This way we're not delaying shutdown.
Closes: https://github.com/openshift/machine-config-operator/issues/486

daemon: Uninstall SIGTERM handler just before rebooting

---

cmd/machine-config-operator/bootstrap.go

Adding this, so we can get the installer PR https://github.com/openshift/installer/pull/1292 in first
before landing in #471.
This is from an approved and lgtm'ed PR #471.

Add infra-image flag to bootstrap.go as no-op

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go

Don't crash on non-rpm-ostree based systems.

daemon: Only print status if os == RHCOS

---

install/image-references

This is to ensure that the image is injected when the
installer is run.
This from an already approved & lgtm'ed PR #417
Installer PR: https://github.com/openshift/installer/pull/1292

Add pod image to image-references

---

pkg/daemon/daemon.go
pkg/daemon/node.go
pkg/daemon/update.go
pkg/daemon/writer.go

The node object is around most of the time (`handleNodeUpdated` for instance). When it's not a call is sufficient to get it and pass it around This reduces the call frequency to the api server.
This PR has been extracted from #460 and can go in w/o that. It allows us, working on PRs similar to #460 to have less places which can return a transient error from the apiserver and act accordingly.
e2e should cover most of this I guess

pkg/daemon: stash the node object

---

examples/machinecontrollerconfig.deploy.yaml
manifests/bootstrap-pod-v2.yaml
manifests/machineconfigcontroller/deployment.yaml
pkg/operator/assets/bindata.go

I made updates to eliminate the use of cpu limits for components that run on control plane.  The intention is to depend entirely on CPU requests and CFS sharing for allocating CPU time.  Setting limits just induces unnecessary latency.
Pass this smoke test:
https://github.com/openshift/origin/pull/22095/files
No longer set cpu limits for components in favor of just setting cpu requests.

Eliminate use of cpu limits

---

pkg/daemon/update.go
pkg/daemon/update_test.go

Closes: #479 
create a proper machineconfig and `oc create -f` it - SUCCESS!:
```
metadata:
labels:
name: good-test
spec:
config:
ignition:
version: 2.2.0
storage:
files:
- contents:
source: data:,hello%20world%0A
verification: {}
filesystem: root
mode: 420
path: /home/core/prtest
```
create a bad/invalid machineconfig (here we are using a relative path which is bad) and apply it - Failure!
```
metadata:
labels:
name: bad-test
spec:
config:
ignition:
version: 2.2.0
storage:
files:
- contents:
source: …
```

MCD: add ign validation check for mc.ignconfig

---

Makefile

added bindata generation to `make update`. This came out from #503 where we also noticed that a previous PR didn't correctly generated bindata https://github.com/openshift/machine-config-operator/pull/503/files#diff-180d80e1c6d7634b2dd083e60c06459bR598
run make update and make sure bindata is correctly (re)generated

Makefile: add bindata generation to update target

---

docs/Update-SSHKeys.md

The previous version had the SSH keys listed as `- ssh rsa AAAA...`, so I
thought the MCO was doing some sort of magic parsing.  Turns out it
needed the commonly seen representation of `- ssh-rsah AAAAA...`
I added a few examples showing how you can provide different key types
and cleaned up some trailing whitespace.

docs/Update-SSHKeys: fix SSH key example

---

OWNERS

Active members of the MCO group are not getting tagged onto MCO PRs quite frequently. As more development is done on this repo, we need to clean up this list so that active members always have the ability to be pinged, review and approve MCO repo PRs and are aware of all of the PRs that are merged.
This PR is also needed to clean-up the Owners file in release (https://github.com/openshift/release/issues/2980), where MCO team members are not being pinged.

clean up OWNERS file so that MCO team is always tagged

---

cmd/machine-config-operator/bootstrap.go
install/0000_30_machine-config-operator_02_images.configmap.yaml
install/image-references

The name needs to *exactly* match that in `image-references`
in order to be substituted.

install: Fix reference to pod image

---

pkg/daemon/daemon.go

Was in the middle of an issue with my code and the reference erroring out wasn't provided, adding it to ease debugging (and my life)

pkg/daemon: add more info to errs

---

install/0000_30_machine-config-operator_02_images.configmap.yaml
install/image-references

We are currently using upstream etcd image which is based on Alpine Linux OS. This PR updates this to the correct origin-v4.0 etcd image build.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1679834
/cc @abhinavdahiya

install: use origin-v4.0 etcd image

---

pkg/controller/node/node_controller.go
pkg/controller/node/node_controller_test.go

There are a bunch of logs like these today:
```
I0301 14:49:44.146628       1 node_controller.go:432] Setting node ip-10-0-148-83.us-west-2.compute.internal to desired config worker-e854dfc4700db876403a02746b62bd99
I0301 14:49:49.164555       1 node_controller.go:432] Setting node ip-10-0-135-231.us-west-2.compute.internal to desired config worker-e854dfc4700db876403a02746b62bd99
I0301 14:50:05.687080       1 node_controller.go:432] Setting node ip-10-0-171-131.us-west-2.compute.internal to desired config worker-e854dfc4700db876403a02746b62bd99
I0301 14:50:10.697380       1 node_controller.go:432] Setting node ip-10-0-135-231.us-west-2.compute.internal to desired config worker-e854dfc4700db876403a02746b62bd99
I0301 …
```

pkg/controller: avoid a patch call if the node is already at desired config

---

hack/push-image.sh

PR #474 broke hack/push-image.sh (and my workflow) by renaming the generated
images.  This PR fixes the names used in this script, so the
latest can be pushed to a remote repo like dockerhub.
I'd like to eventually re-add VERSION support, but I don't have time, so it's commented out for now.
try using the push-image.sh note how it doesn't work. update to use this pr and now it successfully pushes like it did pre-474

update hack/push-image.sh to rename images

---

cmd/machine-config-operator/bootstrap.go
install/0000_30_machine-config-operator_02_images.configmap.yaml
install/image-references

When https://github.com/openshift/installer/pull/1292 lands
this will undo the hacks to enable the CVO-driven pod image.

bootstrap: Final switch to CVO pod image

---

install/0000_30_machine-config-operator_04_deployment.yaml
manifests/machineconfigcontroller/deployment.yaml
manifests/machineconfigdaemon/daemonset.yaml
manifests/machineconfigserver/daemonset.yaml
pkg/operator/assets/bindata.go

Add priorityClassName for machine-config-* related entities to guarantee scheduling.
blocks passing smoke tests for ensuring control plane pods always schedule.
see: openshift/origin#22217
Add priorityClassName for machine-config-* related entities to guarantee scheduling.

manifests: set priority class

---

install/0000_30_machine-config-operator_04_deployment.yaml
install/0000_30_machine-config-operator_06_clusteroperator.yaml
pkg/controller/render/render_controller.go
pkg/controller/template/render.go
pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/status_test.go

The other components versions can be left as they are to use the image
pullspec. This is not changing the version we report when starting every
component though for our debugging sanity.
This is a 4.0 requirement to pass https://github.com/openshift/origin/pull/22156

pkg/operator: set operator version to release payload version

---

pkg/controller/template/render.go

This is a workaround for us switching to an authenticated pause
image and crio not knowing how to use the kubelet's auth for this.
https://bugzilla.redhat.com/show_bug.cgi?id=1686556

Bug: 1686556: Symlink /root/.docker/config.json to kubelet auth

---

pkg/daemon/daemon.go
pkg/daemon/node.go
pkg/daemon/osrelease.go
pkg/daemon/rpm-ostree.go
pkg/daemon/update.go
pkg/daemon/writer.go

Set first char to lowercase for all error strings to conform to golang conventions.
Files changed: daemon.go, node.go, osrelease.go,
rpm-ostree.go, update.go, writer.go
Related-to: #501

mcd: fix error string capitalization

---

pkg/controller/container-runtime-config/container_runtime_config_controller.go

Came across this while in the file container_runtime_config_controller.go. We already have a var `rci` that has the value of `createNewRegistriesConfigIgnition(registriesTOML)`. Used this var a few lines down instead of making another call to `createNewRegistriesConfigIgntion(registriesTOML)` with same args again.
Also renamed `rci` to a clearer name `registriesIgn`.
cc: @umohnani8

mcc: container runtime: remove duplicate function call and use existing var

---

pkg/controller/common/helpers.go
pkg/controller/container-runtime-config/helpers.go
pkg/controller/template/render.go
pkg/controller/template/render_test.go

Closes: #498 
Pre-req for: #502 
`oc get machineconfigs` should have a version for both.
also `e2e-aws` and `e2e-aws-op` in `artifacts/e2e-aws/machineconfigs.json` should show the ssh configs & registry configs as having version numbers.

mcc: add ignition version for ssh & registries machineconfigs

---

pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/none/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/units/kubelet.service
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

Enumerates the OS version from /etc/os-release and creates a `node.openshift.io/os_version={OS_VERSION}` label.
oc get node [node name] -o yaml
Add an initial OS Version to label (`node.openshift.io/os_version={OS_VERSION}`) to nodes.
**- Some background info**
Kubelet --node-labels only get created on kubelet registration, so changes will need to happen with a daemonset. Liggit has a [number](https://github.com/kubernetes/kubernetes/issues/59314) of [comments](https://github.com/kubernetes/kubernetes/issues/59314#issuecomment-362869655) in upstream saying the kubelet should not update labels, so a custom patch would probably never be merged upstream (IMO). There are differing opinions on the ticket.
This PR is …

initial pass at populating the os version label

---

pkg/controller/kubelet-config/kubelet_config_controller.go

Blacklists `ConfigMapAndSecretChangeDetectionStrategy` from being user changeable.
ref: https://github.com/openshift/machine-config-operator/issues/520
ref: https://github.com/openshift/origin/pull/22236
None

kubelet-config: prevent changing the ConfigMap and Secret Changing Strategy

---

pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/node/status.go
pkg/operator/sync.go

We want to get rid of "degraded" someday; but today is not that day.
In the meantime, let's make clear that there's a degraded node
in a pool status, as distinct from "unavailable".

controller: Report number of degraded machines in pool

---

pkg/controller/kubelet-config/kubelet_config_controller.go

We were processing a circular amount of update events (which included
Status updates). This patch detects a real change within the
kubeletconfig.
This patch also fetches a fresh config so we limit the 'please apply your changes to the latest version and try again' messages.
Upon creation of a KubeletConfig the controller will not dump a series of error messages.
Fix KubeletConfig circular updates ultimately printing a series of error messages in the MCC log.

kubelet-config: accurately detect object updates

---

Makefile
test/e2e/mcd_test.go

Modified the e2e MC test to roll out MCs more than just once to understand if rolling MCs just goes ok
run e2e or wait CI reports

test/e2e: roll out new MCs more than just once

---

pkg/controller/render/render_controller.go
pkg/controller/render/render_controller_test.go
pkg/controller/template/render.go
pkg/controller/template/render_test.go
pkg/controller/template/template_controller.go

- Add check in render_controller.go to ensure that all machineconfigs to be merged in
getRenderedMachineConfig() contain valid ignition configs.
- Add unit test for getRenderedMachineConfig() to test ign validation
- Add missing unit test for GetMachineConfigsForPool()
- Rename confusing function names in controller which caused problems while working on this PR: 
generateMachineConfig() -> generateRenderedMachineConfig()
generateMachineConfigs() -> generateTemplateMachineConfigs() 
Closes: #502 
Related-to: #505

mcc: add ignition validation to render controller

---

hack/build-go.sh
pkg/daemon/daemon.go
pkg/daemon/rpm-ostree.go
pkg/daemon/update.go
pkg/daemon/update_test.go

The way the MCD today chroots into the host is problematic
for major OS version updates and creates a hidden dependency.
Eventually we need to stop chrooting, see:
https://github.com/openshift/machine-config-operator/issues/543

daemon: Drop all dependency on cgo and external shlibs

---

manifests/machineconfigpool.crd.yaml
pkg/apis/machineconfiguration.openshift.io/v1/helpers_test.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/node/node_controller.go
pkg/controller/node/status.go
pkg/controller/node/status_test.go
pkg/daemon/daemon.go
pkg/operator/assets/bindata.go
pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/sync.go
test/e2e/mcd_test.go

This PR is a follow up from #548 which accounts for the change in behavior that we introduced with that. Most notably:
- we are never in a permanent Degraded state anymore, we flip Working and Degraded but the logic for determining the updated/unavailable machines rely only on current/desired annotation. I'm going to fix that and remove Degraded
- progressing on applying a machineconfig is currently broken because of the above, so max unavailable isn't respected
- with #548, we can now delete a bad machineconfig which is erroring out in a loop, and just reapply the old one which is going to just stabilize the machine again
- probably something else I'm still not aware of but I'm actively testing
This PR includes …

Fix MCD status reporting, retry loop and max unavailable progress

---

cmd/machine-config-operator/bootstrap.go
pkg/operator/operator.go

This PR is the final action to enable kube-client-agent to be part of the release payload.
depends on: https://github.com/openshift/installer/pull/1429
ref: https://github.com/openshift/machine-config-operator/pull/538
/hold

*: set kube-client-agent-image flag as required

---

pkg/daemon/constants/constants.go
pkg/daemon/daemon.go
pkg/daemon/update.go
pkg/daemon/writer.go

pkg/daemon: keep degraded state after failure
Now that the Degraded state is just a state with the only scope of being
informative, keep it instead of just flipping between Working->Degraded
when we fail. When an MC degrades the machine, it still keeps retrying
to reconcile but at least administrators know that something is wrong
instantly.
pkg/daemon: add an Unreconcilable state
This new state is, like Degraded, the way we communicate to
administrators that something went specifically wrong with their
MachineConfigs. A natural follow up to this would be going ahead and
expose the real error on the object itself. With this state admins can also
just delete the bad MC and roll back.

pkg/daemon: don't flip Degraded/Working and add an Unreconcilable state

---

docs/MachineConfigController.md
docs/MachineConfigServer.md
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/server/api.go
pkg/server/bootstrap_server.go
pkg/server/cluster_server.go
pkg/server/server_test.go

There seems to have been some initial uncertainty about what this would be called, with `MachinePool` first landing in 30d522f9 and `MachineConfigPool` first landing in cfc9660e (#2).  This commit consolidates us around `MachineConfigPool`, except for the `machine-pools/` bootstrap path (since changing that would require consumer updates).

*: Update "MachinePool" -> "MachineConfigPool" and similar

---

pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/none/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/vpshere/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vpshere/units/kubelet.service
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

Fixes https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/11343/pull-ci-openshift-openshift-ansible-devel-40-e2e-aws-scaleup/581/build-log.txt
Related to #514
Quoted values for labels, assigned from /etc/os-release contents, replaced `VERSION` with `VERSION_ID`
Run openshift-ansible's scaleup playbook on CentOS 7 nodes, check kubelet log:
`
kubelet_node_status.go:92] Unable to register node "ip-10-0-172-104.ec2.internal" with API server: Node "ip-10-0-172-104.ec2.internal" is invalid: metadata.labels: Invalid value: "7 (Core)": a valid label must be an empty string or consist of alphanumeric characters, ''-'', ''_'' or ''.'', and must start and end with an alphanumeric character (e.g. ''MyValue'',  or ''my_value'', …

kubelet: quote values in node.openshift.io/os_id label, use VERSION_ID instead of VERSION

---

pkg/operator/status.go
pkg/operator/sync.go
pkg/operator/version.go

Fix BZ#1690707 - remove componenets versions, leave just the top level MCO one
CI -> grab clusteroperators.json -> only `operator` is reported

Bug 1690707: MCO: report only operator version

---

test/e2e/mcd_test.go

bumped timeout to 10 mins as we're doing many reboots which might slow things down (observed in #549 )

test/e2e: wait longer for reboots

---

cmd/machine-config-daemon/start.go

follow up to #483 cause there's still a panic in rhel scaleup job
rhel scaleup job

MCD: fix another panic in onceFrom with Ignition

---

docs/Update-SSHKeys.md
pkg/controller/render/hash.go

Added a `rendered-` prefix to MachineConfig name in getMachineConfigHashedName function
`oc get machineconfigs` should now show a `rendered-` prefix on all names of rendered machineconfigs.
Fixes: #516

controller/render/hash.go: Add "rendered-" prefix to rendered machineconfigs

---

test/e2e/mcd_test.go

Test verifies that MCD updates MCP, daemons and
writes new ssh keys to node filesystems.
Closes #546

e2e: add ssh mcd test

---

Gopkg.lock
cmd/machine-config-controller/start.go
manifests/machineconfigcontroller/clusterrole.yaml
pkg/controller/container-runtime-config/container_runtime_config_controller.go
pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
pkg/controller/container-runtime-config/helpers.go
pkg/operator/assets/bindata.go

We don't want users to add the registry being used by the payload
to the list of blocked registries in /etc/containers/registries.conf.
Doing so will basically bring the whole cluster down. So we add a check
to ensure that doesn't happen and only add the registries that don't
match the payload one.
Added a validation test for this as well.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1686509

Add validation for blocked registries

---

docs/MachineConfigDaemon.md

Reported by QE.  Now separately we seemed not to fail trying to
do this for some reason; will investigate that.

docs: Directories and links aren't supported

---

pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
pkg/apis/machineconfiguration.openshift.io/v1/helpers_test.go
pkg/controller/bootstrap/bootstrap.go
pkg/controller/render/render_controller.go
pkg/controller/render/render_controller_test.go

Always use the osimageurl coming from the CVO. 
close #465 
Added a unit test to cover this change 

Bug 1691660: pkg/controller: always use the OSImageURL from the CVO

---

pkg/controller/node/node_controller.go
pkg/controller/node/node_controller_test.go

For CodeReady Containers and general single-node testing cases,
we need to support having a single node with both master/worker
labels.  In this case, it should fall under the master pool.
We also want to support users defining custom pools that conceptually
"derive" from worker.  If we find both `node-role/worker` and
`node-role/$x`, choose `$x`.  But we don't support more than one
custom role.
Closes: https://github.com/openshift/machine-config-operator/issues/571

controller/node: Support master/worker combined, and 1 custom role

---

docs/README.md
pkg/operator/sync.go

`syncRequiredMachineConfigPools` is continuosly called and can error out
flipping the operator status to Failing. Clarify that we're going to
retry in logs w/o having users think it's a fatal error.

pkg/operator: fix log messages

---

pkg/daemon/update.go

This PR is further fixing https://bugzilla.redhat.com/show_bug.cgi?id=1677198 by
allowing an old cluster to contain links (coming from #535) which are
then removed when upgrading to post #540.
What's happening to QE is that:
1) they're starting a cluster with an MCO version which contains #535
2) they're upgrading to a payload which doesn't have #535 cause it has #540 which reverts #535
The above means that point 1) generates MachineConfigs with an unsupported symlink and when
upgrading to 2), the symlink is removed causing drift and an unreconcilable error.
QE can start testing with a newer MCO version to avoid this, but for
ease of testing, let's add this snippet to make sure getting rid of
links, which we don't support anyway, just works.
Signed-off-by: Antonio Murdaca …

Bug 1677198: pkg/daemon: allow empty new links section

---

pkg/controller/bootstrap/bootstrap.go
pkg/controller/bootstrap/bootstrap_test.go

Users can push manifests during bootstrap that of the form:
```yaml
---
```
Especially for the installer: setting authorizes_keys [1] and setting hyperthreading [2] will push a manifest that includes multiple machineconfig objects for
control-plane (master) and compute (worker) roles.
Single file with multiple k8s objects separated by `---` is also a supported structure for `oc create|apply` ie. there is a high chance that users trying to push machineconfigs at
install time might create such files.
This commit allows bootstrap controller to read all k8s objects, even ones described above to find all the `machineconfiguration.openshift.io` Objects.
[1]: https://github.com/openshift/installer/pull/1150
[2]: https://github.com/openshift/installer/pull/1392
**- How to verify …

controller/bootstrap: use files with multiple yaml documents

---

pkg/controller/kubelet-config/helpers.go
pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/controller/kubelet-config/kubelet_config_features.go

FeatureGates creates a brand new ignition object, and the ignition
subsystem validates the Version field is a valid Semver. This fix uses
the common constructor to create a valid ignition object.
Note: This patch also changes the kubelet_config_controller to make it consistent
with how the featuregates controller constructs the ignition object.
None

kubeletconfig_features: fix ignition object creation

---

cmd/machine-config-operator/bootstrap.go
lib/resourcemerge/machineconfig.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/operator/bootstrap.go
pkg/operator/operator.go

This PR is the first of 2 the default is set for chicken and egg with the installer. Adding the metric ca is part of a series of PRs to add etcd metric support.
Depends on https://github.com/openshift/installer/pull/1477
/hold

BUG 1670700: *: add etcd-metric-ca flag

---

Dockerfile.machine-config-controller.rhel7
Dockerfile.machine-config-daemon.rhel7
Dockerfile.machine-config-operator.rhel7
Dockerfile.machine-config-server.rhel7
Dockerfile.setup-etcd-environment.rhel7

Removed hardcoded 'amd64' in build path from the .rhel7 Dockerfiles so we can start building these containers on other architectures.
Build the containers locally (with doozer or some other method).
Remove amd64 from dockerfile copy path to support Mulit-Arch Builds.

Remove amd64 from dockerfile copy path to support Mulit-Arch Builds.

---

pkg/controller/container-runtime-config/helpers.go

Added support for the "info" log level for ContainerRunetimeConfig.
The "info" log level for ContainerRunetimeConfig is now supported

ContainerRuntimeConfig: Enable "info" debug level

---

pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
pkg/controller/template/test_data/templates/master/00-master/vpshere/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
pkg/controller/template/test_data/templates/worker/00-worker/aws/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
pkg/controller/template/test_data/templates/worker/00-worker/libvirt/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
pkg/controller/template/test_data/templates/worker/00-worker/none/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
pkg/controller/template/test_data/templates/worker/00-worker/openstack/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
pkg/controller/template/test_data/templates/worker/00-worker/vpshere/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
pkg/controller/template/test_data/templates/worker/00-worker/vsphere/files/-etc-systemd-system.conf.d-kubelet-cgroups.conf
templates/master/00-master/_base/files/kubelet-cgroups.yaml
templates/worker/00-worker/_base/files/kubelet-cgroups.yaml

Install system.conf to enable CPU Accounting.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1692131
Install a custom system.conf file enabling CPU, BlockIO, and Memory accounting.
ref: https://github.com/openshift/origin/blob/master/contrib/systemd/origin-accounting.conf
Enable CPU Accounting within systemd
/cc @sjenning @derekwaynecarr

systemd: install systemd.conf to enable CPU Accounting

---

pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go

This PR https://github.com/openshift/machine-config-operator/pull/590
didn't run `make update` and generated deepcopy hasn't been updated.
This PR just does that.
@hexfusion ptal

pkg/apis: update generated deepcopy

---

cmd/setup-etcd-environment/run.go

Modified the `setup-etcd-environment` component so that it continues to wait if any of the targets in the discovery SRV cannot be resolved.
1) Run the setup-etcd-environment component.
2) Create an SRV record with two targets, A and B.
3) Create an A record to point target A to the IP address of the local host.
4) Verify that the setup-etcd-environment compoent logs errors about not being able to resolve target B.
5) Create an A record to point target B to some other IP address.
6) Verify that the setup-etcd-environment component exits successfully.
Wait for the names of all of the etcd members in the SRV to be resolvable before exiting discovery

setup-etcd-environment: wait for all etcd members to be resolvable

---

hack/verify-codegen.sh
hack/verify-generated-bindata.sh

The new verify job I'm trying to add in https://github.com/openshift/release/pull/3332 is failing with https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_release/3332/rehearse-3332-pull-ci-openshift-machine-config-operator-master-verify/3
This patch just makes `cp` copy with just `-R` and not full `-a`as we don't need that for diffing text.
run `make verify`

hack: copy file w/o preserving attributes

---

pkg/operator/status.go
pkg/operator/status_test.go

Update `LastTransitionTime` when flipping progressing
xref: https://github.com/openshift/cluster-version-operator/pull/154
as done in https://github.com/openshift/cluster-version-operator/pull/153
There's gonna be a test in origin covering this

pkg/operator: update LastTransitionTime when flipping conditions

---

pkg/controller/kubelet-config/kubelet_config_controller.go

Otherwise, we were only adding nil as Conditions even when there was an
actual error...
@rphillips ptal, maybe this function should be split in 2 and unit tests added to catch stuff like this..

kubelet-config: fix variable shadowing

---

pkg/operator/operator.go

The operator should be using the `openshift-config/pull-secret` as the `kube-system/coreos-pull-secret` has been marked deprecated.
`Use openshift-config/pull-secret as source for pull secret for images`
requires: https://github.com/openshift/installer/pull/1554
/cc @smarterclayton

Bug 1697644: operator: use openshift-config/pull-secret to fetch the pull secret for images.

---

pkg/operator/bootstrap.go

During bootkube we can see an empty line in there:
```
Apr 09 17:19:18 ip-10-0-7-150 bootkube.sh[1341]: Rendering MCO manifests...
Apr 09 17:19:20 ip-10-0-7-150 bootkube.sh[1341]: I0409 17:19:20.779505       1 bootstrap.go:84] Version: 4.0.0-alpha.0-164-gfc43ad02-dirty
Apr 09 17:19:20 ip-10-0-7-150 bootkube.sh[1341]: I0409 17:19:20.781728       1 bootstrap.go:115] manifests/machineconfigcontroller/controllerconfig.yaml
Apr 09 17:19:20 ip-10-0-7-150 bootkube.sh[1341]: I0409 17:19:20.784134       1 bootstrap.go:115] manifests/master.machineconfigpool.yaml
Apr 09 17:19:20 ip-10-0-7-150 bootkube.sh[1341]: I0409 17:19:20.784863       1 bootstrap.go:115] manifests/worker.machineconfigpool.yaml
Apr 09 17:19:20 ip-10-0-7-150 bootkube.sh[1341]: I0409 17:19:20.785079       1 bootstrap.go:115] …
```

pkg/operator: fix bootstrap logging

---

pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/worker/00-worker/aws/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/worker/00-worker/libvirt/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/worker/00-worker/none/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/worker/00-worker/openstack/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/worker/00-worker/vsphere/files/-etc-tmpfiles.d-cleanup-cni.conf
templates/master/00-master/_base/files/cleanup-cni-conf.yaml
templates/worker/00-worker/_base/files/cleanup-cni-conf.yaml

The cluster considers a node "Ready" when the cni config file
is written. When the cni plugin fails the file was not deleted
so the node continued to be "Ready".
Further when the node is rebooted, the config file remained present
and the cluster set the node "Ready". The startup order of the pods in
the cluster is not sequenced and results are presented in bug 1654044
In addition when the node is rebooted the ovs database is completely
invalid and must be deleted.
This is part of the solution to
bug 1654044
https://bugzilla.redhat.com/show_bug.cgi?id=1654044
for 4.x. Part of the fix is in cluster-network-operator PR 137
https://github.com/openshift/cluster-network-operator/pull/137
And part is in ovn-kubernetes upstream pr 644
https://github.com/openvswitch/ovn-kubernetes/pull/664
The …

templates: Add a tmpfiles.d entry to delete CNI files at boot

---

pkg/controller/template/render.go
pkg/operator/render.go

Add support for Azure platform
installer will add support for azure platform soon.
Add support for Azure platform

Add support for Azure platform

---

docs/ContainerRuntimeConfigDesign.md

Add more info with examples on how to actually roll out changes
made to the ctrcfg CR. This includes adding the matching label
to the mcp config of the pools where the changes are desired.

Add more info to the container runtime config doc

---

pkg/operator/status.go

Saw this in a CI job:
```
extension: {
master: "all 3 nodes are at latest configuration rendered-master-2637ad32a70f0618e20be6b9c53ac6d1",
worker: "3 out of 3 nodes have updated to latest configuration rendered-worker-a48a1e135f36dc49e4c49aee5590ee72"
},
```
Which is confusing since 3/3 looks like everything is right so why that
if the pool is still updating? This patch fixes the above to have a
better status message for updating pools where we also take into
accounts ready machines.

pkg/operator: clarify pool status

---

docs/MachineConfigController.md
examples/etcd.machineconfigpool.yaml
examples/master.machineconfigpool.yaml
examples/worker.machineconfigpool.yaml
lib/resourcemerge/machineconfig.go
manifests/master.machineconfigpool.yaml
manifests/worker.machineconfigpool.yaml
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
pkg/controller/node/node_controller.go
pkg/controller/node/node_controller_test.go
pkg/controller/node/status.go
pkg/operator/assets/bindata.go
pkg/server/testdata/machine-pools/test-pool.yaml

MachineSelector will eventually be replaced with NodeSelector.
This PR allows all current MachineSelector values to be copied
into the NodeSelector label if MachineSelector is not nil, otherwise 
reads and uses NodeSelector value as part 1 of this process.
Closes: #619

Bug 1698250: * : pt1 transition from MachineSelector to NodeSelector labels

---

pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
pkg/apis/machineconfiguration.openshift.io/v1/helpers_test.go
pkg/controller/render/render_controller.go
pkg/operator/sync.go

we were always getting the ControllerConfig before passing it down for a new `ccLister.Get` - this patch avoids that and we just get the CC once inside the check code.

pkg/apis: avoid a double call in getting the cc

---

cmd/machine-config-operator/start.go
pkg/operator/operator.go

added cache sync for the other listers we are using in the operator
CI

pkg/operator: wait for cache on mcp/cc/mcp

---

pkg/controller/kubelet-config/helpers.go
pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/controller/kubelet-config/kubelet_config_controller_test.go
pkg/controller/kubelet-config/kubelet_config_features.go
pkg/controller/kubelet-config/kubelet_config_features_test.go

* The ownerref is not needed on a featuregate change and causes issues
on attempted deletions/modifications later.
* Add unit test
* [The line for the actual fix](https://github.com/openshift/machine-config-operator/pull/634/files#diff-7fdca55408b7882f7cf5d546eccb969eL123)
* Unit test
```
None
```
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1699353

featuregates: remove ownerref reference on managed feature gates

---

lib/resourcemerge/machineconfig.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
pkg/controller/node/node_controller.go
pkg/controller/node/node_controller_test.go
pkg/controller/node/status.go

This PR removes all references to MachineSelector. PR 625 added NodeSelector
in addition to MachineSelector to allow for users to transition. This PR fully
removes all references to MachineSelector to make the transition complete.
Related-to: #625
Related-to: BZ 1698250
CI, nothing should change functionally.

Bug 1698250: *: pt2 NodeSelector transition : remove all MachineSelector refs

---

pkg/controller/render/render_controller.go
pkg/controller/render/render_controller_test.go

I was working on triggering a resync when the pull-secret change and I
got to this:
- pull-secret changes
- template_controller runs and update 00-<role> with the new pull-secret
- stop, the new pull secret is now just in 00-<role> MCs and not on
nodes since there's no rendered MC which contains it
Now, the above isn't quite right since after an admin updates the
pull-secret, it must be rolled out to nodes to be able to pull images
(for e.g. an upgrade).
What's happening is that the template_controller sets an OwnerReference
of Kind: ControllerConfig, whether the render_controller only reacts to
a Kind: MachineConfigPool (and MCs that aren't controller at all, like
the template_controller tho).
This patch fixes the controller checks and we now enqueue an MCP for the
given MC if we have a …

render_controller: render on template MCs changes

---

cmd/machine-config-controller/start.go
docs/HACKING.md
docs/PullSecret.md
pkg/controller/common/controller_context.go
pkg/controller/kubelet-config/kubelet_config_features.go
pkg/controller/template/template_controller.go
pkg/controller/template/template_controller_test.go

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1686117
I've noticed, from code, that we don't trigger a resync when the
pull-secret changes. That leaves us with just a "oc delete pod
controller" to actually trigger a resync with a changed pull-secret.
Added an event handler for that particular secret to trigger a re-sync.
Also added a new doc explaining how to change the pull-secret (taking
care of the referenced BZ).

Bug 1686117: pkg/controller: re-sync on pull secret change

---

manifests/machineconfigcontroller/deployment.yaml
pkg/operator/assets/bindata.go

Drop the memory limit of 50Mi from the MCC deployment since it doesn't
really make sense for the component to have a limit. The MCC deals with
informers and MCs as well and it really makes little sense to cap on
memory, and 50Mi is really low as seen in other PRs.
On top of that, setting memory limits for core component on the
control plan is something that we are recommended NOT to do as this test
in origin says: https://github.com/openshift/origin/pull/22095/files#diff-bf7568debb85800236085e7e6de8cb07R67
So, comply with that test and avoid bad OOMs that can cause issues once
we're deployed for real and people have huge MCs and objects from
informers to deal with.
/cc @derekwaynecarr @abhinavdahiya

MCC: drop memory limit

---

pkg/operator/operator.go

API freeze doc wants user managed resources in openshift-config.  The installer already moved this one.  This updates the location for the MCO

update etcd servicing-ca location for api freeze

---

pkg/daemon/daemon.go

Add an on disk fingerprint about what our current config is on a node (avoiding resync if we changed it or restored from an etcd backup). We check what we have on disk with what we have in annotations before triggering a sync.

pkg/daemon: add a current config on disk check

---

cmd/machine-config-operator/bootstrap.go
manifests/machineconfigserver/kube-apiserver-serving-ca-configmap.yaml
pkg/operator/assets/bindata.go
pkg/operator/bootstrap.go
pkg/operator/operator.go
pkg/operator/render.go

Trying to fix https://bugzilla.redhat.com/show_bug.cgi?id=1685704, we've bumped into MCD ghost dependencies to dead/broken resources.  In this case, it appears to be a dead configmap with ca-bundle.crt inside that cannot actually verify anything except a deprecated serving-cert.  However, we cannot fix the original here https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/bindata/bootkube/manifests/configmap-initial-kube-apiserver-client-ca.yaml#L1 (which was actually only working by a invalid coincidence of a client-ca validating a serving cert).
To avoid the ghost, the MCD can render out its own new configmap and then rely upon that.  Keep in mind that this still leaves it disconnected from the actual trust bundle because the actual values aren't known until after …

try to make MCD render more self-contained

---

install/0000_30_machine-config-operator-00_clusterreader_clusterrole.yaml

Adds permissions to non-sensitive API resources for cluster-reader.
The general rule is that they can read all non-escalating resources, so not things like secrets, oauthtokens

add permissions to the cluster-reader role

---

pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/daemon/fake_writer.go
pkg/daemon/writer.go

Current units are broken on master on linux since the NodeWriter is nil
in fixtures (sorry I didn't catch that on osx).
Anyway, this patch finally abstract NodeWriter behing an interface so
it's easy to use it in tests as well. I've created a fakeNodeWriter
which can also be expanted in the future to make assertions if needed
(like counting actions and stuff like that).
cc @LorbusChris since you spotted this one

pkg/daemon: abstract NodeWriter to an interface

---

manifests/machineconfigpool.crd.yaml
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/container-runtime-config/container_runtime_config_controller.go
pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/controller/node/status.go
pkg/controller/render/render_controller.go
pkg/controller/render/render_controller_test.go
pkg/daemon/constants/constants.go
pkg/daemon/daemon.go
pkg/daemon/writer.go
pkg/operator/assets/bindata.go
pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/sync.go
test/e2e/mcd_test.go

Close https://github.com/openshift/machine-config-operator/issues/234
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1699134
Added a new Reason annotation key set to the specific error we get when failing to reconcile + reintroduced degraded from https://github.com/runcom/machine-config-operator/commit/e753f108d3e0027500fb2c473ceb162c0fed74ae#diff-3bd49282ca65e5525da44a27caaa55c7L80 + bubbling up errors from pool
added a check in one of the e2e

Bug 1699134: pkg/daemon: add reason annotation key for degraded/unreconcilable and bubble up errors from render controller

---

pkg/operator/status.go
pkg/operator/status_test.go

Going to help with debugging, especially on roll out timings.
@deads2k ptal - notice that we fire this event only after we finish progressing to a new version.

pkg/operator: fire an event when we change version

---

pkg/operator/bootstrap.go

PR [1] introduced wrong decoding for the cloud conf configmap file. It was using the openshift/client-go 's config scheme
to decode ConfigMap resource when it should have been using the k8s.io/client-go's kubernetes scheme
[1]: https://github.com/openshift/machine-config-operator/pull/591
fix the decoding scheme for cloud conf configmap on bootstrap

operator/bootstrap: fix the decoding scheme for cloud conf configmap

---

pkg/daemon/daemon.go
pkg/daemon/update.go

making it easier to debug stuff like https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22653/pull-ci-openshift-origin-master-e2e-aws-upgrade/89 
I believe we failed to reboot, but we lost logs since we keep writing only the last error and overriding the previous so we're left with just "unexpected on-disk state".
This patch fires some more events which are persisted anyway during a job.

pkg/daemon: add more events and logging

---

install/0000_30_machine-config-operator_00_namespace.yaml

**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …

Add node-selector annotation to namespace

---

pkg/controller/template/render.go
pkg/controller/template/render_test.go
pkg/controller/template/test_data/templates/master/01-master-kubelet/vsphere/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vsphere/units/kubelet.service

Previously, the assumption was that all platforms that had CloudProviderConfig set can have kubelet configured to
use the config file. But this created a regression for user-provided-infrastructure VSphere case, as everybody like kube-controller-manager etc. except kubelet can use the cloud conf
file from API for vSphere
/cc @staebler

controller/template: put the cloudconf for kubelet behind platform gate

---

install/0000_30_machine-config-operator_07_etcdquorumguard_deployment.yaml
install/image-references

The quorum guard image does not exist in OCP and agreement was not
to create a new one. Use the CLI image which is required to have
bash. Simplify the container name to be easier to input when debugging.

Remove reference to etcd-quorum-guard image, and use cli instead

---

pkg/controller/node/status.go
pkg/daemon/daemon.go
pkg/daemon/update.go

If we fail something after we write files to disk for desired config we
now roll back to files for current config.
In case we fail _after_ writing the pending config file, we still roll
back files but we never remove the pending config.
I was debugging
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22653/pull-ci-openshift-origin-master-e2e-aws-upgrade/89
and what it looks like it's happening is that we wrote the pending
config but we then errored, rolling back files but leaving that pending
config file around which made the MCD restart fail (also hiding the real
failure error on reboot).

pkg/daemon: roll back pending config on error

---

pkg/daemon/update.go

Closes: #679
when dealing with systemd units, the MCD used to check the "content"
section. If no content was provided, it would skip the unit. This
doesn't work for built-in units, which we could merely enable without
writing anything. This allows that.
Allows enabling built-in systemd units without providing the "content" section.

mcd: Allow enabling units even if no content was provided

---

pkg/controller/template/test_data/templates/master/00-master/aws/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/master/00-master/libvirt/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/master/00-master/none/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/master/00-master/openstack/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/master/00-master/vsphere/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/worker/00-worker/aws/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/worker/00-worker/libvirt/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/worker/00-worker/none/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/worker/00-worker/openstack/files/-etc-tmpfiles.d-cleanup-cni.conf
pkg/controller/template/test_data/templates/worker/00-worker/vsphere/files/-etc-tmpfiles.d-cleanup-cni.conf
templates/master/00-master/_base/files/cleanup-cni-conf.yaml
templates/worker/00-worker/_base/files/cleanup-cni-conf.yaml

Discovered in BZ1704706 that we weren't actually cleaning these files
up, leading to failed deletions.
Fixes: rhbz1704706

Bug 1704706: remove openshift-sdn and multus CNI configuration files on boot

---

pkg/daemon/daemon.go

Saw this in daemon logs at some point:
```
E0504 11:59:18.774259    9918 daemon.go:1234] content mismatch for file /etc/crio/crio.conf: "IyBUaGUgImNyaW8iIHRhYmxlIGNvbnRhaW5zIGFsbCBvZiB0aGUgc2VydmVyIG9wdGlvbnMuCltjcmlvXQoKIyBDUkktTyByZWFkcyBpdHMgc3RvcmFnZSBkZWZhdWx0cyBmcm9tIHRoZSBjb250YWluZXJzL3N0b3JhZ2UgY29uZmlndXJhdGlvbgojIGZpbGUsIC9ldGMvY29udGFpbmVycy9zdG9yYWdlLmNvbmYuIE1vZGlmeSBzdG9yYWdlLmNvbmYgaWYgeW91IHdhbnQgdG8KIyBjaGFuZ2UgZGVmYXVsdCBzdG9yYWdlIGZvciBhbGwgdG9vbHMgdGhhdCB1c2UgY29udGFpbmVycy9zdG9yYWdlLiAgSWYgeW91CiMgd2FudCB0byBtb2RpZnkganVzdCBjcmlvLCB5b3UgY2FuIGNoYW5nZSB0aGUgc3RvcmFnZSBjb25maWd1cmF0aW9uIGluIHRoaXMKIyBmaWxlLgoKIyByb290IGlzIGEgcGF0aCB0byB0aGUgInJvb3QgZGlyZWN0b3J5Ii4gQ1JJTyBzdG9yZXMgYWxsIG9mIGl0cyBkYXRhLAojIGluY2x1ZGluZyBjb250YWluZXIgaW1hZ2VzLCBpbiB0aGlzIGRpcmVjdG9yeS4KI3J …
```

pkg/daemon: diff strings on file checks

---

pkg/daemon/daemon.go
pkg/daemon/update.go

Added a lock to read/write `dn.updateActive` as we're reading/writing it from at least 2 goroutines concurrently

pkg/daemon: lock when checking if update is active

---

install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml

`curl` results in heavy dentry cache pollution that gets charged to the eqg's cgroup.  The underlying bug is https://bugzilla.redhat.com/show_bug.cgi?id=1571183.
Fixes 1706625.

Work around bz1571183

---

pkg/daemon/daemon.go
pkg/daemon/update.go

We were printing errors 3 times, reduce that to 1.
Also strip out an extra reconciliation log.

daemon: Tweak logging during updates

---

pkg/daemon/daemon.go
pkg/daemon/update.go

The reboot command itself is being terminated as shown in this log:
```
worker: "pool is degraded because nodes fail with "1 nodes are reporting degraded status on sync": "Node ip-10-0-144-80.ec2.internal is reporting: \"failed to reboot: signal: terminated\"""
```
By the time we issue a reboot it's probably ok to just log reboot errors

Bug 1707212: only log reboot command error and change it to systemd-run

---

install/0000_80_machine-config-operator_04_deployment.yaml
install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
manifests/machineconfigcontroller/deployment.yaml
manifests/machineconfigdaemon/daemonset.yaml
manifests/machineconfigserver/daemonset.yaml
pkg/operator/assets/bindata.go

In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …

Bug 1706204: Fix tolerations

---

pkg/daemon/daemon.go

Having `rpm-ostree status` in the control loop greatly
adds to noise, it shouldn't change (except by us) before
a reboot.
While we're adding stuff that's logged only once, add
`journalctl --list-boots` which should be useful - it contains
the boot ID too.  I may also add some code later here to scrape
logs from the *previous* boot's MCD run.

daemon: Only log rpm-ostree status once, add boot list

---

pkg/daemon/daemon.go

If we hit an error, for the MCD it's very silly to retry in *milliseconds*.
Nothing we care about changes at a rate faster than a second really.
Tweak the queue to start from a second for the exponential backoff
with a cap at 60s (so we do keep retrying at a reasonable rate in
case an admin fixes something).  Drop the token bucket as I don't
think it applies to us.
Ideally what we'd do is slow down the rate of retries for the *same*
node object (that may not be hard, I didn't try), but this should
help avoid the MCD logs turning into spam in cases of error.  In
particular I really often want to see the starting MCD logs, and
that can get GC'd if we output too much.
Also drop `maxRetries` as we're managing the node and it has
to work, we'll keep retrying until it's fixed.

daemon: Greatly slow down rate of retries

---

pkg/daemon/daemon.go
pkg/daemon/update.go

Let's try to avoid losing a file write...

pkg/daemon: log pending config to journal

---

pkg/daemon/update.go

we don't need to compare bootid if we have a _not_ pending config...
xref https://github.com/openshift/machine-config-operator/pull/711

pkg/daemon: fix pending config logic

---

Gopkg.lock
pkg/operator/bootstrap.go
pkg/operator/operator.go
vendor/github.com/openshift/api/config/v1/types_cluster_version.go
vendor/github.com/openshift/api/config/v1/types_infrastructure.go
vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go

Requires https://github.com/openshift/installer/pull/1718
/cc @runcom

Bug 1706689: pkg: Catch up to the api change introduced in openshift/api#308 

---

pkg/daemon/daemon_test.go

Now that the daemon tries to talk to the systemd journal, this unit
test hangs in my dev environment.  We can't really support this
without mocking a lot more, and it's not really covering much
interesting right now.  Delete it.

daemon: Remove dummy OnceFrom Test

---

manifests/machineconfigdaemon/daemonset.yaml
pkg/operator/assets/bindata.go

This job https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/1726/pull-ci-openshift-installer-master-e2e-aws-upgrade/319 is showing us an interesting pattern where:
1) we start a drain
2) we're asked to terminate
3) we exceed the termination grace period (currently 300s)
4) we get terminated
5) we don't reboot and fail the update
I'm still investigating why we're asked to terminate but drain's timeout (not counting the backoff on possible failures) is 600s so this PR is just bumping the DS termination to at least that.

MCD: bump terminationGracePeriodSeconds

---

pkg/controller/node/node_controller.go
pkg/controller/node/node_controller_test.go
pkg/controller/node/status.go
pkg/controller/node/status_test.go
test/e2e/mcd_test.go

Bigger rewrite for #699
This should ensure that the node controller avoids exceeding maxUnavailable,
by changing the notion of "unavailable" to mean nodes which are either
not ready, *or* may become not ready as they're working on an update.
That list is also further filtered by nodes which are degraded/unreconcilable.

Bug 1707212: Rework controller progress

---

cmd/machine-config-controller/version.go
cmd/machine-config-daemon/version.go
cmd/machine-config-operator/version.go
cmd/machine-config-server/version.go
cmd/setup-etcd-environment/version.go
hack/build-go.sh
pkg/controller/container-runtime-config/container_runtime_config_controller.go
pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/controller/kubelet-config/kubelet_config_features.go
pkg/controller/render/render_controller.go
pkg/controller/template/render.go
pkg/operator/status.go
pkg/operator/sync.go
pkg/version/version.go

Do not rely on tags (as they may contain timestamps which can cause us to drift)

Bug 1707928: hack/build-go.sh: use just git hashes for building

---

cmd/machine-config-controller/bootstrap.go
cmd/machine-config-controller/start.go
cmd/machine-config-daemon/start.go
cmd/machine-config-operator/bootstrap.go
cmd/machine-config-operator/start.go
cmd/machine-config-server/bootstrap.go
cmd/machine-config-server/start.go
cmd/setup-etcd-environment/run.go

Forgot these places in #728 - trivial fix tho

cmd: log version hash for components

---

pkg/daemon/daemon.go
pkg/daemon/update.go

We are checking and reconciling any skew once we're actively running as
a controller in prepUpdateFromCluster already.
This patch enhance that so that we reconcile any drift directly when we
bring up the MCD on a node.
This has the advantage of an easy trigger when, for instance, we want to
kick a reconcile after an etcd backup has been restored: we simple
restart the MCD (or we find a way to automate that or whatever, not in
scope for this PR).

DR: pkg/daemon: reconcile current on disk on boot

---

pkg/daemon/daemon.go
pkg/daemon/update.go

RHEL7.6 has an old util-linux's logger which doesn't support the `--journald` flag to log to journal in a structured way. Work that around by logging a json directly and fall back to that if we're on rhel7.6 then.

Bug 1708602:  pkg/daemon: workaround old util-linux logger in rhel7.6

---

hack/build-go.sh

This will be supplied in downstream builds to relay the commit from the source git repo.
Fixes: bz 1709365
Check that the resulting OCP image built binary reports a commit from this github repo.
build-go.sh: use OS_GIT_COMMIT if available

build-go.sh: use OS_GIT_COMMIT if available

---

hack/build-go.sh

This will be supplied in downstream builds to relay the commit from the source git repo.
Fixes: bz 1709365
Check that the resulting OCP image built binary reports a commit from this github repo.
build-go.sh: use SOURCE_GIT_COMMIT if available

build-go.sh: OS_GIT_COMMIT => SOURCE_GIT_COMMIT

---

cmd/machine-config-daemon/start.go
pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/daemon/osrelease.go
pkg/daemon/rpm-ostree.go
pkg/daemon/rpm-ostree_test.go
pkg/daemon/update_test.go

Today at least `detectEarlySSHAccessesFromBoot()` was racing
as it was spawning a goroutine that was expecting the target root,
but we were only calling `chroot()` later on.
I think everything will be a lot clearer if the daemon code is
basically *always* chrooted from as early on as possible.

daemon: Move chroot to very early on

---

hack/build-go.sh

This will be supplied in downstream builds to relay the commit from the source git repo.
Fixes: bz 1709365
Check that the resulting OCP image built binary reports a commit from this github repo.
build-go.sh: use SOURCE_GIT_COMMIT if available

build-go.sh: use SOURCE_GIT_COMMIT if available

---

pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/none/units/kubelet.service
pkg/controller/template/test_data/templates/master/01-master-kubelet/vsphere/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/units/kubelet.service
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vsphere/units/kubelet.service
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

It isn't useful today because most containers just want the RHEL major
which they can't get at without parsing it, and you can't do that
in a selector.
Also, it turns out that the label commandline is a one-shot.  We
need to move any label version updates into the MCD.

Drop os_version label on nodes

---

pkg/daemon/daemon.go

We show this log in the normal case where the file exists.
I don't think we need to `logSystem` this anyways.

daemon: Drop unnecessary logSystem

---

install/0000_80_machine-config-operator_02_images.configmap.yaml
install/0000_80_machine-config-operator_04_deployment.yaml
install/0000_80_machine-config-operator_05_osimageurl.yaml
install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
install/image-references

These get [replaced by the release-creation tooling][1], so there's no point in using more specific names referencing v4.0 or particular digests.  This commit moves us to generic placeholders, where the pattern is:
```
registry.svc.ci.openshift.org/openshift:{name-in-image-references}
```
You can't pull any of them directly, but that makes it more obvious that these are placeholders.
[1]: https://github.com/openshift/cluster-version-operator/blob/33079c7732b99394f78c4fecb8d7d277c87ef02c/docs/dev/operators.md#how-do-i-ensure-the-right-images-get-used-by-my-manifests

install: Use generic image placeholders

---

pkg/controller/node/node_controller.go
pkg/controller/node/status.go

small updates:
- replace repetitive error checks with helper function in updateNode()
mentioned in comment here: https://github.com/openshift/machine-config-operator/pull/718/files/ad37518f2374b2742ad51e492eb8f811d2e21be9#r282160740
- fix errorf caps in status.go
e2e & unit tests

mcc: refactor node controller to use error check helper function 

---

pkg/server/api.go
pkg/server/api_test.go

Returning 204 `StatusNoContent` for `/healthz` is technically the correct response. And on AWS [1] the health checks treat 200 to 399 as Healthy.
But on Azure, the health checks on treat 200 `StatusOK` [2] as the healthy response. :shake_fist:
This moves the ign server to return 200 for `/heathz`
[1]: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html
[2]: https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-custom-probe-overview#httpprobe
Updates the unit tests
`update healthz to return 200 instead of 204`
/cc @wking @runcom

server: update healthz to return 200 instead of 204

---

pkg/controller/node/node_controller.go
pkg/controller/node/node_controller_test.go

Calculate the maxUnavailable for the master pool based also on the etcd fault tolerance and thus removing the hardcoded 1.
added units

pkg/controller: calculate fault tolerance for the master pool

---

pkg/daemon/daemon.go

`logSystem` already logs to stdout, so remove duplicates.
Delete one that I don't think is necessary.
Clarify the disk != annotation one.

daemon: Reduce/clean up logging

---

templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-tokenize-signer-sh.yaml
templates/master/00-master/_base/files/usr-local-share-openshift-recovery-template-etcd-generate-certs-yaml-template.yaml
templates/master/00-master/_base/files/usr-local-share-openshift-recovery-template-kube-etcd-cert-signer-yaml-template.yaml

This PR adds disaster recovery tools used for folks to restore a cluster from failure. We are also providing detailed documentation on how to use these scripts.
/cc @sdodson @patrickdillon @runcom @vrutkovs 
Code is pulled from
https://github.com/hexfusion/openshift-recovery/tree/unify
This PR is required to resolve: https://jira.coreos.com/browse/PROD-1027

JIRA PROD-1027 : templates/master/00-master: add disaster recovery tools

---

docs/MachineConfiguration.md
lib/resourceapply/machineconfig_test.go
pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
pkg/apis/machineconfiguration.openshift.io/v1/machineconfig.deepcopy.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/common/helpers.go
pkg/controller/container-runtime-config/container_runtime_config_controller.go
pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
pkg/controller/container-runtime-config/helpers.go
pkg/controller/kubelet-config/helpers.go
pkg/controller/kubelet-config/kubelet_config_controller.go
pkg/controller/kubelet-config/kubelet_config_controller_test.go
pkg/controller/kubelet-config/kubelet_config_features_test.go
pkg/controller/render/render_controller_test.go
pkg/controller/template/render.go
pkg/controller/template/render_test.go
pkg/controller/template/template_controller_test.go
pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/daemon/update.go
pkg/daemon/update_test.go
pkg/server/api_test.go
pkg/server/bootstrap_server.go
pkg/server/cluster_server.go
pkg/server/server.go
pkg/server/server_test.go
test/e2e/mcd_test.go

Now that we have more time, I am breaking up PR #583 . This PR is removing the changes from #583 that can go into the code-base now to make the future transition easier. 
This PR makes the following changes:
- update helpers.go NewIgnConfig() to use MaxVersion and sub igntypes for ignv2_2types as package alias
- for all non-test files, substitute igntypes for ignv2_2types as package alias (these changes are trivial but take up a lot of space in the PR, let's do it now!)
- in test files, make the above substitution, and also refactor to use NewIgnConfig() instead of generating empty config and hardcoding version.
- minor doc update to reflect above changes
After this lands, the future subtantive ignition change PR should be clearer and easier to test and evaluate.
**- How …

*: pre-transition ign refactor

---

templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

This adds a new script on master which snapshots existing etcd state. 
This scriptis not yet used by DR scenarios (a few more PRs are required 
for that)
/cc @hexfusion @runcom 
Added a new script 
* Setup a master using this release
* Run `/usr/local/bin/etcd-snapshot-backup.sh`
* Check that `/root/assets/backup/etcd/member/snap/db` has been created
* Check that `/usr/local/bin/etcd-snapshot-restore.sh` restores the etcd snapshot

JIRA PROD-1027: templates/master/00-master: add a script to make etcd snapshot

---

templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

…
This enables etcd restore script restore the multimember cluster. This is required for CI where a 3 member cluster needs to be restored.
/cc @hexfusion @runcom

JIRA PROD-1027: templates/master/00-master: optionally pass etcd connection string

---

templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

Add a Wait= dependency for crio to start within the kubelet unit file. Prevents a race starting kubelet before crio has initialized.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1710626
`Add crio dependency to Kubelet systemd unit file`

Bug 1710626: kubelet: add crio dependency to systemd unit file

---

templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

Updated MCO templates to make sure `etcdctl save snapshot` uses etcd certs (these are being backed up)
Use provided scripts to make etcd backup

templates/master/00-master: use etcd certs for snapshot save

---

test/e2e/mcd_test.go

Rather than poll all of the daemons, add a helper that waits
for a pool to complete a config.
One of our tests walks over the MCDs, change it to just assert
on all of the nodes.
The SSH test can also just wait for a pool and then `rsh` to
each node.

test/e2e: More refactoring

---

templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

This PR resolves an issue where we sourced `/run/etcd/environment` after we were populating $ETCD_CONNSTRING which if not passed as a param would result in ${ETCD_DNS_NAME} having no value. Also removed `download_cert_recover_template` function which is no longer used.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1711879
**NOTE: This will fall in 4.1.z and is not blocking for 4.1**

Bug 1711879 : templates/master/00-master: resolve empty var when ETCD_CONNSTRING is not passed

---

templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

Updated DR scripts to start all stopped pods.
Script won't start all stopped pods if it was terminated and restarted.
This may happen when pod-based ssh bastion is used and connection may break 
when other masters are starting.
Instead `start_static_pods` function should re-read a list of pods in MANIFEST_STOPPED_DIR.
* Follow snapshot restore DR procedure and stop the script when master is being restored.
* Stop the script in the middle
* Restart the script
* Verify all pods from `/etc/kubernetes/manifests-stopped` were started

DR start_static_pods: reread a list of static pods when starting them

---

pkg/daemon/daemon.go

This is resurrecting the other part of:
https://github.com/openshift/machine-config-operator/pull/237
Basically it's not advantageous to us to try to shut down everything
at once; we want to ensure kubelet can fully shut itself down
gracefully, and only after that initiate the reboot for the rest
of the machine.
This also sets the MCD up to be in full explicit control of
kubelet shutdown; e.g. if we wanted to configure timeout behavior
more, we could easily do that with this "2 phase" shutdown (though
it would involve some custom code and not a shell script one-liner).

daemon: Explicitly stop kubelet.service first before rebooting

---

templates/master/00-master/_base/files/usr-local-bin-openshift-kubeconfig-gen.yaml

Adds a recovery script to generate a bootstrap kubeconfig for use in kubelet disaster recovery scenarios.
```
Add a script to generate a bootstrap kubeconfig for disaster recovery scenarios.
```
/cc @hexfusion @sjenning

kubelet: add script to generate bootstrap recovery kubeconfig

---

install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
install/image-references
test/e2e/etcdquorumguard_test.go

sleep, when run as pid 1, does not correctly exit on TERM and so stays
running. Correct that by running a small shim that terminates on TERM,
lower the graceful deletion period (the minimum is 3s in practice).
Correct the image reference to be a real image so that this can be
tested against a working cluster.
Also, the etcd quorum guard test does not correctly make nodes unschedulable, resulting in occasional failures when the quorum guard exits more quickly.
@hexfusion @smarterclayton

Bug 1712507: etcdquorumguard: Respond correctly to TERM when pod shut down

---

templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

/run/etcd/environment contains important ENV variables required by most of the DR scripts. This file is populated by the discovery container in the etcd-member init. In some circumstances such as the node rebooting this file can be missing.  `validate_environment` now checks for the existence of the file and if it is missing we populate.
The second part of this PR makes $SNAPSHOT_FILE a required parameter. Currently, we default to the local members DB file backup. This I feel is not a good default and could result in unexpected results.
/cc @vrutkovs

DR: add validate_environment to openshift-recovery tools

---

templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

Updated etcd restore script to reload systemd before starting kubelet
1. Change kubelet on disk
2. Run etcd restore script
If the service has changed kubelet won't start without daemon reload:
```
+ echo 'Starting kubelet..'
+ systemctl start kubelet.service
Warning: The unit file, source configuration file or drop-ins of kubelet.service changed on disk. Run 'systemctl daemon-reload' to reload units
```
I'm not quite sure what's changing kubelet on disk during this procedure though
/cc @patrickdillon @hexfusion

DR: reload systemd services on disk before starting kubelet in etcd restore script

---

docs/MachineConfiguration.md
lib/resourcemerge/machineconfig.go
pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/daemon/update.go
pkg/daemon/update_test.go
test/e2e/mcd_test.go

We need to support things like adding `nosmt` to the kernel
commandline, for users that want to choose security over performance;
this is particularly relevant for multi-tenant clusters.
There are a lot of other "tuning" features that are expressed as
kernel cmdline args; down the line we want `node-tuning-operator`
to write something like `machineconfig/05-node-tuning-operator`.
Per discussion in the PR, we down the line probably want to add
an `operatingsystem` type or so that would be a high level wrapper
for this, but today everything else is expressed in `MachineConfig`,
so we need to extend this type.
There have also been some discussions about extending Ignition,
but that's not likely to land soon, and even if it did we still
need to handle "early pivot" pulling …

 Add KernelArguments to MachineConfig

---

pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
pkg/controller/kubelet-config/kubelet_config_controller_test.go
pkg/controller/node/node_controller.go
pkg/controller/node/node_controller_test.go
pkg/controller/node/status.go
pkg/controller/node/status_test.go
pkg/controller/render/render_controller.go
pkg/controller/render/render_controller_test.go
pkg/operator/status.go
pkg/operator/status_test.go
test/e2e/mcd_test.go

See https://github.com/openshift/machine-config-operator/pull/765#issuecomment-493136113
MachineConfigPool needs a `Spec.Configuration` and `Status.Configuration`
[just like other objects][1] so that we can properly detect state.
Currently there's a race because the render controler may set `Status.Configuration`
while the pool's `Status` still has `Updated`, so one can't check whether the
pool is at a given config.
[1] https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status)

Add a Spec.Configuration to MachineConfigPool

---

cmd/machine-config-controller/start.go
cmd/machine-config-daemon/start.go
cmd/machine-config-server/start.go
pkg/controller/common/helpers.go

Debugging things is easier if we use the termination log, since
it ends up in the pod data which we can see directly in CI, etc.
Note since the daemon runs chrooted we can't quite make use of this
without doing e.g. `openat()` and holding a dfd for the real root
or so, but golang has an ergonomic hit for that.  May do it later.

Make use of /dev/termination-log

---

pkg/controller/kubelet-config/kubelet_config_controller.go

Do not requeue the key if there are zero MCPs. Prevents multiple status updates and will not succeed.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1714769
```
Fix status updates with kubeletconfigs with zero MCPs.
```

BZ1714769: fix kubeletconfig with empty MCPs status updates

---

pkg/daemon/constants/constants.go
pkg/daemon/daemon.go
pkg/daemon/node.go

~Builds on #806 for no good reason actually.~ brought it in here
Should take care of this one as well https://github.com/openshift/machine-config-operator/issues/660 but requires an MCD restart (we might want to drop `dn.booting` to have it automatically reconciles)
This is tricky, but the aim is to workaround missing annotations on node (best effort) - I haven't fully tested this just yet but reviews are highly appreciated.

Bug 1702626: pkg/daemon: reconcile if we lost annotations

---

machine-config-daemon.spec

As we move towards having more things in MachineConfig, we also
in many cases need the functionality during "early pivot" before
the cluster is up.
Let's just ship the MCD as part of the host as well so we can use
the same code then.
Now of course we have the same code in two places.  I think
what we'd want to do after this is have the "pod-MCD" call out
to the "host-MCD" as a subprocess.  That would actually simplify
other things as well.

Add a machine-config-daemon.spec

---

Makefile

fix https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/813/pull-ci-openshift-machine-config-operator-master-e2e-aws-op/2316

Makefile: drop GOCACHE for go1.12

---

Dockerfile.machine-config-controller
Dockerfile.machine-config-controller.rhel7
Dockerfile.machine-config-daemon
Dockerfile.machine-config-daemon.rhel7
Dockerfile.machine-config-daemon.upstream
Dockerfile.machine-config-operator
Dockerfile.machine-config-operator.rhel7
Dockerfile.machine-config-server
Dockerfile.machine-config-server.rhel7
Dockerfile.setup-etcd-environment
Dockerfile.setup-etcd-environment.rhel7

bump golang base images in Dockerfile(s) to 1.12, part of #796
/hold
Holding since we need openshift/release changes as well

Dockerfile.*: bump to golang-1.12

---

pkg/operator/operator.go

Triggering a sync on the following CMs chnages causes a wasteful sync (every 14s):
```
NAME                             DATA   AGE
machine-config                   0      27m
machine-config-controller        0      27m
```
Those cms seem to be bound to operator and controller leases. Since we
don't need to listen on them for our sync, just ignore them.
I'm following up with someone who understands more than me on this but it shouldn't be an issue to just ignore those.

Bug 1703234: pkg/operator: ignore CM changes that we don't care about

---

templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

The PR resolves a few issues.
* `ETCD_NAME` is currently populated from `hostname` but this is not always valid. For example, `hostname` in AWS returns the hostname of the node. But in baremetal hostname returns FQDN. Because we can no longer assume how etcd name is formatted we will ask for it as a mandatory param for `etcd-member-recover.sh`. With the addition of `validate_etcd_name function,` we can now extract the ETCD_NAME from `ETCD_INITIAL_CLUSTER` for `etcd-snapshot-restore.sh`.
* ETCD_CONNSTRING is now renamed ETCD_INTIAL_CLUSTER to more accurately reflect value.
* Fail early if SNAPSHOT_FILE does not actually exist.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1714457
/hold

DR: use param to populate etcd name

---

pkg/operator/status.go

added collection of master,worker MCP and CC
run must-gather

pkg/operator: expose more resources to must-gather

---

templates/common/_base/files/pull-secret.yaml

This is just generally a good idea; other processes on the host
besides kubelet have no business reading this.
Came out of discussion about supporting a pattern for *unprivileged*
pods that mount the host read-only, for inspection/tracing.

templates: Make pull secret mode 0600

---

pkg/daemon/update.go

Fixed some late review comments that I've just noticed over at https://github.com/openshift/machine-config-operator/pull/762/files#diff-13f28de2a32e0dab8f73b67aa5af9803R24
- roll back kargs on error
- do not bail when trying to update kargs on non-RHOS, just log it as we're doing for OS upgrades

pkg/daemon: roll back kargs on error and ignore kargs update on non-RHCOS

---

manifests/machineconfigdaemon/daemonset.yaml
pkg/operator/assets/bindata.go
test/e2e/sanity_test.go

Kubelet now has support for GA OS label as of 1.14.0. Bump MCD to use the new label.
ref: https://jira.coreos.com/browse/POD-114
ref: https://github.com/kubernetes/kubernetes/pull/73048
```
Change MCD to use the generally available OS label `kubernetes.io/os` as a selector.
```

mcd: use GA kubelet OS label

---

manifests/machineconfig.crd.yaml
manifests/machineconfigpool.crd.yaml
pkg/operator/assets/bindata.go

Added mc and mcd shortnames for MachineConfig and MachineConfigPool CRDs respectively.
`oc describe mc` and `oc describe mcp`
Added mc and mcd shortnames for MachineConfig and MachineConfigPool CRDs respectively.

Add shortnames for MachineConfig and MachineConfigPool CRDs

---

pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
pkg/controller/kubelet-config/kubelet_config_controller_test.go
pkg/controller/kubelet-config/kubelet_config_features_test.go
pkg/controller/node/node_controller_test.go
pkg/controller/render/render_controller_test.go
pkg/daemon/daemon_test.go
test/helpers/helpers.go

We had at least 4 different _test helper functions to create these. Just make 1 helper and use those.
Even though this PR along doesn't make a huge difference to the code base, at least I know where to look for the tests I'm writing in another PR...

Centralize test helpers for NewMachineConfig{,Pool}

---

pkg/controller/node/node_controller.go
pkg/controller/node/status.go

If the node belongs to more than 1 pool, run it through the same logic we use
to add it to the queue for a specific pool. This avoids including nodes in
multiple pools for status reporting and multiple desiredConfig swaps.
see https://github.com/openshift/machine-config-operator/issues/429#issuecomment-499458138 for testing. W/o this patch, the worker pool will show Updating with 6 nodes cause 3 nodes are both worker and infra. If you then add an MC for worker only, nodes go through reconciliation twice (which is super bad cause of reboot).
Close #429 
Close https://github.com/openshift/machine-config-operator/issues/294

pkg/controller/node: fix controller to handle multiple roles

---

cmd/machine-config-operator/bootstrap.go

This is a prep step for folding all mco component images into one mco image.
This flag will also be added to the installer.
This should not affect anything right now.
cc: @runcom

cmd/machine-config-operator: add mco image flag to bootstrap.go

---

pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/template/render.go
pkg/controller/template/render_test.go
pkg/controller/template/test_data/controller_config_baremetal.yaml
pkg/operator/render.go
templates/master/01-master-kubelet/baremetal/units/kubelet.yaml

For IPI baremetal, we need to support the platform in MCO. This PR also overrides the kubelet config to remove the NoSchedule taint.
Currently in the baremetal IPI installer fork, [we have to bail out of the installer early](https://github.com/openshift-metal3/kni-installer/blob/master/cmd/kni-install/create.go#L111) to take care of some things  - one of those things is disabling NoSchedule taints: https://github.com/openshift-metal3/dev-scripts/blob/master/06_create_cluster.sh#L82-L83
We are anxious to get an experimental version of this platform into openshift/installer, but need to resolve this issue first. This adds the barematel platform to MCO, and overrides the kubelet config. 
Once #763 is resolved, this can move to the new mechanism, or alternatively once we have workers being …

Add support for baremetal platform

---

pkg/daemon/update.go
test/e2e/mcd_test.go

Deploying an MC changing a file and later deleting it causes the file to
be deleted (it could have been already on disk i.e. shipped by an RPM).
Following Colin's suggestion, this patch adds a backup mechanism which,
when deleting an MC, causes the old file to be restored.
Added an e2e test as well.
closes https://github.com/openshift/machine-config-operator/issues/782

pkg/daemon: do not delete host files when deleting an MC

---

cmd/machine-config-daemon/pivot.go
pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/daemon/pivot/types/imageinspection.go
pkg/daemon/pivot/types/tuneargument.go
pkg/daemon/pivot/utils/fs.go
pkg/daemon/pivot/utils/run.go
pkg/daemon/pivot/utils/run_test.go
pkg/daemon/update.go
templates/common/_base/units/machine-config-daemon-initial.service

This is prep for having "early MCD" process kernel arguments
from MachineConfig objects at pivot time, and more generally
building up the model that the host processes `MachineConfig`,
not just Ignition.
Right now what I've tested is just manually running
`machine-config-daemon pivot registry.svc.ci.openshift.org/rhcos/machine-os-content:latest`
But, next step is to test having this take over the early pivot role,
then we can drop `/usr/bin/pivot` out of RHCOS.
See: https://github.com/openshift/machine-config-operator/issues/798

Import pivot code

---

pkg/controller/node/node_controller_test.go
pkg/controller/node/status_test.go

Add tests for `getNodesForPool` - the e2e version of this is going to QE directly for now but I'm hoping we can add it to our suite eventually.

pkg/controller/node: add tests for multiple pools

---

pkg/controller/template/render.go
pkg/controller/template/render_test.go

This causes an error during installation:
```
Jun 18 16:39:30 master-0 hyperkube[2223]: F0618 16:39:30.475150    2223
server.go:267] failed to run Kubelet: unknown cloud provider "baremetal"
```

controller: don't set cloud provider for baremetal

---

pkg/operator/render_test.go

Added a couple more unit tests to `pkg/operator`
`go test -v github.com/openshift/machine-config-operator/pkg/operator`
pkg/operator add unit tests

pkg/operator: Add unit tests

---

pkg/daemon/update.go

We know RHCOS has it being RHEL8.
Split out of https://github.com/openshift/machine-config-operator/pull/866

daemon: Fix inverted conditional for `logger --journald` check

---

pkg/server/bootstrap_server.go
pkg/server/cluster_server.go

Fixed some typos in `pkg/server/cluster_server.go` (`secert` -> `secret`) and cleaned up some other comments in `pkg/server/bootstrap_server.go`
Fix typos and comments in pkg/server

pkg/server: Clean up typos and comments

---

Makefile
docs/HACKING.md

In https://github.com/openshift/machine-config-operator/pull/818, the flag to disable `GOCACHE` was removed for go 1.12 compatibility.  Turns out, running unit tests with the cache enabled is frustrating.  For example, if a test asset (and not a test file itself) is updated, re-running `make test-unit` will pull test results from the test cache. Also, changing some parts of a unit test may not actually clear the entire test cache for that particular test (even though it should).
The _new_ way to disable the go testing cache is to use `-count=1` in the `go test` command.
(see https://github.com/golang/go/issues/24573)
`make test-unit` and verify that no test were pulled from the cache (ie. look for `(cached)`) …

Disable Go Unit Test Cache in Go 1.12

---

Dockerfile.machine-config-operator
Dockerfile.machine-config-operator.rhel7
cmd/machine-config-operator/bootstrap.go
install/0000_80_machine-config-operator_02_images.configmap.yaml
install/image-references
manifests/bootstrap-pod-v2.yaml
manifests/machineconfigcontroller/deployment.yaml
manifests/machineconfigdaemon/daemonset.yaml
manifests/machineconfigserver/daemonset.yaml
pkg/operator/assets/bindata.go
pkg/operator/images.go
pkg/operator/render_test.go

This is the 3rd pr in a series to fold all MC* images into one.
PR does the following as step 3:
- update dockerfile.machine-config-operator to generates all component
images (mco/mcc/mcd/mcs/setup-etcd-env)
- update dockerfile.machine-config-operator.rhel7 the same as sbove
- update image-references, configmap and manifests to use MCO image
- update MCO image flag in bootstrap.go to be required
TO-DO in follow-on prs:
- removes other dockerfiles to have 1 dockerfile generating image
- make another PR in release to only reference the above dockerfile
- make another PR in installer later to remove individual refs in bootkube
- make another PR here to remove the component image refs
- remove component image refs in ART(??)
Related-to: #847 (merged)
Requires: openshift/installer#1847 …

*: create a single MCO image containing all MC* binaries

---

pkg/daemon/constants/constants.go
pkg/server/bootstrap_server.go
pkg/server/cluster_server.go
pkg/server/server.go
pkg/server/server_test.go
pkg/server/testdata/machine-configs/test-config.yaml
pkg/server/testdata/machine-pools/test-pool.yaml

This effectively "inverts" a `MachineConfig` object so that
when it boots, Ignition processes the subset of MachineConfig
that is Ignition, and then we have the other stuff (`osImageURL`,
`kernelArguments` and in the future more) as a file on disk
that the MCD can read.
The way to think about this is we're aiming to have RHCOS boot
into `MachineConfig`, not just Ignition.

 server: Add /etc/ignition-machine-config-encapsulated.json

---

pkg/operator/status.go

Setting reason to error message can cause Prometheus to report too many series and can potentially bring it down completely.
This patch adds a reason constant to fix the above.
This will be followed up with the addition of more reason constants.

Bug 1722894: pkg/operator: Add FailedToSync Reason

---

pkg/daemon/rpm-ostree.go
templates/common/_base/units/machine-config-daemon-host.service

RHCOS will soon drop `pivot` entirely and I only tested the
bootimage pivot, but as soon as that lands in `machine-os-content`
we need this fix too.
Also this reveals the `-initial` nomenclature in the service
is wrong; I was originally thinking this was just for the first
boot.  But I'd forgotten about the whole saga around why we always
execute on the host because of SELinux.  I fleshed out some of
the comments there.
Rename the systemd unit to make that clearer too.

daemon: Use pivot/machine-config-daemon-host.service as needed

---

cmd/machine-config-daemon/pivot.sh
machine-config-daemon.spec

Since it exists in the docs, and there's already a nontrivial amount
of "muscle memory" around it.

Take over `/usr/bin/pivot` too

---

pkg/daemon/daemon.go
pkg/daemon/rpm-ostree.go
pkg/operator/operator.go
pkg/operator/sync.go

This patch set takes care of mainly three issues we've spotted:
- an osimageurl change from an upgrade can race with the old MCC
- we can still be running the old MCDs on nodes once the new MCC creates the new rendered
- if the node has never rebooted and ConditionFirstBoot is thus True, pivot reboots the node causing an upgrade failure
The above have been fixed by:
- rolling out the new MCC before applying the new osimageurl ConfigMap that is then templated by the new MCC
- roll out the MCDs before the MCC
- always remove `/etc/pivot/reboot-needed` when running pivot from the MCD

MCO/MCD: sync deployment before controllerconfig, roll out MCDs before MCC and remove pivot's reboot-needed file

---

pkg/daemon/rpm-ostree.go
templates/common/_base/units/machine-config-daemon-host.service

Since we merged a change to add `/usr/bin/pivot` redirecting
to the MCD, we need to fix this compat code.  Checking for the unit
file gives us the semantics we need here.

daemon: Look for pivot.service unit file instead of binary

---

pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
pkg/controller/container-runtime-config/container_runtime_config_controller_test.go
pkg/controller/kubelet-config/kubelet_config_controller_test.go
pkg/controller/node/node_controller.go
pkg/controller/node/node_controller_test.go
pkg/controller/node/status.go
pkg/controller/node/status_test.go
pkg/controller/render/render_controller.go
pkg/controller/render/render_controller_test.go
pkg/operator/status.go
pkg/operator/status_test.go
test/e2e/mcd_test.go

Cherry-picked from 37e8466a1a5d809b31a1e7782aeecb8abf62752b
See https://github.com/openshift/machine-config-operator/pull/765#issuecomment-493136113
MachineConfigPool needs a `Spec.Configuration` and `Status.Configuration`
[just like other objects][1] so that we can properly detect state.
Currently there's a race because the render controller may set `Status.Configuration`
while the pool's `Status` still has `Updated`, so one can't reliably check whether the
pool is at a given config.
With this, ownership is clear: the render controller sets the spec, and the node controller
updates the status.
[1] https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status)

[release-4.1] Bug 1706082: Add Spec.Configuration to MachineConfigPool, render controller writes it

---

docs/MachineConfiguration.md
lib/resourcemerge/machineconfig.go
pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/daemon/update.go
test/e2e/mcd_test.go

resurrected from https://github.com/openshift/machine-config-operator/pull/826
close https://github.com/openshift/machine-config-operator/pull/800
Added a new FIPS field to MachineConfig to enable/disable FIPS on rhcos (disabled by default). This is, at this point, only intended as a day-2 operation.
FIPS would also greatly benefit a dedicated CRD (oc edit fips?) - I'm experimenting with that but it will ofc require a new controller.
added an e2e and manually verified
Added FIPS support

pkg/daemon: support FIPS

---

manifests/containerruntimeconfig.crd.yaml
manifests/controllerconfig.crd.yaml
manifests/kubeletconfig.crd.yaml
manifests/machineconfig.crd.yaml
manifests/machineconfigpool.crd.yaml
pkg/controller/common/controller_context.go
pkg/operator/assets/bindata.go

Fixes #815 
Following #817, added a label for `mco-built-in/crd` to MCO CRDs in the `manifests/` directory.  
Then modified `apiExtSharedInformer` to filter based on this label.
Tested on an AWS cluster to be working.
Add logging statements to the `enqueue` function in `pkg/operator/operator.go` and watch `machine-config-operator` pod logs in kube and verify that non-MCO CRDs are not being re-synced (when they don't need to be, as seen in the issue, #815 ).
Filter out object changes not pertaining to MCO when re-syncing MCO CRDs.

pkg/operator Filter out non-MCO CRDs when re-syncing modified MCO CRDs

---

pkg/controller/node/status.go
pkg/controller/render/render_controller.go
pkg/controller/template/status.go
pkg/controller/template/template_controller_test.go

Closes #890.
Found all instances of `MachineConfigPoolCondition` and `NewControllerConfigStatusCondition` in the repo and swapped the (left) Reason field with the (right) Message field, as described in #890.
Unit testing / CI success
pkg/controller: Shorten error Reasons by moving them to Messages

pkg/controller: Shorten error Reasons by moving them to Messages

---

cmd/machine-config-controller/main.go
cmd/machine-config-daemon/main.go
cmd/machine-config-operator/main.go
cmd/machine-config-server/main.go

noticed the `mcc -> mco` typo, fixed that and uppercased all names as well

cmd: fix typo and uppercase components names

---

docs/README.md

Updated the docs with a `base64` encoded example
Apply the example MachineConfig and verify the file is landed on nodes
docs/README: Provided an example of using `base64` encoded file contents

docs/README: provide base64 encoded example

---

templates/common/_base/files/etc-systemd-user.conf.d-10-default-env.conf.yaml

Followup from: https://github.com/openshift/machine-config-operator/pull/901
We want the proxies to be set up for systemd user sessions as well, as it's
quite valid to do e.g. `systemd-run --user podman ...` even if not a primary
OpenShift use case today.

templates: Add proxy conf for systemd user sessions as well

---

pkg/daemon/pivot/utils/run_test.go

Fixed pkg/dameon/pivot/utils Linux assumptions:
- `echo -n` is not recognized in the `/bin/sh` mode; use universal `printf`.
- `stat -c` does not exist; use `wc`.
`make test-unit` now works for me on macOS; Linux will presumably be verified by CI.
N/A

Fix pkg/daemon/pivot/utils tests on macOS

---

pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/template/render.go
pkg/controller/template/render_test.go
pkg/controller/template/test_data/controller_config_gcp.yaml
pkg/operator/render.go

Allow the operator so understand `GCP` platform as suported.
Allow the template controller to create a kubelet service with cloud provider flag set to `gcp`
`add GCP support`

pkg: add GCP support

---

cmd/machine-config-daemon/pivot.go
pkg/daemon/rpm-ostree.go

daemon: Fix pivoting by trimming trailing newlines
Subtle API difference in the `runGetOut` that was duplicated
between the pivot and MCD codebases.  The trailing newline
wasn't expected by podman in further commands obviously.
My bad for not testing this, and doubly bad for not having CI coverage.

Fix upgrades/pivoting

---

pkg/daemon/daemon.go
pkg/daemon/rpm-ostree.go
pkg/operator/operator.go
pkg/operator/sync.go

Backport of https://github.com/openshift/machine-config-operator/pull/887
There's a simple reproducer for this but requires "bootimage == target oscontainer" to avoid an early pivot + reboot. Basically, at least on UPI, install 4.1.0 and upgrade to whatever this PR lands to (4.1.4?).

[release-4.1] Bug 1723327: sync deployment before controllerconfig, roll out MCDs before MCC and remove pivot's reboot-needed file

---

pkg/operator/operator.go
pkg/operator/render.go

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-rollback-4.1-to-4.2/10
The job above failed a 4.1 -> 4.2 upgrade, logs in MCO shows:
```
E0702 05:58:10.557039       1 operator.go:311] proxy.config.openshift.io "cluster" not found
E0702 06:02:00.258227       1 operator.go:311] proxy.config.openshift.io "cluster" not found
E0702 06:05:49.965328       1 operator.go:311] proxy.config.openshift.io "cluster" not found
E0702 06:09:39.666065       1 operator.go:311] proxy.config.openshift.io "cluster" not found
E0702 06:13:29.368922       1 operator.go:311] proxy.config.openshift.io "cluster" not found
```
It means the proxy object isn't in the apiserver and we fail at getting it, disrupting the whole upgrade. …

Bug 1726296: pkg/operator: handle missing proxy object

---

.golangci.yml
Makefile

While golangci-lint runs gosec as well; the way they did it was by
forking the gosec code and importing it. The issue is that they
haven't updated the fork in almost a year.
So to get the latest gosec, lets call it explicitly.
This depends on  openshift/release#4273
If golangci/golangci-lint#597 gets fixed, we could get rid of this.

CI: Add gosec to make verify

---

pkg/operator/bootstrap.go
pkg/operator/operator.go
templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml

Operator.go & bootstrap.go need to reference the MCO image instead of the
old setupetcdenv image.
Update template to add setupetcdenv entrypoint for MCO image.
Required-for: openshift/installer#1875
Related-to: #850
Related-to: #739 (issue will only close when final installer pr merges)
cc: @runcom

templates/mco: update template to replace setupetcdenv image with MCO image

---

test/e2e/mcd_test.go

Spotted a scary:
```
mcd_test.go:601: FIPS hasn't been enabled
```
Let's try to understand more cause current logs aren't that helpful
ref: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/918/pull-ci-openshift-machine-config-operator-master-e2e-aws-op/2670

test/e2e: add more logs to FIPS tests

---

pkg/controller/kubelet-config/helpers.go
pkg/controller/kubelet-config/kubelet_config_controller.go

Change validation of KubeletConfiguration to compare to type-cast fields instead of reflections.
unit tests and CI
Change validation of KubeletConfiguration to compare to type-cast fields instead of reflections.

controller/kubelet-config: Change validation of KubeletConfiguration to compare type-cast fields instead of reflections.

---

pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/status_test.go
pkg/operator/sync.go

Ref: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-rollback-4.1-to-4.2/10
From the above jobs the MCO isn't reporting the internal error
preventing the upgrade (or sync) to go through. This patch moves the
renderConfig setup to its own sync function in order to be accounted in
the CO object as any other sync functions.

pkg/operator: bubble up errors during MCO initial sync

---

docs/ContainerRuntimeConfigDesign.md
docs/KubeletConfigDesign.md

Clarify docs around KubeletConfig and ContainerRuntimeConfig - the pool must be edited to add a valid selector for the CR to take effect.

docs: clarify KubeletConfig and ContainerRuntimeConfig CR

---

cmd/machine-config-operator/bootstrap.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/template/constants.go
pkg/operator/bootstrap.go
pkg/operator/images.go
pkg/operator/operator.go
pkg/operator/render.go
pkg/operator/render_test.go
pkg/operator/sync.go
templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

Honestly finding images in the struct confusing as it's really the
collection of two different sets of images (renderConfig and
ControllerConfig).
This also led to some hassles around changing images in #899 for
instance.
This patch adds some comments around the scope of the images, split the
set in two different ones (still tied to the original struct) and change
the template keys used to substite.

pkg/operator: clarify MCO images and use better names

---

docs/HACKING.md

Minor doc fix to add missing link.

docs/hacking.md: fix osupgrades link

---

pkg/controller/container-runtime-config/container_runtime_config_controller.go
pkg/controller/kubelet-config/kubelet_config_controller.go

cascadeDelete for the container-runtime-config-controller and the
kubelet-config-controller can return errors, so lets handle those
(or at least issue the appropriate error message for visibility).

pkg/controller: Handle errors for cascadeDelete

---

Dockerfile
Dockerfile.rhel7

The final mco master dockerfiles will be named:
Dockerfile and Dockerfile.rhel7 We need to ratchet in the name
change by first adding these files and copying contents of the
current master dockerfiles Dockerfile.machine-config-operator/.rhel7
Once this is is merged will be able to update the names in release
and ART in followup prs and remove all other Dockerfiles.
Related-to: #894
Required-by: openshift/release#4314

fold mco images/ ratchet: add new master Dockerfiles with finalized names

---

pkg/operator/render.go
pkg/operator/render_test.go

The openshift v1 infrastructure API types have been updated (https://github.com/openshift/api/blob/master/config/v1/types_infrastructure.go).  As is, `render.go` does not take into account bare metal or GCP cluster type strings. The currently used struct fields are also marked as deprecated in the API source code.  
Should not be semantically different.
Update platform type strings in controller config spec

pkg/operator: Remove infra platform string constants

---

hack/push-image.sh

Moving script change out of #895, since that can't land until ART is sorted out. This can go in now.
We only have 1 image now so updating push-image.sh too.

dev: update push-image.sh to use new single mco image

---

docs/HACKING.md

Update commands in hacking.md since we now only have 1 Dockerfile/mco image.
Also add hack/push-image.sh command to hacking.md
Related-to: #948
Related-to: #950

docs: update hacking.md to reflect new commands

---

manifests/machineconfig.crd.yaml
pkg/operator/assets/bindata.go

Added a minimal openAPI spec definition to MachineConfig CRD to ensure it gets (minimally) validated when it is being created or changed
Attempt to create an MC with an empty spec -> error message
Create MC with a valid spec -> pass
Validate MachineConfigs have `spec:` field and add description to the ignition subset we support
Fixes #777

manifests/machineconfig.crd: set a minimal openAPIV3Schema

---

docs/README.md

Fixed typo with `charset` in example MachineConfig
Apply example MachineConfig to cluster
Fixed the `charset` value in the example MachineConfig
Must have fat-fingered this the first time I changed it in #900

README: fix charset value in example MC

---

Dockerfile.machine-config-controller
Dockerfile.machine-config-daemon
Dockerfile.machine-config-operator
Dockerfile.machine-config-server
Dockerfile.setup-etcd-environment
cmd/machine-config-operator/bootstrap.go
install/0000_80_machine-config-operator_02_images.configmap.yaml
pkg/operator/images.go

Remove all references to mcc/mcd/mcs/setupetdenv images so that we rely on the new MCO mega image only.
Note: Dockerfile.rhel7 images will be removed in a followup PR pending ART merge
Requires: https://github.com/openshift/installer/pull/1875
Related-to: openshift/machine-config-operator#739

* : remove refs to component images & dockerfiles

---

cmd/setup-etcd-environment/run.go
templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml

This PR adds support for exporting variables consumed as params by the etcd binary during the setup-etcd-environment init container. As we begin to move to cluster-etcd-operator managing bootstrap. We will need to gracefully transition the etcd-member.yaml spec to something more agnostic.
As an example use-case, I removed the runtime flag `--discovery-srv`  and replaced it with an environment variable. As some of these variables can be member-specific such as name they do not fit well with the MachineConfig model.
It would be easier in general to export all variables but as we prefix them with `ETCD_`  they will get picked up by the binary and print a bit of cruft during startup. For example.
```
2019-07-11 20:36:38.756064 W | pkg/flags: unrecognized environment variable …
```

cmd/setup-etcd-environment: add support for exporting env

---

pkg/controller/template/render.go
pkg/controller/template/render_test.go

currently the kubelet on GCP are failing with error:
```
Jul 13 01:06:03 ad-1-cmxng-master-0.c.openshift-dev-installer.internal hyperkube[1147]: F0713 01:06:03.195790    1147 server.go:267] failed to run Kubelet: unknown cloud provider "gcp"
```
the cloud provide name for GCP platform is `gce` [1]
[1]: https://github.com/kubernetes/kubernetes/blob/844a0c9a10cd52367ec7c05f5a8c176535dcef38/staging/src/k8s.io/legacy-cloud-providers/gce/gce.go#L59
the cloud provide name for GCP platform is `gce`

controller/template: update the cloud provider value for GCP to gce

---

manifests/master.machineconfigpool.yaml
manifests/worker.machineconfigpool.yaml
pkg/controller/container-runtime-config/container_runtime_config_controller.go
pkg/operator/assets/bindata.go
test/helpers/helpers.go

Fix https://github.com/openshift/machine-config-operator/issues/954
For custom defined pools (inheriting mainly from worker) do not sync the image config MCs. That's because we already sync for the default pools and that causes a resync for custom defined pool as well. Avoid also a spammy error log.

pkg/controller: skip image config MCs sync for custom defined pools

---

pkg/daemon/update.go

Extracted from https://github.com/openshift/machine-config-operator/pull/962
I'm not sure how we used to live w/o this till now - it shows ignored/evicting pods and progress so far so it's clear who's staying longer at evicting for instance.

pkg/daemon: log during drain

---

templates/common/_base/files/etc-systemd-system-crio.service.d-10-default-env.conf.yaml
templates/common/_base/files/etc-systemd-system-kubelet.service.d-10-default-env.conf.yaml
templates/common/_base/files/etc-systemd-system-machine-config-daemon-host.service.d-10-default-env.conf.yaml

https://github.com/openshift/machine-config-operator/pull/912/files moved files from system|user.conf.d without changing the format.
```
● crio.service - Open Container Initiative Daemon
Loaded: loaded (/usr/lib/systemd/system/crio.service; disabled; vendor preset: disabled)
Drop-In: /etc/systemd/system/crio.service.d
└─10-default-env.conf
Active: active (running) since Mon 2019-07-15 19:27:16 UTC; 18min ago
Docs: https://github.com/kubernetes-sigs/cri-o
Main PID: 1257 (crio)
Tasks: 21
Memory: 90.3M
CPU: 831ms
CGroup: /system.slice/crio.service
└─1257 /usr/bin/crio --enable-metrics=true --metrics-port=9537
Jul 15 19:27:15 master-0 systemd[1]: Starting Open Container Initiative Daemon...
Jul 15 19:27:16 master-0 systemd[1]: Started Open Container Initiative Daemon.
[Manager] …
```

templates: fix proxy envvars set in drop-in files

---

cmd/machine-config-controller/bootstrap.go
cmd/machine-config-controller/start.go
cmd/machine-config-controller/version.go
cmd/machine-config-daemon/start.go
cmd/machine-config-daemon/version.go
cmd/machine-config-operator/bootstrap.go
cmd/machine-config-operator/start.go
cmd/machine-config-operator/version.go
cmd/machine-config-server/bootstrap.go
cmd/machine-config-server/start.go
cmd/machine-config-server/version.go
cmd/setup-etcd-environment/run.go
cmd/setup-etcd-environment/version.go
pkg/controller/template/status.go
pkg/controller/template/template_controller_test.go
pkg/version/version.go

Since we now have a single image, we don't need to worry about
drift between them.
Previously we were trying to parse the output
of `git describe` (trimmed) as a semantic version, which blew
up when ART pushed a git tag that didn't conform to the previous pattern.
Just refer to the literal raw tag name instead of trying to parse it.
Closes: https://github.com/openshift/machine-config-operator/issues/976

Stop parsing our own version as semver

---

pkg/controller/template/render.go

Closes #857
Clarify platform none vs "" in template platform code.
https://github.com/openshift/installer/blob/master/pkg/types/installconfig.go#L122
The installer explicitly sets the `Platform` field to be `""` when a platform type is not specified.
Also, unsupported Platform fields should not be considered as `platformNone` since technically
`platformNone` is a [hidden-but-supported](https://github.com/openshift/installer/blob/master/pkg/types/installconfig.go#L36) platform.
pkg/controller: clarify platform none constant in template/render.go

pkg/controller: clarify platform none constant in template/render.go

---

pkg/controller/node/node_controller.go

Default masters schedulable to false when scheduler spec doesn't exist.

Validate nil values in scheduler spec

---

pkg/controller/common/helpers.go
pkg/controller/common/helpers_test.go
pkg/controller/render/render_controller.go
pkg/controller/render/render_controller_test.go
pkg/daemon/update.go
test/e2e/mcd_test.go
test/helpers/helpers.go

Wrap ignition validation in helper function that adds exception
for empty ign configs.  Use helper validation function in update.go
and render_controller.go
Update and add unit tests
Closes: #888

daemon/controller: handle empty ignition configs

---

cmd/machine-config-operator/bootstrap.go

This is a prep patch to make these images available in MCO
templates. After this merges, we can merge a patch to the
installer which passes these flags.
These images are needed by the following PRs:
https://github.com/openshift/machine-config-operator/pull/795
https://github.com/openshift/machine-config-operator/pull/740

openstack: baremetal: Add static pod image flags to bootstrap.go

---

Makefile
docs/HACKING.md
hack/build-image
hack/build-image.sh
hack/cluster-push.sh

This fixes the `./hack/cluster.push` script to replace all MCO components rather than accepting a `WHAT` since...a lot of nontrivial changes require doing all of them, and since we have a uni-image we might as well now!
The `build-image` script changes apply to both the "cluster push fast-path" as well as the "new release image" path.
The `HACKING.md` doc is updated for the above and more.

local dev/hacking improvements

---

pkg/operator/render.go

Set the proxy iff its status isn't empty + add a log to signal we're not setting proxy otherwise. Been debugging an issue with @sjenning and it turns out we weren't setting the proxy because the proxy object hasn't the Status populated but that's it's expected to be populated so something else is going on.
From the design doc:
> A simple proxy operator will watch for this resource and upon seeing it (or changes to it), will validate the proxies defined in the spec are reachable.  If they are, the proxy configuration will be copied to the status field, indicating a proxy configuration which is valid to be consumed by other components.  The purpose of this operator is to ensure that if an admin provides an invalid proxy configuration, the consuming components are not …

pkg/operator: log when proxy isn't going to be set

---

templates/common/_base/files/etc-systemd-system-pivot.service.d-10-default-env.conf.yaml

if pivot.service is there and we need to set a proxy, we need the template for that. Right now, we only do that for machine-config-daemon-host.service.
Fix the linked BZ
@cgwalters ptal

Bug 1730562: templates: add proxy to pivot.service

---

Makefile
hack/install-go-bindata.sh

This also inverts the dependency we have with openshift/release.
This has a downside tho..if someone adds something that brings down the whole infra it can be our fault to have allowed arbitrary binaries executions. On the other hand.. we're running in pods
Close https://github.com/openshift/machine-config-operator/issues/951

Makefile: pin tools to specific versions

---

hack/build-image

Quick fix for building the MCO image in `build-image` if you _do not_ have a previous version of the MCO image on your local machine.
`make image` without any prior MCO images.
hack: Fix build-image script for first time MCO builds

hack: Fix build-image script for first time MCO builds

---

pkg/daemon/daemon.go
pkg/daemon/update.go

WIP mainly because I want to test it out on a live cluster by forcing a grace period of something really low to kick the kubelet killing the MCD
This patch removes the perma-failure we have in case:
- we were draining
- we exceeded 600s terminationGracePeriod
- the kubelet killed (9) us
The above can be deducted by:
- pending config is on disk
- bootID equality
In such case, we can go ahead and re-kick and drain+reboot routine till it eventually succedes (modulo: as Colin said in https://bugzilla.redhat.com/show_bug.cgi?id=1728873 we're in a permanent situation where we can't really drain _forever_)
testing it manually for now

pkg/daemon: reconcile being killed by kube on drain+reboot

---

install/image-references

The BareMetal and OpenStack platforms need additional images included
for the static pods those platforms create.

Add baremetal and openstack additional images to image-references

---

pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
pkg/operator/render.go

oVirt and possibly other platforms needs access the InfrastructureStatus
to render properly config files with stuff like API VIP, DNS VIP etc.
By embedding the infra object its available for rendering in
tremplates - for example a coredns config file like this:
```
{{ ControllerConfig.Infra.Status.PlatformStatus.Ovirt.DnsVIP }} api-int.{{.EtcdDiscoveryDomain}} api.{{.EtcdDiscoveryDomain}} ns1.{{.EtcdDiscoveryDomain}}
```
**How to verify it**
TODO will create a test
Fixes: #812 
Required-by: #795

Make the infra object available for template rendering

---

pkg/daemon/daemon.go
pkg/daemon/update.go
pkg/daemon/update_test.go

Extracted from https://github.com/openshift/machine-config-operator/pull/935
With one other small commit on top. 
Would like to land this so I'm less in rebase hell later...

Mcd encap prep cleanups 1

---

pkg/server/testdata/machine-configs/test-config.yaml
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/master/01-master-kubelet/baremetal/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

Removed all the unwanted backslash newline escape chars from the service files
While testing on the fedora coreos, have seen these extra backslash newline escape chars were creating issues and couldn't start the service, hence removing them anyways which aren't required here.

Remove the unwanted backslash newline escape chars

---

docs/HACKING.md

Correct the link to OSUpgrades.md in docs/HACKING.md
1.  Navigate to docs/HACKING.md
2.  Follow link to OSUpgrades.md
3.  Feel good about no HTTP 404 error
Corrected the link to OSUpgrades.md in docs/HACKING.md

docs/HACKING: correct link to OSUpgrades.md

---

pkg/operator/render.go

Closes #1001
Drop the verbosity of the "proxy not set" warning.
`oc project openshift-machine-config-operator`
`oc get pods`
`oc logs machine-config-operator-xxxx`
pkg/operator: Fix proxy logging verbosity

pkg/operator: Change proxy logging verbosity

---

templates/common/openstack/units/afterburn-hostname.yaml

This commit sets hostnames equal to OpenStack node names.

OpenStack: set correct hostnames for masters and workers

---

pkg/controller/template/render.go
pkg/controller/template/render_test.go

Cloud provider was temporarily disabled, but now we can enable it again, because its support was added to the installer.

Enable cloud provider for OpenStack

---

Gopkg.lock
cmd/machine-config-operator/bootstrap.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
pkg/operator/bootstrap.go
pkg/operator/sync.go
templates/common/_base/files/additional-trust-bundle.yaml
vendor/github.com/openshift/api/config/v1/types_apiserver.go
vendor/github.com/openshift/api/config/v1/types_authentication.go
vendor/github.com/openshift/api/config/v1/types_console.go
vendor/github.com/openshift/api/config/v1/types_dns.go
vendor/github.com/openshift/api/config/v1/types_proxy.go
vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go

This patch implements the last mile to the Proxy support specifically
(and later, CAs for mirrors).
This just reads from the installer objects and set up the bundle on disk
to be later updated via the new update-ca service shipped in RHCOS.
The service should always run early enough to always have the correct CA
on system to services to be consumed.

pkg/operator: support additional CA bundle

---

cmd/machine-config-operator/bootstrap.go
install/0000_80_machine-config-operator_02_images.configmap.yaml
pkg/controller/template/constants.go
pkg/controller/template/render_test.go
pkg/controller/template/test_data/controller_config_baremetal.yaml
pkg/operator/bootstrap.go
pkg/operator/images.go
pkg/operator/sync.go
templates/common/baremetal/files/baremetal-NetworkManager-kni-conf.yaml
templates/common/baremetal/files/baremetal-coredns-corefile.yaml
templates/common/baremetal/files/baremetal-coredns.yaml
templates/common/baremetal/files/baremetal-keepalived.yaml
templates/common/baremetal/files/baremetal-mdns-publisher.yaml
templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
templates/master/00-master/baremetal/files/baremetal-mdns-config.yaml
templates/master/00-master/baremetal/files/dhcp-dhclient-conf.yaml
templates/worker/00-worker/baremetal/files/NetworkManager-non-virtual-ip-prepender.yaml
templates/worker/00-worker/baremetal/files/baremetal-keepalived-keepalived.yaml
templates/worker/00-worker/baremetal/files/baremetal-mdns-config.yaml
templates/worker/00-worker/baremetal/files/baremetal-non-virtual-ip.yaml
templates/worker/00-worker/baremetal/files/dhcp-dhclient-conf.yaml

Adds pods to master and worker nodes as appropriate for baremetal deployment.
Requires: #943

baremetal: Add coredns, mdns-publisher, haproxy, keepalived static pods

---

docs/HACKING.md
hack/build-image
hack/cluster-push-prep.sh
hack/cluster-push.sh

This patch mainly modifies scripts under ./hack to allow people (me) to
develop using docker instead of podman (various reasons behind that, osx
mainly but still, many people are using docker). What this allows is:
podman=docker ./hack/cluster-push.sh
The normal flow with podman shouldn't have changed (please test it out!).
Also dropped a wrong section from HACKING.md and a minor change there as well.

hack: allow using Docker for development

---

pkg/operator/bootstrap.go

Fix https://github.com/openshift/machine-config-operator/issues/1017
We were wrongly using the config scheme codec. This fixes that by using the corev1 and fixes the issue linked.
@jcpowermac ptal

pkg/operator: use corev1 codecs to decode configmaps

---

pkg/operator/status.go
pkg/operator/status_test.go
pkg/operator/sync.go

Set the condition "upgradeable" on the "machine-config"  cluster operator.
https://github.com/openshift/api/blob/9525304a0adb725ab4a4a54539a1a6bf6cc343d3/config/v1/types_cluster_operator.go#L140
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1727022

Bug 1727022: set upgradeable operator condition

---

templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
templates/master/00-master/baremetal/files/baremetal-haproxy.yaml

Modify the haproxy container so that before starting HAProxy it creates a unix datagram socket that haproxy can connect to as if it were syslog's socket.
```crictl logs id_of_haproxy_container```
should give an output containing entries like this:
```
<133>Jul 29 11:23:20 haproxy[14]: Proxy main started.
<141>Jul 29 11:23:20 haproxy[14]: Proxy main started.
<133>Jul 29 11:23:20 haproxy[14]: Proxy health_check_http_url started.
<141>Jul 29 11:23:20 haproxy[14]: Proxy health_check_http_url started.
<133>Jul 29 11:23:20 haproxy[14]: Proxy stats started.
<141>Jul 29 11:23:20 haproxy[14]: Proxy stats started.
<133>Jul 29 11:23:20 haproxy[14]: Proxy masters started.
<141>Jul 29 11:23:20 haproxy[14]: Proxy masters started.
<134>Jul 29 11:23:20 haproxy[15]: …
```

baremetal: fix haproxy logging

---

Makefile
pkg/controller/node/node_controller.go
test/e2e/mcd_test.go

In case a user needs to rollback the custom pool he can do so by
removing the custom pool label from the node. However, w/o this patch
the MCC wasn't reacting to label changes. It should be safe to only
react to label changes also since we only care about the role label and
the labels aren't updated that often.
`oc label node ip-10-0-143-53.ec2.internal node-role.kubernetes.io/infra-`
The command above is going to drop the infra label from a worker,infra node causing it to rollback to a worker rendered MC.
This also expands the e2e added in #1007 

pkg/controller: allow custom pool rollback

---

pkg/controller/kubelet-config/kubelet_config_controller.go

This fixes a regression introduced in https://github.com/openshift/machine-config-operator/commit/680f79c9c7002bdc56b7d5f7481a2c7712fda164#diff-bc0cd3d2a7a92d7ffb804b2d7b2a5636R54 - I think this can cause the resulting kubeletConfig MC to be deleted when the kube GC kicks in but I haven't successfully verified that. Besides, the controller for kubeConfig is `KubeletConfig` so fix that.

pkg/controller/kubelet-config: fix owener reference

---

install/image-references

Update install/image-references to remove stale references to non-mco images. And remove my to-do.
Note: this is required for multi-arch team work. cc: @yselkowitz

Bug 1737120: fold images: remove stale refs to mc* images in install/image-references

---

pkg/controller/node/node_controller.go

When the scheduler config option, "mastersSchedulable: true" was set
at install time, I observed inconsistent behavior.  Roughly half of
the time this controller would successfully apply this configuration.
The code was only checking the scheduler configuration in the
scheduler config object informer.  When the Add function was called,
the cache was sometimes not yet populated with Nodes.
The fix in this patch is to reconcile the scheduler config any time a
Node is added or updated, as well.
This will also ensure that this configuration option is re-applied
after unexpected changes like the worker label being manually removed
from a Node.
Closes issue #1024

node_controller: Check scheduler config on Node changes.

---

templates/master/00-master/baremetal/files/baremetal-haproxy.yaml

In current code, the haproxy process in haproxy container being started/restarted
only upon request (configuration change) from the monitor container.
So in case haproxy container fail due to liveness probe, it won't run the haproxy
process until configuration will be changed.
To fix that,  the haproxy process will be started if the haproxy cfg file exists.

baremetal - haproxy static pod, run haproxy process if cfg file exist

---

pkg/server/api.go

This is a tiny improvement to the MCS init code logging. 
Right now, when you check the pods logs for the MCS, you see 2 lines that say `launching server`, one after another. This is confusing if you don't know that the MCS hosts both secure and insecure servers.  This PR changes the logging output so its more clear that the MCS is listening and serving on 2 different addresses, rather than accidentally starting 2 of the same server.
Deploy image.
`oc logs machine-config-server-xxxx`
pkg/server: Increase verbosity of server launching

pkg/server: Increase verbosity of server launching

---

hack/cluster-push.sh

Right now the `cluster-push` script errors out if you don't export `podman=podman` or `podman=docker`.
Since the `build-image` script assumes you are using `podman` as a default, we can ignore the `podman` variable in _this_ script if it is not set in the env (and thus default to `podman` when building).
`unset podman`
`./hack/cluster-push.sh`
hack: Don't error out on cluster-push.sh by default

hack: Don't error out on cluster-push.sh by default

---

Makefile
test/e2e/mcd_test.go

Since the router pod started using a PDB, we're noticing a 3m+ delay in
drain on the node that hosts the router, which makes e2e timeouts.
This patch increases the timeout to 120m to be sure we're in time.
Fix #1039 

Makefile: increase test-e2e timeout to 120m

---

manifests/baremetal/keepalived.yaml
pkg/operator/assets/bindata.go

A recent installer change started using a loopback address in kubeconfig
as the default on the bootstrap node. baremetal-runtimecfg will begin
using cluster-config.yml if it exists first, in order to get the domain
and name of the cluster.
This patch adds a flag for this to the keepalived bootstrap pod in order
to utilize it. This should only affect the bootstrap pods.
Fixes: #1037
Depends on openshift/baremetal-runtimecfg#16

baremetal: keepalived to pass cluster-config.yml to runtimecfg

---

templates/common/_base/units/machine-config-daemon-host.service

Implicitly this was happening before because the `pivot` package
contained the systemd unit, and so there was nothing to react
to the MCS injecting `/etc/pivot/image-pullspec`.  Now that the MCD
injects this systemd unit, we need to ensure it's only run
on ostree-managed systems, not BYO RHEL.
Closes: https://github.com/openshift/machine-config-operator/issues/1046

templates: Don't run machine-config-daemon-host on BYO RHEL

---

templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
templates/master/00-master/openstack/files/openstack-haproxy.yaml

The OpenStack HAproxy static pod configuration was copied from the
Baremetal implementation. This commit pulls the following 2 fixes from
BM haproxy config:
https://github.com/openshift/machine-config-operator/commit/8082db516b5d38c9d92a0f684c8a80a4816c93c0
https://github.com/openshift/machine-config-operator/commit/7b997f6c859240409f34539871190e433c1a872f

openstack: import HAproxy config fixes from BM

---

manifests/openstack/keepalived.yaml
pkg/operator/assets/bindata.go

This pulls in fix
https://github.com/openshift/machine-config-operator/pull/1043 for
openstack.
A recent installer change started using a loopback address in
kubeconfig as the default on the bootstrap node. baremetal-runtimecfg
will begin using cluster-config.yml if it exists first, in order to get
the domain and name of the cluster.
This patch adds a flag for this to the keepalived bootstrap pod in
order to utilize it. This should only affect the bootstrap pods.

openstack: keepalived to pass cluster-config.yml to runtimecfg

---

pkg/operator/sync.go

followup to https://github.com/openshift/installer/pull/2173
/cc @jcpowermac @runcom @danehans

pkg/operator/sync.go: udpate the namespace for trust configmap

---

pkg/controller/node/node_controller.go
pkg/controller/node/node_controller_test.go

When a node belongs to more than one pool, we need to trigger a resync
for all the pools it belongs to or we leave the "parent" MCP at an old
state. The easy example would be to create an infra pool of just 1
node and describe the worker mcp and notice that it still has all nodes
(including the now-infra node).

Bug 1738831: pkg/controller/node: resync all pools for a node

---

Dockerfile
Dockerfile.rhel7
Gopkg.lock
Gopkg.toml
cmd/gcp-routes-controller/main.go
cmd/gcp-routes-controller/run.go
cmd/gcp-routes-controller/version.go
pkg/controller/template/constants.go
pkg/operator/bootstrap.go
pkg/operator/sync.go
templates/master/00-master/gcp/files/etc-kubernetes-manifests-gcp-routes-controller.yaml
vendor/github.com/InVisionApp/go-health/LICENSE
vendor/github.com/InVisionApp/go-health/checkers/http.go
vendor/github.com/InVisionApp/go-health/checkers/reachable.go
vendor/github.com/InVisionApp/go-health/checkers/sql.go
vendor/github.com/InVisionApp/go-health/health.go
vendor/github.com/InVisionApp/go-health/safe.go
vendor/github.com/InVisionApp/go-logger/LICENSE
vendor/github.com/InVisionApp/go-logger/log.go

turn a service on/off based on the status of the health check provided.
** Background
On GCP, network load balancing requires modification of the local machine's routes to include the forwarded_ips of the LB rules.
Therefore, for a VM in the backend pool, the traffic to the LB never leaves the box (regardless of the health checks...)
for more info: https://cloud.google.com/load-balancing/docs/internal/setting-up-internal#test-from-backend-vms
This esp. affects the OpenShift control-plane as the clients like kubelet, openshift-networking (SDN) communicate with the apiserver using the LB.. and therefore can only communicate if the
local apiservers is running. This is very fragile during roll-out of the apiserver pods as any interminent faliure to start the local apiserver pod means that …

 cmd: add gcp-routes-controllers to manage the routes service to prevent blackholes

---

pkg/controller/template/render.go

This reverts commit 759702e7bd490099065405cb90742a2a5ce6d2fc.
openshift/installer#1959 is merged, so we can enable template rendering again.

Revert "openstack: Allow to run MCO changes independently of the installer patches" 

---

templates/master/00-master/gcp/files/etc-kubernetes-manifests-gcp-routes-controller.yaml

Added resource request to gcp-routes-controller. Added similar requests to machine-config-server
**- Why**
Test `[Feature:Platform][Smoke] Managed cluster should ensure control plane pods do not run in best-effort QoS [Suite:openshift/conformance/parallel]` is failing example
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/23569/pull-ci-openshift-origin-master-e2e-gcp/3217
because gcp-routes-controller pod is given BestEffortQoS as it doesn't define any resource requests.
more info: https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-burstable
/cc @csrwng

gcp: add resource requests to gcp-routes-controller to make sure it is not in BestEffortQoS

---

templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

Currently, we use a poor assumption that the static pod revision will never go higher than 10[1]. As reported in BZ and confirmed with masters team this is not the case. While the controller would set a MaxEligibleRevision[2] this does mean a linear 0 -> N meaning although `0 - 9` is valid so is `20 - 29`. So we no longer assume instead we populate an array with observed directories output from ls.
[1]https://github.com/openshift/machine-config-operator/compare/master...hexfusion:fx_etcd_backup?expand=1#diff-df2f7b2c367c15c3aa83f8b8e002b3d8L37
[2] https://github.com/openshift/library-go/blob/a5507e7eb29c0ec68b73bd355cf5d248586fd776/pkg/operator/staticpod/prune/cmd.go#L56
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1737575

Bug 1737575: DR: use observed directories vs assumptions for backup_etcd_client_certs

---

pkg/controller/render/render_controller.go
pkg/controller/render/render_controller_test.go
test/e2e/mcd_test.go

also update existing unit tests to pass new validation
closes: BZ 1726866
Note: this is already fixed in master in PR  #894 This PR is a backport for 4.1.z
cc: @runcom

[release-4.1] Bug 1726866: mcc: fix ignition validation to validate entire ign config

---

templates/master/00-master/baremetal/files/baremetal-haproxy.yaml

This commit enables the logging of Haproxy events into haproxy container after
Haproxy container being restarted once.
In current code, after Haproxy container being restarted(e.g: due to Liveness probe); we'll
hit [1] error.
[1]- + socat UNIX-RECV:/var/run/haproxy/haproxy-log.sock STDOUT
2019/08/14 07:21:03 socat[8] E "/var/run/haproxy/haproxy-log.sock" exists

Baremetal: enable Haproxy events logging after Haproxy container  being restarted

---

templates/master/00-master/_base/files/usr-local-bin-openshift-kubeconfig-gen.yaml

Changes the kubelet recovery script to use the internal URI. The initial kubeconfig uses the internal URI as well. Additionally, this removes a dependency on the load balancer cert being valid during recovery.
`recovery-kubeconfig` will contain the api-int.* domain name in the server field.
`NONE`

Bug 1738857: use internal URI for recovery kubeconfig

---

pkg/daemon/update.go

Do not even run the script  for enabling/disabling FIPS on non-RHCOS. Fix the linked BZ.

Bug 1743621: pkg/daemon: error early if updating FIPS on non-RHCOS

---

templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml

Currently, the DR scripts do not check if parameters are valid. 
Added checks for valid params to backup and restore scripts.
Fixes: [BZ 1712826](https://bugzilla.redhat.com/show_bug.cgi?id=1712826)
/cc @hexfusion  @retroflexer

Bug 1712826: DR: Add pre-run checks for backup and restore scripts

---

templates/master/00-master/openstack/files/openstack-haproxy.yaml

After haproxy container is recreated (for example due to liveness probe failure),
the haproxy events don't log anymore in container's logs, and we hit [1]
This commit copy the fix from baremetal platform.
[1]- + socat UNIX-RECV:/var/run/haproxy/haproxy-log.sock STDOUT
2019/08/14 07:21:03 socat[8] E "/var/run/haproxy/haproxy-log.sock" exists

Bug 1744133: Openstack - copy Haproxy container log fix from Baremetal

---

pkg/controller/render/render_controller.go
pkg/operator/status.go

Problem: output of  `oc get co machine-config -o yaml` is pointing to current config name: 
```worker: 0 (ready 0) out of 2 nodes are updating to latest configuration rendered-worker-2fe2c50ca1b300646e59b6fad007d537``` 
instead of the name of the desired/target config that is being applied.
Through some testing/adding additional logs I verified the target config in Spec was set properly at the correct time.  The issue was status.go was improperly referencing `pool.Status.Configuration.Name`  (current config) instead of `pool.Spec.Configuration.Name` in its output.
Closes: BZ 1743361

Bug 1743361: fix updating version output

---

pkg/controller/kubelet-config/errors.go
pkg/controller/kubelet-config/kubelet_config_controller.go

Add a forgettable error type that is caught by the error handler to not requeue the key.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1743487
```NONE```

Bug 1743487: Do not requeue a failed kubeletconfig decode

---

templates/master/00-master/_base/files/usr-local-bin-etcd-member-add-sh.yaml

Fixes: #1734554
The current etcd DR scripts are intended to be used when quorum is lost. However, in simpler cases, an etcd member may fail to restart, but the certificates are valid. In that case, The solution is to remove the member from the cluster, and re-add using etcd-member-add.sh. This script can be used in conjunction with etcd-member-remove.sh.
Created a new DR script etcd-member-add.sh which allows users to easily add back an etcd member when the certs are valid.
1.) Create a new cluster
2.) remove a member using the etcd-member-remove.sh script.
3.) add back the member using this script
3.) verify with etcdctl member list

Bug 1734554: provide etcd-member-add.sh for adding back a member with valid certs

---

pkg/daemon/update.go

Backing up the original file to its $PWD has a side effect on certain
directories like the Kube static pod dir. If a file is backed up there,
it will be still processed by kube which is completely wrong and
unwanted.
This patch is instead backing up the file inside
/etc/machine-config-daemon/$FPATH avoiding the pitfall above.
Fix https://github.com/openshift/machine-config-operator/issues/1074
Let's debate on the `/etc/machine-config-daemon` location, I don't really like it but I'm accepting other suggestions.
cc @hexfusion 

Bug 1744580: pkg/daemon: create orig file outside of pwd for the file

---

pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/status_test.go
pkg/operator/sync.go

Needs cherrypicking for 4.1.z, in order to fix BZ 1741065: 
Add reason for degradation to ClusterOperatorStatusCondition
CI
pkg/operator: Report degraded reason in cluster operator status

Bug 1744764: Report degraded reason in cluster operator status

---

templates/common/_base/files/sysctl-inotify.conf.yaml

add template to create /etc/sysctl.d/inotify.conf with inotify.max_users defaults taken from: 
https://github.com/openshift/openshift-ansible/blob/release-3.11/roles/tuned/templates/openshift-node/tuned.conf
Closes: BZ 1735661

Bug 1735661: add template with default inotify.max_users settings

---

pkg/operator/status.go

The ControllerConfig name is "machine-config-controller", not "cluster".
That was causing the cc to not being collected with must-gather.

Bug 1745240: pkg/operator: fix related objects for must-gather

---

pkg/daemon/constants/constants.go
pkg/daemon/daemon.go

This causes the MCD to skip validating against `currentConfig` (or `pendingConfig`).
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1741817
A long time ago, this PR introduced the current model:
https://github.com/openshift/machine-config-operator/pull/245
One aspect of this is we need to avoid reboot loops; that was
a real-world problem early in OpenShift development, although
it is probably unlikely to re-occur today.
Another problem is that we can't simply reconcile by default because
we don't have a mechanism to coordinate reboots:
https://github.com/openshift/machine-config-operator/issues/662#issuecomment-506472687
However, this PR should aid disaster recovery scenarios and others
where administrators want the MCD to "just do it".

Bug 1741817: mcd: Add /run/machine-config-daemon-force stamp file

---

manifests/baremetal/keepalived.yaml
manifests/openstack/keepalived.yaml
pkg/operator/assets/bindata.go
templates/common/baremetal/files/baremetal-keepalived.yaml
templates/common/openstack/files/openstack-keepalived.yaml

curl commands on the keepalived static pod cause a huge amount of memory dentries.
The underlying bug is https://bugzilla.redhat.com/show_bug.cgi?id=1571183.
For more details see:
https://github.com/openshift/machine-config-operator/pull/705
https://github.com/openshift/openshift-ansible/pull/11829
Supersedes PR #1070

Bug 1743768: avoid excessive dentries due to keepalived static pod health check

---

templates/master/00-master/_base/files/usr-local-bin-etcd-member-remove-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

The current etcd DR scripts are intended to be used when quorum is lost. In the case of for example, on-disk corruption etcd may fail to restart. The solution is to remove the member from the cluster, destroy data-dir, and re-add using etcd-member-recover.sh. This script allows for the removal of an etcd member to take place easily.
Created a new DR script etcd-member-remove.sh this allows users to easily remove a failed etcd member.
1.) Create a new cluster
2.) remove a member using the script.
3.) verify with etcdctl member list
- Added: new DR script etcd-member-remove.sh to easily facilitate removal and replacement of failed etcd member.
openshift-recovery-tools
- Added: export ETCDCTL_API=3 
- Added: …

Bug 1734554: DR: add etcd-member-remove.sh

---

install/0000_80_machine-config-operator_04_deployment.yaml
manifests/bootstrap-pod-v2.yaml
manifests/machineconfigcontroller/deployment.yaml
manifests/machineconfigdaemon/daemonset.yaml
manifests/machineconfigserver/daemonset.yaml
pkg/operator/assets/bindata.go
templates/master/00-master/_base/files/usr-local-share-openshift-recovery-template-etcd-generate-certs-yaml-template.yaml

All containers should generally set terminationMessagePolicy to fallback
so that system agents can observe the last chunk of error output when a
pod crashes or dies.
In 4.2 insights-operator will automatically gather these if containers
have crashed.

Bug 1747432: manifests: Add missing terminationMessagePolicy FallbackToLogsOnError

---

templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml

On high message rates, the default 10MB buffer rotates quickly enough to miss messages. OSE 3.11 
bumped this limit to 50MB within this [commit](https://github.com/openshift/openshift-ansible/commit/5e57addcb1bc88d36015e6f06c209985d1e0dbc7) to capture more messages before the buffer rotates.
Bump the limit in the kubelet master and worker configuration files to 50 MB.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1741955
```
Bump Kubelet container log buffers to 50 MB. Disk space on a node will increase due to more logs being retained.
```

Bug 1741955: bump containerLogMaxSize to 50MB

---

pkg/operator/sync.go

The kubelet should always use the internal API server FQDN, so it does not rely on the LB certificates.

Bug 1747608: APIServerInternalURL fix for kubelet

---

pkg/daemon/daemon.go
pkg/daemon/update.go

If the MCD has applied the update during a sync but it's still in
drain+reboot phase and it gets killed (OOM for instance), it can end up
in a permanent failure leaving node unschedulable as well. Since we know
at which point of the sync the MCD was (we have state on disk and bootid), if it
happens to be killed, instead of permanently failing, we can attempt the
drain+reboot phase again. 
This is definitely better than just bailing and leaving nodes
unschedulable which might also disrupt upgrades.

Bug 1728873: pkg/daemon: reconcile killed just prior drain+reboot

---

Gopkg.lock
Gopkg.toml
pkg/daemon/daemon.go
pkg/daemon/update.go
vendor/github.com/openshift/cluster-api/LICENSE
vendor/github.com/openshift/cluster-api/pkg/drain/drain.go

openshift/kubernetes-drain is about to be officially deprecated and
already discontinued. We need to use the cluster-api's one (which is
basically a fork +
https://github.com/openshift/kubernetes-drain/pull/4).
We also need https://github.com/openshift/kubernetes-drain/pull/4 to
avoid flooding the apiserver as the MAO did (https://bugzilla.redhat.com/show_bug.cgi?id=1733708).
Also, MCO already updated in 4.1 and 4.2 with https://github.com/openshift/kubernetes-drain/pull/3 which is the actual fix to limit the rate of requests for eviction - this bump is to make sure to bring the deadlock fix.

Bug 1748844: vendor: use cluster-api's drain lib

---

templates/common/_base/files/etc-systemd-system-crio.service.d-10-default-env.conf.yaml
templates/common/_base/files/etc-systemd-system-kubelet.service.d-10-default-env.conf.yaml
templates/common/_base/files/etc-systemd-system-machine-config-daemon-host.service.d-10-default-env.conf.yaml
templates/common/_base/files/etc-systemd-system-pivot.service.d-10-default-env.conf.yaml

Fixes [bz-1745875](https://bugzilla.redhat.com/show_bug.cgi?id=1745875)
Remove double quotes surrounding proxy envvar values in config templates. The quotes seem to be causing issues on RHEL worker nodes.
Run cluster install and then RHEL scaleup using HEAD: worker nodes do not become ready. 
Run cluster install and then RHEL scaleup using this change: worker nodes join cluster.
Remove double quotes in proxy config templates for compatibility with RHEL scaleup.

Bug 1745875: Change config templates for BYOH Proxy 

---

pkg/daemon/constants/constants.go
pkg/daemon/daemon.go

Backports https://github.com/openshift/machine-config-operator/pull/1086 to 4.1, since Kubelet CA rotation was backported to 4.1 (https://github.com/openshift/machine-config-operator/pull/1000).
```
NONE
```
/cc @runcom

[release-4.1] Bug 1749271: Backport mcd: Add /run/machine-config-daemon-force stampfile #1086

---

pkg/operator/operator.go
pkg/operator/status.go
pkg/operator/status_test.go
pkg/operator/sync.go

Closes: BZ 1741065
4.1.z backport of BZ 1741064 (GH https://github.com/openshift/machine-config-operator/pull/1064)
Makes syncAll fail fast like upstream
Add reason for degradation to ClusterOperatorStatusCondition
Updated unit tests
CI
pkg/operator: Report degraded reason in cluster operator status

[release 4.1] Bug 1741065: Report degraded reason in cluster operator status

---

templates/common/_base/files/cleanup-cni-conf.yaml

This is a WIP to look at addressing release blocker bz @ https://bugzilla.redhat.com/show_bug.cgi?id=1749448
*NOTE*: Originally submitted as a test. I am actively looking for feedback as to where this code to create a directory should exist. Originally, I simply found a convenient part to sketch it in (otherwise, I am somewhat unfamiliar with the MCO)

Bug 1749446: Creates alternative CNI configuration directory for the cluster network operator

---

templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

When using set -e "errexit" if a piped command fails it will immediately exit before further validation is done. This can result in the script failing without properly printing error message. This PR resolves this issue and standardizes the use of errexit.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1748081

Bug 1748081: DR: ensure piped commands exit 0

---

templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

We are still losing the err message in  `validate_etcd_name`..... this PR allows the script to prints the error message before exit.
```
[core@ip-10-0-141-100 ~]$ export INITIAL_CLUSTER="foo=bar"
[core@ip-10-0-141-100 ~]$ sudo /usr/local/bin/etcd-snapshot-restore.sh ./snapshot.db $INITIAL_CLUSTER
Downloading etcdctl binary..
etcdctl version: 3.3.10
API version: 3.3
etcd-member.yaml found in ./assets/backup/
checking against etcd-0.qe-geliu-0911.qe.devcluster.openshift.com
dns name is etcd-0.qe-geliu-0911.qe.devcluster.openshift.com
Validating INITIAL_CLUSTER failed: etcd-0.qe-geliu-0911.qe.devcluster.openshift.com is not found in foo=ba
```

Bug 1748081: DR: send error to stderr before exit for validate_etcd_name

---

templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml

Currently a lot of ci tests fail because of timeout in haproxy.
Increasing the timeouts in the config should make them less flaky.

OpenStack: increase haproxy timeouts

---

templates/master/00-master/_base/files/usr-local-bin-etcd-member-add-sh.yaml

Fixes: #1748798 
The current etcd-member-add.sh script wasn't backing up the client certificates, which are assumed to be available in the $ASSET_DIR/backup/ directory.
Added `backup_etcd_client_certs` to the script
1.) Create a new cluster
2.) remove a member using the etcd-member-remove.sh script.
3.) rm -rf assets
4.) add back the member using this script
5.) verify with etcdctl member list
Added backing up of client certs needed for etcd-member-add.sh.

Bug 1748798: Add backing up of client certs

---

templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml

This timeout delays when kubelet will send a sigkill to a process causing tests to timeout waiting for pods to be deleted. The delay for a SIGKILL is 10minutes+ when it should be much faster. The default will be around 2 minutes.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1752982
```
Remove runtimeRequestTimeout from Kubelet config to improve pod deletion times. This option is also used for Pod terminations.
```

Bug 1752982: kubelet: remove runtimeRequestTimeout

---

install/0000_80_machine-config-operator_00_namespace.yaml
manifests/openstack/coredns.yaml
manifests/openstack/keepalived.yaml
pkg/operator/assets/bindata.go
templates/common/openstack/files/openstack-NetworkManager-conf.yaml
templates/common/openstack/files/openstack-coredns.yaml
templates/common/openstack/files/openstack-keepalived.yaml
templates/common/openstack/files/openstack-mdns-publisher.yaml
templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
templates/master/00-master/openstack/files/openstack-haproxy.yaml

Currently infra pods are created in "openshift-kni-infra" namespace, which doesn't exist. It leads to various OOM errors and CI issues.
This patch creates the missing namespace "openshift-openstack-infra" and puts all the pods there, since "openshift-kni-infra" belongs to KNI team.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1753067

Bug 1753067: Create a namespace for OpenStack infra static pods

---

install/0000_80_machine-config-operator_00_namespace.yaml

Currently infra pods are created in "openshift-kni-infra" namespace, which doesn't exist. It leads to various OOM errors.
This patch creates the missing namespace "openshift-kni-infra".

Bug 1753411: manifests: Create namespace for static pods IPI-BM

---

templates/common/baremetal/files/baremetal-keepalived.yaml

When using CNV or other operators that modify how the node is connected
to the network, we may end up in the case where the configured VRRP
interface no longer has an address in the network that it is configured
to hold virtual IPs in.
This patch takes a page from what we do for HAProxy and adds a monitor
side car container that checks keepalived and reloads it when necessary.
Fixes: #1751978
Signed-off-by: Antoni Segura Puimedon <antoni@redhat.com>

Bug 1751978: templates/baremetal: Fix keepalived dysfunction on vrrp iface change

---

templates/master/00-master/openstack/files/openstack-haproxy.yaml

One of the consequences of making the static pods known to k8s in https://github.com/openshift/machine-config-operator/pull/1122 is that now the smoke test complain that some of the pods do not comply with the requirements.
By adding resources claim to the `haproxy` pod, we ensure it is not running with best-effort QoS.
This fixes the "[Feature:Platform][Smoke] Managed cluster should ensure control plane pods do not run in best-effort QoS [Suite:openshift/conformance/parallel]" failure in e2e-openstack job.

Bug 1753932: OpenStack: Ensure haproxy pod has the needed resources

---

manifests/openstack/coredns.yaml
manifests/openstack/keepalived.yaml
pkg/operator/assets/bindata.go
templates/common/openstack/files/openstack-coredns.yaml
templates/common/openstack/files/openstack-keepalived.yaml
templates/common/openstack/files/openstack-mdns-publisher.yaml
templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
templates/master/00-master/openstack/files/openstack-haproxy.yaml

#1122 breaks OpenStack CI, so we need to prepare the infrastructure first.
This patch temporarily puts all OpenStack infra pods to a non-existing namespace to make CI green.

Bug 1753953: Temporarily put OpenStack infra pods into non-existing namespace

---

manifests/machineconfigpool.crd.yaml
pkg/operator/assets/bindata.go

by adding new printer columns
Closes: #903
Add columns to the MachineConfigPool CRD manifest
to show machine counts for each pool in output of `oc get mcp`
`oc get mcp` shows MACHINECOUNT columns containing the number of machines in each pool
Add machine counts info on `oc get mcp` output

[4.3] manifests: Show machine counts in `oc get machineconfigpools` output

---

pkg/daemon/daemon.go

Saw this panic in a job:
```
I0911 12:04:57.511213   19608 update.go:984] initiating reboot: Node will reboot into config rendered-worker-01b1c0acbda55b81b7aa8bb9fb9a80d5
panic: close of closed channel
goroutine 85 [running]:
github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).InstallSignalHandler.func1(0xc00007bda0, 0xc00028d180, 0xc000098660)
/go/src/github.com/openshift/machine-config-operator/pkg/daemon/daemon.go:466 +0x13f
created by github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).InstallSignalHandler
/go/src/github.com/openshift/machine-config-operator/pkg/daemon/daemon.go:455 +0xbf
```
This patch fixes the above by returning as soon as we're signaled cause
the MCD is going to shut down anyway, and the node reboot anyway.
Signed-off-by: Antonio …

pkg/daemon: return from signal handler once signaled

---

pkg/controller/container-runtime-config/OWNERS
templates/master/01-master-container-runtime/OWNERS
templates/worker/01-worker-container-runtime/OWNERS

Code and templates is owned by the Node team (was Container Runtime team). Setup some OWNERS file
to make sure they're correctly assigned when something changes there.

ctrcfg: setup OWNERS for code and templates

---

templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml

`/run/etcd/environment` can contain ETCD_INITIAL_CLUSTER which would
override the value the user provided as an argument. This flow is
used during disaster recovery when only a single master remains and
the INITIAL_CLUSTER value needs to come from the user (the other
members are dead / gone).
This prevents performing a second recovery without editing the
`/run/etcd/environment`.

Bug 1755560: Ensure ETCD_INITIAL_CLUSTER is preserved during restore

---

pkg/daemon/daemon.go

Currently this check for journal is just executed in the case of RHEL (for 7.6) . But with CentOS we are in the same situation.
So the fix is as simple as to add the CentOS check to the conditional.
In order to verify it, i just added a CentOS worker. Before that, it was failing in MCP with that logger failure. With the patch, node reports fine.
Add check for logger in CentOS

pkg/daemon: add check for logger in CentOS

---

cmd/setup-etcd-environment/run_test.go

If the environment variables INITIAL_CLUSTER and INITIAL_CLUSTER_STATE are defined in the runtime environment file, then, setBookstrapEnv() should not include the conflicting DISCOVERY_SRV environment variable but instead copy the variables defining initial cluster as is. These initial cluster variables are defined and used during the disaster recovery (DR) cases.
These test cases test setBootstrapEnv() function for 4 scenarios.
1. Test no file
2. Test with INITIAL_CLUSTER and INITIAL_CLUSTER_STATE defined.
3. Test with DISCOVER_SRV in the file
4. Test with none of the variables defined.
Added unit tests for testing the new functionality for DR.
run `go test -v`
Unit tests for verifying the generation of runtime …

cmd: Unit test for setBootstrapEnv() method

---

machine-config-daemon.spec

RPM will happily package the symlink without its target, but
this leads to errors from rpmlint.

spec: Include doc/README.md directly

---

docs/Update-SSHKeys.md

Following https://bugzilla.redhat.com/show_bug.cgi?id=1744940 it's clear that we're missing on documentation about how to add ssh keys. Fix that.

docs: update SSH docs to add keys

---

pkg/operator/sync.go

Spotted in a BZ while looking around for something else. The mistake is
pretty obvious, we need to report the unavailable count but we
were reporting the available ones...

pkg/operator: fix DS unavailable count reporting

---

docs/custom-pools.md

Provide instructions to setup custom pools. This will be especially
useful for the new teams trying to integrate non-RHCOS machines within
the MCO pools (as we may want them to use a different pool rather than
worker directly).
cc @sdodson @ravisantoshgudimetla @aravindhp 

docs: add custom pools instructions

---

manifests/openstack/coredns.yaml
manifests/openstack/keepalived.yaml
pkg/operator/assets/bindata.go
templates/common/openstack/files/openstack-coredns.yaml
templates/common/openstack/files/openstack-keepalived.yaml
templates/common/openstack/files/openstack-mdns-publisher.yaml
templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
templates/master/00-master/openstack/files/openstack-haproxy.yaml

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1753067
This reverts commit ae890b7a4d363655d8c49ee375247079be9d5869.

Bug 1753067: Revert: "Temporarily put OpenStack infra pods into non-existing namespace"

---

pkg/daemon/daemon.go

Even if we document that the file needs to be removed it sounds like the
MCD should do it itself if the force validation file exists. The case
would be someone forgetting to remove the file causing validation to
always be skipped, even on upgrades.
cc @cgwalters @rphillips

pkg/daemon: remove force validation file if it exists

---

cmd/machine-config-daemon/start.go
pkg/daemon/rpm-ostree.go

We recently got reports of commands failing like these:
```
F0909 12:47:53.263253   11212 start.go:74] Binding pod mounts: exit status 32
```
```
F0909 13:00:30.298035   27120 start.go:107] Failed to initialize single run daemon: error reading osImageURL from rpm-ostree: exit status 1
```
This patch captures the command output as well to give further
information if available.
Also fixes 2 godoc issues that were bothering me.

pkg/daemon: provide cmd output when exec'ing fails

---

pkg/controller/common/controller_context.go
pkg/daemon/constants/constants.go

Add the `"openshift.io/operator-managed"` label from #832 to the MCD global constants file.
This way the operator managed label can be easily swapped out if the need arises (once #817 is merged the label will be used more than once, and it is an important label). 
I also cleaned up some small typos in the constants file.
CI

[4.3] pkg/daemon: MCD constants fixup

---

templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/master/01-master-kubelet/baremetal/units/kubelet.yaml

Fixes a warning when the kubelet starts by migrating the rotateCertificates to the config file on masters. Workers already get set via config file.
Kubelet will not warn with `Flag --rotate-certificates has been deprecated`.
```
NONE
```

migrate rotate certificates to the config

---

Makefile
hack/install-go-bindata.sh

Get rid of the build failures cause of go1.10 with golangci-lint seen in https://github.com/openshift/machine-config-operator/pull/1121 and https://github.com/openshift/machine-config-operator/pull/1119
requires https://github.com/openshift/release/pull/5162

Bug 1754924: Makefile: pin tools to specific versions

---

pkg/daemon/update.go

Changing the timeout to -1 ensures the library always honor the pod's
grace period and fixes a subtle issue with the "downloads" pod taking
600s to be evicted.

Bug 1745772: pkg/daemon: default drain grace period to -1

---

pkg/controller/template/test_data/templates/master/01-master-kubelet/aws/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/master/01-master-kubelet/libvirt/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/master/01-master-kubelet/none/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/master/01-master-kubelet/openstack/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/master/01-master-kubelet/vsphere/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/aws/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/libvirt/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/none/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/openstack/files/-etc-kubernetes-kubelet.conf
pkg/controller/template/test_data/templates/worker/01-worker-kubelet/vsphere/files/-etc-kubernetes-kubelet.conf
templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml

Backport: https://github.com/openshift/machine-config-operator/pull/1120
This timeout delays when kubelet will send a sigkill to a process causing tests to timeout waiting for pods to be deleted. The delay for a SIGKILL is 10minutes+ when it should be much faster. The default will be around 2 minutes.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1752982
```
Remove runtimeRequestTimeout from Kubelet config to improve pod deletion times. This option is also used for Pod terminations.
```

Bug 1753293: kubelet: remove runtimeRequestTimeout

---

lib/resourcemerge/machineconfig.go
pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/daemon/update.go
test/e2e/mcd_test.go

It's an acronym, so make it follow golang style:
https://github.com/golang/go/wiki/CodeReviewComments#initialisms

machineconfig: Capitalize FIPS fully

---

pkg/daemon/daemon.go
pkg/daemon/daemon_test.go
pkg/daemon/rpm-ostree.go

Today the RHCOS bootimages come "prepivoted"; they have a custom
origin set to the `machine-os-content` that matches.  The idea
here is to avoid an extra reboot.
In practice we're always going to be updating and rebooting today,
because we don't have a mechanism to update bootimages:
https://github.com/openshift/os/issues/381
I plan to change the RHCOS build system to stop "prepivoting"; the
oscontainer will be pushed *after* the bootimages.  This breaks
a complicated dependency and ensures that the RHCOS "source of truth"
is the cosa storage.
Also, this allows one to use the MCD when e.g. booting Fedora CoreOS.
Closes: https://github.com/openshift/machine-config-operator/issues/981

daemon: Support unpivoted images

---

docs/HACKING.md

Spent too long trying to figure this out today...
Removed old instructions for updating dependencies and added new ones reflecting new Makefile commands
These instructions should actually work now
Lmk if you'd like any changes @runcom just wanted to get the doc update started, so nobody else is as confused as me :laughing:

docs: update hacking.md to reflect switch to go mod

---

templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

remove_certs() function should be considered successful, if it cannot find old certificates to be removed. Currently, remove_certs() fails on pipefail when calculating the certificate file count.
4.3 recovery disruptive test should pass.
Fixes: 1758687

Bug 1758687: remove_certs should not fail, if the certificates are not found

---

manifests/openstack/coredns-corefile.tmpl
manifests/openstack/coredns.yaml
pkg/operator/assets/bindata.go
templates/common/openstack/files/openstack-coredns-corefile.yaml
templates/common/openstack/files/openstack-coredns.yaml

Port 8080 is used by cluster-network-operator in 4.3, so we can't deploy a cluster because of the conflict with coredns:
error listening on :8080: listen tcp :8080: bind: address already in use
This patch changes the coredns healthcheck port from 8080 to 18080 to resolve the conflict.

OpenStack: change coredns healthcheck port 8080->18080

---

cmd/machine-config-daemon/start.go
cmd/machine-config-operator/bootstrap.go
go.mod
install/0000_80_machine-config-operator_00_namespace.yaml
install/0000_80_machine-config-operator_02_images.configmap.yaml
install/0000_80_machine-config-operator_03_rbac.yaml
install/0000_90_machine-config-operator_00_servicemonitor.yaml
install/0001_00_machine-config-operator_00_service.yaml
install/image-references
manifests/machineconfigdaemon/clusterrole.yaml
manifests/machineconfigdaemon/clusterrolebinding.yaml
manifests/machineconfigdaemon/cookie-secret.yaml
manifests/machineconfigdaemon/daemonset.yaml
pkg/daemon/metrics.go
pkg/operator/assets/bindata.go
pkg/operator/images.go
pkg/operator/render.go
pkg/operator/sync.go
test/e2e/mcd_test.go
vendor/modules.txt

Add required components for the Prometheus operator to scrape MCD metrics via TLS. 
We can't serve Prometheus metrics via open `http` since the metrics we will be implementing will consist of data that should be restricted to cluster admins. To serve metrics via authenticated `https`, this PR adds an `oauth-proxy` container to the MCD daemonset. The MCD container then serves a metrics listener via `http` on `localhost`. The `oauth-proxy` forwards incoming secure (and authenticated) connections on port `9001` of the pod to the local metrics listener. This is how the [elastic search operator](https://github.com/openshift/elasticsearch-operator) handles secure metrics.
- Build MCO image and deploy.
- Verify that the MCD is visible in the cluster …

Telemetry: add prometheus service monitor and MCD metrics listener

---

pkg/controller/kubelet-config/errors.go
pkg/controller/kubelet-config/kubelet_config_controller.go

Backporting https://github.com/openshift/machine-config-operator/pull/1069 to 4.1. Old cache keys get requeued on failed kubelet decodes causing old KubeletConfigs to be re-injected.

Bug 1757209: Do not requeue a failed kubeletconfig decode

---

lib/resourcemerge/machineconfig.go

`ensureControllerConfigSpec` wasn't accounting for any change for the
Proxy field which lead to the `modified` bool not flipping to true when
the Proxy did change. That causes any edits in the Proxy object to not
trigger a resync because the new controllerconfig isn't updated with the
new proxy field. Fix all that by teaching `ensureControllerConfigSpec`
about Proxy field changes so the MCO _is_ resyncing once it changes.

Bug 1759363: lib/resourcemerge: account for proxy changes

---

pkg/controller/template/template_controller.go

There are two main reasons for this patch. The first one is obivious and
avoids spending time retemplating when there's no need since the
ControllerConfig's spec hasn't changed.
The second reason is king of tricky but what can happen is the
following:
0) between 4.1 and 4.2 MCO changed the etcd-member image name
placeholder from `setupEtcdEnv` to `setupEtcdEnvKey` (along with other
changes to image names)
1) when an upgrade from 4.1 starts the following happens:
a) the new MCO is rolled out
b) the new MCC is rolled out (note the template controller is also
rolled out here and can start before the new CC is rolled out with the
new image name placeholder!)
c) RACE! the template controller starts running before the new
ControllerConfig with the new image name placeholder is created
d) the …

pkg/controller/template: avoid resyncing templates if the cc didn't change

---

templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml

Increase the kubelet API QPS parameters to allow for more API transactions by the kubelet.
Inspect the kubelet.conf on workers and masters, and the kubelet logs to ensure that the parameters are set accordingly
Increase the kubelet API QPS parameters to allow for heavier load on nodes.

Increase KubeAPIQPS and KubeAPIBurst to 50/100 respectively

---

hack/build-go.sh

This is failing in Brew (rpm build) and reproducing that is annoying,
so let's have this print the env if it fails.

hack/build-go: Print `go env` if it doesn't give us what we want

---

cmd/machine-config-daemon/firstboot_complete_machineconfig.go
pkg/daemon/daemon.go
pkg/daemon/update.go
pkg/daemon/update_test.go
templates/common/_base/units/machine-config-daemon-firstboot.service

The saga of adding "firstboot MachineConfig" in
#798
is getting closer.  This is a small amount of code that builds on
a lot of prep work that landed to add a systemd service + entrypoint
in the MCD that reads the
`/etc/ignition-machine-config-encapsulated.json` file.  You
could think of this a lot like a variant of "once-from".
However, it doesn't run by default right now because the MCS still
serves `/etc/pivot/image-pullspec`, and this gives us a way to
"ratchet" the change as we need this new MCD code to land in RHCOS
before we can use it.

 daemon: Add a m-c-d-firstboot.service that handles encapsulated MC

---

machine-config-daemon.spec

Now that I look at the build log more closely, the error is obvious:
`$GOPATH/go.mod exists but should not`
Now that in 4.3 we use go modules, we don't need to mess around with
`GOPATH`. 🎊
Closes: https://github.com/openshift/machine-config-operator/issues/1185

spec: Remove GOPATH hacks

---

manifests/ovirt/coredns-corefile.tmpl
manifests/ovirt/coredns.yaml
manifests/ovirt/keepalived.conf.tmpl
manifests/ovirt/keepalived.yaml
pkg/controller/template/render.go
pkg/controller/template/test_data/controller_config_ovirt.yaml
pkg/operator/assets/bindata.go
pkg/operator/bootstrap.go
templates/common/ovirt/files/ovirt-NetworkManager-kni-conf.yaml
templates/common/ovirt/files/ovirt-coredns-corefile.yaml
templates/common/ovirt/files/ovirt-coredns-db.yaml
templates/common/ovirt/files/ovirt-coredns.yaml
templates/common/ovirt/files/ovirt-keepalived.yaml
templates/common/ovirt/files/ovirt-mdns-publisher.yaml
templates/master/00-master/ovirt/files/dhcp-dhclient-conf.yaml
templates/master/00-master/ovirt/files/ovirt-haproxy-haproxy.yaml
templates/master/00-master/ovirt/files/ovirt-haproxy.yaml
templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
templates/master/00-master/ovirt/files/ovirt-mdns-config.yaml
templates/worker/00-worker/ovirt/files/NetworkManager-non-virtual-ip-prepender.yaml
templates/worker/00-worker/ovirt/files/dhcp-dhclient-conf.yaml
templates/worker/00-worker/ovirt/files/ovirt-keepalived-keepalived.yaml
templates/worker/00-worker/ovirt/files/ovirt-mdns-config.yaml
templates/worker/00-worker/ovirt/files/ovirt-non-virtual-ip.yaml

Adding the files needed to make ovirt a provider of configs.
Fixes: #766
Added manifests and templates for ovirt platform. This is the same solution like `baremetal` uses for networking so the yamls are almost identical.
To test this I'm running `make update && make image` and pushing the container to quay.io. Then I modify my IPI installer to pull this image during bootstrap.
Related: openshift/enhancements#61
Adding the manifest, templates and controller handling for oVirt platform.

Add ovirt as a platform

---

machine-config-daemon.spec

With Go module switch, by default go build doesn't use vendor/
directory during. We need to explicitly set GOFLAGS with
-mod=vendor. This is required to build packages in build system
like brew/koji where external network download doesn't work
Support of using default vendored packages has landed recently
in Go https://github.com/golang/go/issues/33848, we might not
need this hack once Go 1.14 is out
Also update spec to recent MCO commit needed by MCD in 4.3

spec: Add -mod=vendor in GOFLAGS

---

pkg/daemon/daemon.go
pkg/daemon/update.go

Drain before applying manifests and writing files to avoid, mainly, new pods being scheduled before we reboot into the new configuration which might also lead to etcd-quorum-guard being fooled and cluster disruption.

Bug 1762536: pkg/daemon: drain before applying changes

---

pkg/controller/template/render.go
pkg/controller/template/template_controller.go

What #1177 had inadvertently regressed is that our MCs aren't rolled back anymore. This was sort of fine till the BZ came in, which exposed another bug we had. Basically, the code was adding duplicate and triplicates of common files all over. If you pair that with #1177, you'll get the bug in the title.

Bug 1762868: revert #1177 and fix common templates in MCs

---

install/0000_80_machine-config-operator_02_images.configmap.yaml
pkg/operator/images.go
pkg/operator/operator.go

Full context here https://docs.google.com/document/d/1mBDXujKsQjf0SSP9abLE_Mczvc8KE9D8qmeyoGdrD5Y/edit# (will make it public asap)
holding as it needs a proper bugzilla and whole process as well if this is accepted.
Signed-off-by: Antonio Murdaca runcom@linux.com

Bug 1763638: [release-4.1] pkg/operator: fix race between images CM and MCO

---

install/0000_80_machine-config-operator_02_images.configmap.yaml
pkg/operator/images.go
pkg/operator/sync.go

Full context here https://docs.google.com/document/d/1mBDXujKsQjf0SSP9abLE_Mczvc8KE9D8qmeyoGdrD5Y/edit# (will make it public asap)
holding as it needs a proper bugzilla and whole process as well if this is accepted.

Bug 1763636: [release-4.2] pkg/operator: fix race between images CM and MCO

---

install/0000_80_machine-config-operator_02_images.configmap.yaml
pkg/operator/images.go
pkg/operator/sync.go

Full context here https://docs.google.com/document/d/1mBDXujKsQjf0SSP9abLE_Mczvc8KE9D8qmeyoGdrD5Y/edit# (will make it public asap)
holding as it needs a proper bugzilla and whole process as well if this is accepted.
Signed-off-by: Antonio Murdaca runcom@linux.com

Bug 1763635: pkg/operator: fix race between images CM and MCO

---

cmd/setup-etcd-environment/run.go

I hit this log message when doing some IPv6 testing.  I found that it
would have been helpful to know the IP address it was checking.
There's a verbose message a few lines later that would print it, but
it won't be hit in this error scenario.

Include candidate IP in log message.

---

templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

This fixes a race when the kubelet enumerates the hostname at startup. Wait for the network-online.target to be ready before starting the Kubelet.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1763700

Bug 1763700: kubelet: add dependency on network-online.target

---

install/0000_80_machine-config-operator_00_namespace.yaml
manifests/ovirt/coredns.yaml
manifests/ovirt/keepalived.yaml
pkg/operator/assets/bindata.go
templates/common/ovirt/files/ovirt-coredns.yaml
templates/common/ovirt/files/ovirt-keepalived.yaml
templates/common/ovirt/files/ovirt-mdns-publisher.yaml
templates/master/00-master/ovirt/files/ovirt-haproxy.yaml

This commit creates new openshift-ovirt-infra namespace and moves there all ovirt infra pods from openshift-kni-infra

Create openshift-ovirt-infra namespace

---

Dockerfile
Makefile

This way we avoid hardcoding the architecture, which helps
multi-arch porting.  We also avoid enumerating the components
in `Dockerfile`.
For now, use a hack with `tar` - in the future we'll switch
to using globs once the api.ci cluster updates to 4.x.

build-sys: Add `make install`, use it in Dockerfile

---

Dockerfile.rhel7
Makefile

This finally merges all of the cleanups that went into our
main `Dockerfile` into the ART build, and should ensure the
two stay in sync from now on.

build-sys: Generate Dockerfile.rhel7 from Dockerfile

---

manifests/ovirt/coredns.yaml
manifests/ovirt/keepalived.yaml
pkg/operator/assets/bindata.go
templates/common/ovirt/files/ovirt-coredns.yaml
templates/common/ovirt/files/ovirt-keepalived.yaml
templates/common/ovirt/files/ovirt-mdns-publisher.yaml
templates/master/00-master/baremetal/files/baremetal-haproxy.yaml
templates/master/00-master/ovirt/files/ovirt-haproxy.yaml

Baremetal and ovirt should use there own app labels

Set correct labels to ovirt and kni infra pods

---

templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml

Explicitally give etcd-metrics container privilege, as it is trying to run /run/etc/environment on the host, but wasn't given permissions to do so

give etcd-metrics container privilege

---

templates/common/_base/units/machine-config-daemon-firstboot.service

During firstboot machine-config-daemon running on host will read
/etc/ignition-machine-config-encapsulated.json file available on
node, process it and applies MachineConfig provided like
kernelArguments

templates: Let m-c-d binary on host process encapsulated MC on firstboot

---

machine-config-daemon.spec

Blocks: https://github.com/openshift/release/pull/5659
Make `%global commit foo` overridable with `rpmbuild --define "commit bar"`
This should unblock the `build-rpms-from-tar` job over in https://github.com/openshift/release/pull/5659
Specfile: Make `%global commit ...` overridable

[fcos] Specfile: Make `%global commit ...` overridable

---

pkg/daemon/metrics.go

We only see successful logins, let's make that clear.
Also capitalize SSH since it's an acronym.

daemon: Tweak wording for SSH metric

---

templates/common/_base/units/machine-config-daemon-pull.service

This fixed mcd-pull service command, previous failed with `/usr/bin/cat: 
cannot execute binary file`

[fcos] mcd-pull: fix command to extract mcd on the hosts

---

templates/common/_base/units/machine-config-daemon-pull.service

Follow-up for #1228 - command needs to be wrapped in "sh" to do output redirection.
Seems we're gonna need `/override ci/prow/e2e-aws` here too as installer PR is not yet merged

[fcos] mcd-pull: sh is required for output redirection

---

docs/MachineConfigDaemon.md

minor update: explicitly add groups to excluded ign config chart and note we are using 2.2.0

docs: note groups unsupported

---

templates/common/_base/files/etc-pivot-kernel-args.yaml

This would disable cgroupsv2 and Spectre mitigations. These files are served by MCD to ensure correct initial hash on masters is being calculated

[fcos] templates: place /etc/pivot/kernel-args on masters/workers

---

Dockerfile
Dockerfile.rhel7
hack/build-go.sh

Fixes an issue with builds in ART as well, please look at individual commit messages.
cc @cgwalters

remove make binaries from Dockerfiles and use -mod=vendor when building

---

cmd/machine-config-operator/bootstrap.go
install/0000_80_machine-config-operator_02_images.configmap.yaml
pkg/controller/template/constants.go
pkg/controller/template/render.go
pkg/operator/bootstrap.go
pkg/operator/images.go
pkg/operator/sync.go
templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml

This PR adds a flag to bootstrap allowing the `cluster-etcd-operator` image to be be used in the etcd-member spec. We are also using the value of the flag as conditional logic for the spec. Because we need to balance that with what is put in etcd toggling CEO will involve unsetting the flag and the value of the configmap.
We also add a `readinessProbe` to etcd-member container. etcd should not show ready in service until it can serve traffic.

cmd/machine-config-operator/bootstrap: add cluster-etcd-operator flag

---

templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml

`/run/etcd/environment` can contain ETCD_INITIAL_CLUSTER which would override the value the user provided as an argument. This flow is used during disaster recovery when only a single master remains and the INITIAL_CLUSTER value needs to come from the user (the other members are dead / gone).  In the specific case, the recovery flow failed because we couldn't reestablish the master.
Backport #1133

Bug 1755557: Ensure ETCD_INITIAL_CLUSTER is preserved during restore

---

test/e2e/mcd_test.go

IIRC we did this just to speed up these tests because updating
workers 1 by 1 blew out our hour budget.
The router requires a minimum of two workers though, and we're just
going to be fighting its PDB.
Since customers can't sanely do this, let's stop doing it in our
tests.  If our tests take too long...we'll have to either cut
down the tests or make them a periodic, etc.

tests: Stop bumping worker maxUnavailable to 3

---

cmd/setup-etcd-environment/run.go
go.mod
go.sum
templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml
vendor/github.com/openshift/cluster-etcd-operator/LICENSE
vendor/github.com/openshift/cluster-etcd-operator/pkg/operator/api/scaling.go

The discovery init container is a very important part of the bootstraping process. Currently, we use SRV queries to populate ENV variables consumed by other containers in the pod.
As we move to an operator managed etcd cluster additional data points and validations need to be performed. The scaling of etcd is managed by the clustermembercontroller (CMC). When a new candidate for membership is verified as `Ready` to join the cluster the CMC populates a ConfigMap with basic information for the scaling process. This information includes details on the current members of the cluster. From this information, we can then populate the ETCD_INITIAL_CLUSTER variable which directs etcd on who its peers are.
To manage new candidates from racing only 1 member can scale at a time. Until that member has …

setup-etcd-environment: support scaling from cluster-etcd-operator

---

install/0000_90_machine-config-operator_01_prometheus-rules.yaml
pkg/daemon/update.go

added alerts for following metrics:
MCDRebootErr(critical), MCDDrainErr(critical),
MCDPivotErr(warning), KubeletHealthState(warning)

install/telemetry: add prometheus alerts

---

pkg/daemon/constants/constants.go
pkg/daemon/daemon.go

Rename rather than remove the encapsulated MachineConfig file after processing
on firstboot. This allows users to check what data was processed on the node
after the machineconfigdaemon-firstboot.service has run successfully.

daemon: leave backup copy of encapsulated machineconfig

---

pkg/daemon/update.go

Our new thought around this is that really FIPS should be a "day 1"
operation, and we don't want to make it really easy to undo.
See also https://github.com/openshift/installer/pull/2594
Anyone who wants to force this can change the MC flag, then
`oc debug node` and run the disable command by hand, then reboot.
Our MachineConfig merge semantics should make it hard for this
to happen unless the admin explicitly deletes the installer-generated MC,
but still.
Since we don't support it and don't want customers
to do it by accident, let's disable it and also stop wasting compute
hours testing it.

daemon: Refuse to disable FIPS mode

---

templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml

Update statistics url in Haproxy config to support both
IPv4 and IPv6 (single stack).

[Baremetal] - update haproxy statistics url

---

pkg/controller/node/status.go

We're seeing `OutOfDisk` in some recent runs and I'm wondering
whether it's `ConditionUnknown` appearing recently.  This should
help us find out.

controller: Log the exact status in conditions

---

Makefile
docs/HACKING.md

There's only one image now, so remove the `Makefile` bits
around multiple images.  Doing this since I typed `make images`
which failed, when I meant `make image`.

build-sys: Remove dead code in Makefile, fix HACKING.md typo

---

templates/common/_base/files/nm-ignore-sdn.yaml

The recent os bump includes the OVS plugin for NetworkManager, causing it to manage interfaces that were previously left unmanaged.
This functionality will be used, so we can't tell it to ignore all interfaces of type openvswitch. So, add the interfaces created by openshift-sdn and ovn-kubernetes to the Unmanaged list.

Bug 1766356: templates: tell NetworkManager to ignore interfaces

---

machine-config-daemon.spec

Backport of https://github.com/openshift/machine-config-operator/pull/1225
Blocks: https://github.com/openshift/release/pull/5572
Make `%global commit foo` overridable with `rpmbuild --define "commit bar"`
CI does not break
Specfile: Make `%global commit ...` overridable

Bug 1769578: Specfile: Make `%global commit ...` overridable

---

pkg/daemon/update.go

We no longer carry coreos-fips script in RHCOS, so that check fill
fail regardless. As a temporary fix, check state of node via
cat /proc/sys/crypto/fips_enabled instead.
Fixes: https://github.com/openshift/machine-config-operator/issues/1250

daemon/update.go: fix FIPS check and remove day 2 support

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

We have historically run into issues by the MCO setting more fields than it really needs to. Instead, we only really need to have the select fields MCO cares about, and comment out the rest.
Override the default values with the ones MCO set in the past, then comment out the rest
crio --config "" config > default.conf
crio --config $OLD_TEMPLATE config > mco.conf
sdiff default.conf mco.conf | grep '|'
and the resulting values are the only values uncommented here
Update crio.yaml templates to match CRI-O 1.16 config format as well as removed default values

Update and reduce templates for CRI-O 1.16

---

templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

Closes: #1766918
Added iteration counter to exit after 60 iterations.
Verify that there is timeout for exit to prevent the script going forever in dead loop
timeout verify_certs() to prevent script going forever in dead loop.

Bug 1766918: Exit the verify_certs loop after 60 iterations

---

manifests/openstack/coredns.yaml
manifests/openstack/keepalived.yaml
pkg/operator/assets/bindata.go
templates/common/openstack/files/openstack-coredns.yaml
templates/common/openstack/files/openstack-keepalived.yaml
templates/common/openstack/files/openstack-mdns-publisher.yaml
templates/master/00-master/openstack/files/openstack-haproxy.yaml

All infra pods have "requests" section with 1Gb of RAM and 150m of CPU, but they do not consume more than 200mb and 100m respectively.
This leads to irrational use of resources and prevents the launch of workloads on workers.
Fixes: bz1772440

Bug 1772440: OpenStack: decrease infra pods resource consumption

---

templates/master/00-master/_base/files/usr-local-share-openshift-recovery-template-etcd-generate-certs-yaml-template.yaml

This PR fixes DR scripts that were broken by recent changes to `setup-etcd-environment`.

templates/master/00-master: update recovery template to work with setup-etcd-environment

---

templates/master/00-master/_base/files/usr-local-bin-etcd-member-add-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-member-recover-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-member-remove-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

Closes: #1770269
Added etcdctl version in usr-local-bin-openshift-recovery-tools-sh.yaml
Verify that the DR scripts of release 4.3 use etcdctl of version v3.3.17
The DR scripts download the etcdctl on-demand, but the version was set in various scripts to an older version. This change sets the ETCD_VERSION in one place, and removes all the older versions from the other places.

Bug 1770269: DR: etcdctl version should match with what is shipped with product

---

docs/MachineConfiguration.md

Update kernelArguments section to include day 1 support in 4.3,
as well as adding an example snippet like the installer docs.

docs/MachineConfiguration: update kargs snippet

---

templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

Verify all containers are dead in stop_all_containers() function.
Fixes: #1770273 
Added a while loop to validate that all containers have stopped.
While running the DR function of restore.sh, verify that stop_all_containers function does indeed stop all containers.
Verify all containers are stopped in stop_all_containers() function.

Bug 1770273: Verify all containers are dead in stop_all_containers() function

---

machine-config-daemon.spec

Backport of https://github.com/openshift/machine-config-operator/pull/1225
Blocks: https://github.com/openshift/release/pull/5572
Make `%global commit foo` overridable with `rpmbuild --define "commit bar"`
CI does not break
Specfile: Make `%global commit ...` overridable

Bug 1769581: 4.2: Specfile: Make `%global commit ...` overridable

---

install/0000_80_machine-config-operator_04_deployment.yaml
install/0000_80_machine-config-operator_06_clusteroperator.yaml
install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml
install/0000_80_machine-config-operator_08_etcdquorumguard_pdb.yaml

Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252

Add manifest annotations for hosted deployment exclusions

---

templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1765759
Cherry-pick #1222 for 4.2

Bug 1765759: templates/*etcd-member.yaml: give etcd-metrics container privilege

---

pkg/controller/node/node_controller.go

if a node, for any reason, belongs to only a custom pool, do not enqueue
a nil worker mcp as it would panic when processed.

Bug 1775009: pkg/controller: do not enqueue a nil MCP

---

templates/master/00-master/openstack/files/openstack-haproxy.yaml

HAProxy container have "requests" section with 1Gb of RAM and 150m of CPU, but it does not consume more than 200mb and 100m respectively.
This leads to irrational use of resources.
All other infra containers by https://github.com/openshift/machine-config-operator/pull/1268

Bug 1772440: OpenStack: decrease haproxy container resource consumption

---

pkg/controller/template/render.go
pkg/controller/template/render_test.go

fix(pkg/controller/template/render): set vsphere as provider
Set cloudProvider to VSphere in the kubelet configs.
Fixes Bug 1777082: volume cannot mount to node after upgrade

Bug 1777082: set vsphere as provider

---

templates/common/_base/units/machine-config-daemon-pull.service

This removes condition to run this after first boot, cause some UPI 
installs may want to have other modification right after the 
first boot.
Required to make vSphere UPI tests pass, as these reboot machine to set static IP thus `ignition-firstboot-complete.service` is not active and MCD image cannot be pulled.

[FCOS] Pull MCD image and extract binary if it doesn't exists

---

pkg/daemon/pivot/types/imageinspection.go
pkg/daemon/rpm-ostree.go

If podman has a bug and cannot cleanup container names, we'll be stuck
in the update process as seen in
https://bugzilla.redhat.com/show_bug.cgi?id=1775647.
Randomize container names with UUID to avoid that and I think it's
generally better to do this w/o cleaning up at the beginning every time.
The linked bug won't be closed by this, just using it to attach to it so we can merge as part of that. The podman fix, if any, will close it.

Bug 1775647: pkg/daemon: randomize pivot container name

---

docs/README.md

Use absolute paths from the toplevel of the git repo instead of
relative paths because the README exists in the docs directory but
is symlinked from the toplevel of the repo.

docs/README: fix broken links

---

templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml

[Baremetal] Haproxy add support for IPv6 frontend

---

pkg/controller/kubelet-config/kubelet_config_controller.go

If the finalizer is already set, then we skip setting another finalizer.
Fixes an issue where Finalizers may be duplicated:
```
finalizers:
- 99-worker-935d0eac-d152-4f2a-a754-7f8086c591a1-kubelet
- 99-worker-935d0eac-d152-4f2a-a754-7f8086c591a1-kubelet
```
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1774369
```
NONE
```

Bug 1774369: skip setting the kubeletconfig finalizer if it is set

---

manifests/baremetal/coredns.yaml
manifests/baremetal/keepalived.yaml
pkg/operator/assets/bindata.go
templates/common/baremetal/files/baremetal-coredns.yaml
templates/common/baremetal/files/baremetal-keepalived.yaml
templates/common/baremetal/files/baremetal-mdns-publisher.yaml

All infra pods have "requests" section with 1Gb of RAM and 150m of CPU,
but they do not consume more than 200mb and 100m respectively.
This leads to irrational use of resources and prevents the launch of
workloads on workers.
Fixes Bug 1777837 : [IPI][Baremetal] Infra pods consume too much resources

Bug 1777837: BAREMETAL- decrease infra pods resources

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

In CRI-O we moved to not using implicit hooks dirs (https://github.com/cri-o/cri-o/pull/1943, https://github.com/cri-o/cri-o/pull/2731).
Unfortunately, we never set a default, until: https://github.com/cri-o/cri-o/pull/3011. The default isn't enough, though.
We also need /etc/containers/oci/hook.d because /usr is immutable, so a user can add hooks.

CRI-O: add old default hook directories

---

manifests/machineconfig.crd.yaml
manifests/machineconfigpool.crd.yaml
pkg/operator/assets/bindata.go

Display the age of MCO custom resources as a custom printer column. The "Age" column is standard across most kube api-resources and is useful for quick debugging purposes. Update MCO CRDs to be consistent with this.
- Rename "Created" printer column to "Age" in `MachineConfig` crd for consistency
- Add "Age" printer column to `MachineConfigPool` crd 
```sh
$ oc get machineconfigpools
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED
master   rendered-master-85f8a8bd448e5e02aa8464072ae232fb   True      False      False
worker   rendered-worker-d3f5e04eb265eeafa0b5091a06a368ed   True      False      False
$ oc get machineconfigs
NAME        GENERATEDBYCONTROLLER                      IGNITIONVERSION   CREATED
00-master …
```

Standardize printer column "Age" on mco CRDs.

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

In CRI-O we moved to not using implicit hooks dirs (https://github.com/cri-o/cri-o/pull/1943, https://github.com/cri-o/cri-o/pull/2731).
Unfortunately, we never set a default, until: https://github.com/cri-o/cri-o/pull/3011. The default isn't enough, though.
We also need /etc/containers/oci/hook.d because /usr is immutable, so a user can't add hooks.

Bug 1777838: [release-4.3] CRI-O: add old default hook directories

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

Upstream cri-o has moved to set the conmon-cgroup to system.slice
by default. But we want the conmon cgroup to be under the pod by
default in OpenShift. So explicitly setting it here in the MCO
templates for crio.conf

CRI-O: Set conmon_cgroup to "pod"

---

cmd/setup-etcd-environment/run.go
cmd/setup-etcd-environment/run_test.go

During the work before feature freeze, we introduced a regression in DR. The codebase had become a bit convoluted and hard to test. This PR introduces new unit tests that cover DR to prevent this from happening again. As we continue efforts with `cluster-etcd-operator` these e2e tests will be extended include that functionality.
The regression was reverted in 4.3 FTR [1]
[1] https://github.com/openshift/machine-config-operator/pull/1304

cmd/setup-etcd-environment: refactor and add tests

---

docs/FAQ.md

And can't easily be, so let's explain that.

docs/FAQ: The MCO isn't exclusive

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

For some reason its not available on masters/workers.
Not sure why this dir is not there, probably an older crio is being mixed in machine-os-content? 
UPD. this dir is provided by `oci-systemd-hook`, which no longer gets pulled in
Ref: https://github.com/openshift/machine-config-operator/pull/1305, https://github.com/openshift/openshift-ansible/pull/12047
/cc @LorbusChris @smarterclayton

[FCOS] templates: remove /usr/share/containers/oci/hooks.d from crio config

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

Removed /usr/share/containers/oci/hooks.d from CRI-O config. This folder is not available on RHEL7 hosts when CRI-O is being installed.
This dir is provided by `oci-systemd-hook` (if I understood correctly), however it is planned to be dropped during 4.3 lifecycle. This PR would ensure CRI-O is configured correctly in preparation to that
Run RHEL7 scaleup - it should pass
/usr/share/containers/oci/hooks.d is no longer being used as a source of CRI-O hooks.
/cc @mtnbikenc

templates: remove /usr/share/containers/oci/hooks.d from crio config

---

cmd/gcp-routes-controller/run.go

Closes: BZ 1769847
In BZ 1769847, it was observed that shutting down the GCP controller results in node failures. This change stops the host's routes service on signal.
<in progress>
Shutdown the GCP host route on OS Signal.

Bug 1769847: cmd/gcp-routes-controller: shutdown gcp routes on signal

---

pkg/controller/template/render.go

Having kubelet config or runtime MCs for custom pools isn't possible today.
The reason for that was to avoid risking drift between workers when it comes
to kubelet and runtime configs.
This patches changes that behavior by allowing custom pools to use the worker
base templates in order to generate MCs for kubelet and runtime configs.
Fixes https://github.com/openshift/machine-config-operator/issues/1156
@rphillips @umohnani8 ptal

Bug 1777150: pkg/controller: allow kubelet config and runtime changes for custom pools

---

templates/master/00-master/baremetal/files/baremetal-haproxy.yaml

Since HAProxy timeout values could be sensitive to some applications (e.g: Kuryr) we use long (24 hours) timeout values for the API LB. 
Because of these timeout values, sometimes old HAProxy processes being terminated only after 24Hours when HAProxy reload operation activated.
So, if HAProxy reload operation triggered many times in a short period we may end-up with many HAProxy processes hanging around (as it's described in Bug 1777204)
This change force sending SIGTERM after timeout (default is 120 seconds) to old HAProxy processes which haven't terminated.
Fixes Bug 1777204: Many haproxy processes hanging around due to monitor not closing connections

Bug 1777204: [Baremetal] verify that 'old' HAProxy processes being deleted after HAProxy reload.

---

go.sum

Re-run `make go-deps` with go 1.12 (that's what we're using in openshift 4.3)

vendor: run make go-deps

---

templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

Closes: #1783445
Backup should save static pod resources of kube-apiserver along with the snapshot of etcd database. Similarly, when a restore is invoked, it should restore the static pod resources along with the etcd database.
Follow DR documentation to back up and restore. The cluster should functional after the same backup is restored on all masters.
Save and restore kube apiserver's static pod resources along with etcd database.

DR: save and restore kube apiserver's static pod resources

---

templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

Closes: 1783448
Backup should save static pod resources of kube-apiserver along with the snapshot of etcd database. Similarly, when a restore is invoked, it should restore the static pod resources along with the etcd database.
Follow DR documentation to back up and restore. The cluster should functional after the same backup is restored on all masters.
Save and restore kube apiserver's static pod resources along with etcd database.

Bug 1783448: [release-4.3] DR: save and restore kube apiserver's static pod resources

---

cmd/setup-etcd-environment/run.go
pkg/controller/template/render.go
templates/common/_base/files/sysctl-forward-conf.yaml
templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml

I'm working on bringing OpenShift up with an IPv6 control plane.  With these changes, the etcd cluster forms and the bootstrap process continues.  There are still some suspicious messages in the etcd-member log, but this seems like a good start.
The changes should have no impact to other installs unless the etcd DNS records are created with IPv6 addresses instead of IPv4.  Otherwise, there should be no changes in the resulting behavior.
This is not intended to be complete IPv6 support, just a start.  There's an `IPV4_ADDRESS` variable I left unchanged to cut down on the size of the patch.  I also noticed similar issues still need to be fixed in the recovery tools.

etcd: Add initial support for an IPv6 control plane

---

manifests/ovirt/coredns.yaml
manifests/ovirt/keepalived.yaml
pkg/operator/assets/bindata.go
templates/common/ovirt/files/ovirt-coredns.yaml
templates/common/ovirt/files/ovirt-keepalived.yaml
templates/common/ovirt/files/ovirt-mdns-publisher.yaml
templates/master/00-master/ovirt/files/ovirt-haproxy.yaml

Set much lower resources request by the static coredns, mdns publisher, and keepalived.
Run IPI installation of oVirt, 3 master (all of them use those static pods)  and 2 workers (uses coredns, mdns publisher) see the install complete, cluster is fully operational, the static pods works with no hiccups.
Set much lower resources request by the static coredns, mdns publisher, and keepalived.
Those static pods requested way too much resources, adding pressure on the nodes and sometimes causing pods to be killed by the OOM manager.

ovirt: reduce static pods mem/cpu requirements

---

pkg/daemon/daemon.go
pkg/daemon/update.go

Bug 1763695: [release-4.2] pkg/daemon: drain before applying changes

---

templates/common/_base/files/cleanup-cni-conf.yaml

SDN IPs are leaked on reboots because the files are not being cleaned. This PR removes `/var/lib/cni/networks/openshift-sdn` deleting the IP config files.

Bug 1787581: cleanup sdn ips on reboot

---

templates/common/_base/files/cleanup-cni-conf.yaml

Cherry pick of https://github.com/openshift/machine-config-operator/pull/1360
> SDN IPs are leaked on reboots because the files are not being cleaned. This PR removes /var/lib/cni/networks/openshift-sdn deleting the IP config files.

[release-4.3] Bug 1787635: cleanup sdn ips on reboot

---

hack/build-go.sh

Should fix what we've seen in the ose builds:
...
hack/build-go.sh: line 32: exclude_graphdriver_devicemapper: command not found
...
Still not super sure about what's happening, might be GOFLAGS cluttering
go env and causing an unquoted string which is then eval'ed and errors
out.
Also, there's no reason about having that eval in there in the first
place. No git history shows why it's there as well so get rid of it.

hack/build-go.sh: removed not needed eval go env

---

pkg/daemon/update.go

Fixes bz#1785219 with the simplest approach.
Since this is a corner case [1] which probably few people will hit, this is the simplest approach to fix the issue, also it will be short-lived as RHEL7.7 comes with logger supporting --journald flag.
[1] RHEL7.6 + audit enabled + logger not supporting --journald flag

Bug 1785281: Discard audit messages from journald

---

Makefile
hack/build-go.sh

GOFLAGS env shouldn't be exported as it's meant for something else but we're using
it for "tags" - that's why the build fails on rhel (not sure why it started recently).
Tested in the golang-1.12 container and works fine, should further fix the ocp builds.
Reference to GOFLAGS env: https://tip.golang.org/cmd/go/#hdr-Environment_variables
```
GOFLAGS
A space-separated list of -flag=value settings to apply
to go commands by default, when the given flag is known by
the current command. Each entry must be a standalone flag.
Because the entries are space-separated, flag values must
not contain spaces. Flags listed on the command line
are applied after this list and therefore override it.
```
ref #1364 

build: do not export GOFLAGS

---

templates/master/00-master/openstack/files/openstack-haproxy.yaml

There seems to be some cases where HAProxy doesn't drain properly after HAProxy reload,
for that case we force sending SIGTERM after timeout (default is 120S) to old HAProxy
processes which haven't terminated.
This brings in https://github.com/openshift/machine-config-operator/pull/1274/ for OpenStack.
Co-Authored-By: Yossi Boaron <yboaron@redhat.com>

Bug 1771566: [OpenStack] verify that 'old' HAProxy processes being deleted after HAProxy reload

---

install/0000_80_machine-config-operator_05_osimageurl.yaml
pkg/operator/sync.go

same as #1357 but for 4.2 to test it in CI (4.2->4.2)

Bug 1789565: [release-4.2] Fix osImageURL upgrade race

---

templates/common/_base/units/machine-config-daemon-pull.service

Updated machine-config-daemon-pull.service so that it would be more resilent.
* Run the service only once network is up
* ~~Restart service on errors~~
systemd v243 doesn't support restarting oneshot services. This would need to be implemented once F31 is updated to v244+
* Pull MCD image explicitly so that an empty binary would not be created when image cannot be fetched
Fixes https://github.com/openshift/okd/issues/22
Fixes https://github.com/openshift/okd/issues/31

[FCOS] machine-config-daemon service improvements

---

templates/common/_base/files/cleanup-cni-conf.yaml

Cherry pick of https://github.com/openshift/machine-config-operator/pull/1360
> SDN IPs are leaked on reboots because the files are not being cleaned. This PR removes /var/lib/cni/networks/openshift-sdn deleting the IP config files.

Bug 1789248: cleanup sdn ips on reboot

---

pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/operator/render.go
pkg/operator/render_test.go
templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

In a single-stack IPv6 environment, update the `kubelet.config` to pass `--node-ip ::` to tell it to pick an IPv6 address rather than an IPv4 address for the node address. (Depends on https://github.com/openshift/origin/pull/24401 which is why this was not merged with the other IPv6 changes before (#1211).)
Specifically, this fixes the problem of trying to bring up a single-stack IPv6 cluster on a node that happens to have IPv4 addresses that you aren't using. (eg, this is necessary for testing single-stack IPv6 on AWS or Azure, since there is no way to bring up a node there there doesn't have an IPv4 address.) By default, if you don't specify an explicit `--node-ip`, and there are IPv4 node IPs addresses present, then kubelet will pick the node's default IPv4 address to …

Update kubelet.config for single-stack IPv6

---

templates/common/_base/units/machine-config-daemon-host.service

Today the MCS serves both `/etc/pivot/image-pullspec` *and*
`/etc/ignition-machine-config-encapsulated.json` - and we have
to serve both so that using 4.1 bootimages works.
However, we absolutely shouldn't start *both* services on a modern
4.3+ system on firstboot - they will race, both trying to update,
and one doing a reboot.
Only enable the `-firstboot.service` which will itself currently
invoke `-host.service`, though in the future we should clean this
up by having the firstboot code run rpm-ostree *directly*, since
we're already on the host.
Motivated by discussions around RT kernel handling.

 Don't enable machine-config-daemon-host.service by default

---

templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
templates/master/00-master/ovirt/files/ovirt-haproxy-haproxy.yaml

Have the bind to all interfaces statements listen to both IPv4 and IPv6 so it
works both on single and dual stack deployments.
Fixes: #1389

HAProxy infra pod: Make v4/v6 compatible

---

templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

Create an environment variable for the kubelet log level, so it can be overridden in /etc/kubernetes/kubelet-env across reboots.
```NONE```

Bug 1793144: kubelet: add log level environment variable

---

cmd/machine-config-operator/start.go
install/0000_80_machine-config-operator_02_images.configmap.yaml
install/image-references
manifests/machineconfigcontroller/clusterrole.yaml
pkg/controller/common/controller_context.go
pkg/operator/assets/bindata.go
pkg/operator/operator.go
pkg/operator/sync.go

[This](https://github.com/openshift/machine-config-operator/pull/1224) adds a flag to MCO for cluster-etcd-operator image and hardcodes
the value to `""`. 
This PR conditionally populates the cluster-etcd-operator image only
if the etcd custom resource exists and if it has a spec field set as
`managementState: Managed`. It is the same mechanism used 
in the [installer](https://github.com/openshift/installer/pull/2730). This will make sure that the MC rendered during the initial.
boot with the value coming in from the installer flag is always same
as one generate in the sync loop.
With this, we can use a single [knob](https://github.com/openshift/cluster-etcd-operator/blob/master/manifests/0000_12_etcd-operator_01_operator.cr.yaml#L8) in cluster-etcd-operator 
project to test the bootstrap …

*: conditionally populate the images configmap with cluster-etcd-operator image 

---

pkg/server/bootstrap_server.go
pkg/server/cluster_server.go
pkg/server/server.go

This patch injects the current machine config served by the MCS
into the ignition config to have it on disk for later comparisons.
This isn't making any difference between bootstrap and cluster
but I'm naming this commit with bootstrap as this will be
extremely helpful as a stopgap to investigate installer & MCO drifts.
By having the MC content on disk, if a drift happens, we can collect
the MC with must-gather and just compare it with what the MCO in the
cluster is generating.

pkg/server: save the bootstrap MC content

---

templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml

This PR adds an init container `waitforkube` if CEO is enabled.
Depends on https://github.com/openshift/cluster-etcd-operator/pull/46

templates: etcd-member: add waitforkube init container

---

lib/resourcemerge/machineconfig.go
manifests/machineconfig.crd.yaml
pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/common/helpers.go
pkg/controller/render/render_controller.go
pkg/daemon/update.go
pkg/operator/assets/bindata.go

By default we use traditional kernel on RHCOS system. With this,
one can create a MachineConfig specifying `kernelType: realtime` .
Once this MachineConfig is applied to OpenShift cluster,
targetted RHCOS node should switch to using realtime kernel.
Currently, realtime kernel packages are shipped as rpm files in
RHCOS OSContainer. MCO fetches those rpms from OSContainer and
uses rpm-ostree to layer realtime kernel on host.

Add kernelType to MachineConfig

---

hack/update-codegen.sh

Manual cherry-pick from the fix @sgreene570 added on the `fcos` branch.

Fix update codegen script to be compatible with go mod vendor

---

templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

In airgap and proxy scenario, we need a simple way for allowing an alternative method of obtaining etcd client binary. In the future, this method could be considered the default. But for now we are allowing user to provide the binary in advance of running the script. This process would be part of the documentation as phase 1.
We also do not want old versions of the binary to be used so we added a version check.
This PR needs manual test/verification

Bug 1780442: DR: allow use of local etcdctl plus version check

---

templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

Backup should save static pod resources of kube-apiserver separate from the snapshot of etcd database. When etcd is encrypted, it is important to keep the data and keys separatedly for security. 
Similarly, restore can be invoked on a backup directory containing files for the static pod resources along with the etcd database.
Follow DR documentation to back up and restore. The cluster should functional after the same backup is restored on all masters.
Save and restore kube apiserver's static pod resources separatedly from the etcd database.

DR: Backup should keep data and keys separate

---

pkg/daemon/node.go
pkg/daemon/writer.go

Fixes issue where an "annotation not found" error compounds via wrapping the node in the error message, growing the `machineconfiguration.openshift.io/reason` annotation until it hits the annotation max size limit, thereby preventing updates to that node's annotations by controllers.
- Remove node object from  "annotation not found" error and replace with just node name
- Truncate errors used in `machineconfiguration.openshift.io/reason` node annotation to prevent any that may contain large amounts of data from maxing out annotation size.
- Stop MCO and MCC controllers
- Delete the `machineconfiguration.openshift.io/desiredConfig` annotation on a node and wait for the MCD to sync the update
- Check the node object for the …

Bug 1792914: prevent hitting annotation max size limit on nodes

---

templates/common/baremetal/files/baremetal-mdns-publisher.yaml

This change verifies that mdns-publisher pod advertises node's
name only after hostname being set.

Bug 1790823: [IPI][BAREMETAL] Verify that mdns-publisher starts after hostname is set

---

cmd/machine-config-operator/bootstrap.go
lib/resourcemerge/machineconfig.go
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go
pkg/operator/bootstrap.go
pkg/operator/sync.go
templates/common/_base/files/cloud-provider-ca.yaml

**- What I did** Add support for Ca certs being added to the cloud-provider-config configmap, and writing those certs to where kubelet will know to look for them. This is associated with https://github.com/openshift/installer/pull/2932/files, and is part of a greater scheme to add support for self signed platform (openstack) CA certificates outlined here: https://docs.google.com/document/d/1bKXArO_dtIOQMVqV35GTmUdzoRQAgUqIVMbO9kpfknI/edit?folder=0AFMASrm3oxfNUk9PVA#heading=h.9jxn8ewfjnas
**- How to verify it** For all platforms excluding openstack, this should have no affect on the way the MCO runs. This should be verifiable by the MCO being able to pass its normal unit and e2e test suite. For openstack, this is being tested in a specialized cluster in combination with a number of other …

OpenStack: Add ca cert to disk on all nodes so kubelet can start up

---

templates/common/baremetal/files/baremetal-NetworkManager-kni-conf.yaml

Adding ipv6.dhcp-duid=ll means we get a predictable
client ID so that reservations can be made on the
DHCP server - this is useful if you want to provide
the hostname via DHCP (although a reverse DNS lookup
should also work)
Reservations are also required to ensure the controlplane
IP of the masters won't ever change post-deployment
which will be necessary if the DNS lookup approach
is taken to set the hostnames.
Updated the NetworkManager configuration, only for the baremetal (IPI) platform, so we specify the ipv6.dhcp-duid=ll option.  This enables a predictable (mac derived) client ID/DUID when deploying in an IPv6 environment.
If testing with dev-scripts you can check via `virsh net-dhcp-leases baremetal` - on baremetal you can check the client …

baremetal: IPv6 add dhcp-duid to NetworkManager config

---

cmd/setup-etcd-environment/run.go

Upgrades from a 4.3 cluster to a cluster-etcd-operator enabled
cluster discovery fails because the expected operator environment
is not being populated. The `isScaling` function was passing in normal
scale-up but not in an upgrade, where etcd pods already exist with the
directory and we cannot afford to delete the etcd data directory.
This is a temporary solution until we find a better way of differentiating 
between scale-up and upgrade.
More context [here](https://github.com/openshift/cluster-etcd-operator/pull/51#issuecomment-566886783)
- Install a 4.4 cluster from CI for example, registry.svc.ci.openshift.org/ocp/release:4.4-ci
- Upgrade to a cluster-etcd-operator enabled cluster
fixes upgrades to cluster-etcd-operator enabled …

setup-etcd-environment/run.go: fix upgrade path

---

install/0000_80_machine-config-operator_00_namespace.yaml
manifests/vsphere/coredns-corefile.tmpl
manifests/vsphere/coredns.yaml
manifests/vsphere/keepalived.conf.tmpl
manifests/vsphere/keepalived.yaml
pkg/controller/template/test_data/controller_config_vsphere.yaml
pkg/operator/assets/bindata.go
pkg/operator/bootstrap.go
templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
templates/common/vsphere/files/vsphere-coredns-corefile.yaml
templates/common/vsphere/files/vsphere-coredns-db.yaml
templates/common/vsphere/files/vsphere-coredns.yaml
templates/common/vsphere/files/vsphere-keepalived.yaml
templates/common/vsphere/files/vsphere-mdns-publisher.yaml
templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
templates/worker/00-worker/vsphere/files/vsphere-mdns-config.yaml
templates/worker/00-worker/vsphere/files/vsphere-non-virtual-ip.yaml

Uses existing baremetal networking like openstack and ovirt.
- Added manifests and template for vSphere which identical
beyond names as ovirt (cp and sed).
- Updated bindata as required
- Update pkg/operator/bootstrap for vsphere
Requires: https://github.com/openshift/api/pull/541

Add vSphere IPI

---

cmd/machine-config-operator/start.go
cmd/setup-etcd-environment/run.go
install/0000_80_machine-config-operator_02_images.configmap.yaml
install/image-references
manifests/machineconfigcontroller/clusterrole.yaml
pkg/controller/common/controller_context.go
pkg/operator/assets/bindata.go
pkg/operator/operator.go
pkg/operator/sync.go
templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml

Cherrypick of https://github.com/openshift/machine-config-operator/pull/1288, https://github.com/openshift/machine-config-operator/pull/1408 and https://github.com/openshift/machine-config-operator/pull/1316 on fcos branch

[fcos] Cherry-pick commits to enable cluster-etcd-operator

---

templates/worker/00-worker/baremetal/files/dhcp-dhclient-conf.yaml

This appears to get written out as /etc/dhcp/dhclient.conf.template
with no subsequent render-config templating to create the actual
/etc/dhcp/dhclient.conf - modifying the path results in the file
being correctly written.

Bug 1796148:  baremetal: Remove .template from path in dhcp-dhclient-conf.yaml

---

pkg/server/bootstrap_server.go
pkg/server/server_test.go
pkg/server/testdata/machine-pools/master.yaml

The new cluster etcd operator flow is:
1) start bootstrap mcs
2) start etcd on bootstrap
3) wait for bootstrapping to finish i.e. atleast one control-plane is ready and there is MCS running on cluster
4) turn down bootstrap mcs
What the above does is giving a chance to workers to grab
the ignition config from the bootstap server which now stays up longer.
However, by the time they attempt to create a CSR the kube-apiserver has
rotated that bootstrap chain of trust out which causes the workers to error out with:
Jan 29 19:55:20 ip-10-0-130-205 hyperkube[2623]: E0129 19:55:20.869251    2623 certificate_manager.go:421] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Unauthorized
The above results in workers not being able to join the …

Bug 1796147: pkg/server: serve config only to master in bootstrap server

---

templates/master/00-master/gcp/files/etc-kubernetes-manifests-gcp-routes-controller.yaml

This PR is related to this conversation https://github.com/openshift/machine-config-operator/pull/1031#discussion_r371965677
@sttts suggested to use `readyz` instead of the `healthz` endpoint.
I've just edited the template instead of changing the whole command line flag for the binary itself (cc @abhinavdahiya)
I suspect this needs a BZ and backports, holding for the moment till we figure it out (I can also go ahead and create BZs as needed)

Bug 1796444: gcp: use readyz endpoint

---

templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

For non-x86 architectures there is no etcdctl binary available for the upstream releases of etcd. The suggestion from @cgwalters was to get the binary from the image(https://bugzilla.redhat.com/show_bug.cgi?id=1780396#c4)
which makes sense.
Verified by making the changes on an s390x system and executing the snapshot backup script.

Bug 1780396: Get etcdctl binary from the etcd image and not from the upstream releases

---

templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-backup-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-etcd-snapshot-restore-sh.yaml
templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

Closes: #1796440
Manually cherry picked changes to keep data and keys separate for snapshot backup and restore scripts.
1. Take snapshot backup using the DR script.
2. Verify that it produces two files: one containing static pod resources and another snapshot db.
3. Restore the snapshot following the documentation, and verify that etcd comes up and healthy.
Keep etcd keys and data separate for enhanced security.

Bug 1796440: [release-4.3] DR: Cherry-pick  keep keys and data separate for snapshot backup

---

templates/master/00-master/baremetal/files/baremetal-haproxy-haproxy.yaml
templates/master/00-master/openstack/files/openstack-haproxy-haproxy.yaml
templates/master/00-master/ovirt/files/ovirt-haproxy-haproxy.yaml

Have the bind to all interfaces statements listen to both IPv4 and IPv6 so it
works both on single and dual stack deployments.
Relates: #1389 
Backport of: https://github.com/openshift/machine-config-operator/pull/1394

Bug 1793253: [release-4.3] HAProxy infra pod: Make v4/v6 compatible

---

pkg/operator/bootstrap.go
templates/common/vsphere/files/vsphere-NetworkManager-kni-conf.yaml
templates/common/vsphere/files/vsphere-coredns-corefile.yaml
templates/common/vsphere/files/vsphere-coredns-db.yaml
templates/common/vsphere/files/vsphere-coredns.yaml
templates/common/vsphere/files/vsphere-keepalived.yaml
templates/common/vsphere/files/vsphere-mdns-publisher.yaml
templates/master/00-master/vsphere/files/dhcp-dhclient-conf.yaml
templates/master/00-master/vsphere/files/vsphere-haproxy-haproxy.yaml
templates/master/00-master/vsphere/files/vsphere-haproxy.yaml
templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
templates/master/00-master/vsphere/files/vsphere-mdns-config.yaml
templates/worker/00-worker/vsphere/files/dhcp-dhclient-conf.yaml
templates/worker/00-worker/vsphere/files/vsphere-keepalived-keepalived.yaml
templates/worker/00-worker/vsphere/files/vsphere-mdns-config.yaml
templates/worker/00-worker/vsphere/files/vsphere-non-virtual-ip.yaml

When installing onto vSphere UPI MCC fails templating the in-service networking
components because there is no vSphere platformstatus.
Add check to each template.
If vSphere platform status does not exist create empty files
Tested with both vSphere IPI and UPI.

Bug 1794824: If PlatformStatus.VSphere is nil do not template the file

---

templates/worker/00-worker/baremetal/files/baremetal-non-virtual-ip.yaml

Closes: #1420 
Make non_virtual_ip IPv6 compatible by checking the IPv6 route advertisements to complement the check for whether an address in in the VIPs subnet.
Deploy OpenShift Baremetal on IPv6 with addresses provided by a DHCPv6 with Route Advertisement enabled and check that /etc/resolv.conf gets the right non VIP IPv6 address.

Bug 1798146: [baremetal] Ipv6 non virtual ip fix

---

templates/master/01-master-kubelet/_base/units/kubelet.yaml
templates/worker/01-worker-kubelet/_base/units/kubelet.yaml

Removed quotes around the KUBELET_LOG_LEVEL variable in the kubelet unit file.
Resolves the following error message produced in kubelet log on RHEL host:
```
hyperkube[66517]: F0204 19:10:58.178624   66517 server.go:156] invalid argument "\"3\"" for "-v, --v" flag: strconv.ParseInt: parsing "\"3\"": invalid syntax
```

Bug 1797908: kubelet: Remove quotes from log level argument

---

templates/common/gcp/files/gcp-routes-sh.yaml
templates/common/gcp/units/gcp-routes-service.yaml

This would ensure masters / workers would report as healthy to GCP LBs
xref https://github.com/openshift/okd/issues/38

[fcos] GCP: add a script and a service which ensure GCP routes are set correctly

---

templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml

Closes: #1795696
One can easily update .bashrc or .bash_profile using postStart hooks. However, `oc rsh` apparently doesn't use bash, so these are not getting automatically invoked.
https://github.com/openshift/origin/issues/7514
https://github.com/openshift/origin/issues/7496 
https://github.com/openshift/origin/pull/7519
However, standard shell (Bourne shell) uses .profile. But in RHCOS, /bin/sh is symbolically linked to /usr/bin/bash. 
> If bash is invoked with the name sh, it tries to mimic the startup behavior of historical versions of sh as closely as possible, while conforming to the POSIX standard as well. [...] When invoked as an interactive shell with the name sh, bash looks for the variable ENV, expands its value if it is defined, and uses the expanded value as the name of a …

Bug 1795696: templates: etcd-member: setup environment variables needed for easy etcdctl execution

---

templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml

bumps `systemReserved`. Fixes an issue where the kubelet and node could become starved causing the node to hang.
[upstream doc](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#kube-reserved)
[BZ1800319](https://bugzilla.redhat.com/show_bug.cgi?id=1800319)
The BZ has an attached test case.
```NONE```
/cc @smarterclayton @sjenning @mrunalp

Bug 1800319: kubelet: add kube reservation for kubernetes components

---

templates/master/01-master-kubelet/OWNERS
templates/worker/01-worker-kubelet/OWNERS

Add an owners file to master and worker kubelet templates.

Bug 1801466: add owners files to master and worker kubelet templates

---

docs/FAQ.md

Package layering came up in a Slack conversation.

FAQ: More about preservation of changes and the MCO

---

templates/master/00-master/_base/files/etc-kubernetes-manifests-etcd-member.yaml

In some circumstances such as lights out where all nodes are shutdown `wait-for-kube` init would fail as kube would never be available before etcd. Also the membership init container will attempt to validate etcd membership but that is not possible when etcd is not running...
This PR adds the ability to fall through these checks by validating the existence of an etcd data file.
the full solution requires [1]s but does not block this PR.
[1] https://github.com/openshift/cluster-etcd-operator/pull/73

Bug 1797897: etcd-member: do not wait-for-kube or validate membership for existing members

---

templates/master/00-master/_base/files/usr-local-bin-openshift-recovery-tools-sh.yaml

A backport of PR #1422. Could not do an automatic cherry pick because of some differences.

Bug 1797035: Get etcdctl binary from the etcd image and not from the upstream releases

---

pkg/controller/kubelet-config/kubelet_config_controller.go

Followup to https://github.com/openshift/machine-config-operator/pull/1356 [use the machine config uid for the kubeletconfig finalizer name]
mc.GetUID() is initialized to an empty string, and while the kubeletconfig does get installed, the finalizer does not get set because empty strings are invalid. This patch initializes the ObjectMeta.UID field, and switches over to use ObjectMeta.Finalizers.

Bug 1787907: kubelet: switch to ObjectMeta.UID and initialize UUID

---

templates/common/baremetal/files/NetworkManager-mdns-hostname.yaml
templates/common/baremetal/files/baremetal-mdns-publisher.yaml

MDNS publisher static pod should start advertising the node
only after node's hostname was set by DHCP.
The idea is to add an init container that will monitor host's hostname
until hostname != localhost.
The issue was how host's hostname should be retrieved by the init container.
Since the MDNS static pod doesn't use host's uts namespace, reading 'hostname'
is not an option.
Reading hostname using dbus didn't work due to security constraints(SElinux).
The suggested solution composed of:
1. NM dispatcher script will monitor & store hostname in a file
2. Init container will mount this file, and read the value
This PR is instead of https://github.com/openshift/machine-config-operator/pull/1446

Bug 1790823: [baremetal] Verify that MDNS doesn't advertise localhost

---

templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml

We are seeing some instances where openshift components do not fit on the nodes anymore. Retune the CPU limit to the original.

Bug 1800319: kubelet: bump CPU reservation back to 500m

---

pkg/operator/sync.go

per our discussion in slack, we need this PR to skip setting degraded on machineconfigoperator when the pools are bad so that we can land https://github.com/openshift/cluster-etcd-operator/pull/142 and https://github.com/openshift/machine-config-operator/pull/1465.  After that, we will no longer go degraded in 4.4.
You can see an example of the condition here: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-etcd-operator/112/pull-ci-openshift-cluster-etcd-operator-master-e2e-aws/597 .  The MCO is completely correct to set it, but we need to break the stalemate.

bug 1801397: temporarily skip setting failures on degraded machine config pool

---

docs/custom-pools.md

This should help users to not try adding custom pool on master
nodes and wonder why it is not getting applied.

Bug 1797687: docs: Document that MCO doesn't apply custom pool on master node

---

install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml

paired with https://github.com/openshift/cluster-etcd-operator/pull/162 to make sure the quorum guard can read the correct files off disk.  We would pick this back to 4.3
/cherrypick release-4.3

make etcd quorum guard privileged to read files from etcd operator

---

pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/controller/template/render.go
pkg/controller/template/render_test.go
test/e2e/mcd_test.go
test/e2e/utils_test.go

Other operators may need to use the MCO and hence they need to know this constant. Keeping this constant on a single place may turn out to be advantageous to the whole OpenShift ecosystem.
https://bugzilla.redhat.com/show_bug.cgi?id=1797559
Closes #1797559

Provide RoleLabelKey as const to be re-used by other operators

---

pkg/daemon/update.go

Added nil checks for Ignition v3 options
Run cluster update where unit contents or mask setting is unset
Make sure daemon doesn't panic when mask or contents is nil
Fixes #1378
/cc @LorbusChris @sgreene570

[FCOS] pkg/daemon/update.go: check for nil pointers

---

templates/master/00-master/baremetal/files/NetworkManager-resolv-prepender.yaml
templates/worker/00-worker/baremetal/files/NetworkManager-resolv-prepender.yaml

NetworkManager doesn't always set the hostname when DHCP6 is involved.
This sets the hostname when $DHCP6_FQDN_FQDN is populated and does not
equal localhost.localdomain. This is a workaround while we try to figure
out why NetworkManager is not setting the hostname as it should.

Bug 1806001: [baremetal] Set hostname when DHCP6_FQDN_FQDN is set

---

pkg/controller/container-runtime-config/container_runtime_config_controller.go

Do not compare pointer and struct as that always yields false and forces
the controller to update the MC and spam the logs every ~20m.

CRC: compare the correct object

---

templates/common/baremetal/files/etc-systemd-system-crio-stream-address.conf.yaml

The original fix in 065082e25b5260001d724d34eee9d307c0c3e92c missed the
systemd service ExecStart override that uses the environment variable
set in /etc/systemd/system/crio.service.d

CRI-O to set stream address in ctrl plane

---

templates/common/baremetal/files/baremetal-coredns.yaml

When /etc/resolv.conf file is modified, the forward section of
Coredns Corefile should be updated.
This patch adds sidecar container (similar to HAProxy and Keepalived) that
checks resolv.conf file and updates Coredns Corefile.
This PR should be merged only after https://github.com/openshift/baremetal-runtimecfg/pull/49 is merged.

1790819: [baremetal] Add watcher sidecar container for Coredns static pod

---

manifests/kubeletconfig.crd.yaml
pkg/operator/assets/bindata.go

The kubelet config is now validated, but fields are being silently
dropped since its an "unknown field" (rawExtension), which by
default is pruned by the validator.
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>

Bug 1809274: crd/kubelet: do not prune kubelet rawExtension fields

---

templates/common/baremetal/files/baremetal-mdns-publisher.yaml

On some environments, `hostname` returns localhost whereas on others it
returns `localhost.localdomain`. This commit ensures that we'll catch
both.
It also increases verbosity of initcontainers to ease debugging of
similar issues in the future.

Bug 1810333: Detect default hostname in its variants

---

pkg/daemon/update.go

When we go to write a file, we need to create the temporary
file in the exact target directory, not (potentially) `/tmp`. This will
ensure that the right SELinux label is used by default.
Currently the `renameio` library's logic tries to optimize things
by using `/tmp` if possible, otherwise the target directory.
And without SELinux that's a sane optimization.  But we
can't do it.
Force using the target directory by passing it explicitly.
Should fix a bug seen with the baremetal config which
ended up with a `tmp_t` labeled file in `/etc`.

Bug 1810333: daemon: Always create tempfiles in target dir

---

manifests/baremetal/coredns-corefile.tmpl
pkg/operator/assets/bindata.go
templates/common/baremetal/files/baremetal-coredns-corefile.yaml

In order to facilitate deployments where the external DNS records do
not exist yet, add them to our coredns configuration so that the
deployment can be done in a completely self-contained manner.
Note that the external DNS entries will still need to be added for
production use of the cluster, but this lowers the barrier to entry
for PoC and initial deployments.
Because the hosts plugin does not support wildcard entries, the
template plugin is used for the ingress record instead.

baremetal: Add external DNS entries to coredns

---

templates/master/00-master/baremetal/files/baremetal-mdns-config.yaml

Our current method of mapping master hostnames to etcd-[0,1,2] records introduces undesirable restrictions on the names of master nodes. Now that cluster-etcd-operator allows us to bootstrap the etcd cluster using the SRV record, we can just point it at the masters directly and drop the extra etcd-specific record. This should eliminate the hostname requirements entirely.
This will need to wait for https://github.com/openshift/coredns-mdns/pull/52 to merge since that is forcing use of the etcd record.

Bug 1804944: Point etcd SRV record at master hostnames

---

templates/master/00-master/azure/files/etc-etcd-etcd-conf.yaml

The reason for this change is that currently, Azure disk performance does not allow for the throughput provided by default raft settings. Under heavier, disk I/O Azure will throttle disks causing massive spikes in I/O 600ms+. By reducing the throughput ETCD_HEARTBEAT_INTERVAL and also extending the timeout for etcd elections ETCD_ELECTION_TIMEOUT we can improve stability in slower disks by reducing leader elections.

[release-4.3] Bug 1807279: templates/master/00-master/azure: bump raft tunables

---

manifests/openstack/coredns-corefile.tmpl
pkg/operator/assets/bindata.go
templates/common/openstack/files/openstack-coredns-corefile.yaml

The default policy for CoreDNS forward plugin being random [1], the
cluster may not be able to resolve the OpenStack API hostname when the
user sets multiple external DNS resolvers such as
['172.31.8.1','8.8.8.8'], where 172.31.8.1 knows to resolve internal
hostnames and 8.8.8.8 is a public resolver that doesn't know how to
resolve internal hostnames.
Switch to the sequencial policy to simulate the libc behavior and not
surprise users who expect the DNS servers specified via `externalDNS`
option to have a hierarchy.
[1] https://coredns.io/plugins/forward/

Bug 1809611: OpenStack: Set coredns forward policy to sequencial

---

pkg/daemon/update.go

Fixes bz#1785279 with the simplest approach.
Since this is a corner case [1] which probably few people will hit, this is the simplest approach to fix the issue.
[1] RHEL7.6 + audit enabled + logger not supporting --journald flag

Bug 1785279: [release-4.3] Discard audit messages from journald

---

templates/common/baremetal/files/baremetal-keepalived.yaml

All static pods containers resources should be set to (cpu: 100m and memory: 200Mi), this change updates keepalived-monitor resources to these values.

[baremetal] Decrease resources of keepalived monitor container

---

templates/master/01-master-kubelet/_base/files/kubelet.yaml
templates/worker/01-worker-kubelet/_base/files/kubelet.yaml

Specifying `runtimeCgroups` will cause the Kubelet to monitor statistics for the specified cgroup so that we have statistics for crio.
Specifying `systemCgroups` will cause the Kubelet to monitor
statistics for system processes and make that data available
in our metrics pipeline.
Specifying `cgroupRoot` explicitly is required when specifying
`systemCgroups`
Added cgroup parameters so that the eventual
`/etc/kubernetes/kubelet.conf` will be configured for the kubelet
to monitor cgroup statistics for the crio runtime and other system
processes.
```
oc get --raw /api/v1/nodes/node-name-of-one-of-your-nodes/proxy/metrics/cadvisor | grep crio\\.service
```
Before this change, no metrics will be returned, and after, you should see several metrics …

Bug 1806027: Specify cgroups in kubelet.conf so cAdvisor stats will be tracked

---

templates/master/01-master-kubelet/baremetal/units/kubelet.yaml

This was added in #1206 to the base unit, but not the baremetal
copy of this file
Added a dependency on the network-online target for the baremetal copy of the kubelet unit file.
Verify the unit file on a IPI baremetal deployment or via `systemctl list-dependencies`
Added missing dependency for kubelet on the network-online target, for the baremetal platform.

Bug 1811758 :  baremetal: Add missing network-online dependency to kubelet unit

---

templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
templates/master/00-master/openstack/files/openstack-keepalived-keepalived.yaml
templates/master/00-master/ovirt/files/ovirt-keepalived-keepalived.yaml
templates/worker/00-worker/baremetal/files/baremetal-keepalived-keepalived.yaml
templates/worker/00-worker/openstack/files/openstack-keepalived-keepalived.yaml
templates/worker/00-worker/ovirt/files/ovirt-keepalived-keepalived.yaml

Fixes #1379
The current keepalived ingress VIP password is hardcoded so I've changed to follow the other VIP passwords.
Deploy a cluster and observe the `/etc/keepalived/keepalived.conf` file
Fixed hardcoded ingress VIP password

Bug 1803232: Fixed hardcoded ingress VIP password

---

manifests/kubeletconfig.crd.yaml
pkg/operator/assets/bindata.go

Recent changes to kubeletcfg manifests seem to have broken our kubeletcfgs.  This is on a cluster using master.
When I create a new kubelet config from https://github.com/openshift/machine-config-operator/blob/master/docs/KubeletConfigDesign.md#spec 
```
metadata:
name: set-max-pods
spec:
matchLabels:
custom-kubelet: small-pods
kubeletConfig:
maxPods: 100
```
I see errors:
```$ oc apply -f maxpods.yaml
The KubeletConfig "set-max-pods" is invalid: 
* spec.kubeletConfig.apiVersion: Required value: must not be empty
* spec.kubeletConfig.kind: Required value: must not be empty
```
It seems to be validating against something different than our kubeletconfig type (upstream maybe?)
Thoughts?

Bug 1811211: remove validation of kubeletcfg which is breaking our kubeletcfg

---

manifests/controllerconfig.crd.yaml
pkg/apis/machineconfiguration.openshift.io/v1/types.go
pkg/operator/assets/bindata.go

Infra does not seem mandatory for every platform, and can be null
for some existing clusters. Thus, make it able to be a null object,
otherwise it will fail validation.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1812179
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>

Bug 1812179: manifests/controllerconfig: make infra nullable

---

pkg/daemon/daemon.go

Closes: 1804693
We had skipped a file check on etcd-member so as to enable landing of cluster-etcd-operator, but we can remove that check now that we have been able to remove the file overall.
Install or upgrade to OCP 4.5, it should come up.

Bug 1804693: Revert the changes to skip file checks on etcd-member

---

install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml

* updated `etcd-quorum-guard` deployment to generate readiness script once and use host IP and name to find certificates in defined locations.
* removed `hostNetwork: true` from this deployment.
This caused all network traffic to be counted as a container traffic, so some pods had > 4MBps network in/out in console
Run setup / upgrade. 
Check network in/out data for etcd-quorum pods

etcd quorum guard: don't set hostNetwork

---

manifests/kubeletconfig.crd.yaml
pkg/operator/assets/bindata.go

[4.4] Bug 1811212: remove upstream validation which is breaking our kubeletcfg

---

pkg/daemon/node.go
pkg/daemon/writer.go

Cherry-pick of #1404 
---
- What I did
Fixes issue where an "annotation not found" error compounds via wrapping the node in the error message, growing the machineconfiguration.openshift.io/reason annotation until it hits the annotation max size limit, thereby preventing updates to that node's annotations by controllers.
Remove node object from "annotation not found" error and replace with just node name
Truncate errors used in machineconfiguration.openshift.io/reason node annotation to prevent any that may contain large amounts of data from maxing out annotation size.
Stop MCO and MCC controllers
Delete the machineconfiguration.openshift.io/desiredConfig annotation on a node and wait for the MCD to sync the update
Check the node object for the …

Bug 1797790: [release-4.2] prevent hitting annotation max size limit on nodes (cherry-pick)

---

install/0000_80_machine-config-operator_06_clusteroperator.yaml
pkg/operator/status.go
pkg/operator/sync.go

fixes relatedObject reconciliation found in https://github.com/openshift/cluster-version-operator/pull/318 .  This is in service to https://github.com/openshift/enhancements/pull/149 .  The addition of relatedObjects in the CO itself means that when the operator doesn't start during bootstrapping, we can still get good PD data.

reconcile relatedObjects and place them in the clusteroperator for CVO

---

templates/master/00-master/openstack/files/NetworkManager-resolv-prepender.yaml
templates/worker/00-worker/openstack/files/NetworkManager-resolv-prepender.yaml

This prevents the pods from complaining about the nameserver limits
exceeded:
Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.0.128.6 10.0.128.12 10.0.128.11 (207 times)

Bug 1791008: OpenStack: Limit the number of nameservers to 3

---

templates/master/00-master/baremetal/files/baremetal-haproxy.yaml

This PR updates HAProxy static pod manifest to enable reading API LB backend details
from Kubernetes instead of _etcd-server-ssl._tcp SRV.

[baremetal] Add support for reading API LB backends from KUBE-API

---

templates/common/vsphere/files/vsphere-hostname.yaml
templates/common/vsphere/units/vsphere-hostname.yaml

This commit adds two new files:
- A systemd unit that runs a shell script
- A shell script that runs vmtoolsd to retrieve `guestinfo.hostname`
from vm guest. Then uses hostnamectl to set hostname.

vsphere ipi: set hostname using vmtoolsd and VM extra config

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

change the entry in crio.conf template to manage ns lifecycle
As it is more secure and gives cri-o more control of namespace lifecycle. Also change the outdated config name value
CRI-O now manages namespace lifecycle

cri-o: set manage_ns_lifecycle to true

---

Makefile

Avoids querying the network and download vendors in the CI mainly.

Makefile: use ./vendor for tests

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

This reverts commit 9b3e28d2f6bf884c3903581ac96ee2e690df5c86.
there were some breakages with third party networking plugins as the network ns path changed unexpectedly. revert the switch to cri-o managing namespace lifecycle until this problem is fixed
CRI-O is no longer managing namespace lifecycle

Revert "cri-o: set manage_ns_lifecycle to true"

---

templates/common/_base/units/machine-config-daemon-firstboot.service

Wrapped "podman pull <machine-config-daemon container>" in a retry loop
Run OKD install when registry.svc.ci.openshift.org is unstable. Less flakes are expected on CI / user installs.
Fixes https://github.com/openshift/okd/issues/124

[fcos] machine-config-daemon-firstboot: retry podman pull

---

pkg/daemon/update.go

Adds to https://github.com/openshift/machine-config-operator/pull/1586
Add a check for backwards compatibility: basically if the file
doesn't exist in /usr/etc/ and no rpm is claming it, we assume
that the orig file came from a wrongful backup of a MachineConfig
file instead of a RHCOS file.

Bug 1814397: fix wrongful backup of files not originally on the system

---

pkg/daemon/update.go

Cherry-pick of https://github.com/openshift/machine-config-operator/pull/1593 to `fcos` branch.
This ensures update from march versions (which still have `/usr/local/bin/etcd-snapshot-backup.sh` in `00-master`) passes

[fcos] fix wrongful backup of files not originally on the systemackup of files not originally on the system

---

pkg/daemon/update.go

Initially we were relying on fixed set of kernel-rt
sub-packages which will be installed on the system. This can cause
issues when machine-os-content ships additional kernel-rt
sub-packages.
To solve this, we now query host with
`rpm-ostree status --json` and look for requested-local-packages
in the 0th index from available deployments list.
Fixes bug - https://bugzilla.redhat.com/show_bug.cgi?id=1820401

Bug 1820401: daemon: better way to find installed kernel-rt packages on host

---

pkg/operator/status.go
pkg/operator/sync.go

The MCO runs a bunch of sync functions during its sync. Each of these functions has
a name (a task name). When we loop through the sync functions and fail on any of them,
the MCO breaks and reports the Degraded status for that task as Reason: TaskNameFailed.
It then goes and retries all the sync functions (no change in behavior till here).
During some debugging and testing I've noticed that the RenderConfig task failed with the
version mismatch error for osImageURL. That is good, and also right. The MCO went ahead
and set the Degraded condition to RenderConfigFailed (correctly!). The MCO then went again
and re-tried all the sync functions. Now the RenderConfig task succeeded (the version mismatch error
can indeed be temporary). What happened from now on is that the MCO kept rolling and …

pkg/operator: clear Degraded on task's success

---

go.sum
pkg/daemon/update.go

Bug 1817455: [release-4.4] fix wrongful backup of files not originally on the system

---

templates/common/baremetal/files/baremetal-non-virtual-ip.yaml
templates/common/baremetal/files/nodeip-finder.yaml
templates/common/baremetal/units/nodeip-configuration.service

nodeip-finder: retry on failure
It is possible for NM-wait-online to let our node ip configuration
service go through before the control plane IP Address and/or Route is
configured. In such cases it would be great to have the systemd service
be able to retry on failure. Unfortunately, the current version of RHCOS
does not have a new enough systemd version, so we implement the retry
mechanism in the script itself.

Bug 1819484: Nodeip retry on failure

---

OWNERS

We need to add this now to efficiently route BZs.

OWNERS: add BZ component name

---

cmd/machine-config-operator/start.go

Other subcomponents are still following the old version logging when Raw and Hash
are sufficient for us to debug. This patch just changes the MCO itself to print
RELEASE_VERSION at startup. We might want to revisit this for all components and
bootstrap commands later but not critical either.

Bug 1811898: cmd/machine-config-operator: log RELEASE_VERSION when starting up

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

set log level to info as it's difficult to debug with cri-o only set to log level error
set default log level to info for CRI-O

cri-o: set log level to info

---

pkg/daemon/update.go

As per request by @smarterclayton , adding an event for drain failures.
Lmk if you'd like anything else.

pkg/daemon: Add event for drain failures

---

templates/worker/00-worker/ovirt/files/ovirt-disable-tx-checksum-offload.yaml

This patch adds the workaround suggested on [1]
to make nodeport work, instead of ethtool we use
NM to apply the fix for each connction before it is up.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1794714
Signed-off-by: Gal Zaidman <gzaidman@redhat.com>

ovirt: disable tx checksum offload for workers

---

templates/common/_base/files/nm-ignore-sdn.yaml

To prevent racing with NetworkManager's OVS plugin resulting in IP addresses sometimes being cleared from the OVS internal ports that openshift-sdn and ovn-kubernetes set up, we must tell NM to ignore those ports.
@trozet @danwinship @squeed @openshift/networking

Bug 1820822: sdn: ignore new ovn-kubernetes OVS internal port names ovn-k8s-gw0 and ovn-k8s-mp0

---

templates/master/00-master/baremetal/files/NetworkManager-resolv-prepender.yaml
templates/worker/00-worker/baremetal/files/NetworkManager-resolv-prepender.yaml

When keepalived sets the VIP, it triggers a connection event in
NetworkManager that, since the name we set from DHCP was transient it
would do a reverse lookup on the connection address. Unfortunately, NM
does not filter out the deprecated VIP for the reverse lookup and ends
up overriding the hostname with DNS names that map to VIPs configured in
the system.
This fix is a workaround that on environments that have DHCP provide the
hostname, will prevent the erroneous behavior of NM by setting DHCP
provided FQDN addresses as static, which prevents NM from doing further
address lookups.
On hostname-less DHCP environments we'd want to hook to the hostname
event in NM and make sure that the first one that does not map to a VIP
is the one that gets set as static.

baremetal: static hostname to prevent DNS lookup

---

templates/worker/00-worker/openstack/files/openstack-disable-tx-checksum-offload.yaml

This patch adds the workaround suggested on [1]
to make nodeport work, instead of ethtool we use
NM to apply the fix for each connction before it is up.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1794714
Brings the following ovirt fixes to openstack platform:
- #1606
- #1621

Bug 1821798: OpenStack: disable tx checksum offload for workers

---

Makefile

This is inferred by the golang-1.13 container now and currently block CI testing
Makefile: Drop -mod=vendor flag
CI
Makefile: Drop -mod=vendor flag

Makefile: Drop -mod=vendor flag

---

templates/worker/00-worker/ovirt/files/ovirt-disable-tx-checksum-offload.yaml

On PR [1] we added a workaround for Bug [2], this
fails when the worker starts for the first time since openshift-sdn
is created only when the sdn pod is starting.
Instead we will disable by default and enable tx-checksum offload\
only when running with OVNkubernetes
[1] On PR https://github.com/openshift/machine-config-operator/pull/1606,
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1794714
Signed-off-by: Gal Zaidman <gzaidman@redhat.com>

Bug 1821005: oVirt, fix disable tx checksum offload for workers

---

templates/worker/00-worker/ovirt/files/ovirt-disable-tx-checksum-offload.yaml

We need to disable tx checksum offload on worker nodes due to BZ#1794714.
This is currenly a workaround and is tracked for removal on BZ#18.
Signed-off-by: Gal Zaidman <gzaidman@redhat.com>

Bug 1820975: oVirt, fix disable tx checksum offload for workers

---

pkg/controller/common/helpers.go
pkg/controller/container-runtime-config/helpers.go
pkg/controller/kubelet-config/helpers.go

With the introduction of rawExtension for Ignition config objects
via https://github.com/openshift/machine-config-operator/pull/996,
we also now use ignition.Parse directly to process the validity of
ignition configs. This will cause machineconfigs without a Ignition
section to fail, which we don't want.
Also modify some error messages for clarity.
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>

Bug 1821888: controller: do not error on empty Ignition configs

---

templates/common/gcp/files/gcp-routes-sh.yaml

Using routing tables means that existing connections are immediately
severed when the vip is removed from the node. By using conntrack
instead, existing connections are gracefully preserved.
This commit has been ported from the redhat-coreos repo.
The original author is @squeed
/cc @vrutkovs

[fcos] GCP-routes: switch to using conntrack instead of route tables

---

Makefile

Restore code-generator's go.mod file and
remove vendor/k8s.io/code-generator/vendor directory
after running verification in`make verify`
/cc @sinnykumari @yuqi-zhang

Makefile: Cleanup after `make verify`

---

pkg/controller/container-runtime-config/container_runtime_config_controller.go
pkg/controller/container-runtime-config/helpers.go

Fixes #1809007 (https://bugzilla.redhat.com/show_bug.cgi?id=1809007)
A map doesn't guarantee order when we are creating new ignitions.
When we update the image CR with blocked registries, the ctrcfg
controller needs to update two files registries.conf and policy.json.
Since we get an update from the image CR about every 20 mins, we compare
the semantics to see if anything has changed. But since the order is not
guaranteed, the controller might think that the semantics is not equal
even if nothing in the data changed. Hence another MC is created, and
everytime we get an update the MC applied to the nodes keeps flipping
back and forth for the 2 possible orders causing the nodes to reboot a
bunch of times. So move to using …

Bug 1809007: [ctrcfg controller] Use a struct array instead of map when creating new ignitions

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

RHCOS is shipped with `containernetworking-plugins` (which is a dependency for CRI-O and podman), ex:
```
$ rpm -qa | grep containernetwo
containernetworking-plugins-0.8.3-4.module+el8.1.1+5259+bcdd613a.x86_64
```
These binaries are needed for rudimentary networking actions and the CNO has a much more intricate way of copying the binaries on the host by checking `/etc/os-release` and selecting the right binary depending on the underlying OS. 
Since the rpm exist, let's just add the unpacked RPM's bin location to CRI-O's config so that it can look there. The final goal of this is to stop copying binaries (at least `loopback`) in the CNO.  
Add containernetworking-plugin RPM's bin location to CRI-O config

Add containernetworking-plugin RPM's bin location to CRI-O config

---

templates/common/_base/files/cleanup-cni-conf.yaml

This is due to the fact that we'd like the nodes to come into a "Ready" state
sooner during an upgrade. Multus CNI has the ability to wait for an indication
of the readiness of the default CNI network (typically, openshift-sdn)

Bug 1821833: The Multus CNI configuration file "00-multus.conf" should not be removed

---

templates/common/baremetal/files/baremetal-keepalived.yaml

Update Liveness probe for keepalived container to check also keepalived process existence, 
with this fix if for some reason keepalived process exits - kubelet will automatically restart the container. 

[baremetal] Update keepalived Liveness check

---

machine-config-daemon.spec

After moving to [kubernetes 1.18](https://github.com/openshift/machine-config-operator/pull/1618), we need golang 1.13 to build MCD rpm package

spec: requires golang >=1.13

---

install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml

Updated the script created by etcd quroum guard deployment to run curl with `NSS_SDB_USE_CACHE=no`
Observe etcd-quorum-guard memory consumption
Fixed an issue in 4.5/4.4 which caused memory consumption of readyness probes in etcd-quorum-guard
Initial fix: #705, regression occurred in #1552 
Ref: https://github.com/openshift/okd/issues/146

Bug 1823677:etcdquorumguard_deployment: pass NSS_SDB_USE_CACHE=no to curl

---

pkg/daemon/rpm-ostree.go
pkg/daemon/rpm-ostree_test.go
pkg/daemon/update.go
pkg/daemon/update_test.go

Make GetBootedDeployment() function from rpm-ostree.go public
so that it can be reused.
Follow-up from PR https://github.com/openshift/machine-config-operator/pull/1612

pkg/daemon: reuse rpm-ostree code to get currently booted CoreOS host info

---

pkg/controller/container-runtime-config/container_runtime_config_controller.go
pkg/controller/container-runtime-config/helpers.go

Fixes #1822748 (https://bugzilla.redhat.com/show_bug.cgi?id=1822748)
Cherry-pick of https://github.com/openshift/machine-config-operator/pull/1637
A map doesn't guarantee order when we are creating new ignitions.
When we update the image CR with blocked registries, the ctrcfg
controller needs to update two files registries.conf and policy.json.
Since we get an update from the image CR about every 20 mins, we compare
the semantics to see if anything has changed. But since the order is not
guaranteed, the controller might think that the semantics is not equal
even if nothing in the data changed. Hence another MC is created, and
everytime we get an update the MC applied to the nodes keeps flipping
back and forth for the 2 …

[release-4.4] Bug 1822748: [ctrcfgcontroller] Use a struct array instead of map when creating new ignitions

---

docs/HACKING.md

Like latest MCO needs golang 1.13

docs: update HACKING doc with latest information

---

manifests/vsphere/coredns.yaml
manifests/vsphere/keepalived.conf.tmpl
manifests/vsphere/keepalived.yaml
pkg/operator/assets/bindata.go
templates/common/vsphere/files/vsphere-coredns.yaml
templates/common/vsphere/files/vsphere-keepalived.yaml
templates/common/vsphere/files/vsphere-mdns-publisher.yaml
templates/master/00-master/vsphere/files/NetworkManager-resolv-prepender.yaml
templates/master/00-master/vsphere/files/vsphere-keepalived-keepalived.yaml
templates/worker/00-worker/vsphere/files/NetworkManager-resolv-prepender.yaml

Align with current updates to baremetal
See PR #1569
"Now that etcd does not need DNS for clustering, we no longer need to
have a VIP to allow the masters to use the bootstrap coredns until
their own coredns instances start. Instead, we can just point them
at the local coredns directly and skip the extra complexity. We
already do this on the workers because they never had a dependency
on the bootstrap coredns so the same method is now used for masters."

Update vSphere IPI removing DNS VIP

---

manifests/baremetal/coredns.yaml
manifests/baremetal/keepalived.conf.tmpl
manifests/baremetal/keepalived.yaml
pkg/operator/assets/bindata.go
templates/common/baremetal/files/baremetal-coredns.yaml
templates/common/baremetal/files/baremetal-keepalived.yaml
templates/common/baremetal/files/baremetal-mdns-publisher.yaml
templates/master/00-master/baremetal/files/NetworkManager-resolv-prepender.yaml
templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml
templates/worker/00-worker/baremetal/files/NetworkManager-resolv-prepender.yaml

Now that etcd does not need DNS for clustering, we no longer need to
have a VIP to allow the masters to use the bootstrap coredns until
their own coredns instances start. Instead, we can just point them
at the local coredns directly and skip the extra complexity. We
already do this on the workers because they never had a dependency
on the bootstrap coredns so the same method is now used for masters.

baremetal: Remove DNS VIP

---

templates/common/_base/files/nm-ignore-sdn.yaml

To prevent racing with NetworkManager's OVS plugin resulting in IP addresses sometimes being cleared from the OVS internal ports that openshift-sdn and ovn-kubernetes set up, we must tell NM to ignore those ports.
@trozet @danwinship @squeed @openshift/networking
backport of https://github.com/openshift/machine-config-operator/pull/1614

Bug 1820823: [4.4] sdn: ignore new ovn-kubernetes OVS internal port names ovn-k8s-gw0 and ovn-k8s-mp0

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

Fixes #1820507 (https://bugzilla.redhat.com/show_bug.cgi?id=1820507)
Add the default_env field to the crio.conf template
that is laid down by the MCO
Add default_env filed to the crio.conf template

Bug 1820507: Add new crio.conf field to the template

---

templates/master/01-master-container-runtime/_base/files/crio.yaml
templates/worker/01-worker-container-runtime/_base/files/crio.yaml

Fixes #1822268 (https://bugzilla.redhat.com/show_bug.cgi?id=1822268)
Add the default_env field to the crio.conf template
that is laid down by the MCO
Add default_env filed to the crio.conf template

[release 4.4] Bug 1822268: Add new crio.conf field to the template
