openshift/machine-config-operator

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml, templates/common/on-prem/units/kubelet.service-wait-resolv.yaml
Work around several resolv-prepender issues:
- hostnamectl fails due to being denied by selinux
- resolv-prepender waits more than the overall NM timeout, making devices to not come up
- resolv-prepender copies resolv.conf without nameservers
- kubelet starts before resolve-prepender has had a chance to set resolv.conf and openshift-dns coredns pods fail to start.
=> Bug 2105003: on-prem: improvements on resolv-prepender

templates/common/_base/files/configure-ovs-network.yaml
Manual cherry-pick of #3242 to release-4.11.
Data added to string array in piped while loop is not retained after the loop. Process substitution (http://mywiki.wooledge.org/ProcessSubstitution) fixes the problem.
Signed-off-by: Arkadeep Sen <arsen@redhat.com>
(cherry picked from commit 7617323936a521c03217338b2b358571e4b9a6fe)
=> [release-4.11] Bug 2104386: Fix problem with retaining data in string array in piped while loop

pkg/controller/common/helpers.go, pkg/controller/common/helpers_test.go, pkg/controller/render/render_controller.go, pkg/controller/render/render_controller_test.go, pkg/daemon/daemon.go, pkg/daemon/rpm-ostree.go, pkg/daemon/rpm-ostree_test.go, pkg/daemon/update.go
This allows `OSImageURL`in `MachineConfig` to be overridden with a layered image. 
This isn't entirely complete, I'm still working on cleaning it up, but:
-  the functionality does work
-  I'd like to see what e2e tests this breaks :smile: 
In https://github.com/openshift/machine-config-operator/pull/3258 I was more worried about dealing with the image in the payload, but since that seems like it might be blocked for a little while, we'll start with this and then we can go back and connect those tubes later. 
Credit where credit is due, @yuqi-zhang started doing this against the layering branch over here back in February: https://github.com/openshift/machine-config-operator/pull/2939
This is in service to: [MCO-291](https://issues.redhat.com/browse/MCO-291)
=> Allow overriding OSImageURL with a layered image 

cmd/machine-config-operator/bootstrap.go, install/0000_80_machine-config-operator_02_images.configmap.yaml, install/0000_80_machine-config-operator_04_deployment.yaml, install/0000_80_machine-config-operator_05_osimageurl.yaml, install/image-references, lib/resourcemerge/machineconfig.go, manifests/controllerconfig.crd.yaml, pkg/apis/machineconfiguration.openshift.io/v1/types.go, pkg/controller/render/render_controller.go, pkg/operator/bootstrap.go, pkg/operator/images.go, pkg/operator/sync.go
As discussed in https://github.com/openshift/machine-config-operator/pull/3258, this:
- allows the MCO to consume the new image format
- adds the new `rhel-coreos-8` and `rhel-coreos-8-extensions` images to the MCO's `image-references` file so after this they will show up in nightlies 
- propagates the new base image and extensions container into controllerconfig
Once this is in, and the MCO can accept the new argument, we will need to: 
- PR something like this https://github.com/jkyros/installer/commit/cdf785897ec64ffab940fa912c15e938021749a2 to the installer to dump out the images file so the MCO can consume it during bootstrap 
And then once that is in, we can go back to https://github.com/openshift/machine-config-operator/pull/3258 and decide if/when/how we want the MCO to use the …
=> Accept new image format, consume in controllerconfig, but stop there 

pkg/daemon/rpm-ostree.go
So about a month ago we merged
https://github.com/openshift/machine-config-operator/pull/3239/commits/0bcb4d205d7343436ffdc482f8ede73bc429552a
which dropped all the old workarounds we had for rpm-ostree bugs.
I'm sure you are all shocked that less than a month later, we have
a new one to add in this section.
Actually though one of those previous bugs was arguably really a
systemd bug provoked by rpm-ostree...and that's the case again here.
This is all covered in
https://bugzilla.redhat.com/show_bug.cgi?id=2104619
and
https://github.com/coreos/rpm-ostree/pull/3939/commits/21c82ffe36dff61b2be8778634c571cb177a24e9
but TL;DR systemd's implementation of `InaccessiblePaths` has
quadratic behavior in number of mounts, and so of course
we only discover this when we're testing heavily loaded OCP …
=> Bug 2111817: daemon: Add a workaround for bug 2111817

pkg/daemon/rpm-ostree.go
systemd's implementation of `InaccessiblePaths` has
quadratic behavior in number of mounts.
The fix to rpm-ostree is inbound.  But...adding this workaround which
has the MCD dynamically reconfigure the system to drop that config will
help unstick clusters so they can get the real fix.
Manual backport of PR https://github.com/openshift/machine-config-operator/pull/329
=> OCPBUGS-197: daemon: Add a workaround for bug 2111817

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
The Assisted Installer sets the hostname of a node by writing to the
file /etc/hostname.  When using with IPv6, the hostname is being
overwritten by NetworkManager when DHCPv6 reply contains FDQN.  In this
case the FDQN is written to the file /etc/hostname, thus overriding the
requsted hostname of the Assisted Installer.
This change will cause the FDQN to be written to /etc/hostname file only
if the file didn't exist, or the file was empty, or it contained the
default hostname (localhost.localdomain).
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2051533
Tested on live environment
Set static hostname only if it was not set before in /etc/hostname
/cc @tsorya 
/cc @celebdor
=> Bug-2051533: Adding day2 remote worker node requires manually approving CSRs

pkg/daemon/kernelargs.go, pkg/daemon/osrelease.go, pkg/daemon/update.go
This adds MCD support for `ID="scos"` in `/usr/lib/os-release` and
`/etc/os-release`.
Done:
Requires: ~~https://github.com/openshift/os/pull/773 and possibly https://issues.redhat.com/browse/MCO-126~~ we can defer both
/cc @cheesesashimi 
/cc @travier 
MCD: Add support for RHCOS9 and SCOS9
=> MCD: Add support for RHCOS9 and SCOS9

pkg/controller/template/render.go, pkg/operator/render.go
This isn't used anymore since we enabled Unicast for all on-prem
platforms which use Keepalived, via #3016.
=> Remove `onPremPlatformKeepalivedEnableUnicast` function

templates/common/_base/files/kubelet-auto-sizing.yaml
Signed-off-by: Kenneth D'souza <kennethdsouza94@gmail.com>
Closes: #3298 
Added code to make sure  kubelet-auto-sizing script  recommends SYSTEM_RESERVED_MEMORY size in power of 2^n, as in some cases the value reported can be in decimal. 
Pass RAM size as 377Gi to the script:
Before patch:
SYSTEM_RESERVED_MEMORY=14.3Gi
After patch:
SYSTEM_RESERVED_MEMORY=14Gi
Round off SYSTEM_RESERVED_MEMORY if value is in decimal
=> Round off SYSTEM_RESERVED_MEMORY if value is in decimal

pkg/controller/common/helpers.go
Fixes a lint issue with the gosec linter. Specifically, it fixes gosec rule G110.
Run the unit tests and run the gosec linter.
Fixes gosec lint G110
=> fixes config decompression lint issue

Dockerfile, cmd/machine-config-operator/bootstrap.go, hack/build-go.sh, pkg/version/version.go, pkg/version/version_fcos.go, pkg/version/version_scos.go
Follow up to https://github.com/openshift/machine-config-operator/pull/3286
This change introduces the TAGS build-arg in `Dockerfile` which is
propagated through to the Go build as a build constraint (aka build tag).
Supported values for TAGS are `fcos` and `scos`, with `fcos` taking
precedence if both are specified.
This is necessary to modify the otherwise hard-coded imagestream tag
`rhel-coreos-8` used for the RHCOS8 OS container image to be either
`fedora-coreos` in OKD on FCOS, or `centos-stream-coreos-9` in OKD on
SCOS.
- CI does not break
- manually built image (e.g. with `podman build -f Dockerfile --build-arg TAGS="scos"`) has IS tag named `centos-stream-coreos-9` in `/manifests/image-references`
OKD: Add …
=> OKD: Add build args for FCOS and SCOS

pkg/daemon/daemon.go, pkg/daemon/update.go, pkg/daemon/update_test.go
Drive by cleanup I noticed while working on the code; the daemon
has an instance of this, so use it rather than creating
a new one.
=> daemon: Use just one NodeUpdaterClient instance

install/0000_80_machine-config-operator_02_containerruntimeconfig.crd.yaml, pkg/apis/machineconfiguration.openshift.io/v1/types.go, pkg/controller/container-runtime-config/container_runtime_config_bootstrap.go, pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/container-runtime-config/helpers.go
Update the containerruntimeconfig with `DefaultRuntime` which allows users to specify a different default runtime. At present, the only fully supported options are `"runc"` and `""`. If the cluster has the `TechPreviewNoUpgrade` feature set enabled, then they gain access to `crun` as well.
Launch a cluster with this PR
run `oc describe crd/containerruntimeconfigs.machineconfiguration.openshift.io`
see the presence of `defaultRuntime` field
Add support for DefaultRuntime in ContainerRuntimeConfig CRD, allowing users to specify a different default OCI runtime for CRI-O to run containers with. At present, the only fully supported options are `"runc"` and `""`. If the cluster has the `TechPreviewNoUpgrade` feature set …
=> Add RuntimeDefault to ctrcfg

pkg/daemon/update.go
Fixes: OCPBUGS-642 (release-4.10 backport of BZ#2107113)
- What I did: Create the `~core/.ssh` directory in advance if it didn't previously exist and chown it to `core` user
- How to verify it: Create a cluster without SSH keys and configure those via machine-config post-install. Before fix, `~core/.ssh` user was owned by `root`, with this fix, it is owned by `core` user as expected
- Description for the changelog: Fix .ssh directory not owned by core when created by Machine Config Daemon
=> OCPBUGS-642: Fix .ssh directory not owned by core when created by Machine Config Daemon

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
In order to avoid a podman issue [1] causing a layer corruption when an
image pull is killed midway, let's move the image pull outside of the
timeout command.
The timeout was recently reduced to 20 seconds with [2] making the issue
more likely to happen.
[1] https://github.com/containers/podman/issues/14003
[2] https://github.com/openshift/machine-config-operator/pull/3271
=> OCPBUGS-631: Pull container image as a separate step

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
In order to avoid a podman issue [1] causing a layer corruption when an
image pull is killed midway, let's move the image pull outside of the
timeout command.
The timeout was recently reduced to 20 seconds with [2] making the issue
more likely to happen.
[1] https://github.com/containers/podman/issues/14003
[2] https://github.com/openshift/machine-config-operator/pull/3271
Backports #3318
=> OCPBUGS-737: Pull container image as a separate step

cmd/machine-config-daemon/start.go
This will return when the pod terminates, so no reason to have a confusing error message here when its not an error.
=> Hypershift: remove error message on return

pkg/daemon/daemon.go
Currently the special Hypershift path does not have disruptionless
update capabilities like self-driving OCP. This adds that in for the
Hypershift path.
There is a bunch of duplication with update() functions, but considering
that eventually we need to de-duplicate the whole funtion, this is
easier to do for now until things are more settled.
=> MCO-256: hypershift: add disruptionless updates to MCD

pkg/operator/status.go, pkg/operator/status_test.go
Whenever we update the ClusterOperator with our availability status, we are not
providing a reason as to why the update is occurring. Additionally, where we
become unavailable, we are missing additional context that could ease the
debugging process.
I've updated the unit test suite included in pkg/operator to reflect my changes.
Operator availability updates should have a reason
=> OCPBUGS-825: Provide a reason if operator is unavailable

templates/common/_base/files/configure-ovs-network.yaml
These are mostly cherry picks of CARRY pre-requisites for https://github.com/openshift/machine-config-operator/pull/3180/commits/7d4c459cbb2f898d78f780a9d5abe621f6fff18f, that commit itself and follow-up fixes for it.
Mostly clean cherry-picks but added comments on manual bits for easy reviewing, but most are related with the fact that 4.8 has no support for secondary bridge in configure-ovs.
=> [release-4.8] Bug 2094765: configure-ovs: avoid restarting NetworkManager

install/0000_80_machine-config-operator_02_containerruntimeconfig.crd.yaml
This was added in https://github.com/openshift/cluster-version-operator/pull/821 to allow more featuresets and allow for a future migration to include actual gates.  Because usage of this manifest would prevent upgrades, there are not upgrade concerns for this change.
/cc @wking
=> update to release.openshift.io/feature-set to match OCP 4.12

install/0000_80_machine-config-operator_00_namespace.yaml
This has been affecting kubelet creating mirror pods for keepalived, haproxy etc.
Add privileged labels to infra namespaces.
Kubelet logs should not have errors about "Failed creating a mirror pod for .... is forbidden: violates PodSecurity" error. 
Since this PR: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1369, many pods are affected and fail to create. The infra namespaces are affecting kubelets. The following are some sample errors. 
```
Sep 02 14:02:06.914534 hckrs6pg-c805c-7czxl-master-0.novalocal kubenswrapper[1782]: E0902 14:02:06.914490    1782 kubelet.go:1713] "Failed creating a mirror pod for" err="pods \"keepalived-hckrs6pg-c805c-7czxl-master-0{color}" is forbidden: violates …
```
=> TRT-540: Add privileged label to infra namespaces

pkg/controller/kubelet-config/helpers.go, pkg/controller/kubelet-config/kubelet_config_bootstrap.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_features.go, pkg/controller/kubelet-config/kubelet_config_nodes.go, test/e2e-bootstrap/bootstrap_test.go
Signed-off-by: Sai Ramesh Vanka <svanka@redhat.com>
Added the code to modify the cgroup configuration on all the nodes based on the user provided input of the [cgroupMode](https://github.com/openshift/api/blob/master/config/v1/types_node.go#L36) in the nodes.config.openshift.io custom resource.
By default the `cgroupv1` is enabled on all the nodes of an OCP cluster. Edit the `cgroupMode` field of the `nodes.config.openshift.io` custom resource's `spec` and observe the following kernel arguments appended in the newly created machine config object.
```
kernelArguments:
- systemd.unified_cgroup_hierarchy=1
- cgroup_no_v1="all"
- psi=1
```
Also observe the `cgroupv2` output when the following command is run inside any node.
```
sh-4.4# stat -c %T -f …
```
=> OCPNODE-1146 Add cgroup confiuration support in MCO

pkg/controller/kubelet-config/helpers.go, pkg/controller/kubelet-config/kubelet_config_bootstrap.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_features.go, pkg/controller/kubelet-config/kubelet_config_nodes.go, test/e2e-bootstrap/bootstrap_test.go
This reverts commit a627415c240b4c7dd2f9e90f659690d9c0f623f3, reversing changes made to 26eaa2c19b8d0434de7eca9f2c3806ef7fc9f05a.
Reverting the change so as to fix the CI failures for now.
Fixes: https://issues.redhat.com/browse/OCPBUGS-1616
1. The changes are breaking the techpreview CI jobs.
2. The rendered configs in bootstrap and the controller generated differ by the config Node changes
like nodeStatusUpdate frequency and the kernel arguments to enable the cgroupv2 mode.
=> OCPBUGS-1616: Revert "Merge pull request #3311 from sairameshv/cgroupv2"

Dockerfile, cmd/machine-config-operator/bootstrap.go, go.mod, install/0000_80_machine-config-operator_01_machineconfig.crd.yaml, install/0000_80_machine-config-operator_05_osimageurl.yaml, install/image-references, lib/resourcemerge/machineconfig.go, manifests/controllerconfig.crd.yaml, pkg/apis/machineconfiguration.openshift.io/v1/types.go, pkg/controller/common/constants.go, pkg/controller/common/helpers.go, pkg/controller/common/helpers_test.go, pkg/controller/render/render_controller.go, pkg/controller/template/render.go, pkg/daemon/daemon.go, pkg/daemon/rpm-ostree.go, pkg/daemon/rpm-ostree_test.go, pkg/daemon/update.go, pkg/operator/bootstrap.go, pkg/operator/images.go, pkg/operator/status.go, pkg/operator/status_test.go, pkg/operator/sync.go
This: 
- Makes the operator apply a service and deployment manifest for the extensions container if we have one
- Adds a template for the `rhel-coreos-8-extensions.repo`
- Allows the daemon to make "rebootless" changes to /etc/yum.repos.d/* so we don't trigger a reboot with our template
- Re-enables kernel switching and extensions for the "layering" path 
- Tries to gate all of this behind the presence of the extensions container
Caveats: 
- The node doesn't have access to "pod dns" so it can't find the repo service unless it's told about it
- I fixed this for my testing by adding this next to the registry in the node resolver https://github.com/openshift/cluster-dns-operator/commit/71df59c533a3282beb790e9a0a107ce8b279cb29 and packing my own node resolver in the payload. 
To try this …
=> MCO-289: Teach the MCO to use new format image

templates/common/_base/files/configure-ovs-network.yaml, templates/common/_base/units/nodeip-configuration.service.yaml, templates/common/_base/units/ovs-configuration.service.yaml, templates/common/on-prem/units/nodeip-configuration.service.yaml
[RFE-2962](https://issues.redhat.com//browse/RFE-2962): configure ovs should use node-ip-hint set by
nodeip-configuration service to set bridge on interface that matches
this ip
=> RFE-2962: configure ovs should use node-ip-hint set by nodeip-configuration service

cmd/machine-config-operator/bootstrap.go
xref https://github.com/openshift/hypershift/issues/1767
Basically hypershift is still using the "pass each image via CLI argument" and doing the better "just give me all the images" flow via `--image-references` would require a surprising amount of code change on that side.
Add CLI arguments for the container images so they can be passed the way hypershift is doing now.
=> bootstrap: Add CLI arguments for new format oscontainer

Dockerfile
SCOS will at least initially not be shipping an extensions image, so comment out all references to it.
=> Dockerfile: Remove SCOS extensions image references

templates/common/alibabacloud/files/usr-local-bin-alibaba-kubelet-nodename.yaml, templates/common/alibabacloud/files/usr-local-lib-systemd-system-generators-alibaba-kubelet-extra-env-generator.sh.yaml
systemd environment file. This fixes bug 2056387 systemctl
daemon-reload to alibaba-kubelet-nodename.service.yaml.
the env file generated by usr-local-bin-alibaba-kubelet-nodename.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2056387
1. Ensure the file gets placed: /usr/local/bin/alibaba-kubelet-nodename
1. Ensure the file gets placed: /usr/local/lib/systemd/system-generators/alibaba-kubelet-extra-env-generator.sh
1. Reload systemd with "systemctl daemon-reload"
1. Ensure that kubelet.service now lists a generator with "systemctl status kubelet". Should look something like:
```
● kubelet.service - Kubernetes Kubelet
Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
Drop-In: …
```
=> Bug 2056387: fix alibaba kubelet node name unit

templates/common/_base/files/configure-ovs-network.yaml, templates/common/_base/units/nodeip-configuration.service.yaml, templates/common/_base/units/ovs-configuration.service.yaml, templates/common/on-prem/units/nodeip-configuration.service.yaml
Reverts openshift/machine-config-operator#3233
This is a test, we've got a regression in https://issues.redhat.com/browse/OCPBUGS-1906 likely caused by something in this list: https://sippy.dptools.openshift.org/sippy-ng/release/4.12/tags/4.12.0-0.ci-2022-09-29-133725/pull_requests
Workers are upgrading and rebooting fine, but one master attempts it's reboot, then never comes back. No other masters are attempted. Serial console looks ok.
=> Revert "RFE-2962: configure ovs should use node-ip-hint set by nodeip-configuration service"

templates/common/_base/units/nodeip-configuration.service.yaml
Per the design discussed in
https://github.com/openshift/enhancements/pull/1179 we are going to use this hint variable for more than just Kubelet IP selection, so it makes more sense for it to have a non-service-specific name.
This changes the variable reference so it will initially look for $NODEIP_HINT, and failing that it will fall back to the previous name $KUBELET_NODEIP_HINT. Note that the old name was never formally documented because it was only intended to be used in exceptional cases. This new name will be included in the official documentation, but we maintain compatibility with the old name to avoid breaking existing users on upgrade.
Renamed KUBELET_NODEIP_HINT to NODEIP_HINT, while maintaining …
=> Rename KUBELET_NODEIP_HINT to just NODEIP_HINT

install/0000_90_machine-config-operator_01_prometheus-rules.yaml
For context, see https://github.com/openshift/cluster-monitoring-operator/pull/1784
=> MCO-371: metrics: aggregate os_image_url_override metric to avoid unbounded cardinality

templates/common/_base/files/configure-ovs-network.yaml, templates/common/_base/units/nodeip-configuration.service.yaml, templates/common/_base/units/ovs-configuration.service.yaml, templates/common/on-prem/units/nodeip-configuration.service.yaml
[RFE-2962](https://issues.redhat.com//browse/RFE-2962): configure ovs should use node-ip-hint set by nodeip-configuration
=> RFE-2962: configure ovs should use node-ip-hint set by nodeip-configuration

cmd/machine-config-controller/main.go, cmd/machine-config-controller/start.go, pkg/controller/bootstrap/bootstrap.go, pkg/controller/container-runtime-config/container_runtime_config_bootstrap_test.go, pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/container-runtime-config/helpers.go, test/e2e-bootstrap/bootstrap_test.go
CVE-2022-27652 describes how it's improper for container managers (And managers of processes) to configure a process's inheritable capabilities. However, for a long time, folks have relied on inheritable capabilities to give processes capabilities as non root (as kubernetes doesn't define a way to specify ambient capabilities).
To balance both use cases, cri-o introduced add_inheritable_capabilities in 1.25 to allow for users to opt-out of dropping the inheritable capabilites. Specify it here so clusters that upgrade retain the old behavior (adding them)
This was heavily adapted from 0c8e86938e06aea2d686ae950bb31b0f9b5bfc2d, so most credit goes to Qi
create a drop-in …
=> OCPBUGS-1939: Create a drop-in file for cri-o's add inheritable capabilities

pkg/daemon/rpm-ostree.go, pkg/daemon/update.go
daemon: Temporarily copy auth file with more open perms on FCOS
This works around an rpm-ostree regression
https://issues.redhat.com/browse/OKD-63
---
daemon: Temporarily `setenforce 0` for inplace update from container
In practice, we should ship a SELinux policy tweak that allows a transition
from `spc_t` -> `install_t` but for now I want to see if this works.
---
=> MCO-396: daemon: FCOS workaround, plus SELinux workaround

templates/common/_base/files/configure-ovs-network.yaml
configure-ovs.sh: Do not fail bonds where at least one slave comes up
If for any reason a bond slave does not come up, make sure to continue
network setup as long as there's at least another slave that can be
activated.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-1503
=> Jira OCPBUGS-1503: configure-ovs.sh: Do not fail bond with invalid slave device names

templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
The keepalived config template change for workers was missing from https://github.com/openshift/machine-config-operator/pull/3269. This adds it.
=> [on-prem]: Add missing bits for dual-stack ingress VIPs

pkg/daemon/osrelease.go, pkg/daemon/rpm-ostree.go
This adds the same workaround that was added to FCOS in `6ccdd574fad38fc7bc2de1e1913c9ade69ba6e55` to SCOS, too.
See: https://issues.redhat.com/browse/OKD-63
/cc @cgwalters
=> daemon: Temporarily copy auth file with more open perms on SCOS too

pkg/daemon/update.go
It seems like rpm-ostree wants to check the extensions repo if extensions/kernel are set even if they aren't changing as part of the update. 
I consider this a regression I introduced because the OS update check it is present in the "legacy OS" path. Sorry :(
=> OCPBUGS-2269: Upgrade failures and MCDPivotError Alert Firing on GCP realtime kernel

pkg/daemon/update.go, templates/common/_base/units/rpm-ostreed-proxy.service.yaml
The least invasive fix for ensuring we get the proxy setup in the unit.
Closes: https://issues.redhat.com/browse/OCPBUGS-2197
=> OCPBUGS-2197: OCPBUGS-2122: update: Inject proxy data for firstboot

templates/common/_base/files/configure-ovs-network.yaml
This PR cherry-picks a stream of fixes from 4.8 for configure-ovs which have been blocked for quite some time.
CARRY from 4.8 (things that were not picked from previous cherry picks):
* [configure-ovs: remove spaces from team config json](https://github.com/openshift/machine-config-operator/pull/3043/commits/079968d6531b0a386df021ff8d1279063c9402a0)
* [configure-ovs: don't clone mac address for br-ex ovs bridge](https://github.com/openshift/machine-config-operator/pull/3043/commits/dce098250a85e12a7593134cddcb0b4a0cb9f709)
CHERRY-PICKS from 4.8:
* [configure-ovs: Persist addr-gen-mode for ipv6 connections](https://github.com/openshift/machine-config-operator/pull/3043/commits/0a34865722705199ab3986c07dbec4a03a4ce615)
* [Improvements for configure-ovs …
=> [release-4.7] Bug 2069766: Improvements for configure-ovs script

pkg/daemon/update.go
We need the proxy environment set for the *podman* invocation, not the rpm-ostree invocation inside the container, which today just scrapes data out of the container image and doesn't itself fetch again.
When my initial attempt at this didn't work, I confused myself into thinking we need the proxy inside the container too, but we don't today.  (In the future, we might actually do the pull from there, so let's keep it)
The previous PR fixed proxy clusters for fresh installs; this should fix them for inplace upgrades from 4.11 too.
Closes: https://github.com/openshift/machine-config-operator/issues/3378
=> OCPBUGS-2197: update: Set proxy for inplace container update too

templates/common/_base/files/configure-ovs-network.yaml
When the physical device is configured through a profile generated from
kernel arguments, this profile is activated with initrd and prevents
ovs-if-phys0 to activate on reboot.
Also, configure-ovs is not able to recover from this situation. Since
ovs-if-phys0 did not activate, then the original profile does not
re-activate when ovs-if-phys0 is removed and the default route is not
restored on the device after being moved to br-ex. configure-ovs does
not find a default route and fails.
So set autoconnect-slaves in br-ex and ovs-port-phys0 so that
ovs-if-phys0 is always activated when br-ex is activated.
Had to change the order of explicit activation to avoid transient
errors. This had the effect of activating ovs-if-phys0 before any
existing slaves. This could cause an implicit …
=> OCPBUGS-89: configure-ovs: auto-connect ovs-if-phys0 with br-ex

pkg/daemon/update.go
In OKD, the BaseOSExtensionsContainerImage image reference does not
exist. The change from https://github.com/openshift/machine-config-operator/commit/343475a40a3fe17f725ef4415333379ef3fd621b
broke OKD installations by trying to always extract the extensions from
the image during the initial rebase.
Fix this by making the daemon only try to extract the extensions when
the image-reference in not empty.
Without this, we're currently seeing:
```
Oct 20 21:37:52 ip-10-0-154-20 machine-config-daemon[1210]: I1020 21:37:52.841553    1210 run.go:19] Running: nice -- ionice -c 3 oc image extract --path /:/run/mco-extensions/os-extensions-content-3040886363 --registry-config /var/lib/kubelet/config.json
Oct 20 21:37:53 ip-10-0-154-20 machine-config-daemon[1210]: error: "" is not a …
```
=> daemon: Only try to apply layered changes if BaseOSExtensionsContainerImage is not empty

templates/master/00-master/on-prem/files/haproxy-haproxy.yaml, templates/master/00-master/on-prem/files/keepalived-keepalived.yaml, templates/master/00-master/on-prem/files/keepalived-script-both.yaml, templates/master/00-master/on-prem/files/keepalived-script.yaml
Keepalived was wrongly checking the status of the load-balanced
kube-apiserver, overstepping over HAProxy's responsibility.
Keepalived is responsible for moving the API VIP to a node where HAProxy
is functioning correctly. As a consequence, it should be checking for
the local HAProxy's readiness.
The previous check would make a request to the local API port, effectively
testing that the local HAProxy was correctly distributing traffic,
however, this check could fail if the selected API server was able to
handle the request, unnecessarily forcing a VIP failover.
This becomes important during recovery from an outage. When none of the
kube-apiservers are healthy this health check will fail continuously,
and the API VIP will move uselessly between masters. However the
situation is much worse …
=> OCPBUGS-1257: Have keepalived check for haproxy status for API VIP

pkg/daemon/update.go
This is part of a big mess in our control logic around the problem domain of "which is canonical: the machineconfig hash or the node state".
In the case of doing a manual `rpm-ostree rollback`, one will get "torn" state because the MCO will think it should be in config A, but we got reverted to config B (kind of, except for stuff in `/var`...).  Eventually the goal is to make
node state == container image
But, let's not error out if we're already in the expected container image in this case.
=> OCPBUGS-2757: Reconcile successfully if already booted into target

pkg/daemon/rpm-ostree.go, pkg/operator/sync.go
Operator was spamming every sync if the extensions container wasn't present in the `machine-config-osimageurl` configmap. This is okay now for the MCO because we've shipped the extensions container and it's always present, but things like OKD don't ship an extensions container so they would get a bunch of spam. 
```
W0923 14:37:41.798239       1 sync.go:886] New format image specified, but no matching extensions image present
W0923 14:38:39.329934       1 sync.go:886] New format image specified, but no matching extensions image present
W0923 14:38:44.497008       1 sync.go:886] New format image specified, but no matching extensions image present
```
=> Fix machine-config-operator logspam when extensions container is not present

pkg/operator/sync.go
This adds a conditional "safety controllerconfig-only sync" to the `machine-config-operator` so that `controllerconfig` will continue to sync in clusters where a daemon rollout cannot be completed (e.g. someone makes a proxy change with unavailable nodes). 
- This obviously only helps when the number of unavailable nodes is < maxUnavailable (otherwise the new config wouldn't get rolled out anyway), but that's generally been the case for customers who have hit this
- This does not help us during an upgrade because we need the new controller to process the new controllerconfig, but it helps us everywhere else 
- This is a stopgap until we can figure out how we want to refactor these sync dependencies, which will take significantly more time 
How I tested it: 
1. shutdown a node
2. push a …
=> Bug 2034883: Sync controllerconfig anyway if daemon sync fails

pkg/daemon/update.go
The semantics here will create a permanent reboot loop, which caused a lot of confusion in support case 03304353
The force file was intended as a last ditch *manual* thing; adding it via MachineConfig will just create a reboot loop.
=> controller: Don't allow creating the force file via MachineConfig

pkg/daemon/daemon.go
Ran across this accidentally while trying to reproduce a different issue, we're outputting unreadable bytes right now :) 
```
I1027 19:17:02.068070    2294 update.go:2106] Starting to manage node: ip-10-0-188-48.us-west-1.compute.internal
I1027 19:17:02.074272    2294 rpm-ostree.go:417] Running captured: rpm-ostree status
I1027 19:17:02.107054    2294 daemon.go:1303] [83 116 97 116 101 58 32 105 100 108 101 10 68 101 112 108 111 121 109 101 110 116 115 58 10 42 32 111 115 116 114 101 101 45 117 110 118 101 114 105 102 105 101 100 45 114 101 103 105 115 116 114 121 58 113 117 97 121 46 105 111 47 111 112 101 110 115 104 105 102 116 45 114 101 108 101 97 115 101 45 100 101 118 47 111 99 112 45 118 52 46 48 45 97 114 116 45 100 101 118 64 115 104 97 50 53 54 58 100 49 54 101 51 101 51 49 100 …
```
=> Force string format when logging rpm-ostree status

pkg/daemon/daemon.go, pkg/daemon/rpm-ostree.go
The problem: 
- While checking the format of the `osImageURL` image, we were getting stuck in exponential backoff in podman for minutes trying to pull/inspect an image that could never be pulled/inspected. 
- We did 2 tries on `imageInspect`, then we'd try 6 exponential backoff tries on `podman`, and only then would we degrade (minutes later) 
This PR:
- drops the "podman fallback" in `isBootableImage` and switches to using `skopeo` directly now that we have the `--no-tags` argument
- farms the exponential backoff/retry out to skopeo since it understands the error codes and will only retry if it's a "retryable" error (e.g. network timeout) 
Concerns: 
- If we'd rather do this the "code way" instead of the "shell out to skopeo way", I have that code too, but I'd need drag in more pieces of …
=> OCPBUGS-1761: Substitute skopeo inspect for imageInspect/podman, drop podman inspect fallback

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
If resolv.conf gets populated after NetworkManager has attempted to
do a reverse lookup on the node IP to get the hostname, we can end
up with a hostname of localhost because the lookup has no DNS servers
to use. To avoid this possibility, use "nmcli general reload dns-rc"
to force NetworkManager to redo the lookup.
Reload NetworkManager after populating resolv.conf so the node hostname is set correctly.
=> [release-4.10] Bug 2069754: [on-prem] Add NetworkManager reload to resolv-prepender

pkg/daemon/daemon.go, pkg/daemon/rpm-ostree.go
This reverts commit 08831f071793fd0d25462744b768a8253b7ac96d.
skopeo gained --no-tags option recently, older RHCOS node may not have this feature causing upgrade/node scale-up to fail.
Fixes: OCPBUGS-3621
=> OCPBUGS-3621: Revert "Substitute skopeo inspect for imageInspect/podman"

pkg/daemon/controlplane.go, pkg/daemon/coreos.go, pkg/daemon/update.go
This apparently provoked a kernel bug and caused a lockup.  Previously we did the BFQ work as a way to try to preserve fairness and avoid etcd disruption during in-place OS updates.
But from my point of view that was a total failure, and dynamically switching to a non-default I/O scheduler is just asking to provoke bugs.
The move to layering will help with OS updates because we now start only pulling and writing to disk something much closer to *what actually changed*.
The previous OS update path of pulling a single giant image to the container storage, then writing it to the host, then deleting it involves a lot more I/O and disruption.
=> OCPBUGS-2935: daemon: Stop setting I/O scheduler to bfq

templates/common/_base/files/configure-ovs-network.yaml
RHEL7 uses iproute2 4.11 which does not support json output which was available from iproute2 4.14. This prevents scaling up with RHEL nodes. Resort back to parsing normal iproute2 output with grep.
=> [release-4.9] OCPBUGS-3200: configure-ovs: avoid using 'ip -j' unavailable in RHEL7

templates/master/00-master/on-prem/files/keepalived-script-both.yaml, templates/master/00-master/on-prem/files/keepalived-script.yaml
The haproxy health check is not an https endpoint and calling it with https always fails. This is causing our loadbalancer to misbehave because we're relying entirely on the localhost healthcheck, which causes unnecessary failover.
Fixed a bug in the keepalived healthcheck that was causing it to always fail.
=> OCPBUGS-3508: Don't make https call to http endpoint

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Ideally, we would like to pull required images
before resolv prepender but this doesnt seem to
be possible.
NM dispatcher has a timeout value which isn't
being respected. This PR fixes this.
If required image is already available, do not
attempt to pull the image.
If not, pull required image in background and
never allow SIGTERM to be sent to the podman
pull process in order not to encounter image
corruption issue.
Signed-off-by: Martin Kennelly <mkennell@redhat.com>
=> [release-4.12] OCPBUGS-3504: On-prem: Ensure resolv-prepender respects NM dispatcher timeout

templates/common/_base/files/configure-ovs-network.yaml
RHEL7 uses iproute2 4.11 which does not support json output which was available from iproute2 4.14. This prevents scaling up with RHEL nodes. Resort back to parsing normal iproute2 output with grep.
=> [release-4.8] OCPBUGS-3201: avoid using 'ip -j' as it is unavailable in RHEL7

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
Fix bash script syntax to make OKD branch pass as correctly.
Bug was introduced in #3394
=> OCPBUGS-4039: NM resolve prepender: remove extra quotes in OKD flow

templates/common/_base/files/sysctl-arp.conf.yaml, templates/common/_base/files/sysctl-vm-max-map.conf.yaml
Add two files to templates/common/_base/files for setting sysctls vm.max_map_count and net.ipv4.all.arp_announce.
In OpenShift 4.13 we are planning to make the Node Tuning Operator an optional feature (composable OCP). Two sysctls currently set by NTO are needed for functional reasons, and should be set even in clusters where NTO is disabled.
vm.max_map_count=262144 is needed for OpenShift Logging to work (ElasticSearch), see [RH BZ#1793714](https://bugzilla.redhat.com/show_bug.cgi?id=1793714).
net.ipv4.conf.all.arp_announce=2 is needed for the OpenShift SDN (see [RH BZ#1758552](https://bugzilla.redhat.com/show_bug.cgi?id=1758552)).
NTO will remain enabled by default and will continue to apply recommended default tunings to improve scalability and performance, while …
=> Add templates for required sysctls max_map_count and arp_announce

go.mod, go.sum, pkg/daemon/daemon.go, pkg/daemon/image-inspect.go, pkg/daemon/rpm-ostree.go, vendor/github.com/containers/common/LICENSE, vendor/github.com/containers/common/pkg/retry/retry.go, vendor/github.com/containers/common/pkg/retry/retry_linux.go, vendor/github.com/containers/common/pkg/retry/retry_unsupported.go, vendor/github.com/coreos/go-systemd/v22/unit/escape.go, vendor/modules.txt
https://github.com/openshift/machine-config-operator/pull/3390 didn't take into account the "old bootimages" case, which of course would not contain a newer skopeo that supported the `--no-tags` argument
This: 
- removes the podman inspect fallback
- uses the retry package from github.com/containers/common/ for ImageInspect
- should give us the same behavior as https://github.com/openshift/machine-config-operator/pull/3390 but without the "old bootimages" issues where a too-old skopeo is called with the `--no-tags` argument
- ~~is maybe an alternative to https://github.com/openshift/machine-config-operator/pull/3412 ?~~
=> OCPBUGS-1761: Imageinspect takes type of error into account, drop podman inspect fallback

templates/common/vsphere/files/vsphere-hostname.yaml, templates/common/vsphere/units/vsphere-hostname.service.yaml
Instead of checking that `/etc/hostname` exists `vsphere-hostname` service should verify that the hostname is set, meaning the file is not empty. Starting from Fedora 37 an empty hostname file is created.
This also removes condition to start `vsphere-hostname` and allow indefinite retries
Run OKD 4.12 on vsphere, ensure that workers join the cluster on CI
Update `vsphere-hostname` service check that the hostname is set
Closes https://issues.redhat.com/browse/OKD-91
=> OCPBUGS-4656: vsphere: check that /etc/hostname is not empty

docs/README.md, docs/UsingLayering.md
We enabled `OSImageURL` overrides for 4.12 as part of layering phase 0, but it wasn't immediately straightforward how one might use it. 
This just adds: 
- some instructions for overriding `OSImageURL` with a layered image that has been built outside the cluster 
- details some of the consequences/tradeoffs/caveats/limitations of doing so.
The goal here is just something succinct we can point people at that answers the question "how can I use layering and what do I need to know if I do?"
=> MCO-397: Add repo doc for using "Layering Phase 0", detail some of the tradeoffs/consequences/questions

install/0000_90_machine-config-operator_01_prometheus-rules.yaml, pkg/daemon/metrics.go, pkg/daemon/update.go
Metrics shouldn't log failure, that should be done by logs Rename metrics name to match with metric type being used i.e Counter: ssh_accessed->  ssh_accessed_total
mcd_pivot_err -> mcd_pivot_err_total
mcd_reboot_err -> mcd_reboot_err_total
Followup of PR- https://github.com/openshift/machine-config-operator/pull/2394/ Metric types- https://prometheus.io/docs/concepts/metric_types/ Metric naming-  https://prometheus.io/docs/practices/naming/
Co-authored-by: Kirsten Garrison <kikis.github@gmail.com>
=> Bug 1853264: Fix unbound cardinality for MCDRebootErr and MCDPivotErr

pkg/controller/kubelet-config/helpers.go, templates/common/_base/files/kubelet-auto-sizing.yaml
Fixes: https://issues.redhat.com/browse/OCPBUGS-4101
Make sure none of the system reserved values end up empty and make kubelet crash during startup. 
```
metadata:
name: system1-reserved-config
spec:
matchLabels:
kubeletConfig:
systemReserved:
cpu: 500m
memory: 1500Mi
ephemeral-storage: "" 
```
Even after deploying that MC, the kubelet should start up and come up with default value of the ephemeral storage for system reserved (1Gi)
Force default values of system reserved in case empty values were supplied.
=> OCPBUGS-4101: Do not allow empty system reserved values

cmd/machine-config-controller/start.go, cmd/machine-config-daemon/start.go, install/0000_90_machine-config-operator_01_prometheus-rules.yaml, pkg/controller/common/metrics.go, pkg/controller/drain/drain_controller.go, pkg/daemon/daemon.go, pkg/daemon/drain.go, pkg/daemon/metrics.go, pkg/daemon/update.go, pkg/daemon/writer.go
This PR does the following:
- Consolidates duplicate code between the `pkg/controller/common/metrics.go` and `pkg/daemon/metrics.go` files.
- Makes the Prometheus metrics for the MCD private to the `daemon` package since they're not used elsewhere.
- Renames `MCDDrainErr` to `MCCDrainErr` and migrates it to `pkg/controller/common/metrics.go`.
- Refactors drain controller logic by extracting the drain code into a separate function for clarity.
- Adds MCCDrainErr to the refactored drain node logic.
TBD
Rename MCDDrainErr to MCCDrainErr and move into drain controller
=> MCO-420: Migrate drain alert to drain controller

install/0000_90_machine-config-operator_01_prometheus-rules.yaml
The broken URIs were originally from 2c44c12c (#2802)
=> OCPBUGS-5001: install/0000_90_machine-config-operator_01_prometheus-rules: Fix MachineConfigControllerPausedPoolKubeletCA runbook URIs

pkg/operator/sync.go
The kube-apiserver publishes this configmap. It also publishes one for general delegated authenticaiton consumption, but that won't function when the kube-apiserver is unavailable and these files will still exist.
This should fix https://issues.redhat.com/browse/OCPBUGS-4521.
We need be sure the kubelet doesn't get restarted. This file is auto-reloaded by the generic apiserver package for the last couple years.
/assign @rphillips
/cc @simonpasquier
=> OCPBUGS-4521: kubelet client certificate verification ca bundle should match kube-apiserver

Makefile, hack/test-unit.sh
When unit tests run and encounter a failure, they should exit with a non-zero
exit code so the CI system marks the whole job as "FAILED". This fixes that
behavior which was broken in
https://github.com/openshift/machine-config-operator/pull/3428.
Create a purposely-failing test, commit, and push it. Ensure that the OpenShift
CI system marks the job as "FAILED".
Ensures unit test failures cause a failing CI job
=> fix unit test exit code propagation

install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Avoiding the `machine-config-controller-xxxxx` from c90d7e4001 (#3169), so users don't need to manually replace a pod-name placeholder.
Moving to a label selector also automatically gets us `--tail=10` limiting, so we aren't flooded by old history:
```console
$ oc logs --help | grep -A1 tail
--tail=-1:
Lines of recent log file to display. Defaults to -1 with no selector, showing all log lines otherwise 10, if a selector is provided.
```
That limiting might remove older `Cannot evict pod ...` messages, but the `-f`/`--follow` means that if there's still a problem, we'll get a fresh log complaining about it soon.
=> install/0000_90_machine-config-operator_01_prometheus-rules: Use labels for MCC logs

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
This PR changes the logic of executing `podman pull` inside the NM
resolv-prepender by wrapping it in a while loop.
It has been observed that in some scenarios, when network is not yet
ready when the prepender script is executed, image may not be pulled
correctly. This ultimately can lead to a scenario when the node being
installed never pivots correctly causing the OCP installation to fail.
Fixes: OCPBUGS-5872
=> OCPBUGS-5872: Wrap podman commands in a while loop

Makefile, test/e2e/mcd_test.go
- I added a shell option onto each of the e2e tests that ensures that the Makefile step exits with the appropriate error code whenever a failure occurs.
- Because the e2e tests were failing to a timeout, I've increased the timeout for the `go test` command.
- I've removed redundant test iterations from the e2e test suite which were taking ~12 minutes per iteration to execute with no discernible benefit provided.
Write a failing test and run it.
Fix e2e test jobs and adjust timeouts
=> MCO-456: Fix e2e test jobs

pkg/daemon/update.go
OCPBUGS-5379: There are not enough logs in case "oc extract" is stuck in mco first boot
Added more verbosity for ox extract command
check logs of any installation
=> OCPBUGS-5379: There are not enough logs in case "oc extract" is stuck in mco first boot

install/0000_90_machine-config-operator_01_prometheus-rules.yaml
Added namespace=openshift-machine-config-operator for all 8 MCO specific alerts as referenced by styleguide [here](https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#style-guide). This will show up in the webview under Observe/Alerting and is also viewable using  amtool/oc CLI. 
Using amtool(filtered via the MCO namespace):
```
$ oc rsh -n openshift-monitoring alertmanager-main-0 amtool alert query namespace="openshift-machine-config-operator" --output=json --alertmanager.url http://localhost:9093
[{"annotations":{"message":"Reboot failed on  , update may be blocked. For more details:  oc logs -f -n   -c machine-config-daemon "},"endsAt":"2023-01-18T16:28:06.849Z","fingerprint":"3a7aa61f63da9f8b","receivers":[{"name":"Crit …
```
=> OCPBUGS-904: Alerts from MCO are missing namespace

manifests/bootstrap-pod-v2.yaml, manifests/machineconfigdaemon/daemonset.yaml, manifests/on-prem/coredns.yaml, manifests/on-prem/keepalived.yaml
Make MCO's privileged pods specify `readOnlyRootFilesystem: false` as part of the securityContext so they will no longer end up matched with "too restrictive" Security Context Constraints (SCCs) on clusters with custom SCCs.
We can't really control what SCCs people set up, and we've had enough folks hit this that we should fix it. 
This should be completely safe, and should have no real effect whatsoever on a cluster with standard/non-custom SCCs, because the default "privileged" SCC our pods get assigned already comes with `readOnlyRootFilesystem: false` : 
```
[jkyros@jkyros-t590 cluster]$ oc get scc privileged
NAME         PRIV   CAPS    SELINUX    RUNASUSER   FSGROUP    SUPGROUP   PRIORITY     READONLYROOTFS   VOLUMES
privileged   true   ["*"]   RunAsAny   RunAsAny    RunAsAny …
```
=> Bug 2113973: Avoid 'too restrictive' SCC problems by being more explicit

cmd/machine-config-controller/start.go, docs/MachineConfigDaemon.md, go.mod, go.sum, manifests/machineconfigcontroller/clusterrole.yaml, pkg/controller/bootstrap/bootstrap.go, pkg/controller/bootstrap/testdata/bootstrap/image-content-source-policy-0.yaml, pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/container-runtime-config/helpers.go, pkg/controller/container-runtime-config/helpers_test.go, pkg/daemon/drain.go, pkg/daemon/drain_test.go, test/e2e-bootstrap/bootstrap_test.go, test/e2e/ctrcfg_test.go, vendor/github.com/openshift/runtime-utils/pkg/registries/registries.go, vendor/modules.txt
- Add support for ImageDigestMirrorSet,ImageDigestMirrorSet mirror configuration CRDs.
- Reject the update of one of current icsp and new idms.itms resources if both exist to avoid having both icsp and new CRs on the same cluster.
Close card: https://issues.redhat.com/browse/OCPNODE-553
Epic: https://issues.redhat.com/browse/OCPNODE-521 
Dependent PR: https://github.com/openshift/runtime-utils/pull/15
Apply following CR, check the /etc/containers/registries.conf
```
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
name: tag-mirror
spec:
imageTagMirrors:
- mirrors:
- example.io/example/ubi-minimal 
source: registry.access.redhat.com/ubi8/ubi-minimal
- mirrors:
- example.io/example/ubi-minimal 
source: …
```
=> [OCPNODE-553] Add CRD ImageDigestMirrorSet,ImageTagMirrorSet

pkg/controller/bootstrap/bootstrap.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_features.go, pkg/controller/kubelet-config/kubelet_config_nodes.go, pkg/controller/kubelet-config/kubelet_config_nodes_test.go, test/e2e-bootstrap/bootstrap_test.go, test/e2e/kubeletcfg_test.go, test/framework/envtest.go
1. The CGroups version on an OCP cluster can be altered by altering the `nodes.config` resource's `spec.cgroupMode` field
2. It is very likely that the CGroups version would be defaulting to "v2" starting from OCP-4.13([RHEL-9](https://issues.redhat.com//browse/RHEL-9)) on the underlying RHCOS nodes.
3. To avoid unexpected complications, this code explicitly sets the CGroups version to "v1" on the newer OCP-4.13 versions
4. Also improved the bootstrap test cases, fixed a corner case issue
Signed-off-by: Sai Ramesh Vanka <svanka@redhat.com>
Added code to explicitly set the `cgroupMode` to "v1", if found empty, in the newer OCP clusters(4.13)
1. Deploy an OCP cluster (version = 4.13)
2. Debug into any of the nodes and observe the `CGroupsV1` …
=> OCPNODE-1330: Set the CGroups version explicitly to "v1"

go.mod, go.sum, pkg/controller/template/render_test.go, vendor/github.com/openshift/library-go/pkg/cloudprovider/external.go, vendor/github.com/openshift/library-go/pkg/crypto/OWNERS, vendor/github.com/openshift/library-go/pkg/crypto/crypto.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go, vendor/modules.txt
Update library-go vendor to the latest/tip of master. `go mod tidy && go mod vendor`
This will move the vSphere cloud provider to external in all clusters, not just techpreview.
Spin up a vSphere nightly with the default featureset, the cluster should come up with uninitialized nodes, which the vSphere cloud provider will then initialize.
=> OCPCLOUD-1818: Bump library-go to move vSphere to external CCM

templates/common/_base/files/configure-ovs-network.yaml
`remove_ovn_bridge` function is idempotent, so there is no need to conditionally invoke it.
Add early exit in `convert_to_bridge` if unable to find the connection for the given interface. This should reduce the noise in case of error.
Signed-off-by: Andrea Panattoni <apanatto@redhat.com>
=> OCPBUGS-6092: Improvements for `configure-ovs.sh`

install/0000_90_machine-config-operator_01_prometheus-rules.yaml, pkg/controller/common/metrics.go, pkg/controller/drain/drain_controller.go
I adjusted the parameters for the MCCDrainErr since it was reporting the node
that the Drain Controller is running on; not the node that couldn't be drained.
This was reported in https://issues.redhat.com/browse/OCPBUGS-5188
Follow the replication instructions in the aforementioned bug.
MCCDrainErr should reference the affected node
=> OCPBUGS-5188: MCCDrainErr should reference the affected node

templates/common/_base/units/nodeip-configuration.service.yaml
depends on https://github.com/openshift/baremetal-runtimecfg/pull/215
Added network type param to nodeip-configuration service
Run any test
=> OCPBUGS-6004: Adding network type parameter to nodeip-configuration service

templates/master/00-master/on-prem/files/haproxy.yaml
Instead of using `oc get nodes` to make sure the deploy was correct. Use the same approach as others components.
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
=> OCPBUGS-3988: haproxy - use curl for validation

pkg/daemon/config_drift_monitor_test.go, pkg/daemon/file_writers.go, pkg/daemon/on_disk_validation.go, pkg/daemon/update.go, test/e2e-shared-tests/helpers.go, test/e2e-shared-tests/mcd_config_drift.go, test/helpers/helpers.go, test/helpers/utils.go
Fixes OCPBUGS-3909. The key here is to ignore the unit contents and file mode when it is masked. I also did a bit of refactoring to reuse the writeFiles and writeSystemdUnits code in the MCD to make this easier to reproduce.
The TestConfigDriftMonitor includes a new test fixture that will cause the test to fail without the implemented fix. There is also a new e2e test case for the Config Drift e2e Test Suite. So one can run either the unit test suite or the e2e suite (or both!). Additionally, to verify my other refactoring changes, the e2e-gcp-op test target should provide adequate coverage for that code.
Ignore file content and mode for masked systemd units (fixes OCPBUGS-3909)
=> OCPBUGS-3909: Don't validate contents and mode for masked units

templates/common/_base/files/configure-ovs-network.yaml
Add support to configure via environment variable NM_CONN_SET_PATH where
are the configured NM keyfiles to reside. This path can be either the NM
etc or run paths and the environment variable can be configured through
a systemd dropin.
Change configure-ovs to generate the keyfiles in the NM run directory.
Setting up configure-ovs to work with the NM run path makes the
configuration ephemeral so that on a reboot there is no need to rollback any
configuration which has been problematic in some complex network
configurations.
Having this as a environment configuration variable gives the flexibility
to backport this solution and give users a choice in older releases.
=> OCPBUGS-3612: configure-ovs: optionally generate configuration in /run

pkg/daemon/daemon.go
The "complete update" workflow in the daemon today is quite convoluted,
which can cause the daemon to never uncordon the node, if the first
attempt reaches the timeout.
This patch moves the storePendingState to the very end of update
completion, such that if the drain fails, we just start from the
beginning again.
This problem is mitigated in 4.11+ since the drain is conducted by the
controller, but in 4.10 and prior the MCD is still doing the
drain/uncordon. We should probably rework this logic entirely, but for
4.10, let's take the less risky/less effort route of just fixing the one
issue above.
The associated bug above is targetted towards master, so the verification
will fail. Since this fix is only required for 4.10 and prior, we could either
1. do some dummy clones
2. have someone …
=> [release-4.10] OCPBUGS-4830: daemon: gate done state on uncordon completion

templates/common/_base/units/machine-config-daemon-pull.service.yaml
This PR removes the `--quiet` flag from Podman operations so that we have ability to see error messages in case something fails. It has been observed that `podman pull` does not always succeed in the first attempt and while it is wrapped with `while` (so that the installation does not fail), by using `--quiet` we are not able to investigate why the attempt failed.
As we are modifying a systemd unit, the logs are going to be saved in the journald thus we are not creating a danger of polluting a random location with those logs.
=> Preserve logs from Podman executions

install/0000_90_machine-config-operator_01_prometheus-rules.yaml, pkg/daemon/metrics.go, pkg/daemon/update.go
- Changed mcd pivot error count to a prometheus gauge, allowing for resets
- on a successful pivot(or if a pivot wasn't necessary), we reset the pivot error count to 0
- adjusted the prometheus rule to be an absolute check with a `for:` expression. This will prevent transient changes.
To trigger this alert replace the rpm-ostree exec file in a worker node, following these steps:
```
$ mount -o remount,rw /usr
$ mv /usr/bin/rpm-ostree /usr/bin/rpm-ostree2
$ vi  /usr/bin/rpm-ostree
The content of the new rpm-ostree file should be:
#!/bin/bash
if [ "$1" == "rebase" ];
then
exit -1
else
/usr/bin/rpm-ostree2 $@
fi
exit $?
$ chmod +x  /usr/bin/rpm-ostree
```
Then, apply a new machineconfig that can cause a pivot. 
To clear the error:
```
$ mount -o …
```
=> OCPBUGS-5520: MCDPivotError alert fires due temporary transient failures 

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml, templates/common/on-prem/units/kubelet.service-wait-resolv.yaml
Not a clean cherry-pick of 1b97dcc2390e3f76f39dfc732c9124030c5f7c5e from 4.12
Needed to replace 2 lines with:
```
"{{ onPremPlatformAPIServerInternalIP . }}" \
"{{ onPremPlatformIngressIP . }}")
```
=> [release-4.11] OCPBUGS-3507: On-prem: Ensure resolv-prepender respects NM dispatcher timeout

install/0000_90_machine-config-operator_01_prometheus-rules.yaml, pkg/daemon/update.go
On reboot, MCD now goes into a loop that updates the metric counter on every timeout(5 minutes) & attempts to reboot again. The MCDRebootError alert rule sees the metric counter increase over time and stays latched past 15 minutes(..forever essentially). 
Follow reproduction rules from the [bug](https://issues.redhat.com/browse/OCPBUGS-5497) to block a reboot. Alert will appear 5 minutes after the first failed reboot attempt and should sustain until the node is rebooted. 
OCPBUGS-5497: daemon: added reboot reconciliation; counter for total reboot attempts
=> OCPBUGS-5497: MCDRebootError alarm disappears after 15 minutes

docs/ImageMirrorSetDesign.md
Follow up the PR: https://github.com/openshift/machine-config-operator/pull/3037  
Add the document to give examples of the new mirror configuration CRDs ImageDigestMirrorSet and ImageTagMirrorSet.
Add document for ImageDigestMirrorSet and ImageTagMirrorSet.
=> Add doc for IDMS and ITMS CRDs

pkg/daemon/file_writers.go
Fixed an assignment typo that caused user and group lookup values to be lost.
Follow reproduction instructions on the [bug](https://issues.redhat.com/browse/OCPBUGSM-37597) to create a new file with the core user. It should now assign the correct user and group names as expected.
OCPBUGSM-37597: daemon: Fixed uid/gid assignment typo
=> Bug 2027000: The user is ignored when we create a new file using a MachineConfig

templates/common/_base/files/configure-ovs-network.yaml
At some point in the mtu-migration development a configuration file was generated at /etc/cno/mtu-migration/config which was used as a flag to indicate to configure-ovs that a migration procedure was in progress. When that file was missing, it was assumed the migration procedure was over and configure-ovs did some cleaning on behalf of it.
But that changed and /etc/cno/mtu-migration/config is never set. That causes configure-ovs to remove mtu-migration information when the procedure is still in progress making it to fail.
However, this was not a problem for the CI job as it doesn't use the migration procedure as documented for the sake of saving limited time available to run CI jobs. The CI merges two steps of the procedure into one so that there is never a reboot while the procedure is …
=> OCPBUGS-7207: configure-ovs: fix mtu-migration cleanup

templates/common/on-prem/units/nodeip-configuration.service.yaml
[OPNET-133](https://issues.redhat.com//browse/OPNET-133): Enabling remote worker feature only for baremetal platform
Pass platform type to node-ip service
=> OPNET-133: Enabling remote worker feature only for baremetal platform

docs/ContainerRuntimeConfigDesign.md, docs/HACKING.md, docs/KubeletConfigDesign.md
Fix typos in docs/ContainerRuntimeConfigDesign.md, docs/KubeletConfigDesign.md
=> Fix typo in ctrcfg,kcfg docs

templates/master/00-master/on-prem/files/keepalived-keepalived.yaml, templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Ensure that nodes that don't appear in the list of possible peers do not
participate in VRRP, as it would cause a split-brain scenario where
nodes would be fighting for the VIP.
Nodes that failed to register with the cluster but still participate in
VRRP believe they are the master (not receiving VRRP from other nodes),
and other nodes constantly re-electing a master, since they receive VRRP
from the rogue nodes claiming they own the VIP.
=> OCPBUGS-1565: Prevent possible split-brain scenario with keepalived unicast

templates/common/_base/files/configure-ovs-network.yaml
Switch from ifconfig to iproute2
Fixes:  https://issues.redhat.com/browse/OCPBUGS-6682
Signed-off-by: Michael Cambria <mcambria@redhat.com>
Switched command from ifconfig to iproute2 version 
Command is logged when vSphere system boots OVNK 
Change command used from ifconfig to iproute2 to plan for ifconfig deprecation and future RHEL9 support
=> OCPBUGS-6682: Switch from ifconfig to iproute2

pkg/daemon/update.go
[release-4.11]  OCPBUGS-5379: There are not enough logs in case "oc extract" is stuck in mco first boot in mco first boot
This is an manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3493
=> [release-4.11]  OCPBUGS-6002: There are not enough logs in case "oc extract" is stuck in mco first boot in mco first boot

templates/master/01-master-kubelet/vsphere/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/vsphere/units/kubelet.service.yaml
This PR modifies the kubelet systemd unit for vSphere platform so that in case of dual-stack networking we do not pass `--node-ip` parameter.
This change is part of onboarding vSphere platform to dual-stack networking but due to the fact that it's currently impossible to pass dual-stack IPs as `--node-ip` and to use `--cloud-provider` at the same time, we are using a temporary workaround that removes explicit node IP setting and lets kubelet pick it automatically.
This change will no longer be needed when the upstream enhancement https://github.com/kubernetes/enhancements/pull/3706 gets implemented, but currently seems like the most reasonable solution to enable such a setup.
This change creates a limitation that vSphere dual-stack cluster should be used only on a single NIC …
=> OPNET-197: Remove node-ip from kubelet for dual-stack vSphere

templates/master/01-master-kubelet/_base/files/kubelet.yaml, templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Enables protectKernelDefaults by default.
=> OCPNODE-1501: add protectKernelDefaults to kubelet config

pkg/controller/template/render.go
OCPBUGS-7896: MCO should not add keepalived pod manifests in case of VSPHERE UPI
Install vsphere upi and verify keepalived is not part of vsphere upi
=> OCPBUGS-7896: MCO should not add keepalived pod manifests in case of VSPHERE UPI

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml, templates/common/on-prem/files/resolv-prepender.yaml, templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
Previously the resolv.conf file generated by the prepender script
was owned by root with 600 permissions. This made it unreadable for
regular users and could cause some tools to fail.
After we generate resolv.conf, let's set the permissions to a more
normal 644 so regular users are able to read it.
=> OCPBUGS-7909: Fix permissions on resolv.conf

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml, templates/common/on-prem/files/resolv-prepender.yaml, templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
It turns out that doing potentially long-running operations such as image pulls in a dispatcher can be very problematic. If the image pull takes so long that the script times out, we end up with corrupt image files that require manual intervention to resolve. While we tried to address this by backgrounding the image pull in a previous commit, this proved ineffective. To avoid the timeout entirely, let's run the bulk of the script in a systemd service and only have the dispatcher script start the service. This should prevent it from being killed when the dispatcher script times out.
Moved resolv-prepender script to a systemd service to improve stability in slower network environments.
=> OCPBUGS-6624: Forklift most of resolv-prepender dispatcher script to systemd

manifests/controllerconfig.crd.yaml
Regenerate controllerconfig.crd.yaml to reflect
latest changes in the openshift infrastructure resource.
Outdated ControllerConfig CRD causes issues with using newly introduced platform types, such as `External`.
For example: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/36572/rehearse-36572-periodic-ci-openshift-release-master-nightly-4.13-e2e-vsphere-ovn-upi-platform-external/1627969406782935040
MCO is degraded with message: `Cluster not available for []: ControllerConfig.machineconfiguration.openshift.io "machine-config-controller" is invalid: spec.infra.spec.platformSpec.type: Unsupported value: "External": supported values: "", "AlibabaCloud", "AWS", "Azure", "BareMetal", "GCP", "Libvirt", "OpenStack", "None", "VSphere", "oVirt", "IBMCloud", …
=> Regenerate controllerconfig.crd.yaml

install/0000_80_machine-config-operator_01_machineconfig.crd.yaml, pkg/controller/common/helpers_test.go, pkg/daemon/update.go, pkg/daemon/update_test.go, test/e2e/mcd_test.go
Created a SetPasswordHash function to allow a user to create a password; MCD learns to make/update a password for the user core based on what is provided by MachineConfig.
Set a password for the user core by adding a machine config that specifies the password (following ignition format). Shell into the pod and log in as core (not from root, or the password option will not prompt), verifying that your password works.
SetPassword Hash allows users to create and update their password for core (password cannot be empty); edited verifyUserFields allows the user field verification if the password or ssh key exists.
=> MCO-417: MCO-418: MCD watches/create/update password with MachineConfig

pkg/daemon/daemon.go, pkg/daemon/update.go
Added a flag that indicated reboot is pending; when the flag is set we skip node syncs
I used a regular cluster and simulated a long reboots from happening with the following method. 
```
-On any node, do the following commands:
$ mount -o remount,rw /usr
$ mv /usr/bin/systemd-run /usr/bin/systemd-run2
$ vi  /usr/bin/systemd-run
#!/bin/bash
if [ "$2" == "machine-config-daemon-reboot" ];
then
exit 0
else
/usr/bin/systemd-run2 $@
fi
exit $?
$ chmod +x  /usr/bin/systemd-run
-Then, apply an MC that will cause a reboot.
```
This fake script returns a good value, so the daemon thinks that a reboot is queued. To undo, do a manual reboot and restore the old systemd-run binary.
OCPBUGS-7903:  daemon: Added no-op sync while …
=> OCPBUGS-7903:  Pool degraded with error: rpm-ostree kargs: signal: terminated

pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/kubelet-config/helpers.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_controller_test.go, pkg/controller/kubelet-config/kubelet_config_features.go, pkg/controller/kubelet-config/kubelet_config_features_test.go, pkg/controller/kubelet-config/kubelet_config_nodes.go, pkg/controller/kubelet-config/kubelet_config_nodes_test.go
https://github.com/openshift/machine-config-operator/pull/2570 was removed by https://github.com/openshift/machine-config-operator/pull/3149 and #3096. Add the #2570 back since the symptom it can fix may still happen.
Possibly the cluster hit bug https://bugzilla.redhat.com/show_bug.cgi?id=2041814 in 4.11, and upgrade to 4.12 that the cleanupDuplicateMC has been removed, so the problematic machineconfig from 4.11 still stayed and then 4.12 to 4.13 upgrade failed at the MC check https://github.com/openshift/machine-config-operator/pull/3501 .
Add cleanupDuplicateMC to delete unmanaged machinconfigs with generated-kubelet, generated-containerruntim suffix.
1. launch quay.io/openshift-release-dev/ocp-release:4.12.4-x86_64 
2. Add custom pool infra
3. …
=> OCPBUGS-7719: Add back cleanupDuplicateMC

pkg/apis/machineconfiguration.openshift.io/v1/types.go, pkg/operator/render.go, pkg/operator/render_test.go, templates/common/_base/units/nodeip-configuration.service.yaml, templates/common/on-prem/units/nodeip-configuration.service.yaml
In ipv6-primary dual stack clusters we need to pass --prefer-ipv6 to runtimecfg so it knows to select the ipv6 address as the primary node ip. This adds a new network type value for this case and the necessary logic to use it.
Add support for ipv6-primary dual stack clusters.
=> OPNET-208: Prefer ipv6 on v6-primary dual stack deployments

pkg/daemon/daemon.go, pkg/daemon/metrics.go, pkg/daemon/writer.go
Added a new function to clear old gauges in a gaugevec when we update them. `mcd_state` and `mcd_update_state` will both use this function. 
Trigger a state change orr a config change and observe the above metrics. They should set their value to None and no longer be tracked by the mcd after the change
OCPBUGS-1662: daemon: state metrics will clear old values when updated
=> OCPBUGS-1662: mcd_update_state metric should have a single time-series per node

pkg/controller/kubelet-config/kubelet_config_nodes.go, pkg/controller/kubelet-config/kubelet_config_nodes_test.go, pkg/controller/template/render.go, test/e2e-bootstrap/bootstrap_test.go, test/e2e/kubeletcfg_test.go
Node gets rebooted due to the creation of (`97-{master/worker}-generated-kubelet`) while explicitly setting the cgroups version to `"v1"`.
Moreover, in the future releases, if the cgroups version defaults to `"v2"`, on an upgrade, the above created MCs are not required. So, the `co/machine-config` gets degraded due to the presence of the unwanted `97-{master/worker}-generated-kubelet` MCs.
Following is the sample error log snippet due to the present of unwanted MCs.
```
I0222 16:30:59.551346       1 render_controller.go:377] Error syncing machineconfigpool worker: Ignoring MC 97-worker-generated-kubelet generated by older version f4c13d6e7004ec37f81fd28f4db3823f1d9b3b86 (my version: d4d98db75d7d3565db1b02bd4ce6a9daef4eca86)
I0222 16:31:00.074122       1 render_controller.go:377] Error …
```
=> OCPNODE-1495 : Default the cgroup version to "v1" via base template controller

templates/common/_base/files/configure-ovs-network.yaml
Retry configure_ovs until it succeeds.
By default, retry every 15 minutes to give enough time to gather
troubleshooting information in between. Note that configure_ovs has other
internal retry mechanisms. This retry is intended to give some
self-healing capabilities to temporary but not necessarily short-lived
infrastructure problems.
=> configure-ovs: permanent retry on failure

pkg/daemon/daemon.go
The whole reason we're doing the "state diff" here is so that we only log when transitioning.  This log message effectively prints the same thing every time we've done a sync, which adds noise to logs unnecessarily.  In this MCD pod log I'm looking at it ends with 163 instances of this.
=> daemon: Remove noisy log message

install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml
The semantics get a little confusing when one has e.g. 3 or more machine configs in play (by applying a new one while an update is in progress for example).  Let's clarify that we only reach spec == status when an update is 100% fully rolled out.  The term "current" here is too ambiguous.
=> machineconfigpool: Clarify `status.configuration` description

pkg/daemon/rpm-ostree.go
This reverts commit 6ccdd574fad38fc7bc2de1e1913c9ade69ba6e55.
Reverted one of commits introduced in #3358 to fix OKD-63. This workaround however breaks Assisted Installer flow, which runs `mcd start` on Live ISO where /var/lib/kubelet/config.json is not yet created.
Install OKD FCOS/SCOS
=> OCPBUGS-8523: Revert "daemon: Temporarily copy auth file with more open perms on FCOS"         

Dockerfile, cmd/machine-config-operator/bootstrap.go, docs/UsingLayering.md, install/0000_80_machine-config-operator_05_osimageurl.yaml, install/image-references, pkg/daemon/constants/constants.go, pkg/daemon/daemon.go, pkg/daemon/update.go, pkg/daemon/update_test.go, templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml, test/e2e-single-node/sno_mcd_test.go, test/e2e/mcd_test.go, test/helpers/utils.go
Forking from https://github.com/openshift/machine-config-operator/pull/3485
*This* version of the PR uses `rhel-coreos`, not `rhel-coreos-9` per discussion.
---
ensures that RHCOS 9 SSH keys are in the right place
---
OKD release controller is out-of-date
---
ensures SSH keys get moved to the correct location
When we move from RHCOS 8 -> RHCOS 9, the SSH keys are not being written
to the new location because:
1. When the upgrade configs are written to the node, it is still running RHCOS 8, so the keys are not being written to the new location.
2. The node reboots into RHCOS 9 to complete the upgrade.
3. The "are we on the latest config" functions detect that we are indeed on the latest config and so it does not attempt to perform an update.
---
teaches TestIgn3Cfg about the new RHCOS 9 …
=> Switch to rhel-coreos (9)

Dockerfile
We broke OKD, SCOS and the required okd-scos-images test when #3596 merged because our regexes no longer matched without the number. 
This can go in with something else, we just need to fix it :smile:
=> Make OKD/SCOS Dockerfile regexes match again after `rhel-coreos` image name change

pkg/daemon/update.go
This is followup to https://github.com/openshift/machine-config-operator/pull/3580 - we're fixing the case where deploying the RT kernel fails and we want to retry.
---
daemon: Move cleanup of pending deployment earlier
We hit a confusing failure in https://issues.redhat.com/browse/OCPBUGS-8113
where the MCD will get stuck if deploying the RT kernel fails, because
the switch to the RT kernel operates from the *booted* deployment
state, but by default rpm-ostree wants to operate from pending.
Move up the "cleanup pending deployment on failure" `defer` to
right before we do anything else.
---
daemon: Always remove pending deployment before we do updates
The RT kernel switch logic operates from the *booted* deployment,
not pending.  I had in my head that the MCO always cleaned up
pending, …
=> OCPBUGS-9685: daemon: Always remove pending deployment before we do updates

pkg/daemon/update.go
This fixes a regression with the previous commit
https://github.com/openshift/machine-config-operator/pull/3580/commits/8ac5beeddc331dd0186844d4714500d17454621d where we would simply fail to roll out on RT node systems any further MachineConfig changes.
Also of note: It seems like this (quite common thing) is actually not in our CI here nor in the periodics.
=> OCPBUGS-8113: daemon: Only switchkernel if we are doing an OS update or kernel change

pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/kubelet-config/helpers.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_controller_test.go, pkg/controller/kubelet-config/kubelet_config_features.go, pkg/controller/kubelet-config/kubelet_config_features_test.go, pkg/controller/kubelet-config/kubelet_config_nodes.go, pkg/controller/kubelet-config/kubelet_config_nodes_test.go
backport #3559 to 4.12
Add back https://github.com/openshift/machine-config-operator/pull/2570
=> OCPBUGS-8261: [release-4.12] backport cleanupDuplicateMC

Dockerfile, cmd/machine-config-operator/bootstrap.go, docs/UsingLayering.md, install/0000_80_machine-config-operator_05_osimageurl.yaml, install/image-references, pkg/daemon/constants/constants.go, pkg/daemon/daemon.go, pkg/daemon/update.go, pkg/daemon/update_test.go, templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml, test/e2e-single-node/sno_mcd_test.go, test/e2e/mcd_test.go, test/helpers/utils.go
This rolls together the following PRs:
- https://github.com/openshift/machine-config-operator/pull/3603
- https://github.com/openshift/machine-config-operator/pull/3601
- https://github.com/openshift/machine-config-operator/pull/3602
- https://github.com/openshift/machine-config-operator/pull/3597
---
daemon: Clean up `switchKernel` a bit
De-duplicate calls to `canonicalizeKernelType` to make the
logic easier to read.  Also add a few comments.
(cherry picked from commit b75c7afdbc8c6551dbdd9480faf484623fd20ceb)
---
vendor: Bump coreos/rpm-ostree-client-go
In prep for usage in MCD.
(cherry picked from commit cae67a648f4ee4250eab06c7fd09454160e8582e)
---
daemon: Make switchKernel less stateful
This is prep for fixing RHEL9 upgrades while maintaining `kernel-rt`.
Previously the …
=> COS-1926, MCO-116, OCPBUGS-8703, OCPBUGS-9951: rhel coreos 9 4.13 katamari

templates/common/aws/files/usr-local-bin-aws-kubelet-nodename.yaml, templates/common/aws/files/usr-local-bin-aws-kubelet-providerid.yaml, templates/common/aws/units/aws-kubelet-nodename.service.yaml, templates/common/aws/units/aws-kubelet-providerid.service.yaml
In older versions of OCP (4.1 specifically) boot image does not contain the afterburn service.
This causes instance provisioning issues within
clusters that use bootimages from OCP 4.1 and below.
This commit adds fallback logic into service scripts that try to communicate with IMDS via curl
if afterburn populated environment variables were not found.
Use bootimage from the OCP 4.1 for machine boot. Machine should come successfully.
For ocp 4.12+
1. Update user-data-secret for using ignition 2.2.0 
- ```oc -n openshift-machine-api get -o json secret worker-user-data | jq '.data.userData | @base64d | fromjson' | jq '.networkd = {} | .passwd = {} | .storage = {} | .systemd = {} | .ignition.version = "2.2.0" | …
```
=> OCPBUGS-7559: Remove hard requirement for the afterburn from early-running aws-related services

pkg/daemon/rpm-ostree.go
This reverts commit 6ccdd574fad38fc7bc2de1e1913c9ade69ba6e55. Cherry-pick of #3594 on release-4.12 branch
Reverted one of commits introduced in https://github.com/openshift/machine-config-operator/pull/3358 to fix OKD-63. This workaround however breaks Assisted Installer flow, which runs mcd start on Live ISO where /var/lib/kubelet/config.json is not yet created.
Install OKD FCOS/SCOS
=> [release-4.12] OCPBUGS-9993: Revert "daemon: Temporarily copy auth file with more open perms on FCOS"

pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/kubelet-config/helpers.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_controller_test.go, pkg/controller/kubelet-config/kubelet_config_features.go, pkg/controller/kubelet-config/kubelet_config_features_test.go, pkg/controller/kubelet-config/kubelet_config_nodes.go, pkg/controller/kubelet-config/kubelet_config_nodes_test.go
backport cleanupDuplicateMC #3559   to 4.11 and add new callers: nodes, featureGates handler
Add back https://github.com/openshift/machine-config-operator/pull/2570
=> OCPBUGS-8260: [release-4.11] backport cleanupDuplicateMC

pkg/daemon/update.go
This will fix using ancient bootimages that didn't have this option for `podman`.
xref https://issues.redhat.com/browse/OCPBUGS-9969
=> OCPBUGS-9969: daemon: Drop duplicate `--authfile` used in `run`

hack/test-unit.sh, test/e2e/osimageurl_override_test.go, test/helpers/utils.go, test/helpers/utils_test.go
This adds an OS image URL override test that ensures we can apply a custom OS
container to a cluster node which contains custom contents. This test assumes
that the image is prebuilt and pullable from someplace. There will need to be
some additional work done to the openshift/release repo to build the custom OS
image and inject the pullspec into the test.
Once the aforementioned openshift/release work is done, the
`TestOSImageURLOverride` test should pass. Until that work is done, this test
will be skipped.
Adds OS image URL override e2e test
=> MCO-423: Adds OS image override test

pkg/controller/node/node_controller.go
In getPoolsForNode, pool.Name == "worker" should use the constant, the same as for master.
=> getPoolsForNode: Use constant MachineConfigPoolWorker instead of "worker" string

templates/master/01-master-kubelet/_base/units/kubelet.service.yaml, templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml, templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
This PR changes conditional statement for dual-stack clusters from
```
{{- if eq .IPFamilies "DualStack"}}
```
into
```
{{- if or (eq .IPFamilies "DualStack") (eq .IPFamilies "DualStackIPv6Primary") }}
```
This is because by implementing IPv6-primary dual-stack support we have created a separate IPFamiliesType value for such clusters.
Fixes: OCPBUGS-8676
=> OCPBUGS-8676: Fix kubelet.service node-ip for v6-primary dual-stack

templates/common/_base/files/configure-ovs-network.yaml
In configuring VLANs, Network Manager setting `vlan.parent` can contain (a) the device which the virtual LAN is using or (b) a connection that holds the device.
In case of (b), if br-ex1 is built on top of a VLAN of the br-ex related connection (C), when br-ex1 connection is activated the target connection C is not active and a `Failed to find a compatible device for this connection` error is raised.
To solve this problem, the ovs-if-physX VLAN must be configured with the underlying device of C.
Support secondary bridge VLAN based on primary bridge connection.
=> OCPBUGS-10379: configure-ovs: support UUID in vlan.parent

templates/common/_base/files/NetworkManager-ipv6.conf.yaml, templates/common/on-prem/files/NetworkManager-onprem.conf.yaml
1. NetworkManager-onprem.conf.yaml will set unmanaged field as before and will do it only for onprem platforms as before
2. NetworkManager-ipv6.conf.yaml will set ipv6 flags for all platforms
=> OCPBUGS-10598: Splitting NetworkManager-onprem.conf.yaml to 2 files:

templates/common/_base/files/configure-ovs-network.yaml
configure-ovs would not retry if it exited due to a failed command.
From https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html:
If a compound command or shell function executes in a context where -e is being ignored, none of the commands executed within the compound command or function body will be affected by the -e setting, even if -e is set and a command returns a failure status.
So when we used `( configure_ovs "$@" ) || e=$?`, -e was being ignored within configure_ovs because it was followed by `|| ...`.
So just set -e within configure_ovs. Anything done outside should be simple enough that it should not really matter much.
=> configure-ovs: would not retry on some errors

templates/common/vsphere/units/nodeip-configuration-vsphere-upi.service.yaml
When the base nodeip-configuration service was added for UPI, the
vsphere platform was missed because it has a unique UPI configuration.
Instead of using platform None, it uses platform vsphere but does
not set the VIP fields. As a result, neither nodeip-configuration
service was enabled on that platform and multiple nic behavior is
problematic.
Because the _base nodeip-configuration service is overwritten by the
IPI version in the on-prem directory, we need a separate service for
VSphere UPI that can be enabled when platform is "VSphere" and the
API VIPs field is not set. This is the inverse logic to the one in
the on-prem directory, so only one will ever be enabled at a time.
Enabled the nodeip-configuration …
=> OCPBUGS-4963: Enable base nodeip-configuration for vsphere upi

pkg/daemon/config_drift_monitor_test.go, pkg/daemon/daemon.go, pkg/daemon/file_writers.go, pkg/daemon/update.go, pkg/daemon/update_test.go
We introduced the functionality for the daemon to always sync the kubelet CA cert contents, but this broke RHEL8 installs since those machines use a special daemon OnceFrom mode to write all the file content, and it wasn't getting the CA cert bundle anymore.
Add the ability to specify which type of update should or should not skip the certificate write, so RHEL8 and HyperShift are still functional under the new workflow.
=> OCPBUGS-11092: daemon: write certificate in OnceFrom and HyperShift

templates/common/on-prem/files/coredns-corefile.yaml
We are fixing an incorrect use of the dot in the coredns configuration file. Currently we are using simply a dot character (`.`) whereas we should be using a regex dot (`[.]`). With this change our coredns configuration is going to match only entries of a form `*.apps` and not `*apps`.
Closes: OCPBUGS-10414
=> OCPBUGS-10414: Fix regex dot in coredns config file

pkg/controller/container-runtime-config/helpers.go, pkg/controller/container-runtime-config/helpers_test.go
If the registry from image CR has three or more segments, do not add it to atomic transport.
fix: https://issues.redhat.com/browse/OCPBUGS-4122
=> OCPBUGS-4122: Do not add deep nested scope to atomic transport

manifests/controllerconfig.crd.yaml, pkg/apis/machineconfiguration.openshift.io/v1/types.go
I think `ServerSideFieldValidation` got turned on by default around kube 1.25/ OpenShift 4.12, which means we get additional schema validation now, and that validation apparently doesn't care for the metadata of the other CRD objects we embed in `ControllerConfig` (proxy,infra,dns) . The metadata fields are "special", and those embedded types aren't currently marked as embedded, so they aren't expected by default to have metadata. 
```
2022-12-13T23:11:51.511167249Z W1213 23:11:51.511120       1 warnings.go:70] unknown field "spec.dns.metadata.creationTimestamp"
2022-12-13T23:11:51.511167249Z W1213 23:11:51.511140       1 warnings.go:70] unknown field "spec.dns.metadata.generation"
2022-12-13T23:11:51.511167249Z W1213 23:11:51.511143       1 warnings.go:70] unknown field …
```
=> OCPBUGS-4877: End the operator's "unknown field" logspam by marking controllerconfig embedded fields as embedded so they validate

cmd/machine-config-daemon/start.go
Changed error handling so that runtime is not interrupted if kubeconfig gets moved or renamed
1. Remove / change the name of the file "/etc/kubernetes/kubeconfig"
2. Delete machine-config-daemon pod
3. inspect logs to see that there is no runtime error
=> OCPBUGS-5356: changed error handling so no runtime error

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml, templates/common/on-prem/files/resolv-prepender.yaml, templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
It turns out that doing potentially long-running operations such as image pulls in a dispatcher can be very problematic. If the image pull takes so long that the script times out, we end up with corrupt image files that require manual intervention to resolve. While we tried to address this by backgrounding the image pull in a previous commit, this proved ineffective. To avoid the timeout entirely, let's run the bulk of the script in a systemd service and only have the dispatcher script start the service. This should prevent it from being killed when the dispatcher script times out.
Moved resolv-prepender script to a systemd service to improve stability in slower network environments.
=> OCPBUGS-7945: [release-4.12] Forklift most of resolv-prepender dispatcher script to systemd

Dockerfile, Dockerfile.rhel7, cmd/machine-config-daemon/firstboot_complete_machineconfig.go, cmd/machine-config-daemon/start.go, pkg/daemon/daemon.go, pkg/daemon/osrelease/osrelease.go, templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
When upgrading rhel8 -> rhel9, some NIC names may change; e.g. the `mlx5` driver started emitting port information.
This breaks static IP addressing which references those interfaces.
We're going to land code in nmstate to address this; see https://github.com/nmstate/nmstate/pull/2301
- For a few reasons; one is that this isn't an OCP specific problem
- nmstate is in Rust
- nmstate already parses network interface information
- Adding more glue into the MCO is undesirable
However...to solve the bootstrap problem here in that we don't have this nmstate code on 4.12, add it to the MCD binary.
---
TESTING FLOW:
The true verification for this PR is:
- Install a 4.12 (RHEL 8) cluster on a machine that uses e.g. `mlx5` for ethernet with a _static IP address_
- Upgrade to a release image which …
=> OCPBUGS-10787: Persist static IP addressed NIC names from rhel8

Dockerfile, Dockerfile.rhel7
The downstream build pipeline parses bash in Dockerfile `RUN` commands in order to smooth over yum/dnf invocations that break downstream builds. For example, upstream Dockerfiles may use `--disablerepo`  /  `--enablerepo` / `microdnf` -- none of which will work as intended in brew/koji builds. 
The intent of this feature is to allow, to a reasonable extent, teams to use the same Dockerfile for upstream and downstream -- preventing the overhead of managing two nearly identical files.
When processing changes introduced by https://github.com/openshift/machine-config-operator/commit/c1f5e353969a8b4db33b9f4867be3b9fd37b2e5d , a limitation in the bashlex parser has been discovered where it cannot handle the (admittedly commonplace / proper) `[[ .. ]]` test syntax. 
Many OCP repos rely on this …
=> Accomodate ART limitation in parsing [[]] bash

templates/common/baremetal/files/NetworkManager-static-dhcpv6.yaml
properly quote DHCP IP6 ADDRESS variable in shell script
fixes https://issues.redhat.com/browse/OCPBUGS-10235
shell script error fix
=> OCPBUGS-10235:Add quotes to variable with -z

templates/master/00-master/alibabacloud/files/opt-libexec-openshift-alibabacloud-routes-sh.yaml, templates/master/00-master/alibabacloud/units/openshift-alibabacloud-routes.path.yaml, templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml, templates/master/00-master/azure/units/openshift-azure-routes.path.yaml
There was a [change](https://github.com/systemd/systemd/commit/708961c7011b7578d3e6e10ca463d15edb62b5c1) in systemd that re-checks the files watched with PathExistsGlob once the service finishes:
> With this commit, systemd rechecks all paths specs whenever the triggered unit deactivates. If any PathExists=, PathExistsGlob= or DirectoryNotEmpty= predicate passes, the triggered unit is reactivated
This means that openshift-azure-routes will get triggered all the time as long there are files in /run/cloud-routes.
Removed the PathExistsGlob, openshift-azure-routes.service will get
triggered with PathChanged=/run/cloud-routes every time apiserver-watcher
writes to a file in that directory.
Additionally improved logging to always log operations that change the iptables.
Second commit reverts …
=> OCPBUGS-11162:Do not trigger openshift-azure-routes/openshift-alibaba-routes service based on file existence

manifests/controllerconfig.crd.yaml, pkg/apis/machineconfiguration.openshift.io/v1/types.go
I introduced a regression in #3662 by tagging the controllerconfig's "proxy" field as an embedded resource. While it is "embedded" ( `*configv1.ProxyStatus`) , it is just the "status" portion of the proxy object, and it has no metadata (and thus will fail validation as an embedded resource). 
Removed the tagging of proxy as an embedded resource. Infra and DNS are still correct. 
Add a proxy, make sure controllerconfig still gets generated instead of a validation failure such as: 
```
2023-04-19T12:38:15.240508503Z E0419 12:38:15.240437 1 operator.go:342] ControllerConfig.machineconfiguration.openshift.io "machine-config-controller" is invalid: [spec.proxy.apiVersion: Required value: must not be empty, spec.proxy.kind: Required value: must not be …
```
=> OCPBUGS-11992: ControllerConfig's Proxy field should not be marked as embedded resource

pkg/daemon/rpm-ostree.go
In the case that we've already written the link, but there is no `/var/lib/kubelet/config.json`, we will try to re-create the link and fail.
I believe this can happen in the assisted installer path, and only if we end up re-trying an initialization.
https://issues.redhat.com/browse/OCPBUGS-12951
=> OCPBUGS-12951: daemon: Don't traverse `/run/ostree/auth.json` symlink

templates/master/01-master-kubelet/_base/files/kubelet.yaml, templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Fixed a duplicate featuregate key causing errors on the new 1.27 rebase.
=> OCPBUGS-12456: fix duplicate RotateKubeletServerCertificate setting

pkg/controller/drain/drain_controller.go, pkg/controller/node/node_controller.go
Added clean-up of any existing drain errors associated with a node during its deletion. Also changed the function to clear the drain error when a drain is complete, as `DeleteLabelValues(node.Name)` seemed like the right way to do this than `WithLabelValues(node.Name).Set(0)`
Trigger a drain error(this happens if a drain goes longer than an hour), and then delete the node. The drain error should disappear at node deletion. I manually set a drain error in the drain logic to test this, but if there's a faster way to do this let me know (: 
controller: improved MCCDrainError cleanup
=> OCPBUGS-11670: mcc_drain_err metric should not be served for removed nodes

templates/master/00-master/on-prem/files/keepalived-keepalived.yaml, templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
This is a cherry-pick of #3562. It did not backport cleanly due to the dual stack VIP changes between 4.11 and 4.12.
=> [release-4.11] OCPBUGS-11556: Prevent possible split-brain scenario with keepalived unicast

pkg/daemon/daemon.go
As a compatibility fix for IBM's use case. Should revisit the actual IBM workflow.
=> OCPBUGS-12980: daemon: write certs in firstboot-complete path

templates/master/01-master-kubelet/_base/files/kubelet.yaml, templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
Now that the `oc adm node-logs` feature has been upstreamed, enable the kubelet config flag introduced in 1.27 to allow the feature to work downstream.
=> OCPBUGS-11652: kubelet: add enableSystemLogQuery

cmd/machine-config-daemon/firstboot_complete_machineconfig.go, pkg/daemon/daemon.go, pkg/daemon/drain.go, pkg/daemon/kernelargs.go, pkg/daemon/update.go, templates/common/_base/units/machine-config-daemon-firstboot.service.yaml
Support for that switch was dropped.[[1]]
[1]: https://github.com/nmstate/nmstate/pull/2306
(And other minor prep patches split out of https://github.com/openshift/machine-config-operator/pull/3684.)
=> OCPBUGS-12885: daemon: stop using `nmstatectl persist-nic-names --inspect` on el9

cmd/machine-config-controller/main.go, cmd/machine-config-daemon/main.go, cmd/machine-config-operator/main.go, cmd/machine-config-operator/start.go, cmd/machine-config-server/main.go, install/0000_80_machine-config-operator_04_deployment.yaml, manifests/bootstrap-pod-v2.yaml, manifests/machineconfigcontroller/deployment.yaml, manifests/machineconfigdaemon/daemonset.yaml, manifests/machineconfigserver/daemonset.yaml, pkg/operator/operator.go, pkg/operator/render.go, pkg/operator/render_test.go, pkg/operator/sync.go, pkg/version/version.go, test/e2e-bootstrap/bootstrap_test.go
Adds a `--payload-version` flag to all the components in this repo (MCC, MCS, MCO, MCD) so that they consistently populate the release version into `version.ReleaseVersion`. The payload version is already used in MCO in a couple of places via env vars, so this includes a backwards compatible env var pre-population, but the intention is to remove that shortly (once the installer populates the flag for the bootstrap) and then the only, and consistent way to set the release version within the MCO suite would be via the flag. In code/tests it can be set via setting `version.ReleaseVersion`.
This should make the usage consistent across the codebase ahead of introducing feature gate changes on top of this.
Should be no functional changes, will want to …
=> OCPBUGS-13547: Use payload-version flag to set release version consistently across components

pkg/operator/sync.go
`Apiversion` and `Kind` fields on the Infrastructure object "go missing" once the Infrastructure object gets updated (due to cache/lister behavior), which causes validation errors when the MCO tries to embed the new Infrastructure in ControllerConfig.  
This PR makes sure the GVK (and by extension Apiversion/Kind) are always populated for our embedded infrastructure and dns resources so they will validate as embedded resources. 
Use the client scheme to inject the group, version, kind (GVK) back into the object so it gets explicitly included when we embed the object in ControllerConfig, allowing the embedded objects to validate. 
1. Mutate the the cluster infrastructure object harmlessly e.g. : `oc annotate infrastructure cluster break.the.mco=yep` …
=> OCPBUGS-13860: Fix missing apiVersion and kind fields for embedded resources

install/0000_90_machine-config-operator_01_prometheus-rules.yaml, pkg/controller/common/metrics.go, pkg/controller/node/node_controller.go, pkg/controller/node/node_controller_test.go
if a node specifies a custom label while already being a master node, the MCO should default to master similar to how we do with master,worker nodes. The label is retained but the pool selection of the custom label is not honored.
create a cluster, label master node as infra, push a custom mcp with a nodeSelector for this label, push a mc that updates a file to enqueue an update. `oc get mcp` should eventually list 3 nodes in worker and master pool rather than the current state which removes the node from all pools.
allow users to set custom labels on master nodes, deferring to the master pool rather than the custom pool if a custom mcp specifies the nodeSelector.
Signed-off-by: Charlie Doern <cdoern@redhat.com>
=> OCPBUGS-2177: MCO-634: add support for a node pool hierarchy

templates/common/_base/files/sysctl-userfaultfd.yaml
To implement post-copy migrations in OpenShift Virtualization (CNV), QEMU uses the userfaultfd system call.
lately this syscall was blocked by the kernel by default [[1](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2d5de004e009add27db76c5cdc9f1f7f7dc087e7)]. This effectively broke post-copy migrations.
Instead, there are three ways to grant permission to use userfaultfd [[1](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2d5de004e009add27db76c5cdc9f1f7f7dc087e7)]:
* By allowing unprivileged users to use it explicitly via sysctl
* By granting `CAP_SYS_PTRACE` capability to a process / container
* By exposing the `/dev/userfaultfd` to a container
This basically leaves us with two options:
1. Expose …
=> OCPBUGS-14793: Allow userfaultfd syscall to be used by unprivileged users

manifests/on-prem/keepalived.conf.tmpl, templates/master/00-master/on-prem/files/keepalived-keepalived.yaml, templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
With this change whenever keepalived adds an IP address to the interface, the IP will be explicitly labeled as "vip". This is in order for anyone relying on the output of `ip a` to be able to distinguish between the IP addresses configured by the network and IP addresses coming from keepalived.
Until now looking only at the output of `ip a` wasn't a reliable way of distinguishing host IP from VIP. There were heuristics possible like e.g. treating IP with /32 as VIP but those are not always as reliable as we would like (e.g. for IPv6 the mask /128 is used also by real host IP).
Contributes-to: OCPBUGS-4370
=> OCPBUGS-4370: Add label to VIP via keepalived

templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
Improve logging format of KNI haproxy logs to display tcplogs + frondend IP and frontend port.
The current logging format is not very verbose:
~~~
<134>Jun  2 22:54:02 haproxy[11]: Connect from ::1:42424 to ::1:9445 (main/TCP)
<134>Jun  2 22:54:04 haproxy[11]: Connect from ::1:42436 to ::1:9445 (main/TCP)
<134>Jun  2 22:54:04 haproxy[11]: Connect from ::1:42446 to ::1:9445 (main/TCP)
~~~
It lacks critical information for troubleshooting, such as load-balancing destination and timestamps. 
https://www.haproxy.com/blog/introduction-to-haproxy-logging recommends the following for tcp mode:
~~~
When in TCP mode, which is set by adding mode tcp, you should also add [option tcplog](https://www.haproxy.com/documentation/hapee/1-8r1/onepage/#option%20tcplog).
~~~
Because `option …
=> OCPBUGS-14612: Improve logging for IPI deployments

templates/common/openstack/files/ipv6-config.yaml
This commit makes sure the br-ex interface of masters and workers
consistently gets the same IPv6 and mac addresses that were configured
in the OpenStack Ports for the control plane and api/ingress VIPs by
including ipv6.addr-gen-mode with eui64 and method auto by default.
Partially implements: https://github.com/openshift/enhancements/pull/1365
=> OpenStack: configure ipv6 addresses

Dockerfile
The nmstate operator team wants to use newer nmstate in 4.13. We still
want an older nmstate because we use `--inspect` which is useful for
diagnostic purposes.
Until we replace it, just pin to the build of nmstate we need for our
purposes.
Related: https://github.com/openshift/machine-config-operator/pull/3706
=> OCPBUGS-13404,OCPBUGS-14298: Dockerfile: pin to nmstate-2.2.9-6.rhaos4.13.el8

cmd/machine-config-operator/bootstrap.go, pkg/operator/bootstrap.go
No code changes, just renaming the variable and adding a link to the official doc.
Part of https://issues.redhat.com/browse/MCO-642
=> bootstrap: Clarify that "root ca" is really "MCS CA"

pkg/daemon/daemon.go, pkg/daemon/update.go
Removed all references/checks for the journal pending config writes. In some cases, I replaced them with `desiredConfig` checks and in other cases removed them entirely. 
Upgrades tests should work without any *new* complaints (: 
daemon: removed pending config checks
=> MCO-595: Remove MCO's pending config workflow

pkg/controller/kubelet-config/helpers.go
"Fixes: https://issues.redhat.com/browse/OCPBUGS-14399"
Added a small workaround to support the `protectKernelDefaults` field of the Kubelet Config when user sets it to `false`
Apply the following kubeletconfig to the OCP cluster and observe that the same has been reflected in the /etc/kubernetes/kubelet.conf file of the worker nodes
```
metadata:
name: worker-protect-kernel-defaults
spec:
matchLabels:
kubeletConfig:
protectKernelDefaults: false
```
`protectKernelDefaults` is set to `true` in the OCP by default …
=> OCPBUGS-14399 : Minor fix to support `protectKernelDefaults` field in Kubelet Config

cmd/machine-config-controller/start.go, manifests/machineconfigcontroller/clusterrole.yaml, pkg/controller/node/node_controller.go, pkg/controller/node/node_controller_test.go, pkg/operator/sync.go, test/e2e-bootstrap/bootstrap_test.go
Added a new function called getOperatorNodeName() ~Fleshed out the findEtcdLeader stub~ in the controller that helps us queue control plane nodes for updates.  I'll do a subsequent commit for bumping the timeout, but want to run a few tests with the queuing in place first. 
controller: defer update of node running operator
=> OCPBUGS-4820: Controller version mismatch causing degradation during upgrades

docs/MachineConfigDaemon.md
The documentation references openshift-kubeapiserver operator, which should map to
https://github.com/openshift/cluster-kube-apiserver-operator. If you look in an OpenShift cluster for that namespace, it doesn't exist. This commit updates the documentation to use openshift-kube-apiserver, which is the namespace for the operator.
Update documentation to reference the proper namespace for the `openshift-kube-apiserver` operator.
=> trivial: Fix namespace for kube api server operator

install/0000_80_machine-config-operator_03_rbac.yaml, install/0000_80_machine-config-operator_04_deployment.yaml
create the new account, tombstone the old one, and update all references.
All tests should work the same as proof that this change does not impact functionality.
=> OCPBUGS-10924: Switch default SA to machine-config-operator

Dockerfile, Dockerfile.rhel7, templates/common/_base/units/machine-config-daemon-pull.service.yaml
While attempting to switch builder to rhel9 base, the nmstate binary from rhel9 fails. With that change reverted for now, this aims to build a separate MCD binary off the rhel9 builder, for the mcd-firstboot.service to use. This way, the image MCD runs on rhel8, and the host runs on rhel9, matching the on-disk OS version.
If any rhel8 nodes (non-rhcos) are present, I think it should have skipped this process, so that shouldn't be affected.
This is an alternative to https://github.com/openshift/machine-config-operator/pull/3758
=> 4.13: use rhel9 builder for daemon binary

Dockerfile, Dockerfile.rhel7
Embarrassingly, I was using the wrong image to build the rhel9 binary. Updating to the correct location.
=> 4.13: Dockerfile: use proper rhel9 image

install/0000_90_machine-config-operator_01_prometheus-rules.yaml
using message violates the style guide and therefore every instance where message is used should be switched to description.
This will also fix aws-ovn failures due to this invalid styling.
=> OCPBUGS-14185: change the message annotation to description

manifests/controllerconfig.crd.yaml, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/template/render.go, pkg/controller/template/render_test.go, pkg/controller/template/template_controller_test.go, pkg/controller/template/test_data/controller_config_external.yaml
We found two errors while installing the recently added platform type External in a non-integrated provider (OCI).
The machine-config operator is getting stuck with the following message:
~~~
$ oc get co machine-config
NAME             VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
machine-config             True        True          True       21h     Unable to apply 4.14.0-0.nightly-2023-06-27-233015: 
error during syncRequiredMachineConfigPools: [context deadline exceeded, failed to update clusteroperator:
[client rate limiter Wait returned an error: context deadline exceeded, error MachineConfigPool master 
is not ready, retrying. Status: (pool degraded: true total: 3, ready 0, updated: 0, unavailable: 3)]]
~~~
Errors:
1) External platform wasn't …
=> OCPBUGS-15728: Fix machine config drifts when deploying with platform external

Dockerfile.rhel7
Confusingly, this Dockerfile doesn't seem to be autogenerated, and is also what is using for ART builds.
Match the nmstate pin so we unbreak 4.13 builds.
=> OCPBUGS-15580: 4.13: Dockerfile: update rhel7 nmstate pin

install/0000_90_machine-config-operator_01_prometheus-rules.yaml, pkg/controller/common/metrics.go, pkg/controller/node/node_controller.go
set pool alert back to zero in more default scenarios.
this entails alerting users when only applying worker, master, or custom, or a combination
without these `.Set(0)` lines, the alert will be firing when it should not.
Also, change the metric to just log node name so the label is easier to track down and reset.
1. Create a custom MCP
kind: MachineConfigPool
metadata:
name: infra
spec:
machineConfigSelector:
matchExpressions:
- { key: machineconfiguration.openshift.io/role, operator: In, values: [master,infra] }
nodeSelector:
matchLabels:
node-role.kubernetes.io/infra: ""
2. Label a master node so that it is included in the new custom MCP
$ oc label node $( oc get nodes -l …
=> OCPBUGS-14674: set pool alert back to zero in more default scenarios.

templates/common/openstack/files/ipv6-config.yaml
The creation of a new connection profile affects installations
that are configured with additional networks resulting in wrong node-ip
selection. Let's restrict the IPv6 configuration for only dual-stack
clusters, which is what is supported at the moment to unblock other
testings that rely on additional networks.
Related to: https://issues.redhat.com/browse/OCPBUGS-15233
=> OpenStack: restrict IPv6 configuration

pkg/controller/common/helpers.go, pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/drain/drain_controller.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/node/node_controller.go, pkg/controller/render/render_controller.go, pkg/controller/render/render_controller_test.go, pkg/controller/template/template_controller.go, pkg/daemon/writer.go, pkg/operator/operator.go
events are namespaced resources.  When looking for events for an operator, it's natural to look in their operator or operand namespace.  The MCO manages many cluster-scoped resources.  Cluster-scoped  objectReferences in namespaces are placed into "default". This is bad for categorization, separation, quota, and later listing (too big to list).
This PR creates a shim to an eventrecorder to set a namespace of the MCO if nothing is specified ahead of time.
/assign @yuqi-zhang
=> set MCO namespace on all events

Dockerfile, Dockerfile.rhel7, templates/common/_base/units/machine-config-daemon-pull.service.yaml
This reverts commit ce6cadfb71ca0b3d958fe4f2f939f48c5406e2cf and
2619e1b0b41bf8c713e03de60ea8a11737c3c5b9 (the fixup). These introduced a
regression that causes bootimages on rhel8 to be broken.
To hopefully not break 4.13, we have decided revert some changes for 4.13 golang builder,
and work towards a better solution via https://issues.redhat.com/browse/OCPBUGS-16128
=> 4.13: Revert rhel9 binaries builds

templates/common/_base/files/usr-local-bin-mco-hostname.yaml
It has been discovered that in environments that use revDNS for setting the hostname instead of DHCP Option 12 it is possible to intermittently lose it and try to register as `localhost.localdomain`.
It happens in a scenario when we obtain the hostname from the DNS server (PTR record for the IP address of the node), later we lose DNS for any reason and during this time we reload the NM configuration. Because of its design, if the revDNS is not available anymore instead of persisting the previous name, NetworkManger will unset it completely leaving the node visible as `localhost.localdomain`.
In order to prevent this behaviour we are modifying `node-valid-hostname.service` so that instead of only waiting for the non-localhost name to appear once (without detecting if it can intermittently …
=> OCPBUGS-11997: Prevent NM from unsetting the hostname

pkg/controller/kubelet-config/kubelet_config_nodes.go, pkg/controller/kubelet-config/kubelet_config_nodes_test.go, test/e2e-bootstrap/bootstrap_test.go
- Future OCP releases will default to cgroupsv2
- During the upgrades, in order to honor the cgroupsv1 on the existing cluster, there should be a reference in the node spec for the future code to depend on deciding the cgroup version.
- Hence, this code updates the config node spec whenever the cgroupsv1 is explicitly set
=> OCPNODE-1717: Update config node spec while explicitly updating the cgroups mode

templates/common/openstack/files/ipv6-config.yaml
When using an additional network in the cluster, this network
would end up being considered as the node ip network, when in
fact the first network should be the one to be used. This happens
because at certain moment the addresses on the primary interface
are not available, which results node-ip selection based on the default route.
Using connection profile to configure IPv6 is causing this issue, so
this commit moves the `addr-gen-mode` configuration to the global config.
The `method` configuration is not needed anymore as is already the default one.
=> Bug OCPBUGS-15233: OpenStack: fix IPv6 configuration

templates/common/on-prem/files/keepalived-script-default-ingress.yaml
We have noticed that OCP 4.14 doesn't follow anymore the old pattern for Ingress default router pods, causing `router-default-97fb6b94c-wfxfk` to fail our check. As a consequence, keepalived is not deploying the ingress VIP to the node even if it holds the router pod.
This PR softens the check so that slight changes in the random suffix shouldn't cause us to miss the pod anymore.
Closes: OCPBUGS-15613
=> OCPBUGS-15613: Soften grep pattern for ingress default router

install/0000_80_machine-config-operator_04_deployment.yaml
xref https://issues.redhat.com/browse/MCO-642?focusedId=22410761&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22410761
As far as I can tell, the operator has actually never read this file.  It's only on the bootstrap path.
In fact, I believe this is dead code since
1f94f06b52ddf00ebc8377e1737a8fd68b4f357a
which dates to the very creation of OCP 4.
This is preparatory cleanup for adding support for rotation.
=> operator: Stop mounting /etc/kubernetes/ca.crt

OWNERS_ALIASES, templates/common/kubevirt/OWNERS, templates/common/kubevirt/files/001-nmstate-disable-ipv6-autoconf.yaml, templates/common/kubevirt/files/002-nmstate-arp-proxy-ipv6-gw.yaml
The live migration feature implemented at [1] creates a stable default
gw for IPv4 and IPv6, for IPv4 it's delivered using DHCPv4 but for IPv6
there is not support for routes at DHCPv6. This change harcoded the IPv6
stable default gw using ignition.
[1] ovn-org/ovn-kubernetes#3478
Add kubevirt configuration for disable ipv6 autoconf and add arp proxy ipv6 gw
=> kubevirt: Configure IPv6 arp proxy default gw

docs/MachineConfigDaemon.md, pkg/daemon/daemon.go, pkg/daemon/metrics.go, pkg/daemon/writer.go
Removed the unused SSH login monitor and related metrics. We put out a deprecation notice for this in 4.12. This is also part of our effort to make the MCO less dependent on journal reads. 
I ran the basics on my local cluster, but CI should ensure that this doesn't break any existing functionality. 
daemon: removed login monitor
=> MCO-596: Deprecate the login monitor

Dockerfile, Dockerfile.rhel7, Makefile, cmd/machine-config-daemon/firstboot_complete_machineconfig.go, cmd/machine-config-daemon/pivot.sh, cmd/machine-config-daemon/start.go, hack/build-go.sh, pkg/daemon/constants/constants.go, pkg/daemon/daemon.go, pkg/daemon/osrelease/osrelease.go, templates/common/_base/units/machine-config-daemon-firstboot.service.yaml, templates/common/_base/units/machine-config-daemon-pull.service.yaml
4.13: use rhel9 builder for daemon binary
While attempting to switch builder to rhel9 base, the nmstate binary from
rhel9 fails. With that change reverted for now, let's try just building
the daemon binary on rhel9, so when it gets copied to host for
firstboot, it matches the on-node os version (rhel9)
For https://issues.redhat.com/browse/TRT-1143
(walters: I also snuck in a cleanup to use `chcon --reference` here
because it avoids hardcoding a SELinux context)
---
build-sys: Drop setting CGO_ENABLED=0
We must dynamically link in general.
---
daemon: Run firstboot as a container image too
As the TODOs say, I am now no longer sure why we did the
"copy self to host" instead of always running from the container.
IOW, this makes firstboot work *exactly the same* as the daemonset
running after …
=> OCPBUGS-16128:  daemon: Copy matching binary to host, re-exec with it

templates/common/_base/files/configure-ovs-network.yaml
This change relates to the SNO relocation feature, it allows for preserving the statically configured internal IP on the br-ex in case the connection is configured with DHCP.
nmstate connection files allow configuring static IPs on an interface together with DHCP, see https://github.com/nmstate/nmstate/pull/2303 By cloning the existing connection file we should get both IPs (static and the one from DHCP) on the vr-ex bridge.
I updated ovs-configuration service to preserve static IP configured on the original connection if one is configured (regardless of the connection method)
I tested the resulted br-ex in cases where the original connection had:
1. a single address from DHCP (192.168.128.11), method=auto 
Result:
```
323: br-ex    inet …
```
=> MGMT-14843: ovs-configuration service should copy the statically configured address even if the method isn't manual.

pkg/daemon/daemon.go, pkg/daemon/rpm-ostree.go, pkg/daemon/update.go
This must be dead code in 4.14.  There's no going back.  Everything in 4.12 really should have transitioned, and certainly 4.13 and very much most definitely 4.14.
Deleting code is good on general principle, but very specifically this cost me hours of debugging because I modified the legacy update path when trying something, not the new one.
=> MCO MCO-424: daemon: Remove old legacy OS update path

install/0000_90_machine-config-operator_01_node_dashboard.yaml
Added a configmap that creates a node related dashboard
Install the cluster and observe a `node-cluster` configmap in the `openshift-config-managed` namespace.
Also find the `node-cluster` dashboard in the `Observe/Dashboards` section in the OCP UI
Added a configmap that installs a node-cluster dashboard that contains some useful information about the node related components.
=> OCPNODE-1655: Apply node-cluster dashboard as a config map

pkg/controller/kubelet-config/kubelet_config_nodes.go, pkg/controller/kubelet-config/kubelet_config_nodes_test.go, pkg/controller/template/render.go, test/e2e-bootstrap/bootstrap_test.go
1. RHCOS comes up with cgroupsv2 by default.
2. In order to make cgroupsv2 as a default in OCP-4.14, the changes that explicitly set the cgroupsv1 should be removed
3. With this change, all the new OCP clusters by default come up with cgroupsv2.
Make cgroupsv2 as a default in the newer OCP releases
Deploy OCP-4.14 and execute the following command on any node and observe the following
```
sh-4.4# stat -c %T -f /sys/fs/cgroup/
cgroup2fs
```
Remove the explicit setting of cgroupsv1 and make cgroupsv2 a default in OCP 4.14
=> OCPNODE-1717: Make cgroupsv2 default in OCP-4.14

Makefile, cmd/machine-os-builder/main.go, cmd/machine-os-builder/start.go, cmd/machine-os-builder/version.go, manifests/machineosbuilder/clusterrole.yaml, manifests/machineosbuilder/clusterrolebinding-anyuid.yaml, manifests/machineosbuilder/clusterrolebinding-service-account.yaml, manifests/machineosbuilder/deployment.yaml, manifests/machineosbuilder/events-clusterrole.yaml, manifests/machineosbuilder/events-rolebinding-default.yaml, manifests/machineosbuilder/events-rolebinding-target.yaml, manifests/machineosbuilder/sa.yaml, pkg/controller/common/constants.go, pkg/operator/operator.go, pkg/operator/sync.go, test/e2e/mob_test.go, test/helpers/utils.go
…ler with label
and rework Machine OS Builder startup logic
=> MCO-565: MCO-568: MCO-659: MCO-660 On-cluster build opt-in function, building machine-os-builder stub, RBAC and service acct inclusions

pkg/controller/common/helpers.go, pkg/daemon/update.go, pkg/server/api.go, pkg/server/server.go, test/e2e/mcd_test.go
This ensures that the first nodes always know about core, and the authorized ssh keys.
New nodes should get the full passwd config since it is now in the data the MCS serves via the appenders.
now, all machineConfigs should have the core user (even firstboot) and all scaled nodes should have a filled /home/core/.ssh/authorized_keys.d/ignition
=> OCPBUGS-16227: add Passwd to bootstrap served ignition

pkg/daemon/daemon.go
=> OCPBUGS-16888: daemon: no need to reexec when target and source rhel version is same

install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml
the certExpiry description is wrong, probably from copying the formatting from elsewhere.
=> fix certExpiry description

pkg/daemon/daemon.go
Removed a flag related to journal reads/writes that hasn't been used in a while. This should clean up all our journal dependencies, with the only exception being the boot listing done at daemon startup(which doesn't exit fatally, just errors and proceeds).
Tests should pass without any complaints, since this is dead code.
daemon: remove dead journal flag
=> MCO-597: Remove the MCO's dependency on journal reads

pkg/controller/common/helpers.go, pkg/daemon/update.go, pkg/server/api.go, pkg/server/server.go, test/e2e/mcd_test.go
Reverts openshift/machine-config-operator#3811, tracked by [TRT-1168](https://issues.redhat.com//browse/TRT-1168)
Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get nightly payloads flowing again.
Workers are failing to provision on the nightly hypershift job (see jira above for details). The first payload hypershift broke contains this PR https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2023-07-27-223709.   After testing this revert, hypershift is installing again so this broke something related to ignition and hypershift.
See our test of this revert here, which made it past install: …
=> Revert " add Passwd to bootstrap served ignition"

pkg/daemon/daemon.go, pkg/daemon/update.go
=> OCPBUGS-16921: daemon: Make binary writing idempotent

pkg/daemon/rpm-ostree.go, pkg/daemon/update.go
This code could have also been removed in
https://github.com/openshift/machine-config-operator/pull/3583/commits/85b297c1a063a7e130e82afb2fd2230ffd5c5fcc "daemon: Remove old legacy OS update path"
Beyond just removing dead code, a motivation is that calling `imageInspect()` which is trying to do out-of-band inspection of the booted image, which creates problems with fully-disconnected environments: https://issues.redhat.com/browse/RFE-4482
=> daemon: Remove even more dead legacy OS update code

pkg/daemon/daemon.go
These two things got lost in the conflict-fest of juggling two branches and an incoming revert.
=> daemon: Two minor fixes for reexec

pkg/daemon/update.go, test/e2e/mcd_test.go
re-implement fix for sshKeys without adding them to ignition passwd
I want to run tests on this to see what breaks and also run the hypershift conformance tests, just so we don't burn ourselves twice!
sshKeys should not be removed from nodes upon firstboot.
=> OCPBUGS-16227: make sure sshKey are not emptied out on firstboot

templates/common/_base/files/container-storage.yaml
When a privileged user creates a container that mounts `/` (or any parent of `/var/lib/containers/storage`), they often expect to be able to inspect the container mountpoint `/var/lib/containers/storage/overlay/.../merged`. However, if `skip_mount_home` isn't specified, that is mounted private, and is not accessible to containers.
In openshift 3, the behavior worked with `skip_mount_home` present, and many consider it a regression.
It was removed because there were concerns on kernel performance of the recursive mounts, but I have collaborated with a member of perf/scale to check that's not the case anymore.
Thus, I think we can safely set this field by default and allow privileged containers to have the access one naively expects.
**- Description …
=> OCPNODE-1714: files: add skip_mount_home to storage.conf

templates/common/baremetal/files/NetworkManager-static-dhcp.yaml
This was fixed for the resolv-prepender script in
https://github.com/openshift/machine-config-operator/commit/1953269ebc168065345e465bac9c832b71bfb016 but it was recently pointed out that we are doing the same thing in static-dhcp dispatcher script too. Although I doubt anyone is still using that feature, it is still technically supported so we should fix it.
Fixed SELinux issue in static-dhcp dispatcher script.
=> OCPBUGS-14965: Run hostnamectl with systemd-run

pkg/controller/node/node_controller.go
If the controller is killed and restarted, there is a race condition where the scheduler lists are checked before the cache sync is complete. This happens outside the work queue, within an event callback(`checkMasterNodesOnAdd`) so the wait for cache sync is skipped. By returning an error on an empty scheduler list, the controller will not take any action on the nodes by default and consequently, will (hopefully) not flip the master node between scheduleble and unschedulable when the controller is unexpectedly killed. 
How to test:
Deleting the controller pod should not unschedule the master nodes. This was observed on SNO and SNO+1 nodes according to the bug.
=> OCPBUGS-13825: The machine-config-controller pod restart in SNO+1 causing daemonsets to restart

cmd/common/helpers.go
Changes the lease lock resource type from ConfigMapsLeases to LeasesResourceLock. We'll do a follow-up PR to clean up the old lease config maps in a later release.
leader elections should work as before with no complaints, no timing weirdness etc
migrate to LeasesResourceLock for leader elections
=> MCO-532: Finish lease type migration

Dockerfile, Dockerfile.rhel7
Backport #3741 to release-4.13
OCP - CI runs should continue to pass
OKD - Install and then enable kernel-rt on nodes
Re-enable SCOS Extensions
=> OKD-174: Dockerfile: OKD: Reenable extensions image on SCOS

manifests/bootstrap-pod-v2.yaml, manifests/machineconfigdaemon/daemonset.yaml, manifests/on-prem/coredns.yaml, manifests/on-prem/keepalived.yaml, templates/common/on-prem/files/coredns.yaml, templates/common/on-prem/files/keepalived.yaml, templates/master/00-master/alibabacloud/files/etc-kubernetes-manifests-apiserver-watcher.yaml, templates/master/00-master/azure/files/etc-kubernetes-manifests-apiserver-watcher.yaml, templates/master/00-master/gcp/files/etc-kubernetes-manifests-apiserver-watcher.yaml, templates/master/00-master/on-prem/files/haproxy.yaml
In order to not break specific volume drivers, all volume mounts who's source is a hostPath must use mountPropagation: HostToContainer
All volumeMounts that come form this type of volume now have the mountPropagation specified.
=> OCPBUGS-14945: add HostToContainer propagation to all hostPath volume mounts

pkg/daemon/update.go
currently, the forcefile sometimes gets stopped from triggering an osupdate if one of our other priorities gets in the way. The forcefile should alwyas trigger and end to end update, re-applying all changes if the osImageURL is different. This will get many customers out of this half baked reboot loop we have been seeing.
when using the forcefile, should always see `Updating OS` indicating a full reboot, especially when there is a config mismatch with the osImageURLs.
the forcefile now always triggers a full os update.
=> MCO-654: forcefile should always trigger an OS update

pkg/controller/kubelet-config/kubelet_config_features.go, pkg/controller/kubelet-config/kubelet_config_nodes.go
1. Changes in the `nodes.config.openshift.io` object results in the create/update of `97-{master/worker}-generated-kubelet` machine configs
2. However, these changes are not rendered into the `master/worker` mcps if `98-{master/worker}-generated-kubelet` or `99-{master/worker}-generated-kubelet` machine configs exist due to precedence.
3. Hence, in order to bring in the change caused by nodes.config object's update, the respective sync functions of featuregate controller and the Kubelet config controller need to be called/executed in the syncNodeConfig function.
4. `syncKubeletConfig` function is already getting called and this code change introduces the calling of `syncFeatureHandler` function
5. Also added a minor fix in featuregate controller sync to apply the workerlatencyprofiles …
=> OCPBUGS-17433: Sync featuregate controller during the node config controller sync

pkg/operator/status.go
removed a metric related log that is no longer required
=> operator: remove metrics related log

pkg/daemon/certificate_writer.go
Fixes: OCPBUGS-17683
Replaced `..` with a `:` in the registry related CA file paths.
```
$ oc new-build -D $'FROM centos:7\nRUN yum install -y httpd'
$ oc new-app centos:latest
```
Fixes x509 error after node-ca removal (https://github.com/openshift/cluster-image-registry-operator/pull/867)
=> OCPBUGS-17683 replace .. with : on registry CA file paths

pkg/controller/common/layered_node_state.go, pkg/controller/common/layered_node_state_test.go, pkg/controller/common/layered_pool_state.go, pkg/controller/common/layered_pool_state_test.go, pkg/controller/node/node_controller.go, pkg/controller/node/node_controller_test.go, pkg/controller/node/status.go, pkg/controller/node/status_test.go, pkg/daemon/writer.go, test/helpers/nodebuilder.go, test/helpers/poolbuilder.go, test/helpers/utils.go
This makes NodeController aware of BuildController. Specifically, it will
propagate the final OS image pullspec from the MachineConfigPool annotation
(`machineconfiguration.openshift.io/newestImageEquivalentConfig`) into the
currentImage and desiredImage annotations for each node in the target pool.
I've written a small Go binary that can be used to help aid in these steps: https://github.com/openshift/machine-config-operator/pull/3852. It is not required, but does make the setup / teardown process of this much easier.
1. Bring up an OpenShift cluster.
2. Create a new MachineConfigPool or use an existing MachineConfigPool.
3. Opt a pool into layering by adding the `machineconfiguration.openshift.io/layering-enabled` label onto a MachineConfigPool. …
=> MCO-564: Make NodeController aware of BuildController

pkg/controller/build/assets/Dockerfile.on-cluster-build-template, pkg/controller/build/build_controller.go, pkg/controller/build/fixtures_test.go, pkg/controller/build/helpers.go, pkg/controller/build/helpers_test.go, pkg/controller/build/image_build_request.go, pkg/controller/build/image_build_request_test.go, pkg/controller/build/pod_build_controller.go
BuildController now allows a cluster admin to provide an optional ConfigMap containing a custom Dockerfile. This Dockerfile is provided on a per-pool basis, meaning that different pools can have different Dockerfiles, if desired. A admin-supplied Dockerfile will be injected into the Dockerfile that we render prior to beginning a build. The custom Dockerfile is located in a ConfigMap with 1:1 mapping of pool -> Dockerfile content. In other words, it will look like this:
```yaml
---
apiVersion: v1
data:
layering: |-
FROM configs AS final
echo 'custom file' > /etc/custom-file
master: ""
worker: ""
kind: ConfigMap
metadata:
name: on-cluster-build-custom-dockerfile
namespace: openshift-machine-config-operator
``` 
This ConfigMap is optional as are the individual Dockerfiles …
=> MCO-729: BuildController should allow cluster admins to provide a custom Dockerfile

pkg/daemon/daemon.go
With ReexecuteForTargetRoot, we have already chroot into rootfs. So, we should already have necessary MCD pod content mounted inside the host. This also avoids overriding previously mounted content.
We saw this issue in 4.13 https://github.com/openshift/machine-config-operator/pull/3812#issuecomment-1645446448 . We don't see this issue in usual upgrade case in ci because we upgrade from 4.13 to 4.14 , where both have RHEL 9 baseOS. But I forgot that in EUS upgrade with paused pool, it is likely that OS upgrade will happen from 4.12 (RHEL 8) to 4.14 .
This was anyway I had in mind to cherry-pick to 4.14 but somehow went off the radar.
=> OCPBUGS-17701: daemon: igmore mounting MCD pod content when target is "/"

pkg/controller/bootstrap/bootstrap.go, pkg/controller/bootstrap/bootstrap_test.go, pkg/daemon/certificate_writer.go, pkg/daemon/daemon.go, pkg/daemon/update.go, pkg/operator/render.go, pkg/operator/sync.go, pkg/server/bootstrap_server.go, pkg/server/cluster_server.go, pkg/server/server.go, pkg/server/testdata/controller-config/machine-config-controller.yaml, templates/common/_base/files/additional-trust-bundle.yaml, templates/common/_base/files/cloud-provider-ca.yaml, templates/common/_base/files/kubelet-ca.yaml, test/e2e-bootstrap/bootstrap_test.go, test/e2e/mcd_test.go, test/helpers/utils.go
In order to remove certificates from MC, the MCS needs to read the controller config both in the bootstrap server and the cluster server. Once this is in place, removing the certs from machine configs consists of ensuring the rendered configs do not contain the kube data to write into the files of the machine config. Accomplish this by deleting cert templates
`oc describe mc/xxxx` the raw config/storage/files should no longer contain the following certs:
/etc/kubernetes/kubelet-ca.crt
/etc/kubernetes/static-pod-resources/configmaps/cloud-config/ca-bundle.pem
/etc/pki/ca-trust/source/anchors/openshift-config-user-ca-bundle.crt
ensure the MCS properly writes certificate data directly to ignition while also ensuring …
=> MCO-605: MCO-550: Remove Certificates from MachineConfig

cmd/machine-os-builder/main.go, cmd/machine-os-builder/start.go, manifests/machineosbuilder/clusterrole.yaml, pkg/controller/build/build_controller.go, pkg/controller/build/fixtures_test.go, pkg/controller/build/helpers.go, pkg/controller/build/image_build_request.go, pkg/controller/build/image_build_request_test.go, pkg/controller/build/pod_build_controller.go, pkg/operator/sync.go, test/e2e/mob_test.go
Wire up productionalized BuildController in Machine OS Builder binary and added choice for backend image builder. The productionalized BuildController is started by the binary and it is able to create and monitor builds. The Machine OS Builder startup process reads the on-cluster-build-config ConfigMap at startup and uses the desired imageBuilder.
**For [MCO-566](https://issues.redhat.com//browse/MCO-566): Wiring up Productionalized Build Controller**
1. create a machine config pool and apply it
```
kind: MachineConfigPool
metadata:
name: on-cluster-build
spec:
machineConfigSelector:
matchExpressions:
- {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,on-cluster-build]} …
```
=> MCO 566: MCO 662 Wire up productionalized BuildController in Machine OS Builder binary and choosing backend image builder

pkg/daemon/daemon.go, pkg/daemon/daemon_test.go, pkg/daemon/node.go, pkg/daemon/rpm-ostree.go, pkg/daemon/update.go, pkg/daemon/update_test.go, pkg/daemon/writer.go, test/e2e-shared-tests/mcd_config_drift.go
The MCD needs to be aware of the new layered image annotations so that it can apply layered OS updates as well as traditional MachineConfig updates.
=> MCO-564: Make MCD aware of on-cluster builds

pkg/daemon/update.go
Check the existence of the /home/core/.ssh dir before creating a new one via runuser core by hand. Delete if any in case the dir is created at a wrong time and under the wrong user (root), and let the MCD recreate it.
Before:
1) create a cluster w/ ssh key
2) remove file /home/core/.ssh/authorized_keys.d/ignition
3) remove dir /home/core/.ssh/authorized_keys.d
4) chown root /home/core/.ssh
5) oc apply -f new-ssh.yaml
RESULT: nodes degraded; new mc could not apply to nodes; owner of the .ssh dir remains root ; .ssh dir remains empty
After:
1) create a cluster w/ ssh key
2) remove file /home/core/.ssh/authorized_keys.d/ignition
3) remove dir /home/core/.ssh/authorized_keys.d
4) chown root /home/core/.ssh
5) oc apply -f new-ssh.yaml
RESULT: nodes all …
=> OCPBUGS-11832: SSHkeys fails to write on upgrade to 4.13.rc3

install/0000_80_machine-config-operator_01_machineconfigpool.crd.yaml, install/0000_90_machine-config-operator_01_certificate_observability_storage_migration.yaml, manifests/controllerconfig.crd.yaml, pkg/apis/machineconfiguration.openshift.io/v1/types.go, pkg/controller/node/node_controller_test.go, pkg/controller/node/status.go, pkg/controller/template/template_controller.go
- Removed certificate observability fields from the MachineConfigPool and ControllerConfig CRDs and types.go, because if they make it in for 4.14 ships, we won't be able to easily change them to the proper `metav1.Time`. 
- Made sure the MCO never sets the cert availability date fields to a value
- This also adds a `StorageVersionMigration` for `ControllerConfig` and `MachineConfigPool` so etcd can clean out anything it has stored for these types (see: https://github.com/openshift/kubernetes-kube-storage-version-migrator/blob/master/USER_GUIDE.md#check-if-migration-has-completed) 
- The certificate cleanup that was using these fields as part of the Image Registry Certificate work  https://github.com/openshift/machine-config-operator/blob/40dfd9b927452690effd3400fbc8f556a2b …
=> OCPBUGS-17810: temporarily remove cert observability fields, add storageversionmigration for machineconfigpools,controllerconfig

templates/master/01-master-kubelet/_base/files/kubelet.yaml, templates/worker/01-worker-kubelet/_base/files/kubelet.yaml, test/e2e/kubeletcfg_test.go
if the customer does not specify nodeStatusUpdateFrequency, we should still set it to the default value. If we do not, it seems that it gets set to zero.
While the 0 will be eventually translated to 10 so the effect is the same, our handling causes unintended diffs in kubeletConfigs in the intermediary which seems to confuse the MCO in choosing the proper machineConfig to update to.
=> OCPBUGS-15583: fix nodeStatusUpdateFrequency

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
With this change we are adding NetworkManager's "reapply" event to the list of events that trigger resolv-prepender. As per documentation[1], reapply attempts to update the configuration of a device without deactivating it what is a valid scenario for us to trigger the script.
[1] https://developer-old.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Device.html#gdbus-method-org-freedesktop-NetworkManager-Device.Reapply
Fixes: OCPBUGS-16733
=> OCPBUGS-16733: on-prem: run resolv-prepender on NM reapply event

templates/common/on-prem/files/configure-ip-forwarding.yaml
Using sysctl to modify paths containing dots is known to cause issues due to the fact that sysctl blindly assumes that dot is always a separator and is changed to `/`.
This is a problem when we want to configure a network interface containing a dot in its name, e.g. `bond0.354`, because `net.ipv4.conf.bond0.354.forwarding=1` expands to
`/proc/sys/net/ipv4/conf/bond0/354/forwarding` when in reality it should be `/proc/sys/net/ipv4/conf/bond0.354/forwarding`.
To remediate this we are changing the call from
`sysctl -w net.ipv4.conf.bond0.354.forwarding=1` to `echo "1" > /proc/sys/net/ipv4/conf/bond0.354/forwarding` as there is no simple way to change the behaviour of sysctl.
In the current form the call is breaking the script as writing a value to a non-existing path returns an error `cannot …
=> OCPBUGS-17787: Fix sysctl breaking dots in paths

templates/master/01-master-kubelet/_base/files/kubelet.yaml, templates/worker/01-worker-kubelet/_base/files/kubelet.yaml, test/e2e/kubeletcfg_test.go
This reverts commit 3c70c4bb9b4da7127ff848c0deb696a72a6b456b.
TRT is observing failures starting in payload [4.14.0-0.nightly-2023-08-24-021808](https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.nightly/release/4.14.0-0.nightly-2023-08-24-021808) we started seeing failures in [periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-gcp-ovn-rt-upgrade-4.14-minor-release-openshift-release-analysis-aggregator/1694535327638622208) job tests for `Nodes should reach OSUpdateStaged in a timely fashion`
We have opened [OCPBUGS-18090](https://issues.redhat.com/browse/OCPBUGS-18090) to track the issue and identified https://github.com/openshift/machine-config-operator/pull/3784 …
=> Revert "fix nodeStatusUpdateFrequency"

pkg/daemon/daemon.go
OCPBUGS-16035: On some system, nmstatectl fails to persists nic due to missing /etc/systemd/network. Until we use fixed version of nmstate in MCO, this workaround will ensure that the process happens successfully.
=> OCPBUGS-16035: daemon: create /etc/systemd/network directory on node

pkg/controller/render/render_controller.go, pkg/controller/template/template_controller.go
controller: Drop noisy log message about certificates
I often turn to the controller pod logs to debug issues, and
this log message is repeated very often.  While it was
probably useful at the time the feature was being developed/tested
I doubt it will be necessary in the future.
In the end, the status really *is* the debugging frontend I believe.
---
controller: Drop noisy BaseOSContainerImage log message
In general we should avoid logging unless something changed.
I don't believe we need this log message, we can detect OS
changes from e.g. the MCD logs.
---
=> OCPBUGS-18086: Quiet controller noisiness

pkg/daemon/daemon.go
Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3883
In 4.13, for safer side creating the /etc/systemd/network/ directory on both both RHEL 8 and RHEL 9 based nodes. This is because we are invoking `nmstatectl persist-nic-names ----inspect` on RHEL 9 nodes.
=> OCPBUGS-18076: daemon: create /etc/systemd/network directory on node

pkg/operator/sync.go
order the image registry cert data before adding it to cconfig so that we do not have a different ordering and therefore a different resource each sync potentially.
=> OCPBUGS-18097: ensure cconfig is not updated too frequently

manifests/machine-os-puller/rolebinding.yaml, pkg/operator/sync.go
The original check for image registry operator wasn't sufficient. The fetch call can also return an error, so I added a specific carveout so as to not cause a degrade.
(also cleaned up some minor commenting nits I had noticed the other day)
MCO should no longer degrade when launching a cluster with no image registry installed
operator: fixed no-op when registry isn't present
=> OCPBUGS-18442: MCO is degraded if not install image registry operator

templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml
Ensure azure-routes hack for internalLB hairpin traffic works for SGW
We have a watcher that adds iptable rules to redirect
traffic destined towards internal azureLB on the master nodes.
This is to avoid the hairpin bug where srcIP==dstIP and
azure drops the traffic.
However SGW in OVN does not egress via mp0 into the host
and traffic leaves directly via br-ex. The ovnk pods on
the node will hence have rejections 1/3rd of the time
without this fix in case the external azure lb dnats it
back to same master node.
Let's add ovnk routes on ovn-cluster-router for sgw
that will ensure this traffic is hairpinned within the
node.
Use steps in https://issues.redhat.com/browse/OCPBUGS-9972
However azure+v6 and azure+dualstack deployments are not supported, so …
=> OCPBUGS-9972: Fix azure routes hack for ovnk pods towards internalLB on master nodes in SGW mode

templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml
We have a watcher that adds iptable rules to redirect traffic destined towards internal azureLB on the master nodes. This is to avoid the hairpin bug where srcIP==dstIP and azure drops the traffic.
However SGW in OVN does not egress via mp0 into the host and traffic leaves directly via br-ex. The ovnk pods on the node will hence have rejections 1/3rd of the time without this fix in case the external azure lb dnats it back to same master node.
Let's add ovnk routes on ovn-cluster-router for sgw that will ensure this traffic is hairpinned within the node.
Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
(cherry picked from commit 6c3dc5ec2394546527a1e1b7d9ed5d79ea1fad21)
Closes: #OCPBUGS-18159
Clean cherry-pick
**- Description for the …
=> OCPBUGS-18159: Ensure azure-routes hack for internalLB hairpin traffic works for SGW

pkg/daemon/file_writers.go, pkg/daemon/update.go, pkg/daemon/update_test.go
- OCPBUGS11437
The pull secret is preserved in the path /etc/machine-config-daemon/orig/var/lib/kubelet/config.json.mcdorig. Whereas, the user needs it to be deleted when the pull secret is being deleted/ replaced.
- What is the problem
There is complaint about that the MCD is creating orig files to preserve files that should not be preserved. To be more specific, the orig preserving system should only preserve files that are originally on the disk, but are now preserving files that are written by Ignition. The root cause is that Ignition writes the files before the MCD takes the control as a result when MCD comes in, it sees all the files written before as files on disk, which is very wrong.
- What I did
Add more constraints for orig file generation: orig files should only be generated …
=> OCPBUGS-11437: MCO keeps the pull secret to .orig file once it replaced

pkg/daemon/daemon.go, pkg/daemon/daemon_test.go, pkg/daemon/update.go
In firstboot MCO checks if reboot can be skipped.  In order for reboot to be skipped, the kernel arguments of the current (booted) system and the expected system need to match.
Currently, in firstboot the list of the current kargs is assumed to be empty.  To reflect the actual list of arguments the system was booted with, this change extracts the set of booted kargs from /proc/cmdline to be used for comparison.
Only kargs that appear both in the requested kargs and /proc/cmdline are used for comparison.
Extracted the kernel arguments from /proc/cmdline to be used for comparison with the expected kernel arguments
1. regression
2. With assisted installed with other changes in the epic, verify that reboot is skipped and installation is successful.
**- …
=> MCO-708: Extract and merge kernel arguments from /proc/cmdline

templates/common/_base/units/machine-config-daemon-firstboot.service.yaml, templates/common/_base/units/machine-config-daemon-pull.service.yaml
The systemd service ovs-configuration.service is skipped if the file /etc/ignition-machine-config-encapsulated.json exists. 
The service machine-config-daemon-firstboot.service removes the file after processing.
When we want to skip reboot, we need to verify that the service is not skipped. Therefore, these two services are moved before ovs-configuration.service.
Moved machine-config-daemon-pull.service and machine-config-daemon-firstboot.service before ovs-configuration.service
1. Regression
2. Verify with Assisted Installer that the installation succeeds with reboot skipped and network type is OVN 
Move services machine-config-daemon-pull.service and machine-config-daemon-firstboot.service before …
=> MCO-731: Move services machine-config-daemon-pull.service and machine-config-daemon-firstboot.service before ovs-configuration.service

manifests/bootstrap-pod-v2.yaml
Removed memory limits on bootstrap MCC as per https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits
This was the only instance of a pod cpu/memory limit in the MCO repo. 
Tests should work as before. This is minimal change, so I don't think QE is required.
bootstrap: removed memory limit on controller
=> MCO-765: Examine/Remove memory limits on MCO pods

install/0000_80_machine-config-operator_03_rbac.yaml, install/0000_80_machine-config-operator_04_deployment.yaml, install/0000_90_machine-config-operator_90_deletion.yaml
Carrying and extending #3884.
Single-node updates from 4.13 to 4.14 are having slow leader handoffs during operator Deployment updates.  For example,  [this CI run][2] in Loki:
```console
{invoker="openshift-internal-ci/periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-aws-upgrade-ovn-single-node/1692132139799154688"} | unpack | pod="machine-config-operator-74d7475455-cgcmg" |= "leaderelection"
```
gives:
```
machine-config-operator-7987b6bcdd-6zvrt
I0817 11:26:14.747630       1 leaderelection.go:248] attempting to acquire leader lease openshift-machine-config-operator/machine-config...
I0817 11:26:14.756376       1 leaderelection.go:258] successfully acquired lease openshift-machine-config-operator/machine-config
E0817 11:31:15.153289       1 …
```
=> OCPBUGS-16905: install: Recreate and delayed default ServiceAccount deletion

templates/common/on-prem/files/resolv-prepender.yaml
Avoid pulling baremetalRuntimeCfgImage again if it already exists on the node
`pull_baremetal_runtime_cfg_image` function should avoid  pull attempt if this image already present on the node. This ensures DNS prepender can work when mirror/quay image is temporarily unreachable
Updated resolv-prepender.sh to make sure that pull is not running if the image already exists on the node 
Check networkmanager logs - it should have `NM resolv-prepender: Starting download of baremetal runtime cfg image` just once (in upgrade case you may see it twice) for on-premise jobs, i.e.:
```
wget -O - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/3907/pull-ci-openshift-machine-config-operator-maste …
```
=> OCPBUGS-18772: resolv-prepender: avoid pulling baremetalRuntimeCfgImage again 

pkg/daemon/update.go
In the past, we have been using `oc image extract` to get OS and extensions container content on node and only fallback to `podman cp` when oc fails. oc doesn't respect ICSP well and lead to bugs like https://issues.redhat.com/browse/OCPBUGS-13044. Since 4.12, we don't need to extract and copy os content on node. Now, using podman for extensions container will keep MCO completely honor ICSP.
When we apply an extension, MCD pod log would show podman related log instead of `oc image extract`
=> OCPBUGS-13044: daemon: always use `podman cp` to copy extensions container content

pkg/daemon/update.go
This is a manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3808
/assign yuqi-zhang
=> [release-4.13] OCPBUGS-19414: The kubeconfig copied on to each node has 644 permissions

pkg/controller/template/template_controller.go, pkg/daemon/certificate_writer.go, pkg/operator/operator.go, pkg/operator/sync.go, test/e2e/mco_test.go
currently we delete and re-create the merged configmap every sync. Instead, we want to patch it with new data.
merged-trusted-image-registry-ca in openshift-config-managed now should always exist, and be patched with new data
get openshift-config-managed/merged-trusted-image-registry-ca and get the creation timestamp
patch image.config.openshift.io/cluster with a new additionalTrustedCA entry in the spec.
get openshift-config-managed/merged-trusted-image-registry-ca, get the creation timestamp and ensure that it matches the previous one and that the new data is there.
=> OCPBUGS-18800: fix merged image registry CA behavior

lib/resourcemerge/machineconfig.go, lib/resourcemerge/meta.go
This PR introduces a missing reconciliation of IPFamilies property in the ControllerConfig. A consequence of the reconciliation missing is that after conversion from single-stack to dual-stack the kubelet is still configured as single-stack because the underlying MCO's variable does not change its value.
With this PR, when converting such a cluster, ControllerConfig will update the value and as a consequence reconfigure kubelet (specifically `--node-ip` param).
Please note with this change we are introducing one reboot to the process of cluster conversion.
Fixes: OCPBUGS-15910
=> OCPBUGS-15910: After dual-stack conversion reconcile IPFamilies

templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml
This regression was introduced in https://github.com/openshift/machine-config-operator/pull/3878. If the plugin is SDN, do not invoke the nbctl commands as it causes errors like:
```
Sep 19 02:10:31 jima41501-c646k-master-0 openshift-azure-routes[13908]: /opt/libexec/openshift-azure-routes.sh: line 130: ovnkContaine>
Sep 19 02:10:31 jima41501-c646k-master-0 systemd[1]: openshift-azure-routes.service: Main process exited, code=exited, status=1/FAILURE
Sep 19 02:10:31 jima41501-c646k-master-0 systemd[1]: openshift-azure-routes.service: Failed with result 'exit-code'.
```
=> OCPBUGS-19365: Ignore invoking nbctl calls if its SDN

templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml
Clean cherry-pick of https://github.com/openshift/machine-config-operator/pull/3928 + rename container name to ovnkube-master to match pre-IC era. @huiran0826 : let's sync up tomorrow on this because I am unsure how this passed 4.13 verification earlier since ovnkube-controller doesn't really exist on 4.13
=> [release-4.13] OCPBUGS-19509: Ignore invoking nbctl calls if its SDN

Dockerfile
This is keep it consistent with Dockerfile.rhel7
Follow-up of https://github.com/openshift/machine-config-operator/pull/3919
=> Dockerfile: update local copy to OCP 4.15 image

Makefile, test/e2e-layering/helpers_test.go, test/e2e-layering/onclusterbuild_test.go, test/helpers/utils.go
I added an e2e test suite specifically targeting the on-cluster build dev preview. This is separate and distinct from the e2e and e2e-single-node suites and will have its own test stage in the OpenShift CI configs. The tests contained perform the following functions:
- Runs an on-cluster build using the OpenShift Image Builder.
- Runs an on-cluster build using the custom Pod Builder.
- Runs an on-cluster build and rolls out the final image to a cluster node, then verifies that the expected binaries are present.
For testing purposes, I temporarily modified the `make test-e2e` target to execute this new test suite so that I could verify that it runs successfully in CI. Those results can be seen in [this Prow job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/p …
=> MCO-664: adds e2e for on-cluster build dev preview

cmd/machine-config-operator/start.go, pkg/operator/operator.go, pkg/operator/sync.go
Added listers to hopefully reduce the amount of calls caused by #3806 
internal registry secrets merge should work as before, but we should see a good amount of reduction in API calls by this code path
=> OCPBUGS-18902: Internal Registry Secrets merge causing excessive API calls

pkg/controller/build/build_controller.go, pkg/controller/build/build_controller_test.go, pkg/controller/build/fixtures_test.go, pkg/controller/build/image_build_request.go, pkg/controller/build/pool_state.go, pkg/controller/build/pool_state_test.go, pkg/controller/common/layered_pool_state.go
This makes the BuildController unit tests less flaky in a couple of ways:
1. Consolidates all MachineConfigPool object interrogation / mutation into a single place.
2. Ensures that MachineConfigPool object updates are retried in the event of a conflict. This work was imported from https://github.com/openshift/machine-config-operator/pull/3894 and should be merged as part of this PR.
To verify this, the unit test suite must be run exhaustively. To reproduce this locally, one can clone this PR and run: `$ go test -count=100 -failfast ./pkg/controller/build` This will effectively run the unit test suite 100 times. While I cannot completely guarantee that it will never fail, the likelihood that it will is substantially reduced.
**- Description for the …
=> MCO-746: make buildcontroller tests less flaky

pkg/daemon/update.go
Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/3932
=> OCPBUGS-19675: daemon: always use `podman cp` to copy extensions container content

pkg/daemon/rpm-ostree.go
One of the conditions to reboot after firstboot is different os image
URLs.  In order to correctly compare the URLs, the booted OS image URL
has to be stripped from container image reference and transport.
This commit utilizes a recent change in rpm-ostree client to do just
that.
Strip registry transport from os image URLs before checking if reboot is needed.
1. Regression
2. Verify if URLs are considered equal when booted os URL is with a registry transport, and the required is without.
Strip registry transport from OS Image URLs for comparison
=> MCO-707: Strip registry transport from os image URL for comparison

templates/common/on-prem/files/resolv-prepender.yaml
This PR modifies the check for existing image to use `podman image
exists` command instead of `wc -l` and comparing the value. We are also
adding here some additional logic so that instead of current image
digest we will print a readable message indicating whether image exists
or not.
Original problem that we have observed was related to the fact in NM
there is a transient time without working DNS and during this time
resolv-prepender has no chance of finishing successfuly. Now this will
not be a problem anymore.
=> OCPBUGS-18772: Use image exists in resolv-prepender instead of wc -l

templates/common/on-prem/units/kubelet.service-wait-resolv.yaml
Fixes: #OCPBUGS-18911
Added  message before we exit with 255 status
To quickly reproduce just delete  /run/resolv-prepender-kni-conf-done on IPI cluster and restart kubelet. 
Improve kubelet error log when there is an issue with resolv-prepender
=> Improve kubelet error log

go.mod, go.sum, pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/container-runtime-config/helpers_test.go, vendor/github.com/openshift/runtime-utils/pkg/registries/registries.go, vendor/modules.txt
remove the check that prevents ICSP and IDMS/ITMS from coexisting.
vendor in https://github.com/openshift/runtime-utils/pull/18 to support both ICSP and IDMS objects writing to registries.conf
on the cluster launched with https://github.com/openshift/kubernetes/pull/1685, and this patch:
`launch https://github.com/openshift/kubernetes/pull/1685,https://github.com/openshift/machine-config-operator/pull/3898`
1. create icsp objects
2. create idms objects that has same source, mirror configurations as icsp
3. delete icsp objects and registries.conf stays  the same. No reboots after the icsp deletion.
```yaml
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
name: ubi8repo
spec:
imageDigestMirrors:
- mirrors:
- …
```
=> OCPNODE-1799: support icsp and idms objects

cmd/machine-config-operator/start.go, pkg/operator/operator.go, pkg/operator/sync.go
Manual cherry pick of #3912 
-What I did
Added listers to hopefully reduce the amount of calls caused by https://github.com/openshift/machine-config-operator/pull/3806
-How to verify it
internal registry secrets merge should work as before, but we should see a good amount of reduction in API calls by this code path
=> [release-4.14] OCPBUGS-19703: Internal Registry Secrets merge causing excessive API calls

templates/common/vsphere/units/nodeip-configuration-vsphere-upi.service.yaml
Because this unit merged after the v6-primary PR it is missing the logic to allow node ip selection work in v6-primary envs. I don't believe v6-primary dual stack is supported on this platform yet anyway, but it likely will be soon and we don't want to let these unit files diverge anyway.
Make sure nodeip-configuration on VSphere UPI clusters supports v6-primary dual stack.
=> OCPBUGS-19992: Add v6-primary dual stack support to VSphere UPI

cmd/machine-config-operator/bootstrap.go, install/0000_80_machine-config-operator_05_osimageurl.yaml, install/image-references, pkg/controller/common/helpers.go, pkg/operator/bootstrap.go, pkg/operator/images.go, pkg/operator/sync.go
xref https://github.com/openshift/enhancements/blob/master/enhancements/ocp-coreos-layering/ocp-coreos-layering.md
This is part of https://issues.redhat.com/browse/MCO-392
Since we've landed the new format image usage in the latest nightly, it's time to try dropping it from our image references entirely.
=> MCO-424: Drop `machine-os-content` references

templates/common/on-prem/units/nodeip-configuration.service.yaml
We never intended to support ingress and API VIPs on different subnets, but it turns out we didn't prevent it either and it was working up until 4.13 so we have clusters deployed in production that use such an architecture. In 4.13 this was broken by the automatic remote worker functionality because we only look at the API VIPs when selecting the node IP, and as a result the nodes on the ingress VIP subnet looked like remote workers and would not start keepalived or schedule ingress router pods.
To restore the previous behavior we can just include the ingress VIPs in the call to node-ip set so nodes on the ingress VIP subnet will also be seen as non-remote.
Also use ingress VIPs when searching for node IP.
=> OCPBUGS-18771: Consider ingress VIPs when selecting node IP

pkg/controller/common/helpers.go, pkg/controller/kubelet-config/kubelet_config_bootstrap.go
Fixes: https://issues.redhat.com/browse/OCPBUGS-19708
- This code change allows the user to configure duplicate kArgs via MC.
- Also fixes failure of the bootstrap-unit ci job while enabling the above functionality
cc: @sinnykumari
=> OCPBUGS-19708: Support to append the duplicate kernel arguments to the rendered MC

templates/common/vsphere/files/vsphere-hostname.yaml
Currently, the virtual machines on vCenter don't have `guestinfo.hostname` when using CAPI on OCP. This PR adds another check to see whether `vm_name` variable is empty, therefore we take the hostname from the metadata.
=> OCPCLOUD-1609: Set guestinfo.hostname for CAPI VMs on vSphere

templates/common/_base/units/crio.service.yaml, templates/common/_base/units/firstboot-osupdate.target, templates/common/_base/units/kubelet-auto-node-size.service.yaml, templates/common/_base/units/kubelet-dependencies.target.yaml, templates/common/_base/units/machine-config-daemon-firstboot.service.yaml, templates/common/_base/units/machine-config-daemon-pull.service.yaml, templates/common/_base/units/mtu-migration.service.yaml, templates/common/_base/units/node-valid-hostname.service.yaml, templates/common/_base/units/nodeip-configuration.service.yaml, templates/common/_base/units/ovs-configuration.service.yaml, templates/common/alibabacloud/units/alibaba-kubelet-nodename.service.yaml, templates/common/aws/units/aws-kubelet-nodename.service.yaml, templates/common/aws/units/aws-kubelet-providerid.service.yaml, templates/common/gcp/units/gcp-hostname.service.yaml, templates/common/on-prem/units/nodeip-configuration.service.yaml, templates/common/openstack/units/openstack-kubelet-nodename.service.yaml, templates/common/vsphere/units/nodeip-configuration-vsphere-upi.service.yaml, templates/common/vsphere/units/vsphere-hostname.service.yaml, templates/master/00-master/alibabacloud/units/openshift-alibabacloud-routes.path.yaml, templates/master/00-master/azure/units/openshift-azure-routes.path.yaml, templates/master/00-master/azure/units/openshift-azure-routes.service.yaml, templates/master/01-master-kubelet/_base/units/kubelet.service.yaml, templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml, templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
The primary motivation here is to eventually stop pulling container images `Before=network-online.target` because it creates complicated dependency loops.
We introduce a new `kubelet-dependencies.target` - both `crio.service` and `kubelet.service` are `After+Requires=kubelet-dependencies.target`.
This also makes it cleaner for pre-kubelet services, which can just order themselves `Before=kubelet-dependencies.target`.
This is just a small preparatory PR to introduce the target unit. The real bigger change will come when we move services like `ovs-configuration.service` and `node-valid-hostname.service` to actually be `After=network-online.target` + `Before=kubelet-dependendies.target`.
Crucially, this will unblock services like `machine-config-daemon-pull.service` that want to fetch …
=> OCPBUGS-15087: templates: Introduce kubelet-dependencies.target

cmd/machine-config-controller/start.go, cmd/machine-config-daemon/start.go, cmd/machine-config-operator/start.go, cmd/machine-os-builder/start.go, pkg/controller/common/controller_context.go, test/e2e-bootstrap/bootstrap_test.go
Removed the namspace argument in CreateControllerContext, since this seems like it should be a constant for all pods. Sending a wrong namespace argument(we were sending in the componentName in most cases, except the operator)  would break the informer - we didn't run into this before because we were luckily not using namespace based informers in these pods. Let's see if removing this argument breaks anything. 
controller: remove namespace arg in context create
=> OCPBUGS-19722: Informers are setup with incorrect namespace

install/0000_90_machine-config-operator_01_node_dashboard.yaml
Fixes: https://issues.redhat.com/browse/OCPBUGS-20338
This dashboard is used to report the number of not ready nodes.  If a node stops reporting its status, it is possible to have a condition status that says `unknown` rather than `false`.  We should check for both unknown and false.
I applied this yaml to an existing 4.14 cluster and verified that the query works.
NodeNotReady should report both unknown and false for reporting unhealthy nodes.
=> OCPBUGS-20338: dashboard should detect unknown and not ready for not ready dashboard

templates/common/_base/files/configure-ovs-network.yaml
In the past (4.10 and before) we had support exceptions where a user was able to indicate different interfaces for kube traffic and br-ex. In 4.11 and later that ability was removed because node IP now runs before configure-ovs and configure-ovs uses the node IP hint interface to also choose its interface.
This commit restores the ability to separate the kube network interface from the one chosen to be used by br-ex. Similar to the extra bridge file, by specifying /etc/ovnk/default_bridge this interface will be used instead of the one found by nodeip or via default gateway detection.
=> OCPBUGS-7638: Allow specifying the interface for br-ex

templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
We don't want to terminate the whole systemd unit and potentially bring down dependent units (like network-online) for things that aren't really fatal.
=> OCPBUGS-20499: gcp-routes: don't exit on crictl failures

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
This should work since it's the default in CRI-O with the merge of https://github.com/cri-o/cri-o/pull/1714. It slightly increases security of the default configuration.
Updated CRI-O streaming server configuration to use 127.0.0.1 and a random port.
=> CRI-O: Use `127.0.0.1` for stream server with random port

Dockerfile, Dockerfile.rhel7
openshift/machine-config-operator#3769 pinned the nmstate package to version 2.2.9 until the breaking changes of the newer versions are addressed in the code base of the MCO. 
The changes in this PR allow to build the image on top of CS9 base images that do not have nmstate-2.2.9 in the current repositories by retrieving it from kojihub. This is useful when building the entire OKD payload on top of CS9 base images
=> Get the nmstate pinned package from kojihub when building on top of a CentOS base image

docs/MachineConfiguration.md, pkg/controller/common/constants.go, pkg/controller/common/helpers.go, pkg/daemon/update.go
Since RHEL 9 reverted to 4K memory pages for aarch64, add a way to
switch to a hugepage kernel.
The MachineConfig should contain the following to trigger the kernel
switch:
spec:
kernelType: 64k-pages
This is exclusive with the `realtime` kernel option.
xref https://issues.redhat.com/browse/COS-2402
This requires https://github.com/openshift/os/pull/1351
=> Add kernel-64k kernelType

templates/common/_base/files/configure-ovs-network.yaml
However unlikely, it is possible that configure-ovs receives any of these signals and either ignores them or terminates midway with an inconsistent configuration requiring manual intervention to recover.
Handle these signals by attempting to rollback any configuration changes performed and exiting with a sensible exit code.
=> OCPBUGS-19736: configure-ovs: handle SIGINT and SIGTERM

pkg/daemon/daemon.go, pkg/daemon/update.go
Set up a backup plan for on-disk current config reading, so that the call will reads the current config from the node annotation when the currentConfig is missing on the filesystem 
Before:
1. remove the currentConfig (/etc/machine-config-daemon/currentConfig)  from the node 
2. apply an update 
3. check the status of the MCO 
RESULT: DEGRADED
After:
1. remove the currentConfig (/etc/machine-config-daemon/currentConfig) from the node
2. apply an update
3. check the status of the MCO
RESULT: update went through; the mcp did not get degraded; currentConfig got written back to the disk at some point
=> OCPBUGS-16871: MCO - currentConfig missing on the filesystem

templates/common/_base/files/configure-ovs-network.yaml
typo s/iface_default_hint_file/default_bridge_file/
We are reading the wrong file.
This is why `[ -f ]` checks are bad, they aren't atomic.  Actually reading the file is the only true test.
```
configure-ovs.sh[8910]: ++ get_default_bridge_interface /var/lib/ovnk/iface_default_hint /etc/ovnk/extra_bridge /run/nodeip-configuration/primary-ip /etc/ovnk/default_bridge
configure-ovs.sh[8910]: ++ local iface=
configure-ovs.sh[8910]: ++ local counter=0
configure-ovs.sh[8910]: ++ local iface_default_hint_file=/var/lib/ovnk/iface_default_hint
configure-ovs.sh[8910]: ++ local extra_bridge_file=/etc/ovnk/extra_bridge
configure-ovs.sh[8910]: ++ local ip_hint_file=/run/nodeip-configuration/primary-ip
configure-ovs.sh[8910]: ++ local default_bridge_file=/etc/ovnk/default_bridge
configure-ovs.sh[8910]: …
```
=> OCPBUGS-7638: typo s/iface_default_hint_file/default_bridge_file/

templates/common/_base/files/ofport-request.yaml
The master of a bridge port can be indicated by UUID or ID. The current implementation assumed it was always ID and that the ID was equal to the interface name. While those assumptions hold true when the configuration is done by configure-ovs, it is not necessarily the case otherwise.
=> Use the bridge interface name for ofport request

pkg/controller/bootstrap/testdata/bootstrap/machineconfigcontroller-controllerconfig.yaml
The backporting chain of suppressing warning messages somehow broke this for 4.13, where the test will complain for DNS not setting APIVersion and Kind (but interestingly not for Infra)
So set these explicitly in the object creation loop. This doesn't otherwise affect any cluster functionality and is fine from 4.14 onwards.
=> OCPBUGS-22412: bootstrap_test: always set APIVersion and Kind for DNS

templates/common/_base/units/crio.service.yaml, templates/common/_base/units/firstboot-osupdate.target, templates/common/_base/units/kubelet-auto-node-size.service.yaml, templates/common/_base/units/kubelet-dependencies.target.yaml, templates/common/_base/units/machine-config-daemon-firstboot.service.yaml, templates/common/_base/units/machine-config-daemon-pull.service.yaml, templates/common/_base/units/mtu-migration.service.yaml, templates/common/_base/units/node-valid-hostname.service.yaml, templates/common/_base/units/nodeip-configuration.service.yaml, templates/common/_base/units/ovs-configuration.service.yaml, templates/common/alibabacloud/units/alibaba-kubelet-nodename.service.yaml, templates/common/aws/units/aws-kubelet-nodename.service.yaml, templates/common/aws/units/aws-kubelet-providerid.service.yaml, templates/common/gcp/units/gcp-hostname.service.yaml, templates/common/on-prem/units/nodeip-configuration.service.yaml, templates/common/openstack/units/openstack-kubelet-nodename.service.yaml, templates/common/vsphere/units/nodeip-configuration-vsphere-upi.service.yaml, templates/common/vsphere/units/vsphere-hostname.service.yaml, templates/master/00-master/alibabacloud/units/openshift-alibabacloud-routes.path.yaml, templates/master/00-master/azure/units/openshift-azure-routes.path.yaml, templates/master/00-master/azure/units/openshift-azure-routes.service.yaml, templates/master/01-master-kubelet/_base/units/kubelet.service.yaml, templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml, templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
The primary motivation here is to stop pulling
container images `Before=network-online.target` because it creates complicated dependency loops.
This is aiming to fix
https://issues.redhat.com/browse/OCPBUGS-15087
A lot of our services are "explicitly coupled" with ordering relationships; e.g. some had `Before=kubelet.service` but not `Before=crio.service`.
systemd .target units are explicitly designed for this situation.
We introduce a new `kubelet-dependencies.target` - both `crio.service` and `kubelet.service` are `After+Requires=kubelet-dependencies.target`. And units which are needed for kubelet should now be both `Before + RequiredBy=kubelet-dependencies.target`.
Similarly, we had a lot of entangling of the "node services" and the firstboot OS updates, with things explicitly ordering …
=> OCPBUGS-20418: Introduce kubelet-dependencies.target and firstboot-osupdate.target

pkg/controller/common/constants.go, pkg/controller/common/helpers.go, pkg/controller/common/helpers_test.go, test/helpers/helpers.go
In the MCO today MachineConfiguration merging is purely alphanumerically based, meaning that duplicate entries in higher alphanumerical (e.g. 99>00) MachineConfigs overwrite the lower config.
This is not an issue until you use custom pools, which always need to inherit from worker configs. In an example use case, let's say I have infra and worker pool, and would like to apply a separate kubeconfig to both of them. Both get generated as machineconfig like this:
- 99-infra-generated-kubelet
- 99-worker-generated-kubelet
And since infra pool takes base worker configuration, and i alphanumerically is lower than w, the infra kubeletconfig never can take effect. (The reverse is always fine since worker doesn't contain infra configs)
This means to have a setup where both worker and custom pools …
=> MCO-772: controller: allow custom pool configs to take priority

templates/common/openstack/files/usr-local-bin-openstack-kubelet-nodename.yaml, templates/common/openstack/units/kubelet-node-env.dropin.yaml, templates/common/openstack/units/openstack-kubelet-nodename.service.yaml
Common cause with https://github.com/openshift/machine-config-operator/pull/3979
Firstly, a refactor to use an EnvironmentFile via a dropin on kubelet.service rather than systemd config in kubelet.service.d. This is a slightly nicer way of doing it and is consistent with the approach for AWS in #3979. It requires an upgrade to move any existing file to the new location and format, but this can be removed in a release after all legacy nodes have been upgraded.
Most significantly, updates the generator script to retry indefinitely until it gets a value returned.
* Ensure a newly installed machine gets /etc/kubernetes/node.env correctly populated with instance name.
* Ensure an upgraded machine gets …
=> OCPBUGS-22200: Retry fetching OpenStack hostname if it fails

templates/common/kubevirt/files/002-nmstate-arp-proxy-ipv6-gw.yaml
Due to an nmstate bug - [0] - the IPv4 address previously configured from the
DHCP server is being configured as a static address.
The same should happen for IPv6 addresses.
If we explicitly list the desired IPs on the interfaces for IPv4 and
IPv6, the issue is not triggered.
This commit is a workaround, which should be used until the nmstate fix - [1] - is released in a RHEL Z-stream.
[0] - https://issues.redhat.com/browse/RHEL-16316
[1] - https://github.com/nmstate/nmstate/pull/2455
1. create an hosted cluster
2. restart a worker node of the hosted cluster
3. the node status should reach `Ready` after a while
Work-around nmstate bug [RHEL-16316](https://issues.redhat.com//browse/RHEL-16316) by explicitly …
=> OCPBUGS-23209: workaround nmstate bug by configuring ipv{4,6} addresses

templates/common/kubevirt/files/002-nmstate-arp-proxy-ipv6-gw.yaml
Due to an nmstate bug - [0] - the IPv4 address previously configured from the
DHCP server is being configured as a static address.
The same should happen for IPv6 addresses.
If we explicitly list the desired IPs on the interfaces for IPv4 and
IPv6, the issue is not triggered.
This commit is a workaround, which should be used until the nmstate fix - [1] - is released in a RHEL Z-stream.
[0] - https://issues.redhat.com/browse/RHEL-16316
[1] - https://github.com/nmstate/nmstate/pull/2455
1. create an hosted cluster
2. restart a worker node of the hosted cluster
3. the node status should reach `Ready` after a while
Work-around nmstate bug [RHEL-16316](https://issues.redhat.com//browse/RHEL-16316) by explicitly …
=> [release-4.14] OCPBUGS-23208: workaround nmstate bug by configuring ipv{4,6} addresses

templates/common/vsphere/files/vsphere-hostname.yaml
This is a follow up to #3949 as I have introduced bash code that was not syntactically correct.
=> OCPCLOUD-1609: Fix syntax in vsphere-hostname.yaml for CAPI machines

manifests/on-prem/keepalived.conf.tmpl, templates/master/00-master/on-prem/files/keepalived-keepalived.yaml, templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
This PR modifies the label used for an IP address assigned by keepalived to not include the name of the interface. This is because the maximum allowed lenght of the label is 15 characters, causing stuff to fail when interface itself has a name longer than 12 characters.
With this change the label will always be a simple string of length 3 and will not be susceptible to overflow for long NIC names.
Contributes-to: OCPBUGS-23432
=> OCPBUGS-23432: Use shorter IP label for keepalived VIP

templates/common/kubevirt/units/nodeip-configuration.service.yaml
Activate nodeip-configuration for KubeVirt
When creating the node-hint file KubeVirt node select the proper IP for kubelet
kubevirt: Activate nodeip-configuration.service
=> OCPBUGS-23484: kubevirt, Activate nodeip-configuration.service

pkg/daemon/daemon.go, pkg/daemon/update.go
When trying to avoid reboot, current FIPS setting needs to be set into the running machine config configuration.
Merged running node FIPS to old configuration
Test installation with assisted installer on top 4.15 with fips enabled.  Reboot should be skipped
=> OCPBUGS-23255: Add FIPS information to oldconfig when checking if reboot is needed

manifests/machineconfigserver/kube-apiserver-serving-ca-configmap.yaml
Updated annotations in `initial-kube-apiserver-server-ca` configmap so that it can be identified to be created and managed by Machine Config Operator
This adds annotation which identifies the component used to file issues with this certificate. The annotation is verified by [the test](https://github.com/openshift/origin/blob/master/test/extended/operators/certs.go?rgh-link-date=2023-11-21T09%3A53%3A38Z#L130), so that all certificates would be registered and have owners assigned. More metadata would be added later.
See https://github.com/openshift/enhancements/pull/1502 for proposed workflow with TLS registry
=> OCPBUGS-24019: Add ownership annotations to TLS artifacts

pkg/controller/common/metrics.go, pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/drain/drain_controller.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_features.go, pkg/controller/kubelet-config/kubelet_config_nodes.go, pkg/controller/node/node_controller.go, pkg/controller/render/render_controller.go, pkg/controller/template/template_controller.go, pkg/daemon/daemon.go, pkg/daemon/metrics.go, pkg/daemon/update.go, pkg/operator/metrics.go
In this PR, I have enabled several metrics to report key state of the MCC & MCD
- Metrics for MCC sub-controllers
- Introduced state metric: `MCCSubControllerState`, which has label `"subcontroller, state object`, to record the action of the subcontroller on certain object e.g. `machine-config-controller-render Sync Machine Config Pool master timestampA` --> the render controller has synced the master pool at timestamp A. 
- Timestamps for MCD config drifts
- Timestamps for pivot error 
I have also fixed the bug reported in https://issues.redhat.com/browse/OCPBUGS-20427:
Before: when query for `mcc_drain_err`, it returns `no datapoint found`
Now: when query for `mcc_drain_err`, it returns the initial value set until change happened
=> MCO-681, OCPBUGS-20427: Add Key State Metrics, No datapoint found when querying up certain registered metrics

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml, templates/common/on-prem/files/wait-for-br-ex-up.yaml, templates/common/on-prem/units/wait-for-br-ex-up.yaml
In environments with ipv6 (both single and dual stack) we explicitly set the hostname to the FQDN. However, the recent change to make the current hostname static in the node-valid-hostname service[0] has created a conflict with the resolv-prepender script where we force the FQDN. If node-valid-hostname runs before the "up" event for the interface which provides the hostname, it's possible for it to statically set a short name, which prevents the prepender script from later changing it to an FQDN.
This can happen because the up event is asynchronous. The network is marked up before the event is dispatched, and as a result we currently have a race between the event and the node-valid-hostname service. To ensure proper ordering, this change adds a new dependency to node-valid-hostname which …
=> OCPBUGS-22324: Wait for br-ex up event before node-valid-hostname

pkg/upgrademonitor/upgrade_monitor.go
the UpgradeMonitor and the Operator try to create the MCN if they DNE. if the Upgrade Monitor gets there first, it needs to set spec.DesiredConfig to  sane value
=> OCPBUGS-24177: fix race for MCN creation

pkg/controller/common/metrics.go, pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/drain/drain_controller.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_features.go, pkg/controller/kubelet-config/kubelet_config_nodes.go, pkg/controller/node/node_controller.go, pkg/controller/render/render_controller.go, pkg/controller/template/template_controller.go, pkg/daemon/daemon.go, pkg/daemon/metrics.go, pkg/daemon/update.go, pkg/operator/metrics.go
Reverts #3965 ; tracked by [TRT-1375](https://issues.redhat.com//browse/TRT-1375)
10/10 GCP upgrades failed on MCDPivotError firing on the last payload, https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-gcp-ovn-rt-upgrade-4.15-minor-release-openshift-release-analysis-aggregator/1730187997023834112
``` …
```
=> TRT-1375: Revert #3965 "MCO-681, OCPBUGS-20427: Add Key State Metrics, No datapoint found when querying up certain registered metrics"

pkg/daemon/coreos.go
This commit removes the dependency of the imgid field in the coreos aleph file. As per the discussion in the following PR to OSBuild, as decision was made to remove the field:
https://github.com/dustymabe/osbuild/pull/10#issuecomment-1806069282
=> COS-2526: CoreOS: Remove `imgid` field in coreos aleph

pkg/controller/bootstrap/bootstrap_test.go, pkg/controller/kubelet-config/helpers.go, pkg/controller/kubelet-config/kubelet_config_nodes.go, pkg/controller/kubelet-config/kubelet_config_nodes_test.go
NTO is seeing some flakes on rollout of PerformanceProfile custom resources still using cgroupv2 or conflicting kernel arguments.
This PR fixes:
* Node Controller does not update the Node object directly. This causes an additional rollout of the MachineConfig.
* osev1.CgroupModeEmpty did not lay down the default kernel arguments needed by OpenShift. osev1.CgroupModeEmpty is a default and defaults to cgroupv2.
* Fixes bootstrap to lay down the correct kernel arguments without rendering an additional initial MC in the incorrect state.
@yprokule is testing various ZTP scenarios.
```
Fix day-0 and day-2 cgroupv2 MC rollout.
```
=> OCPBUGS-19352: Fix bootstrap with NTO Operator and duplicate MachineConfigs

pkg/daemon/certificate_writer.go, pkg/daemon/constants/constants.go, pkg/daemon/daemon.go, pkg/daemon/drain.go, pkg/daemon/update.go, pkg/server/bootstrap_server.go, pkg/server/cluster_server.go, templates/common/_base/files/additional-trust-bundle.yaml, test/e2e-bootstrap/bootstrap_test.go, test/e2e/mco_test.go
in order to update the system with new cert info, execute update-ca-trust and crio restart when the userCA changes
also add it back to MachineConfig in order to avoid the kubelet going down and the node becoming unreachable. So now, changing this cert causes an update with a new post config action
=> OCPBUGS-24035: execute cert related processes to ensure proper rotation

pkg/controller/node/node_controller.go, pkg/controller/node/node_controller_test.go, pkg/controller/node/status.go, pkg/helpers/helpers.go, pkg/operator/metrics.go, pkg/operator/status.go
This is a stopgap solution to fix the mco_state confusion. Currently, the node reported is not necessarily the node the pool is related to. Adding a node label necessitates some new package level functions to retreive the node. All of this logic is going to stay in pkg/helpers but will be used by the state controller in the future.
=> OCPBUGS-21597: Alleviate confusion over mco_state

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
as well as allow /dev/fuse device access to the runtime class. After this merges, we will stop shipping a crio.conf in the crio rpm
=> OCPNODE-1943: crio: add crun handler to template

pkg/daemon/certificate_writer.go, pkg/daemon/constants/constants.go, pkg/daemon/daemon.go, pkg/daemon/drain.go, pkg/daemon/update.go, pkg/server/bootstrap_server.go, pkg/server/cluster_server.go, templates/common/_base/files/additional-trust-bundle.yaml, test/e2e-bootstrap/bootstrap_test.go, test/e2e/mco_test.go
backport of: #4050 
in order to update the system with new cert info, execute update-ca-trust and crio restart when the userCA changes
also add it back to MachineConfig in order to avoid the kubelet going down and the node becoming unreachable. So now, changing this cert causes an update with a new post config action
=> OCPBUGS-24596: [release-4.14] execute cert related processes to ensure proper rotation

cmd/machine-config-operator/start.go, pkg/operator/operator.go
the MCO logs are spammed regarding an "unknown type" even though the MCN lister isn't added to the `waitForCacheSync` unless the Fg is enabled. Remove it for good measure because this might be causing some upgrade issues. And the lister is unused.
=> OCPBUGS-25144: Remove MCN lister and informer from MCO struct

pkg/daemon/daemon.go
During firstboot, if a kernel argument appears both in the boot command line and in the encapsulated machine config, this kernel argument is duplicated.
The reason for that is that current running configuration is not taken into account when updating the configuration before reboot. The solution is to use the current running configuration when updating during firstboot.
Fixes: OCPBUGS-23085
Use the current running configuration when updating in firstboot.
Add a kernel argument that appears also in the machine-config to firstboot, and see that it is not duplicated after reboot.
Do not duplicate kernel arguments if they are present during firstboot
/cc @sinnykumari
=> OCPBUGS-23085: MCO duplicates kernel arguments during firstboot

pkg/daemon/certificate_writer.go, pkg/daemon/on_disk_validation.go
it seems the certs prior to 4.14 have a \n at the end. We need to tack one onto the end of the data before writing to disk. Also, skip cloudCA on disk validation similarly to how we do for kubelet to avoid a race.
=> OCPBUGS-25245: Add \n in cert_writer for old cert methods and skip cloudCA validation

templates/common/_base/files/apiserver-url-env.yaml
This moves the `apiserv-url-env.yaml` file from the master base files to the common base files. The intention is that rather than applying this file to just the master nodes, that it is present on all nodes.
This is required since the Azure cloud node manager runs on all nodes and relies on the file to understand how to talk to KAS without routing through the CNI. Up until now, a bug in Kubelet has meant that on workers, an IP address was set, allowing CNI to schedule correctly without the CNM initialising the IP addresses on the node. This bug has now been fixed in 1.29 which means the CNM is now a dependency of CNI, meaning it cannot use the cluster network to talk to KAS anymore.
There is code in place already such that this works on master, but it does not work on …
=> OCPBUGS-25412: APIServer URL env should exist on all nodes

templates/common/_base/units/nodeip-configuration.service.yaml, templates/common/on-prem/units/nodeip-configuration.service.yaml, templates/common/vsphere/units/nodeip-configuration-vsphere-upi.service.yaml
When early boot network services get stuck, in some circumstances it can make debugging difficult because it prevents ssh login. This change adds configuration to log their output to the console so it is at least possible to see where the node is stuck when something fails repeatedly.
This is already being done in ovs-configuration, and it makes sense to do it for nodeip-configuration too.
Log nodeip-configuration output to the console for debugging in cases where networking is broken.
=> OCPBUGS-19628: Log network service output to console

templates/common/azure/units/ovs-configuration.service.yaml
ARO's dnsmasq.service, if present, must be run after ovs-configuration. This, could of course be fixed in that service's definition but doing so is not operationally easy to do at this point. There is potential risk that some other dnsmasq.service implementation needs to be run before ovs-configuration and this change would break them. Given the temporal proximity to the breaking change in #3865 lets go ahead and make this.
We should also ensure that ARO makes their service more robust in the future.
Fixes: OCPBUGS-25406
Added dnsmasq.service to the list of units that ovs-configuration.service should run before.
1) Regression test in normal OCP
2) Confirm in ARO that this addresses OCPBUGS-25406, QE should consult with ARO @rogbas and @bennerv good …
=> OCPBUGS-25406: Azure Run ovs-configuration.service before dnsmasq.service

pkg/controller/node/status.go, pkg/controller/template/template_controller.go, pkg/operator/status.go, pkg/operator/sync.go
These had snuck in back in 80e7b4dbdb (#3756), 81136ed1ae (#3770), and similar.  Having the same package imported under multiple names doesn't have any functional impact, but it's less confusing to read if the package is refered to with a consistent prefix.  This commit addresses all the duplicates turned up with:
```console
$ git grep -c '"github.com/openshift/api/machineconfiguration/v1"'  | grep '[.]go:' | grep -v 'vendor/\|:1$'
```
=> NO-ISSUE: pkg: Deduplicate api/machineconfiguration/v1 imports

lib/resourcemerge/machineconfig.go, lib/resourcemerge/meta.go
This PR introduces a missing reconciliation of IPFamilies property in the ControllerConfig. A consequence of the reconciliation missing is that after conversion from single-stack to dual-stack the kubelet is still configured as single-stack because the underlying MCO's variable does not change its value.
With this PR, when converting such a cluster, ControllerConfig will update the value and as a consequence reconfigure kubelet (specifically `--node-ip` param).
Please note with this change we are introducing one reboot to the process of cluster conversion.
Fixes: OCPBUGS-15910
Cherry-picks: https://github.com/openshift/machine-config-operator/pull/3909
=> [release-4.13] OCPBUGS-19658: After dual-stack conversion reconcile IPFamilies

install/0000_80_machine-config-operator_00_clusterreader_clusterrole.yaml, pkg/operator/sync.go, pkg/upgrademonitor/upgrade_monitor.go
the MCN object was not reacting to node deletions. the MCO was also creating these objects too early in their lifecycle. We should only create an MCN  once the node is out of the Provisioning and Pending Status.
=> OCPBUGS-24416: Sync MCN with node creation and deletion

pkg/controller/node/node_controller.go
Currently we allow nodes to exist without being in a pool. If the MCO is managing a node, it needs to be in a pool.
=> OCPBUGS-5452: If node is not in pool, error

test/e2e-layering/onclusterbuild_test.go, test/framework/clientset.go, test/helpers/utils.go
I replaced the calls to oc with native Machine clients for the on-cluster build test.
Run the e2e-gcp-op-layering job. The tests should pass.
Fixes e2e-gcp-op-layering job
=> OCPBUGS-26605: use machine client instead of oc for teardown

cmd/machine-config-controller/start.go, manifests/machineconfigcontroller/clusterrole.yaml, pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
Fixes scale-up issue found here: https://github.com/openshift/machine-config-operator/pull/4083#issuecomment-1864268866
This should only merge after #4083 merges.
This PR changes the way the MCO finds the architecture of a machineset to [this method](https://github.com/openshift/enhancements/pull/1496#discussion_r1368704488). Originally, I was mapping the machineset to a node to determine it. However, for machinesets that have no nodes scaled up yet, this would cause an error, and the very first scale-up would take place with the older boot image. This fix only requires a label on the machineset to determine the architecture, if the label is not present the MCO will default to the control plane architecture.
=> OCPBUGS-25725: ManagedBootImages: failed to fetch architecture type of machineset no linked machine found

pkg/operator/sync.go
To make it easier for cluster admins to discover the management stack for these Secrets.  This will also enable [garbage-collection][1] of these Secrets if the associated MachineConfigPool is removed.
[1]: https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-dependents
=> NO-ISSUE: pkg/operator/sync: Set ownerReferences on *-user-data-managed Secrets

templates/common/aws/files/usr-local-bin-aws-kubelet-nodename.yaml
This typo means that the hostname env var is being overwritten on every reboot, which is not the desired behaviour. The intention is that the file is written once, before Kubelet starts up for the first time, and never modified.
=> OCPBUGS-27261: Fix typo in AWS node env unit

manifests/on-prem/coredns.yaml, templates/common/on-prem/files/coredns.yaml
This is required so that coredns can use the IP information written to that directory.
Fixes: OCPBUGS-22664
=> OCPBUGS-22664: Mount /run/nodeip-configuration into coredns containers

manifests/machineconfigdaemon/daemonset.yaml
CU request to secure cri-o's metrics 9537 port.
kube-rbac-proxy will be added to machine-config-daemon to deploy an RBAC proxy to secure the cri-o metrics port. kube-rbac-proxy will allow us to get TLS, cert rotation, and authz to the crio metrics endpoint. cri-o will change to only listen to 127.0.0.1:9537 (in a followup PR) via configuration (```metrics_host="127.0.0.1"```).
Merge phases are split into 2 section. In phase 1, enable the proxy, then switch CMO to use the new proxy. Both insecure and secure ports (9537 and 9637) are available.
In phase 2, switch cri-o metrics port 9537 to localhost only.
- [MCO#PR4108](https://github.com/openshift/machine-config-operator/pull/4108) (Merge Order **1**, This PR)
- [CRIO#PR7677](https://github.com/cri-o/cri-o/pull/7677) (Merge Order **1**)
- …
=> OCPNODE-2021: add crio-kube-rbac-proxy

pkg/controller/template/render.go, pkg/controller/template/render_test.go, templates/common/aws/files/etc-kubernetes-credential-providers-ecr-credential-provider.yaml, templates/master/01-master-kubelet/_base/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
Adds configuration for the ECR credential provider to kubelet on AWS.
Unit tests show new flags being set correctly.
Depends on the ecr-credential-provider RPM shipping in RHCOS, this is currently a WIP.
/hold
Kubelet should be able to pull an image from a private ECR registry.
=> OCPBUGS-25662: Add Image Credential Provider flags for Kubelet on AWS

go.mod, go.sum, pkg/daemon/daemon.go, pkg/daemon/image-inspect.go, pkg/daemon/rpm-ostree.go, vendor/github.com/containers/common/LICENSE, vendor/github.com/containers/common/pkg/retry/retry.go, vendor/github.com/containers/common/pkg/retry/retry_linux.go, vendor/github.com/containers/common/pkg/retry/retry_unsupported.go, vendor/modules.txt
Manual 4.12 cherry-pick of https://github.com/openshift/machine-config-operator/pull/3413
~~had to bump `go-health` because it had dependency issues~~
=> [release-4.12] OCPBUGS-14071: Imageinspect takes type of error into account, drop podman inspect fallback

pkg/controller/container-runtime-config/helpers.go, pkg/controller/container-runtime-config/helpers_test.go
Fix conflicting mirrorSourcePolicy error prompt to include imagecontentsourcepolicies
=> OCPBUGS-27190: Fix mirrorSourcePolicy error prompt imagecontentsourcepolicies

pkg/apis/machineconfiguration.openshift.io/v1/types.go, pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go, pkg/controller/container-runtime-config/container_runtime_config_bootstrap.go, pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/container-runtime-config/helpers.go, pkg/controller/container-runtime-config/helpers_test.go
Backport API fix https://github.com/openshift/api/pull/1656
Change the type of OverlaySize and LogSizeMax resource.Quantity to pointer *resource.Quantity.
the struct type will be set as 0 automatically when retrieving the ctrcfg object.
```
kind: ContainerRuntimeConfig
metadata:
name: pidlimit
spec:
matchLabels:
pools.operator.machineconfiguration.openshift.io/worker: '' 
containerRuntimeConfig:
pidsLimit: 4096 
logLevel: debug
$ oc get containerruntimeconfig  pidlimit -o json | jq '.spec.containerRuntimeConfig'
{
"logLevel": "debug",
"logSizeMax": "0",
"overlaySize": "0",
"pidsLimit": 4096
}
$ oc get containerruntimeconfig  pidlimit -o json | jq …
```
=> [release-4.14]OCPBUGS-27178: use *resource.Quantity to not automatically set 0

Dockerfile, Dockerfile.rhel7, pkg/daemon/daemon.go
After nmstate 2.2.10, nmstate changed its persistent NIC names logic to:
1. Before upgrade, `nmstatectl persist-nic-names` will pin ALL ethernet interfaces using its firmware MAC address.
2. After upgrade, `nmstatectl persist-nic-names --cleanup` will remove systemd .link files which has no effect.
This patch replaced the old nmstate persist-nic-names workflow with above.
The clean up error will be ignored as nmstatectl will fail if stamp file or `ROOT/etc/systemd/network` folder not found.
Backport of https://github.com/openshift/machine-config-operator/pull/4020
=> [OCP 4.14] OCPBUGS-24660: daemon: Add support for new nmstate logic

manifests/machineconfigdaemon/role.yaml, manifests/machineconfigdaemon/rolebinding.yaml, pkg/daemon/daemon.go, pkg/daemon/drain.go, pkg/daemon/drain_test.go, pkg/daemon/update.go, pkg/operator/sync.go
The MCO logic today allows users to not reboot when changing the registries.conf file (through ICSP/IDMS/ITMS objects), but the MCO will sometimes drain the node if the change is deemed "unsafe" (deleting a mirror, for example).
This behaviour is very disruptive for some customers who with to make all image registries changes non-disruptive. With this PR they can create a ConfigMap and override the drain check.
Also add rbac for MCD to only read MCO-namespaced ConfigMaps.
To be used with support exception only.
Testing steps:
create ICSP/IDMS/ITMS, e.g.
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
name: quay-mirror
spec:
repositoryDigestMirrors:
- mirrors:
- my-quay.io.mirror
source: quay.io
```
apply the configmap
```
apiVersion: v1
kind: …
```
=> OCPBUGS-27508: daemon: allow the user to override drains on IR changes

install/0000_90_machine-config-operator_01_prometheus-rules.yaml, pkg/daemon/daemon.go, pkg/daemon/metrics.go
the error for when a MachineConfig is missing is very vague. Usually the error has little to do with the cause. Specify steps users can take to alleviate the situations.
=> OCPBUGS-17788: Improved error handling for missing MC

templates/master/01-master-kubelet/_base/units/kubelet-cleanup.service.yaml, templates/master/01-master-kubelet/_base/units/kubelet.service.yaml, templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml, templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/_base/units/kubelet-cleanup.service.yaml, templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
The original kubelet.service definition deletes the cpu and memory manager state files on every kubelet restart. That causes a loss of cpu manager information and new cpu allocations the pods are not expecting.
Splitting the kubelet.service into two parts should fix this.
Make sure the cpu and memory manager state files are not present when kubelet is starting for the first time after a node reboot.
Restarting kubelet should not change cpu affinity of already running pods. 
Kubelet systemd service definitions were updated:
- kubelet.service no longer deletes the state files on restart
- kubelet-cleanup.service is an oneshot before=kubelet service that only executes once at boot and performs the state files cleanup …
=> OCPBUGS-24366: Delete state files on reboot only

install/0000_80_machine-config-operator_04_deployment.yaml, manifests/machineconfigcontroller/deployment.yaml, manifests/machineconfigdaemon/daemonset.yaml
All openshift operators must include FallbackToLogsOnError to ease debugging.
=> OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

pkg/apis/machineconfiguration.openshift.io/v1/types.go, pkg/apis/machineconfiguration.openshift.io/v1/zz_generated.deepcopy.go, pkg/controller/container-runtime-config/container_runtime_config_bootstrap.go, pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/container-runtime-config/helpers.go, pkg/controller/container-runtime-config/helpers_test.go
Backport API fix https://github.com/openshift/api/pull/1656 to 4.13
=> [release-4.13]OCPBUGS-27816: use *resource.Quantity to not automatically set 0

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml, templates/common/on-prem/files/resolv-prepender.yaml
Currently the resolv-prepender dispatcher script starts the systemd service and then waits for it to complete. This can cause the dispatcher script to time out if the runtimecfg image pull is slow or if resolv.conf does not get populated in a timely fashion (it's not entirely clear to me why the latter happens, but it does). This can cause configure-ovs to time out if there are a large number of interfaces on the system triggering the dispatcher script, such as when there are many VLANs configured.
To avoid this, we can stop waiting for the systemd service in the dispatcher script. In fact, there's an argument that we shouldn't wait since we need to be able to handle asynchronous execution anyway for the slow image pull case (which was the entire reason the script was split into a service …
=> OCPBUGS-25753,OCPBUGS-22721: Run resolv-prepender entirely async

install/0000_80_machine-config-operator_00_namespace.yaml, manifests/cloud-platform-alt-dns/coredns-corefile.tmpl, manifests/cloud-platform-alt-dns/coredns.yaml, manifests/controllerconfig.crd.yaml, pkg/controller/template/render.go, pkg/operator/bootstrap.go, pkg/operator/render.go, pkg/operator/render_test.go, pkg/operator/status.go, templates/common/cloud-platform-alt-dns/files/coredns-corefile.yaml, templates/common/cloud-platform-alt-dns/files/coredns.yaml
Based on enhancement : https://github.com/openshift/enhancements/pull/1468
Verification still in-progress.
These changes allow MCO to read an optional configmap containing the LB IPs of the LBs configured on cloud platforms, to be used to generate in-cluster DNS for API and API-Int URLs.
Contains implementation for [CORS-2814](https://issues.redhat.com//browse/CORS-2814), [CORS-2815](https://issues.redhat.com//browse/CORS-2815) and [CORS-3169](https://issues.redhat.com//browse/CORS-3169)
=> CORS-2814: Add support for in-cluster DNS on Cloud Platforms when cloud DNS cannot be used

pkg/controller/common/layered_node_state.go, pkg/controller/common/layered_node_state_test.go, pkg/controller/node/node_controller_test.go, pkg/controller/node/status_test.go
The `isNodeUnavailable()` code was not taking the `currentImage` / `desiredImage` annotations into consideration when it determines if the node should be considered unavailable. While opting into on-cluster builds, the following would happen:
1. A node gets updated with the `desiredImage` annotation, indicating that the MCD should transition it to an image.
2. There is a lag between when this annotation is applied and the MCD transitions from "Done" -> "Working".
3. During this lag period, the NodeController may re-enter the sync loop.
4. Because the MCD state has not transitioned yet to "Working" yet and we were not considering the currentImage / desiredImage annotations, the NodeController will apply the `desiredImage` annotation to another node instead.
This adds a …
=> OCPBUGS-24705: consider currentImage and desiredImage annotations

templates/common/_base/files/configure-ovs-network.yaml
When converting a VLAN connection to a bridge, the case when the target connection `vlan.parent` has been configured with a connection UUID needs to be managed as a special case, as the bridge connection has to target the underlying device instead of a connection UUID.
Use `nmcli connection show uuid <X>` to verify X is a connection UUID.
Previous condition `nmcli connection show <X>` evaluates to true if X is either a connection name, a UUID or a connection path. This happens to break when there are two connections with the same name, e.g.:
```
NAME        UUID                                  TYPE      DEVICE
bond0.3810  5960c784-fe08-45ec-ab4d-7c68edb4c0bc  vlan      bond0.3810
bond0       313f4e8e-f950-4a59-8015-0359675758d6  bond      bond0
bond0 …
```
=> OCPBUGS-24356: ovs-configure: fix `vlan_parent` calculation

Dockerfile, Dockerfile.rhel7, cmd/machine-config-daemon/firstboot_complete_machineconfig.go, pkg/daemon/daemon.go
After nmstate 2.2.10, nmstate changed its persistent NIC names logic to:
1. Before upgrade, `nmstatectl persist-nic-names` will pin ALL ethernet interfaces using its firmware MAC address.
2. After upgrade, `nmstatectl persist-nic-names --cleanup` will remove systemd .link files which has no effect.
This patch replaced the old nmstate persist-nic-names workflow with above.
Backport of https://github.com/openshift/machine-config-operator/pull/4020
=> [OCP-4.13] OCPBUGS-24661: daemon: Add support for new nmstate logic

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Migrate crio metrics to localhost only.
/hold until https://github.com/openshift/cluster-monitoring-operator/pull/2229 merges
=> OCPNODE-2024: crio: migrate metrics port to localhost only

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Reverts openshift/machine-config-operator#4164
=> OCPBUGS-29098: Revert "OCPNODE-2024: crio: migrate metrics port to localhost only"

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
cherry-pick of https://github.com/openshift/machine-config-operator/pull/4116
related to https://issues.redhat.com/browse/SUPPORTEX-17246
=> OCPSTRAT-1062: [4.15] crio: enable log linking by default in 4.15

templates/common/on-prem/files/coredns.yaml, templates/common/on-prem/files/keepalived.yaml, templates/master/00-master/on-prem/files/haproxy.yaml
In order for static pods to use reserved CPUs according to the workload partitioning, we are adding a `PreferredDuringScheduling` annotation.
Closes: OCPBUGS-26951
=> OCPBUGS-26951: annotate on-prem static pods for workload partitioning

manifests/machineconfigdaemon/daemonset.yaml
Removes the kube-rbac-proxy for the crio port from the MCD.
#4175 will likely supersede with a static pod solution.
=> NO-JIRA: remove kube-rbac-proxy for crio port

Makefile, pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go, test/e2e-techpreview/helpers_test.go, test/e2e-techpreview/main_test.go, test/e2e-techpreview/msbic_test.go, test/e2e-techpreview/onclusterbuild_test.go, test/helpers/utils.go
This PR does a few things:
- Removes excessive no-op syncs for the boot image controller
- Renames the existing `e2e-layering` test suite which runs under TechPreviewNoUpgrade feature gate to `e2e-techpreview`
- Add a new e2e test to verify boot image reconciliation in the `e2e-techpreview` test suite
How to test:
`e2e-gcp-op-layering`/`e2e-gcp-op-techpreview` should succeed.
This PR will pair with https://github.com/openshift/release/pull/48618, which renames the test under the release repo. This PR should land first.
=> MCO-774: Write e2e tests for bootimage management

templates/master/00-master/on-prem/files/keepalived-keepalived.yaml, templates/master/00-master/on-prem/files/keepalived-mcs-script.yaml
We need to ensure that machine-config-server is available from the API VIP. Up to now we've been relying on the fact that normally MCS is running on all control plane nodes so it doesn't matter which one holds the VIP, but there are circumstances (such as disaster recovery) where not all MCS instances will be running.
Unfortunately, we don't have access to the MCS from deployed nodes for security reasons. Because of this, it's not possible to simply add it to the HAProxy configuration like we would for an external loadbalancer. It's not even possible to call it from the check script and ensure that it's responding. The best we can do is look for the container (similar to what we do for the default ingress pod) and assume that MCO is healthchecking it appropriately and will restart it if …
=> OCPBUGS-18940: Add keepalived healthcheck for machine-config-server

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
NetworkManager starting from 1.42.2-12.el9_2 and 1.36.0-17.el8_6 adds a new event `dns-change` which is fired whenever a change to the DNS configuration happens. Thanks to this we no longer need to piggyback on other events (like `up` or `dhcp-change`) to detect when we need to potentially fix the content of `/etc/resolv.conf`.
This change will reduce the overall number of calls to `resolv_prepender` as now it will be called only if DNS configuration could have been changed.
We are still keeping the timeout for the `resolv_prepender` function because it is not expected that it would be running for longer than one minute.
Closes: [OPNET-355](https://issues.redhat.com//browse/OPNET-355)
=> OPNET-355: Use NM's dns-change event for resolv.conf

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml, templates/common/on-prem/files/wait-for-br-ex-up.yaml, templates/common/on-prem/units/wait-for-br-ex-up.yaml
This reverts commit c558cc6bc72d40a243dc22f507decb89b2293bae and adds a commit to fix the problem that prompted the revert in the first place. Now the service will be disabled for all CNI plugins except OVNKubernetes.
=> OCPBUGS-22324: Revert "Revert "Merge pull request #4028 from cybertron/wait-for-br-ex""

templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
Because resolv-prepender can run very early in boot and it pulls an image, it can interfere with the functioning of the crio-wipe service after an unclean shutdown (such as a power outage). To avoid this, we can add a dependency to ensure crio-wipe will always complete before we start resolv-prepender.
Added dependency on crio-wipe to resolv-prepender.
=> OCPBUGS-27162: Add dependency on crio-wipe to resolv-prepender

Makefile, test/e2e-techpreview-shared/README.md, test/e2e-techpreview-shared/noop_test.go
This PR adds a new test package, `e2e-techpreview-shared`. This test package should be used for e2e tests that need to be tested under the default featureset and the techpreview featureset. This would mean that your test 
has two paths, one when the feature gate is enabled and one when the feature gate is disabled. Tests added here will run under the test-e2e and test-e2e-techpreview Makefile targets, which is used by ci/prow/e2e-gcp-op and ci/prow/e2e-gcp-op-techpreview test suites respectively.
This PR also removes the old makefile target for e2e-gcp-op-layering which has now been repurposed into e2e-gcp-op-techpreview. 
This should merge after https://github.com/openshift/release/pull/48618 merges.
- tests, including the new …
=> NO-ISSUE: add e2e-techpreview-shared, remove layering test target

templates/common/_base/files/nmstate-service-keep-state-file-after-apply.yaml
When https://github.com/nmstate/nmstate/pull/2546 land to RHCOS the nmstate service will go back to previous behaviour, the /etc/nmstate/*.yml files are moved to .applied files, so we need to configure nmstate to keep the those files, if we don't do so MCO complains at in place upgrades since the file system has change.
The original in place problem is described at https://github.com/nmstate/nmstate/pull/2499:
```
At some envs like openshift machine-config-operator moving configuration files can break in place upgrades. This change use symlinks instead of rename to mark a .yml file as applied so the original file is preserved.
```
And the original issue was:
https://issues.redhat.com/browse/RHEL-19680
=> NO-JIRA: nmstate, configure nmstate to keep service yamls

Dockerfile.proxy, docs/openshift-proxy-pull-test.md
openshift-proxy-pull-test image was not used in the code, remove the image openshift-proxy-pull-test-container from the build, so we will not be affected by the possible bugs during the image build.
Created [ART-8371](https://issues.redhat.com/browse/ART-8371) to ask the ART team to remove the image openshift-proxy-pull-test
revert https://github.com/openshift/machine-config-operator/pull/2602
=> OCPNODE-1877: Delete image openshift/openshift-proxy-pull-test

templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
With this PR we are leveraging the systemd `on-failure` restart mode for on-prem-resolv-prepender service to make it more robust for cases when we didn't manage to successfuly configure DNS.
This has been implemented for `oneshot` service types already long time ago via https://github.com/systemd/systemd/pull/13754.
Contributes-to: OCPBUGS-29624
=> OCPBUGS-29624: Restart resolv-prepender on failure

templates/common/on-prem/files/resolv-prepender.yaml
With this change the resolv-prepender script will apply DNS changes only when DNS servers actually changed. This will significantly reduce the number of `nmcli` calls and remove scenarios in which we can end up in the infinite loop of resolv-prepender calls.
Fixes: [OPNET-469](https://issues.redhat.com//browse/OPNET-469)
Relates-to: OCPBUGS-29624
=> OCPBUGS-29659: Apply new DNS configuration only if changed

templates/common/on-prem/files/resolv-prepender.yaml
PR #4196 made this conditional based on whether changes were actually made to resolv.conf. Unfortunately, because resolv.conf is persistent over reboots this means that we never touch it after the initial deployment and as a result on subsequent boots kubelet will never start because the file is never created.
Because we don't care whether changes were actually made, only that resolv.conf is correctly generated, we can move this file creation out of the if block and always do it to fix the problem.
Note that this probably does not happen with OVNKubernetes because the creation of br-ex triggers DNS changes (it gets cleared and then re-populated) so this is only relevant for OpenShiftSDN-based envs.
=> OCPBUGS-29732: Always touch resolv-prepender file at end of script

.snyk
In order to get a baseline setup for automated Snyk security scans on each PR, I added a .snyk file to our repository root to ignore certain directories and files.
Once https://github.com/openshift/release/pull/47445 lands, one can run the security job that PR creates. The security job should pass.
Enable automated Snyk security scans
=> MCO-998: sets up MCO repository for Snyk CI scans

templates/master/01-master-kubelet/_base/files/kubelet.yaml, templates/worker/01-worker-kubelet/_base/files/kubelet.yaml
with nodeStatusUpdateFrequency set to 10s, the report freq no longer gets set to 5m. We need to do this manually.
=> OCPBUGS-29713: set nodeStatusReportFrequency

manifests/cloud-platform-alt-dns/coredns.yaml
Fixes OCPBUGS-29067
Adds HostToContainer mount propogation to hostPath volumeMounts in the CoreDNS pod definition used for cloud platforms.
This fixes the issue where kubeconfig was unavailable to `runtimecfg render` initContainer within the CoreDNS pod running on the bootstrap node for platform GCP.
=> OCPBUGS-29067:  Add HostToContainer propogataion for coreDNS pods on cloud platforms

pkg/operator/sync.go, pkg/upgrademonitor/upgrade_monitor.go
for garbage collection, MCN object needs node as its owner.
=> OCPBUGS-30090: add node owner to MCN

pkg/daemon/update.go, pkg/daemon/update_test.go
Inside the `podmanCopy` function, a check has been added to test whether a container image is present on the local system before pulling it.  With this change we avoid downloading the image if it is not necessary.
=> OCPBUGS-29946: Prevent pull images in podmanCopy if they are present

pkg/operator/sync.go, pkg/upgrademonitor/upgrade_monitor.go
The same thing happens with MCN objects sometimes. The easiest solution is to hardcode the group and kind (since they don't change)
=> OCPBUGS-30136: APIVersion and Kind sometimes are empty when listing objects

pkg/controller/template/render.go, pkg/controller/template/render_test.go, templates/common/gcp/files/etc-kubernetes-credential-providers-gcr-credential-provider.yaml
Adds configuration for the GCR credential provider to kubelet on GCP
Unit tests show new flags being set correctly.
Builds on  #4103
Depends on the gcr-credential-provider RPM shipping in RHCOS.
Kubelet should be able to pull an image from a private GCR registry.
Adds support for GCP gcr credential provider
=> OCPCLOUD-2465: Add Image Credential Provider flags for Kubelet on GCP

install/0000_90_machine-config-operator_01_prometheus-rules.yaml, pkg/controller/common/metrics.go, pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
- Added a new prometheus metric that counts MSBIC failures to update boot images per machineset. 
- Added a new prometheus rule that creates an alert if there are sustained failures on a machineset for longer than 30 minutes
Open to changing the alerting expression/time interval, this is just a starting point (: 
Break anything that is necessary for machineset reconciliation. I tested this via removing patch powers for the MCC in RBAC, breaking JSON marshalling for the `coreos-bootimages` configmap.(Both require scaling down the CVO) There are probably simpler ways I hadn't thought of!
=> MCO-898: OCPBUGS-29857: OCPBUGS-29819: Implement an alerting mechanism for boot image update failures

Makefile, cmd/machine-config-daemon/start.go, install/0000_80_machine-config-operator_00_service.yaml, manifests/machineconfigcontroller/clusterrole.yaml, manifests/machineconfigdaemon/daemonset.yaml, manifests/machineconfigdaemon/role.yaml, manifests/machineconfigserver/clusterrole.yaml, pkg/controller/common/constants.go, pkg/controller/common/helpers.go, pkg/controller/node/node_controller.go, pkg/daemon/certificate_writer.go, pkg/daemon/constants/constants.go, pkg/daemon/daemon.go, pkg/daemon/update.go, pkg/operator/operator.go, pkg/operator/sync.go, pkg/server/cluster_server.go, pkg/server/server.go, test/e2e-shared-tests/helpers.go, test/e2e-shared-tests/mcd_config_drift.go, test/helpers/utils.go
this PR is supposed to merge before #4104. This does not follow the MCO's current cert path but does ensure a backport for 4.15/14/13 since we are not bumping the API at all.
when the api-int CA syncs we write to an mco namespaced configmap with the data (this is so the daemon only needs a role for reading MCO configmaps). We also need to add an annotation to the controllerconfig via the operator when this api-int CA rotates. This will trigger the daemons syncControllerConfig loop without actually modifying the controllerconfig API type (we will do this in future ocp versions). We then read from the configmap we just wrote to in the operator if it exists and if the annotation on the controllerconfig is set, and do some kubeconfig related tasks in the daemon's cert writer.
In this PR we …
=> OCPBUGS-25821: backportable version of api-int cert work

pkg/controller/template/render.go, pkg/controller/template/render_test.go, templates/common/azure/files/etc-kubernetes-credential-providers-acr-credential-provider.yaml
Adds configuration for the ACR credential provider to kubelet on Azure
Unit tests show new flags being set correctly.
Builds on  #4103
Depends on the acr-credential-provider RPM shipping in RHCOS.
Kubelet should be able to pull an image from a private ACR registry.
Adds support for azure acr credential provider
=> OCPCLOUD-2462: Add Image Credential Provider flags for Kubelet on Azure

lib/resourcemerge/machineconfig.go, lib/resourcemerge/meta.go
This PR introduces a missing reconciliation of IPFamilies property in the ControllerConfig. A consequence of the reconciliation missing is that after conversion from single-stack to dual-stack the kubelet is still configured as single-stack because the underlying MCO's variable does not change its value.
With this PR, when converting such a cluster, ControllerConfig will update the value and as a consequence reconfigure kubelet (specifically `--node-ip` param).
Please note with this change we are introducing one reboot to the process of cluster conversion.
Fixes: OCPBUGS-15910
Cherry-picks: https://github.com/openshift/machine-config-operator/pull/3909
=> [release-4.12] OCPBUGS-19659: After dual-stack conversion reconcile IPFamilies

pkg/controller/container-runtime-config/OWNERS, templates/master/01-master-container-runtime/OWNERS, templates/worker/01-worker-container-runtime/OWNERS
Syncing CRI-O config owners defined in:
https://github.com/cri-o/cri-o/blob/main/OWNERS_ALIASES
Leaving out folks which are not associates of Red Hat.
cc @mrunalp @giuseppe @haircommander @kolyshkin @nalind @umohnani8 @mtrmac @QiWang19 @hasan4791 @kwilczynski @sohankunkerkar @wgahnagl
=> NO-JIRA: Sync CRI-O owners

templates/common/_base/units/ovs-configuration.service.yaml, templates/common/azure/units/ovs-configuration.service.yaml
Kdump will generate it's initramfs based on the running state when kdump.service run If OVS has already run, the kdump fails to gather a working network config, which prevent network log exports, sush as SSH.
See https://issues.redhat.com/browse/OCPBUGS-28239
Ideally we would need that to be backported to 4.14, otherwise I will add a systemd drop-in as a workaround in RHCOS
=> OCPBUGS-30239: Prevent OVS-configuration to run before kdump

templates/common/gcp/files/etc-kubernetes-credential-providers-gcr-credential-provider.yaml
This change updates the GCR CredentialProviderConfig to pass the 'get-credentials' argument, which is required for the credential plugin to function correctly.
It also adds a matcher for "*.pkg.dev"
- Enable the `DisableKubeletCloudCredentialProviders` feature flag
- Create a deployment that pulls from a private GCR image
- Verify the image does not fail to pull
Updates GCR CredentialProviderConfig, passing 'get-credentials' and updating matchers
=> OCPCLOUD-2465: Updates GCR CredentialProviderConfig

templates/common/_base/units/crio.service.yaml, templates/common/_base/units/firstboot-osupdate.target, templates/common/_base/units/kubelet-auto-node-size.service.yaml, templates/common/_base/units/kubelet-dependencies.target.yaml, templates/common/_base/units/machine-config-daemon-firstboot.service.yaml, templates/common/_base/units/machine-config-daemon-pull.service.yaml, templates/common/_base/units/mtu-migration.service.yaml, templates/common/_base/units/node-valid-hostname.service.yaml, templates/common/_base/units/nodeip-configuration.service.yaml, templates/common/_base/units/ovs-configuration.service.yaml, templates/common/alibabacloud/units/alibaba-kubelet-nodename.service.yaml, templates/common/aws/units/aws-kubelet-nodename.service.yaml, templates/common/aws/units/aws-kubelet-providerid.service.yaml, templates/common/azure/units/ovs-configuration.service.yaml, templates/common/gcp/units/gcp-hostname.service.yaml, templates/common/on-prem/units/nodeip-configuration.service.yaml, templates/common/openstack/units/openstack-kubelet-nodename.service.yaml, templates/common/vsphere/units/vsphere-hostname.service.yaml, templates/master/00-master/alibabacloud/units/openshift-alibabacloud-routes.path.yaml, templates/master/00-master/azure/units/openshift-azure-routes.path.yaml, templates/master/00-master/azure/units/openshift-azure-routes.service.yaml, templates/master/01-master-kubelet/_base/units/kubelet.service.yaml, templates/master/01-master-kubelet/alibabacloud/units/kubelet.service.yaml, templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/alibabacloud/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Manual backport of https://github.com/openshift/machine-config-operator/pull/4043 and https://github.com/openshift/machine-config-operator/pull/4115 (needed to avoid [regression](https://issues.redhat.com/browse/OCPBUGS-26240) on Azure).
=> [release-4.12] OCPBUGS-30823: Introduce kubelet-dependencies.target and firstboot-osupdate.target

pkg/controller/build/build_controller.go, pkg/controller/build/build_controller_test.go, pkg/controller/common/constants.go, pkg/controller/common/helpers.go
trigger a rebuild by adding the machineconfiguration.openshift.io/rebuildImage label to the specified pool this will delete any existing build objects for an MCP and start a new one in the traditional manner.
=> MCO-760: add rebuild mechanism to ocb

Makefile
Hardcoded setup-envtools to a version right before [the go bump](https://github.com/kubernetes-sigs/controller-runtime/pull/2693) to 1.22. As a result, this will have to manually updated along with a kube bump to keep up as we will no longer be using the @latest tag
`make verify` should pass
=> OCPBUGS-31365: make verify should use MCO's kube version

templates/common/on-prem/files/keepalived.yaml, templates/master/00-master/on-prem/files/keepalived-keepalived.yaml, templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Previously, because we had weights set for both check scripts for ingress, keepalived would always assign the ingress VIP somewhere, even if there were no ingress controllers available. While normally this is not a problem, this behavior is not ideal in circumstances such as remote workers where one worker per remote subnet will take the VIP because they can't coordinate with the other subnets.
The advantage of removing the weight from the check script is that if there is no ingress controller running on the node it will never take the VIP, even if no other node in the cluster has taken it. This allows us to deploy remote workers without the extra step of disabling keepalived. As long as the ingress pods are deployed to the correct nodes keepalived will handle assigning the VIP on its …
=> OPNET-303,OCPBUGS-25744: Remove weights from ingress check script

templates/common/_base/files/configure-ovs-network.yaml
Up until now, configure-ovs would use nmcli to generate the profiles in /etc/NetworkManager/system-connections and then at the very end it would move them to /run/NetworkManager/system-connections
The problem with this is that if configure-ovs was killed due to a hard power off, it could leave half baked profiles in /etc preventing a subsequent reboot from reaching a network-online state and running configure-ovs again.
This change makes use of the --temporary and --offline flags of nmcli to generate the profiles directly in /run to prevent that problem.
If configure-ovs is explicitly configured to generate profiles in /etc it would then move them at the very end to /etc. This is subject to the problem state above but since it is not the default let's not worry too much about it.
=> OCPBUGS-27316: configure-ovs: generate profiles directly in /run

pkg/operator/status.go, pkg/operator/status_test.go, pkg/operator/sync.go
I refactored ApplyManifests by hoisting the waitForDaemonsetRollout call to the syncMachineConfigxxx function as this is more consistent with the other sync functions. This also makes the retry action cleaner by not multiplying the final wait timeout. Retry only takes place on rpc errors and resource conflicts, for all other cases, an immediate degrade takes place. Operator will no longer report Available=False for any case.
This is slightly hard to test right now as these rpc errors/resource conflicts aren't as prevalent on 4.14+.
=> OCPBUGS-9108: OCPBUGS-24228: Make MCO operator always Available, add retry to applyManifests before degrading

pkg/daemon/certificate_writer.go, pkg/server/cluster_server.go, pkg/server/server_test.go
Reverts a recent change where we stuffed in the full kubeconfig from the apiserver-server-ca instead of using the mounted node-bootstrapper token. The caData should still be up to date, but we go back to using node-bootstrapper for node scaling so it can get the CSR auto-appoved.
=> OCPBUGS-31067: server: still serve kubeconfig with node-bootstrapper-token

templates/master/01-master-kubelet/_base/files/criometricsproxy.yaml, templates/worker/01-worker-kubelet/_base/files/criometricsproxy.yaml
workload partitioning ignores the init container setup, because it does not contain resources.requests due to them being in the wrong indentation level
Correct indentation level for resources
init container `setup` should have correct resource requests applied
Fixed incorrect indentation for `setup` container in pod `kube-rbac-proxy-crio` template.
=> OCPBUGS-31630: fix: resources were in the wrong indentation level

pkg/operator/sync.go
We have handling in the build controller to error if we get invalid settings. However, there is no explicit code in the MCO to degrade if someone gives us bad settings. Something like push or pull secrets might get caught due the the objects not existing, but for some reason image builder type sneaks through.
Add a check at the end of `reconcileMachineOSBuilder` to validate the config.
=> OCPBUGS-18955: make sure CO degrades if OCL config is invalid

templates/common/_base/files/configure-ovs-network.yaml
Avoid failing the condition if `ovs-if-br-ex.nmconnection.J1K8B2` like file present in the `${NM_CONN_CONF_PATH}` as `${new_conn_files[0]}` from the next step takes only the first file that does not have the extra extension.
```
touch /etc/NetworkManager/system-connections/ovs-if-br-ex.nmconnection.J1K8B2
systemctl restart ovs-configuration.service
```
=> OCPBUGS-22910: Remove the condition for checking the multiple ovs-if-br-ex profiles

.ci-operator.yaml, Dockerfile, Dockerfile.rhel7, pkg/daemon/daemon.go
I updated the Dockerfile to use RHEL 9 as the primary base image for building the Machine Config Operator (MCO) components, ensuring compatibility with RHEL 9 environments. Additionally, I modified the ReexecuteForTargetRoot function within the MCO to correctly identify and use the corresponding MCO daemon binaries based on the underlying OS version, addressing the transition between RHEL 8 and RHEL 9 nodes. Lastly, I modified and updated the go dependencies.
1. Build the MCO container image using the updated Dockerfile and verify that it successfully creates images with the correct RHEL 9 base and includes RHEL 8 MCO daemon binaries.
2. Deploy the updated MCO on a mixed environment (with both RHEL 8 and RHEL 9 nodes) and validate that it can …
=> OCPBUGS-28577: MCO-1030, MCO-910: Updating MCO base image to RHEL9

templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
This was the correct key in the wrong section. Moving it to Unit fixes the warning at start and also will hopefully fix the upgrade issue we're hitting where resolv-prepender restarts too quickly and gets stopped permanently by systemd.
=> OCPBUGS-30192: Move StartLimitIntervalSec to Unit section

templates/common/cloud-platform-alt-dns/files/coredns.yaml, templates/common/on-prem/files/coredns.yaml, templates/common/on-prem/files/keepalived.yaml, templates/master/00-master/on-prem/files/haproxy.yaml, templates/master/01-master-kubelet/_base/files/criometricsproxy.yaml, templates/worker/01-worker-kubelet/_base/files/criometricsproxy.yaml
These appear to be static pods, but they're missing the termination failure policy, so I've updated them too.  I think I see these active on openstack.
=> OCPBUGS-28230: enforce termination message policy on all platform pods

templates/common/on-prem/files/configure-ip-forwarding.yaml
- Check if the file exists before appending
- In the IPv6-disabled node, the `/proc/sys/net/ipv6` path will not exist.
=> OCPBUGS-32278: Fix configure-ip-forwarding.sh

Dockerfile, Dockerfile.rhel7
Go is very good about doing incremental builds, provided that it has a build cache that it can access. This is why once you've performed an initial `$ go build .`, future runs are much faster since it will only rebuild changes. Because of how our Dockerfile is written, it cannot take advantage of that caching. Each build takes place against an empty cache, which means that it must perform a full build every time. Recently, I learned that one can mount a cache into the build context at an arbitrary path by adding a  `--mount` flag to any `RUN` directive.
Doing this and using separate cache paths for the RHEL8 and RHEL9 builds in our Dockerfile, Podman can mount a cache directory at build-time that the Go toolchain can use to cache incremental build objects. Additionally, …
=> MCO-1117: Make local MCO image builds faster

cmd/machine-config-operator/start.go, pkg/controller/kubelet-config/helpers.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_controller_test.go, pkg/controller/kubelet-config/kubelet_config_features_test.go, pkg/controller/kubelet-config/kubelet_config_nodes_test.go, pkg/operator/operator.go, pkg/operator/status.go, pkg/operator/sync.go
Enables ClusterFleetEvaluation logic within MCO. This PR adds flags for `failswapon`, `cgroupsv1`, and `runc`.
```
❯ oc get clusteroperators.config.openshift.io machine-config -o yaml | grep EvaluationConditionsDetected -B 3
- lastTransitionTime: "2024-04-12T13:03:04Z"
reason: AsExpected
status: "False"
type: EvaluationConditionsDetected
❯ cat worker-kube-config.yaml 
metadata:
name: set-worker-kube-config
spec:
matchLabels:
kubeletConfig:
failSwapOn: false
❯ oc create -f worker-kube-config.yaml 
❯ oc get clusteroperators.config.openshift.io machine-config -o yaml | grep EvaluationConditionsDetected -B 3
- lastTransitionTime: …
```
=> OCPBUGS-32138: add cluster fleet evaluation support to mco

cmd/machine-config-daemon/start.go, manifests/machineconfigdaemon/clusterrole.yaml, pkg/apihelpers/apihelpers.go, pkg/controller/common/helpers.go, pkg/daemon/constants/constants.go, pkg/daemon/daemon.go, pkg/daemon/daemon_test.go, pkg/daemon/drain.go, pkg/daemon/update.go, pkg/daemon/upgrade_monitor_test.go, pkg/operator/operator.go, pkg/operator/sync.go
- The operator now checks the MachineConfiguration global knob for any user provided node disruption policies, merges them with cluster defaults and displays the results in the Status of the MachineConfiguration object. 
- The daemon looks at the status of the MachineConfiguration object during node updates. If the daemon is unable to find the status of MachineConfiguration for more than 2 minutes, it will default to the legacy update path.
- All of this is gated on NodeDisruption feature gate
- Bring up a cluster in TechPreview. If testing on a cluster that was originally having the default FeatureSet and then transitioned to TechPreview, please read this https://github.com/openshift/machine-config-operator/pull/4267#issuecomment-2071154702
- Check the status of the MachineConfiguration …
=> MCO-1009: MCO-1008: MCO-905: Implement NodeDisruptionPolicy API

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
the default in cri-o 1.29 and below is 0, which is interpreted differently by runc and crun. The intended outcome of setting 0 was to set the cgroup limit to "max", so the pids limit is instead set by the kubelet's podPidsLimit.
After crun 1.13, both crun and runc correctly interpret a negative value as "max", so use this value instead to keep consistency.
=> OCPBUGS-28926: [4.15] crio: update pids limit to be -1

pkg/daemon/daemon.go
Some adjustements to the logic from 4d447c5c8f (#4106).
Factor out the common rebootstrap logic into a new function, just to avoid repeating ourselves in two places.  This part is a pure refactor, with no user-visible changes.
Significantly for users, 4d447c5c8f's `utilruntime.ErrorHandlers` handling introduced a race like:
1. Daemon is rolling an update out onto disk.
2. Kube API or DNS hiccup causes the daemon's watches, or other Kube API requests, to fail.
3. `utilruntime.ErrorHandlers` feeds that failure into `errCh`.
4. `stopCh` set to trigger graceful shutdowns in the child goroutines.
5. Child goroutine performing the update moves into its deferred rollbacks (for example, see code around [`error rolling back files writes`][rollback]).
6. But before that rollback completes, the main …
=> OCPBUGS-33018: pkg/daemon: Ignore watch failure unless kubelet needs a rebootstrap

manifests/machineconfigcontroller/machineconfiguration-guards-validatingadmissionpolicy.yaml, manifests/machineconfigcontroller/machineconfiguration-guards-validatingadmissionpolicybinding.yaml, pkg/operator/sync.go
This adds a new ValidatingAdmissionPolicy which rejects all MachineConfiguration objects not named "cluster".
How to test:
- Launch a cluster in TechPreview. Handy cluster bot command:
```
launch 4.16,openshift/machine-config-operator#4332 gcp,techpreview
```
If starting from default and transitioning to TechPreview, wait for the `kube-apiserver` operator to settle as this indicates that all the feature gates have been setup correctly. This can take up to 20 minutes, so I recommend the above method.
- Attempt to create a new CR of the type MachineConfiguration not named "cluster". Here is a sample object.
```
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration
metadata:
name: example-file
namespace: openshift-machine-config-operator
spec:
nodeDisruptionPolicy:
files:
- path: …
```
=> OCPBUGS-32739: MachineConfigurations is only effective with name <cluster>

cmd/machine-config-operator/start.go, pkg/controller/kubelet-config/helpers.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_controller_test.go, pkg/controller/kubelet-config/kubelet_config_features_test.go, pkg/controller/kubelet-config/kubelet_config_nodes_test.go, pkg/operator/operator.go, pkg/operator/status.go, pkg/operator/sync.go
Backports https://github.com/openshift/machine-config-operator/pull/4316 to 4.15.
=> OCPBUGS-32922: [release-4.15] add cluster fleet evaluation support to mco

templates/common/openstack/units/afterburn-hostname.service.yaml
When deploying a cluster on OpenStack using OVN-Kubernetes, there can be a delay before the metadata service is available. Afterburn [1] does not provide a mechanism to configure the timeouts and the network-online target merely indicates that we *a* configured, routable IP address, not necessarily that we can access the metadata service yet. Work around by restarting the service on failure. This is possible since systemd v244.1 [2].
[1] https://github.com/coreos/afterburn
[2] https://github.com/systemd/systemd/pull/13754
Working on this with QE now.
The `afterburn-hostname.service` systemd service deployed on the OpenStack will now retry in the event of the metadata service taking longer than expected to come up.
=> OCPBUGS-11936: Wait for OpenStack Metadata service

pkg/daemon/daemon.go
[OCPBUGS-33018](https://issues.redhat.com/browse/OCPBUGS-33018) is wrestling with some surprise `kubeletRebootstrap` `ErrAuxiliary` 255 exits.  Once the container exits, replacement containers [crash-loop on `content mismatch for file`][2], which means that it's hard to get details about the error condition that triggered the re-bootstrap (and then exited leaving dirty disk state).  By writing the error to the system logs, we're more likely to be able to understand what went wrong, and this will help us maintain the `strings.Contains` filtering going forward.  If we notice re-bootstrap triggers that don't look like things that a re-bootstrap would help resolve, we can drop or adjust that trigger.
[2]: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/period …
=> OCPBUGS-33018: pkg/daemon: logSystem the Kube API errors that trigger a re-bootstrap

pkg/daemon/daemon.go
Since 4d447c5c8f (#4106) landed the initial re-bootstrap work, we had been triggering re-bootstraps on a number of errors:
* `failed to watch`
* `unknown authority`
* `error on the server`
But `failed to watch` message is about what failed (a watch), and not about how/why it failed.  Which leads to situations [like][1]:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.16-upgrade-from-stable-4.15-e2e-metal-ipi-upgrade-ovn-ipv6/1787177729708265472/artifacts/e2e-metal-ipi-upgrade-ovn-ipv6/gather-extra/artifacts/nodes/master-0.ostest.test.metalkube.org/journal | zgrep -A1 'Re-bootstrapping kubelet'
May 05 20:30:04.956832 master-0.ostest.test.metalkube.org root[197839]: …
```
=> OCPBUGS-33018: pkg/daemon: Only re-bootstrap kubelet on X.509 errors

pkg/controller/node/node_controller.go, pkg/controller/node/status.go, pkg/daemon/pinned_image_set.go, pkg/upgrademonitor/upgrade_monitor.go
This PR improves status updates to MCN and MCP while PinnedImageSets are reconciling.
Changes:
- node controller status properly calculates update machines
- node controller will sync  if a pool attached to a node is currently reconciling pinnedImageSets. This gives a faster feedback loop when nodes have updated or errored.
- add poolSyncronizer logic to MCN status to provide finer grained status reporting for MCP poolSyncronizers.
- refactoring of status population in PinnedImageSet Manager
- additional feature gating
=> OCPBUGS-33046:  improve status reporting for pinned image sets

pkg/daemon/pinned_image_set.go, pkg/daemon/pinned_image_set_test.go
This PR refactors how authentication is handled for mirrored images. Previous to this PR we assumed that a mirrored image configuration was mirrored to a path for example `registry.ci.openshift.org/ocp/release` but did not cover the case where a registry was a domain name `ec2-18-226-52-10.us-east-2.compute.amazonaws.com:6002`.
=> OCPBUGS-32583: daemon/pinned-image-set: refactor mirrored registry auth

templates/master/00-master/on-prem/files/keepalived-keepalived.yaml, templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
Previously we were only checking the ready endpoint, which means the check script will start failing as soon as the ingress service indicates it is gracefully stopping. In some upgrade scenarios that seems to be resulting in a 30-ish second outage because we now remove the VIP from nodes without a healthy ingress. I don't fully understand how all the ingress endpoints could be down at the same time in a rolling update, but that seems to be the most likely explanation
With this change, we still have no weight set for the healthz endpoint, which means failure of that script will still cause removal of the VIP. However, a weight is included for the ready endpoint so if a node starts to gracefully shut down ingress and there are no other nodes to take the VIP, we'll leave it in place until …
=> OCPBUGS-33357: Check both ready and health ingress endpoints

pkg/daemon/certificate_writer.go
Presently it seems that the daemon sometimes doesn't react to the configmap changes, possibly due to the lexicographical comparison (which probably should have been a size?)
Change the logic a bit such that it:
1. checks for all the cert changes (adds/updates)
2. always write in from the configmap
3. still defer kubelet restarts/MCD restarts for some cases
4. do not write back to the configmap as that shouldn't be necessary
=> OCPBUGS-25821,OCPBUGS-31381: certificate_writer: clean up disk-write logic

Dockerfile, Dockerfile.rhel7, cmd/machine-config-operator/bootstrap.go
Align with the version-less-ness of `rhel-coreos` and `fedora-coreos` and shorten the overall tag.
Both tags are currently aliases, `centos-stream-coreos-9` will be removed in the future.
OKD: Reference `stream-coreos` instead of `centos-stream-coreos-9`
=> OKD-212: Reference `stream-coreos` instead of `centos-stream-coreos-9`

pkg/daemon/certificate_writer.go
When trying to read the /etc/docker/certs.d directory don't return an error if the error is that it doesn't exist. It is possible that the direcotry hasn't been created yet and that is okay.
Fixes the cert issue described in https://issues.redhat.com/browse/OCPBUGS-20152 but not the timing issue around controller config.
This issue was already fixed in 4.16 and master in this PR https://github.com/openshift/machine-config-operator/pull/4106. However, that PR consist of other major cert changes that cannot be backported at this time. So only picking the patch that fixes the certs.d not found issue.
This will need to be backported to 4.14 as well.
Added a check to not error on dir doesn't exist for the /etc/docker/certs.d directory.
This issue is …
=> [release-4.15] OCPBUGS-20152: Don't error if the certs.d dir doesn't exist yet

templates/common/aws/files/usr-local-bin-aws-kubelet-nodename.yaml
It is possible in AWS to specify multiple hostnames as part of the VPC DHCP options. Machine API will pick both of these up and set them in the Machine status:
```
- address: ip-10-0-91-2.huliu.test
type: InternalDNS
- address: ip-10-0-91-2.testa.com
type: InternalDNS
```
CSR approval needs to match one of these against the provided hostname, and it doesn't matter which.
We will use the first of the names in the list always, so that we have a simple and consistent approach.
Tested manually, this patch trims everything after and including the first space character, eg
```
$ hostname="foo bar baz"
$ echo ${hostname}
foo bar baz
$ echo ${hostname%% *}
foo
```
=> OCPBUGS-10498: If multiple hostnames are returned, use the first one for the Node name

templates/common/_base/files/internal-registry-pull-secret.yaml, test/e2e-techpreview/helpers_test.go, test/e2e-techpreview/onclusterbuild_test.go, test/helpers/utils.go
This patch does the following to workaround around the new rotations of the registry pull secrets:
- removes the template for /etc/mco/internal-registry-pull-secret.json
- the OCL test now lays down the file until we figure out a longer term fix
=> OCPBUGS-33803: machine-os-puller SA refreshes every hour, causing machine config regeneration

install/0000_80_machine-config_04_deployment.yaml, manifests/machineconfigcontroller/deployment.yaml, manifests/machineconfigdaemon/daemonset.yaml, manifests/machineconfigserver/daemonset.yaml
Pinned the required SCC to the following workloads:
- `deployment/machine-config-operator`
- `deployment/machine-config-controller`
- `daemonset/machine-config-daemon`
- `daemonset/machine-config-server`
No effective changes expected; the pinned SCC is the one that the pods are getting admitted with.
Pinned the required SCC to prevent custom SCCs from taking precedence.
=> AUTH-482: set required-scc for openshift workloads

manifests/machineconfigdaemon/mcn-guards-validatingadmissionpolicy.yaml, manifests/machineconfigdaemon/mcn-guards-validatingadmissionpolicybinding.yaml, pkg/operator/sync.go, test/e2e-techpreview/main_test.go, test/e2e-techpreview/mcn_test.go
This PR adds:
- a ValidatingAdmissionPolicy that limits the service account of a node's MCD from editing the MCN associated with another node
- tests in e2e/techpreview to verify this behavior
How to test manually:
- Launch a cluster in TechPreview
- From a random node's MCD pod, attempt to patch the MCN of another node. This should fail.
```
$ oc rsh pod/machine-config-daemon-l2wmr ./rootfs/usr/bin/oc patch  machineconfignodes/djoshy11-gwphs-worker-
b-b5r6s.c.openshift-gce-devel.internal --type=merge -p '{"spec":{"configVersion":{"desired":"rendered-worker-test"}}}'
The machineconfignodes "djoshy11-gwphs-worker-b-b5r6s.c.openshift-gce-devel.internal" is invalid: : ValidatingAdmissionPolicy 'mcn-guards' with binding 'mcn-guards-binding' denied request: MCN update request from node …
```
=> OCPBUGS-30343: Scope each MCN object to only be accessible from its associated MCD

pkg/operator/operator.go, pkg/operator/operator_test.go, pkg/operator/status.go, pkg/operator/status_test.go, pkg/operator/sync.go
I added a lister and cached the CO object wherever I could, and only did a get call when there is an update conflict error. Initial results look promising. I think we should be safe to merge this if the test suite is passing, but it can wait till after FF. It does not introduce any new behavior, so we could probably skip pre-merge QE.
For a [recentish test run](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_machine-config-operator/4327/pull-ci-openshift-machine-config-operator-master-e2e-aws-ovn/1787431388836794368/artifacts/e2e-aws-ovn/openshift-e2e-test/artifacts/junit/audit-log-summary__20240506-112905.json)(LARGE FILE WARNING) on #4327 :
```
{
"GroupVersionResource": {
"Group": "config.openshift.io",
"Version": "v1",
"Resource": …
```
=> OCPBUGS-32242: The MCO makes a lot of API requests for ClusterOperator objects

pkg/daemon/update.go, pkg/daemon/update_test.go
Added an additional check in  `calculatePostConfigChangeActionFromMCDiffs` within the daemon so that a crio reload would not override a crio restart action that was already queued. Also added a couple of unit tests that verified this behavior.
On a cluster without these patch, apply a MachineConfig with changes that would cause both these actions, with the crio reload file later in the new config. Here is a sample:
```
metadata:
labels:
machineconfiguration.openshift.io/role: infra
name:  109-test-file
spec:
config:
ignition:
version: 3.4.0
storage:
files:
- contents:
source: data:,MCO%20test%20file%20permissions%0A
path: /etc/pki/ca-trust/source/anchors/openshift-config-user-ca-bun …
```
=> OCPBUGS-32367: The MCD can override a restart crio action with a reload crio action

lib/resourceapply/machineconfig.go, lib/resourcemerge/meta.go
Fixed function setBytesIfSet to correctly remove certificate data from controller config, which now correctly reflects onto node contents
-apply certs
`oc create cm cm-test-cert -n openshift-config --from-file=ca-bundle.crt`
`oc patch proxy/cluster --type merge -p '{"spec": {"trustedCA": {"name": "cm-test-cert"}}}'`
`oc set data -n openshift-config ConfigMap cloud-provider-config  --from-file=ca-bundle.pem=ca-bundle.crt`
-inspect controller config
`oc describe controllerconfig machine-config-controller | head -n 150`
-check node contents
`oc debug -q  node/$(oc get nodes -l node-role.kubernetes.io/worker -ojsonpath="{.items[0].metadata.name}") -- chroot /host cat "/etc/pki/ca-trust/source/anchors/openshift-config-user-ca-bundle.crt"`
`oc debug -q …
=> OCPBUGS-28653: userCA and cloudCA certfiicates are not removed from nodes and ignition config

manifests/controllerconfig.crd.yaml
Removed the platform field under spec in the CRD. Now it matches the 4.16 CRD.
`oc logs <machine-controller-config-pod> | grep unknown `
=> OCPBUGS-17658: Controller pod is spamming unknown field "spec.dns.spec.platform" message

pkg/daemon/rpm-ostree.go, pkg/daemon/update.go
This PR add the ability to upgrade an os image if it has already been pulled into local container storage. This functionality is  behind `PinnedImage` feature gate. The advantage to this path is that before this change skopeo by default will make a call to the registry to pull the image during upgrade. That does not work for disconnected clusters.
=> OCPBUGS-33248: daemon: upgrade os image from local container storage if it exists 

pkg/controller/pinnedimageset/pinned_image_set.go, pkg/daemon/pinned_image_set.go
This PR addresses a race with the ordering of event handlers and queue which can result in a panic.
tests:
clusterbot: 1
e2e-vsphere-ovn-techpreview: 1
=> OCPBUGS-34959: ensure event handlers are registered after queue is configured

pkg/daemon/update.go, pkg/operator/sync.go, test/e2e-shared-tests/helpers.go, test/e2e-shared-tests/mcd_config_drift.go, test/e2e-techpreview/helpers_test.go, test/e2e-techpreview/main_test.go, test/e2e-techpreview/nodedisrupt_test.go, test/helpers/utils.go
This PR adds:
- some e2e tests for NodeDisruptionPolicy which landed in #4267 
- add a generation check before the MCD consumes NodeDisruptionPolicy Status
- the MCD will now degrade on NodeDisruptionPolicy errors
=> MCO-1152: MCO-1146: Add e2e tests for NodeDisruptionPolicy

pkg/controller/build/build_controller.go, pkg/controller/node/node_controller.go
Avoid non-existing MOSC de-reference.
=> OCPBUGS-33129: Panic when we remove an OCB infra MCP and we try to create new ones with different names

pkg/controller/build/build_controller.go, pkg/controller/build/build_controller_test.go, pkg/controller/build/helpers.go, pkg/controller/build/helpers_test.go
If multiple MachineOSConfigs are created simultaneously (e.g., from multiple
YAML documents in the same file) and each of these MachineOSConfigs references
a legacy pull secret (that is, a pull secret that does not have a top-level
`{"auths": {}}` key), only one of the MachineOSBuilds that gets created will
actually get a status and begin building.
This is because multiple Goroutines will attempt to create a canonicalized
secret and only one will be able to. In the event that this occurs, the best
thing to do is to just fetch the secret and continue.
This PR also includes fixes for updating the canonicalized pull secrets. Basically, if a legacy-style pull secret is supplied and then changed, it would not be kept up-to-date. Instead, we now set a label which contains the …
=> OCPBUGS-33671, OCPBUGS-34079: fix secret canonicalization

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Move crio metrics port to localhost only.
=> OCPNODE-2216: crio: migrate metrics port to localhost only [4.17]

templates/common/azure/units/machine-config-daemon-pull.service.yaml
In 4.14 we slightly tweaked the services such that mcd-pull no longer depends on network-online.target. This broke some ARO disconnected environments that needed dnsmasq to be ready before the MCD-pull runs on firstboot.
Add in a new Azure template for MCD-pull with an additional After=dnsmasq.service so the strict ordering of:
1. ovs-configuration
2. dnsmasq
3. mcd-pull
4. mcd-firstboot
is adhered to.
=> OCPBUGS-35300: Azure: add Azure specific dnsmasq ordering

templates/master/01-master-kubelet/_base/units/kubelet.service.yaml, templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
This ensures that the `--node-ip` flag is defaulted to `0.0.0.0` on IPv4 clusters when otherwise not overridden by the kubelet-env file.
This we believe should Kubelet to start pods, that require the host IP to be set via the downwards API, prior to the kubelet accessing the kube API. This is helpful in hibernation recovery scenarios.
/hold for manual testing of the above theory
=> OCPBUGS-34050: Default ipv4 NODE_IP to 0.0.0.0

templates/common/baremetal/files/nmstate-configuration.yaml
I missed a spot when renaming this and it breaks host-specific configuration for br-ex.
=> OCPBUGS-33331: Fix reference to $host_file

pkg/controller/kubelet-config/helpers.go, pkg/controller/kubelet-config/kubelet_config_bootstrap_test.go, pkg/controller/kubelet-config/kubelet_config_controller_test.go, test/e2e/kubeletcfg_test.go
…se YAML encoding instead of JSON encoding
From doc: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/controller-revision-v1/#ControllerRevision about `RawExtension`, this field holds the unpacked data in json format. So keep using json encoding for kubeletconfig for unit/e2e testing.
close: https://issues.redhat.com/browse/OCPBUGS-31710
apply a kubelet config sets maxPods
```yaml
metadata:
name: max-pods-worker
spec:
matchLabels:
kubeletConfig:
maxPods: 107
```
```bash
sh-5.1# cat /etc/kubernetes/kubelet.conf
apiVersion: kubelet.config.k8s.io/v1beta1
authentication: …
```
=> OCPBUGS-31710: Unify machineconfig file format for kubeletconfig to use YAML encoding instead of JSON encoding

install/0000_80_machine-config_03_rbac.yaml, manifests/on-prem/keepalived.yaml, templates/common/on-prem/files/keepalived.yaml
This PR consists of 2 commits that together are allowing to configure logging for on-prem components (as for today, the log level of the node IP selection logic)
* OCPBUGS-32348: Mount pod namespace for on-prem components
* OCPBUGS-32348: Allow system:node read config maps in infra namespaces
The first one is self-explanatory. The second one is explained in its commit message (for ease of access, pasted below)
```
Host networking services running in on-prem platforms require access to
the config map so that their configuration can be parametrized. As those
services run as static pods, it is not possible to simply mount the
config map from the Pod yaml definition. In order to overcome this, the
respecive applications use k8s API calls to retrieve the config map at
runtime.
Credentials used …
```
=> OCPBUGS-32348: Make logging configurable for on-prem components

templates/common/_base/units/disable-mglru.service.yaml, templates/common/_base/units/kubelet-dependencies.target.yaml
Backports #4425 
Disable MG LRU via systemd unit
Before the fix,
sh-5.1# cat /sys/kernel/mm/lru_gen/enabled
0x0007
and after the fix is should look like,
sh-5.1# cat /sys/kernel/mm/lru_gen/enabled
0x0000
Disable MG LRU via systemd unit
=> OCPBUGS-35992: disable mglru service

test/e2e-techpreview/onclusterbuild_test.go
This test was accidentally committed and merged by mistake. Its original purpose was to assist me with writing a more in-depth test below.
N/A
Removes unnecessary e2e test
=> OCPBUGS-36178: remove unnecessary e2e test TestControllerConfigStuff

pkg/daemon/file_writers.go, pkg/daemon/update.go
When overwriting a systemd unit with new content, we need to account for
the case where the new unit content has a different `[Install]` section.
If it does, then simply overwriting will leak the previous enablement
symlinks and become node state. That's OK most of the time, but this can
cause real issues as we've seen with the combination of #3967 which does
exactly that (changing `[Install]` sections) and #4213 which assumed
that those symlinks were cleaned up. More details on that cocktail in:
https://issues.redhat.com/browse/OCPBUGS-33694?focusedId=24917003#comment-24917003
Fix this by always checking if the unit is currently enabled, and if so,
running `systemctl disable` *before* overwriting its contents. The unit
will then be re-enabled (or not) based on the MachineConfig.
Fixes: …
=> OCPBUGS-33694: daemon/update: disable systemd unit before overwriting

pkg/daemon/osrelease/osrelease.go
Fixes:
- https://issues.redhat.com/browse/OCPBUGS-28974
- https://issues.redhat.com/browse/OCPBUGS-21628
=> OCPBUGS-28974, OCPBUGS-21628: daemon: Handle correctly OS Version for 4.1 and 4.2 bootimages

templates/common/_base/files/kubelet-auto-sizing.yaml
Introducing versioning for the auto-node-sizing feature
The presence of `/etc/node-sizing-version.json` file on a node indicates the introduction of versioning in the auto node sizing feature
Auto node sizing feature gives recommendations about the `kube reserved`, `system reserved` memory and cpus as described in this [enhancement](https://github.com/openshift/enhancements/blob/master/enhancements/kubelet/kubelet-node-sizing.md)
These recommendations tend to change on a requirement basis i.e. based on the resource utilizations of system and kube, new features etc.
Hence, introduction of the versioning for this feature helps in modifying the memory, cpu values and also ease the upgrades without breaking the …
=> OCPNODE-2226: Introduce versioning in auto-node-sizing feature

cmd/machine-config-controller/start.go, pkg/controller/common/featuregates.go, test/e2e-bootstrap/bootstrap_test.go
-added a function waitForFeatureGatesReady to handle the initialization and added necessary logging for debugging.
-updated the runStartCmd function to wait for feature gates to be ready before starting controllers.
-run the bootstrap e2e tests located in test/e2e-bootstrap/bootstrap_test.go.
-observe the logs to confirm that feature gates are initialized before controllers are started.
Ensure feature gates are initialized before starting controllers in the bootstrap process for the Machine Config Operator.
=> OCPBUGS-30603: Bootstrap e2e test featuregate setup does not match the actual code

templates/common/azure/units/machine-config-daemon-pull.service.yaml
This was originally reordered such that ovs-configuration was able to run when the reboot was skipped. See: https://github.com/openshift/machine-config-operator/pull/3858
This broke ARO since they require the network to be ready for the pull to happen (and generally, probably best for the network to be ready before attempting to pull the new OS image).
This fix aims to apply just to Azure, which is not ideal since it drifts the service definition, but if don't-reboot-on-metal and ARO have different dependency chains, this is the easiest middle ground.
=> OCPBUGS-35300: MCD-pull: run after network-online.target in Azure

pkg/controller/container-runtime-config/helpers.go, pkg/controller/container-runtime-config/helpers_test.go
cherry-pick of #4125
This PR replaces https://github.com/openshift/machine-config-operator/pull/4132 due to unit test failure with the auto cherrypick PR.
=> [release-4.15] OCPBUGS-27436: Fix mirrorSourcePolicy error prompt imagecontentsourcepolicies

templates/common/_base/units/disable-mglru.service.yaml
RHEL worker nodes may not have lru_gen, so adding a condition so it doesn't fail
=> OCPBUGS-36711: templates: run disable-mglru conditionally

pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/container-runtime-config/helpers.go, pkg/controller/container-runtime-config/helpers_test.go
Close: #4446 
Cluster 4.17.0-0.ci.test-2024-07-08-173847 has default ICSP:
```
$ oc describe imagecontentsourcepolicy/image-policy
Name:         image-policy
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  operator.openshift.io/v1alpha1
Kind:         ImageContentSourcePolicy
Metadata:
Creation Timestamp:  2024-07-08T17:51:37Z
Generation:          1
Resource Version:    706
UID:                 036f79f1-826c-459c-8adc-8b3cc0499801
Spec:
Repository Digest Mirrors:
Mirrors:
quayio-pull-through-cache-us-east-2-ci.apps.ci.l2s4.p1.openshiftapps.com
Source:  quay.io
Events:      <none>
```
Apply CIP:
```
apiVersion: config.openshift.io/v1alpha1
kind: ClusterImagePolicy
metadata:
name: openshift
annotations:
kubernetes.io/description: …
```
=> OCPBUGS-36344: Add CIP relevant mirrors to sigstore attachement cfg

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml, templates/common/on-prem/files/resolv-prepender.yaml, templates/common/on-prem/files/wait-for-br-ex-up.yaml, templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml, templates/common/on-prem/units/wait-for-br-ex-up.yaml
This is a manual cherry-pick for commits implementing OPNET-355. Initially discovered as bug RHEL-2184.
=> OCPBUGS-30139: [release-4.15] Use NM's dns-change event for resolv.conf

Dockerfile, Dockerfile.rhel7
HyperShift uses some components of MCO in order to generate ignition files. In order to work with FIPS, those binaries need to be built with the same RHEL/openssl version as the HyperShift component that runs them.
This commit makes the dockerfile include those already built binaries so they can be successfully extracted by HyperShift, according to version.
Fixes: #OCPBUGS-36863
Copy the already built RHEL9 binaries that HyperShift uses
Deploying a FIPS cluster in HyperShift (needs a PR in HyperShift that will choose the right binaries)
Ship RHEL9 binaries for machine-config-operator, machine-config-controller and machine-config-server for HyperShift.
=> OCPBUGS-36863: Copy RHEL9 binaries used in HCP

pkg/controller/node/node_controller.go, pkg/controller/node/node_controller_test.go
This PR adds a node readiness check in the node controller before a selection of update candidate nodes are made. Prior to this, the MCO used a count of target nodes, but did not specifically exclude a node that was already unscheduled or mid update. This would only happen in clusters where maxUnavailable > currently unscheduled nodes, as there was an earlier check that blocked the pool from updating in that case.
It also adds a new unit test for this particular case.
On a cluster without this fix, set the maxUnavailable on the worker pool to 2, and cordon one of the nodes. Attempt an MC update to the worker pool. You should notice that the node controller will queue all the nodes for updates, and eventually uncordon all of the nodes. 
Now, on a …
=> OCPBUGS-33397: Openshift uncordoned compute-node that was intentionally cordoned

pkg/daemon/osrelease/osrelease.go, pkg/helpers/helpers.go, pkg/operator/sync.go, test/e2e/node_os_test.go
If a non-coreos based node, such as RHEL8, is added to a cluster and the user tries to enable on cluster builds, throw an error as that is not supported on non-coreos based nodes.
Fixes https://issues.redhat.com/browse/OCPBUGS-19537
Added a check for when OCB is enabled to verify which OS the nodes have and to fail if they are non-coreos based.
Start a cluster, add a RHEL node to it and then try enabling OCB
Throw an error if cluster has non-coreos node when trying to enable OCB
=> OCPBUGS-19537: OCB should fail if node is not coreos based

docs/NodeDisruptionPolicy.md, pkg/apihelpers/apihelpers.go, pkg/controller/common/helpers.go, pkg/daemon/constants/constants.go, pkg/daemon/update.go, pkg/daemon/update_test.go
- Add support for paths in file based NodeDisruptionPolicies. If multiple policies apply to a file being updated, the closest match will be considered.
- Moved some of the "backdoor" directory based exceptions into the MCO's default policies.
- Added a new default policy for the user CA cert to maintain feature parity until it moves to cert_writer.
- Updated docs to reflect new defaults and path support.
- All previous NodeDisruptionPolicy behavior should still behave the same(node disruption e2e should pass)
- The daemon should now behave correctly for user CA cert changes instead of rebooting.
- To test the multi-path based policies:
1. Define more than one file based policy:
```
apiVersion: operator.openshift.io/v1
kind: MachineConfiguration …
```
=> MCO-1125: OCPBUGS-35277: Allow paths to be defined for non-disruptive updates

go.mod, go.sum, install/0000_10_config-operator_01_clusterimagepolicies-CustomNoUpgrade.crd.yaml, install/0000_10_config-operator_01_clusterimagepolicies-DevPreviewNoUpgrade.crd.yaml, install/0000_10_config-operator_01_clusterimagepolicies-TechPreviewNoUpgrade.crd.yaml, install/0000_80_machine-config_01_kubeletconfigs.crd.yaml, vendor/github.com/openshift/api/config/v1alpha1/types_cluster_image_policy.go, vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go, vendor/github.com/openshift/api/config/v1alpha1/zz_generated.featuregated-crd-manifests.yaml, vendor/github.com/openshift/api/features.md, vendor/github.com/openshift/api/features/features.go, vendor/modules.txt
Bump API to get the ClusterImagePolicy doc update https://github.com/openshift/api/pull/1927
Run hack/crds-sync.sh to update the manifests
=> OCPNODE-2438: bump API and update CRD manifests

manifests/cloud-platform-alt-dns/coredns.yaml, manifests/on-prem/coredns.yaml, templates/common/cloud-platform-alt-dns/files/coredns.yaml, templates/common/on-prem/files/coredns.yaml, templates/common/on-prem/files/keepalived.yaml, templates/master/00-master/on-prem/files/haproxy.yaml
It turns out we don't need this in some cases and in others we can get by with specific capabilities instead of a fully privileged container. This is more secure because it means even a compromised container won't have as much ability to cause trouble.
=> OCPBUGS-36175: Remove privileged flag from on-prem containers

cmd/machine-config-controller/start.go, cmd/machine-config-operator/start.go, cmd/machine-config-server/bootstrap.go, cmd/machine-config-server/main.go, cmd/machine-config-server/start.go, install/0000_80_machine-config_00_clusterreader_clusterrole.yaml, manifests/machineconfigcontroller/deployment.yaml, manifests/machineconfigdaemon/daemonset.yaml, manifests/machineconfigserver/daemonset.yaml, pkg/controller/bootstrap/bootstrap.go, pkg/controller/common/constants.go, pkg/controller/common/helpers.go, pkg/controller/kubelet-config/kubelet_config_bootstrap.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_controller_test.go, pkg/controller/template/render.go, pkg/controller/template/render_test.go, pkg/controller/template/template_controller.go, pkg/controller/template/template_controller_test.go, pkg/operator/bootstrap.go, pkg/operator/operator.go, pkg/operator/render.go, pkg/operator/sync.go, pkg/server/api.go, pkg/server/api_test.go, templates/master/01-master-kubelet/_base/files/criometricsproxy.yaml, templates/worker/01-worker-kubelet/_base/files/criometricsproxy.yaml, test/e2e-bootstrap/bootstrap_test.go
In regular cluster operation:
- The operator and controller will listen on an APIServer object, which contains the [global cluster tls settings](https://docs.openshift.com/container-platform/4.15/security/tls-security-profiles.html#tls-profiles-kubernetes-configuring_tls-security-profiles).
- The operator will now render TLSMinVersion and TLSCiphers to the MCC and MCD kube-rbac-proxy sidecar manifests via templated arguments.
- The template controller will now render TLSMinVersion and TLSCiphers to the kube-rbac-proxy-crio metrics pods via templated arguments. These are per node pods in the MCO namespace, and deployed via MachineConfigs. As a result changing the tls settings will cause a MachineConfig rollout.
- The MCS container now has two new TLS arguments. The …
=> MCO-1202: MCO-1203: MCO-1204: MCO-1205: MCO-1213: Implementing tlsSecurityProfile for MCO

manifests/machineconfigcontroller/machineconfiguration-guards-validatingadmissionpolicy.yaml, manifests/machineconfigcontroller/update-bootimages-validatingadmissionpolicy.yaml
Manual cherry pick of #4460. 4.16 only has 2 of these policies so an auto cherry pick did not work.
=> [release-4.16] OCPBUGS-37428: Machine-config operator should not hot loop generating ValidatingAdmissionPolicyUpdated events

pkg/controller/drain/drain_controller.go
Manual cherry pick of https://github.com/openshift/machine-config-operator/pull/4467
=> [release-4.16] OCPBUGS-37470: Nodes are drained twice when an OCB image is applied

test/e2e-techpreview/helpers_test.go, test/e2e-techpreview/onclusterbuild_test.go
The `TestMCDGetsMachineOSConfigSecrets` e2e test was failing frequently during a backport to 4.16 in this PR: https://github.com/openshift/machine-config-operator/pull/4430. Basically, `helpers.ExecCmdOnNode()` was unable to get the current credentials on the node because that particular function uses the MCD pod as a bridge to execute a command on a given node. The reason why is because the MCD pod restarted to get the new secret volumes required by the MachineOSConfig. However, the MCD pod containers were not in a running / ready state.
This PR introduces a check to ensure that the MCD pods are in a running / ready state before moving onto the final phase of the test. This PR also includes minor cleanups such as only fetching the expected registry hostnames from the …
=> OCPBUGS-36289: e2e test should wait for MCD pod to be running

pkg/daemon/bootc.go, pkg/daemon/image_manager_helper.go, pkg/daemon/rpm-ostree.go
- Create a bootc.go to store bootc status reading and command line execution
- Create bootc internal go-bindings inside bootc.go. Code designed in the way to be easily separated into a standalone lib: https://github.com/inesqyx/bootc-client-go/tree/bootc-client-go 
- Consolidate functions that rpm-ostree and bootc share in common into one place
=> MCO-1191, MCO-1194: Experiment with creating internal go bindings for bootc , Incorporate support for bootc commands to Machine Config Daemon 

templates/common/on-prem/units/on-prem-resolv-prepender.path.yaml
Currently the `on-prem-resolv-prepender.service` is triggered only by NetworkManager dispatcher script in case `dns-change` event has happened.
Lately we have noticed that in case there are bugs in NM and the event is not thrown (even though the content of
`/var/run/NetworkManager/resolv.conf` changed), the resolv-prepender will not run and as a result `/etc/resolv.conf` will have incorrect content.
In order to remediate this, we not only rely on NetworkManager sending an event, but also actively monitor for changes in NM and act upon them. Thanks to this, when NM forgets to send an event and start the resolv-prepender, we will anyway notice the change and do what's necessary.
Fixes: OCPBUGS-30955
=> OCPBUGS-30955: On-Prem resolv prepender to watch for NM changes

pkg/controller/build/assets/buildah-build.sh, pkg/controller/build/assets/wait.sh, pkg/controller/build/image_build_request.go
Occasionally, an image build and / or push operation will fail due to a transient network condition. To make this process more robust, we should retry these operations multiple times. This PR implements a simplified approach where the build and push operations themselves are wrapped in a `retry` function. It should be noted that a key limitation of this approach is that it _does not_ account for situations where the build pod is evicted or rescheduled onto a different node. For that, we may want to investigate using a [Kubernetes Job](https://kubernetes.io/docs/concepts/workloads/controllers/job/) which provides additional resilience around evictions and rescheduling.
1. Create a MachineOSConfig with a syntax error in the Containerfile or use an …
=> MCO-1230: Retry build and push operations multiple times

cmd/machine-config-controller/start.go, pkg/controller/common/controller_context.go, pkg/controller/node/node_controller.go
Added a tech preview specific InformerFactory that is only started if the OCL feature gate is enabled.
I also noticed a minor bug within the informer callback which I fixed.
- There should no longer be logs like the following in the controller while in the default featureset:
```
W0515 10:38:17.921662       1 reflector.go:539] github.com/openshift/client-go/machineconfiguration/informers/externalversions/factory.go:125: failed to list *v1alpha1.MachineOSBuild: the server could not find the requested resource (get machineosbuilds.machineconfiguration.openshift.io)
E0515 10:38:17.921703       1 reflector.go:147] github.com/openshift/client-go/machineconfiguration/informers/externalversions/factory.go:125: Failed to watch *v1alpha1.MachineOSBuild: …
```
=> OCPBUGS-33784: Guard MachineOSBuild informers with feature gates

templates/common/on-prem/files/keepalived.yaml, templates/master/00-master/on-prem/files/keepalived-keepalived.yaml, templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
This is a combined backport of https://github.com/openshift/machine-config-operator/pull/4290 and https://github.com/openshift/machine-config-operator/pull/4398 because both are needed for this to be functional and not cause issues on upgrade. Both commits applied cleanly on 4.14.
=> [release-4.14] OCPBUGS-37483: Remove weights from ingress check script

templates/common/_base/files/kubelet-auto-sizing.yaml
- What I did
Introducing versioning for the auto-node-sizing feature
The presence of /etc/node-sizing-version.json file on a node indicates the introduction of versioning in the auto node sizing feature
Auto node sizing feature gives recommendations about the kube reserved, system reserved memory and cpus as described in this [enhancement](https://github.com/openshift/enhancements/blob/master/enhancements/kubelet/kubelet-node-sizing.md)
These recommendations tend to change on a requirement basis i.e. based on the resource utilizations of system and kube, new features etc.
Hence, introduction of the versioning for this feature helps in modifying the memory, cpu values and also ease the upgrades without breaking the clusters.
=> OCPBUGS-37840: [release-4.16] Introduce versioning for Auto Node Sizing feature

pkg/controller/node/node_controller.go, pkg/controller/node/node_controller_test.go
=> [release-4.13] OCPBUGS-37783: Openshift uncordoned compute-node that was intentionally cordoned

cmd/machine-config-controller/start.go, pkg/controller/common/controller_context.go, pkg/controller/node/node_controller.go
=> [release-4.16] OCPBUGS-37759: Guard MachineOSBuild & MachineOSConfig informers with feature gates

pkg/controller/common/layered_pool_state.go
Follow up https://github.com/openshift/oc/pull/1834#issuecomment-2260804858
- It should be `l.pool.Annotations` instead.
- No need to do the nil check as "A nil map is equivalent to an empty map except that no elements may be added." [1]
[1] https://go.dev/ref/spec#Map_types
=> NO-JIRA: Fix HasOSImage function

test/e2e-techpreview/main_test.go, test/e2e/msbic_test.go, test/e2e/nodedisrupt_test.go
This PR moves ManagedBootImages and NodeDisruptionPolicy  e2es to the main test suite, as they have been recently GAed.
=> NO-ISSUE: Move ManagedBootImages and NodeDisruptionPolicy to default e2e suite

manifests/machineconfigcontroller/update-bootimages-validatingadmissionpolicy.yaml, pkg/controller/machine-set-boot-image/platform_helpers.go
I enabled the ManagedBootImage feature for the AWS platform as part of managing boot images via the MCO 
See the instructions in this PR for testing GCP for setting up the cluster. 
https://github.com/openshift/machine-config-operator/pull/4083
Please note that with AWS instead of directly using one boot image for each cluster version like GCP does. AWS uses a specific boot image per region for each version and they are stored in the ami field 
You can see each region and the value assigned to that ami in the coreos-bootimages configmap in the machine-config-operator namespace for validation that it's correct.
=> MCO-1214: Enabled boot images updates for AWS

internal/kubeutils.go
Closes OCPBUGS-31298
When the node status is updated, detect if `reconcileMaster` actually makes any changes to the node config. If empty then prevent making no-op calls
1) #4277 increases the `nodeStatusReportFrequency` to 10s and adds logs when an empty patch is made in function `UpdateNodeRetry`.
```
if bytes.Equal(patchBytes, []byte("{}")) {
klog.Infof("No change detected in UpdateNodeRetry")
}
```
These logs will indicate reduction in the empty patch calls made to the api-server
2)  grepping the MCC's node update calls in the kube-api audit logs
=> OCPBUGS-31298: Prevent no-operation patches from overloading the kube-api server with unnecessary calls

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
as of cri-o 1.30 (available in 4.17), it now supports a per runtime minimum memory, which allows us to customize the minimum allowed memory for a container. Now, we can utilize the fact crun can run with as low as 512 kb to allow users to specify tighter memory limits for their containers
CRI-O: set a customized minimum memory limit for containers run by crun, as its memory footprint is much lower. Now, if using the crun OCI runtime, a container can have a memory limit as low as 512 KB
=> NO-JIRA: crio: set min memory for crun

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
This commit sets `crun` as the default container runtime in OCP for 4.17
I'm in the process of adding test coverage for this behavior.
Make crun the default container runtime
=> OCPNODE-2357: templates/master/cri-o: make crun as the default container runtime

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Reverts openshift/machine-config-operator#4437; tracked by https://issues.redhat.com/browse/OCPBUGS-38320
4.18/4.17 Disruption failures
```
/payload-job periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-upgrade-out-of-change
```
```
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-serial
``` …
=> OCPBUGS-38320: Revert "templates/master/cri-o: make crun as the default container runtime"

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Reverts #4518 ; tracked by https://issues.redhat.com/browse/OCPBUGS-38321
4.18/4.17 Disruption failures
```
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-upgrade-out-of-change
```
```
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-serial
```
CC: @sohankunkerkar
<div …
=> OCPBUGS-38321: Revert "templates/master/cri-o: make crun as the default container runtime"

templates/common/on-prem/files/keepalived.yaml
When we dropped the privileged flag from the on-prem containers we missed that the keepalived-monitor container needs access to iptables in order to signal to keepalived whether the HAProxy redirect rule is in place. This change gives it the necessary caps to do that.
=> OCPBUGS-37984: Give keepalived-monitor necessary capabilities

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
For a while now, CRI-O can attempt to repair the storage directory on start-up following an unclean shutdown, such as a node crash or unexpected restart. This allows CRI-O to recover from a storage directory corruption, alleviating potential crashes or termination with a fatal error once it's started back up.
However, this internal repair feature has to be enabled to take effect, so it's currently an opt-in solution. This feature has matured and can be turned on as the new default when deploying OpenShift clusters. As a result, our customers will benefit from improved cluster resilience.
Thus, turn the internal feature on as the new default.
Related:
- https://github.com/cri-o/cri-o/pull/8417
- https://github.com/cri-o/cri-o/issues/7177
Deploy …
=> OCPNODE-2482: Enable CRI-O internal repair feature as the default

docs/MachineConfigDaemon.md
This adds a ref link to `docs/NodeDisruptionPolicy.md` under the Rebootless Updates section in `docs/MachineConfigDaemon.md`.
=> NO-ISSUE:  Add ref link to NodeDisruptionPolicy in docs/*

pkg/daemon/pinned_image_set.go
This reorders the callback registration so the lister object is not empty when called
There should not be any daemon panics for CI runs as listed in https://issues.redhat.com/browse/OCPBUGS-37850
=> OCPBUGS-37850: Machine-config daemon ListPools panic during tech-preview CI runs

pkg/daemon/daemon.go, pkg/daemon/update.go, pkg/server/api.go
This change updates the message verbs to use %q instead of %s, where appropriate, to properly escape output. This is to ensure potentially malicious input will be properly escaped.
Read the code
Updates verbs to use %q where appropriate
=> OCPBUGS-31777: Updates message verbs to use %q where appropriate

cmd/machine-config-controller/start.go, pkg/controller/node/node_controller.go, pkg/controller/node/node_controller_test.go, test/e2e-bootstrap/bootstrap_test.go
Sync MCP according to MachineOSConfig - CurrentImagePullspec update to capture image built completion to (1) avoid unnecessary syncing (2) make sure that the MCP is notified of a successful image build as soon as possible 
1. Opt a pool in to On Cluster Layering by creating a MachineOSConfig for it
2. Wait for image to be built
3. Watch image building process and time the interval between timestamp1-new image built and timestamp2-newly built image start to roll out 
4. Make sure that it won't take too much time to apply the new image once it has been built.
=> OCPBUGS-35509: In OCB/OCL it takes too much time to apply the new image once it has been build

pkg/server/api.go
Disallowed two insecure ciphers from the MCS server settings:
- TLS_RSA_WITH_AES_128_GCM_SHA256
- TLS_RSA_WITH_AES_256_GCM_SHA384   
With this fix, the server should no longer use the ciphers listed above. This can be tested using the method described [in this comment](https://issues.redhat.com/browse/MCO-850?focusedId=25198979&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25198979).
=> OCPBUGS-36850: Port number 22623 exposing weak ciphers to external client from master node IP

manifests/on-prem/coredns.yaml, manifests/on-prem/keepalived.yaml, templates/common/on-prem/files/coredns.yaml, templates/common/on-prem/files/keepalived.yaml, templates/master/00-master/on-prem/files/haproxy.yaml
Fixes: [OCPBUGS-38770](https://issues.redhat.com/browse/OCPBUGS-38770)
Cherry-pick of #4504 
Updated the templates and manifest files to pin the required SCCs to workloads in platform namespaces (`openshift-kni-infra`,  `openshift-openstack-infra`, `openshift-vsphere-infra`) - added annotations for the `privileged` SCC to the following pods:
- `coredns` on both master and worker nodes
- `haproxy` on master nodes
- `keepalived` on both master and worker nodes
The SCC chosen is `privileged`, which is already in use by these pods, ensuring no change to the SCC used.
Check that the required SCC annotations are present on the specified pods.
Pin required SCCs to platform namespace workloads, including `coredns`, …
=> [release-4.17] OCPBUGS-38770: SCC-pinning for openshift workloads

manifests/on-prem/coredns.yaml, manifests/on-prem/keepalived.yaml, templates/common/on-prem/files/coredns.yaml, templates/common/on-prem/files/keepalived.yaml, templates/master/00-master/on-prem/files/haproxy.yaml
Fixes: [OCPBUGS-38711](https://issues.redhat.com/browse/OCPBUGS-38711)
Cherry-pick of #4504 
Updated the templates and manifest files to pin the required SCCs to workloads in platform namespaces (`openshift-kni-infra`,  `openshift-openstack-infra`, `openshift-vsphere-infra`, `openshift-nutanix-infra`) - added annotations for the `privileged` SCC to the following pods:
- `coredns` on both master and worker nodes
- `haproxy` on master nodes
- `keepalived` on both master and worker nodes
The SCC chosen is `privileged`, which is already in use by these pods, ensuring no change to the SCC used.
Check that the required SCC annotations are present on the specified pods.
Pin required SCCs to platform namespace workloads, …
=> [release-4.16] OCPBUGS-38711: SCC-pinning for openshift workloads

templates/common/_base/files/configure-ovs-network.yaml
The linux bridge can be configured to add a virtual switch between one or many ports. This can be done by a simple machine config that adds:
"bridge=br0:enpf0,enpf2 ip=br0:dhcp"
to the the kernel command line options which will be processed by dracut.
The use case of adding such a virtual bridge for simple IEEE802.1 switching is to support PCIe devices that act as co-processors in a baremetal server. For example:
```
--------         ---------------------
| Host |  PCIe   |    Co-processor   |
|  eth0|<------->|enpf0 <-br0-> enpf2|<---> network
|      |         |                   |
--------         ---------------------
```
This co-processor could be a "DPU" network interface card. Thus the co-processor can be part of the same underlay network as the cluster and pods can be scheduled on …
=> OCPBUGS-39226: Enable the use of Linux Bridge as the ovs default port connection

manifests/on-prem/coredns.yaml, manifests/on-prem/keepalived.yaml, templates/common/on-prem/files/coredns.yaml, templates/common/on-prem/files/keepalived.yaml, templates/master/00-master/on-prem/files/haproxy.yaml
Fixes: [OCPBUGS-38712](https://issues.redhat.com/browse/OCPBUGS-38712)
Cherry-pick of #4504 
Updated the templates and manifest files to pin the required SCCs to workloads in platform namespaces (`openshift-kni-infra`,  `openshift-openstack-infra`, `openshift-vsphere-infra`, `openshift-nutanix-infra`) - added annotations for the `privileged` SCC to the following pods:
- `coredns` on both master and worker nodes
- `haproxy` on master nodes
- `keepalived` on both master and worker nodes
The SCC chosen is `privileged`, which is already in use by these pods, ensuring no change to the SCC used.
Check that the required SCC annotations are present on the specified pods.
Pin required SCCs to platform namespace workloads, …
=> [release-4.15] OCPBUGS-38712: SCC-pinning for openshift workloads

test/e2e-techpreview/helpers_test.go, test/e2e-techpreview/onclusterlayering_test.go, test/e2e/mcd_test.go, test/helpers/archiveartifact.go, test/helpers/archiveartifact_test.go, test/helpers/nodestate.go, test/helpers/utils.go
Fixes: OCPBUGS-39131
Removes the node / Machine deletion call and ensures that the node scaledown function waits for all of the nodes to be ready and prioritizes the nodes it created for deletion. Also modifies `GetRandomNode()` to ensure that the node it returns is actually ready. If not, `GetRandomNode()` will poll for up to 5 minutes for a node to become ready.
Run the e2e test suite. All tests should pass.
Fixes node scaledown for e2e tests
=> OCPBUGS-39131: fixes node scaledown for e2e tests

go.mod, go.sum, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/github.com/containers/image/v5/docker/docker_image.go, vendor/github.com/containers/image/v5/docker/docker_image_dest.go, vendor/github.com/containers/image/v5/docker/docker_image_src.go, vendor/github.com/containers/image/v5/docker/docker_transport.go, vendor/github.com/containers/image/v5/docker/registries_d.go, vendor/github.com/containers/image/v5/version/version.go, vendor/modules.txt
This bumps github.com/containers/image to v5.29.4 which includes the fix for CVE-2024-3727 vulnerability. More details can be found [here](https://github.com/containers/image/pull/2418#issuecomment-2223604474).
=> OCPBUGS-37032: CVE-2024-3727 ose-machine-config-operator-container: containers/image: digest type does not guarantee valid type

templates/common/_base/files/configure-ovs-network.yaml
In some circumstances it is necessary to disable the ethtool setting feature-esp-tx-csum-hw-offload. Previously if this was disabled on the underlying interface, that setting would be lost when br-ex was created. This patch adds it to the list of configuration values to maintain from the underlying interface.
For the time being I am only persisting the specific value needed to fix the referenced bug. We may want to consider persisting all ethtool configuration as a followup, but I'm unsure of the implications of that right now so I'd like to get this specific problem fixed before worrying about more general cases.
=> OCPBUGS-39438: Persist ethtool hw offload setting for br-ex

cmd/apiserver-watcher/README.md, templates/master/00-master/azure/files/opt-libexec-openshift-azure-routes-sh.yaml, templates/master/00-master/gcp/files/opt-libexec-openshift-gcp-routes-sh.yaml
iptables is going away in RHEL10; this PR ports {azure,gcp}-routes.sh from iptables to nftables.
What's different:
- The old azure script created separate iptables and ip6tables rules, but the nftables version just uses the `inet` family so we can put both sets of rules together (and we don't need to check if IPv6 is enabled or not; the IPv6 rule will just never match anything if IPv6 is disabled.)
- The old version used an iptables rule per VIP, the new version uses a single nftables rule that does a set match against all the VIPs at once.
- The old version did "figure out which rules don't belong, then remove then, then add new rules", while the new version does "atomically overwrite the old rules with the new rules".
Other than that (and the commit that removes an unnecessary ACCEPT …
=> MCO-1248: port {azure,gcp}-routes.sh from iptables to nftables

templates/common/on-prem/units/on-prem-resolv-prepender.path.yaml
=> OCPBUGS-39222: Do not enable on-prem-resolv-prepender.path for UPI

pkg/apihelpers/apihelpers.go, pkg/daemon/constants/constants.go, pkg/daemon/update.go
On failure to execute `coreos-update-ca-trust` service, the daemon will attempt to run the `update-ca-trust` command directly. This is needed on RHEL nodes as this service is not included on them by default.
Follow the reproductions steps on the bug. Daemon logs will make note of the MCD falling back to the command:
```
I0827 18:54:36.728842    3232 update.go:2650] Performing post config change action: Restart for config rendered-worker-99a3e7096a7eea7769d164af4b6742fe
I0827 18:54:36.732053    3232 update.go:2635] Running: systemctl restart coreos-update-ca-trust.service
I0827 18:54:36.738163    3232 update.go:2650] Error executing coreos-update-ca-trust.service unit, falling back to command
I0827 18:54:37.595582    3232 update.go:2650] …
```
=> OCPBUGS-38632: MCPs with RHEL nodes are degraded when a userCA bundle is added to the cluster

pkg/controller/common/layered_node_state.go, pkg/controller/node/node_controller.go, pkg/controller/node/node_controller_test.go, pkg/controller/node/status.go, pkg/controller/node/status_test.go
- Tweaked a few things with how OCL populates MCP status numbers. [More details here](https://issues.redhat.com/browse/OCPBUGS-32812?focusedId=25185877&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25185877).
- Removed MachineConfigNode based status population, this will have to be reworked as a [separate card](https://issues.redhat.com/browse/MCO-1228). 
- Beefed up a few of the node controller log messages, so it is easier to understand what node/pool the controller is working on.
- Updated some of the OCL related unit tests to work with the fixed mechanism, but this is really more of a stopgap. I think a bigger rework needs to be done in the test suite which I believe @cheesesashimi has alluded to. Some of the tests did not seem …
=> OCPBUGS-32812: When newly built images rolled out, the update progress is not displaying correctly (went 0 --> 3)

install/0000_90_machine-config_01_prometheus-rules.yaml, pkg/daemon/constants/constants.go, pkg/daemon/drain.go, pkg/daemon/update.go, pkg/operator/metrics.go, pkg/operator/operator_test.go, pkg/operator/status.go, pkg/operator/status_test.go
- Added a Prometheus alert if the image registry override `image-registry-override-drain` configmap is detected
- Fixed a bug which was causing the drain skip configmap method to no longer work. We want the workaround to still be functional during deprecation. We plan to remove the configmap workaround completely in 4.19.
1. Create the configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: image-registry-override-drain
namespace: openshift-machine-config-operator
```
2. You should now seen an alert called `MCODrainOverrideConfigMapAlert` alerting the admin of the workaround deprecation.
3. Ensure that the configmap workaround works as expected to skip the drain.
4. Now, delete the configmap. This should remove the alert.
=> OCPBUGS-38857:  Add alert for users of deprecating the Image Registry workaround

Dockerfile
The bot only updated the "rhel 7" dockerfile for some reason in: github.com/openshift/machine-config-operator/pull/4561
Confusingly, that's the one used for the product build, whereas the "regular" dockerfile is used for CI builds. We should probably keep the aligned.
cc @djoshy
=> NO-ISSUE: Dockerfile: update to 4.18 image

templates/common/_base/files/configure-ovs-network.yaml, templates/common/_base/files/vsphere-disable-vmxnet3v4-features.yaml
The first option attempted by @cybertron did not work well for the customer for some reason. We decided to disable offloads all-together in vsphere as is simply not working for now.
=> OCPBUGS-39438: Disable ESP offload in vmxnet3 including bonds

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
upstream moved to crun, but there's still an outstanding bug in crun that's breaking graceful shutdowns. Force runc until we identify the bug
=> OCPBUGS-41956: crio: force runc by default

pkg/controller/node/node_controller.go
Added a nil check for the oldPool field before using it.
The periodic test listed in bug should no longer have an undiagnosed panic.
=> OCPBUGS-41631: Panic seen in CI job for MCC pod

templates/common/openstack/files/usr-local-bin-openstack-kubelet-nodename.yaml
We need to mount and umount the config drive to get the hostname.
=> OSASINFRA-3585: openstack: mount config drive when needed

pkg/controller/common/layered_node_state.go, pkg/controller/node/node_controller.go, pkg/controller/node/node_controller_test.go, pkg/controller/node/status.go, pkg/controller/node/status_test.go
Manual cherry pick of https://github.com/openshift/machine-config-operator/pull/4583
=> [release-4.16] OCPBUGS-41806: When newly built images rolled out, the update progress is not displaying correctly (went 0 --> 3)

templates/common/_base/files/bond-esp-offload.yaml, templates/common/_base/files/vsphere-disable-vmxnet3v4-features.yaml
We first thought that this issue was specific to vmxnet3 driver but it
looks like it is a widespread issue of bonds: it has been observed that
the kernel enables ESP offloads of bond devices in active/backup mode
even if slaves apparently don't support it. So set ESP offload
features off in bond devices if they are off in slave devices for the
time being.
Sorry for the extra noise but the situation is developing as a PRIO case.
=> OCPBUGS-39438: Set ESP offloads off in bonds if slaves don't support them

templates/common/_base/files/root-ca.yaml
Removing writing this CA to disk as nothing we know of uses it. Read [MCO-1323](https://issues.redhat.com/browse/MCO-1323) for more details.
No functional changes are expected, existing e2es & paayloads should pass.
=> MCO-1323:  Stop writing root-ca to disk

templates/common/on-prem/files/resolv-prepender.yaml
In some cases, the tmp files were not removed.
This patch fixes that.
When deploying Shift On Stack, check in /tmp and we should not see any tmp.XXX files anymore.
Temporary files created to populate resolv.conf are now removed when the script has run.
=> OCPBUGS-42018: on-prem/resolv-prepender: stop leaking tmp files

cmd/machine-config-daemon/firstboot_complete_machineconfig.go, pkg/daemon/daemon.go, pkg/daemon/runtimeassets/README.md, pkg/daemon/runtimeassets/machine-config-daemon-revert.service.yaml, pkg/daemon/runtimeassets/revertservice.go, pkg/daemon/runtimeassets/revertservice_test.go, pkg/daemon/runtimeassets/runtimeassets.go, pkg/daemon/update.go, test/e2e-techpreview/onclusterlayering_test.go, test/e2e/osimageurl_override_test.go, test/helpers/utils.go
This adds code that reverts from a layered MachineConfigPool to a non-layered MachineConfigPool.
Why this was so troublesome is:
- When a MachineConfig is written to the node, it is placed in the portions of the filesystem that are mutable according to ostree.
- When a container image containing those MachineConfigs is written onto the node using rpm-ostree, it technically overwrites those preexisting MachineConfigs. In doing so, the container is now claiming (for lack of a better term) ownership of those files.
- The "factory" OS image does not contain these MachineConfigs.
- So when we roll back from the customized image to the "factory" image, because the MachineConfig files on disk are now owned by the customized container, they are removed when the factory OS image …
=> MCO-694: revert from layered pool to non-layered pool

templates/common/_base/units/wait-for-primary-ip.yaml, templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
Because of how firstboot works, we should not use features that were added to RHEL (in here, systemd) late in the process, e.g. only in OCP 4.12
`Restart=on-failure` for `Type=oneshot` service is one of them. Albeit very helpful, it does break certain deployments. In order to fix this, we are falling back to an old, ugly but proven `until ... do ... done` bash loop.
Fixes: OCPBUGS-38012
=> OCPBUGS-38012: Do not use 'restart' for 'oneshot' service

pkg/controller/kubelet-config/helpers.go, pkg/controller/kubelet-config/kubelet_config_nodes.go
CGroupsV1 support would be deprecated and hence a warning and a condition status update needs to be present for the clusters that are still on CGroupsV1 mode.
=> OCPNODE-2399: Add a condition in the config node object

templates/master/01-master-kubelet/_base/units/kubelet.service.yaml, templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Fixes: [OCPBUGS-42419](https://issues.redhat.com/browse/OCPBUGS-42419)
The restorecon command expect a path to be given.
providing a path is mandatory.
see man page: https://linux.die.net/man/8/restorecon
At the moment the command does nothing and the error
is swallowed due to the dash (-) in the beginning
of the command.
check that directories/files selinux labels are matching
the expected labels provided by the container-selinux package 
Provide a path to restorecon command
=> OCPBUGS-42419: kubelet-service: provide path to restorecon command

templates/common/openstack/files/usr-local-bin-openstack-kubelet-nodename.yaml, templates/common/openstack/units/openstack-kubelet-nodename.service.yaml
In https://github.com/openshift/machine-config-operator/pull/4570, we
added a dependency on a service that in certain cases (Hypershift) will
never run. That makes Kubelet never starting.
We initially relied on br-ex because we thought it was the simplest way
to use a predictable interface name to reach the metadata via curl.
In fact, it's not reliable because we rely on br-ex being actually a
thing (OVN k8s CNI uses it but some other CNIs don't). And also because
br-ex might come online later. We don't really need it to be online as
we already have an interface connected to the network and able to reach
the metadata.
Let's use `ip` command to find how which interface can reach the
metadata over ipv6 and use it.
* Hypershift jobs for OpenStack will …
=> OCPBUGS-42392: openstack: relax openstack-kubelet-nodename systemd dependency

pkg/controller/render/render_controller.go
Closes: OCPBUGS-38733
If a renderedMC in use gets deleted, regenerate it without reconciling. The daemon will take care of the reconciling.
1. Create a MC to deploy any file in the worker MCP
2. Get the name of the new rendered MC, like for example "rendered-worker-bf829671270609af06e077311a39363e"
3. When the first node starts updating, delete the new rendered MC
`oc delete mc rendered-worker-bf829671270609af06e077311a39363e`
4. It should be regenerated and deployed again
=> OCPBUGS-38733: Regenerate the rendered MC in use when deleted

templates/common/openstack/units/afterburn-hostname.service.yaml
This was added via https://github.com/openshift/machine-config-operator/pull/4092 but maybe incompatible with old bootimages. See linked bug https://issues.redhat.com/browse/OCPBUGS-38012 for additional context for on-prem situation.
=> OCPBUGS-42324: openstack: fix non-old systemd compatible unit

pkg/operator/sync.go
Closes: [OCPBUGS-42546](https://issues.redhat.com/browse/OCPBUGS-42546)
Added a nil check before posting a degrade from `syncMachineConfiguration` within `syncRequiredMachineConfigPools`
Follow repro instructions in bug.
=> OCPBUGS-42546: The MCO does not properly degrade when pools are failing to render a new config

pkg/daemon/update.go
Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/4522
=> OCPBUGS-38382:  [release-4.12] daemon/update: disable systemd unit before overwriting

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
This commit sets `crun` as the default container runtime in OCP for 4.18
I'm in the process of adding test coverage for this behavior.
Make crun the default container runtime
=> OCPNODE-2633: templates/*: make crun as the default container runtime

templates/master/01-master-kubelet/_base/units/kubelet-cleanup.service.yaml, templates/worker/01-worker-kubelet/_base/units/kubelet-cleanup.service.yaml
This only impacts TechPreview or DevPreview jobs right now, since DRA is still in Alpha. We remove the dra_manager_state like we do with the cpu and memory manager state files.
Clusters on TechPreview or DevPreview will exhibit on upgrade:
```
failed to run Kubelet: failed to create claimInfo cache: error calling GetOrCreate() on checkpoint state: failed to get checkpoint dra_manager_state: checkpoint is corrupted"
```
=> OCPBUGS-43328: remove dra manager state

docs/MachineConfig.md, pkg/daemon/update.go, test/e2e-single-node/sno_mcd_test.go, test/e2e/mcd_test.go
Ref: https://issues.redhat.com/browse/COS-2947
Related to https://github.com/openshift/os/pull/1621
This PR adds `sysstat` to the list of extensions.
=> COS-2947: Add sysstat extension support

pkg/daemon/daemon.go, pkg/daemon/metrics.go
- What I did
Implemented metric collection in the mcd to report unsupported packages by vendor via the mcd_local_unsupported_packages_by_vendor metric.
follow the provided e2e test TestInstallRPMAndCheckMCDMetrics to verify that:
The RPM package (aeskeyfind) is successfully installed on the node.
The MCD reports the correct metric reflecting the installed package.
e2e test found here https://github.com/openshift/machine-config-operator/pull/4614/files#diff-6324e53eb8b87fa591d0dd87722e4dff1200a2bc57d7c83f042a90f4be53f68b
Added metric reporting in the mcd.
=> MCO-1276: Integrate Metric Collection with MCO Daemon

cmd/machine-config-operator/main.go, install/0000_80_machine-config_04_deployment.yaml, install/0000_80_machine-config_06_clusteroperator.yaml, pkg/operator/operator.go, pkg/version/version.go
By setting a new `operator-image` entry in the ClusterOperator `status.versions` manifest, so [the cluster-version operator will wait for the in-cluster status][1] to have both:
* The `operator` value we already declare, so the CVO waits for us to hit the target version.
* The `operator-image` value I'm adding in this commit, to help distinguish between single-arch and multi-arch targets which share the same version string (but have unique release and MCO pullspecs).
Without this change, the CVO immediately thinks the MCO has completed its update ("`operator` matches 4.13.0, and that's all I've been asked to match!") while the MCO is still working to pivot to the new, multi-arch component.  Folks who try to take advantage of the new multi-arch functionality at this point might be …
=> NO-ISSUE: pkg/operator/status: Block ClusterVersion updates until multi-arch transitions complete

templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
This PR changes timeouts used by haproxy when deciding whether the master backend (i.e. k8s api server) is dead or alive.
The previous probe was relatively strict, allowing for a very fast failover but at the same time very prone to temporary flakiness.
The new configuration aligns haproxy with the readiness probe used by k8s when detecting if pod is dead or alive. Aligning those configurations removes the mismatch we have when k8s believes api server is ready but haproxy sees it as dead.
A consequence of this change is a potential increase of the downtime when api server is forcefully removed. In the worst case scenario we may see unavailability for 15 seconds. This should not be happening much in a real setups, but for the sake of completeness this should be noted.
Fixes: OCPBUGS-43428
=> OCPBUGS-43428: Soften haproxy timeout for kubeapi probe

templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
It has been reported that for certain deployments in hub-spoke topology (a single metal cluster with 3500+ managed clusters attached), during upgrades the current limit of 20k connections to the loadbalancer is not big enough and clusters are reporting connection timeouts.
As the current limit of 20k is an arbitrary selected number and the tests report that increasing it to 40k does help for the scenario described above, we should increase the current default limit.
This PR does not change the overall recommendation to use external enterprise-grade loadbalancer for such a resource-consuming workload.
=> OCPBUGS-38490: Increase connection limit for cluster loadbalancer

templates/common/_base/files/bond-esp-offload.yaml, templates/common/_base/units/ipsec.service.yaml
We learnt a bit more about the ESP offload problem with bonds (part 3).
Actually it is OVS which does not support ESP offload, neither in hardware 
nor as part of GRO (generic receive offload). The fact that esp_offload kernel
module plays a role if both scenarios without OVS supporting either, combined
with the bond device reporting that ESP offload was supported when it really wasn't,
threw us us in all kind of directions. That's like three potential kernel issues to be
tracked from https://issues.redhat.com/browse/RHEL-58811
Reworked dispatcher script to disable ESP offload if interface is in OVS
bridge.
Delay ipsec service after configure-ovs so that we have a chance to
disable ESP offloads before it starts. Otherwise libreswan can be
tricked into thinking ESP offload is supported and …
=> OCPBUGS-42987: Disable ESP offload for OVS attached interfaces

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml, templates/common/on-prem/units/on-prem-resolv-prepender.path.yaml
This PR changes the logic of how NetworkManager communicates changes in the environment and how they are picked by on-prem-resolv-prepender.
Previously the NM dispatcher script had a logic that would trigger a systemd service (either to start it or to restart). This proven to be problematic, prone to race conditions and in principle a complicated design.
Now we are moving to a model where systemd on its own will decide what and when to restart, in our case by leveraging the systemd path units.
NM dispatcher is now responsible only for writing a correct environment file (we need that in case DNS search domains change). Systemd path unit observes the file and if a change is detected, it will trigger whatever is necessary.
There is other stuff in the NM dispatcher script that we are keeping …
=> OPNET-569: Do not run resolv-prepender from NM dispatcher

templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
Manual cherry pick of https://github.com/openshift/machine-config-operator/pull/4596
Closes: OCPBUGS-42110
=> [4.15] OCPBUGS-42110: Do not use 'restart' for 'oneshot' service

pkg/daemon/cri/cri.go
Explicitly set the pinned image set dialer to use passthrough.
In tech preview, apply a pinned image set object, and ensure that the images are being pinned as expected. See attached bug for more details.
```
$ oc create -f - << EOF
apiVersion: machineconfiguration.openshift.io/v1alpha1
kind: PinnedImageSet
metadata:
labels:
name: tc-73623-worker-pinned-images
spec:
pinnedImages:
- name: "quay.io/openshifttest/busybox@sha256:0415f56ccc05526f2af5a7ae8654baec97d4a614f24736e8eef41a4591f08019"
- name: quay.io/openshifttest/alpine@sha256:be92b18a369e989a6e86ac840b7f23ce0052467de551b064796d67280dfa06d5
EOF
```
=> OCPBUGS-43893: Pinned images not working

pkg/daemon/daemon.go, pkg/daemon/metrics.go, test/e2e/mcd_test.go, test/helpers/utils.go
1. Created an e2e test to verify the installation of unsupported RPM packages on nodes using rpm-ostree.
2. Implemented metric collection in the mcd to report unsupported packages by vendor via the mcd_local_unsupported_packages_by_vendor metric.
3. Ensured that the e2e test verifies the installation of the unsupported package, checks that the correct metrics are being reported, and includes cleanup logic to uninstall the package after the test completes.
Run the provided e2e test TestInstallRPMAndCheckMCDMetrics to verify that:
1. The RPM package (aeskeyfind) is successfully installed on the node.
2. The MCD reports the correct metric reflecting the installed package.
Added e2e test for verifying unsupported RPM …
=> MCO-1276, MCO-1339: Integrate Metric Collection with MCO Daemon and e2e testing automation

Dockerfile, Dockerfile.rhel7
This updates our Dockerfiles to use multi arch builders so that MCO devs who are building on non x86 architectures can use them without needing to modifying them locally.
=> MCO-1294: Update MCO Dockerfile to Use Multi-Base Images from OpenShift 4.18

templates/common/_base/files/bond-esp-offload.yaml, templates/common/_base/units/ipsec.service.yaml
Reworked dispatcher script to disable ESP offload if interface is in OVS bridge.
Delay ipsec service after configure-ovs so that we have a chance to disable ESP offloads before it starts. Otherwise libreswan can be tricked into thinking ESP offload is supported and might try to enable it anyway.
(cherry picked from commit fbf7f02fc8f93481dcc7bb44657046ea98814a07)
=> OCPBUGS-44240: Disable ESP offload for OVS attached interfaces

templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
Manual cherry pick of https://github.com/openshift/machine-config-operator/pull/4596
Closes: OCPBUGS-42111
=> [4.14] OCPBUGS-42111: Do not use 'restart' for 'oneshot' service

pkg/operator/sync.go
Closes: OCPBUGS-42695
The lister returns mosc's which have no guarantee of the order. When template renderer controller consumes this list, its order varies every control loop iteration. Since the MCD's daemonset has every MOSC's image pull secret in it, an order change means a difference in spec causing it to be restarted again. Have the order constant by sorting it by alphanumerical name prevents changes to the manifest MCD daemonset template
Configure several MOSC resources for several MCPs, the MCD pods should only restart per MOSC
Sort the moscs alphanumerically
=> OCPBUGS-42695: Sort the moscs alphanumerically

lib/resourceapply/machineconfig.go, lib/resourcemerge/meta.go
backport of https://github.com/openshift/machine-config-operator/pull/4378
=> [release-4.16] OCPBUGS-44337: Removal of additionalTrustBundle CA does not remove certificate from node backport

templates/common/_base/files/gcp-disable-idpf-tx-checksum-off.yaml
See bug [1] for more details.
[1] https://issues.redhat.com/browse/OCPBUGS-38779
GCP driver docs: https://cloud.google.com/compute/docs/networking/using-idpf
/hold for:
* QE premerge validation
* GCP team ack
=> OCPBUGS-38779: Disable tx chksum for driver IDPF on GCP C3/C4

pkg/controller/build/buildrequest/assets/Containerfile.on-cluster-build-template, pkg/controller/build/buildrequest/assets/buildah-build.sh, pkg/controller/build/buildrequest/buildrequest.go, pkg/controller/build/buildrequest/buildrequestopts.go, pkg/controller/build/utils/helpers.go
Closes: [MCO-1273](https://issues.redhat.com//browse/MCO-1273)
Added support for proxy configuration specified in the Controller Config to the buildah-build scripts 
1) Add a cluster wide proxy like
```
oc get proxy/cluster -o yaml | yq
apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
creationTimestamp: "2024-09-19T13:45:39Z"
generation: 1
name: cluster
resourceVersion: "546"
uid: b9890313-569c-4083-8f1d-a97eb4bb42e3
spec:
httpProxy: http://username:passwd@ip:port/
httpsProxy: http://username:passwd@ip:port/
trustedCA:
name: ""
status:
httpProxy: http://username:passwd@ip:port/
httpsProxy: http://username:passwd@ip:port/
noProxy: .cluster.local,localhost
```
2) Add a network policy to only allow egress through the proxy
3) Trigger a build by …
=> MCO-1273: OCB respects proxy configuration in Controller Config

cmd/machine-config-controller/main.go, cmd/machine-config-controller/start.go, pkg/controller/bootstrap/bootstrap.go, pkg/controller/container-runtime-config/container_runtime_config_bootstrap_test.go, pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/container-runtime-config/helpers.go, test/e2e-bootstrap/bootstrap_test.go, test/framework/envtest.go
Fixes https://issues.redhat.com/browse/OCPBUGS-38292
This change prevents the automatic switch to crun during the upgrade from version 4.17 to 4.18. Customers can manually opt-in to use crun by deleting the MachineConfig that sets runc as the default runtime.
=> OCPBUGS-38292: controller: default to runc when upgrading clusters from 4.17 to 4.18

pkg/controller/template/render.go, pkg/operator/bootstrap.go, pkg/operator/render.go
In-cluster DNS support was previously added for the GCP platform. Only the platform specific portions of that solution have been updated to include the AWS platform.
=> CORS-3713: Extend in-cluster DNS support to AWS Platform

manifests/machineosbuilder/deployment.yaml
Closes: [OCPBUGS-44758](https://issues.redhat.com/browse/OCPBUGS-44758)
deployment: Ensures machine-os-builder has a higher priority when getting scheduled since its a part of the cluster control plane
machine os builder pods should now be scheduled with higher priority and passes the openshift/origin test for pods.
=> OCPBUGS-44758: Set priority class for machine-os-builder

pkg/controller/build/buildrequest/assets/Containerfile.on-cluster-build-template, pkg/controller/build/buildrequest/buildrequest.go, pkg/controller/build/buildrequest/buildrequest_test.go, pkg/controller/build/buildrequest/buildrequestopts.go, pkg/controller/common/helpers.go, pkg/controller/common/helpers_test.go, pkg/daemon/daemon.go, pkg/daemon/update.go, test/e2e-techpreview/onclusterlayering_test.go
Add logic to the Containerfile used to build the new OS image to be able to install extensions when using OCL. Extensions are installed via rpm-ostree and commited to the container image.
Enable OCL and create a MC with to install extensions, wait for the image to build and roll out and the extensions installed should be installed on the nodes.
Install extension via Containerfile when using OCL.
=> MCO-1331: Install extensions via Containerfile for OCL

cmd/machine-config-controller/main.go, cmd/machine-config-controller/start.go, pkg/controller/bootstrap/bootstrap.go, pkg/controller/container-runtime-config/container_runtime_config_bootstrap_test.go, pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/container-runtime-config/helpers.go, test/e2e-bootstrap/bootstrap_test.go, test/framework/envtest.go
This reverts commit fd148574acf50271171c33570a4ba80fd9e9e617, reversing changes made to 39e1cd3c3b04229c48988be1fb7f99b95856aff3.
The default MC takes precedence over the `ContainerRuntimeConfig`, meaning anyone upgrading to the new 4.17 will revert to runc until they notice and delete the newly created defaulting MC.
=> OCPBUGS-38292: Revert "controller: default to runc when upgrading clusters from 4.17 to 4.18"

pkg/controller/build/constants/constants.go, pkg/controller/build/helpers.go, pkg/controller/build/osbuildcontroller_test.go, pkg/controller/build/reconciler.go, test/e2e-techpreview/onclusterlayering_test.go
I added the ability for a cluster admin to request that the currently active
MachineOSBuild be rebuilt. This is done by adding the annotation
`machineconfiguration.openshift.io/rebuild` to the MachineOSConfig.
1. Bring up an OpenShift cluster.
2. Opt into on-cluster layering by creating a MachineOSConfig.
3. Wait for the build to complete.
4. Add the annotation `machineconfiguration.openshift.io/rebuild` onto the MachineOSConfig.
5. The controller should delete the current MachineOSBuild and a new one should be started in its place.
Adds rebuild functionality for OCL
=> MCO-1165: rebuild annotation

install/0000_90_machine-config_01_prometheus-rules.yaml
Corrected minor English language typos in PrometheusRule alert definitions. Specifically:
- Changed "tallys" to "tallies" in KubeletHealthState..
- Changed "specially" to "especially" in ExtremelyHighIndividualControlPlaneMemory.
- Changed "miutes" to "minutes" in SystemMemoryExceedsReservation.
N/A
Fixed minor typos and improved readability in PrometheusRule alert definitions for the machine-config-operator in OpenShift.
=> NO-ISSUE: Fix 3 typos

lib/resourceapply/apps.go, lib/resourceapply/machineconfig.go, lib/resourcemerge/apps_test.go, lib/resourcemerge/core_test.go, pkg/operator/sync.go
Adds a retry on error for applying the MCC deployment, the MCD daemonset and the MCS daemonset. I also took this opportunity to clean up some pointer library references.
These error logs mentioned in the bug [is quite rare](https://search.dptools.openshift.org/?search=MachineConfigDaemonFailed&maxAge=336h&context=1&type=junit&name=periodic-ci-openshift-release-master-ci-4.18-e2e-aws-ovn-techpreview-serial&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job), so it may be hard to verify this. Regardless, it should help clean up such failures.
=> OCPBUGS-38749: add retry on error for apply functions

templates/common/_base/files/container-storage.yaml
Updated current storage.conf configuration file template to reflect changes made over time to the upstream dependencies such as containers/storage package, etc. The changes include:
- Move the `size` attribute from the `storage` table into the specific file system driver table
- Update the `runroot` property from the `storage` table to reflect changes to the temporary directory default location
- Mention the `storage.options` table `Remap-User/Group` settings precedence over `Remap-UIDs/GIDs` when both are set
- Remove the `storage.options.thinpool` table entirely, as the support for DeviceMapper driver has been removed
- Disable the partial container image downloads as it is still considered an experimental feature that should be opt-in
- Add `use_hard_links` and …
=> OCPBUGS-44995: Update the storage.conf configuration file template

templates/common/aws/files/usr-local-bin-aws-kubelet-nodename.yaml
This ensures that any DHCP option set, configured with a trailing period (which must be done using the AWS CLI, and not the console), does not prevent nodes from joining the cluster.
With the previous logic, the nodename passed would contain a trailing period, which is not compatible with Kube's validation of object names.
This new logic ensures that we trim any trailing periods prior to passing the hostname over to kubelet
Create an AWS cluster with a custom DHCP option set. Ensure the custom domain name in the option set includes a trailing period (`foo.bar.baz.`), and then spin up new nodes. They should join the cluster with a node name, missing the trailing period.
=> OCPBUGS-45306: Remove trailing periods from AWS provided hostnames

test/e2e-ocl/onclusterlayering_test.go
Increase the timeouts in different stages of the ocl e2e tests.
N/A
[MCO-1416](https://issues.redhat.com//browse/MCO-1416): Increase timeouts in OCL e2e tests
=> MCO-1416: Increase timeouts in OCL e2e tests

pkg/operator/sync.go
Update the event message on pause of required pool where no updates are outstanding.
Pause a required machine config pool:
```bash
$ oc patch mcp/master --patch '{"spec": {"paused":true}}' --type=merge
```
Watch the `machine-config-operator` pod logs:
```bash
$ oc logs -n openshift-machine-config-operator -c machine-config-operator <pod-name> -f
Starting MachineConfigOperator
Event(v1.ObjectReference{Kind:"ClusterOperator", Namespace:"openshift-machine-config-operator", Name:"machine-config", UID:"a22bdfc5-84c1-4063-b66d-87f4e86815e2", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'OperatorDegraded: RequiredPoolsFailed' Failed to resync 4.18.0-0.nightly-arm64-2024-11-06-051902 because: **the required MachineConfigPool …
```
=> OCPBUGS-27477: Pausing Master MCP results in Alerts

pkg/daemon/node.go
Theoretically this shouldn't be empty by the time it gets to here, but in the error stacktrace: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.18-e2e-vsphere-ovn-upi-serial/1861922894817267712/artifacts/e2e-vsphere-ovn-upi-serial/gather-extra/artifacts/pods/openshift-machine-config-operator_machine-config-daemon-4mzxf_machine-config-daemon_previous.log we see this function panicking.
This seems to have actually been the second place where we hit this function in that logic loop? i.e. loadNodeAnnotations -> getNodeAnnotation -> getNodeAnnotationExt should have panicked if either node or node.Annotations is empty, but for some reason it didn't.  Weird. Also the fact that we have not seen this before makes it …
=> OCPBUGS-45860: daemon: add nil check for annotation fetching

cmd/machine-config-controller/start.go, pkg/apihelpers/apihelpers.go, pkg/controller/render/render_controller.go, pkg/controller/render/render_controller_test.go, test/e2e-bootstrap/bootstrap_test.go
Instead of the render controller just waiting on the controllerConfig status to reach completed (which requires template controller status to be completed), the render controller also should wait on the status of containerRuntime config and kubeletConfig
=> OCPBUGS-42636: Wait to render for other MC generating sub-controllers

manifests/machineosbuilder/deployment.yaml
Added required-scc annotation to machineosbuilder manifest
passes from CI for:
- e2e-aws-ovn-ocb-techpreview
- e2e-aws-ovn-upgrade-ocb-techpreview
=> OCPBUGS-46052: machine-os-builder deployment missing openshift.io/required-scc annotation

manifests/machineosbuilder/deployment.yaml
Added required-scc annotation to machineosbuilder manifest
passes from CI for:
- e2e-aws-ovn-ocb-techpreview
- e2e-aws-ovn-upgrade-ocb-techpreview
=> OCPBUGS-46583: [release-4.18] machine-os-builder deployment missing openshift.io/required-scc annotation 

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
historically crun has run with a subcgroup to allow it to own the cgroup configuration of a container this is more idiomatic with systemd's single owner rule.
The problem is the subcgroup means there is an extra cgroup for cadvisor to read metrics for, so moving to crun by default actually increases cpu usage. Dropping the subcgroup (with a new cri-o knob and this annotation) fixes this regression.
=> OCPBUGS-45928,OCPBUGS-46531: crio: drop crun subcgroup

cmd/machine-config-controller/main.go, cmd/machine-config-controller/start.go, pkg/controller/bootstrap/bootstrap.go, pkg/controller/container-runtime-config/container_runtime_config_bootstrap_test.go, pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/container-runtime-config/helpers.go, test/e2e-bootstrap/bootstrap_test.go, test/framework/envtest.go
We need to handle the following cases:
- The user has already set the default runtime and then updates to 4.17.z with this change.
- The user updates to 4.17.z with this change and then tries setting the default runtime of their choice.
- The user updates from 4.17.z with the defaulting logic to 4.18 and then wants to set the runtime.
=> [release-4.17] OCPBUGS-38292: controller: default to runc when upgrading clusters from 4.17 to 4.18

lib/resourceapply/apps.go
Added one more error to the retry list for applyManifest, so we don't immediately degrade. This is follow-up from https://github.com/openshift/machine-config-operator/pull/4698, as merging that uncovered these failures.
=> OCPBUGS-38749: add timeout error to applyManifest retry list

pkg/controller/node/node_controller.go
Add `"maxUnavailable"` to error string alerting users of invalid type definition.
Update `maxUnavailable` to an invalid value:
```
$ oc patch mcp/worker --patch '{"spec": {"maxUnavailable":"2"}}' --type=merge
```
Watch the `machine-config-controller` pod logs:
```
$ oc logs -n openshift-machine-config-operator -c machine-config-controller <pod-name> -f
Error syncing machineconfigpool worker: "maxUnavailable" invalid value for IntOrString: invalid type: string is not a percentage
```
OCPBUGS-33144: Add clarification to invalid maxUnavailable alert
=> OCPBUGS-33144: Add clarification to invalid maxUnavailable alert

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Reverts #4765 ; tracked by [TRT-1926](https://issues.redhat.com//browse/TRT-1926)
We are seeing cri-o panic in jobs after this and the cri-o package bump landed, which seems to be impacting nodes and causing some tests to fail.
```
/payload 4.19 blocking nightly 
```
CC: @haircommander
<div align="right">
PR created by <a …
=> TRT-1926: Revert #4765 "crio: drop crun subcgroup"

hack/build-image
When building the mco image, add an AUTHFILE check to allow users to specify a different file from the default one for the authentication to be used during the build process.
This is something I kept having to change manually because I use a different location for my openshift auth and not the default one that podman looks at. 
Add AUTHFILE option to make image to allow specifying a file path for the auth needed during build
run make image AUTHFILE=path/to/auth file and the podman build command outputed should have `--authfile=path/you/specified`
Add AUTHFILE option to make image to allow specifying a file path for the auth needed during build
=> NO-ISSUE: Add AUTHFILE option to make image

pkg/controller/drain/drain_controller.go
Add a couple of events to indicate drain failure in the MCC. Currently drain failures causes a prom alert, which isn't helpful for data aggregation in CI.
On failing drain, in addition to logs, we should also see events emitted.
=> MCO-81: Emit events to warn about failing drains

pkg/operator/status.go
956e7874dc (#4012) had added the "this should no longer trigger when adding a node to a pool" comment, but unfortunately, it's still triggering.  For example, in [this serial 4.19 run][1]:
```console
$ curl -s https://storage.googleapis.com/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.19-e2e-gcp-ovn-serial-crun/1868424902256627712/build-log.txt | grep 'PoolUpdating' | sort | uniq
time="2024-12-16T01:43:52Z" level=info msg="operator status: processing event" event="Dec 16 00:55:35.662 W clusteroperator/machine-config condition/Upgradeable reason/PoolUpdating status/False One or more machine config pools are updating, please see `oc get mcp` for further details" operator=machine-config
``
Checking PromeCIeus, the `Upgradeable=False` window seems to have been …
```
=> MCO-1482: pkg/operator/status: Drop PoolUpdating as an Upgradeable=False condition

cmd/machine-config-controller/start.go, pkg/apihelpers/apihelpers.go, pkg/controller/render/render_controller.go, pkg/controller/render/render_controller_test.go, test/e2e-bootstrap/bootstrap_test.go
This is an manual cherry-pick of #4727
=> OCPBUGS-47802: OCPBUGS-47801: trying to wait for sub-controllers

install/0000_90_machine-config_01_prometheus-rules.yaml
Added a runbook I wrote to the MCDPivotError  Alert
Trigger MCDPivotError  on cluster. Alert should now display associated runbook.
Added https://github.com/openshift/runbooks/blob/master/alerts/machine-config-operator/MachineConfigDaemonPivotError.md to alert as a runbook_url.
=> MCO-1449: Add MCDPivotError runbook to prometheus rules

pkg/controller/container-runtime-config/helpers.go, pkg/controller/container-runtime-config/helpers_test.go
Fix the bug where ImagePolicy fails to roll out for different namespaces due to a decoding error.
Apply ImagePolicy objects for different namespaces, the files under /etc/crio/policies will bu updated for all corresponding namespaces.
=> OCPBUGS-48195: use new buffer for decoding clusterOverridePolicyJSON

pkg/daemon/update.go, templates/common/_base/files/podman-policy-args.yaml, templates/common/_base/units/machine-config-daemon-pull.service.yaml, templates/master/01-master-container-runtime/_base/files/policy-no-sigstoresigned.yaml, templates/worker/01-worker-container-runtime/_base/files/policy-no-sigstoresigned.yaml
Update machine-config-daemon-pull.service.yaml to not use sigstore policy.json if pdman version is less than 4.4.1. it will use `/etc/machine-config-daemon/policy-for-old-podman.json` to skip the default `openshift` clusterimagepolicy verifications.
Using reproduce steps in the bug description
copied-machineset-modified-flgjt running using 4.5 base image
```
$ oc get machines.machine.openshift.io    -n openshift-machine-api
NAME                                                PHASE     TYPE         REGION      ZONE         AGE
ci-ln-cihng1k-76ef8-zm6hv-master-0                  Running   m6a.xlarge   us-east-1   us-east-1d   97m
ci-ln-cihng1k-76ef8-zm6hv-master-1                  Running   m6a.xlarge   us-east-1   us-east-1f   97m …
```
=> OCPBUGS-38809: Update machine-config-daemon-pull.service to use custom policy for Podman < 4.4.1

templates/common/_base/files/configure-ovs-network.yaml
We already do this in a few other places, but not on these two calls. Under some circumstances, this is causing ovs-configuration to fail until manual intervention is done.
=> OCPBUGS-41489: Specify interface type when adding ovs-port

templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml
added CUSTOM_KUBELET_LABELS env var to --node-labels parameter for kubelet in master node's template
The use case is a CAPI bootstrap provider install openshift need to advertise a given provider ID via label, so that the infrastructure provider can set the actual provider ID once verified.
add `CUSTOM_KUBELET_LABELS=mydummylabel=myvalue` to any of the environmental files used by kubelet (possibly `/etc/kubernetes/kubelet-envs`)
Inject master node labels via CUSTOM_KUBELET_LABELS env var
=> MGMT-19337: enable injection of custom kubelet labels via env var for master nodes

docs/MachineConfig.md, pkg/controller/common/helpers.go, test/e2e-single-node/sno_mcd_test.go, test/e2e/mcd_test.go
The KubeSAN operator requires the addition of 2 host level dependencies: `lvm2-lockd` and `sanlock` in order to manage shared LVM volumeGroup access.
- Added `ksan-storage` extension
Post boot, the extensions can be queried on each node via `rpm -qa | grep -E 'lvm2-lockd|sanlock'`
Added host-level support for kubesan operator
=> OCPEDGE-1419: Add ksan-storage extension

templates/common/gcp/files/usr-local-bin-update-dns-server.yaml, templates/common/gcp/units/gcp-update-dns.service.yaml, templates/master/00-master/gcp/units/openshift-gcp-routes.service.yaml
1. Added a update-dns-server script that adds DNS servers to /etc/NetworkManager/conf.d/dns-servers.conf. This script is run as part of gcp-update-dns.service which is also added as part of this PR. This service should run when the DNSType on the GCP platform is set to "ClusterHosted".
2. The `openshift-gcp-routes` service does not need to run when DNSType is "ClusterHosted". So, enable it conditionally
Start an IPI Install on GCP with userProvisionedDNS=true
Creates a gcp-update-dns.service that updates DNS configuration when GCP's DNSType is "ClusterHosted"
Conditionally runs the `openshift-gcp-routes` service
=> OCPBUGS-29067: GCP Custom-DNS: Update services that run on control plane nodes

pkg/controller/common/helpers.go
Fixes: OCPBUGS-34586
Add extension validation to controller's machine config validation function to catch the extension error before the daemon attempts to start updating nodes.
Example MC with an invalid extension `1-worker-extension.yaml`:
```
metadata:
labels:
name: 80-worker-extensions
spec:
config:
ignition:
version: 3.2.0
extensions:
- badName
```
1. Apply MC
```
$ oc apply -f 1-worker-extension.yaml
```
2. Wait for MCP to be in degraded state
```
$ oc get mcp
NAME     CONFIG                 UPDATED   UPDATING   DEGRADED 
worker   rendered-worker-XXXX   True      False      True
```
3. Delete MC
```
$ oc delete …
```
=> OCPBUGS-34586: Auto-recover from MC with invalid extension

templates/master/01-master-kubelet/_base/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml
Related to https://github.com/openshift/machine-config-operator/pull/4746
added CUSTOM_KUBELET_LABELS env var to --node-labels parameter for kubelet in master node's template
The use case is a CAPI bootstrap provider install openshift need to advertise a given provider ID via label, so that the infrastructure provider can set the actual provider ID once verified.
add CUSTOM_KUBELET_LABELS=mydummylabel=myvalue to any of the environmental files used by kubelet (possibly /etc/kubernetes/kubelet-envs)
Inject master node labels via CUSTOM_KUBELET_LABELS env var in base template
=> MGMT-19337: enable injection of custom kubelet labels via env var in base template

templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
With nmstate `br-ex` creation using static IP, it looks like the systemd boot ordering can change and we can attempt to run `30-resolv-prepender` before `nodeip-configuration.service`.
When `30-resolv-prepender` runs it tries to touch a file in `/run/nodeip-configuration` when it does not exist.
```log
nm-dispatcher[2409]: touch: cannot touch '/run/nodeip-configuration/br-ex-up': No such file or directory
```
The quick fix is to always mkdir before touching, then we don't have to track the global state of `/run/nodeip-configuration`
=> OCPBUGS-46072: create /run/nodeip-configuration before use

pkg/operator/status.go, pkg/operator/sync.go
Added a clear CO degrade function, which is called after a successful invocation of an operator sync function. 
On a build without this fix:
1. Degrade the operator.  I did this is by scaling down the CVO and editing the `releaseVersion` field in the `machine-config-operator-images` configmap to a bad value. This will cause `syncRenderConfig` to fail and degrade the operator(visible in the CO object and operator logs). 
2. Now, deploy an MC update to the master pool. This will cause the operator to be stuck in `syncRequiredMachineConfigPool` sync function, where it'll wait until the master pool completes the update. 
3. While the master pool is still updating, restore the `releaseVersion` back to the original value. You should see the operator log …
=> OCPBUGS-48250: MCO CO degrades are stuck on until master pool updates complete

devex/cmd/onclustertesting/README.md, devex/cmd/onclustertesting/ci.go, devex/cmd/onclustertesting/machineosconfigs.go, devex/cmd/onclustertesting/opts.go, devex/cmd/onclustertesting/secrets.go, devex/cmd/onclustertesting/setup.go, pkg/controller/build/buildrequest/machineosbuild_test.go, test/e2e-ocl/helpers_test.go, test/e2e-ocl/onclusterlayering_test.go, test/helpers/machineosconfigbuilder.go
- Removed some old code that dealt with copy etc-pki-entitlement secrets. This is now handled by the operator in https://github.com/openshift/machine-config-operator/pull/4756 which merged recently. 
- Fixed a couple of places where old "PodImageBuilder" was being assigned to `ImageBuilderType`. This isn't used anywhere in the controller, so it didn't break anything, but we should clean this up.
Existing e2es should pass. QE testing shouldn't be needed since this is just removing test/devex code.
=> NO-ISSUE: Remove etc-pki-entitlement cruft

templates/common/on-prem/files/resolv-prepender.yaml, templates/common/on-prem/units/on-prem-resolv-prepender.service.yaml
With the EnvironmentFile set to mandatory, this service fails if it gets triggered by the path unit before the dispatcher script has populated the env file. We don't want that, so this patch makes the file optional and will allow the service to run if it's not there.
=> OCPBUGS-49436: Make resolv-prepender env file optional

docs/MachineConfig.md, pkg/controller/common/helpers.go, test/e2e-single-node/sno_mcd_test.go, test/e2e/mcd_test.go
This reverts commit 302b6f0c5eb34d2dade80ab930cfdb96f26313fe.
KubeSAN project is no longer under development.
=> OCPEDGE-1585: Revert "OCPEDGE-1419 Add ksan-storage extension"

docs/MachineConfig.md
Updated the MachineConfig documentation to reflect when `sysstat` extension support was added.
"Add sysstat as RHCOS extension" [epic](https://issues.redhat.com/browse/COS-2945) references 4.18 as the release version.
OCPBUGS-49731: Correct MachineConfig documentation on sysstat extension support
=> OCPBUGS-49731: Correct MachineConfig documentation on sysstat extension support

pkg/controller/node/node_controller.go, pkg/controller/node/status.go
Added an additional check in `isNodeDone` to verify that a node rolling back is not mistakenly considered as done updating.
As the bug states, this is hard to reproduce, but the typical reproduction path is:
1. Configure maxUnavailable=2 in the worker pool
2. Create a MOSC resource for the worker pool and wait for the images to be applied
3. Remove the MOSC
4. Check if maxUnavailable value is honored
It takes several tries(5+) for this to cause the bug, as it relies on the daemon being slow _enough_ to react to the controller's node annotation updates, it's really a luck of the draw.
=> OCPBUGS-43552: maxUnavailable value is not honored when disabling OCL

install/0000_90_machine-config_01_prometheus-rules.yaml
- What I did
Added a runbook I wrote to the Alert
Trigger SystemMemoryExceedsReservation on cluster. Alert should now display associated runbook.
Added https://github.com/openshift/runbooks/blob/master/alerts/machine-config-operator/SystemMemoryExceedsReservation.md to alert as a runbook_url.
=> MCO-1492: Add new runbook for  SystemMemoryExceedsReservation  to alert

Makefile, cmd/machine-config-controller/start.go, pkg/controller/common/controller_context.go
I accidentally switched out the tech preview informer factory for the default informer factory as part of https://github.com/openshift/machine-config-operator/pull/4756. This swaps it back.
- In the default feature set mode, there shouldn't any [failed informer watches on the v1 MachineOSConfig objects](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_machine-config-operator/4830/pull-ci-openshift-machine-config-operator-master-e2e-gcp-op/1887666655807410176/artifacts/e2e-gcp-op/gather-extra/artifacts/pods/openshift-machine-config-operator_machine-config-controller-5b89bf5465-6kvb2_machine-config-controller.log):
```
E0207 02:33:17.847220       1 reflector.go:158] "Unhandled Error" …
```
=> OCPBUGS-50002: MCC complains about v1 MachineOSConfig in default featureset

pkg/daemon/update.go, pkg/daemon/writer.go
Closes: #[OCPBUGS-31778](https://issues.redhat.com/browse/OCPBUGS-31778)
- Updated select log messages to use %q format verbs
N/A
OCPBUGS-31778: Update format verbs for daemon alert logs
=> OCPBUGS-31778: Update format verbs for alert logs

pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
This change sets up the event handlers after the listers are created, so we shouldn't be running into panics described in the bug.
=> OCPBUGS-49959: Panic in the MCC when using OCL v1 GA

pkg/controller/common/helpers.go, pkg/controller/common/helpers_test.go, pkg/daemon/daemon.go, pkg/daemon/update.go
This is a manual cherrypick of #4805. The automatic cherrypick in #4809 failed due to the necessary extension validation function not existing in the correct directory.
- Added the bug fix first introduced in #4763 for OCPBUGS-49363
- Pulled in the changes from [this commit](https://github.com/openshift/machine-config-operator/commit/69e89548cd5fb4ed45e3c823ea8a1021b6743ea2) that enable the extension validation
See steps in #4763.
OCPBUGS-34586: Auto-recover from MC with invalid extension & move extensions validation helpers into ctrlcommon
=> [release-4.17] OCPBUGS-49363: Auto-recover from MC with invalid extension

internal/kubeutils.go
- Use nodeName instead of node in error message for setting node annotations. On a degraded node, such an error would result in the entire node object to be dumped in the node's annotation which was not user friendly.
- I also changed retry mechanism to use a backoff of `retry.DefaultRetry`, instead of `retry.DefaultBackoff` which is recommended for conflicts. 
- Reading through the bug, this seems to surface during upgrades/installs when the APIServer goes unavailable/nodes have high activity. It may be useful to simulate such conditions and see if the errors resurface.
- I suppose one could also explore ways to make the API update calls from the MCO to fail to simulate a retry error scenario.
=> OCPBUGS-33894: Avoid dumping Go struct in potentially user-facing reason annotation

templates/master/00-master/on-prem/files/keepalived-keepalived.yaml, templates/worker/00-worker/on-prem/files/keepalived-keepalived.yaml
When using dual-stack with OpenStack, both IPv4 and IPv6
share the same Neutron Port and this makes OVN thinks that
both addresses are associated to the same Node, but that might
not always be true as keepalived can put them in separate Nodes.
To change that, let's make sure the API VIPs stays together through
state changes, the same goes for Ingress VIPs.
=> OCPBUGS-50599: Enforce VIPs to be collocated at the same host

templates/common/openstack/files/usr-local-bin-openstack-afterburn-hostname.yaml, templates/common/openstack/units/afterburn-hostname.service.yaml
SELinux is preventing the afterburn binary in OpenStack's afterburn-hostname from writing anywhere useful. Instead we invoke the afterburn service and read its output.
Closes: #OCPBUGS-49394
=> OCPBUGS-49394: Fix SELinux failures running afterburn-hostname

templates/common/openstack/files/usr-local-bin-openstack-kubelet-nodename.yaml
Fixed an issue where hostnames with a trailing dot were not properly handled
Based on https://github.com/openshift/machine-config-operator/pull/4729
1. Provide a hostname with a trailing dot in the configuration.
2. Ensure the trailing dot is stripped and the correct hostname is set.
=> OCPBUGS-45459: Remove trailing period from Openstack provided hostnames

install/0000_80_machine-config_00_clusterreader_clusterrole.yaml
- Update the cluster-reader ClusterRole to have read-only permissions (get, list, and watch).
_Testing permission updates:_
1. Use this PR to launch a cluster.
2. View the cluster-reader permissions in the Openshift UI by going to `User Management` &#8594; `Roles` &#8594; `cluster-reader`
_Testing that functionality remained unchanged:_
OCPBUGS-47743: Update cluster-reader ClusterRole permissions
=> OCPBUGS-47743: Update cluster-reader ClusterRole permissions

pkg/daemon/update.go
- Stopped emitting `OSUpdateStarted` events for a specific scenario: there are some extensions currently in use, but no extension installs/uninstalls are taking place. In such cases, `rpm-ostree update` is not run and no OS updates are happening. I suspect this a special case that we accounted for that is no longer in use.
- Made the `OSUpdateStarted` event's message a bit more verbose for easier debugging. 
- Existing units/e2es should pass, this should not break extension functionality.
- Not sure this needs pre merge QE testing.
=> OCPBUGS-51009: OSUpdateStarted event should only be emitted on actual OS updates

pkg/daemon/osrelease/osrelease.go, pkg/daemon/update.go
Added an additional case for the isEL() check to account for the changes in `/etc/os-release` from [RHCOS layers EP](https://github.com/openshift/enhancements/blob/master/enhancements/rhcos/split-rhcos-into-layers.md). Some more context here: https://github.com/openshift/enhancements/pull/1755
The test listed in the bug, `periodic-ci-openshift-openshift-tests-private-release-4.19-multi-nightly-gcp-ipi-ovn-ipsec-arm-mixarch-f14` should succeed. I don't think there is a way to directly run it from this PR, so @sergiordlr will be doing this test manually via the QE private deck.
=> OCPBUGS-50849: add RHEL variant to IsEL() check

docs/MachineConfig.md, pkg/controller/common/helpers.go, pkg/controller/common/helpers_test.go, test/e2e-single-node/sno_mcd_test.go, test/e2e/mcd_test.go
See: https://issues.redhat.com/browse/OCPEDGE-1493
Add 2no-ha extension support required by Two Node OpenShift
=> OCPEDGE-1493: Add 2no-ha extension support required by Two Node OpenShift

test/e2e-ocl/onclusterlayering_test.go
We will be switching to using the legacy method of installing extensions instead of doing it in the containerfile for OCL. Remove the test as it is failing constantly and blocking PRs
Reference bug https://issues.redhat.com/browse/OCPBUGS-51130
The e2e-ocl tests should pass now
Remove ocl extensions test
=> No-Issue: Remove OCL Extensions test

pkg/controller/build/buildrequest/buildrequest.go, pkg/controller/build/imagebuilder/jobimagebuilder.go, pkg/controller/build/reconciler.go
Closes [OCPBUGS-44602](https://issues.redhat.com/browse/OCPBUGS-44602)
Set an owenrship hierarchy for the OCL build objects created to ensure that everything is linked and cleaned up properly.
Here is how the ownerships are created:
- MOSC owns the MOSB
- MOSB owns the Job
- Job owns the configmaps and secrets
Create a MOSC and delete the build objects to verify that their dependencies are cleaned up. Also, run `oc get object -o yaml` to ensure that the ownerReference is set for them.
Add ownerReferences for OCL build objects
=> OCPBUGS-44602: Set ownerReference for OCL build objects

templates/master/00-master/on-prem/files/haproxy-haproxy.yaml
Previously we avoided doing this because of potential issues in unhealthy clusters where backends were flapping and we didn't want to trigger failovers. However, given the nature of the firewall rule monitor check that approach was not effective anyway and allowing HAProxy to report its own status to the monitor is much more robust than relying on API calls being routed correctly when API rollouts are happening.
This is being implemented as a separate monitor endpoint because we don't want the Kubelet liveness probes to fail just because there are no backends (which is an expected state in early cluster deployment). That would trigger unnecessary crash loops.
=> OPNET-629: Mark haproxy unhealthy if no healthy backends

templates/common/_base/files/configure-ovs-network.yaml
This required  a manual backport because we didn't backport the previous failed fix to this same code past 4.18. No real conflicts though.
Due to some unexpected behavior when applying NMState configuration, the ovs-if-br-ex connection profile is being persisted to /etc/NetworkManager/system-connections when it shouldn't be. By default, configure-ovs only cleans the /run directory, but if we also clean /etc even when it's not supposed to be used then it will unblock a number of users who are currently hitting this bug.
This also swaps the order of the master and slave-type parameter in the nmcli call since we discovered the previous ordering is ineffective. With the removal of the spurious nmconnection file it's likely that this doesn't matter, but it won't hurt to have it there.
(cherry …
=> [release-4.17] OCPBUGS-52257: configure-ovs workaround for ovs-if-br-ex bug

pkg/daemon/daemon.go, pkg/daemon/update.go
If a problem occurs while attempting to reboot a given node while OCL is enabled, the degradation message did not indicate what the problem was. Instead, it would indicate a problem with rpm-ostree because it would attempt to reapply the same image, which it can't do. Additionally, the MCDRebootError metric was not being surfaced in certain cases (although I did not actually observe this to be the case).
To remedy this, I did the following:
- Refactored the onClusterBuildUpdate() function in the MCD to include more state restorations in the event of an error. Additioanlly, this function now uses the applyOSChanges() method which includes benefits such as additional eventing and metrics.
- Refactored the finalizeOCLRevert() function to do more state restorations.
- …
=> OCPBUGS-43896: add revert logic to OCL path in MCD

install/0000_90_machine-config_01_prometheus-rules.yaml
- What I did
Added a runbook I wrote to the MCDRebootError Alert
Trigger MCDRebootError on cluster. Alert should now display associated runbook.
Added https://github.com/openshift/runbooks/blob/master/alerts/machine-config-operator/MachineConfigDaemonRebootError.mdto alert as a runbook_url.
=> MCO-1537: Add MCDRebootError runbook to prometheus rules

pkg/controller/node/status.go
OCPBUGS-44618: In OCL, MCPs are reporting Updating=false while the image is being built
- What I did
added mcp reporting status to follow mosb's
1. Enable techpreview
2. Create a MOSC
3. watch mcp status change
NOTE mcp will not degrade if a build fails.
=> [release 4.18] OCPBUGS-50954: In OCL, MCPs are reporting Updating=false while the image is being built

pkg/controller/certrotation/certrotation_controller.go, pkg/controller/certrotation/helpers.go, pkg/controller/common/constants.go, pkg/controller/machine-set-boot-image/helpers.go, pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go, pkg/controller/machine-set-boot-image/platform_helpers.go, test/e2e/msbic_test.go
- If a `MachineSet` enrolled for boot image updates has a spec 2 Ignition stub, the boot image controller will attempt to upgrade it to the latest Ignition version used by the MCO(which at the moment, is `3.4.0`). 
- If the upgrade fails, the boot image controller will degrade and abort the boot image update. When an upgrade is successful, the timestamp and new version is annotated on the secret object.
- The boot image controller will no longer hardcode an update enrolled `MachineSet` to `*-managed` stub. The e2e tests have been adjusted accordingly.
- As https://issues.redhat.com/browse/OCPBUGS-19824 is now fixed, we can directly use the `releaseVersion` in the `coreos-bootimages` configmap instead of the one written into the configmap by the MCO. 
- Added an e2e to …
=> MCO-1485: MCO:1486: MCO-1324: Attempt stub Ignition upgrade

templates/common/_base/files/configure-ovs-network.yaml
Bonded network configurations with mode=active-backup and fail_over_mac=follow are not functioning due to a race when activating network profiles. activate_nm_connections() attempts to activate all its generated profiles that are not currently in the "active" state. As autoconnect-slaves is set, once br-ex is activated the bond and all its slaves are automatically activated. Their state is set to "activating" until they become active. The "activating" state is not tested for therefor some of the subordinate profiles maybe activated multiple times causing a race in the bonding driver and incorrectly configuring the bond.
Link: https://github.com/openshift/machine-config-operator/issues/4605
Fixes: #4605 
Please see …
=> OCPBUGS-44185: Race in configure-ovs.sh affects bonding interface configuration.

pkg/daemon/daemon.go
This works around the race condition in libostree identified in https://issues.redhat.com/browse/OCPBUGS-51150
Since we're conveniently already running `reboot` via `systemd-run`, we can just inline more requirements to ensure that the transient unit doesn't start until `ostree-finalize-staged.service` has been started.
Fixes: https://issues.redhat.com/browse/OCPBUGS-51150
=> OCPBUGS-51150: daemon: ensure ostree-finalize-staged is started before rebooting

templates/arbiter/01-arbiter-kubelet/_base/files/criometricsproxy.yaml
I think we missed this originally since those PRs were being worked on around the same time.
Fixes e.g. https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.19-e2e-metal-ovn-arbiter/1899662618499485696
Marking no-jira since we don't need to backport anything (and arbiter hasn't yet GA'ed)
cc @eggfoobar
=> OCPBUGS-53085: Add scc label to arbitor crio-metrics-proxy

pkg/daemon/daemon.go, pkg/daemon/update.go, pkg/daemon/writer.go, pkg/server/api.go
Closes: OCPBUGS-52421
This includes:
- Changes part of the automated cherrypick PR #4899 
- Changes made for OCPBUGS-31777 in PR #4369 
Pulling in changes for OCPBUGS-31777 was necessary as it originally addressed many of the log issues highlighted in OCPBUGS-31778, but was not backported beyond 4.17.
N/A
OCPBUGS-31778: Update format verbs for daemon & server alert logs
=> [release-4.16] OCPBUGS-52421: Update format verbs for alert logs

cmd/machine-config-controller/start.go, cmd/machine-config-daemon/start.go, pkg/controller/drain/drain_controller.go, pkg/daemon/daemon.go, pkg/daemon/daemon_test.go, pkg/daemon/drain.go, pkg/daemon/pinned_image_set.go, pkg/daemon/update.go, pkg/daemon/upgrade_monitor_test.go, pkg/helpers/helpers.go, pkg/operator/sync.go, pkg/upgrademonitor/upgrade_monitor.go, test/e2e-techpreview/mcn_test.go
This work adds support for custom MCPs in MCN. The update makes use of the previously existing `GetPrimaryPoolForNode` function to get the pool a node is associated with.
**_Test for standard case_**
1. Create a custom MCP named `infra` and add a worker node to the new MCP.
2. View the `machineconfignode` object for the `infra` node and check that the pool name matches.
```
$ oc describe machineconfignode <node-name>
...
Spec:
...
Pool:
Name:  infra
```
3. Check that the pool names are properly populated for all `machineconfignode`.
```
$ oc get machineconfignode
NAME                                         POOLNAME   DESIREDCONFIG           CURRENTCONFIG          UPDATED
ip-10-0-101-100.us-west-2.compute.internal   infra      rendered-infra-xxxxx …
```
=> MCO-1501: Add support for custom MCPs in MCN

test/framework/clientset.go
This fixes a bug in CreateLongLivedPullSecret() where the base rest.Config was being mutated. Now, any calls to clientset.GetRestConfig() will get a copy of the config that can be mutated without affecting the original config.
Run the test-ocl job. Also, run the onclustertesting devex helper, which is where this was occurring.
Ensure that client configs are not mutable
=> "NO-ISSUE: ensure that client configs are not mutable"

pkg/operator/operator_test.go, pkg/operator/status.go, pkg/operator/status_test.go
Added code to set the cluster operator's status to `Upgradeable=False` when a cluster is found to be on cgroup v1
Update the `CgroupMode` field of ndes.config object to `v1` and verify that the MCO cluster operator's status has the `Upgradeable=False` condition
Cgroupsv1 support deprecation condition/message has been added in the last release and this PR helps in updating all the clusters to cgroup v2 before upgrading to ocp 4.19
References:
- Enhancement Proposal: https://github.com/openshift/enhancements/blob/master/enhancements/machine-config/mco-cgroupsv2-support.md 
- API PR: https://github.com/openshift/api/pull/2181
=> OCPNODE-2842: Set Upgradeable=False when cluster is on cgroup v1

templates/common/_base/files/wait-for-ipsec-connect.yaml, templates/common/_base/units/ipsec.service.yaml, templates/common/_base/units/wait-for-ipsec-connect.yaml
The IPsec upgrade CI job (`e2e-aws-ovn-ipsec-upgrade`) is never passing and failing with api connection disruptive events and some cluster operator are unavailable for more than allowed period. so we are addressing those issues
with this PR by fixing two things.
**Add ipsec connect wait service**
When node goes for a reboot on an IPsec enabled cluster, once it comes up, after ovn-ipsec-host pod is deployed, the ovs-monitor-ipsec process deployed by the pod parses /etc/ipsec.d/openshift.conf file, makes pluto daemon to
establish IKE SAs with peer nodes, but these are established after kubelet is started, workload pods scheduled on this node would fail communicating with other node pods until IPsec SAs are established.
So the commit e96fe31 adds wait-for-ipsec-connect.service systemd …
=> OCPBUGS-52280, SDN-5330: Add ipsec connect wait service

pkg/controller/build/buildrequest/assets/Containerfile.on-cluster-build-template
Installs fuse-overlayfs and configures it in storage.conf for rootless containers.
1. opt into OCL
2. create and apply a MC that has ext enabled
=> OCPBUGS-51130: In OCL. Cannot install extensions

pkg/daemon/update.go, pkg/upgrademonitor/upgrade_monitor.go
Closes : OCPBUGS-52827
Fixed typos for MachineConfigNode.
N/A
OCPBUGS-52827: Fixes typos for MachienConfigNode
=> OCPBUGS-52827: Fixing typos for MachineConfigNode

pkg/operator/operator_test.go, pkg/operator/status.go, pkg/operator/status_test.go
CgroupMode `v1` is not supported in OCP-4.19
This change helps in preventing clusters to upgrade to 4.19 before updating the cluster to cgroupMode `v2`
This is a cherry-pick of https://github.com/openshift/machine-config-operator/pull/4822
=> OCPNODE-2276: Set `Upgradeable=False` when cluster is on cgroup `v1`

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
=> OCPBUGS-51132: [release-4.18] /etc/crio/crio.conf.d/00-default should contain runtime_root for runc

pkg/helpers/helpers.go, pkg/upgrademonitor/upgrade_monitor.go
Update the `NotYetSet` constant used throughout the upgrade monitor to match the validation enforced by the [updated MCN API](https://github.com/openshift/api/pull/2201).
Launch cluster with this and the API PR.
```
launch 4.19,openshift/api#2201,openshift/machine-config-operator#4949 aws,techpreview
```
Upgrade monitor: Update default NotYetSet placeholder constant
=> NO-ISSUE: MCN changes for API validation

pkg/controller/build/buildrequest/buildrequest.go, pkg/controller/build/constants/constants.go, pkg/controller/build/imagebuilder/jobimagebuilder.go, pkg/controller/build/imagebuilder/jobimagebuilder_test.go, test/e2e-ocl/onclusterlayering_test.go
There was a potential discrepancy in the success / fail criteria for *batchv1.Jobs in our E2E tests which could potentially explain why the `TestControllerEventuallyReconciles` test frequently fails. The following serves as a potential remedy:
- Set some of the values such as maxBackoff and completions as constants so that we can adjust them more easily in the future since we'll only have to adjust them in one place.
- Exported the `MapJobToBuildStatus()` function from `imagebuilder` and modified the `TestControllerEventuallyReconciles` to use that plus the various MachineOSBuild statuses in order to determine whether a job is successful or not.
Run e2e-gcp-op-ocl
Use the same success criteria for OCL e2e tests
=> OCPBUGS-54161: use the same success criteria for OCL e2e tests

pkg/controller/build/buildrequest/builder.go, pkg/controller/build/buildrequest/interfaces.go, pkg/controller/build/buildrequest/machineosbuild.go, pkg/controller/build/constants/constants.go, pkg/controller/build/fixtures/objects.go, pkg/controller/build/imagebuilder/base.go, pkg/controller/build/imagebuilder/cleaner.go, pkg/controller/build/imagebuilder/jobimagebuilder.go, pkg/controller/build/imagebuilder/jobimagebuilder_test.go, pkg/controller/build/imagebuilder/preparer_test.go, pkg/controller/build/osbuildcontroller_test.go, pkg/controller/build/reconciler.go, test/e2e-ocl/helpers_test.go, test/e2e-ocl/onclusterlayering_test.go, test/helpers/assertions.go, test/helpers/utils.go
Ensure that the build job under the MOSB is deleted before deleting the MOSB when the rebuild annotation is added to the MOSC. This ensures proper cleanup so that the build can start again.
Closes https://issues.redhat.com/browse/OCPBUGS-48675
Closes https://issues.redhat.com/browse/OCPBUGS-48808
Closes https://issues.redhat.com/browse/OCPBUGS-46421
Ensure job is cleaned up when rebuild is triggered.
Follow the steps in the bug lhttps://issues.redhat.com/browse/OCPBUGS-48675. With this fix, the rebuild should be triggered.
Ensure rebuild is actually triggered when the rebuild annotation is added to the MOSC.
=> OCPBUGS-48675, OCPBUGS-48808, OCPBUGS-46421: Ensure build job is deleted when rebuild is triggered

pkg/daemon/update.go
Closes: OCPBUGS-38869
This adds an MCN spec update during the OCL update flow to ensure the desired config version is properly set when OCL is enabled.
1. Create a cluster and enable OCL.
2. Apply an MC targeting the MCP with OCL enabled.
3. Watch the MCN objects during the MC application.
- The DESIREDCONFIG column in the `oc get machineconfignode` output should update properly.
- The spec.configVersion.desired value in the `oc describe machineconfignode/<node-name>` output should update properly.
OCPBUGS-38869: Update desired config in MCN on OCL update
=> OCPBUGS-38869: Update desired config in MCN on OCL update

pkg/daemon/pinned_image_set.go, pkg/upgrademonitor/upgrade_monitor.go
MCN.Spec.PinnedImageSets should not exist. There is no benefit to it existing as a "psuedo" Status that we don't react to
=> MCO-1627: Get rid of setting mcn.Spec.PinnedImageSets field

pkg/controller/container-runtime-config/container_runtime_config_controller.go
The machine config that is called by Get might be cleaned up when the cluster encountered regression https://issues.redhat.com/browse/OCPBUGS-7719. We should ignore is not found error to avoid controller failure.
1. Reproduce the cluster:  create two ctrcfg, and then delete the first ctrcfg, edit the second ctrcfg finalizers field, adding 99-worker-generated-containerruntime to the list
```yaml
kind: ContainerRuntimeConfig
metadata:
annotations:
machineconfiguration.openshift.io/mc-name-suffix: "1"
creationTimestamp: "2025-03-29T05:22:44Z"
finalizers:
- 99-worker-generated-containerruntime
- 99-worker-generated-containerruntime-1
`oc get mc` displays `99-worker-generated-containerruntime-1`, …
```
=> [release-1.17]OCPBUGS-52188: ignore mc not found error

pkg/controller/kubelet-config/helpers.go, pkg/controller/kubelet-config/kubelet_config_nodes.go, pkg/controller/kubelet-config/kubelet_config_nodes_test.go, test/e2e-bootstrap/bootstrap_test.go
Remove the references of `cgroupv1`
- Do not support setting of `cgroupMode` field to `v1` of the `nodes.config.openshift.io` object
- Remove the `cgroupv1` deprecation message
References:
API PR - https://github.com/openshift/api/pull/2181
Enhancement Proposal - https://github.com/openshift/enhancements/blob/master/enhancements/machine-config/mco-cgroupsv2-support.md
=> OCPNODE-3020: Remove `cgroupv1` references

templates/common/_base/files/wait-for-ipsec-connect.yaml, templates/common/_base/units/ipsec.service.yaml, templates/common/_base/units/wait-for-ipsec-connect.yaml
Manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/4930, No conflicts.
=> [release-4.16] OCPBUGS-52952: Add ipsec connect wait service 

templates/common/_base/files/wait-for-ipsec-connect.yaml
The Libreswan 5.2 uses a slightly updated string for displaying established child SAs for an IPsec connection. So this PR updates ipsec showstates command with right regex value. The modified command is harmless and can also work well with Libreswan 4.x version.
=> CORENET-5524: Modify regex for ipsec showstates command

templates/common/_base/files/wait-for-ipsec-connect.yaml, templates/common/_base/units/ipsec.service.yaml, templates/common/_base/units/wait-for-ipsec-connect.yaml
Manual cherry-pick of 4.16 PR https://github.com/openshift/machine-config-operator/pull/4931. No conflicts.
=> [release-4.15] OCPBUGS-36688: Add ipsec connect wait service

pkg/daemon/pinned_image_set.go
Do not add the same PIS to the MCNStatusPIS for separate different MCPs
1) Create a custom MCP
2) Add a worker node to the custom MCP
3) Create a PIS targeting the Worker MCP
4) Look at the MCD logs and ensure no error like "Failed to update MCN status" pops up
=> OCPBUGS-52656: Update the MCN PIS status of only the primary pool

templates/master/00-master/gcp/units/openshift-gcp-routes.service.yaml
The openshift-gcp-routes service is required eve during GCP installs with in-cluster DNS. During some early work on the in-cluster DNS feature, I had concluded that this service may not be necessary. After testing the in-cluster DNS further it is clear that this service is required even in this case.
Enable `userProvisionedDNS` via install-config for GCP platform
=> OCPBUGS-49737: GCP: Include the gcp-routes.service for all GCP installs

install/0000_90_machine-config_01_prometheus-rules.yaml
- What I did
Added a runbook I wrote to the ExtremelyHighIndividualControlPlaneMemory Alert
Trigger ExtremelyHighIndividualControlPlaneMemory on cluster. Alert should now display associated runbook.
Added https://github.com/openshift/runbooks/blob/master/alerts/machine-config-operator/ExtremelyHighIndividualControlPlaneMemory.md to alert as a runbook_url.
=> MCO-1587: Add runbook for ExtremelyHighIndividualControlPlaneMemory

templates/common/_base/files/etc-docker-certs.d.yaml
OLMv1 uses containers/images/v5 which looks in the /etc/docker/certs.d directory for certificates used in image fetching. It is necessary for local registries as well as additional CAs specified in images.config.
Added /etc/docker/certs.d to template
Ensure /etc/docker/certs.d exists after cluster startup
Add /etc/docker/certs.d to template
=> OCPBUGS-54175: Add /etc/docker/certs.d to template

templates/arbiter/01-arbiter-kubelet/_base/units/kubelet.service.yaml, templates/master/01-master-kubelet/_base/units/kubelet.service.yaml, templates/master/01-master-kubelet/on-prem/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/_base/units/kubelet.service.yaml, templates/worker/01-worker-kubelet/on-prem/units/kubelet.service.yaml
Previously the `restorecon` command was applies on /var/lib/kubelet/ This caused the command to hang forever on a stale NFS volumes.
To minimize the affect of the command this command suggest few things:
1. Narrowing down the path so the command will take affect only for the concrete use case we aware of, where pod-resources changes its label due to: https://github.com/containers/container-selinux/pull/329
2. Add the `-i` flag which ignores the path if it doesn't exist. This is done to make sure we're not failing the service in case of missing path.
Fixes: #[OCPBUGS-50535](https://issues.redhat.com/browse/OCPBUGS-50535)
1. Check the new kubelet.service updated correctly.
2.  Verify the service is not hanging on stale NFS mounts anymore.
**- …
=> OCPBUGS-54384: kubelet-service: narrow down restorecon path

templates/common/_base/units/mtu-migration.service.yaml
When NMState is used to manage br-ex, we need mtu-migration to run after the wait-for-primary-ip service so we know the network is ready to go. If not, the script can have trouble getting the current configuration.
=> OCPBUGS-53425: Make mtu-migration run after wait-for-primary-ip

pkg/controller/common/mos_state.go, pkg/controller/node/node_controller.go, pkg/controller/node/node_controller_test.go, pkg/controller/node/status.go, pkg/daemon/update.go
Occasionally, there is a delay between the time that a new rendered MachineConfig is produced and OCL begins a build. However, a couple of things happen in the interim:
- The RenderController updates the MachineConfigPool. Because of the delay mentioned above, the NodeController begins updating all of the nodes with only the new rendered MachineConfig. The OS image remains the same because the NodeController is not ensuring that the image pullspec on the MachineOSConfig is the same as the MachineOSBuild.
- Because of the work done to the MCD in https://github.com/openshift/machine-config-operator/pull/4825, the original check that we had to determine whether the image pullspecs were the same is no longer present. Additionally, the logic change there makes it possible for …
=> OCPBUGS-53408: wait for build and ensure OS image is actually new

pkg/controller/build/buildrequest/buildrequest.go, pkg/controller/build/osbuildcontroller_test.go, pkg/controller/build/utils/helpers.go, test/e2e-ocl/onclusterlayering_test.go
Closes https://issues.redhat.com/browse/MCO-1509
Grab the /etc/containers/registries.conf and
/etc/containers/policy.json files from the node
and mount it into the builder pod so that buildah
can use it during the build process.
Note: mirrors only work for image pulls and not for image push. So the mirror here will be used when doing the FROM BaseOSImage part in the Containerfile during the build.
Replace the value of `BaseOSImage` with a registry/image that doesn't exist. Set up an IDMS, something like this with the mirror and source configured:
```
apiVersion: config.openshift.io/v1 
kind: ImageDigestMirrorSet 
metadata:
name: builder-test
spec:
imageDigestMirrors: 
- mirrors:
- quay.io/umohnani8/mirror-base
source: quay.io/umohnani8/og-base …
```
=> MCO-1509: Enable OCL for disconnected workflow

pkg/apihelpers/apihelpers.go, pkg/controller/common/constants.go, pkg/controller/common/featuregates.go, pkg/controller/machine-set-boot-image/helpers.go, pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go, pkg/operator/sync.go, pkg/operator/sync_test.go, test/e2e/msbic_test.go
- The operator will begin to opt-in clusters for boot image updates by default on AWS and GCP, **except** for cases where the cluster already has an existing boot image update configuration.
- The operator will populate a new API field called `ManagedBootImagesStatus` in the `MachineConfiguration` object's status. This will reflect the `spec.managedBootImages` of the object. When the `spec.managedBootImages` is empty, it will reflect the cluster defaults. On platforms that have no boot image updates support, the `managedBootImagesStatus` field will be empty. Currently, only AWS and GCP will be opt-ed in by default. 
Following are some examples:
Scenario: No admin configuration and the current release **does not** opt-in by default:
```
apiVersion: operator.openshift.io/v1 …
```
=> MCO-1584: Opt-in boot image updates for AWS & GCP by default

manifests/cloud-platform-alt-dns/coredns.yaml, pkg/controller/template/render.go, pkg/controller/template/render_test.go, pkg/controller/template/test_data/controller_config_gcp_custom_dns.yaml, pkg/controller/template/test_data/controller_config_gcp_default_dns.yaml, templates/common/cloud-platform-alt-dns/files/coredns-corefile.yaml, templates/common/cloud-platform-alt-dns/files/coredns.yaml
Fixes: OCPBUGS-48469
1. Updated CoreDNS Corefile errors for cloud platforms needing alternate in-cluster DNS when UserProvisionedDNS is enabled via the install-config
2. Updated the list of directories to include the location of the CoreDNS files for cloud platforms
3. Updated test data and unit tests for UserProvisionedDNS enabled on GCP.
Set `UserProvisionedDNS` to `Enabled` for GCP via install-config and start installation
Fixed issues with CoreDNS Corefile and template path for cloud platforms when UserProvisionedDNS is enabled.
Added test_data for GCP with all the UserProvisionedDNS configuration to better test this path.
=> OCPBUGS-48469: Fix CoreDNS static pod bring-up on cloud platforms

pkg/controller/build/buildrequest/assets/Containerfile.on-cluster-build-template
=> [release-4.18] OCPBUGS-53278: In OCL. Cannot install extensions

templates/common/_base/files/configure-ovs-network.yaml
Currently the only supported combination is either DHCP or static IP on the default gateway interface. This leads to the scenario when IP address from DHCP and static DNS address is not working (the custom DNS is just ignored).
With this change we allow to have DNS configured manually no matter where the IP address of the interface comes from.
In principle this should be done using k-nmstate operator and its global DNS configuration, but it seems there are scenarios where we want this functionality already at installation time.
Closes: OCPBUGS-44732
=> OCPBUGS-44732: Support for br-ex with DHCP and static DNS

templates/master/00-master/on-prem/files/haproxy.yaml
Previously we just crashlooped when the HAProxy init container failed, which is a normal, expected condition when HAProxy starts before CoreDNS. This is causing issues in CI because having a pod crash more than 3 times in a row is considered a failure. While it usually doesn't take that long for it to pass, we are hitting a weird timing issue during upgrades when the node is just about to reboot after MCO updates the pod definitions and it's taking longer than normal because ostree is updating the node at the same time.
Since this is just a case of everything behaving as expected, let's stop failing the pod for an expected situation. This change puts the api-int call in a loop so it will just run until coredns is ready and we'll never trigger any error reporting just because of harmless …
=> OCPBUGS-51273: Don't crashloop for HAProxy init container

install/0000_90_machine-config_01_prometheus-rules.yaml
- What I did
Added a runbook I wrote to the HighOverallControlPlaneMemory Alert
Trigger HighOverallControlPlaneMemory on cluster. Alert should now display associated runbook.
Added https://github.com/openshift/runbooks/blob/master/alerts/machine-config-operator/HighOverallControlPlaneMemory.md to alert as a runbook_url.
=> MCO-1635: Add new runbook for HighOverallControlPlaneMemory to alert 

templates/common/aws/units/aws-update-dns.service.yaml, templates/common/cloud-platform-alt-dns/files/usr-local-bin-update-dns-server.yaml
New `update-dns-server` script that adds DNS resolvers to /etc/NetworkManager/conf.d/dns-servers.conf. The script adds the host's own IP address and the cloud metadata server's IP address to the conf file. These would then get added to the local resolv.conf by NetworkManager.
This script is run as part of aws-update-dns.service This service runs when the DNSType on the AWS platform is set to "ClusterHosted".
=> OCPBUGS-52940: AWS Custom-DNS: Update services that run on control plane nodes

templates/common/_base/files/wait-for-ipsec-connect.yaml
We noticed a cross streaming issue with Libreswan 5.2 creating duplicate child SAs on the node and no matching SA on the other end causing packet drops. To fix it, this commit makes `wait-for-ipsec-connect.service` updates `openshift.conf` with `auto=start` only for out connections.
=> OCPBUGS-55262: Use auto=start only for IPsec out connections

pkg/upgrademonitor/upgrade_monitor.go
Closes: OCPBUGS-55450
This adds a check to only set `Status.PinnedImageSets.CurrentGeneration` in a MachineConfigNode object when the generation value is valid, or non-zero.
1. Launch a cluster with this PR.
2. Apply an invalid PIS.
<details><summary>Example Invalid PIS targeting "custom" MCP</summary>
<pre>
kind: PinnedImageSet
metadata:
name: test-pinned
labels:
machineconfiguration.openshift.io/role: "custom"
spec:
pinnedImages:
- name: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:86d26e7ebcccd6f07a75db5b1e56283b25c2ee1c6a755d6ffc5a4d59beb9cdef
</pre>
</details>
3. Check that the PIS reference in the MCN has values for `Name`, `DesiredGeneration`, `LastFailedGeneration`, and …
=> OCPBUGS-55450: Only populate `Status.PinnedImageSets.CurrentGeneration` on valid generation value

OWNERS
Closes: OCPBUGS-55597
This adds @pablintino to the OWNERS file and updates it generally to be up to date with current MCO team.
N/A
OWNERS: update owners file with current MCO team members
=> OCPBUGS-55597: OWNERS: update owners file with current MCO team members

templates/master/01-master-container-runtime/_base/files/crio.yaml, templates/worker/01-worker-container-runtime/_base/files/crio.yaml
Fixes https://issues.redhat.com/browse/OCPNODE-3173
Disable OCI artifacts mount by specifying the newly added option `oci_artifact_mount_support`.
https://github.com/cri-o/cri-o/blob/main/docs/crio.conf.5.md#crioimage-table
Added `oci_artifact_mount_support = false` in the default crio config.
=> OCPNODE-3173: Disable OCI artifact mount by default.

pkg/controller/render/render_controller.go
Fixes:  #OCPBUGS-54697
Fix misleading error in generateAndValidateRenderedMachineConfig
When a full-render reconciliation fails, we now iterate through the
base MachineConfigs one by one—to
pinpoint the exact config that introduced the irreconcilable change.
If a partial render fails, we report that config’s name and its error,
instead of incorrectly blaming an earlier override. We still fall back
to the original combined error behavior if no single config produces
the full-render failure.
See https://issues.redhat.com/browse/OCPBUGS-54692
=> OCPBUGS-54697: error from generateAndValidateRenderedMachineConfig function can be misleading

install/0000_90_machine-config_01_prometheus-rules.yaml
- What I did
Added a runbook I wrote to the KubeletHealthState Alert
Trigger KubeletHealthState on cluster. Alert should now display associated runbook.
Added https://github.com/openshift/runbooks/blob/master/alerts/machine-config-operator/KubeletHealthState.md to alert as a runbook_url.
=> MCO-1654: Add new runbook for KubeletHealthState to alert

pkg/controller/render/render_controller.go, pkg/daemon/daemon.go
Closes https://issues.redhat.com/browse/OCPBUGS-55770
There is no need to check the ostree.commit label
to validate the os image on disk. Use the osImageURL value instead as the digest is what is used to verify.
Start a cluster and delete a MCD pod, the logs should show that no remote inspect is happening anymore in the `checkOS()` call. 
Use osImageURL to validate the on disk OS image.
=> OCPBUGS-55770: Compare the osImageURLs for OS validation check

cmd/machine-config-daemon/start.go, pkg/controller/common/controller_context.go, pkg/daemon/writer.go
Each node in the cluster was also listing all of the other nodes within the cluster and we were filtering out irrelevant nodes manually. Instead, a much better approach is to have the informer filter the node at the API server level to reduce load on the API server. This is mostly a problem for clusters with 1200+ nodes.
The MCD should continue to work as-is.
MCD node listers should only be scoped to the node they're running on
=> OCPBUGS-55439: scope MCD node listers to current node

pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go, pkg/controller/machine-set-boot-image/machine_set_boot_image_controller_test.go
I added a simple hot loop detection counter in the boot image controller. If a machineset is updated more than 3 times to the same target boot image, the MSBIC will error and degrade the cluster. To fix this, one could:
1. Opt the cluster out of boot image updates. You can stop here if you do not want/care about boot image updates.
2. Fix the other actor in your cluster that is also reconciling the boot image. This will vary depending on the platform.
3. Opt the cluster back in for boot image updates.
1. Bring up a cluster on GCP/AWS. 
2. Update the boot image to a different value. On GCP, this would be the `disk.image` field in the providerSpec and on AWS, this would the `AMI.ID` field in the providerSpec. The MSBIC should immediately update the …
=> OCPBUGS-55967: Add hot loop detection in the boot image controller

pkg/controller/render/render_controller.go
What I did
Fixes: #OCPBUGS-56119
Fix misleading error in generateAndValidateRenderedMachineConfig
When a full-render reconciliation fails, we now iterate through the
base MachineConfigs one by one—to
pinpoint the exact config that introduced the irreconcilable change.
If a partial render fails, we report that config’s name and its error,
instead of incorrectly blaming an earlier override. We still fall back
to the original combined error behavior if no single config produces
the full-render failure.
How to verify it
See https://issues.redhat.com/browse/OCPBUGS-54692
=> [release-4.19] OCPBUGS-56119: error from generateAndValidateRenderedMachineConfig function can be misleading

pkg/controller/build/imagebuilder/jobimagebuilder.go
Closes https://issues.redhat.com/browse/OCPBUGS-53390
If the job hasn't completely failed but some of the pods have failed and we deleted the job we weren't setting the MOSB to interrupted as expected. This was because we had a wrong check for failure state. This patch fixes that.
Create a failing MOSC and then delete the job after on pod has failed, the MOSB should be in interrupted state.
Fix validation for MOSB interrupted state.
=> OCPBUGS-53390: Fix interrupt state to account for failure correctly

pkg/controller/machine-set-boot-image/machine_set_boot_image_controller.go
I removed the wait loop for the golden configmap stamp in the MSBIC. Instead, the controller will exit the sync and attempt to resync again when the confgimap is updated. This means that the MSBIC will no longer degrade if the master pool takes a while to update, which can be due to myriad of issues, and typically not boot image related.
Existing e2es should pass. This should not cause any substantial changes in the MSBIC's actual update behavior. The MSBIC should no longer degrade if the golden configmap never gets stamped, but I'm fairly confident we weren't directly testing for this failure mode.
=> OCPBUGS-56211: Boot Image Controller should not degrade when golden configmap is slow to update

pkg/operator/sync.go
Use "openshift.io/owning-component" annotation to set configmap ownership.
=> NO-JIRA: operator: use component annotation for ownership

pkg/controller/render/render_controller.go, pkg/daemon/daemon.go
Cherry pick of https://github.com/openshift/machine-config-operator/pull/5041
Closes https://issues.redhat.com/browse/OCPBUGS-56217
=> [release-4.18] OCPBUGS-56217: Compare the osImageURLs for OS validation check

cmd/machine-config-operator/start.go, pkg/apihelpers/apihelpers.go, pkg/operator/admin_ack.go, pkg/operator/admin_ack_test.go, pkg/operator/operator.go, pkg/operator/operator_test.go, pkg/operator/status_test.go, pkg/operator/sync.go
I added a new sync loop in the operator for the `admin-gates` configmap in the `openshift-config-managed` namespace. This sync loop will now begin to add the following keys:
- `ack-4.18-boot-image-opt-out-in-4.19` when a AWS/GCP cluster does not have a boot image configuration.
- `ack-4.18-aarch64-bootloader-4.19` when an aarch64/arm64 node is detected in the cluster.
These gates are only relevant for upgrades to 4.19, so they will only need to exist in the MCO's `release-4.18` branch. I've also added a few units for this functionality. 
Before testing either case, ensure that any non MCO keys in `admin-gates` have been acknowledged. For example, if there is a key called `ack-4.18-kube-1.32-api-removals-in-4.19` in `admin-gates`, add this key to the …
=> OCPBUGS-55638: OCPBUGS-55637: Add admin_acks handling in the MCO

templates/common/on-prem/files/keepalived.yaml
When we switched our containers to use capabilities intead of giving them full admin access to everything, we missed that the keepalived container needs to be able to chroot for one of its health checks. Because this check is always failing now, we may place the VIP incorrectly and break access to ingress services on the cluster. This just adds the necessary capability to the container.
There will be a followup change in the origin repo to add a test that would have caught this, since it's not a problem in a normal CI run.
=> OCPBUGS-55681: Give keepalived container chroot cap

templates/common/on-prem/units/nodeip-configuration.service.yaml
Originally this was only enabled for UPI deployments because in IPI we expected the node IP to match the VIP subnet. However, since then two scenarios have come up where that may not be true:
- VSphere clusters are often deployed with VIPs that are not on the Machine Network
- User-namaged loadbalancers may be on any subnet In either of these cases we currently fall back to the remote worker behavior of selecting based on the default route. This is a problem if there are two interfaces, both with default routes. The order of activation can cause nondeterministic behavior.
This deliberately does not support the old KUBELET_NODEIP_HINT name that the UPI service does because it was never a thing in IPI and we don't need the backward compatibility with it.
**- How to verify …
=> OCPBUGS-36859: Support NODEIP_HINT in IPI deployments too

templates/common/_base/files/kubelet-auto-sizing.yaml
When using the `dynamic-system-reserved-calc.sh` command with only `true` parameter, the call to function `dynamic_node_sizing` only has 1 parameter, and then the call to function `dynamic_cpu_sizing $2` has no parameter and fail.
Fixes: OCPBUGS-45621
Changed the order of the parameters passed to function `dynamic_node_sizing`, as `$4` is optional
Run the command this way (to not override the default env file) and check the output file:
~~~
~~~
Fix the `dynamic-system-reserved-calc.sh` script when only `true` parameter is used.
=> OCPBUGS-45621: Fix `dynamic-system-reserved-calc.sh` when only `true` parameter is used

pkg/controller/machine-set-boot-image/platform_helpers.go, test/e2e/msbic_test.go
Add an additional check for `boot:true`, before updating the providerSpec. 
See bug for reproduction steps.
=> OCPBUGS-55830: Only update boot disks during GCP boot image updates

pkg/daemon/pinned_image_set.go
Edited the error message for an invalid PIS to not have a typo. Fixes #[OCPBUGS-56744]
When an invalid PIS is applied, the 'MachineConfigNodePinnedImageSetsDegraded' message has a '.' at the end of the message. The message for `MachineConfigNodePinnedImageSetsDegraded` should not have a typo, so it should be:
"One or more PinnedImageSet is experiencing an error. See PinnedImageSet list for more details."
A period added to the end of the error message
=> [release-4.20] OCPBUGS-56744: Fix typo in MCN's `MachineConfigNodePinnedImageSetsDegraded` message

templates/common/_base/files/usr-local-bin-mco-hostname.yaml
Some cloud platforms may assign a hostname with a trailing dot. However, tools like `hostnamectl` (used by systemd) do not allow trailing dots, so we strip the trailing dot before applying the hostname.
=> OCPBUGS-45459: Remove trailing period from hostnames

.gitignore
This simple PR adds Jetbrains IDEs workspace directory to our .gitignore to avoid considering those files from Git's perspective.
=> NO-ISSUE: Add Jetbrains IDEs files to .gitignore

pkg/daemon/constants/constants.go, pkg/daemon/update.go, pkg/daemon/update_test.go
Closes [OCPBUGS-56555](https://issues.redhat.com/browse/OCPBUGS-56555).
This updates extension handling to use actual installed packages from rpm-ostree status instead of comparing extension lists between configs. It also removes FCOS conditionals as they are no longer required. I've also added a few units.
- Existing e2es/units should pass. 
- Adding new packages to an existing extension should be correctly handled during upgrades. (https://github.com/openshift/machine-config-operator/pull/4878)
=> OCPBUGS-56555: openvswitch3.5-ipsec package not included with ipsec os extension

lib/resourcemerge/core.go, pkg/operator/sync.go
Closes https://issues.redhat.com/browse/OCPBUGS-56220
Fix the reconcilation of the build controller to
ensure that new changes are actually applied when
there is an update to the deployment.
Upgrade from 4.18 to 4.19, ensure that the upgrade is successful and the machine-os-builder pod is started with the new image.
Ensure the build controller restarts when updates are detected.
=> OCPBUGS-56220: Ensure the build controller restarts on upgrade

templates/common/_base/files/configure-ovs-network.yaml
nmcli --get-values will escape `:` and `\` by default. This is because `:` is the normal key:value separator. This escape breaks IPv6 output and MAC address output.
`src/nmcli/utils.c`
```c
if (nmc_config->print_output == NMC_PRINT_TERSE) {
if (nmc_config->escape_values) {
const char *p = text;
while (*p) {
if (*p == ':' || *p == '\\')
g_string_append_c(str, '\\'); /* Escaping by '\' */
g_string_append_c(str, *p);
p++;
}
} else
```
=> OCPBUGS-57072: configure-ovs: don't escape `:` in nmcli output

install/0000_90_machine-config_01_prometheus-rules.yaml, pkg/daemon/constants/constants.go, pkg/daemon/daemon.go, pkg/daemon/drain.go, pkg/daemon/drain_test.go, pkg/daemon/update.go, pkg/operator/metrics.go, pkg/operator/status.go
Removed all code and related alerts for the Image Registry Workaround ([PR#4514](https://github.com/openshift/machine-config-operator/pull/4514) and [PR#4139](https://github.com/openshift/machine-config-operator/pull/4139)) due to NodeDisruptionPolicy going GA.
// Apply imagecontentsourcepolicy
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
name: quay-mirror
spec:
repositoryDigestMirrors:
- mirrors:
- my-quay.io.mirror
source: quay.io
cruhm@cruhm-thinkpadp16vgen1:~$ vim imagecontent.yaml
cruhm@cruhm-thinkpadp16vgen1:~$ oc create -f imagecontent.yaml 
imagecontentsourcepolicy.operator.openshift.io/quay-mirror created
```
// Apply override config map
```
apiVersion: v1
kind: ConfigMap
metadata:
name: …
```
=> MCO-1282: Remove all code related to the Image Registry workaround Config Map

pkg/controller/node/node_controller.go
Some master nodes from very old clusters do not have the node-role.kubernetes.io/control-plane label. This PR changes the logic of `makeMasterNodeSchedulable`. The MCO in this code path is already changing the labels and taints, and bringing the node back online as scheduable. It seems like a great spot to add the control-plane label if it was not set.
=> OCPBUGS-58180: Add control-plane label for master nodes on legacy clusters

test/e2e/mcn_test.go
Moved MCN e2e tests from non-blocking `e2e-techpreview` suite to blocking `e2e` suite.
Run e2e tests with `/test e2e-gcp-op`.
[MCO-1624](https://issues.redhat.com//browse/MCO-1624): Move MCN e2e tests into `e2e` suite.
=> MCO-1624: Make MCN e2e tests blocking

.ci-operator.yaml, Dockerfile, Dockerfile.rhel7
The bot-created PR doesn't update the Dockerfile (used for presubmits), so let's update both.
The rhel-9-enterprise-base-multi image doesn't seem to have a 4.20 variant yet so updating it to 4.19.
Supercedes https://github.com/openshift/machine-config-operator/pull/5128
=> OCPBUGS-57702: Update images to be consistent with ART

test/extended/util/logext/log.go
The OTE framework resets the Ginkgo writer on each test run but our Zerolog logger was taking the default initialized Ginkgo writer for the entire run.
This chnage does two things:
- Make the logger a singleton that uses late initialization
- Wrape the Ginkgo writer with a simple writer that always calls the Ginkgo global writer instead of storing a reference to it.
This change disables coloring/formatting of the zerolog output too.
1. Spin up a cluster
2. Run the new added command machine-config-tests-ext run-suite openshift/machine-config-operator/disruptive
3. Ensure that in the resulting json output **each test result** has at least on `OK!` in the output section.
4. Ensure that the logs we output with zerolog (like "OK!") are not formatted.
**- …
=> MCO-1741: Fix missing OTE logs

test/extended/mco_ocb.go
In polarion we have ImageMode test cases duplicated, one test case using the old API testing versions smaller than 4.18, and one test case using the new API testing versions 4.18+
The current ImageMode extended test cases are using the polarion ID of the test cases used to test OCP < 4.18, in this PR we update the polarion ID to match the test cases testing OCP >= 4.18 
This PR mirrors the changes done in the test repo: https://github.com/openshift/openshift-tests-private/pull/25953/files
Only cosmetic changes
=> NO-ISSUE: Update ImageMode tests Polarion ID

templates/common/_base/files/kubelet-auto-sizing.yaml
Fixes https://issues.redhat.com/browse/OCPBUGS-58270 
This sets the default system-reserved-cpu value of 500 millicore based on our recommendation[1]
This change has been introduced in 4.20 through 4.17 [2]
[1] - https://docs.redhat.com/en/documentation/openshift_container_platform/4.10/html/scalability_and_performance/recommended-host-practices#infrastructure-node-sizing_recommended-host-practices 
[2] - https://github.com/openshift/machine-config-operator/pull/5046
=> OCPBUGS-58270: Do not set cpu system reserve below the default value

cmd/machine-config-tests-ext/main.go
With this change, origin won't filter out origin defined tests when running the test suite.
If a suite is not declared as global the qualifier specified in the suite definition is always appended by an and condition that enforces the test to live in the repo where the suite is declared.
Closes: [OCPBUGS-59367](https://issues.redhat.com/browse/OCPBUGS-59367)
Add the `openshift/machine-config-operator/disruptive` as global and not as a regular test-suite.
1. Compile the binaries after checking out this PR
2. Run `./machine-config-tests-ext info`
3. The qualifier of the test-suite should be `name.contains(\"[Suite:openshift/machine-config-operator/disruptive\")` and not `(source == \"openshift:payload:machine-config-operator\") \u0026\u0026 …
=> OCPBUGS-59367: Set our test suite as global

test/e2e/mcn_test.go
Added a cleanup call after the custom MCP MCN test. This may be causing conflicts with later tests as the node remains associated with the custom pool, and the same custom pool is used by other tests. 
Existing tests/e2es should pass. This should not need QE as it is only a test fix.
=> OCPBUGS-59672: TestMCNPoolNameCustom should clean up resources properly

pkg/controller/drain/drain_controller.go, pkg/controller/node/node_controller.go, pkg/controller/node/node_controller_test.go, pkg/daemon/daemon.go, pkg/daemon/drain.go, pkg/daemon/pinned_image_set.go, pkg/daemon/update.go, pkg/daemon/upgrade_monitor_test.go, pkg/helpers/helpers.go, pkg/operator/sync.go, pkg/upgrademonitor/upgrade_monitor.go
Closes: OCPBUGS-52302
This moves the MCN spec update function, `GenerateAndApplyMachineConfigNodeSpec` into the node controller's update function so that the desired config version in the MCN is updated when the node annotation is updated.
1. Launch a 4.20 cluster with this PR build included.
```
launch 4.20,openshift/machine-config-operator#5121 aws
```
2. Apply a MachineConfig to trigger a node update.
3. Track how the desired configs are updated in the MCN's spec and status. The desired config value in the spec should update before the `UpdatePrepared` condition is `True` and before the desired config version is updated in the status.
_Example grep to see the necessary fields:_
```
oc describe machineconfignode/<node-name> | grep -E "Config …
```
=> OCPBUGS-52302: Fix timing of `Spec.ConfigVersion.Desired` update in MCN

Makefile, test/e2e-1of2/main_test.go, test/e2e-1of2/mcd_test.go, test/e2e-2of2/ctrcfg_test.go, test/e2e-2of2/kubeletcfg_test.go, test/e2e-2of2/main_test.go, test/e2e-2of2/mcc_test.go, test/e2e-2of2/mcn_test.go, test/e2e-2of2/mco_test.go, test/e2e-2of2/msbic_test.go, test/e2e-2of2/node_os_test.go, test/e2e-2of2/nodedisrupt_test.go, test/e2e-2of2/osimageurl_override_test.go, test/e2e-2of2/osimageurl_test.go, test/e2e-2of2/sanity_test.go
**What I did:**
This PR adds two new e2e packages/targets: `test-e2e-1of2` and `test-e2e-2of2` consisting of tests from the main e2e target: `test-e2e`. The tests have been equally divided among the two new targets so they would both run for about the same amount of time. 
Once these tests have been rehearsed correctly and merged into o/release, we can then make a follow-up PR to remove the original make target. 
**How to verify:**
Existing e2es should pass. This should not need QE testing since it is only affecting test changes.
=> NO-ISSUE: Split gcp-op into two tests

pkg/daemon/update.go
The rpm-ostree rebase call makes a remote fetch for the image, which can race with the static coredns pod and attempt the fetch while the static pod is updating.
Add a small 5x retry so we can workaround this issue. Long term we'd like to do some mix of retrying in rpm-ostree + image mode making updates more transactional.
=> OCPBUGS-43406: Add workaround fix for static pod race

templates/common/_base/files/nmstate-configuration.yaml
This PR adds logic to handle two migration paths to NMState: one from an existing OVNK cluster using configure-ovs, and one from OpenShift SDN directly to NMState without ever using configure-ovs.
In the former case, we need to clean up the left over remnants of configure-ovs's br-ex configuration. In the latter we need to clean up br0, which would otherwise have been done by configure-ovs.
=> OPNET-681,OCPBUGS-57484: Support migration to NMState

pkg/controller/common/helpers.go, pkg/daemon/on_disk_validation.go, pkg/daemon/update.go
helpers: Compute systemdUnits that added and changed between Ign configs
update: Only write added or updated systemd units
Verify that **while** updating a node from 1 MC to another MC, the unchanged systemd units are not unnecessarily disabled 
=> OCPBUGS-58023: Prevent unnecessary systemd unit disable

pkg/controller/common/helpers.go, pkg/daemon/on_disk_validation.go, pkg/daemon/update.go
Reverts #5148 ; tracked by [TRT-2232](https://issues.redhat.com//browse/TRT-2232)
machine-config operator causing azure, metal and other platforms to fail to install
```
Verify azure and metal-ovn-ipv6 jobs succeed
```
CC: @RishabhSaini
<div align="right">
PR created by <a …
=> TRT-2232: Revert #5148 "OCPBUGS-58023: Prevent unnecessary systemd unit disable"

pkg/controller/machine-set-boot-image/machine_set_boot_image_controller_test.go, pkg/controller/machine-set-boot-image/ms_helpers.go
This updates the annotation check in the boot image controller to work with multiple labels. I also added a new unit test to verify this check.
See bug for reproduction steps. Existing e2es & units should pass.
=> OCPBUGS-60119: Invalid architecture value found in annotation during 4.19 update

pkg/controller/build/buildrequest/assets/Containerfile.on-cluster-build-template, pkg/controller/build/buildrequest/buildrequest.go, pkg/controller/build/buildrequest/buildrequestopts.go, pkg/controller/common/helpers.go, pkg/daemon/update.go, pkg/helpers/helpers.go, test/e2e-ocl/helpers_test.go, test/e2e-ocl/onclusterlayering_test.go
Containerfile: Remove default kernel packages and add new
buildrequest: Set the template variables for kernel packages
buildrequestopts: validate a kernel switch and get packages
helpers: retrieve packages for each supported kernel type
1) Have a MC that switches kernel type to hugepages / realtimeKernel
```
spec:
kernelType: realtime
```
2) Create an MOSC from this MC
3) Verify that the built image has the appropriate packages / kernel installed
```
[root@ip-10-0-124-186 ~]# uname -r
5.14.0-570.28.1.el9_6.x86_64+rt
```
=> MCO-1810: Support kernelType in OCL

test/extended/machineosconfig.go, test/extended/mco_ocb.go
Closes: OCPBUGS-60559
Update the MOSC-related functions in the `test/extended/` directory to take in one parameter representing both the MOSC and MCP names to align with the API validation introduced in https://github.com/openshift/api/pull/2399 requiring the names to be identical.
The on-cluster image mode tests in the MCO disruptive test suite should not fail with the following error.
```
MachineOSConfig name must match the referenced MachineConfigPool name; can only have one MachineOSConfig per MachineConfigPool
```
OCPBUGS-60559: Update the OnClusterBuild tests to reflect validation rule requiring the MOSC and MCP names to match
=> OCPBUGS-60559: Update the OnClusterBuild payload tests to reflect the validation rule requiring MCP & MOSC names to match

go.mod, go.sum, manifests/machineconfigcontroller/machineconfiguration-guards-validatingadmissionpolicy.yaml, manifests/machineconfigcontroller/machineconfiguration-guards-validatingadmissionpolicybinding.yaml, manifests/machineconfigcontroller/update-bootimages-validatingadmissionpolicy.yaml, manifests/machineconfigcontroller/update-bootimages-validatingadmissionpolicybinding.yaml, manifests/machineconfigdaemon/mcn-guards-validatingadmissionpolicy.yaml, manifests/machineconfigdaemon/mcn-guards-validatingadmissionpolicybinding.yaml, pkg/operator/sync.go, vendor/github.com/openshift/library-go/pkg/controller/factory/controller_context.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go, vendor/github.com/openshift/library-go/pkg/operator/configobserver/featuregates/featuregate.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/admission.go, vendor/modules.txt
Backports b53b9df3b05a4d3fc0cc6a43bd0b7cccd1d757b6 to 4.17 to avoid the upgrade to 4.18 from complaining about v1beta1 usage which happens prior to the upgrade. I believe this should be safe because we enabled the featuregate in 4.17 and Kube API Server Operator upgrades prior to Machine Config Operator.
I believe this will however prevent us from cleanly downgrading back to 4.16, which is unsupported.
=> OCPBUGS-60704: operator: switch out VAP v1beta1 to v1

test/extended/machineosconfig.go, test/extended/mco_ocb.go
Closes: OCPBUGS-60767
This is a manual cherrypick of #5249 since the [automated cherrypick failed](https://github.com/openshift/machine-config-operator/pull/5249#issuecomment-3208183995). This backport is required since we are backporting the API validation rule requiring MCP & MOSC names to match (see https://github.com/openshift/api/pull/2449).
The OnClusterBuild tests in the MCO disruptive test suite triggered against the API backport PR introducing the new validation rule should not fail with the following error, `MachineOSConfig name must match the referenced MachineConfigPool name; can only have one MachineOSConfig per MachineConfigPool`.
See payload test: https://pr-payload-tests.ci.openshift.org/runs/ci/9788cd30-7e94-11f0-8c45-45136dc11bb6-0 …
=> [release-4.19] OCPBUGS-60767: Update the OnClusterBuild payload tests to reflect the validation rule requiring MCP & MOSC names to match

pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_controller_test.go, pkg/controller/kubelet-config/kubelet_config_features_test.go
crc & kcc: Before deleting a degraded MC, ensure that the annotations have not been updated since the last check
Check OCPBUGS-56558
=> OCPBUGS-56558: Recheck `generatedByControllerVersion` annotation prior to deleting a degraded MC

pkg/controller/drain/drain_controller.go, pkg/controller/drain/drain_controller_test.go
The MCC will now check if a node undergoing drain has been uncordoned, and re-cordon it. I also added a few unit tests to verify this behavior. 
1. Deploy a cluster with this PR.
2. Deploy an MC update to a pool and wait for nodes to start draining. Take note of the node name and manually uncordon it:
```
$ oc adm uncordon ip-10-0-91-77.ec2.internal
node/ip-10-0-91-77.ec2.internal uncordoned
```
3. Observe the MCC logs. It should be re-cordoned by the MCC and there should also be a note of this in the logs. 
```
I0905 14:31:35.703403       1 drain_controller.go:397] Previous node drain found. Drain has been going on for 0.04207911874472222 hours
I0905 14:31:35.703486       1 drain_controller.go:416] External actor has unexpectedly uncordoned node …
```
=> OCPBUGS-60537: Machine-config controller should actively manage cordon while draining

templates/common/_base/units/nmstate.service.yaml
A bug was introduced in the NMState service definition that breaks many of our uses of it on the host. This overrides the service so the NetworkManager-wait-online service is a softer dependency because in some environments that service will fail and we don't want it to prevent NMState from running.
This is done as a complete override of the service because it is not possible to replace dependencies using a partial drop-in. Also, it is only a temporary fix until the NMState fix lands in our images.
=> OCPBUGS-61695: Override NMState service definition

pkg/controller/build/osbuildcontroller_test.go
This test has been flakey in the past, and we opened https://issues.redhat.com/browse/OCPBUGS-48526 to track it, but its [failure count](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-machine-config-operator-main-unit) has gotten frequent enough to warrant further investigation. Unsure if some recent changes have made its failure more prevalent.
I've added my conclusions from testing in the jira ticket, please check [this comment](https://issues.redhat.com/browse/OCPBUGS-48526?focusedId=28057945&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-28057945) for more context.
=> NO-ISSUE: Add delays to reduce TestOSBuildController failures

test/extended/boot_image.go, test/extended/boot_image_update_agnostic.go, test/extended/boot_image_update_azure.go, test/extended/const.go, test/extended/node.go, test/extended/resource.go, test/extended/testdata/files/machineconfigurations/managedbootimages-all.yaml, test/extended/testdata/files/machineconfigurations/managedbootimages-empty.yaml, test/extended/testdata/files/machineconfigurations/managedbootimages-none.yaml, test/extended/testdata/files/machineconfigurations/managedbootimages-partial.yaml, test/extended/util/template.go
This PR adds 5 CR tests for Azure boot image updates to the MCO's extended test suite. These include the Azure variant of the tests we've used for [other platforms in origin](https://github.com/openshift/origin/blob/main/test/extended/machine_config/boot_image_update_aws.go#L38-L55), and an additional test to ensure that migration from a legacy image to a marketplace image works as expected.
I broke this down into two commits for easier review; the first commit includes all the helpers(some imported from o/origin) that are needed for the new tests and the second commit includes the actual tests.
=> MCO-1673: Add Component Readiness tests for Azure boot image updates

devex/cmd/mco-sanitize/config.go, devex/cmd/mco-sanitize/main.go, devex/cmd/mco-sanitize/processor.go, devex/cmd/mco-sanitize/processor_test.go, devex/cmd/mco-sanitize/redactor.go, devex/cmd/mco-sanitize/redactor_test.go, devex/cmd/mco-sanitize/types.go, devex/cmd/mco-sanitize/walker.go, devex/cmd/mco-sanitize/walker_test.go, go.mod
This change adds a sub-piece of the mco-sanitizer, the utility binary that takes a must-gather directory and removes/sanitizes the content based on some given configuration.
This change is limited to the file walker and processor components of  the tool.
UT testing is enough to test this sub-component of mco-sanitize.
Implements a sub-component of the mco-sanitizer that is responsible of walk and process a FS directory.
=> MCO-1685: Add mco-sanitize file processing logic

pkg/controller/drain/drain_controller.go
Ensure the node passed to RunCordonOrUncordon comes from the latest updated state
Trigger a node cordon/uncordon, when the first node's cordon/uncordon request failed, RunCordonOrUncordon will skip invoke PatchOrReplaceWithContext and return nil, the MCC will hangs to wait.
With this code, MCC will work as excepted.
CordonHelper.PatchOrReplaceWithContext() will always set the node's Unschedulable state to desired, even if the PATCH/UPDATE request failed
=> OCPBUGS-62341: Ensure the node passed to RunCordonOrUncordon comes from the latest updated state

cmd/machine-config-controller/start.go, pkg/controller/certrotation/certrotation_controller.go, pkg/controller/certrotation/certrotation_controller_test.go, pkg/controller/certrotation/dynamic_serving.go, pkg/controller/certrotation/hostnames.go
This takes inspiration from https://github.com/openshift/cluster-kube-apiserver-operator/blob/main/pkg/operator/certrotationcontroller/dynamic_serving.go. I did not want to vendor a whole package for that type, but most of the mechanism is similar to that; with a few adjustments for it to work with the MCO's cert controller. I also added a unit test for this particular case. 
I also chose not to listen on the ARO resource, although I can include it if requested. Since we want to eventually move from vendoring non openshift API, I figured it wasn't worth plumbing that through. 
**How to verify:**
Existing cert rotation mechanisms should remain unchanged. The easiest way to verify this is that installs and upgrades to this PR should be able to successfully scale up nodes. Examining the cert …
=> OCPBUGS-59968: Cert Controller should live fetch SAN IPs during cert rotation

install/0000_90_machine-config_01_prometheus-rules.yaml, pkg/daemon/daemon.go, pkg/daemon/metrics.go
-->
Removed the MissingMachineConfig Alert , metric gauge, and related code.
Due to the work done in
https://github.com/openshift/machine-config-operator/pull/4594
and the fix having been backported to 4.16
https://github.com/openshift/machine-config-operator/pull/4655
It is defunct and can no longer fire 
1. Build openshift cluster with image
2.  Check prometheusrules for machine-config-daemon and see alert is no longer present. Due to previous commits the alert no longer functioned anyways. 
$ oc get prometheusrule machine-config-daemon -o yaml
Removed the MissingMachineConfig Alert from PrometheusRules as it can no longer fire.
=> MCO-1844: Remove MissingMachineConfig Alert

templates/master/00-master/two-node-with-fencing/files/fencing-validator.yaml
- What I did
Added a new MachineConfig template file under templates/master/00-master/two-node-with-fencing/files/ that installs the fencing_validator.sh script to /usr/local/bin/ on control-plane nodes for Two-Node Fencing clusters.
Deploy a Two-Node Fencing cluster.
Verify the MachineConfig for masters includes the new file.
On a master node, run:
oc debug node/<master> -- chroot /host ls -l /usr/local/bin/fencing_validator
oc debug node/<master> -- chroot /host /usr/local/bin/fencing_validator --help
copy it into the hypervisor:
oc debug node/<master> -- chroot /host cat /usr/local/bin/fencing_validator > fencing_validator
chmod +x fencing_validator
The script should be present, executable (0755), and runnable.
Ship …
=> OCPEDGE-2188: embed fencing validator into TNF MCO

pkg/controller/container-runtime-config/container_runtime_config_controller.go, pkg/controller/container-runtime-config/container_runtime_config_controller_test.go, pkg/controller/kubelet-config/kubelet_config_controller.go, pkg/controller/kubelet-config/kubelet_config_controller_test.go, pkg/controller/kubelet-config/kubelet_config_features_test.go
This is an manual cherry-pick of https://github.com/openshift/machine-config-operator/pull/5259
/assign RishabhSaini
=> [release-4.19] OCPBUGS-61738: Recheck generatedByControllerVersion annotation prior to deleting a degraded MC
